🌐Add Polish translation for `docs/pl/docs/help-fastapi.md`
fastapi/fastapi pull request #10121
Opened 2023-08-20 12:35 UTC by romabozhanovgithub

Relates to https://github.com/tiangolo/fastapi/discussions/9195

This PR is a translation of docs/pl/docs/help-fastapi.md

This is my first PR to this repository. I would appreciate a code review. Please let me know if it has any problems.

2023-08-20 12:53 UTC, tiangolo commented
📝 Docs preview for commit 679878ab3fc9f77e34afe2a2ceea4b11f836c7b3 at: https://1e5494a5.fastapitiangolo.pages.dev

2023-08-31 20:03 UTC, isulim requested changes
Most of translation is ok, but I have some suggestions.

Większość tłumaczenia jest ok, ale mam trochę propozycji.

2023-08-31 20:03 UTC, isulim commented on docs/pl/docs/help-fastapi.md
> +Z drugiej strony w systemach czatu jest tysiące użytkowników, więc jest duża szansa, że znajdziesz tam kogoś do rozmowy, prawie cały czas. 😄
```suggestion
Z drugiej strony w systemach czatu są tysiące użytkowników, więc jest duża szansa, że znajdziesz tam kogoś do rozmowy, prawie w każdej chwili. 😄
```

2023-08-31 21:03 UTC, romabozhanovgithub commented
@isulim Thanks for you review, really appreciate

2023-08-31 21:25 UTC, tiangolo commented
📝 Docs preview for commit 026faf5b27f2a788b4dea303093ca91c30ed6ceb at: https://fc058b53.fastapitiangolo.pages.dev

2023-08-31 22:01 UTC, isulim approved these changes

2023-08-31 22:07 UTC, isulim commented
Hello @tiangolo 
Why does smokeshow/coverage fail on file `tests/test_openapi_examples.py`?
I never changed this file.

2023-08-31 22:22 UTC, romabozhanovgithub commented
> Hello @tiangolo Why does smokeshow/coverage fail on file `tests/test_openapi_examples.py`? I never changed this file.

Same here

2023-09-01 22:16 UTC, tiangolo commented
It seems it was a line in a dummy test I left uncovered and I probably didn't notice while Smokeshow was having errors. But now I added it, and updating the branch here should solve it. 🤓

2023-09-01 22:24 UTC, tiangolo commented
📝 Docs preview for commit 5c4fcabcdf9a38e4599f365a4fa0cf473c1c981f at: https://ae496c77.fastapitiangolo.pages.dev

2023-09-07 10:20 UTC, bluefish6 requested changes

2023-09-07 10:20 UTC, bluefish6 commented on docs/pl/docs/help-fastapi.md
> +* Jest też duża szansa, że pull request nie jest tak naprawdę potrzebny, ponieważ problem można rozwiązać w **inny sposób**. Wtedy możesz to zasugerować lub o to zapytać.
```suggestion
* Jest też duża szansa, że pull request nie jest konieczny, ponieważ problem można rozwiązać w **inny sposób**. Wtedy możesz to zasugerować lub o to zapytać.
```

2023-09-07 10:20 UTC, bluefish6 commented on docs/pl/docs/help-fastapi.md
> +* Nie martw się zbytnio rzeczami takimi jak style wiadomości commitów, scalę i połączę je ręcznie, dostosowując commit.
```suggestion
* Nie przejmuj się zbytnio rzeczami takimi jak style wiadomości commitów, przy wcielaniu pull requesta łączę commity i modyfikuję opis sumarycznego commita ręcznie.
```

2023-09-07 10:20 UTC, bluefish6 commented on docs/pl/docs/help-fastapi.md
> +* Nie martw się również zasadami stylu, istnieją już zautomatyzowane narzędzia sprawdzające to.
```suggestion
* Nie przejmuj się również stylem kodu, automatyczne narzędzia w repozytorium sprawdzają to samodzielnie.
```

2023-09-07 10:20 UTC, bluefish6 commented on docs/pl/docs/help-fastapi.md
> +A jeśli istnieje jakaś inna potrzeba dotycząca stylu lub spójności, poproszę bezpośrednio o to, lub dodam commity z potrzebnymi zmianami.
```suggestion
A jeśli istnieje jakaś konkretna potrzeba dotycząca stylu lub spójności, sam poproszę o zmiany lub dodam commity z takimi zmianami.
```

2023-09-07 10:20 UTC, bluefish6 commented on docs/pl/docs/help-fastapi.md
> +* Sprawdź i przeczytaj kod, zobacz, czy ma sens, **uruchom go lokalnie** i zobacz, czy faktycznie rozwiązuje problem.
```suggestion
* Przeczytaj kod, zastanów się czy ma sens, **uruchom go lokalnie** i potwierdź czy faktycznie rozwiązuje problem.
```

2023-09-07 10:20 UTC, bluefish6 commented on docs/pl/docs/help-fastapi.md
> +* Następnie **skomentuj**, mówiąc, że to zrobiłeś, dzięki temu będę wiedział, że naprawdę to sprawdziłeś.
```suggestion
* Następnie dodaj **komentarz** z informacją o tym, że sprawdziłeś kod, dzięki temu będę miał pewność, że faktycznie go sprawdziłeś.
```

2023-09-07 10:20 UTC, bluefish6 commented on docs/pl/docs/help-fastapi.md
> +    Niestety, nie mogę po prostu ufać PR-om, które mają kilka zatwierdzeń.
```suggestion
    Niestety, nie mogę ślepo ufać PR-om, nawet jeśli mają kilka zatwierdzeń.
```

2023-09-07 10:20 UTC, bluefish6 commented on docs/pl/docs/help-fastapi.md
> +    Kilka razy zdarzyło się, że są PR-y z 3, 5 lub więcej zatwierdzeniami, prawdopodobnie dlatego, że opis jest interesujący, ale gdy sprawdzam PR-y, są one w rzeczywistości uszkodzone, mają błąd lub
```suggestion
    Kilka razy zdarzyło się, że PR-y miały 3, 5 lub więcej zatwierdzeń (prawdopodobnie dlatego, że opis obiecuje rozwiązanie ważnego problemu), ale gdy sam sprawdziłem danego PR-a, okazał się być zbugowany lub nie rozwiązywał problemu, który rzekomo miał rozwiązywać. 😅
```

2023-09-07 10:20 UTC, bluefish6 commented on docs/pl/docs/help-fastapi.md
> +    Dlatego naprawdę ważne jest, abyś faktycznie przeczytał i uruchomił kod oraz dał mi znać w komentarzach, że to zrobiłeś. 🤓
```suggestion
    Dlatego tak ważne jest, abyś faktycznie przeczytał i uruchomił kod oraz napisał w komentarzu, że to zrobiłeś. 🤓
```

2023-09-07 10:20 UTC, bluefish6 commented on docs/pl/docs/help-fastapi.md
> +* Jeśli PR można uprościć w jakiś sposób, możesz o to poprosić, ale nie ma potrzeby być zbyt wybrednym, może być wiele subiektywnych punktów widzenia (a ja też będę miał swoje 🙈), więc lepiej, jeśli
```suggestion
* Jeśli PR można uprościć w jakiś sposób, możesz o to poprosić, ale nie ma potrzeby być zbyt wybrednym, może być wiele subiektywnych punktów widzenia (a ja też będę miał swój 🙈), więc lepiej żebyś skupił się na kluczowych rzeczach.
```

2023-09-07 10:20 UTC, bluefish6 commented on docs/pl/docs/help-fastapi.md
> +    * Możesz również pomóc w recenzji tłumaczeń stworzonych przez innych.
```suggestion
    * Możesz również pomóc w weryfikacji tłumaczeń stworzonych przez innych.
```

2023-09-07 10:20 UTC, bluefish6 commented on docs/pl/docs/help-fastapi.md
> +* [Pomóc innym z pytaniami na GitHubie](#help-others-with-questions-in-github){.internal-link target=_blank} (zobacz powyższą sekcję).
```suggestion
* [Pomóc innym z pytaniami na GitHubie](#help-others-with-questions-in-github){.internal-link target=_blank} (zobacz sekcję powyżej).
```

2023-09-07 10:20 UTC, bluefish6 commented on docs/pl/docs/help-fastapi.md
> +* [Oceniać Pull Requesty](#review-pull-requests){.internal-link target=_blank} (zobacz powyższą sekcję).
```suggestion
* [Oceniać Pull Requesty](#review-pull-requests){.internal-link target=_blank} (zobacz sekcję powyżej).
```

2023-09-07 10:20 UTC, bluefish6 commented on docs/pl/docs/help-fastapi.md
> +Jeśli możesz mi w tym pomóc, **pomagasz mi utrzymać FastAPI** i upewnić się, że nadal **rozwija się szybciej i lepiej**. 🚀
```suggestion
Jeśli możesz mi w tym pomóc, **pomożesz mi utrzymać FastAPI** i zapewnisz że będzie **rozwijać się szybciej i lepiej**. 🚀
```

2023-09-07 10:22 UTC, bluefish6 commented on docs/pl/docs/help-fastapi.md
> +Na GitHubie szablon poprowadzi Cię do napisania odpowiedniego pytania, dzięki czemu łatwiej uzyskasz dobrą odpowiedź, a nawet rozwiążesz problem samodzielnie, zanim zapytasz. Pondato na GitHubie mogę
```suggestion
Na GitHubie szablon poprowadzi Cię do napisania odpowiedniego pytania, dzięki czemu łatwiej uzyskasz dobrą odpowiedź, a nawet rozwiążesz problem samodzielnie, zanim zapytasz. Ponadto na GitHubie mogę się upewnić, że zawsze odpowiadam na wszystko, nawet jeśli zajmuje to trochę czasu. Osobiście nie mogę tego zrobić z systemami czatu. 😅
```

2023-09-08 20:24 UTC, romabozhanovgithub commented
@isulim @bluefish6 Thanks for your review and suggestions!

2023-09-10 15:02 UTC, bluefish6 approved these changes
:+1:

2023-09-10 17:01 UTC, tiangolo commented
📝 Docs preview for commit 6788ebc57082506be903ded2970aec2fa64bdb39 at: https://e8b63855.fastapitiangolo.pages.dev

2023-09-10 17:16 UTC, romabozhanovgithub commented
@tiangolo Looks like we have 2 approves there

2023-09-17 21:19 UTC, tiangolo commented
📝 Docs preview for commit 2d2e7118091427640281bf3c189ac92f482f2d03 at: https://17f45cfb.fastapitiangolo.pages.dev

2023-09-22 23:38 UTC, tiangolo commented
Thanks @romabozhanovgithub! 🙇 

And thanks for the reviews @bluefish6 and @isulim 🍰

2023-09-22 23:38 UTC, merged