Translate header-params to Russian lang
fastapi/fastapi pull request #10226
Opened 2023-09-10 07:51 UTC by AlertRED

Already exist request for this translation https://github.com/tiangolo/fastapi/pull/3783
But it got stuck for reasons I don't understand. Just I try to do again, if this is unnecessary, tell it.

2023-09-10 09:28 UTC, AGolicyn requested changes

2023-09-10 09:28 UTC, AGolicyn commented on docs/ru/docs/tutorial/header-params.md
> +    Чтобы объявить заголовки, вам нужно использовать `Header`, потому что в противном случае параметры были бы интерпретированы как query-параметры.
```suggestion
    Чтобы объявить заголовки, важно использовать `Header`, потому что в противном случае параметры интерпретируются как query-параметры.
```
Хочется как-то избавиться от "были бы")).

2023-09-10 16:37 UTC, tiangolo commented
📝 Docs preview for commit 23237c9cf913fa0128dc8ccd34bbb770ec97bb7c at: https://656962e5.fastapitiangolo.pages.dev

2023-09-10 17:09 UTC, AGolicyn approved these changes

2023-09-12 06:07 UTC, tiangolo commented
📝 Docs preview for commit 7e66873eaf358b418c9f62e5a0ad2425d4a6d961 at: https://940a1fdb.fastapitiangolo.pages.dev

2023-09-14 20:23 UTC, eVery1337 requested changes

2023-09-14 20:23 UTC, eVery1337 commented on docs/ru/docs/tutorial/header-params.md
> +!!! Внимание
```suggestion
!!! warning "Внимание"
```
Опять же в оригинале другой бокс.

2023-09-14 20:23 UTC, eVery1337 commented on docs/ru/docs/tutorial/header-params.md
> +Есть возможность получать повторяющиеся заголовки. Это означает один и тот же заголовок с множеством значений.
```suggestion
Есть возможность получать несколько заголовков с одним и тем же именем, но разными значениями.
```
В таком варианте перевода смысл кажется более понятным, на мой взгляд.

2023-09-14 20:23 UTC, eVery1337 commented on docs/ru/docs/tutorial/header-params.md
> +        Prefer to use the `Annotated` version if possible.
```suggestion
    !!! tip "Подсказка"
        Предпочтительнее использовать версию с аннотацией, если это возможно.
```

2023-09-14 20:23 UTC, eVery1337 commented on docs/ru/docs/tutorial/header-params.md
> +        Prefer to use the `Annotated` version if possible.
```suggestion
    !!! tip "Подсказка"
        Предпочтительнее использовать версию с аннотацией, если это возможно.
```

2023-09-14 20:23 UTC, eVery1337 commented on docs/ru/docs/tutorial/header-params.md
> +        Prefer to use the `Annotated` version if possible.
```suggestion
    !!! tip "Подсказка"
        Предпочтительнее использовать версию с аннотацией, если это возможно.
```

2023-09-14 20:23 UTC, eVery1337 commented on docs/ru/docs/tutorial/header-params.md
> +        Prefer to use the `Annotated` version if possible.
```suggestion
    !!! tip "Подсказка"
        Предпочтительнее использовать версию с аннотацией, если это возможно.
```

2023-09-14 20:23 UTC, eVery1337 commented on docs/ru/docs/tutorial/header-params.md
> +        Prefer to use the `Annotated` version if possible.
```suggestion
    !!! tip "Подсказка"
        Предпочтительнее использовать версию с аннотацией, если это возможно.
```

2023-09-14 20:23 UTC, eVery1337 commented on docs/ru/docs/tutorial/header-params.md
> +        Prefer to use the `Annotated` version if possible.
```suggestion
    !!! tip "Подсказка"
        Предпочтительнее использовать версию с аннотацией, если это возможно.
```

2023-09-14 20:23 UTC, eVery1337 commented on docs/ru/docs/tutorial/header-params.md
> +        Prefer to use the `Annotated` version if possible.
```suggestion
    !!! tip "Подсказка"
        Предпочтительнее использовать версию с аннотацией, если это возможно.
```

2023-09-14 20:23 UTC, eVery1337 commented on docs/ru/docs/tutorial/header-params.md
> +        Prefer to use the `Annotated` version if possible.
```suggestion
    !!! tip "Подсказка"
        Предпочтительнее использовать версию с аннотацией, если это возможно.
```

2023-09-14 20:23 UTC, eVery1337 commented on docs/ru/docs/tutorial/header-params.md
> +        Prefer to use the `Annotated` version if possible.
```suggestion
    !!! tip "Подсказка"
        Предпочтительнее использовать версию с аннотацией, если это возможно.
```

2023-09-15 12:40 UTC, AlertRED commented on docs/ru/docs/tutorial/header-params.md
> +# Header-параметры
Я, если что, отталкивался от ранее переведенных пунктов меню: "Path-параметры", "Query-параметры".

2023-09-15 13:09 UTC, tiangolo commented
📝 Docs preview for commit 298019982c019f15fbbc3133d976b58cb46bb4d4 at: https://c5c51197.fastapitiangolo.pages.dev

2023-09-15 13:12 UTC, eVery1337 commented on docs/ru/docs/tutorial/header-params.md
> +# Header-параметры
Ну ок, для общей картины и правда лучше оставить.

2023-09-15 13:28 UTC, tiangolo commented
📝 Docs preview for commit 3277e7669ac453213fd1c9d029481459635e763c at: https://0639725b.fastapitiangolo.pages.dev

2023-09-15 13:34 UTC, eVery1337 approved these changes

2023-09-15 14:06 UTC, eVery1337 approved these changes

2023-09-20 16:16 UTC, AlertRED commented
@Kludex Could you tell me, please, should I do something else to promote this pullrequest? I would like to add a translation of other pages, but I see that this pullrequest has not been merged yet. I don't want my work to be in vain.

2023-09-22 23:36 UTC, tiangolo commented
Thanks @AlertRED! 🙇 

And thanks for the reviews @eVery1337 and @AGolicyn ☕

2023-09-22 23:37 UTC, merged