🌐 Add Chinese translation for `docs/zh/docs/deployment/https.md`
fastapi/fastapi pull request #10277
Opened 2023-09-19 19:28 UTC by xzmeng

2023-09-19 19:42 UTC, tiangolo commented
📝 Docs preview for commit e69c5c1090fc79acd6c2f66abd2947210752f9f5 at: https://759ff0cb.fastapitiangolo.pages.dev

2023-09-20 19:52 UTC, shamosishen requested changes

2023-09-20 19:52 UTC, shamosishen commented on docs/zh/docs/deployment/https.md
> +要从顾客的角度**了解 HTTPS 的基础知识**，请查看 <a href="https://howhttps.works/" class="external-link" target="_blank">https://howhttps.works/</a>。
```suggestion
要从用户的角度**了解 HTTPS 的基础知识**，请查看 <a href="https://howhttps.works/" class="external-link" target="_blank">https://howhttps.works/</a>。
```

2023-09-20 19:52 UTC, shamosishen commented on docs/zh/docs/deployment/https.md
> +* 连接加密发生在 **TCP 层**。
```suggestion
* 连接的加密发生在 **TCP 层**。
```

2023-09-20 19:52 UTC, shamosishen commented on docs/zh/docs/deployment/https.md
> +* **TCP 不知道“域(domains)”**。 仅仅知道 IP 地址。
```suggestion
* **TCP 不知道“域(domain)”**。 仅仅知道 IP 地址。
```

2023-09-20 19:52 UTC, shamosishen commented on docs/zh/docs/deployment/https.md
> +* **TLS** 协议（在 HTTP 之下的TCP 层处理加密的协议）有一个**扩展**，称为 **<a href="https://en.wikipedia.org/wiki/ Server_Name_Induction" class="external-link" target="_blank"><abbr title="服务器名称指示">SNI</abbr></a>**。
```suggestion
* **TLS** 协议（在 HTTP 之下的TCP 层处理加密的协议）有一个**扩展**，称为 **<a href="https://en.wikipedia.org/wiki/ Server_Name_Indication" class="external-link" target="_blank"><abbr title="服务器名称指示">SNI</abbr></a>**。
```

2023-09-20 19:52 UTC, shamosishen commented on docs/zh/docs/deployment/https.md
> +* nginx
```suggestion
* Nginx
```

2023-09-20 20:22 UTC, tiangolo commented
📝 Docs preview for commit faca68b3bce85df63a1a6987a2bf9c843fc6479b at: https://ef1bebd9.fastapitiangolo.pages.dev

2023-09-24 02:05 UTC, socket-socket requested changes

2023-09-24 02:05 UTC, socket-socket commented on docs/zh/docs/deployment/https.md
> +在设置所有内容时，您可能只会在第一次时执行此操作一次。
change

2023-09-24 02:05 UTC, socket-socket commented on docs/zh/docs/deployment/https.md
> +     域名早于 HTTPS，但由于一切都依赖于域和 IP 地址，因此值得在此提及。
change

2023-09-24 02:12 UTC, socket-socket commented
”域“和”域名“是否是相同的？

2023-09-24 02:14 UTC, tiangolo commented
📝 Docs preview for commit 14dd7ca9f68d9d71427054fba54dc0b298d4aff8 at: https://34e98a81.fastapitiangolo.pages.dev

2023-09-28 11:55 UTC, tiangolo commented
📝 Docs preview for commit a60bb0411bbb0160cd1dda9a6032282729ec1955 at: https://11667024.fastapitiangolo.pages.dev

2023-09-28 12:01 UTC, socket-socket approved these changes

2023-09-28 12:01 UTC, socket-socket commented on docs/zh/docs/deployment/https.md
> +     * SNI 扩展允许一台服务器（具有 **单个 IP 地址**）拥有 **多个 HTTPS 证书** 并提供 **多个 HTTPS 域/应用程序**。
```suggestion
     * SNI 扩展允许一台服务器（具有 **单个 IP 地址**）拥有 **多个 HTTPS 证书** 并提供 **多个 HTTPS 域名/应用程序**。
```

2023-09-28 12:01 UTC, socket-socket commented on docs/zh/docs/deployment/https.md
> +因此，要更新证书，更新程序需要向权威机构（Let's Encrypt）**证明**它确实**“拥有”并控制该域**。
```suggestion
因此，要更新证书，更新程序需要向权威机构（Let's Encrypt）**证明**它确实**“拥有”并控制该域名**。
```

2023-09-28 12:01 UTC, socket-socket commented on docs/zh/docs/deployment/https.md
> +TLS 终止代理将使用协商好的加密算法**解密请求**，并将**（解密的）HTTP 请求**传输到运行应用程序的进程（例如运行 FastAPI 应用的 Uvicorn 进程） 。
```suggestion
TLS 终止代理将使用协商好的加密算法**解密请求**，并将**（解密的）HTTP 请求**传输到运行应用程序的进程（例如运行 FastAPI 应用的 Uvicorn 进程）。
```

2023-09-28 12:05 UTC, shamosishen approved these changes

2023-09-28 12:07 UTC, tiangolo commented
📝 Docs preview for commit 9c581bb08adf64b522d0d5e11f5b0cedc34d7b04 at: https://e06746b4.fastapitiangolo.pages.dev

2024-01-09 02:25 UTC, Aruelius approved these changes

2024-01-09 15:38 UTC, tiangolo commented
Thank you @xzmeng! 🍰 

And thanks for the reviews! @shamosishen, @Aruelius, @socket-socket 🙇

2024-01-09 15:38 UTC, merged