🌐 Add Chinese translation for `docs/zh/docs/deployment/manually.md`
fastapi/fastapi pull request #10279
Opened 2023-09-19 21:34 UTC by xzmeng

2023-09-19 21:42 UTC, tiangolo commented
📝 Docs preview for commit 2352428947bde0f1b64fd8e362905079a77ad9f7 at: https://a2cb7b7a.fastapitiangolo.pages.dev

2023-09-20 21:11 UTC, shamosishen requested changes

2023-09-20 21:11 UTC, shamosishen commented on docs/zh/docs/deployment/manually.md
> +         通过添加“标准”，Uvicorn 将安装并使用一些推荐的额外依赖项。
```suggestion

         通过添加`standard`，Uvicorn 将安装并使用一些推荐的额外依赖项。
```

2023-09-20 21:11 UTC, shamosishen commented on docs/zh/docs/deployment/manually.md
> +您可以按照教程中的相同方式运行应用程序，但不使用`--reload`选项，例如：
```suggestion
您可以按照之前教程中的相同方式运行应用程序，但不使用`--reload`选项，例如：
```

2023-09-20 21:30 UTC, tiangolo commented
📝 Docs preview for commit 4f7a3e058a3ff7376025a8eb4f1bb59ca88e830d at: https://6ca64508.fastapitiangolo.pages.dev

2023-09-20 21:37 UTC, shamosishen commented
A tip is rendered incorrectly, can you check it out ?

2023-09-20 21:46 UTC, tiangolo commented
📝 Docs preview for commit 5eb4e84b899a16361fa49dd3f8c3255e51deeb01 at: https://f8cffb41.fastapitiangolo.pages.dev

2023-09-20 22:12 UTC, tiangolo commented
📝 Docs preview for commit 085ac494dba19373e66677ebfff233024474d260 at: https://40693db6.fastapitiangolo.pages.dev

2023-09-20 22:58 UTC, xzmeng commented
fixed

2023-09-28 12:13 UTC, shamosishen approved these changes

2023-09-28 12:13 UTC, shamosishen commented on docs/zh/docs/deployment/manually.md
> +尽管如此，Uvicorn 目前仅与 asyncio 兼容，并且通常使用 <a href="https://github.com/MagicStack/uvloop" class="external-link" target="_blank">`uvloop`</a >,`asyncio`的高性能替代品。
```suggestion
尽管如此，Uvicorn 目前仅与 asyncio 兼容，并且通常使用 <a href="https://github.com/MagicStack/uvloop" class="external-link" target="_blank">`uvloop`</a >, 它是`asyncio`的高性能替代品。
```

2023-09-28 12:19 UTC, tiangolo commented
📝 Docs preview for commit 9a01d9248b695e780ff514f98cc7d6d536808e7d at: https://332759d7.fastapitiangolo.pages.dev

2024-01-09 02:25 UTC, Aruelius approved these changes

2024-01-09 15:39 UTC, tiangolo commented
Thank you! @xzmeng 🍰 

And thanks for the reviews @shamosishen, @Aruelius! ☕

2024-01-09 15:39 UTC, merged