🌐 Add Chinese translation for `docs/zh/docs/deployment/index.md`
fastapi/fastapi pull request #10276
Opened 2023-09-19 19:28 UTC by xzmeng

2023-09-19 19:41 UTC, tiangolo commented
📝 Docs preview for commit 754d4ff20b27678b80449936f9aa8a2a28933476 at: https://c29b0395.fastapitiangolo.pages.dev

2023-09-20 10:23 UTC, shamosishen requested changes
修改一些与原文不一致的地方

2023-09-20 10:23 UTC, shamosishen commented on docs/zh/docs/deployment/versions.md
> +这就是为什么当前版本仍然是“0.x.x”，这反映出每个版本都可能有Breaking changes。 这遵循<a href="https://semver.org/" class="external-link" target="_blank">语义版本控制</a>的约定。
```suggestion
这就是为什么当前版本仍然是`0.x.x`，这反映出每个版本都可能有Breaking changes。 这遵循<a href="https://semver.org/" class="external-link" target="_blank">语义版本控制</a>的约定。
```

2023-09-20 10:23 UTC, shamosishen commented on docs/zh/docs/deployment/versions.md
> +如果你使用“requirements.txt”文件，你可以使用以下命令指定版本：
```suggestion
如果你使用`requirements.txt`文件，你可以使用以下命令指定版本：
```

2023-09-20 10:23 UTC, shamosishen commented on docs/zh/docs/deployment/versions.md
> +如果一切正常，或者在进行必要的更改之后，并且所有测试都通过了，那么你可以将“fastapi”固定到新的版本。
```suggestion
如果一切正常，或者在进行必要的更改之后，并且所有测试都通过了，那么你可以将`fastapi`固定到新的版本。
```

2023-09-20 10:23 UTC, shamosishen commented on docs/zh/docs/deployment/versions.md
> +Pydantic 包含针对 **FastAPI** 的测试及其自己的测试，因此 Pydantic 的新版本（“1.0.0”以上）始终与 FastAPI 兼容。
```suggestion
Pydantic 包含针对 **FastAPI** 的测试及其自己的测试，因此 Pydantic 的新版本（`1.0.0`以上）始终与 FastAPI 兼容。
```

2023-09-20 10:34 UTC, tiangolo commented
📝 Docs preview for commit 029665811697a3c211dd71f0b0ad7a21007438c1 at: https://70291246.fastapitiangolo.pages.dev

2023-09-20 19:34 UTC, shamosishen approved these changes

2023-09-22 11:35 UTC, wdh99 approved these changes

2023-09-22 23:30 UTC, tiangolo commented
Great, thanks @xzmeng! 🙇 

And thanks for the reviews @shamosishen and @wdh99 🍰

2023-09-22 23:30 UTC, merged