🌐 Add Chinese translation for `docs/zh/docs/deployment/index.md`
fastapi/fastapi pull request #10275
Opened 2023-09-19 19:27 UTC by xzmeng

Some people have translated these parts before, but due to the fact that the original contributors has been inactive for a long time, I am going to re-translate this series of articles.

2023-09-19 19:41 UTC, tiangolo commented
📝 Docs preview for commit 5af5a97f084ec1187a16dfd742a86cb035eb9c3b at: https://d58294e6.fastapitiangolo.pages.dev

2023-09-19 22:47 UTC, xzmeng commented
@mkdir700  @funny-cat-happy @wdh99 @Royc30ne @ Sefank Would anyone like to review these ?

2023-09-20 11:13 UTC, wdh99 requested changes

2023-09-20 11:13 UTC, wdh99 commented on docs/zh/docs/deployment/index.md
> +根据你的具体用例和使用的工具，有多种方法可以实现此目的。
```suggestion
根据你的使用场景和使用的工具，有多种方法可以实现此目的。
```

2023-09-20 11:13 UTC, wdh99 commented on docs/zh/docs/deployment/index.md
> +你可以使用工具组合自行**部署服务器**，你也可以使用为你完成部分工作的**云服务**，或其他可能的选项。
```suggestion
你可以使用一些工具自行**部署服务器**，你也可以使用能为你完成部分工作的**云服务**，或其他可能的选项。
```

2023-09-20 19:11 UTC, tiangolo commented
📝 Docs preview for commit 6137dafe9983af61bd6ab5674002abc7761558ab at: https://aeab451f.fastapitiangolo.pages.dev

2023-09-21 10:59 UTC, wdh99 approved these changes

2023-09-28 11:55 UTC, socket-socket approved these changes

2023-12-03 13:29 UTC, HiemalBeryl approved these changes

2024-01-09 02:31 UTC, Aruelius approved these changes

2024-01-09 02:31 UTC, Aruelius commented on docs/zh/docs/deployment/index.md
> +对于**Web API**来说，通常涉及将上传到**云服务器**中，搭配一个性能和稳定性都不错的**服务器程序**，以便你的**用户**可以高效地**访问**你的应用程序，而不会出现中断或其他问题。
建议对英文字母加上前后空格，和下面的 `FastAPI` 一样
```suggestion
对于 **Web API** 来说，通常涉及将上传到**云服务器**中，搭配一个性能和稳定性都不错的**服务器程序**，以便你的**用户**可以高效地**访问**你的应用程序，而不会出现中断或其他问题。
```

2024-01-09 15:37 UTC, tiangolo commented
Thanks @xzmeng! 🙇 

And thanks for the reviews @Aruelius, @HiemalBeryl, @wdh99, @socket-socket 🚀

2024-01-09 15:37 UTC, merged