🌐 Add Chinese translation for `docs/zh/docs/deployment/concepts.md`
fastapi/fastapi pull request #10282
Opened 2023-09-19 22:32 UTC by xzmeng

2023-09-20 21:28 UTC, tiangolo commented
📝 Docs preview for commit 47abc02e26346c60678e8eea723af85de8a8b08a at: https://a19f2068.fastapitiangolo.pages.dev

2023-09-21 17:38 UTC, socket-socket requested changes

2023-09-21 17:38 UTC, socket-socket commented on docs/zh/docs/deployment/concepts.md
> +在部署 **FastAPI** 应用程序或实际上任何类型的 Web API 时，您可能会关心几个概念，使用它们您可以找到**最合适的**方法来**部署您的应用程序**。
```suggestion
在部署 **FastAPI** 应用程序或任何类型的 Web API 时，有几个概念值得了解，通过掌握这些概念您可以找到**最合适的**方法来**部署您的应用程序**。
```

2023-09-21 17:38 UTC, socket-socket commented on docs/zh/docs/deployment/concepts.md
> +我们将了解它们将如何影响**部署**。
```suggestion
我们接下来了解它们将如何影响**部署**。
```

2023-09-21 17:38 UTC, socket-socket commented on docs/zh/docs/deployment/concepts.md
> +最后，最终目标是能够以**安全**的方式**为您的 API 客户端**提供服务，**避免中断**，并尽可能高效地使用**计算资源**（ 例如远程服务器/虚拟机）。 🚀
```suggestion
我们的最终目标是能够以**安全**的方式**为您的 API 客户端**提供服务，同时要**避免中断**，并且尽可能高效地利用**计算资源**（ 例如服务器CPU资源）。 🚀
```

2023-09-22 02:10 UTC, tiangolo commented
📝 Docs preview for commit 758204d0808cd360c466de2cd7e57d9d8c1b1e22 at: https://8dd1d228.fastapitiangolo.pages.dev

2024-01-31 14:22 UTC, alejsdev commented
Thanks for your interest! @xzmeng 

Do you think this is ready to merge now with the suggested changes? Please let me know @socket-socket 🤓

2024-02-01 02:55 UTC, socket-socket commented
@alejsdev It's good!

2024-02-01 02:56 UTC, socket-socket approved these changes

2024-02-01 03:04 UTC, socket-socket approved these changes

2024-02-01 03:04 UTC, socket-socket commented on docs/zh/docs/deployment/concepts.md
> +＃＃ 资源利用率
```suggestion
## 资源利用率
```

2024-02-01 03:12 UTC, tiangolo commented
📝 Docs preview for commit d1a3b0d6bfd9ba0757c78d265e62df1777e2350f at: https://d0b5d225.fastapitiangolo.pages.dev

2024-02-01 08:56 UTC, merged

2024-02-01 08:58 UTC, alejsdev commented
Thank you for the help! @xzmeng 🤓 

And thanks for the review @socket-socket 🚀