🌐 Add Chinese translation for `docs/zh/docs/deployment/docker.md`
fastapi/fastapi pull request #10296
Opened 2023-09-20 23:31 UTC by xzmeng

2023-09-20 23:38 UTC, tiangolo commented
📝 Docs preview for commit 2626f65623dfaf48b6520acfba6faaa7119335c7 at: https://60549044.fastapitiangolo.pages.dev

2023-09-21 17:27 UTC, socket-socket requested changes

2023-09-21 17:27 UTC, socket-socket commented on docs/zh/docs/deployment/docker.md
> +    很着急并且已经知道这些东西了？ 跳转到下面的 [`Dockerfile` 👇](#build-a-docker-image-for-fastapi)。
链接无法跳转

2023-09-21 17:27 UTC, socket-socket commented on docs/zh/docs/deployment/docker.md
> +    很着急并且已经知道这些东西了？ 跳转到下面的 [`Dockerfile` 👇](#build-a-docker-image-for-fastapi)。
```suggestion
    赶时间并且已经知道这些东西了？ 跳转到下面的 [`Dockerfile` 👇](#为-fastapi-构建-docker-镜像)。
```

2023-09-21 17:27 UTC, socket-socket commented on docs/zh/docs/deployment/docker.md
> +容器（主要是 Linux 容器）是一种非常**轻量级**的打包应用程序的方式，包括其所有依赖项和必要的文件，同时使它们与同一系统中的其他容器（其他应用程序或组件）隔离。
```suggestion
容器（主要是 Linux 容器）是一种非常**轻量级**的打包应用程序的方式，其包括所有依赖项和必要的文件，同时它们可以和同一系统中的其他容器（或者其他应用程序/组件）相互隔离。
```

2023-09-21 17:27 UTC, socket-socket commented on docs/zh/docs/deployment/docker.md
> +Linux 容器使用主机（机器、虚拟机、云服务器等）的相同 Linux 内核运行。 这仅仅意味着它们非常轻量（与模拟整个操作系统的完整虚拟机相比）。
```suggestion
Linux 容器使用宿主机（如物理服务器、虚拟机、云服务器等）的Linux 内核运行。 这意味着它们非常轻量（与模拟整个操作系统的完整虚拟机相比）。
```

2023-09-21 17:27 UTC, socket-socket commented on docs/zh/docs/deployment/docker.md
> +这样，容器消耗**很少的资源**，与直接运行进程相当（虚拟机会消耗更多）。
```suggestion
通过这样的方式，容器消耗**很少的资源**，与直接运行进程相当（虚拟机会消耗更多）。
```

2023-09-21 17:27 UTC, socket-socket commented on docs/zh/docs/deployment/docker.md
> +容器还有自己的**隔离**运行进程（通常只有一个进程）、文件系统和网络，简化了部署、安全、开发等。
```suggestion
容器的进程（通常只有一个）、文件系统和网络都运行在隔离的环境，这简化了部署、安全、开发等。
```

2023-09-21 17:27 UTC, socket-socket commented on docs/zh/docs/deployment/docker.md
> +容器镜像是容器中应存在的所有文件、环境变量和默认命令/程序的**静态**版本。 **静态**这里的意思是容器**镜像**没有运行，没有被执行，只是打包的文件和元数据。
```suggestion
容器镜像是容器中文件、环境变量和默认命令/程序的**静态**版本。 **静态**这里的意思是容器**镜像**还没有运行，只是打包的文件和元数据。
```

2023-09-21 17:27 UTC, socket-socket commented on docs/zh/docs/deployment/docker.md
> +当**容器**启动并运行时（从**容器镜像**启动），它可以创建或更改文件、环境变量等。这些更改将仅存在于该容器中，但不会持久存在于底层中 容器镜像（不会保存到磁盘）。
```suggestion
当**容器**启动并运行时（从**容器镜像**启动），它可以创建或更改文件、环境变量等。这些更改将仅存在于该容器中，而不会持久化到底层的容器镜像中（不会保存到磁盘）。
```

2023-09-21 17:27 UTC, socket-socket commented on docs/zh/docs/deployment/docker.md
> +容器镜像相当于**程序**文件和内容，例如 `python` 和某些文件 `main.py`。
```suggestion
容器镜像相当于**程序**和文件，例如 `python`命令 和某些文件 如`main.py`。
```

2023-09-21 17:27 UTC, socket-socket commented on docs/zh/docs/deployment/docker.md
> +```
没有正确渲染

2023-09-21 17:27 UTC, socket-socket commented on docs/zh/docs/deployment/docker.md
> +```
没有正确渲染

2023-09-21 17:27 UTC, socket-socket commented on docs/zh/docs/deployment/docker.md
> +6. 设置**命令**来运行 `uvicorn` 服务器。
渲染错位

2023-09-22 02:13 UTC, tiangolo commented
📝 Docs preview for commit 6eccce5227b94475cd2431c0d7684f33effe5d9f at: https://908f6858.fastapitiangolo.pages.dev

2023-09-22 15:00 UTC, socket-socket requested changes

2023-09-22 15:00 UTC, socket-socket commented on docs/zh/docs/deployment/docker.md
> +     该文件仅存在于前一个阶段，这就是为什么我们使用 `--from-requirements-stage` 来复制它。
```suggestion
   该文件仅存在于前一个阶段，这就是为什么我们使用 `--from-requirements-stage` 来复制它。
```

2023-09-22 15:17 UTC, tiangolo commented
📝 Docs preview for commit 953ab49fd8657885ebe92c98836d3a562ac1ddbb at: https://ae37bcd7.fastapitiangolo.pages.dev

2023-09-22 15:20 UTC, xzmeng commented on docs/zh/docs/deployment/docker.md
> +   因为它使用 `./poetry.lock*` （以 `*` 结尾），所以如果该文件尚不可用，它不会崩溃。
```suggestion
     因为它使用 `./poetry.lock*` （以 `*` 结尾），所以如果该文件尚不可用，它不会崩溃。
```

2023-09-22 15:20 UTC, xzmeng commented on docs/zh/docs/deployment/docker.md
> +   该文件仅存在于前一个阶段，这就是为什么我们使用 `--from-requirements-stage` 来复制它。
```suggestion
     该文件仅存在于前一个阶段，这就是为什么我们使用 `--from-requirements-stage` 来复制它。
```

2023-09-22 15:26 UTC, tiangolo commented
📝 Docs preview for commit 52a2f7f52d090869e21bd0c54f4787bb7de5ad94 at: https://426906b0.fastapitiangolo.pages.dev

2023-09-23 00:11 UTC, tiangolo commented
📝 Docs preview for commit 053ce6139f3473065cc33c6e71fd9157730f4480 at: https://4b99b2c6.fastapitiangolo.pages.dev

2024-01-09 02:27 UTC, Aruelius approved these changes

2024-01-28 18:00 UTC, merged

2024-01-28 18:01 UTC, alejsdev commented
Thanks for your work! @xzmeng 🤓 

And thanks for the reviews @Aruelius and @socket-socket 🚀💯