German translation of docs/tutorial/body-fields.md
fastapi/fastapi pull request #10310
Opened 2023-09-22 21:04 UTC by nilslindemann

See commit description.

← [tutorial/body-multiple-params.md](https://github.com/tiangolo/fastapi/pull/10308)

2023-09-22 21:09 UTC, tiangolo commented
📝 Docs preview for commit 05f33ba3eee51b9774a57263bcd8f8420d65d945 at: https://bc74ea94.fastapitiangolo.pages.dev

2023-09-26 00:06 UTC, tiangolo commented
📝 Docs preview for commit 55cd1bdbe4263dbe84e778034101df0f8209e583 at: https://28378b06.fastapitiangolo.pages.dev

2023-09-26 00:51 UTC, tiangolo commented
📝 Docs preview for commit 03d3dd2d90e7a597fb3e96175bd6e94511283f32 at: https://799f6f86.fastapitiangolo.pages.dev

2023-09-26 01:28 UTC, tiangolo commented
📝 Docs preview for commit d990bbc36c84f8cbcc0f9f2195db7ed3c91e332e at: https://8c75477e.fastapitiangolo.pages.dev

2023-09-29 10:19 UTC, tiangolo commented
📝 Docs preview for commit 5b05940dbeea739e4a102007d1374143149a70dc at: https://8b952cf5.fastapitiangolo.pages.dev

2023-09-29 14:52 UTC, tiangolo commented
📝 Docs preview for commit 92cfdf3d7e663fc850cf93f95b62573b0ec1a7cf at: https://4f69181f.fastapitiangolo.pages.dev

2023-09-30 10:18 UTC, tiangolo commented
📝 Docs preview for commit aed065b0a2b5dd7a3c0160c7689523a1df65deda at: https://acfd432d.fastapitiangolo.pages.dev

2023-10-05 02:03 UTC, tiangolo commented
📝 Docs preview for commit 702eae5a984daf3d31fe9a884b2fb9a063ee8abb at: https://d81b3177.fastapitiangolo.pages.dev

2023-10-14 02:57 UTC, tiangolo commented
📝 Docs preview for commit b5ae1d2ac553f0ff8e3f85f56dcf958b1cf11363 at: https://2d1bad45.fastapitiangolo.pages.dev

2023-10-17 18:33 UTC, tiangolo commented
📝 Docs preview for commit c8d08b1ce8626f50db7ddf2b98cedf120f41a2d0 at: https://f93734cc.fastapitiangolo.pages.dev

2023-10-18 18:59 UTC, tiangolo commented
📝 Docs preview for commit 527216d57a5a8872ec063a8b6c7235a35eaf1aae at: https://5fd8d1f4.fastapitiangolo.pages.dev

2023-10-20 14:57 UTC, tiangolo commented
📝 Docs preview for commit 6fb4def61071973327712eb807ca39b4e238af82 at: https://8da7b35d.fastapitiangolo.pages.dev

2023-10-22 17:03 UTC, tiangolo commented
📝 Docs preview for commit 5898e12093f907e1f13da14a2757f23e89f4f4e5 at: https://55ed4dd9.fastapitiangolo.pages.dev

2023-10-25 18:14 UTC, tiangolo commented
📝 Docs preview for commit 990eda1fe278d00fad712bd86661de6954450000 at: https://ce1b045f.fastapitiangolo.pages.dev

2023-10-30 08:05 UTC, tiangolo commented
📝 Docs preview for commit f120f33d3974bb578d1143621e175a7bada8801f at: https://db7f36ad.fastapitiangolo.pages.dev

2023-10-31 07:13 UTC, tiangolo commented
📝 Docs preview for commit a5a24538c96af8a665a7bfe9b5ed01808182f9f7 at: https://c047878a.fastapitiangolo.pages.dev

2023-11-10 02:02 UTC, tiangolo commented
📝 Docs preview for commit 5d071c200b53d872076dfab4f771c54fc8d26e7f at: https://1a07c191.fastapitiangolo.pages.dev

2023-11-29 19:59 UTC, tiangolo commented
📝 Docs preview for commit 8d4f748454e85d72161644aefd6122308f9fe49f at: https://211f2153.fastapitiangolo.pages.dev

2023-12-01 03:28 UTC, tiangolo commented
📝 Docs preview for commit f1c4bb4a073b54e30f967d7c17dea1204bc359b2 at: https://5af3e5ab.fastapitiangolo.pages.dev

2023-12-30 20:22 UTC, tiangolo commented
📝 Docs preview for commit c4648bc4a120ad7581509510164edac00c496d96 at: https://f748ae08.fastapitiangolo.pages.dev

2024-01-27 22:18 UTC, mattkoehne requested changes
Thank you @nilslindemann 👍

2024-01-27 22:18 UTC, mattkoehne commented on docs/de/docs/tutorial/body-fields.md
> +    Extra-Schlüssel, die `Field` überreicht werden, werden auch im resultierenden OpenAPI-Schema ihrer Anwendung gelistet. Da diese Schlüssel nicht notwendigerweise Teil der OpenAPI-Spezifikation sin
`ihrer Anwendung` -> `Ihrer Anwendung`

2024-01-29 13:43 UTC, nilslindemann commented
Auch hier, Danke fürs Review. :+1:

2024-01-29 13:49 UTC, tiangolo commented
📝 Docs preview for commit cb0c8610b604e2ec7468dc9c1c2b71f7738609b9 at: https://b4086a49.fastapitiangolo.pages.dev

2024-01-29 17:28 UTC, mattkoehne approved these changes
Awesome! Thanks! 🥂

2024-01-29 17:36 UTC, merged

2024-01-29 17:36 UTC, alejsdev commented
Thank you both for your help!  @nilslindemann @mattkoehne 🚀✨