Fix/conider alias in form
fastapi/fastapi pull request #10319
Opened 2023-09-25 03:49 UTC by harol1997

alias is considered in swagger and redoc docs

2023-10-04 01:45 UTC, Ryandaydev requested changes
@harol1997 I verified the behavior before and after this change, and the PR corrects it in both redoc and swagger.

However, I couldn't get the test to run successfully, and your branch appears to be out of date with master. Do the tests run successfully on your end?

2023-10-07 08:15 UTC, harol1997 commented
> @harol1997 I verified the behavior before and after this change, and the PR corrects it in both redoc and swagger.
> 
> However, I couldn't get the test coverage script to run successfully, and your branch appears to be out of date with master. Do the tests run successfully on your end?

@Ryandaydev  I already updated repository from master fastapi (original branch)  and I was able to  run test succesfully.

2023-10-13 01:57 UTC, Ryandaydev approved these changes
All tests pass now that branch is updated, including new test.
 
I verified the behavior before and after this change, and the PR corrects it in both redoc and swagger.

2023-11-07 18:10 UTC, hruzeda commented
any updates on this guys?

2023-11-14 00:38 UTC, harol97 commented
> any updates on this guys?

For the moment You could use validation_alias and alias at same time .

I hope @tiangolo check it P.R soon

2023-11-14 20:08 UTC, hruzeda commented
@harol97, the workaround didn't work for me, am I doing something wrong?

```...
    for route in app.routes:
        if isinstance(route, APIRoute):
            # TODO: body params aliases won't work in Swagger - https://github.com/tiangolo/fastapi/issues/10286
            _transform_snake_case(route.dependant.body_params)
            _transform_snake_case(route.dependant.query_params)
            _transform_snake_case(route.dependant.header_params)```

def _transform_snake_case(params: list[ModelField]) -> None:
    for param in params:
        camelized = humps.camelize(param.name)
        param.field_info.alias = camelized
        param.field_info.validation_alias = camelized
```

![image](https://github.com/tiangolo/fastapi/assets/977242/b02240e2-4923-4b69-aabf-ed418ec47c14)

2024-02-17 06:10 UTC, YuriiMotov requested changes
I've just run the `test_get_alias` on current FastAPI version (0.109.2) and it works without errors.
The issue isn't covered by test.

The alias actually works, but the problem is that it is not displayed correctly in the json schema (at least in the current version of FastAPI).

We need to add test case that checks JSON schema. I would also remove `test_without_alias` (I bet this case is already covered in other places).

I propose next code:
```
from starlette.testclient import TestClient

from fastapi import FastAPI, Form

app: FastAPI = FastAPI()


@app.post("/testing_alias")
async def check_alias(id_test: int = Form(alias="otherId")):
    return {"other_id": id_test}


client = TestClient(app)


def test_get_alias():
    response = client.post("/testing_alias", data={"otherId": "1"})
    assert response.status_code == 200
    assert response.json() == {"other_id": 1}


def test_file_alias_schema():
    response = client.get("/openapi.json")
    assert response.status_code == 200, response.text
    schema = response.json()

    assert (
        "otherId"
        in schema["components"]["schemas"]["Body_check_alias_testing_alias_post"][
            "properties"
        ]
    )
```
@harol97, can you check it?

2024-03-07 04:23 UTC, harol97 commented
> I've just run the `test_get_alias` on current FastAPI version (0.109.2) and it works without errors. The issue isn't covered by test.
> 
> The alias actually works, but the problem is that it is not displayed correctly in the json schema (at least in the current version of FastAPI).
> 
> We need to add test case that checks JSON schema. I would also remove `test_without_alias` (I bet this case is already covered in other places).
> 
> I propose next code:
> 
> ```
> from starlette.testclient import TestClient
> 
> from fastapi import FastAPI, Form
> 
> app: FastAPI = FastAPI()
> 
> 
> @app.post("/testing_alias")
> async def check_alias(id_test: int = Form(alias="otherId")):
>     return {"other_id": id_test}
> 
> 
> client = TestClient(app)
> 
> 
> def test_get_alias():
>     response = client.post("/testing_alias", data={"otherId": "1"})
>     assert response.status_code == 200
>     assert response.json() == {"other_id": 1}
> 
> 
> def test_file_alias_schema():
>     response = client.get("/openapi.json")
>     assert response.status_code == 200, response.text
>     schema = response.json()
> 
>     assert (
>         "otherId"
>         in schema["components"]["schemas"]["Body_check_alias_testing_alias_post"][
>             "properties"
>         ]
>     )
> ```
> 
> @harol97, can you check it?

You're right. I changed the test file and I also add support to validation_alias when it's instance of str. validation_alias is priority above alias.

@YuriiMotov  check new changes

Thanks @YuriiMotov

2025-11-06 23:26 UTC, YuriiMotov requested changes
@harol97, thank your for your interest and efforts!

The changes from this PR actually affect much more than just `Form` fields (all kinds of parameters?). So, we should add more tests.

Would you like to continue working on this?

2025-11-06 23:26 UTC, YuriiMotov commented on .gitignore
> +.python-version
```suggestion
```
Avoid adding unnecessary changes

2025-11-06 23:26 UTC, YuriiMotov commented on fastapi/_compat.py
> +        field_params = {
I think this is incorrect. We should solve this the way it's done in #10257 (by fixing `serialization_alias` in `field_info`)

2025-11-06 23:26 UTC, YuriiMotov commented on fastapi/_compat.py
> +            ) or self.field_info.alias
```suggestion
        va = self.field_info.validation_alias
        if isinstance(va, str) and va:
            return va
        a = self.field_info.alias
```
I think this way it's easier to read

2025-11-07 02:53 UTC, harol97 commented on fastapi/_compat.py
> +            ) or self.field_info.alias
Hello @YuriiMotov . I would have to review what has changed in the latest versions of FastAPI and verify that the error persists. I will close this PR since I believe it has been too long since it was opened, and if I find that this error persists, I will open a new one.

2025-11-07 02:53 UTC, closed without merging

2025-11-07 02:54 UTC, harol97 commented
Hello @YuriiMotov  . I would have to review what has changed in the latest versions of FastAPI and verify that the error persists. I will close this PR since I believe it has been too long since it was opened, and if I find that this error persists, I will open a new one.