Fixes for russian doc
fastapi/fastapi pull request #10311
Opened 2023-09-23 10:08 UTC by AlertRED

- В разделе "фоновые задачи" параметр `q` используется в качестве query-параметра, а не в значении очереди, как это описано внизу примера.
- В разделе "тестирование" используется местоимение "вы" и другие его производные с большой буквы. Причины исправления:
  1. "Вы" - это уже уважительная форма слова "ты", писать с большой буквы не имеет смысла, если это не начало предложения;
  2. Во всей остальной документации тоже используется написание этого слова с маленькой буквы.

Остальные исправления - это исправления опечаток.

2023-09-23 10:17 UTC, tiangolo commented
📝 Docs preview for commit b99c2ad1b64f4665fcb7c52acb69d200defb63c5 at: https://9534290c.fastapitiangolo.pages.dev

2023-09-23 10:44 UTC, tiangolo commented
📝 Docs preview for commit 5fcf4158348bc2197ed64654e0cdb84f407cab1f at: https://5294c8ca.fastapitiangolo.pages.dev

2023-09-28 15:50 UTC, Alexandrhub approved these changes

2023-09-28 17:47 UTC, Xewus commented
> * В разделе "фоновые задачи" параметр `q` используется в качестве query-параметра, а не в значении очереди, как это описано внизу примера.
> * В разделе "тестирование" используется местоимение "вы" и другие его производные с большой буквы. Причины исправления:
>   
>   1. "Вы" - это уже уважительная форма слова "ты", писать с большой буквы не имеет смысла, если это не начало предложения;
>   2. Во всей остальной документации тоже используется написание этого слова с маленькой буквы.
> 
> Остальные исправления - это исправления опечаток.

Касательно претензии к "Вы" (так как это я писал).
Не разу не видел и не слышал про массовые случаи чтения документации количеством людей более одного, но писать "ты" не считаю уместным, а "вы" - это множественное число.
И да, Вы правы,"Вы" - уважительная форма обращения, которая закрепилась в английском языке, равно как и вопрос - "Как Ваше имя?", а не "как тебя звать [холоп]?"

Тем не менее, несмотря на свой принцип (и правила этикета) обращаться к незнакомым людям на "Вы", я не выказываю претензий к остальным коллегам по столь незначительному поводу, так как понятна лень людей, не дающая зажать шифт или дотянуться до буквы "Ё".

На эту тему можно много холиварить и даже пулять источниками с обеих сторон, но вместо этого лучше перевести ещё пару страниц.
http://new.gramota.ru/spravka/letters/51-rubric-88

2023-09-28 17:51 UTC, Xewus requested changes

2023-09-28 17:51 UTC, Xewus commented on docs/ru/docs/tutorial/testing.md
> -Используя эти инструменты, Вы можете напрямую задействовать <a href="https://docs.pytest.org/" class="external-link" target="_blank">pytest</a> с **FastAPI**.
Пояснение в комментариях.

2023-09-28 20:25 UTC, tiangolo commented
📝 Docs preview for commit 33a2d714e5883a00ecf571647c59c99d61e7825a at: https://5ef18eb5.fastapitiangolo.pages.dev

2023-09-29 07:53 UTC, Xewus approved these changes

2023-09-29 08:03 UTC, Xewus commented
Вы пометили testing.md "на удаление" и если перейти по ссылке указанной выше, которая показывает результат применения изменений, то видно, что страница теперь без перевода.

https://5ef18eb5.fastapitiangolo.pages.dev/ru/tutorial/testing/

2023-09-29 08:09 UTC, AlertRED commented
> Вы пометили testing.md "на удаление" и если перейти по ссылке указанной выше, которая показывает результат применения изменений, то видно, что страница теперь без перевода.
> 
> https://5ef18eb5.fastapitiangolo.pages.dev/ru/tutorial/testing/

Вы правы, спасибо. Уже восстанавливаю :)

2023-09-29 08:13 UTC, tiangolo commented
📝 Docs preview for commit ef260850602d8c82c51e8ea3c0e78e31736cc80a at: https://be3877bd.fastapitiangolo.pages.dev

2023-09-29 08:38 UTC, AlertRED commented
> > * В разделе "фоновые задачи" параметр `q` используется в качестве query-параметра, а не в значении очереди, как это описано внизу примера.
> > * В разделе "тестирование" используется местоимение "вы" и другие его производные с большой буквы. Причины исправления:
> >   
> >   1. "Вы" - это уже уважительная форма слова "ты", писать с большой буквы не имеет смысла, если это не начало предложения;
> >   2. Во всей остальной документации тоже используется написание этого слова с маленькой буквы.
> > 
> > Остальные исправления - это исправления опечаток.
> 
> Касательно претензии к "Вы" (так как именно так везде пишу). Не разу не видел и не слышал про массовые случаи чтения документации количеством людей более одного, но писать "ты" не считаю уместным, а "вы" - это множественное число. И да, Вы правы,"Вы" - уважительная форма обращения, которая закрепилась в английском языке, равно как и вопрос - "Как Ваше имя?", а не "как тебя звать [холоп]?"
> 
> Тем не менее, несмотря на свой принцип (и правила этикета) обращаться к незнакомым людям на "Вы", я не выказываю претензий к остальным коллегам по столь незначительному поводу, так как понятна лень людей, не дающая зажать шифт или дотянуться до буквы "Ё" и в целом невысокий средний уровень образованности (впрочем, я сам не профессор).
> 
> На эту тему можно много холиварить и даже пулять источниками с обеих сторон, но вместо этого лучше перевести ещё пару страниц. http://new.gramota.ru/spravka/letters/51-rubric-88

Я действительно убрал свои изменения связанные с написанием этого слова, видимо, тема не простая в обществе.
Я вчера посмотрел информацию по вашей ссылке, но остался уверен, что местоимение "вы" должно писаться с маленькой, строчной буквы. Это не личная переписка, и тут не должно быть проявления такого глубокого уважения.
У меня даже не идет упор на то как правильно в русском языке писать это слово, а ориентируюсь тут даже по своему ощущению, а именно: частое использование написание "вы" с большой буквы обесценивает это самое уважение. Это также связанно компаниями которые так общаются с клиентами, и причем не только это слово пишут с большой буквы. Это все, лично во мне, создает чувство, что мне хотят понравится в плохом смысле т.е. вижу уважение без какой либо причины, от какой-то там компании. Может и такое написание скоро обесценится, через лет 40, и будут писать все слово большими буквами :)
Решил не оставлять ваш комментарий без ответа. И действительно, лучше перейду к переводу других страниц, чем холиварить всю эту историю :)

2023-10-18 19:55 UTC, Xewus approved these changes

2024-01-09 15:52 UTC, tiangolo commented
Nice, thank you @AlertRED! 🍰 

And thanks for the reviews @Xewus and @Alexandrhub 🙇

2024-01-09 15:52 UTC, merged