🌐 Add German translation for `docs/de/docs/tutorial/response-status-code.md`
fastapi/fastapi pull request #10357
Opened 2023-09-30 14:08 UTC by nilslindemann

See commit description.

← [tutorial/extra-models.md](https://github.com/tiangolo/fastapi/pull/10351)

2023-09-30 14:15 UTC, tiangolo commented
📝 Docs preview for commit 3dc76228ab0908e6601e0a72453f0ea90fd86605 at: https://4beca6c2.fastapitiangolo.pages.dev

2023-09-30 14:47 UTC, tiangolo commented
📝 Docs preview for commit e3c7f1ed0a391627302ad7213aa0e7e1900b6117 at: https://4aa42ef4.fastapitiangolo.pages.dev

2023-09-30 15:04 UTC, tiangolo commented
📝 Docs preview for commit 825c3271cdfffa824b860e24052e219a61cd5a65 at: https://737db89a.fastapitiangolo.pages.dev

2023-10-03 22:42 UTC, tiangolo commented
📝 Docs preview for commit 9ff2ff86cc37a49eb3aef3fae71e9a8107da3c8d at: https://a7ae81c7.fastapitiangolo.pages.dev

2023-10-04 00:34 UTC, tiangolo commented
📝 Docs preview for commit 26255012fa15e1b68fe5c36ea5a9c0e9d8016deb at: https://ace6d452.fastapitiangolo.pages.dev

2023-10-14 02:57 UTC, tiangolo commented
📝 Docs preview for commit 1e1628333650e6d7390eccf63a477497ee4a7d15 at: https://4da35bac.fastapitiangolo.pages.dev

2023-10-17 16:18 UTC, tiangolo commented
📝 Docs preview for commit c2b500b34c71bc97ed1f703e2a58b0a9bcf3a313 at: https://cfd70024.fastapitiangolo.pages.dev

2023-10-18 19:00 UTC, tiangolo commented
📝 Docs preview for commit 57824a59cd1d880455332b09404ff481dfae2493 at: https://af124631.fastapitiangolo.pages.dev

2023-10-20 14:56 UTC, tiangolo commented
📝 Docs preview for commit 7b4289629c5c115a909ddae1be2cbeedaaa6d71c at: https://992b1ac6.fastapitiangolo.pages.dev

2023-10-22 17:30 UTC, tiangolo commented
📝 Docs preview for commit fb4897f6ce4ae34e358c7f9eb2429bdeed4ef7df at: https://8faba312.fastapitiangolo.pages.dev

2023-10-25 18:17 UTC, tiangolo commented
📝 Docs preview for commit ebe343b722c49defab7a72b8dd52ae7350b52407 at: https://77dcaff1.fastapitiangolo.pages.dev

2023-10-29 05:20 UTC, tiangolo commented
📝 Docs preview for commit 5e20ffdd0b8e5b91e281264f9e5ce3e004f6d362 at: https://596db1aa.fastapitiangolo.pages.dev

2023-10-30 07:59 UTC, tiangolo commented
📝 Docs preview for commit 7dfa73fbc15889500768ee48bc0bec2068fd11f0 at: https://cfe373be.fastapitiangolo.pages.dev

2023-10-31 07:13 UTC, tiangolo commented
📝 Docs preview for commit f10d2f94dd163f1350650639233ed46ddf5812c8 at: https://1285da69.fastapitiangolo.pages.dev

2023-11-12 01:56 UTC, tiangolo commented
📝 Docs preview for commit 7e6309265e87d0fad2c445bdc9938c929b07a0f5 at: https://a4dd19d0.fastapitiangolo.pages.dev

2023-11-18 14:35 UTC, tiangolo commented
📝 Docs preview for commit 74698ff16b205b49b470df0ed6c7494fb4ff21e2 at: https://350c3c05.fastapitiangolo.pages.dev

2023-11-29 19:51 UTC, tiangolo commented
📝 Docs preview for commit d6667b2c2a33ba24f4b150cfaf993951348c21e2 at: https://b3c27a77.fastapitiangolo.pages.dev

2023-12-30 20:22 UTC, tiangolo commented
📝 Docs preview for commit 91c40adedd467372571d1770dfcd4e02ec7f882d at: https://69ea0c2c.fastapitiangolo.pages.dev

2024-02-07 17:58 UTC, mattkoehne requested changes
Thanks Nils :)

2024-02-07 17:58 UTC, mattkoehne commented on docs/de/docs/tutorial/response-status-code.md
> +    Beachten Sie, dass `status_code` ein Parameter der „Dekorator“-Methode ist (`get`, `post`, usw.). Nicht der *Pfadoperation-Funktion*, so wie die anderen Parameter.
`so wie die anderen Parameter.` -> `so wie die anderen Parameter und der Body.`

2024-02-07 17:58 UTC, mattkoehne commented on docs/de/docs/tutorial/response-status-code.md
> +* `500` und darüber stehen für Server-Fehler. Diese verwenden Sie fast nie direkt. Wenn etwas an irgendeiner Stelle in ihrem Anwendungscode oder im Server schiefläuft, wird automatisch einer dieser F
`in ihrem Anwendungscode` -> `in Ihrem Anwendungscode`

2024-02-07 17:58 UTC, mattkoehne commented on docs/de/docs/tutorial/response-status-code.md
> +Diese sind nur eine Annehmlichkeit und enthalten dieselbe Nummer, aber auf diese Weise können Sie die Autovervollständigung ihres Editors verwenden, um sie zu finden:
`ihres Editors` -> `Ihres Editors`

2024-04-01 02:20 UTC, nilslindemann commented
Auch hier wieder ein herzliches Dankeschön fürs Review an dich, Matthias!

2024-04-01 02:24 UTC, tiangolo commented
📝 Docs preview for commit 8a425cc405fcd38e9043c3a2adc28034dfec5c63 at: https://5e1781e6.fastapitiangolo.pages.dev

2024-04-01 20:01 UTC, mattkoehne approved these changes

2024-04-02 02:32 UTC, merged