🌐 Add Russian translation for `docs/ru/docs/tutorial/encoder.md`
fastapi/fastapi pull request #10374
Opened 2023-10-03 19:06 UTC by AlertRED

2023-10-03 19:14 UTC, tiangolo commented
📝 Docs preview for commit fb10b83d549734e10f7a999c7481a7928d855879 at: https://2c97e658.fastapitiangolo.pages.dev

2023-10-18 20:13 UTC, Xewus requested changes
На самом деле у Pydantic-моделей есть метод преобразования в json, так что не приходилось этой функцией пользоваться. Но может полезна для сторонних библиотек...

2023-10-18 20:13 UTC, Xewus commented on docs/ru/docs/tutorial/encoder.md
> +Так, объект `datetime` должен быть преобразован в `str` в <a href="https://en.wikipedia.org/wiki/ISO_8601" class="external-link" target="_blank">ISO формате</a>.
```suggestion
В таком случае объект `datetime` следует преобразовать в строку соответствующую <a href="https://en.wikipedia.org/wiki/ISO_8601" class="external-link" target="_blank">формату ISO</a>.
```

2023-10-18 20:13 UTC, Xewus commented on docs/ru/docs/tutorial/encoder.md
> +Точно так же эта база данных не получит Pydantic модель (объект с атрибутами), а только `dict`.
```suggestion
Точно так же эта база данных не может принять Pydantic модель (объект с атрибутами), а только `dict`.
```

2023-10-18 20:13 UTC, Xewus commented on docs/ru/docs/tutorial/encoder.md
> +Для этого можно использовать `jsonable_encoder`.
```suggestion
Для этого можно использовать функцию `jsonable_encoder`.
```

2023-10-18 20:13 UTC, Xewus commented on docs/ru/docs/tutorial/encoder.md
> +Он принимает объект, например, модель Pydantic, и возвращает версию, совместимую с JSON:
```suggestion
Она принимает объект, например, модель Pydantic, и возвращает его версию, совместимую с JSON:
```

2023-10-18 20:13 UTC, Xewus commented on docs/ru/docs/tutorial/encoder.md
> +Он принимает объект, например, модель Pydantic, и возвращает версию, совместимую с JSON:
в 35 строке Вы сами применили местоимение "она".

2023-10-18 20:13 UTC, Xewus commented on docs/ru/docs/tutorial/encoder.md
> +Результатом его вызова является объект, который может быть закодирован с помощью стандартной библиотеки Python <a href="https://docs.python.org/3/library/json.html#json.dumps" class="external-link" t
```suggestion
Результатом её вызова является объект, который может быть закодирован с помощью функции из стандартной библиотеки Python <a href="https://docs.python.org/3/library/json.html#json.dumps" class="external-link" target="_blank">`json.dumps()`</a>.
```

2023-10-18 20:13 UTC, Xewus commented on docs/ru/docs/tutorial/encoder.md
> +Результатом его вызова является объект, который может быть закодирован с помощью стандартной библиотеки Python <a href="https://docs.python.org/3/library/json.html#json.dumps" class="external-link" t
перед названием функции может быть нужно тире или что-то такое...

2023-10-23 21:52 UTC, AlertRED commented on docs/ru/docs/tutorial/encoder.md
> +Результатом его вызова является объект, который может быть закодирован с помощью стандартной библиотеки Python <a href="https://docs.python.org/3/library/json.html#json.dumps" class="external-link" t
> перед названием функции может быть нужно тире или что-то такое...

```suggestion
Результатом его вызова является объект, который может быть закодирован с помощью стандартной библиотеки Python - <a href="https://docs.python.org/3/library/json.html#json.dumps" class="external-link" target="_blank">`json.dumps()`</a>.
```

2023-10-23 21:55 UTC, AlertRED commented on docs/ru/docs/tutorial/encoder.md
> +Результатом её вызова является объект, который может быть закодирован с помощью функции из стандартной библиотеки Python <a href="https://docs.python.org/3/library/json.html#json.dumps" class="extern
```suggestion
Результатом её вызова является объект, который может быть закодирован с помощью функции из стандартной библиотеки Python – <a href="https://docs.python.org/3/library/json.html#json.dumps" class="external-link" target="_blank">`json.dumps()`</a>.
```

2023-10-23 22:02 UTC, tiangolo commented
📝 Docs preview for commit 76e3e00a595b1dd280c9c7b08aaf1b05dbe4bfa7 at: https://cfe1e00a.fastapitiangolo.pages.dev

2024-01-14 18:01 UTC, Xewus approved these changes

2024-01-23 13:56 UTC, merged

2024-01-23 13:56 UTC, alejsdev commented
Thank you! @AlertRED 🚀✨ 

And thanks for the review @Xewus 🔍