🌐 Add Russian translation for `docs/ru/docs/tutorial/dependencies/classes-as-dependencies.md`
fastapi/fastapi pull request #10410
Opened 2023-10-09 09:11 UTC by AlertRED

2023-12-17 16:03 UTC, Xewus requested changes

2023-12-17 16:03 UTC, Xewus commented on docs/ru/docs/tutorial/dependencies/classes-as-dependencies.md
> +Для таких случаев можно поступить следующим образом:
Это строку можно удалить. Весь смысл уже описан в предыдущем предложении.

2023-12-26 12:46 UTC, AlertRED commented on docs/ru/docs/tutorial/dependencies/classes-as-dependencies.md
> +Для таких случаев можно поступить следующим образом:
```suggestion
```

2023-12-26 12:56 UTC, tiangolo commented
📝 Docs preview for commit ef263ba59f36e48c61198ee03145b79228828262 at: https://f23f9e5f.fastapitiangolo.pages.dev

2023-12-26 17:01 UTC, Xewus approved these changes

2024-01-09 16:25 UTC, EpsilonRationes approved these changes

2024-01-12 11:12 UTC, tiangolo commented
Nice, thank you @AlertRED! 🍰 

And thanks for the reviews @Xewus and @EpsilonRationes! 🙇

2024-01-12 11:12 UTC, merged