🌐 Add Turkish translation for `docs/python-types.md`
fastapi/fastapi pull request #10445
Opened 2023-10-16 09:51 UTC by esrefzeki

Fixes mistranslations and adds new features

2023-10-16 09:58 UTC, tiangolo commented
📝 Docs preview for commit 018703a41b7236195f10c1bdefa04b228f387071 at: https://149a3713.fastapitiangolo.pages.dev

2023-10-16 12:10 UTC, hasansezertasan requested changes
Vurgulanan noktalar çevirinin genelinde tekrar etmekte. Gözden geçirmeye şimdilik ara veriyorum,.

2023-10-16 12:10 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +## Tip Bildirme
`Tip Tanımlama` daha uygun görünüyor.

2023-10-16 12:10 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
>   **FastAPI**ile çalışırken tip belirteçlerini en çok kullanacağımız yer yine fonksiyonlardır.
Satır başında fazladan boşluk var. Kalınlaştırma sonrası boşluk bırakılması gerekiyor.

2023-10-16 12:10 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> -"dict", "list", "set" ve "tuple" gibi diğer değerleri içerebilen bazı veri yapıları vardır. Ve dahili değerlerinin de tip belirtecleri olabilir.
Backquote kullanalım.

2023-10-16 12:26 UTC, esrefzeki commented
Geri dönüşler için teşekkürler.

2023-10-16 22:58 UTC, tiangolo commented
📝 Docs preview for commit 574596ceaae7cbb1447a4868e518111dab393a15 at: https://6b65633d.fastapitiangolo.pages.dev

2023-10-16 23:08 UTC, tiangolo commented
📝 Docs preview for commit aba7b4cb9f46728322e1d84f78563990f670ee9a at: https://461f92ef.fastapitiangolo.pages.dev

2023-10-19 23:38 UTC, hasansezertasan requested changes
Çeviri iyi olmuş elinize sağlık, devamını daha uygun bir zamanda değerlendireceğim. Hata sayısı fazla olduğu için değerlendirme de çok uzun sürüyor ve yoruyor. Kusura bakmayın.

2023-10-19 23:38 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +Tüm dokümanlarda Python'un her sürümüyle uyumlu örnekler bulabilirsiniz (eğer bir farklılık oluştuysa).
Tüm dokümanlarda (eğer bir farklılık oluştuysa) Python'un her sürümüyle uyumlu örnekler bulabilirsiniz.

2023-10-19 23:38 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +    Declare the variable, with the same colon (`:`) syntax.
Türkçe değil.

2023-10-19 23:38 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +    As the type, put `list`.
Çevirilmemiş.

2023-10-19 23:38 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +    As the list is a type that contains some internal types, you put them in square brackets:
Çevirilmemiş.

2023-10-19 23:38 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +    Liste, bazı dahili tipleri içeren bir tür olduğundan, bunları köşeli parantez içine alırsınız:
`...alabilirsiniz.`

`Liste tanımlarken dahil tip tanımlayabiliz, bunu köşeli parantez içerisinde gerçekleştirebilirsiniz:`

2023-10-19 23:38 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
>  !!! ipucu
`tip` için "ipucu" kullanmak daha mantıklı olacağı için `info` için `bilgi` kullanmak daha mantıklı olacaktır.

2023-10-19 23:38 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +!!! tip
Çevirilmemiş.

2023-10-19 23:38 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +    Bu durumda `str`, `List`e iletilen tür parametresidir (veya Python 3.9+ için `list`)
`...iletilen bir tür parametresidir`

2023-10-19 23:38 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +    Python 3.9 veya daha üstünü kullanıyorsanız, `List`i `typing`den import etmek zorunda değilsiniz, bunun yerine aynı normal `list` türünü kullanabilirsiniz.
`... import etmek...` => `...modülünden projenize dahil etmek...` veya `...modülünden import etmek`

`...aynı normal...` demek doğru mu? `...her zamanki...` demek çeviriye daha uygun oluyor. 

`import etmek` için ne kullanmalıyız?

2023-10-19 23:38 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +Tipler olmadan bunu başarmak neredeyse imkansızdır.
`Tipler olmasaydı bunu elde etmek neredeyse imkansızdı.`

2023-10-19 23:38 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +Değişken öğenin `list` öğelerindeki `items`dan biri olduğuna dikkat edin.
Hocam otomatik çeviri mi kullandık?

``Notice that the variable `item` is one of the elements in the list `items`.``

``Şuna dikkat edin: `item` değişkeni, `items` listesinde bulunan elemanlardan birisi.``

`item` değişkenine değinilmemiş.

2023-10-19 23:38 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +    {!> ../../../docs_src/python_types/tutorial006.py!}
Doküman formatı bozulmuş ve sanırım `mkdocs serve` komutuyla çıktısı değerlendirilmemiş. Burada bulunan hata döküman formatını etkilemektedir.

2023-10-19 23:38 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
>  `Tuple` ve `set`lerin tiplerini bildirmek için de aynısını yapıyoruz:
`bildirmek` => `belirtmek`

2023-10-19 23:38 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
>      *  `dict` değişkeninin `key` değeri  `str` tipindedir (herbir item'ın "name" değeri).
Kelimeler arası "tek boşluk" kullanılmalı, "çift boşluk" değil.

`herbir` ayrı yazılacak.

2023-10-19 23:38 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
>      *  `dict` değişkeninin `value` değeri `float` tipindedir (lherbir item'ın "price" değeri).
Yazım hatası.

2023-10-19 23:38 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +Python 3.6 ve üzeri sürümlerde (Python 3.10 dahil) `typing`den `Union` türünü kullanabilir ve kabul edilecek olası türleri köşeli parantezlerin içine koyabilirsiniz.
`...kabul edilecek olası türleri köşeli parantezlerin içine koyabilirsiniz.` => `...değişkenin alabileceği veri tiplerini köşeli parantezlerin içine yerleştirebilirsiniz...`

2023-10-19 23:38 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +Python 3.10'da olası türleri dikey bir <abbr title='"bitsel veya operatör" olarak da adlandırılır, ancak bu anlam burada geçerli değildir'>çubukla (`|`)</abbr> (|) ayırabileceğiniz yeni bir **sözdizi
Çıktısı şu şekilde: ``(`|`) (|)`` Ard arda aynı şey sadece farklı yazılmış... Anlamadım.

2023-10-19 23:38 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +Her iki durumda da bu, `item`in bir `int` veya `str` olabileceği anlamına gelir.
``Her iki kullanımda `item`ın bir `int` veya `str` değer alabileceğini ifade eder.``

Lütfen ek kullanırken Türkçe okuyormuşuz gibi değilde İngilizce okuyormuşuz gibi hareket edelim. `FastAPI'nin` veya `item'in` kullanımı yanlıştır.

2023-10-19 23:38 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +Bir değerin `str` gibi bir türe sahip olabileceğini, ancak `None` da olabileceğini bildirebilirsiniz.
``Bir değer `str` bir tipe sahip olabileceği gibi, `None` tipine de sahip olabilir.``

2023-10-19 23:38 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +Python 3.6 ve üzeri sürümlerde (Python 3.10 dahil) `typing` modülünden `Optional`ı içe aktarıp kullanarak bildirebilirsiniz.
Okuyup değerlendirebilir misiniz?

2023-10-19 23:38 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +Sadece `str` yerine `Optional[str]` kullanmak, düzenleyicinin bir değerin aslında `None` da olabileceğini ve gelen değerin `str` olmadığı durumlarda hataları tespit etmenize yardımcı olmasını sağlar.
`Editör`mü yoksa `düzenleyici`mi?

2023-10-20 00:01 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +Şimdi, bu programı sıfırdan yazmaya başladığınızı düşünün. İlk adım, fonksiyonun tanımına başlamak ve gerekli parametreleri hazırlamaktır. Ancak metin içerisindeki ilk harfi büyük harfe dönüştüren me
@esrefzeki Bu yaklaşım ile orjinal doküman güncellendiğinde, çeviriyi güncel tutmak için tekrar çeviri yaparken işimiz de kolaylaşmış olacak.

2023-10-22 12:34 UTC, BilalAlpaslan commented on docs/tr/docs/python-types.md
> +Değişkenleriniz için tip bildirerek, editörler ve araçlar size daha iyi bir kullanım deneyimi sağlayabilir.
`Değişkenleriniz için tip bildirmeniz, bazı kod editörleri ve araçlardan daha iyi destek almanıza yardımcı olur.`  nasıl

2023-10-22 17:30 UTC, hasansezertasan requested changes

2023-10-22 17:41 UTC, tiangolo commented
📝 Docs preview for commit 1a6ae53e896e361c456c19dc8395861c130024f4 at: https://3aad993a.fastapitiangolo.pages.dev

2023-10-22 19:15 UTC, hasansezertasan requested changes

2023-10-22 19:15 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +    Değişkenin tipini yine iki nokta üstüste (`:`) ile belirleyin ve tip olarak `List` kullanın.
Satır düzenini burada bozmuşuz, orjinal haline bağlı satırlama yapalım.

2023-10-22 19:17 UTC, BilalAlpaslan commented on docs/tr/docs/python-types.md
>  !!! not
!!! note "Not"

2023-10-22 19:19 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +`upper` mıydı? Yoksa  `uppercase`' mi? `first_uppercase`? Ya da `capitalize`?
Ard arda boşluk kullanımı yapılmış.

2023-10-22 19:21 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +
Fazladan boşluk kullanılmış.

2023-10-22 19:21 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +##  **FastAPI** Tip Belirteçleri
Ard arda boşluk kullanımı yapılmış.

2023-10-29 10:35 UTC, hasansezertasan requested changes

2023-10-29 10:35 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +Değişkenleriniz için tip bildirmeniz, bazı kod editörleri ve araçlardan daha iyi destek almanıza yardımcı olur.
`Değişkenlerinizin tiplerini belirtmeniz , bazı kod editörleri ve araçlardan daha iyi destek almanıza yardımcı olur.`

2023-10-29 10:35 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> + **"Tip belirteçleri"** (veya ek açıklamalar) bir değişkenin <abbr title="örneğin: str, int, float, bool">tipinin</abbr> belirtilmesine olanak sağlayan özel bir sözdizimidir.
Satırın başlangıcında hala boşluk var...

2023-10-29 10:35 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +Bu program çağrıldığında <abbr title="Output">çıktısı</abbr> aşağıdaki gibi olur:
`Bu fonksiyon çalıştırıldığında <abbr title="Output">çıktısı</abbr> aşağıdaki gibi olur:`

2023-10-29 10:35 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +`upper` mıydı? Yoksa  `uppercase`' mi? `first_uppercase`? Ya da `capitalize`?
Fonksiyonun adı `upper` mıydı? Yoksa `uppercase`' mi? `first_uppercase`? Belki de`capitalize`?

2023-10-29 10:35 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +### Tipleri Ekle
`# Tipleri Ekleyelim`

2023-10-29 10:35 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +Tam olarak bu parçayı, işlevin parametrelerini şu şekilde değiştireceğiz:
Burası resolve olmamış neden resolve işaretledik? `işlev` yerine yerine göre `fonksiyon` veya `metod` kullanmaya karar vermiştik.

2023-10-29 10:35 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +"Tip belirteçlerini" aşağıdaki gibi uygulayabilirsiniz:
Bunlara "tip belirteçleri" deniyor.

2023-10-29 10:35 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +Parametrelere varsayılan değer atamak ile aynı şey değildir:
Bu yapı, aşağıdaki gibi parametrelere varsayılan değer atamakla aynı şey değil:

2023-10-29 10:35 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +Dikkat edin; iki nokta üst üste (`:`) kullanıyoruz , eşittir (`=`) DEĞİL.
"değil" neden tüm harfleri büyük olacak şekilde yazıldı acaba?

2023-10-29 10:35 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +Şimdi programı tekrar en baştan yazdığınızı hayal edin.
Şimdi bu fonksiyonu tekrar yazdığınızı hayal edin, ama bu sefer tip belirteçleri kullanıyorsunuz.

2023-10-29 10:35 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +Tür belirteçlerine sahip bir fonksiyonu inceleyelim:
Dokümanın farklı yerlerinde `type hint` için hem `tür belirteçleri` hemde `tip belirteçleri` kullanılmış. Bu okuyucunun kafasını karıştırabilir. `Tip Belirteçleri` şeklinde sabit bir kullanıma yönelebilir miyiz? `type annotation` içinde `tip açıklamaları` kullanabiliriz.

2023-10-29 10:35 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +Bu tipleri ve dahili tpileri bildirmek için standart Python küyüphanesi `typing`i kullanabilirsiniz. Bu tür tip belirteçlerini desteklemek için özel olarak mevcuttur.
Bu tipleri ve dahili tipileri belirtmek için standart Python modülü olan `typing` modülünü kullanabilirsiniz. Modülün amacı tip belirteçlerini desteklemektir.

2023-10-29 10:35 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +Dahili tipleri olan bu tiplere "**generic**" (jenerik) tipler denir. Ve bunları iç tipleriyle bile belirtmek mümkündür.
`jenerik` yerine başlıkta ki gibi `genel tip` kullanıp abbr etiketi ile `generic` ifadesine yer verebiliriz.

2023-10-29 10:35 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +Yazım kullanan `typing`, Python 3.6'dan Python 3.9, Python 3.10 vb. dahil olmak üzere en son sürümlere kadar tüm sürümlerle **uyumludur**.
`Yazım kullanan...` ne demek anlamadım ama İngilizce dokümantasyonu incelediğimde `The syntax using...` gibi bir cümleyle karşılaştım. İnceleyebilir misiniz?

2023-10-29 10:35 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +**Python'un en son sürümlerini** kullanayorsanız, en son sürüm için oluşturulan örnekleri kullanın. Bunlar **en iyi ve en basit sözdizimine** sahip olacaktır, örneğin, "**Python 3.10+**".
Doküman genelinde hem `Python'un' hemde `Python'ın` şeklinde karışık bir kullanım var, düzeltebilir misiniz lütfen?

2023-10-29 10:35 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +    Liste bazı dahili türleri içeren bir tür olduğundan, bunları köşeli parantez içine alırsınız:
Liste tipi, başka tipleri içerebildiğinden ötürü, bu tipleri köşeli parantez içerisinde belirtebilirsiniz:

2023-10-29 10:35 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +    From `typing`, import `List` (büyük harf olan `L` ile):
Cümlenin başını çevirebilir miyiz, burası kod değil, bir ifade.

2023-10-29 10:35 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> -!!! ipucu
!!! tip "İpucu" şeklinde düzeltebilir miyiz?

2023-10-29 10:35 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> -Değişkenin tipini yine iki nokta üstüste (`:`) ile belirleyin.
`üst üste` ikilemesi ayrı yazılır.

2023-10-29 10:35 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +    Değişkenin tipini yine iki nokta üstüste (`:`) ile belirleyin ve tip olarak `List` kullanın.
`üst üste` ikilemesi ayrı yazılır.

2023-10-29 10:35 UTC, hasansezertasan commented on docs/tr/docs/python-types.md
> +!!! bilgi
!!! info "Bilgi"

2024-01-31 13:35 UTC, tiangolo commented
As this PR had requested changes to be applied but has been inactive for a while, it's now going to be closed. But if there's anyone interested, feel free to create a new PR.

2024-01-31 13:35 UTC, closed without merging