🌐 Update Turkish translation for `docs/tr/docs/features.md`
fastapi/fastapi pull request #10492
Opened 2023-10-21 13:09 UTC by BilalAlpaslan

2023-10-21 13:21 UTC, tiangolo commented
📝 Docs preview for commit 790b113ad3837620c1428fc676f8e38507f2de75 at: https://2887ccfd.fastapitiangolo.pages.dev

2023-10-21 18:53 UTC, hasansezertasan requested changes

2023-10-21 18:53 UTC, hasansezertasan commented on docs/tr/docs/features.md
> +### Tamamen Test Edildiş ve Güvenilir
Typo mevcut

2023-10-21 18:53 UTC, hasansezertasan commented on docs/tr/docs/features.md
> +* 100% <abbr title="Kodun ne kadarının test edildiği">testle kapsanmış</abbr>.
Yüzde yazımı Türkçe yazıma uygun değil, `%{deger}` şeklinde olmalı.

`%100 test edildi.` demek yeterl, abbr etiketi detayı veriyor ve coverage yabancı.

2023-10-21 18:53 UTC, hasansezertasan commented on docs/tr/docs/features.md
> +* 100% <abbr title="Kodun ne kadarının test edildiği">testle kapsanmış</abbr>.
Yüzde yazımı Türkçe yazıma uygun değil, `%{deger}` şeklinde olmalı.

2023-10-21 18:53 UTC, hasansezertasan commented on docs/tr/docs/features.md
>  * FastAPI ile yapılan bir çok proje insanlar tarafından kullanılıyor.
`FastAPI ile son kullanıcıya ulaşmış bir çok uygulama geliştirildi.`

2023-10-21 18:53 UTC, hasansezertasan commented on docs/tr/docs/features.md
> +`FastAPI` aslında `Starlette`'nin alt katmanında kullanan bir üst framework. Eğer Starlette'nin nasıl kullanılacağını biliyor isen, çoğu işlevini aynı şekilde yapıyor.
`...biliyor isen...` => `...biliyorsanız...`

2023-10-21 18:53 UTC, hasansezertasan commented on docs/tr/docs/features.md
>  * **GraphQL** desteği.
Güncel İngilizce dokümanda `GraphQL desteği` gibi bir madde yok, dokümanı hızlıca kontrol edebilir misin, hata olmasın.

2023-10-21 18:53 UTC, hasansezertasan commented on docs/tr/docs/features.md
> +* Başlatma ve kapatma anında kod çalıştırabilme(startup and shutdown).
Parantez kuralımızı unutmayalım.

2023-10-21 18:53 UTC, hasansezertasan commented on docs/tr/docs/features.md
>  * **CORS**, GZip, Static dosyalar, Streaming responseları.
`response` yerine => `yanıt` kullanalım. Doküman öğretici amacıyla birlikte geliyor, anlatımda günlük dile uygun olmalı.

2023-10-21 18:53 UTC, hasansezertasan commented on docs/tr/docs/features.md
>  * **Session and Cookie** desteği.
`cookie` => `Çerezler`

2023-10-21 18:53 UTC, hasansezertasan commented on docs/tr/docs/features.md
> +* Bütün kod tabanı 100% test ile kapsanmıştır.
`Kod tabanının tamamı...` gibi bir kullanım daha uygun olacaktır.

2023-10-21 18:53 UTC, hasansezertasan commented on docs/tr/docs/features.md
> +* Bütün kod tabanı 100% tip belirteçleriyle desteklenmiştir.
`Kod tabanının tamamı...` gibi bir kullanım daha uygun olacaktır.

2023-10-21 18:53 UTC, hasansezertasan commented on docs/tr/docs/features.md
> +* Bütün kod tabanı 100% test ile kapsanmıştır.
`Kod tabanının tamamı...` gibi bir kullanım daha uygun olacaktır.

2023-10-21 18:53 UTC, hasansezertasan commented on docs/tr/docs/features.md
> +* Bütün kod tabanı 100% tip belirteçleriyle desteklenmiştir.
`Kod tabanının tamamı...` gibi bir kullanım daha uygun olacaktır.

2023-10-21 18:53 UTC, hasansezertasan commented on docs/tr/docs/features.md
> +**FastAPI**  <a href="https://pydantic-docs.helpmanual.io" class="external-link" target="_blank"><strong>Pydantic</strong></a> ile tamamen uyumlu ve üzerine kuruludur. Yani FastAPI üzerine ekleme yap
Yukarıda aynı yapı için `üzerine kurulu` burada ise `üzerine kuruludur` kullanılmış.

`Yani FastAPI üzerine ekleme yapacağınız herhangi bir Pydantic kodu da çalışacaktır.` => `Sonuç olarak sahip olduğunuz herhangi bir Pydantic kodu FastAPI ile birlikte çalışacaktır.`

2023-10-21 18:53 UTC, hasansezertasan commented on docs/tr/docs/features.md
>  Bunlara Pydantic üzerine kurulu <abbr title="Object-Relational Mapper">ORM</abbr> databaseler ve , <abbr title="Object-Document Mapper">ODM</abbr> kütüphaneler de dahil olmak üzere.
Virgülden önce boşluk kullanılmış.

`Bunların içerisinde Pydantic üzerine kurulu <abbr title="Object-Relational Mapper">ORM</abbr> ve, <abbr title="Object-Document Mapper">ODM</abbr> veritabanları da dahil.`

Böyle güncelleyelim.

2023-10-21 18:53 UTC, hasansezertasan commented on docs/tr/docs/features.md
>  * **Kafa karıştırmaz**:
188:192 kontrol edilmeli.

2023-10-21 18:53 UTC, hasansezertasan commented on docs/tr/docs/features.md
>      * Farklı bir syntax öğrenmenize gerek kalmaz,
Bu satır sonunda virgül, sonraki satırların sonunda nokta kullanılmış.

Syntax yerine `sözdizimi` kullanıyoruz.

Aşağıda ki kısımlarda en güncel en/docs/index.md ile uyumlu değil, eşit değil.

2023-10-22 11:38 UTC, BilalAlpaslan commented on docs/tr/docs/features.md
> +* Ayrıca bu bir çok dilde kullanılabilecek **client code generation** kullanımına da izin veriyor.
ne olarak çevirebiliriz, `istemci kodunun otomatik oluşturulması` dendiğinden ben `clint code generator` olduğunu anlamıyorum, bide eski ceviri de öyle bırakmıştı, aklında daha uygun bi çeviri gelmeyince review e bıraktım

2023-10-22 11:39 UTC, BilalAlpaslan commented on docs/tr/docs/features.md
> +* <a href="https://github.com/OAI/OpenAPI-Specification" class="external-link" target="_blank"><strong>OpenAPI</strong></a> oluşturduğumuz <abbr title="also known as: endpoints, routes">path</abbr> <
Bence bu satırın üzerinde ayrıca bi kafa yormak gerek, çok anlaşılabilir bir bölüm değil anlatılmak isteneni sıfırdan yazsak daha iyi olabilir.

2023-10-22 11:46 UTC, BilalAlpaslan commented on docs/tr/docs/features.md
> +OpenAPI standartlarına dayalı bir framework olarak, geliştiricilerin birden çok seçeneği var, varsayılan olarak gelen 2 farklı interaktif API dokümantasyonu ve web kullanıcı arayüzü var.
çok daha iyi

2023-10-22 11:57 UTC, BilalAlpaslan commented on docs/tr/docs/features.md
> +* Bunlar gibi en yabancıl tiplerle bile doğrulama yapabiliyorsunuz.:
normalde egzotik yazıyordu, tam anlamını yabancıl karşılıyor. verilmek istenen anlam `çok sık kullanılmayan çeşitli tiplerle bile`. belki bu olabilir

2023-10-22 12:23 UTC, BilalAlpaslan commented on docs/tr/docs/features.md
> +Tamamen **Python 3.8**'nın tip belirteçlerine dayanıyor (Pydantic'in sayesinde). Yeni bir syntax öğrenmene gerek yok. Sadece modern Python.
bende 3.6 yazmıştım aslında, üstünde conflict çıkınca çözerken nerden geldi anlamadım 3.8 yaptım :D

2023-10-22 12:29 UTC, BilalAlpaslan commented on docs/tr/docs/features.md
>  * **Kafa karıştırmaz**:
anlamadım

2023-10-22 12:33 UTC, tiangolo commented
📝 Docs preview for commit f56704faea552c378ec7829f1b68d9ebbd8ca8c3 at: https://005020a8.fastapitiangolo.pages.dev

2023-10-22 18:08 UTC, hasansezertasan commented on docs/tr/docs/features.md
>  * **Kafa karıştırmaz**:
188 ve 192 satırlarının arasını demek istemiştim.

2023-10-22 18:52 UTC, tiangolo commented
📝 Docs preview for commit 573c5805db3ed785f5b28c6f36efd193a3d5da81 at: https://7b3a16f5.fastapitiangolo.pages.dev

2023-10-29 11:10 UTC, hasansezertasan requested changes
Her şey çok güzel görünüyor. Genel anlamda vurguladığım hatalara da göz atabilir misin_

2023-10-29 11:10 UTC, hasansezertasan commented on docs/tr/docs/features.md
> +`FastAPI` aslında `Starlette`'nin alt katmanında kullanan bir üst framework. Eğer Starlette'nin nasıl kullanılacağını biliyorsanız, çoğu işlevini aynı şekilde yapıyor.
FastAPI aslında Starlette'i genişleten bir Framework.

2023-10-29 11:10 UTC, hasansezertasan commented on docs/tr/docs/features.md
> +* Çalışma anında arka planda iş  parçacıkları çalıştırabilme imkanı.
Çift boşluk kullanılmış, bir kaç yerde de gördüm. Düzeltebilir miyiz?

2023-10-29 11:10 UTC, hasansezertasan commented on docs/tr/docs/features.md
> +* **Oturum and Çerez** desteği.
Session'ı oturum olarak çevirmişiz, mükemmel. Dokümanın genelinde kullanılan session kullanımlarını oturum olarak güncelleyebilir miyiz?

2023-10-29 11:10 UTC, hasansezertasan commented on docs/tr/docs/features.md
> +* Kod tabanının tamamen (100%) test ile kapsanmıştır.
Hatalı yüzde yazımı.

2023-10-29 11:10 UTC, hasansezertasan commented on docs/tr/docs/features.md
> +* Kod tabanının tamamen (100%) tip belirteçleriyle desteklenmiştir.
Hatalı yüzde yazımı.

2023-10-29 11:10 UTC, hasansezertasan commented on docs/tr/docs/features.md
> +**FastAPI**  <a href="https://pydantic-docs.helpmanual.io" class="external-link" target="_blank"><strong>Pydantic</strong></a> ile tamamen uyumlu ve üzerine kurulu. Sonuç olarak sahip olduğunuz herha
Fazladan boşluk kullanımı.

2023-10-29 11:10 UTC, hasansezertasan commented on docs/tr/docs/features.md
> +Bunlara Pydantic üzerine kurulu <abbr title="Object-Relational Mapper">ORM</abbr> veritabanları ve , <abbr title="Object-Document Mapper">ODM</abbr> kütüphaneler de dahil olmak üzere.
Virgülden önce boşluk hatası.

2023-10-29 11:10 UTC, hasansezertasan commented on docs/tr/docs/features.md
> +    * Farklı bir sözyazımı öğrenmenize gerek kalmaz,
Bu satır sonunda virgül, sonraki satırların sonunda nokta kullanılmış.

Sözyazımı doğru bir kullanım mı?

2023-10-29 11:10 UTC, hasansezertasan commented on docs/tr/docs/features.md
> +Bunlara Pydantic üzerine kurulu <abbr title="Object-Relational Mapper">ORM</abbr> veritabanları ve , <abbr title="Object-Document Mapper">ODM</abbr> kütüphaneler de dahil olmak üzere.
`Bunların içerisinde Pydantic üzerine kurulu <abbr title="Object-Relational Mapper">ORM</abbr> ve, <abbr title="Object-Document Mapper">ODM</abbr> veritabanları da dahil.`

Şeklinde güncelleyebilir miyiz?

2023-10-29 11:10 UTC, hasansezertasan commented on docs/tr/docs/features.md
>  **FastAPI** ile beraber **Pydantic**'in bütün özelliklerine sahip olacaksınız (FastAPI data kontrolünü Pydantic'in üzerine kurduğu için):
data => veri

2023-10-29 11:10 UTC, hasansezertasan commented on docs/tr/docs/features.md
> +    * Pydantic'in veri yapıları aslında sadece senin tanımladığın classlar; Bu yüzden doğrulanmış dataların ile otomatik tamamlama, linting ve mypy'ı kullanarak sorunsuz bir şekilde çalışabilirsin.
`...classlar...` => `...sınıflar...`

2023-10-29 11:10 UTC, hasansezertasan commented on docs/tr/docs/features.md
>      * Hiyerarşik Pydantic modellerinin kullanımı ile beraber, Python `typing`’s `List` and `Dict`, vs gibi şeyleri doğrula.
Burayı dikkatlice okuyup tekrar çevirmeni tavsiye ediyorum, çevirmeyi unuttuğumuz yerler var.

2024-01-31 13:35 UTC, tiangolo commented
As this PR had requested changes to be applied but has been inactive for a while, it's now going to be closed. But if there's anyone interested, feel free to create a new PR.

2024-01-31 13:35 UTC, closed without merging