:globe_with_meridians: Add Turkish translation for `docs/tr/docs/alternatives.md`
fastapi/fastapi pull request #10502
Opened 2023-10-23 17:48 UTC by alperiox

Kafami karistiran bir iki farkli yaklasimi ceviri icerisinde denedim, ornegin orijinal dokumanlarda `abbr` tag'ini bazi kavramlar icin bir kac defa kullanip sonrasinda kullanmayi birakiyordu, ben de buna benzer bir yaklasim sergilemeye calistim. Bunun disinda haddimden fazla yerellestirme yapmis olabilirim, incelemenizde lutfen acimayin ki ortaya duzgun bir sey ciksin 😄

2023-10-23 17:56 UTC, tiangolo commented
📝 Docs preview for commit 121e6d6a9ed2176615b308489cc8953790ab72ff at: https://88cd7bfd.fastapitiangolo.pages.dev

2023-10-24 21:50 UTC, hasansezertasan requested changes
Satır sayıları ana doküman ile eşit değil, çeviri değerlendirmesi yapacağımız zaman satır numarasını referans alıyoruz, aynı şekilde ana doküman güncellendiğinde güncellenen noktaları tespit etmek için satır numaralarını referans alıyoruz. Güncel dokümana uygun bir şekilde satır sayılarını bozmadan çeviriyi güncelleyebilir misin?

2024-01-15 06:14 UTC, hasansezertasan requested changes
Dosyanın başına şu kısmı ekleyelim lütfen:

```markdown
---
hide:
  - navigation
---
```

Review'imi yarıda bırakıyorum. Dosyada tarihi geçmiş alanlar mevcut. Ne zaman ilgilenebilirsin @alperiox?

2024-01-15 06:14 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +Flask bir <abbr title="Mikro Framework: Micro Framework">mikro framework</abbr> olduğundan Django gibi framework'lerin aksine veritabanı integrasyonu gibi Django ile gelen pek çok özelliği direkt sağ
```suggestion
Flask bir <abbr title="Mikro Framework: Micro Framework">mikro framework</abbr> olduğundan Django gibi framework'lerin aksine veritabanı entegrasyonu gibi Django ile gelen pek çok özelliği barındırmaz.
```

2024-01-15 06:14 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +Yapısı oldukça basit olduğundan öğrenmesi de nispeten basittir, tabii dökümantasyon bazı noktalarda biraz teknik hale geliyor.
```suggestion
Yapısı oldukça basit olduğundan öğrenmesi de nispeten basittir, tabii dökümantasyonu bazı noktalarda biraz teknikleşmeye başlıyor.
```

2024-01-15 06:14 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +Flask'ın basitliği göz önünde bulundurulduğu zaman, API geliştirmek için iyi bir eşleşme gibi görünüyordu. Bulunacak bir sonraki şey ise Flask için bir "Django REST Framework"!
```suggestion
Flask, basitliği göz önünde bulundurulduğu zaman, API geliştirmek için iyi bir seçim gibi görünüyordu. Sıradaki şey ise Flask için bir "Django REST Framework"!
```

2024-01-15 06:14 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +    Basit ve kullanması kolay bir <abbr title="Yönlendirme: Routing">routing sistemine</abbr> sahip olmalı.
```suggestion
    Basit ve kullanması kolay bir <abbr title="Yönlendirme: Routing">yönlendirme sistemine</abbr> sahip olmalı.
```

2024-01-15 06:14 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +Birbirlerini, zıt uçlarda olmalarına rağmen az çok tamamlıyorlar.
```suggestion
Öyle yada böyle zıt uçlarda olmalarına rağmen birbirlerini tamamlıyorlar.
```

2024-01-15 06:14 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +Kullanım şekli bayağı basit. Örneğin bir `GET` isteği yapmak için aşağıdaki yeterli:
```suggestion
Kullanım şekli oldukça basit. Örneğin bir `GET` isteği yapmak için aşağıdaki yeterli:
```

2024-01-15 06:14 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +    Örneğin <a href="https://www.buildwithfern.com/?utm_source=tiangolo&utm_medium=website&utm_campaign=docs-alternatives" class="external-link" target="_blank">Fern</a>'i deneyebilirisiniz, kendisi
Outdated.

2024-01-23 07:57 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +Eğer geçmişte diğerlerinin yaptığı çalışmalar olmasaydı **FastAPI**'da var olamazdı.
```suggestion
Başkalarının daha önceki çalışmaları olmasaydı, **FastAPI** var olmazdı.
```

2024-01-23 12:44 UTC, tiangolo commented
📝 Docs preview for commit 88c6d84911a4bc17f7fe3723ff57e9f692ddf492 at: https://8d96dfce.fastapitiangolo.pages.dev

2024-01-23 13:39 UTC, tiangolo commented
📝 Docs preview for commit ced982a7a3f540bbad91a844e4b55bf9b220294f at: https://8e3e519d.fastapitiangolo.pages.dev

2024-01-23 15:00 UTC, alperiox commented on docs/tr/docs/alternatives.md
> +Yapısı oldukça basit olduğundan öğrenmesi de nispeten basittir, tabii dökümantasyon bazı noktalarda biraz teknik hale geliyor.
teknikleşmek diye bir kelime yok bildiğim kadarıyla, sıfat olarak bence 'teknik hale geliyor' daha doğru.

2024-01-23 15:03 UTC, alperiox commented on docs/tr/docs/alternatives.md
> +Ancak bir noktada, geçmişteki diğer araçlardan en iyi fikirleri alarak bütün bu çözümleri kapsayan, ayrıca bütün bunları Python'ın daha önce mevcut olmayan özelliklerini (Python 3.6+ ile gelen <abbr
'bir' kullanmaya gerek yok.

2024-01-23 17:12 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +Flask'ın basitliği göz önünde bulundurulduğu zaman, API geliştirmek için iyi bir eşleşme gibi görünüyordu. Bulunacak bir sonraki şey ise Flask için bir "Django REST Framework"!
@alperiox Burası hakkında ne düşünüyorsun?

2024-01-23 18:19 UTC, hasansezertasan requested changes
Garip ama "dosyanın başına şu kısmı ekleyelim lütfen" dediğim blok orjinal dosyadan kaldırılmış...

```markdown
---
hide:
  - navigation
---
```

Yine yarıda bırakıyorum, bunun için üzgünüm. Yarın devam edeceğim. Eline sağlık 😇

2024-01-24 21:22 UTC, alperiox commented on docs/tr/docs/alternatives.md
> +API'ların ihtiyacı olan bir diğer önemli özellik ise gelen isteklerdeki verileri Python objelerine ayrıştırabilmektir (<abbr title="Parsing: dönüştürmek, ayrıştırmak, çözümlemek">parsing</abbr>, <abb
aynı metin :D, [orijinal metinde](https://github.com/tiangolo/fastapi/blob/master/docs/en/docs/alternatives.md#webargs) de hemen üstte Webargs yer alıyor.

2024-01-24 21:34 UTC, tiangolo commented
📝 Docs preview for commit 03e7b2dfda6779e5c4db649dd11bd52439ae0152 at: https://fd75c3b9.fastapitiangolo.pages.dev

2024-01-24 21:36 UTC, alperiox commented on docs/tr/docs/alternatives.md
> +Şemanın tanımını <abbr title="Route: HTTP isteğinin gittiği yol">route</abbr>'u işleyen her bir fonksiyonun <abbr title="Döküman dizesi: docstring">döküman dizesinin</abbr> içine YAML formatında olac
Evet, 'yürüten' veya 'sunan' gibi alternatifler kullanılabilir. Sanki 'sunan' daha iyi bir alternatif oluyor fakat karar veremedim. 

Açıkçası ben çevirileri karşılaştırırken sorun yaşamıyorum, dolayısıyla satır numaraları arasındaki farkı çok abartmadıkça sorun olduğunu düşünmüyorum.

2024-01-24 21:39 UTC, alperiox commented on docs/tr/docs/alternatives.md
> +Böylece Flask-apispec, Python döküman dizilerine YAML gibi farklı bir syntax yazma sorununu çözmüş oldu.
Evet, aralarında anlamca bir fark yok. Sözdizimi demek daha doğru gözüküyor, ona geçelim.

2024-01-24 21:52 UTC, tiangolo commented
📝 Docs preview for commit 49c0ceb5a3704f6c06b4df44385abc0d0fcda15b at: https://2cdb64e8.fastapitiangolo.pages.dev

2024-01-24 22:15 UTC, tiangolo commented
📝 Docs preview for commit 7b9dfc3be6b7180d1ead298b4df5030869b7c8d7 at: https://b36663fa.fastapitiangolo.pages.dev

2024-01-24 22:37 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +API'ların ihtiyacı olan bir diğer önemli özellik ise gelen isteklerdeki verileri Python objelerine ayrıştırabilmektir (<abbr title="Parsing: dönüştürmek, ayrıştırmak, çözümlemek">parsing</abbr>, <abb
Hmm, burada iki adet kısaltma kullanılmış ancak orjinalinde tek ve orjinalinde "data parsing". Bu kısaltmaları "ayrıştırabilmek" kelimesinde `abbr` etiketiyle kullansak nasıl olur?

2024-01-24 22:40 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +Şemanın tanımını <abbr title="Route: HTTP isteğinin gittiği yol">route</abbr>'u işleyen her bir fonksiyonun <abbr title="Döküman dizesi: docstring">döküman dizesinin</abbr> içine YAML formatında olac
> Evet, 'yürüten' veya 'sunan' gibi alternatifler kullanılabilir. Sanki 'sunan' daha iyi bir alternatif oluyor fakat karar veremedim.

```suggestion
Şemanın tanımını <abbr title="Route: HTTP isteğinin gittiği yol">yol</abbr>'a istek geldiğinde çalışan her bir fonksiyonun <abbr title="Döküman dizesi: docstring">döküman dizesinin</abbr> içine YAML formatında olacak şekilde yazıyorsunuz o da OpenAPI şemaları üretiyor.
```

Biraz uzatmış oluyoruz ancak hedeflenen anlamı daha iyi sunuyor diye düşünüyorum. Ne diyorsun?

> Açıkçası ben çevirileri karşılaştırırken sorun yaşamıyorum, dolayısıyla satır numaraları arasındaki farkı çok abartmadıkça sorun olduğunu düşünmüyorum.

Yine de sürdürülebilirlik için satır sayılarına saygı duymamız gerektiğini düşünüyorum. Burada bana yardımcı olabilirsen çok sevinirim 🚀.

2024-01-24 22:49 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +API'ların ihtiyacı olan bir diğer önemli özellik ise gelen isteklerdeki verileri Python objelerine ayrıştırabilmektir (<abbr title="Parsing: dönüştürmek, ayrıştırmak, çözümlemek">parsing</abbr>, <abb
```suggestion
API'ların ihtiyacı olan bir diğer önemli özellik ise gelen isteklerdeki verileri Python objelerine <abbr title="Parsing: dönüştürmek, ayrıştırmak, çözümlemek">dönüştürebilmektir</abbr>.
```

```suggestion
API'ların ihtiyacı olan bir diğer önemli konu ise <abbr title="Parsing: dönüştürmek, ayrıştırmak, çözümlemek">parsing</abbr> olarak bilinen, gelen isteklerdeki verileri Python objelerine dönüştürebilme özelliğidir.
```

Bunlar kulağa nasıl geliyor?

2024-01-24 23:00 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +Böylece Flask-apispec, Python döküman dizilerine YAML gibi farklı bir syntax yazma sorununu çözmüş oldu.
@alperiox rica etsem bu detayı ve ayrım kriterini sunucuda not düşebilir misin? Sonraki çevirilerde bu konuda hata yapabilirmişim gibi geliyor.

2024-01-25 06:27 UTC, alperiox commented on docs/tr/docs/alternatives.md
> +Şemanın tanımını <abbr title="Route: HTTP isteğinin gittiği yol">route</abbr>'u işleyen her bir fonksiyonun <abbr title="Döküman dizesi: docstring">döküman dizesinin</abbr> içine YAML formatında olac
Evet, bence de bu şekilde çevirmek daha mantıklı. Ancak satır sayılarının eşitliğinin bu fark çok abartılmadığı sürece sürdürülebilirliğe etkisi olduğunu düşünmüyorum. Sonuçta arada 15-20 satır fark olsa dahi bunu yakalamak oldukça kolay ve yapılan çeviri sıklığı bunun yorucu olmasını büyük ölçüde engelliyor.

2024-01-25 06:33 UTC, tiangolo commented
📝 Docs preview for commit add6aa7b5cf12e2d9ba722eb3e84363c13e07309 at: https://8d3d0eae.fastapitiangolo.pages.dev

2024-01-25 06:40 UTC, alperiox commented on docs/tr/docs/alternatives.md
> +API'ların ihtiyacı olan bir diğer önemli özellik ise gelen isteklerdeki verileri Python objelerine ayrıştırabilmektir (<abbr title="Parsing: dönüştürmek, ayrıştırmak, çözümlemek">parsing</abbr>, <abb
'route' u direkt Türkçeye çevirdik fakat burada 'parsing' i bırakıyoruz, bunun gerekli olup olmadığından emin değilim. 'özellik' demek daha doğru, sonuçta bu API'ya ait bir özellik; bir şeyin bir konuya ihtiyaç duyması ne demek? Ayrıca çeviri içerisinde 'serialization' u 'veri dönüştürme' olarak çevirdiğimden, 'ayrıştırabilmek' kafa karışıklığı yaratmamak adına daha iyi bir seçenek gibi görünüyor.

2024-01-25 08:39 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +API'ların ihtiyacı olan bir diğer önemli özellik ise gelen isteklerdeki verileri Python objelerine ayrıştırabilmektir (<abbr title="Parsing: dönüştürmek, ayrıştırmak, çözümlemek">parsing</abbr>, <abb
> 'route' u direkt Türkçeye çevirdik fakat burada 'parsing' i bırakıyoruz, bunun gerekli olup olmadığından emin değilim.

Okuyucu gözünden İngilizce bilmeyen birisi için "route" neyse "parsing" de odur gibi düşünüyorum.

>'özellik' demek daha doğru, sonuçta bu API'ya ait bir özellik; bir şeyin bir konuya ihtiyaç duyması ne demek?

Deneme yapıyordum...

> Ayrıca çeviri içerisinde 'serialization' u 'veri dönüştürme' olarak çevirdiğimden, 'ayrıştırabilmek' kafa karışıklığı yaratmamak adına daha iyi bir seçenek gibi görünüyor.

Haklısın ancak burada kavramlar zaten iç içe girmiyor mu? Bu dönüştürmeyi direkt senin kısaltma notlarından aldım orada "Parsing: dönüştürmek, ayrıştırmak, çözümlemek" demişsin. Çözümlemek de diyebiliriz.

Velhasıl burada "data" ve "data parsing" için ayrı ayrı kısaltma olması gerekli değil. "data parsing"'e yer verilmediği ve "data" yı da "veri" olarak çevirdiğimiz için "parsing"'i çevirip kısaltma notu düşmemiz gerektiğini düşünüyorum.

2024-01-25 08:42 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +Şemanın tanımını <abbr title="Route: HTTP isteğinin gittiği yol">route</abbr>'u işleyen her bir fonksiyonun <abbr title="Döküman dizesi: docstring">döküman dizesinin</abbr> içine YAML formatında olac
O zaman daha önce konuştuğumuz mevzu, satır sayılarını eşit tutmak için yorum satırı bırakmak... Bununla ilgilenebilir misin?

2024-01-25 08:45 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +API'ların ihtiyacı olan bir diğer önemli özellik ise gelen isteklerdeki verileri Python objelerine ayrıştırabilmektir (<abbr title="Parsing: dönüştürmek, ayrıştırmak, çözümlemek">parsing</abbr>, <abb
```suggestion
API'ların ihtiyacı olan bir diğer önemli özellik ise gelen isteklerdeki verileri Python objelerine <abbr title="Parsing: dönüştürmek, ayrıştırmak, çözümlemek">ayrıştırabilmektir</abbr>.
```

Böyle yazsan yeterdi aslında.

2024-01-25 09:54 UTC, alperiox commented on docs/tr/docs/alternatives.md
> +API'ların ihtiyacı olan bir diğer önemli özellik ise gelen isteklerdeki verileri Python objelerine ayrıştırabilmektir (<abbr title="Parsing: dönüştürmek, ayrıştırmak, çözümlemek">parsing</abbr>, <abb
> Okuyucu gözünden İngilizce bilmeyen birisi için "route" neyse "parsing" de odur gibi düşünüyorum.

O halde aynı 'route' için Türkçe karşılık kullandığımız gibi 'parsing' için de Türkçe karşılık kullanmamız daha anlamlı olur. O değişikliği de review içerisinde sen belirtmiştin. 

> Bakış açımı iyi bir şekilde aktarabilmek için deneme yapıyordum, ayrıca o cümlede bir sorun görmüyorum, ne demek olduğunu anlamışsındır bence.

Ben tabii ki anlayabiliyorum, fakat bence 'özellik' demek daha açık bir aktarım sağlıyor. Sonuçta halen aynı soru cevapsız, bir şeyin bir konuya ihtiyaç duyması ne demek?

> Haklısın ancak burada kavramlar zaten iç içe girmiyor mu? Şimdiye kadar "serialization" derken aslında tam olarak bu konudan (ve tam tersi süreçten, python'dan json'a gibi) bahsediyorduk. Bu dönüştürmeyi direkt senin kısaltma notlarından aldım orada "Parsing: dönüştürmek, ayrıştırmak, çözümlemek" demişsin. Çözümlemek de diyebiliriz.

İç içe girdikleri için kafa karışıklığı yaratabilir. Ancak bunlar yine de birbirinden farklı kavramlar, parsing genelde gelen data stream'i in-memory data structure haline getirirken daha çok ayrıştırmaya benzer bir süreç izleniyor. İşte atıyorum gelen veriyi array, key-value çiftleri vb. yapılar olarak ayrıştırıyoruz. Serialization ise elimdeki in-memory yapıyı stream edebileceğim bir formata dönüştürmemi sağlıyor. Bu durumda burada 'ayrıştırma' kelimesi daha uygunken 'serialization' çevirisine eklediğim 'parsing' notunu kaldırmam daha anlamlı olacak. 

> Böyle yazsan yeterdi aslında. "data parsing" kısmını bir türlü anlayamadım çünkü türkçe çeviri de o süreci anlatıyoruz. "...gelen isteklerdeki verileri python objelerine..."

Evet, kesinlikle fazlalık olmuş. Onu kaldıralım :D

2024-01-25 10:06 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +API'ların ihtiyacı olan bir diğer önemli özellik ise gelen isteklerdeki verileri Python objelerine ayrıştırabilmektir (<abbr title="Parsing: dönüştürmek, ayrıştırmak, çözümlemek">parsing</abbr>, <abb
> Ben tabii ki anlayabiliyorum, fakat bence 'özellik' demek daha açık bir aktarım sağlıyor. Sonuçta halen aynı soru cevapsız, bir şeyin bir konuya ihtiyaç duyması ne demek?

Orası cümleyi toparlamak için bir denemeydi dediğim gibi. Şöyle bir örnek vereyim, "Mehmetin ihtiyacı olan bir diğer önemli konu/nokta/şey... ise bla bladır."

Doğrudan bir konuya ihtiyaç duymuyor, ihtiyaç duyduğu önemli diğer bir konu ise...

Daha nasıl anlatabilirim bilmiyorum.

2024-01-25 10:06 UTC, hasansezertasan approved these changes

2024-01-25 10:07 UTC, tiangolo commented
📝 Docs preview for commit dca64ba1cd69184188f2898bc0aabeb43122cff1 at: https://04ac286b.fastapitiangolo.pages.dev

2024-01-25 10:11 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +API'ların ihtiyacı olan bir diğer önemli özellik ise gelen isteklerdeki verileri Python objelerine ayrıştırabilmektir (<abbr title="Parsing: dönüştürmek, ayrıştırmak, çözümlemek">parsing</abbr>, <abb
> Evet, kesinlikle fazlalık olmuş. Onu kaldıralım :D

Sadece yardımcı olmaya çalışıyorum. Burada amacım daha iyi bir iş çıkarmamızı (okuyucunun daha kolay bir şekilde anlayabilmesinden geçiyor) sağlamak, alay etmek/edilmek değil. Doğru olduğu konusunda ısrarcı olduğunu görüyorum ve bu çabam son satırınla birlikte anlamsız bir hale geldi.

2024-01-25 10:32 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +API'ların ihtiyacı olan bir diğer önemli özellik ise gelen isteklerdeki verileri Python objelerine ayrıştırabilmektir (<abbr title="Parsing: dönüştürmek, ayrıştırmak, çözümlemek">parsing</abbr>, <abb
> Yardımın için teşekkür ederim, sonuçta ortak amacımız okuyucunun zorlanmayacağı bir içerik sunmak. Alay ettiğini ya da bir tarafın kazanması uğruna ısrarcı olduğumuzu da düşünmüyorum, biz ortaya iyi bir şey çıkması için elimizden geleni yapacağız ki en azından kendi işimizden tatmin olalım :D

Rica ederim, haklısın. Açık kaynağa destekte bulunma konusu kafamı kurcalıyor bugün. Her ne kadar hevesli ve istekli başlamış olsamda gerçekten zor.

> Bunun yanında; attığım emojileri dalga geçmek için atmıyorum, o fazlalığın bu zamana kadar gözümüze çarpmaması komik geldi sadece :D fikirlerin benim için oldukça önemli, yanlış anlaşılma olduysa özür dilerim.

Benim yanlış anlamış gibi görünüyorum, yazı dili sonuçta. Özür dilemene gerek yok gerçekten hatta bu tutumum için ben özür diliyorum, niyetini bilemem ancak o mesajdan algıladığım buydu gerçekten. Tepki göstermeden önce teyit etmem, "bunu mu demek istiyorsun" demem gerekirdi. 😞

Ek olarak, başından beri tek derdim "o fazlalık" idi. 🧆 

Köstek oluyormuşum gibi bir hissiyata kapıldım sadece. Eğer "request review" yaparsan daha sakin bir kafayla review'ime devam edebilirim.

2024-01-25 10:40 UTC, alperiox commented on docs/tr/docs/alternatives.md
> +API'ların ihtiyacı olan bir diğer önemli özellik ise gelen isteklerdeki verileri Python objelerine ayrıştırabilmektir (<abbr title="Parsing: dönüştürmek, ayrıştırmak, çözümlemek">parsing</abbr>, <abb
Köstek olduğunu düşünsem söylemekten çekinmezdim, çözdüğümüze göre sıkıntı yok 🤗

2024-01-25 10:44 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +API'ların ihtiyacı olan bir diğer önemli özellik ise gelen isteklerdeki verileri Python objelerine ayrıştırabilmektir (<abbr title="Parsing: dönüştürmek, ayrıştırmak, çözümlemek">parsing</abbr>, <abb
> Ben tabii ki anlayabiliyorum, fakat bence 'özellik' demek daha açık bir aktarım sağlıyor. Sonuçta halen aynı soru cevapsız, bir şeyin bir konuya ihtiyaç duyması ne demek?

Şöyle cevap vermek istiyorum...

```
API'ların ihtiyacı olan bir diğer önemli konu ise <abbr title="Parsing: dönüştürmek, ayrıştırmak, çözümlemek">parsing</abbr> olarak bilinen, gelen isteklerdeki verileri Python objelerine dönüştürebilme özelliğidir.
```

İhtiyacı olan bir diğer önemli (şey) konu/nokta ise "parsing" olarak bilinen şunu bunu yapan dönüştürebilme özelliğidir.

Burada "konu" ihtiyaç duyulan değilde, ihtiyaç duyulanı işaret eden bir kelime. Yani özünde sorduğun soruyu anlamadım çünkü "bir konuya ihtiyaç duyma" durumu yok, ihtiyaç duyduğu şeyi işaret etme var, "ihtiyaç duyduğu bir diğer önemli "şey" (burada açıklayacağımız için konu dedim) x özelliğidir."

"X programını çalıştırmak için ihtiyaç duyduğumuz bir diğer şey ise Y gücünde bir işlemcidir." gibi aslında ancak "konu" demek gerçekten de doğru görünmüyor ancak "o fazlalık" dediğimiz noktayı vurgulamaya çalışırken sunduğum iki öneriden biriydi, üzerine çok düşünmedim yani.

2024-01-25 12:04 UTC, hasansezertasan requested changes
Sonunda bitti, tamamını bitirdim 🚀

2024-01-25 12:04 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +Bir web framework'ünden ziyade bir sunucudur, yani yollara bağlı routing yapmanızı sağlayan araçları yoktur. Bu daha çok Starlette (ya da **FastAPI**) gibi bir framework'ün sunucuya ek olarak sağladı
```suggestion
Bir web framework'ünden ziyade bir sunucudur, yani yollara bağlı yönlendirme yapmanızı sağlayan araçları yoktur. Bu daha çok Starlette (ya da **FastAPI**) gibi bir framework'ün sunucuya ek olarak sağladığı bir şeydir.
```

2024-01-25 12:04 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +    Daha fazla detay için [Deployment](deployment/index.md){.internal-link target=_blank} bölümünü inceleyebilirsiniz.
"Deployment" sayfasını henüz çevirmedik ancak yakın zamanda oraya bakmak istiyorum. Başlığı böyle bırakıp orayı çevirince oranın başlığıyla mı güncelleyelim yoksa ne yapalım?

2024-01-25 12:04 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +Uvicorn, Starlette ve FastAPI arasındakı farkı daha iyi anlamak ve karşılaştırma yapmak için [Benchmarks](benchmarks.md){.internal-link target=_blank} bölümüne bakın!
```suggestion
Uvicorn, Starlette ve FastAPI arasındakı farkı daha iyi anlamak ve karşılaştırma yapmak için [Kıyaslamalar](benchmarks.md){.internal-link target=_blank} bölümüne bakın!
```

"Benchmarks" sayfası çevirildi 👍

2024-01-26 05:28 UTC, alperiox commented on docs/tr/docs/alternatives.md
> +Bu Python bile değil. NestJS, Angulardan ilham almış olan bir JavaScript (TypeScript) NodeJS framework'ü.
'Bu İngilizce bile değil' der gibi düşünmüştüm :D Ancak evet, 'Bu Python ekosisteminde bile değil' veya 'Bu Python teknolojisi bile değil' gibi alternatifler tercih edilebilir.

2024-01-26 05:32 UTC, alperiox commented on docs/tr/docs/alternatives.md
> +    Tam da bu yüzden **FastAPI** Starlette'e dayanıyor, çünkü Starlette şu anda kullanılabir en hızlı framework. (üçüncü parti karşılaştırmalı değerlendirmelerce test edildi)
```suggestion
    Tam da bu yüzden **FastAPI** Starlette'e dayanıyor, çünkü Starlette şu anda kullanılabilir en hızlı framework. (üçüncü parti karşılaştırmalı testlerine göre)
```
Daha iyi olabilir sanki, parantezi cümle içerisine yerleştirince biraz akışı bozuyor gibi.

2024-01-26 05:34 UTC, alperiox commented on docs/tr/docs/alternatives.md
> +    Yani, Starlette ile yapabileceğiniz her şeyi, Starlette'in bir nevi güçlendirilmiş hali olan **FastAPI** ile doğrudan yapabilirsiniz.
Direkt Türkçe çevirisi yok onun, bence de gerek yok :D

2024-01-26 05:35 UTC, alperiox commented on docs/tr/docs/alternatives.md
> +    Daha fazla detay için [Deployment](deployment/index.md){.internal-link target=_blank} bölümünü inceleyebilirsiniz.
Çevirince güncelleriz.

2024-01-26 05:45 UTC, tiangolo commented
📝 Docs preview for commit ada79e684085b8f762522a9def6039de04510030 at: https://0140430d.fastapitiangolo.pages.dev

2024-01-26 13:40 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +Bu Python bile değil. NestJS, Angulardan ilham almış olan bir JavaScript (TypeScript) NodeJS framework'ü.
> 'Bu İngilizce bile değil' der gibi düşünmüştüm :D Ancak evet, 'Bu Python ekosisteminde bile değil' veya 'Bu Python teknolojisi bile değil' gibi alternatifler tercih edilebilir.

Bak öyle düşünmemiştim hiç. Şahane nokta 👏.

2024-01-26 13:41 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +Bu Python bile değil. NestJS, Angulardan ilham almış olan bir JavaScript (TypeScript) NodeJS framework'ü.
```suggestion
Bu Python teknolojisi bile değil. NestJS, Angulardan ilham almış olan bir JavaScript (TypeScript) NodeJS framework'ü.
```

2024-01-26 13:44 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +    Tam da bu yüzden **FastAPI** Starlette'e dayanıyor, çünkü Starlette şu anda kullanılabir en hızlı framework. (üçüncü parti karşılaştırmalı değerlendirmelerce test edildi)
Hmm, nasıl uygun görüyorsan. Burada beni rahatsız eden tek şey cümle "bittikten" sonra bir parantez içerisinde o cümleyle ilgili bilgi almak. Genelde 2 defa okumama sebebiyet veriyor. Bu dokümantasyonda çok fazla parantez kullanılmış, can sıkıcı.

2024-01-26 13:50 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +    Yani, Starlette ile yapabileceğiniz her şeyi, Starlette'in bir nevi güçlendirilmiş hali olan **FastAPI** ile doğrudan yapabilirsiniz.
Bunu resolved olarak işaretler misin?

2024-01-26 13:50 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +    Daha fazla detay için [Deployment](deployment/index.md){.internal-link target=_blank} bölümünü inceleyebilirsiniz.
Tamamdır, resolved olarak işaretler misin?

2024-01-26 13:58 UTC, alperiox commented on docs/tr/docs/alternatives.md
> +    Hug, Python dosyalarını otomatik olarak sıralayan harika bir araç olan  <a href="https://github.com/timothycrosley/isort" class="external-link" target="_blank">`isort`</a>'un geliştiricisi Timoth
Ben aralarında bir fark göremiyorum fakat 'geliştirildi' kullanılabilir, 'dahil etme satırları' daha açıklayıcı gözüküyor.

2024-01-26 13:59 UTC, alperiox commented on docs/tr/docs/alternatives.md
> +Otomatik veri doğrulama, veri dönüştürme ve farklı yerlerdeki tip belirteçlerine bağlı olarak OpenAPI şeması oluşturma desteği sunuyordu.
Bilmiyordum, düzeltme için teşekkürler.

2024-01-26 14:19 UTC, alperiox commented on docs/tr/docs/alternatives.md
> +    Ben bu önceki araçlardan öğrendiklerime dayanarak **FastAPI**'ın özelliklerini arttırıp geliştiriyor, typing sistemini ve diğer kısımları iyileştiriyorum ancak yine de **FastAPI**'ı APIStar'ın "r
[Bu](https://hasansezertasan.github.io/fastapi-turkiye/translation-notes/) sayfada bulamadım

2024-01-26 14:21 UTC, alperiox commented on docs/tr/docs/alternatives.md
> +* Kodun %100'ünde kullanılan veri tipleri açıklanıyor.
Sözlük sayfasında bir karşılığa denk gelmedim, burada içeriğe uyuyor gibi gözüküyor.

2024-01-26 14:22 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +İki parametre kabul eden fonksiyonler şeklide tasarlandı, biri "istek" ve diğeri ise "cevap". Sonra isteğin çeşitli kısımlarını **okuyup** cevaba **yazıyorsunuz**. Bu dizayndan dolayı istek parametre
Şahane görünüyor.

2024-01-26 14:26 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +* Kodun %100'ünde kullanılan veri tipleri açıklanıyor.
Bura kaldı.

2024-01-26 14:26 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +    Ben bu önceki araçlardan öğrendiklerime dayanarak **FastAPI**'ın özelliklerini arttırıp geliştiriyor, typing sistemini ve diğer kısımları iyileştiriyorum ancak yine de **FastAPI**'ı APIStar'ın "r
Bura kaldı.

2024-01-26 14:26 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +Biraz daha detaylı ayarlamalara gerek duyuyor. Ayrıca <abbr title="ASGI (Asynchronous Server Gateway Interface): Asenkron Sunucu Ağ Geçidi Arabirimi, asenkron Python web uygulamaları geliştirmek için
Bura kaldı, ard arda boşluk.

2024-01-26 14:27 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +Biraz daha detaylı ayarlamalara gerek duyuyor. Ayrıca <abbr title="ASGI (Asynchronous Server Gateway Interface): Asenkron Sunucu Ağ Geçidi Arabirimi, asenkron Python web uygulamaları geliştirmek için
```suggestion
Biraz daha detaylı ayarlamalara gerek duyuyor. Ayrıca <abbr title="ASGI (Asynchronous Server Gateway Interface): Asenkron Sunucu Ağ Geçidi Arabirimi, asenkron Python web uygulamaları geliştirmek için yeni standart.">ASGI</abbr> yerine <abbr title="WSGI (Web Server Gateway Interface): Web Sunucusu Ağ Geçidi Arabirimi, Pythonda senkron web uygulamaları geliştirmek için eski standart.">WSGI</abbr>'a dayanıyor. Yani Uvicorn, Starlette ve Sanic gibi araçların yüksek performansından faydalanacak şekilde tasarlanmamış.
```

2024-01-26 14:29 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +    Ben bu önceki araçlardan öğrendiklerime dayanarak **FastAPI**'ın özelliklerini arttırıp geliştiriyor, typing sistemini ve diğer kısımları iyileştiriyorum ancak yine de **FastAPI**'ı APIStar'ın "r
bunu bi incelemek istiyorum. Döneceğim.

2024-01-26 14:31 UTC, tiangolo commented
📝 Docs preview for commit 4c871702a100bfe668513ebd1c24762f53c8f910 at: https://01de0dd0.fastapitiangolo.pages.dev

2024-01-26 14:38 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +    Ben bu önceki araçlardan öğrendiklerime dayanarak **FastAPI**'ın özelliklerini arttırıp geliştiriyor, typing sistemini ve diğer kısımları iyileştiriyorum ancak yine de **FastAPI**'ı APIStar'ın "r
Tüm dokümantasyona baktım, `typing system` tek bir defa kullanılmış o yüzden çok düşünmeye gerek yok ancak burada `typing system`'den kasıt ne? Benim algıladığım `tip desteği sistemi`. Sen ne düşünüyorsun?

Koca dokümanda "typing system" bir defa geçerken, onu da İngilizce bırakmayalım bence.

2024-01-26 14:43 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +* Kodun %100'ünde kullanılan veri tipleri açıklanıyor.
Bura için bir inceleme yaptım. `Annotated` önceki kullanımlarda `tipleri belirtilmiş` olarak kullanılmış. `Annotated` veri tipleriyle ilgili olduğu için aklıma ilk gelen benzeri `type annotations` oldu. Orjinalinde de zaten `100% type annotated codebase.` denilmiş.

```suggestion
* Kodun %100'ünde tip belirteçleri kullanıldı.
```

Bu kulağa nasıl geliyor?

2024-01-26 14:48 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +* Kodun %100'ünde kullanılan veri tipleri açıklanıyor.
Hatta şöyle bir ekleme yapayım, [burada](https://github.com/tiangolo/fastapi/pull/10492/files) da şöyle bir çeviri gerçekleştirilmiş:

```diff
- * 100% type annotated codebase.
+ * Kod tabanının tamamen (100%) tip belirteçleriyle desteklenmiştir.
```

2024-01-26 14:50 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +    Ben bu önceki araçlardan öğrendiklerime dayanarak **FastAPI**'ın özelliklerini arttırıp geliştiriyor, typing sistemini ve diğer kısımları iyileştiriyorum ancak yine de **FastAPI**'ı APIStar'ın "r
```suggestion
    Ben bu önceki araçlardan öğrendiklerime dayanarak **FastAPI**'ın özelliklerini arttırıp geliştiriyor, tip desteği sistemini ve diğer kısımları iyileştiriyorum ancak yine de **FastAPI**'ı APIStar'ın "ruhani varisi" olarak görüyorum.
```

2024-01-26 14:51 UTC, alperiox commented on docs/tr/docs/alternatives.md
> +    Ben bu önceki araçlardan öğrendiklerime dayanarak **FastAPI**'ın özelliklerini arttırıp geliştiriyor, typing sistemini ve diğer kısımları iyileştiriyorum ancak yine de **FastAPI**'ı APIStar'ın "r
```suggestion
    Ben bu önceki araçlardan öğrendiklerime dayanarak **FastAPI**'ın özelliklerini arttırıp geliştiriyor, veri tipi sistemini ve diğer kısımları iyileştiriyorum ancak yine de **FastAPI**'ı APIStar'ın "ruhani varisi" olarak görüyorum.
```

Kulağa nasıl geliyor?

2024-01-26 14:54 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +    Ben bu önceki araçlardan öğrendiklerime dayanarak **FastAPI**'ın özelliklerini arttırıp geliştiriyor, typing sistemini ve diğer kısımları iyileştiriyorum ancak yine de **FastAPI**'ı APIStar'ın "r
"veri tipi sistemi", burada algıda karmaşa olabilir diye düşnüüyorum. Çünkü veri tipi sistemi programlamada çok genel bir konu ancak burada bahsedilen şey yönlendirme fonksiyonlarında kullanılan parametrelere veri tipi tanımlama ve bunu kullanarak veri doğrulama, dönüştürme uygulama.

2024-01-26 14:55 UTC, alperiox commented on docs/tr/docs/alternatives.md
> +* Kodun %100'ünde kullanılan veri tipleri açıklanıyor.
```suggestion
* Kodun %100'ü tip belirteçleriyle desteklenmiştir.
```

Diyorum, çünkü bir önceki maddede de yüzdelik gösterim üzerinden çeviriye devam edilmiş.

2024-01-26 14:57 UTC, alperiox commented on docs/tr/docs/alternatives.md
> +    Ben bu önceki araçlardan öğrendiklerime dayanarak **FastAPI**'ın özelliklerini arttırıp geliştiriyor, typing sistemini ve diğer kısımları iyileştiriyorum ancak yine de **FastAPI**'ı APIStar'ın "r
Evet karmaşık olabilir fakat tip desteği sistemi ne demek ki? 'veri tipi belirtme sistemi' falan mı desek?

2024-01-26 14:57 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +* Kodun %100'ünde kullanılan veri tipleri açıklanıyor.
Gönder gitsin 👍

2024-01-26 15:04 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +    Ben bu önceki araçlardan öğrendiklerime dayanarak **FastAPI**'ın özelliklerini arttırıp geliştiriyor, typing sistemini ve diğer kısımları iyileştiriyorum ancak yine de **FastAPI**'ı APIStar'ın "r
> Evet karmaşık olabilir fakat tip desteği sistemi ne demek ki? 'veri tipi belirtme sistemi' falan mı desek?

Doğru, aslında burada ki tip belirtme sistemi uzaktan "type safety"'ye uzanıyor.

İlk soruna cevap olsun: sen bilmiyorsun ama "tip desteği" deyince aklıma "typing support" geliyor. İngilizce haliyle böyle kullanılıyor genellikle. O yüzden "tip desteği" dedim. Senin veya okuyucunun aklına ilk başta soru işareti getirebilir ancak bu dokümanı okudukça öğrenecek bunu da.

`tip desteği sistemi` yazıp, `tip desteği`'ni abbr ile açıklasan nasıl olur?

2024-01-26 15:06 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +    Ben bu önceki araçlardan öğrendiklerime dayanarak **FastAPI**'ın özelliklerini arttırıp geliştiriyor, typing sistemini ve diğer kısımları iyileştiriyorum ancak yine de **FastAPI**'ı APIStar'ın "r
Dur dur...

2024-01-26 15:07 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +    Ben bu önceki araçlardan öğrendiklerime dayanarak **FastAPI**'ın özelliklerini arttırıp geliştiriyor, typing sistemini ve diğer kısımları iyileştiriyorum ancak yine de **FastAPI**'ı APIStar'ın "r
Düz `typing desteği` yazıp, `typing` kelimesini kütüphane olarak değerlendiremez miyiz? Python typing modülü, sonrasında da `typing` kısmına abbr ekleriz?

2024-01-26 15:09 UTC, alperiox commented on docs/tr/docs/alternatives.md
> +    Ben bu önceki araçlardan öğrendiklerime dayanarak **FastAPI**'ın özelliklerini arttırıp geliştiriyor, typing sistemini ve diğer kısımları iyileştiriyorum ancak yine de **FastAPI**'ı APIStar'ın "r
```suggestion
    Ben bu önceki araçlardan öğrendiklerime dayanarak **FastAPI**'ın özelliklerini arttırıp geliştiriyor, <abbr title="Tip desteği (typing support): kod yapısında parametrelere, argümanlara ve objelerin özelliklerine veri tipi atamak">tip desteği sistemi</abbr>ve diğer kısımları iyileştiriyorum ancak yine de **FastAPI**'ı APIStar'ın "ruhani varisi" olarak görüyorum.
```

Bu şekilde fena durmuyor sanırım.

2024-01-26 15:24 UTC, hasansezertasan commented on docs/tr/docs/alternatives.md
> +    Ben bu önceki araçlardan öğrendiklerime dayanarak **FastAPI**'ın özelliklerini arttırıp geliştiriyor, typing sistemini ve diğer kısımları iyileştiriyorum ancak yine de **FastAPI**'ı APIStar'ın "r
```suggestion
    Ben bu önceki araçlardan öğrendiklerime dayanarak **FastAPI**'ın özelliklerini arttırıp geliştiriyor, <abbr title="Tip desteği (typing support): kod yapısında parametrelere, argümanlara ve objelerin özelliklerine veri tipi atamak">tip desteği</abbr> sistemi ve diğer kısımları iyileştiriyorum ancak yine de **FastAPI**'ı APIStar'ın "ruhani varisi" olarak görüyorum.
```

2024-01-26 15:33 UTC, hasansezertasan approved these changes
Thank you @alperiox for this awesome translation 👏. It was very nice to collaborate with you on this project! 🚀 Looking forward to seeing this merged! 🤩 

Müthiş çevirin için sana teşekkür ederim @alperiox 👏. Bu projede seninle işbirliği yapmak oldukça güzeldi! 🚀 Çevirinin yayınlanmasını dört gözle bekliyorum 🤩

2024-01-26 15:35 UTC, tiangolo commented
📝 Docs preview for commit 4b2019ee4a07accf2746394cb3f5b16fba011b3d at: https://eef7d8e2.fastapitiangolo.pages.dev

2024-01-27 09:14 UTC, merged

2024-01-27 09:14 UTC, alejsdev commented
Nice! Thanks @alperiox 🤓🚀 

And thanks for your help @hasansezertasan 🥳💯