🌐 Add Russian translation for `docs/ru/docs/tutorial/dependencies/sub-dependencies.md`
fastapi/fastapi pull request #10515
Opened 2023-10-24 19:55 UTC by AlertRED

…dependencies.md

2023-10-24 20:01 UTC, tiangolo commented
📝 Docs preview for commit f7d8d0ad9bbe3179f1fdc1051ae4890e49d25138 at: https://8c8dc96d.fastapitiangolo.pages.dev

2023-10-25 13:46 UTC, art3xa requested changes

2023-10-25 13:46 UTC, art3xa commented on docs/ru/docs/tutorial/dependencies/sub-dependencies.md
> +Но, тем не менее, эта систиме очень мощная и позволяет вам объявлять вложенные графы (деревья) зависимостей сколь угодно глубоко.
```suggestion
Но, тем не менее, эта систима очень мощная и позволяет вам объявлять вложенные графы (деревья) зависимостей сколь угодно глубоко.
```

2023-10-25 13:46 UTC, art3xa commented on docs/ru/docs/tutorial/dependencies/sub-dependencies.md
> +В расширенном сценарии, когда вы знаете, что вам нужно, чтобы зависимость вызывалась на каждом шаге (возможно, несколько раз) в одном и том же запросе, чтобы не использовать "кэшированное" значение в
```suggestion
В расширенном сценарии, когда вы знаете, что вам нужно, чтобы зависимость вызывалась на каждом шаге (возможно, несколько раз) в одном и том же запросе, вместо использования "кэшированного" значения, вы можете установить параметр `use_cache=False` при использовании `Depends`:
```

2023-10-25 13:54 UTC, art3xa commented on docs/ru/docs/tutorial/dependencies/sub-dependencies.md
> +    Обратите внимание, что мы объявляем только одну зависимость в *функции пути* - `query_or_cookie_extractor`.
```suggestion
    Обратите внимание, что мы объявляем только одну зависимость в *функции операции пути* - `query_or_cookie_extractor`.
```

2023-10-25 13:54 UTC, art3xa commented on docs/ru/docs/tutorial/dependencies/sub-dependencies.md
> +Если одна из ваших зависимостей объявлена несколько раз для одной и той же *функции пути*, например, несколько зависимостей имеют общую подзависимость, **FastAPI** будет знать, что вызывать эту подза
```suggestion
Если одна из ваших зависимостей объявлена несколько раз для одной и той же *функции операции пути*, например, несколько зависимостей имеют общую подзависимость, **FastAPI** будет знать, что вызывать эту подзависимость нужно только один раз за запрос.
```

2023-10-25 13:55 UTC, art3xa commented on docs/ru/docs/tutorial/dependencies/sub-dependencies.md
> +Это просто функции, которые выглядят так же, как *функции путей*.
```suggestion
Это просто функции, которые выглядят так же, как *функции операций путей*.
```

2023-10-25 14:45 UTC, kostyaten commented on docs/ru/docs/tutorial/dependencies/sub-dependencies.md
> +Но, тем не менее, эта систиме очень мощная и позволяет вам объявлять вложенные графы (деревья) зависимостей сколь угодно глубоко.
Может все таки "система"?

2023-10-25 15:06 UTC, art3xa commented on docs/ru/docs/tutorial/dependencies/sub-dependencies.md
> +Но, тем не менее, эта систиме очень мощная и позволяет вам объявлять вложенные графы (деревья) зависимостей сколь угодно глубоко.
Да, спасибо :)

2023-10-26 10:12 UTC, tiangolo commented
📝 Docs preview for commit 2abf13040fef46d1349aeee9aa9d9b60fe011791 at: https://33de33c8.fastapitiangolo.pages.dev

2023-12-26 12:47 UTC, tiangolo commented
📝 Docs preview for commit 4d77dfda12fe3acabf54d581d091fe21ac4f7c1b at: https://c82babfd.fastapitiangolo.pages.dev

2023-12-27 02:59 UTC, s111d commented on docs/ru/docs/tutorial/dependencies/sub-dependencies.md
> +## Первая зависимость
Там в оригинале "First dependency "dependable"" – это нечто вроде противопоставления "ведущий/ведомый", либо "провайдер зависимости/потребитель зависимости", дальше по тексту ясно.

2023-12-27 03:18 UTC, s111d commented on docs/ru/docs/tutorial/dependencies/sub-dependencies.md
> +    Все это может показаться не столь полезным на этих простых примерах.
Я бы сделал "Всё это может не выглядеть таким уж полезным на этих несложных примерах."

2023-12-27 03:19 UTC, s111d commented on docs/ru/docs/tutorial/dependencies/sub-dependencies.md
> +    Но вы увидите, насколько это полезно, в главах, посвященных безопасности.
Или: Но вы увидите как это пригодится в главах посвященных безопасности.

2023-12-27 03:22 UTC, s111d commented on docs/ru/docs/tutorial/dependencies/sub-dependencies.md
> +Но, тем не менее, эта систиме очень мощная и позволяет вам объявлять вложенные графы (деревья) зависимостей сколь угодно глубоко.
* система

2023-12-27 03:23 UTC, s111d commented on docs/ru/docs/tutorial/dependencies/sub-dependencies.md
> +Помимо всех причудливых слов, используемых здесь, система внедрения зависимостей довольно проста.
Несмотря на все громкие слова...

2023-12-27 03:32 UTC, s111d commented on docs/ru/docs/tutorial/dependencies/sub-dependencies.md
> +Вы можете создать первую зависимость следующим образом:
"Вы" не обязательно тут. "Можно создать первую зависимость..."

2023-12-27 03:35 UTC, s111d commented on docs/ru/docs/tutorial/dependencies/sub-dependencies.md
> +Это довольно просто (не очень полезно), но поможет нам сосредоточиться на том, как работают подзависимости.
(хотя и не очень полезно/применимо)

2023-12-27 22:47 UTC, s111d commented on docs/ru/docs/tutorial/dependencies/sub-dependencies.md
> +**FastAPI** позаботится об их управлении.
Или: о том как их разрешить.

2024-01-07 14:37 UTC, AlertRED commented on docs/ru/docs/tutorial/dependencies/sub-dependencies.md
> +    Но вы увидите, насколько это полезно, в главах, посвященных безопасности.
```suggestion
    Но вы увидите как это пригодится в главах посвященных безопасности.
```

2024-01-07 14:38 UTC, AlertRED commented on docs/ru/docs/tutorial/dependencies/sub-dependencies.md
> +    Но вы увидите, насколько это полезно, в главах, посвященных безопасности.
```suggestion
    Но вы увидите как это пригодится в главах посвященных безопасности.
```

2024-01-07 14:39 UTC, AlertRED commented on docs/ru/docs/tutorial/dependencies/sub-dependencies.md
> +Но, тем не менее, эта систиме очень мощная и позволяет вам объявлять вложенные графы (деревья) зависимостей сколь угодно глубоко.
```suggestion
Но, тем не менее, эта система очень мощная и позволяет вам объявлять вложенные графы (деревья) зависимостей сколь угодно глубоко.
```

2024-01-07 14:41 UTC, AlertRED commented on docs/ru/docs/tutorial/dependencies/sub-dependencies.md
> +Помимо всех причудливых слов, используемых здесь, система внедрения зависимостей довольно проста.
```suggestion
Помимо всех этих громких слов, используемых здесь, система внедрения зависимостей довольно проста.
```

2024-01-07 14:42 UTC, AlertRED commented on docs/ru/docs/tutorial/dependencies/sub-dependencies.md
> +Это довольно просто (не очень полезно), но поможет нам сосредоточиться на том, как работают подзависимости.
```suggestion
Это довольно просто (хотя и не очень полезно), но поможет нам сосредоточиться на том, как работают подзависимости.
```

2024-01-07 14:43 UTC, AlertRED commented on docs/ru/docs/tutorial/dependencies/sub-dependencies.md
> +Вы можете создать первую зависимость следующим образом:
```suggestion
Можно создать первую зависимость следующим образом:
```

2024-01-07 14:45 UTC, AlertRED commented on docs/ru/docs/tutorial/dependencies/sub-dependencies.md
> +## Первая зависимость
```suggestion
## Провайдер зависимости
```

2024-01-07 14:47 UTC, AlertRED commented on docs/ru/docs/tutorial/dependencies/sub-dependencies.md
> +**FastAPI** позаботится об их управлении.
Думаю, то как написано сейчас читается лучше :)

2024-01-07 14:48 UTC, AlertRED commented on docs/ru/docs/tutorial/dependencies/sub-dependencies.md
> +    Все это может показаться не столь полезным на этих простых примерах.
То как сейчас написано лучше читается, думаю :)

2024-01-07 14:53 UTC, AlertRED commented on docs/ru/docs/tutorial/dependencies/sub-dependencies.md
> +Но, тем не менее, эта систиме очень мощная и позволяет вам объявлять вложенные графы (деревья) зависимостей сколь угодно глубоко.
```suggestion
Но, тем не менее, эта система очень мощная и позволяет вам объявлять вложенные графы (деревья) зависимостей сколь угодно глубоко.
```

2024-01-07 14:58 UTC, tiangolo commented
📝 Docs preview for commit fcd2d3580db572948fec15a160cd24e12d117731 at: https://e1979f58.fastapitiangolo.pages.dev

2024-01-07 15:00 UTC, AlertRED commented on docs/ru/docs/tutorial/dependencies/sub-dependencies.md
> +Но, тем не менее, эта систиме очень мощная и позволяет вам объявлять вложенные графы (деревья) зависимостей сколь угодно глубоко.
Уже исправлено :)
https://github.com/tiangolo/fastapi/pull/10515/files

2024-01-07 18:28 UTC, s111d commented on docs/ru/docs/tutorial/dependencies/sub-dependencies.md
> +**FastAPI** позаботится об их управлении.
Не согласен, это субъективное. 
В оригинале: FastAPI will take care of solving them. Всё-таки другой глагол и суть.
И, если уж оставлять "управление", то должно быть что-то вроде "управлении (кем?-чем?) ими". 
Либо: FastAPI сам займётся их управлением.

2024-01-16 17:18 UTC, AlertRED commented on docs/ru/docs/tutorial/dependencies/sub-dependencies.md
> +**FastAPI** позаботится об их управлении.
```suggestion
**FastAPI** сам займётся их управлением.
```

2024-01-16 17:25 UTC, tiangolo commented
📝 Docs preview for commit 7767a5ed47f7c1e00260ed90ea1fd5962e863fb0 at: https://f80897ff.fastapitiangolo.pages.dev

2024-05-09 15:27 UTC, EpsilonRationes approved these changes

2024-07-27 23:59 UTC, alejsdev commented
Cool! Thanks to @AlertRED and everyone for the help! :rocket:

2024-07-27 23:59 UTC, merged