:globe_with_meridians: Update Turkish translation for `docs/tr/docs/fastapi-people.md`
fastapi/fastapi pull request #10547
Opened 2023-10-29 15:13 UTC by alperiox

Bazi cumleleri duzenledim, cesitli kisimlar google translate havasi vermisti.

2023-10-29 15:20 UTC, tiangolo commented
📝 Docs preview for commit bb829b185b5f0d96c28ff1b1a894f768d48da84e at: https://78fdeed6.fastapitiangolo.pages.dev

2024-01-15 05:51 UTC, hasansezertasan requested changes
Dosyanın başına şu kısmı ekleyelim lütfen:

```markdown
---
hide:
  - navigation
---
```

Review'imi yarıda bırakıyorum. Dosyada tarihi geçmiş alanlar mevcut. Ne zaman ilgilenebilirsin @alperiox?

2024-01-15 05:51 UTC, hasansezertasan commented on docs/tr/docs/fastapi-people.md
> +Ben **FastAPI**'nin yazarı ve geliştiricisiyim. Bununla ilgili daha fazla bilgiyi şurada okuyabilirsiniz:
```suggestion
Ben **FastAPI**'nın yazarı ve geliştiricisiyim. Bununla ilgili daha fazla bilgiyi şurada okuyabilirsiniz:
```

2024-01-15 05:51 UTC, hasansezertasan commented on docs/tr/docs/fastapi-people.md
>  ... Burada size harika FastAPI topluluğunu göstermek istiyorum.
```suggestion
...burada size harika FastAPI topluluğunu anlatmak istiyorum.
```

2024-01-15 05:51 UTC, hasansezertasan commented on docs/tr/docs/fastapi-people.md
> +**FastAPI**, topluluğundan çok destek alıyor. Ben de onların katkısını vurgulamak istiyorum.
```suggestion
**FastAPI**, topluluğundan çok destek alıyor. Ben de onların katkılarını vurgulamak istiyorum.
```

2024-01-15 05:51 UTC, hasansezertasan commented on docs/tr/docs/fastapi-people.md
> +O mükemmel insanlar:
Orjinalinde "Mükemmel" vurgusu göremedim.

2024-01-15 05:51 UTC, hasansezertasan commented on docs/tr/docs/fastapi-people.md
> +* [GitHubdaki sorunları (issues) çözmelerinde diğerlerine yardım ediyor](help-fastapi.md#help-others-with-issues-in-github){.internal-link target=_blank}.
Outdated.

2024-01-15 05:51 UTC, hasansezertasan commented on docs/tr/docs/fastapi-people.md
> +Bunlar geçen ay boyunca [GitHub'da başkalarına en çok yardımcı olan](help-fastapi.md#help-others-with-issues-in-github){.internal-link target=_blank} kullanıcılar. ☕
```suggestion
Geçtiğimiz ay boyunca [GitHub'da başkalarına en çok yardımcı olan](help-fastapi.md#help-others-with-issues-in-github){.internal-link target=_blank} kullanıcılar. ☕
```

2024-01-15 05:51 UTC, hasansezertasan commented on docs/tr/docs/fastapi-people.md
> +Bunlar geçen ay boyunca [GitHub'da başkalarına en çok yardımcı olan](help-fastapi.md#help-others-with-issues-in-github){.internal-link target=_blank} kullanıcılar. ☕
`## Uzmanlar` başlığına kadar olan kısım outdated.

2024-01-30 11:08 UTC, tiangolo commented
As this PR had requested changes to be applied but has been inactive for a while, it's now going to be closed. But if there's anyone interested, feel free to create a new PR.

2024-01-30 11:30 UTC, alejsdev commented
Sorry, we probably closed this PR too early. I'm going to reopen it and adjust the auto close times. 😅

2024-01-31 06:49 UTC, alperiox commented
> Sorry, we probably closed this PR too early. I'm going to reopen it and adjust the auto close times. 😅

Sorry for the trouble 😅

2024-01-31 06:55 UTC, tiangolo commented
📝 Docs preview for commit 91c2b870979dc4ead9a5f9b3478bd965a2835f97 at: https://9dbae149.fastapitiangolo.pages.dev

2024-01-31 07:39 UTC, tiangolo commented
📝 Docs preview for commit 783c6dc61786b95e507abd298cb7874a3202de7e at: https://2fc2ca38.fastapitiangolo.pages.dev

2024-02-01 22:11 UTC, hasansezertasan requested changes
12'inci satır çevirilmemiş, orayı "Merhaba! :wave" gibi güncellemeye ne dersin?


Gayet kaliteli bir çalışma olmuş, eline sağlık 🧿

2024-02-02 09:40 UTC, alperiox commented on docs/tr/docs/fastapi-people.md
> +Ben **FastAPI**'ı oluşturan geliştiricisiyim. Bununla ilgili daha fazla bilgiyi şurada okuyabilirsiniz:
Benimde kulağıma pek doğru gelmiyor fakat tamamen doğru bir Türkçe kullanımı :D Belki şöyle bir şey daha uygun olabilir:
```suggestion
Ben **FastAPI**'ı oluşturan geliştiriciyim. Bununla ilgili daha fazla bilgiyi şurada okuyabilirsiniz:
```
Ben halen FastAPI geliştiricisi olduğunu vurgulamak istemiştim, böyle dediğimizde de yeterince belli oluyorsa öneriden ilerleyelim.

2024-02-02 11:17 UTC, hasansezertasan commented on docs/tr/docs/fastapi-people.md
> +Ben **FastAPI**'ı oluşturan geliştiricisiyim. Bununla ilgili daha fazla bilgiyi şurada okuyabilirsiniz:
```suggestion
Ben **FastAPI**'ı oluşturan ve geliştiren kişiyim. Bununla ilgili daha fazla bilgiyi şurada okuyabilirsiniz:
```
Bu nasıl?

2024-02-02 11:18 UTC, hasansezertasan commented on docs/tr/docs/fastapi-people.md
> +**FastAPI**, topluluğundan çok destek alıyor. Ben de onların katkısını vurgulamak istiyorum.
https://github.com/tiangolo/fastapi/blob/6f6e786979eb3156b85e7c2f44d0b8af5cf0af17/docs/en/docs/fastapi-people.md?plain=1#L32

2024-02-02 11:20 UTC, hasansezertasan commented on docs/tr/docs/fastapi-people.md
> +**FastAPI**, topluluğundan çok destek alıyor. Ben de onların katkısını vurgulamak istiyorum.
"onların katkısını" dediğimizde çıkan anlam ile "onların katkılarını" dediğimizde çıkan anlam farklı ancak burada söylenmek isteyen şey "farklı kişilerin, farklı katkıları: onların katkıları"

2024-02-03 21:48 UTC, hasansezertasan commented on docs/tr/docs/fastapi-people.md
> +Ben **FastAPI**'ı oluşturan geliştiricisiyim. Bununla ilgili daha fazla bilgiyi şurada okuyabilirsiniz:
Birde senin daha önce, "creator" için yaptığın iki çeviriye bakmak istiyorum:

https://github.com/tiangolo/fastapi/blob/3f3ee240dd8656962e94e89eceb3838508982068/docs/tr/docs/alternatives.md?plain=1#L34

Burada "yaratıcısı" demişiz.

https://github.com/tiangolo/fastapi/blob/3f3ee240dd8656962e94e89eceb3838508982068/docs/tr/docs/alternatives.md?plain=1#L286

Burada "geliştiricisi" demişiz.

---

[Tureng - maintainer - Türkçe İngilizce Sözlük](https://tureng.com/tr/turkce-ingilizce/maintainer) sayfasında gördüğüm kadarıyla `maintainer` aynı zamanda "geliştirici" demek için de kullanılıyor yani inanıyorum ki şöyle bir çeviri yeterli olacaktır...

```suggestion
Ben **FastAPI**'ın geliştiricisiyim. Bununla ilgili daha fazla bilgiyi şurada okuyabilirsiniz:
```

Türkçede "geliştirici" dendiğinde akla gelen şeylerden birisi de aslında "oluşturan" oluyor. Burada ki "maintainer" aynı zamanda "bakıcı" yani "sürekli ilgilenen" kişi anlamını taşıyor bunun için de "geliştirici" kullanılabilir mi? Evet çünkü geliştirici olmak illa "geçmişte oldu ve bitti" anlamını taşımaz, "geliştiricisiyim, hala geliştiriyorum"'da denilebilir...

Çok kafa yordum çözelim bunu 😆

2024-02-03 22:40 UTC, tiangolo commented
📝 Docs preview for commit a2d0ebfe9d9ef04a9b3a8c7a79ce831ecef53abd at: https://d0a85970.fastapitiangolo.pages.dev

2024-02-04 01:01 UTC, hasansezertasan commented on docs/tr/docs/fastapi-people.md
> + [FastAPI yardım - yardım al -  benimle iletişime geç](help-fastapi.md#connect-with-the-author){.internal-link target=_blank}.
```suggestion
Ben **FastAPI**'ın geliştiricisiyim. Bununla ilgili daha fazla bilgiyi şurada okuyabilirsiniz: [FastAPI yardım - yardım al -  benimle iletişime geç](help-fastapi.md#connect-with-the-author){.internal-link target=_blank}.
```

2024-02-04 01:04 UTC, tiangolo commented
📝 Docs preview for commit 39b894164fa897f35ea63300992324de6630208d at: https://9e4282b5.fastapitiangolo.pages.dev

2024-02-04 01:10 UTC, alperiox commented on docs/tr/docs/fastapi-people.md
> +**FastAPI**, topluluğundan çok destek alıyor. Ben de onların katkısını vurgulamak istiyorum.
Günün sonunda aralarında bir fark olduğunu düşünmüyorum, sonuçta hepsi günün sonunda FastAPI'a katkıda bulunuyor. Ancak 'katkılarını' demek gramer açısından daha doğru.

2024-02-04 01:19 UTC, hasansezertasan commented on docs/tr/docs/fastapi-people.md
> +**FastAPI**, topluluğundan çok destek alıyor. Ben de onların katkısını vurgulamak istiyorum.
Birde şunu düşünüyorum, 182. satırda da "katkılarını" demişsin, orada ki anlam hemen hemen aynı. Sadece "onların" yok. Ayrıca burada bahsi geçen şey "bir kişinin birden fazla katkısı" yada "birden fazla kişinin tek katkısı" değil 😇.

2024-02-04 01:21 UTC, hasansezertasan approved these changes
Thank you @alperiox for this awesome translation 👏. It was very nice to collaborate with you on this project! 🚀 Looking forward to seeing this merged! 🤩

Müthiş çevirin için sana teşekkür ederim @alperiox 👏. Bu projede seninle işbirliği yapmak oldukça güzeldi! 🚀 Çevirinin yayınlanmasını dört gözle bekliyorum 🤩

2024-02-04 01:22 UTC, tiangolo commented
📝 Docs preview for commit 35590e21c493bc6c4f6e46e4b8ad1d7dd339d988 at: https://0a8fc1ba.fastapitiangolo.pages.dev

2024-02-04 14:28 UTC, merged

2024-02-04 14:28 UTC, alejsdev commented
Thank you for your contribution! @alperiox 🥳 

And thanks for the help @hasansezertasan 🔍