📝 Update `en/docs/tutorial/debugging.md`
fastapi/fastapi pull request #10590
Opened 2023-11-05 00:27 UTC by nilslindemann

This chapter was outdated:

* VS Code now has a special debug configuration for FastAPI, so calling `uvicorn` from the `myapp.py` is not necessary.
* The UI of PyCharm has changed, and it is also easier to start the debugger.

I kept the `__name__ == "__main__"` part, but rewrote the rest.

2023-11-05 00:34 UTC, tiangolo commented
📝 Docs preview for commit 795445b2357c86a6b2adf684b698af92d05b5d4c at: https://8f6d59a7.fastapitiangolo.pages.dev

2023-11-05 13:32 UTC, tiangolo commented
📝 Docs preview for commit a0c83b2ee36430d018b622aceb9d5e6b748af420 at: https://4c10a07d.fastapitiangolo.pages.dev

2023-11-05 14:01 UTC, tiangolo commented
📝 Docs preview for commit 04c8adff3ffaa4d7186a404cfe8c3dc986459ebd at: https://65312a71.fastapitiangolo.pages.dev

2023-11-05 14:11 UTC, tiangolo commented
📝 Docs preview for commit 6442719ec65177c1d8b96b53182893386323334d at: https://d15b381d.fastapitiangolo.pages.dev

2023-11-05 14:21 UTC, tiangolo commented
📝 Docs preview for commit 8f389692462cb21e77d8c2836505a3a172949fda at: https://e9051d67.fastapitiangolo.pages.dev

2023-11-05 14:33 UTC, tiangolo commented
📝 Docs preview for commit a0676bb22a3084ef939fc615058d196a173fd2d7 at: https://305990b4.fastapitiangolo.pages.dev

2023-11-29 19:59 UTC, tiangolo commented
📝 Docs preview for commit b039a661051b2e943ed7799092743029123c2ff2 at: https://e83d55cb.fastapitiangolo.pages.dev

2023-12-01 03:28 UTC, tiangolo commented
📝 Docs preview for commit f74ed2c9184d7ff50885c52d31d6cf908b6bb2e2 at: https://f9ddd104.fastapitiangolo.pages.dev

2023-12-30 20:25 UTC, tiangolo commented
📝 Docs preview for commit 46ebcbe40e98828a4eb24ade6517f4ef8cf1584c at: https://7c08282b.fastapitiangolo.pages.dev

2024-02-02 18:52 UTC, alejsdev approved these changes

2024-02-03 23:04 UTC, nilslindemann commented
Thanks for the review, @alejsdev

2024-02-03 23:08 UTC, tiangolo commented
📝 Docs preview for commit 8ccde00a628d66e096ac4ea25bfdeb79e43917d1 at: https://d9f7b8ec.fastapitiangolo.pages.dev

2024-04-01 02:10 UTC, tiangolo commented
📝 Docs preview for commit f641f31b3cf0caae9e0697eb55de08b00dd13a47 at: https://9a4f6523.fastapitiangolo.pages.dev

2025-06-13 05:51 UTC, YuriiMotov requested changes
@nilslindemann, thanks for your efforts!

I think there are a couple of things that need to be improved. 🧐
Would you like to continue working on this?

2025-06-13 05:51 UTC, YuriiMotov commented on docs/en/docs/tutorial/debugging.md
> +* In the subsequent dropdown, enter the name of your application file, here `myapp.py` (This is only necessary because VS Code did not find a `main.py` file).
Looks like this has been changed. I tried to follow steps and it didn't ask me to provide file name. It showed `launch.json` with default `main.py` right after I chose "FastAPI" on previous step.

2025-06-13 05:51 UTC, YuriiMotov commented on docs/en/docs/tutorial/debugging.md
> +```
```suggestion
{* ../../docs_src/debugging/tutorial002.py hl[1,15] *}
```

2025-06-13 05:51 UTC, YuriiMotov commented on docs/en/docs/tutorial/debugging.md
> +PyCharm does not currently have a debug configuration specifically for FastAPI applications, so we will run the `uvicorn` server directly from our `myapp.py`.
Not sure it's true: https://www.jetbrains.com/help/pycharm/fastapi-project.html#run-debug-configuration

2025-06-13 10:21 UTC, nilslindemann commented on docs/en/docs/tutorial/debugging.md
> +* In the subsequent dropdown, enter the name of your application file, here `myapp.py` (This is only necessary because VS Code did not find a `main.py` file).
Thanks, Yuri, I currently don't have time for this. Very probable that this is meanwhile outdated again. After all, the PR is nearly two years old. I will close this issue for now, and may create a new one when there is time.

2025-06-13 10:21 UTC, closed without merging

2025-06-13 10:27 UTC, nilslindemann commented
Closing this as it is outdated, as @YuriiMotov pointed out. Will maybe recreate at a later time. Also, Party! I don't have any open PRs in this Repo anymore. It was a fun time, @tiangolo, @alejsdev and all others I have met. See you again.

2025-06-13 10:41 UTC, YuriiMotov commented
@nilslindemann, thank you for your contribution!
Sorry for not being able to review it in time..