🌐 Add Russian translation for `docs/ru/docs/tutorial/security/simple-oauth2.md`
fastapi/fastapi pull request #10599
Opened 2023-11-06 12:12 UTC by AlertRED

2024-03-31 17:27 UTC, codespearhead commented
Do you happen to know three Russian developers you can ask a [PR review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) from? [This](https://github.com/tiangolo/fastapi/pulls?q=is%3Apr+is%3Aopen+Russian) might help.

2024-11-22 16:24 UTC, alv2017 requested changes

2024-11-22 16:24 UTC, alv2017 commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +Для этого простого примера мы будем совершенно небезопасны и вернем то же самое `имя пользователя`, что и токен.
*suggestion:*

В этом простом примере мы нарушим все правила безопасности, и будем считать, что имя пользователя (username)  полностью соответствует токену (token)

2024-11-22 16:24 UTC, alv2017 commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +    Но пока давайте остановимся на необходимых нам деталях.
*correction required: incorrect implementation of info box*

2024-11-22 16:24 UTC, alv2017 commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +    ```
*correction required: incorrect implementation of code insertions*

2024-11-22 16:24 UTC, alv2017 commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +    В остальном за вас это сделает **FastAPI**.
*correction required: incorrect implementation of info box*

2024-11-22 16:24 UTC, alv2017 commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +    ```
*correction required: incorrect implementation of code insertions*

2024-11-22 16:24 UTC, alv2017 commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +    В этом и заключается преимущество стандартов...
*correction required: incorrect implementation of info box*

2024-11-22 16:24 UTC, alv2017 commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +## Посмотим в действии
*suggestion:*

`## Посмотим как это работает`

2024-11-22 16:24 UTC, alv2017 commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +Теперь попробуйте с неактивным пользователем, пройдите аутентификацию:
*correction required:*

Теперь попробуйте пройти аутентификацию с неактивным пользователем:

2024-11-22 16:36 UTC, alv2017 commented on docs/ru/docs/tutorial/security/simple-oauth2.md
@AlertRED 

1) Есть небольшие проблемы с переводом, которые было бы неплохо исправить. Я их обозначала как translation issues

2) Комментарии обозначенные как *suggestions*, предложения по улучшению перевода, но это на твое усмотрение

3) Достаточно много проблем со ссылками и инфо боксами, по-видимому надо обновиться (pull request сделан достаточно давно) и внести необходимые попровки.

2024-11-25 22:05 UTC, alv2017 requested changes

2024-11-25 22:11 UTC, alv2017 commented
@Xewus, @s111d нужна помощь с ревью. Подключайтесь!
:wave: :blush:

2024-11-25 22:50 UTC, alv2017 approved these changes

2024-11-25 22:52 UTC, alv2017 approved these changes
Дополнительно добавила предложения по улучшению перевода (на твое усмотрение)

2024-11-26 22:04 UTC, alejsdev commented
Hi @AlertRED, I have updated the documentation with the latest syntax for `includes`.
I will wait for you to review the changes suggested by @alv2017 before merging the PR. 
Thanks to both of you for the help! :rocket:

2024-11-28 15:58 UTC, AlertRED commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +Но при авторизации в *эндпоинте* нам необходимо использовать именно эти имена, чтобы соответствовать спецификации (и иметь возможность, например, использовать это во встроенной системе документации A
```suggestion
Но при авторизации согласно спецификации, требуется использовать именно эти имена, что даст нам возможность, воспользоваться встроенной системой документации API.
```

2024-11-28 16:06 UTC, AlertRED commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +Но при авторизации в *эндпоинте* нам необходимо использовать именно эти имена, чтобы соответствовать спецификации (и иметь возможность, например, использовать это во встроенной системе документации A
@alv2017 Только в этом предложении немного изменил ваш вариант

2024-11-28 22:15 UTC, alv2017 commented
@alejsdev: Thank you for your help! 

@AlertRED: I think we are ready with PR, aren't we? 

:smiley:

2024-11-29 00:08 UTC, AlertRED commented
> @alejsdev: Thank you for your help! 
> 
> @AlertRED: I think we are ready with PR, aren't we? 
> 
> :smiley: 

Yes, we are :)

2024-11-30 09:21 UTC, Xewus requested changes
В целом, проделанный объём работы большой.

2024-11-30 09:21 UTC, Xewus commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +Каждый раз, когда вы передаете точно такое же содержимое (точно такой же пароль), вы получаете точно такую же тарабарщину.
Так, на заметку, как ни странно, на данное утверждение но относится к стандартной функции `hash()` в Python.

2024-11-30 09:21 UTC, Xewus commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +Таким образом, вор не сможет попытаться использовать эти же пароли в другой системе (поскольку многие пользователи используют одни и те же пароли повсеместно, это было бы опасно).
```suggestion
Таким образом, вор не сможет использовать эти же пароли в другой системе (поскольку многие пользователи используют одни и те же пароли повсеместно, это было бы опасно).
```
 Попытаться-то может.

2024-11-30 09:21 UTC, Xewus commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +Ответ конечной точки `token` должен представлять собой объект в формате JSON.
```suggestion
Ответ эндпоинта `token` должен представлять собой объект в формате JSON.
```

2024-11-30 09:21 UTC, Xewus commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +Это то, что вы должны сделать сами в своем коде, и убедиться, что вы используете эти JSON-ключи.
```suggestion
Это то, что вы должны сделать сами в своем коде и убедиться, что вы используете эти JSON-ключи.
```

2024-11-30 09:21 UTC, Xewus commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +Таким образом, в нашей конечной точке мы получим пользователя только в том случае, если он существует, правильно аутентифицирован и активен:
```suggestion
Таким образом, в нашем эндпоинте мы получим пользователя только в том случае, если он существует, правильно аутентифицирован и активен:
```

2024-11-30 09:21 UTC, Xewus commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +Любой HTTP с кодом состояния 401 "UNAUTHORIZED" должен также возвращать заголовок `WWW-Authenticate`.
```suggestion
Ответ сервера с  HTTP-кодом 401 "UNAUTHORIZED" должен также возвращать заголовок `WWW-Authenticate`.
```

2024-11-30 09:21 UTC, Xewus commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +На самом деле этот дополнительный заголовок можно пропустить, и все будет работать.
```suggestion
На самом деле этот дополнительный заголовок можно пропустить и все будет работать.
```

2024-11-30 09:21 UTC, Xewus commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +Но он приведен здесь для соответствия спецификации.
```suggestion
Но он приведён здесь для соответствия спецификации.
```

2024-11-30 09:21 UTC, Xewus commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +Кроме того, могут существовать инструменты, которые ожидают его и могут использовать, и это может быть полезно для вас или ваших пользователей, сейчас или в будущем.
```suggestion
Кроме того, могут существовать инструменты, которые ожидают его и могут использовать, и это может быть полезно для вас или ваших пользователей сейчас или в будущем.
```

2024-11-30 09:21 UTC, Xewus commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +Используйте учетные данные:
```suggestion
Используйте учётные данные:
```

2024-11-30 09:21 UTC, Xewus commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +Если щелкнуть на значке замка и выйти из системы, а затем попытаться выполнить ту же операцию еще раз, то будет выдана ошибка HTTP 401:
```suggestion
Если щелкнуть на значке замка и выйти из системы, а затем попытаться выполнить ту же операцию ещё раз, то будет выдана ошибка HTTP 401:
```

2024-11-30 09:21 UTC, Xewus commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> + Единственным недостатком нашей системы является то, что она все еще не защищена.
```suggestion
 Единственным недостатком нашей системы является то, что она всё ещё не защищена.
```

2024-11-30 09:47 UTC, AlertRED commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +Теперь давайте, отталкиваясь от предыдущей главы, добавим недостающие части, чтобы получить полный поток безопасности.
```suggestion
Теперь, отталкиваясь от предыдущей главы, добавим недостающие части, чтобы получить полный  процесс обеспечения безопасности.
```

2024-11-30 10:01 UTC, AlertRED commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +Теперь, отталкиваясь от предыдущей главы, добавим недостающие части, чтобы получить полный поток безопасности.
```suggestion
Теперь, отталкиваясь от предыдущей главы, добавим недостающие части, чтобы получить систему обеспечения безопасности.
```

2024-11-30 10:18 UTC, AlertRED commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +`OAuth2PasswordRequestForm` - это зависимость от класса, которая объявляет тело формы со следующими полями:
```suggestion
`OAuth2PasswordRequestForm` - это класс для использования в качестве зависимости для *функции обрабатывающей эндпоинт*, который определяет тело формы со следующими полями:
```

2024-11-30 10:56 UTC, alv2017 commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +Теперь давайте, отталкиваясь от предыдущей главы, добавим недостающие части, чтобы получить полный поток безопасности.
термин `security` flow это ссылка к [RFC6749](https://datatracker.ietf.org/doc/html/rfc6749)
это набор действий, которые нужно произвести в соответствии с выбранным протоколом авторизации.

и нужен соответствующий термин на русском языке

2024-11-30 11:11 UTC, alv2017 commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +`OAuth2PasswordRequestForm` - это зависимость от класса, которая объявляет тело формы со следующими полями:
так лучше и понятнее

2024-11-30 11:29 UTC, alv2017 commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +Экземпляр зависимого класса `OAuth2PasswordRequestForm` не будет иметь атрибута `scope` с длинной строкой, разделенной пробелами, вместо этого он будет иметь атрибут `scopes` с фактическим списком ст
@Xewus: здесь не соглашусь, на мой взгляд смысл предложения таков:

```suggestion
В экземпляре зависимого класса `OAuth2PasswordRequestForm` атрибут `scope`, состоящий из одной длинной строки, разделенной пробелами, заменен на атрибут `scopes`, состоящий из списка отдельных строк, каждая из которых соответствуе определенному уровню доступа.
```

основной момент это замена `scope` на `scopes`

2024-11-30 11:34 UTC, alv2017 commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +Каждый раз, когда вы передаете точно такое же содержимое (точно такой же пароль), вы получаете точно такую же тарабарщину.
т.е. ты хочешь сказать, что hash() будет вести себя по-другому? можешь привести пример?

2024-11-30 11:40 UTC, alv2017 commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +На самом деле этот дополнительный заголовок можно пропустить, и все будет работать.
1) Я бы поставила запятую после `На самом деле` (вводное слово)
2) И оставила бы запятую перед `и` (сложносочиненное предложение)

2024-11-30 11:46 UTC, alv2017 reviewed
У меня возражение по поводу строки 135:

`scope` vs `scopes`

2024-11-30 12:17 UTC, Xewus commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +Теперь давайте, отталкиваясь от предыдущей главы, добавим недостающие части, чтобы получить полный поток безопасности.
Вспомнил, что, вроде с АлтерРедом, обсуждали эту штуку года 2 назад, но тоже ничего хорошего не придумали...

2024-11-30 12:19 UTC, Xewus commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +Экземпляр зависимого класса `OAuth2PasswordRequestForm` не будет иметь атрибута `scope` с длинной строкой, разделенной пробелами, вместо этого он будет иметь атрибут `scopes` с фактическим списком ст
> @Xewus: здесь не соглашусь, на мой взгляд смысл предложения таков:
> 
> основной момент это замена `scope` на `scopes`

Действительно, не заметил "с" в конце названия.

2024-11-30 12:20 UTC, Xewus approved these changes

2024-11-30 15:11 UTC, AlertRED commented on docs/ru/docs/tutorial/security/simple-oauth2.md
> +У экземпляра класса `OAuth2PasswordRequestForm` атрибут `scope` содержит список строк (а не длинную строку), полученных путём разделения длинной строки по пробелам. .
```suggestion
В экземпляре зависимого класса `OAuth2PasswordRequestForm` атрибут `scope`, состоящий из одной длинной строки, разделенной пробелами, заменен на атрибут `scopes`, состоящий из списка отдельных строк, каждая из которых соответствует определенному уровню доступа.
```
@alv2017 внес твое предложение

2024-11-30 16:02 UTC, alv2017 commented
Проблема решена, у меня никаких возражений больше нет :smiley:

2024-12-10 10:53 UTC, merged

2024-12-10 10:54 UTC, alejsdev commented
Great! Thanks for your work @AlertRED @Xewus @alv2017 :rocket: :sparkles: