Chinese translation
fastapi/fastapi pull request #1060
Opened 2020-03-01 04:54 UTC by linupychiang

FastAPI文档index部分中文翻译

2020-03-01 05:11 UTC, phy25 requested changes
I don't think this is the proper way to merge translations into master by removing all the original sentences.

2020-03-02 15:00 UTC, sm-Fifteen commented
I don't even know if the documentation even supports having translations with the way is is setup right now; not to mention that translating all of it would be a huge endeavor. I know FastAPI has contributors from a variety of countries speaking a variety of languages, but I guess English has done a good enough job at getting everyone involved to understand each other so far, so it's not a priority for anyone at the moment.

2020-03-03 11:40 UTC, ghost reviewed
Didn't do a full review, but there are some inaccuracies, many references to 3rd party images that are not guaranteed to be immutable, many of the helpful additional comments have been removed. Most importantly, rewriting the index.md is not ideal, (IMHO) this translation is probably better left in a forked repo for other people to see if necessary.

2020-03-03 11:40 UTC, juhovh-aiven commented on docs/index.md
> +老实说，你做的东西看起来很可靠和漂亮。从很多方面来说，这就是我希望**Hug**成为的样子。看到有人这么做，真的很鼓舞人心。
看到有人这么做 doesn't convey very well the point of someone building what Hug was supposed to be.

2020-03-03 11:40 UTC, juhovh-aiven commented on docs/index.md
> +如果您的代码使用了`async` / `await`，请使用 `async def` ：
Not sure why the past tense in the former part of the sentence.

2020-03-03 11:40 UTC, juhovh-aiven commented on docs/index.md
> +![ReDoc](http://linupyoos.oss-cn-beijing.aliyuncs.com/blogs/2020-02-29-135552.png)
More external images.

2020-03-03 11:54 UTC, closed without merging

2020-03-03 11:56 UTC, linupychiang commented on docs/index.md
> +![FastAPI](http://linupyoos.oss-cn-beijing.aliyuncs.com/blogs/2020-02-29-114916.png)
Thanks for your comments.  Recently, I learned a lot about Github.

2020-03-03 11:56 UTC, linupychiang commented on docs/index.md
> +![FastAPI](http://linupyoos.oss-cn-beijing.aliyuncs.com/blogs/2020-02-29-114916.png)
Thanks for your comments.  Recently, I learned a lot about Github.

2020-03-27 09:31 UTC, tiangolo commented
Thanks for your effort and contribution @linupychiang ! :cake: :rocket: And thanks a lot @juhovh-aiven for helping with the review ...and for keeping the review in English (that way I can understand the conversation :sweat_smile: ).

@linupychiang I finally finished the set up to have translations for the docs, here are the new docs: https://fastapi.tiangolo.com/contributing/#translations

You can probably still copy a lot of the text you had already translated, as the file structure is the same.