🌐 Add Russian translation for `docs/ru/docs/tutorial/security/oauth2-jwt.md`
fastapi/fastapi pull request #10601
Opened 2023-11-06 16:41 UTC by AlertRED

2023-11-06 16:48 UTC, tiangolo commented
📝 Docs preview for commit 2b2d346633a2d5dbd1c9f48de611a58c951b5a48 at: https://2e637ad7.fastapitiangolo.pages.dev

2024-11-28 16:22 UTC, AlertRED commented
@alv2017 Вот еще PR требующий ревью, последний :)

2024-11-29 00:11 UTC, alv2017 requested changes
1) Пакет `python-jose` больше не рекомендуется к использованию, поэтому отдел по `python-jose` нужно переделать

2) Остальные поправки, не касающиеся `python-jose`, на твое усмотрение

2024-11-29 00:11 UTC, alv2017 commented on docs/ru/docs/tutorial/security/oauth2-jwt.md
> +Using the credentials:
```suggestion
Используя учетные данные пользователя:
```

2024-11-29 13:28 UTC, AlertRED commented on docs/ru/docs/tutorial/security/oauth2-jwt.md
> +///
Поправил

2024-11-29 13:30 UTC, AlertRED commented
@alv2017 Все твои предложения внес без возражений

2024-11-29 21:53 UTC, alv2017 commented on docs/ru/docs/tutorial/security/oauth2-jwt.md
> +Но он подписан. Таким образом, когда вы получаете токен, который вы эмитировали (выдавали), вы можете убедиться, что это именно вы его эмитировали.
```suggestion
Но он подписан. Следовательно, когда вы получаете токен, который вы эмитировали (выдавали), вы можете убедиться, что это именно вы его эмитировали.
```

("таким образом" используется сначала в этом предложении, а потом сразу в следующем)

2024-11-29 21:57 UTC, alv2017 approved these changes
The translation looks good, @AlertRED made a good job being precise and careful with technical details.

:ok_hand:

2024-12-10 10:56 UTC, merged

2024-12-10 10:56 UTC, alejsdev commented
Thanks for your work! @AlertRED :100: 
And thanks for your detailed review @alv2017 :raised_hands: