🌐 Add Turkish translation for help pages
fastapi/fastapi pull request #10629
Opened 2023-11-12 11:12 UTC by aprilcoskun

This pr adds Turkish translations for docs/tr/docs/help-fastapi.md and docs/tr/docs/help/index.md.

2023-11-12 11:19 UTC, tiangolo commented
📝 Docs preview for commit df89fb748922277c53fee2475fe9d98af3681cae at: https://7a4a69ae.fastapitiangolo.pages.dev

2023-11-12 11:28 UTC, hasansezertasan requested changes
@aprilcoskun Eline sağlık.

İnceleme gerçekleştirmeden önce [FastAPI Türkiye](https://hasansezertasan.github.io/fastapi-turkiye/) sayfasını incelemeni rica edeceğim.

Bununla birlikte pr başlığını standartlara uygun bir şekilde değiştirmeni rica edeceğim. Yine ek olarak çevirilerde kolaylık için her pull request içerisinde bir adet markdown dosyasının çevirisi olması standartları korumamız için daha iyi olacaktır.

2023-11-12 11:32 UTC, hasansezertasan commented
Bunlara ek olarak [Development - Contributing - FastAPI](https://fastapi.tiangolo.com/contributing/#translations) sayfasını da okumanı tavsiye ediyorum.

2024-02-24 03:14 UTC, tiangolo commented
As this PR had requested changes to be applied but has been inactive for a while, it's now going to be closed. But if there's anyone interested, feel free to create a new PR.

2024-02-24 03:14 UTC, closed without merging