Add Ukrainian translation for docs/uk/docs/tutorial/body-fields.md
fastapi/fastapi pull request #10670
Opened 2023-11-17 09:20 UTC by ArtemKhymenko

Context:
Ukrainian translation for docs/uk/docs/tutorial/body-fields.md
Changes:
Created Ukrainian version of docs/uk/docs/tutorial/body-fields.md

2023-11-17 09:26 UTC, tiangolo commented
📝 Docs preview for commit 47329aa7644cb569c71f3644d140d67d8bd488a4 at: https://642845c4.fastapitiangolo.pages.dev

2023-11-30 08:55 UTC, mezgoodle requested changes

2023-11-30 08:55 UTC, mezgoodle commented on docs/uk/docs/tutorial/body-fields.md
> +     Зверніть увагу, як кожний атрибут моделі із типом, значенням за замовчуванням та `Field` має ту саму структуру, що й параметр *функції обробки шляху*, з `Field` замість `Path`, `Query` і `Body`.
```suggestion
     Зверніть увагу, що кожен атрибут моделі із типом, значенням за замовчуванням та `Field` має ту саму структуру, що й параметр *функції обробки шляху*, з `Field` замість `Path`, `Query` і `Body`.
```

2023-11-30 08:55 UTC, mezgoodle commented on docs/uk/docs/tutorial/body-fields.md
> +    Додаткові ключі, передані в `Field`, також будуть присутні в отриманій схемі OpenAPI для вашого додатка.
```suggestion
    Додаткові ключі, передані в `Field`, також будуть присутні у згенерованій схемі OpenAPI для вашого додатка.
```

2023-12-01 10:22 UTC, tiangolo commented
📝 Docs preview for commit fe18a37b789c1d8ba244a9d483a61b94cb6d8d0a at: https://aaa94259.fastapitiangolo.pages.dev

2023-12-03 12:30 UTC, rostik1410 approved these changes

2023-12-05 07:11 UTC, mezgoodle approved these changes

2024-01-09 15:25 UTC, alejsdev commented
Thanks for your help! 😄 @ArtemKhymenko 

And for the reviews @rostik1410 and @mezgoodle 🚀

2024-01-09 15:25 UTC, merged