🌐 Add German translation for `docs/de/docs/how-to/extending-openapi.md`
fastapi/fastapi pull request #10794
Opened 2023-12-18 00:10 UTC by nilslindemann

← `how-to/conditional-openapi.md` (#10790)
→ `how-to/separate-openapi-schemas.md` (I am currently translating)

[German translation progress](https://github.com/tiangolo/fastapi/discussions/10582)

2023-12-18 00:16 UTC, tiangolo commented
📝 Docs preview for commit c2f266289502edc3c6d03817f400afe938e0ad5f at: https://2318bdcb.fastapitiangolo.pages.dev

2023-12-18 20:31 UTC, tiangolo commented
📝 Docs preview for commit 5736fd9bee3822908ad737bc2791f82a63516f26 at: https://7bef6141.fastapitiangolo.pages.dev

2023-12-30 20:19 UTC, tiangolo commented
📝 Docs preview for commit df61b01981405e8ea495faa7289717fed54aff1c at: https://bb3998a8.fastapitiangolo.pages.dev

2024-02-21 19:59 UTC, dpinezich requested changes
Awesome work, small changes (ideas) as always 👍

2024-02-23 17:03 UTC, nilslindemann commented on docs/de/docs/how-to/extending-openapi.md
> +Ist das nicht der Fall, wird er mithilfe der Hilfsfunktion unter `fastapi.openapi.utils.get_openapi` generiert.
Ja, ist klarer.

2024-02-23 17:12 UTC, nilslindemann commented
Danke wieder, @dpinezich!

2024-03-13 22:43 UTC, dpinezich approved these changes
Well done 👍

2024-03-14 16:44 UTC, merged

2024-03-14 16:44 UTC, alejsdev commented
Thanks for the help! @nilslindemann 🚀 @dpinezich 🔍️

2024-03-14 21:18 UTC, nilslindemann commented
Super, wieder eins mehr :-)