Printing object failing to encode to json
fastapi/fastapi pull request #10947
Opened 2024-01-12 13:23 UTC by leonarf

I was using FastAPI on a project an I had to see which object was making fail the json encoding to understand what to change in my code. So I suggest to add an Exception in this case that allow dev to read what object make encoding fails

2024-04-01 20:34 UTC, codespearhead approved these changes

2024-08-17 06:56 UTC, tiangolo requested changes
Thanks! Could you please add a test that shows the use case and how the current logic is not enough, and that would fail on `master` and would be solved by this?

2024-08-17 08:12 UTC, leonarf commented
I'm sorry, but my usecase is too old, and I can't remember what object I was encoding to json, and why it was failing.
But my PR just adds some logging for debugging purpose. Although, if you think it's dangerous to merge it, you can close the PR and next time I face this usecase, I'll try to write a test.

2025-02-15 11:36 UTC, tiangolo commented
Thanks for the response! I'll then close it for now. :nerd_face: :coffee:

2025-02-15 11:36 UTC, closed without merging