🌐 Add Korean translation for `docs/ko/docs/features.md`
fastapi/fastapi pull request #10976
Opened 2024-01-16 11:41 UTC by KaniKim

- Add Korean translation for docs/ko/docs/features.md
- I mistaken git push, sorry for my mistake.

2024-01-16 11:47 UTC, tiangolo commented
📝 Docs preview for commit dc79e88f10e0164e978d4a1a614a2d28af29af63 at: https://2c945df8.fastapitiangolo.pages.dev

2024-01-17 02:33 UTC, hard-coders requested changes
Thanks for your great effort! 🎉  
I looked over some untranslated and typos, so please take a look.

2024-01-17 02:33 UTC, hard-coders commented on docs/ko/docs/features.md
> +    * 최소값과 최대값을 가지는 숫자 (`int`, `float`), 그 외.
```suggestion
    * JSON 객체 (`dict`).
    * 아이템 타입을 정의하는 JSON 배열 (`list`).
    * 최소 길이와 최대 길이를 정의하는 문자열 (`str`) 필드.
    * 최솟값과 최댓값을 가지는 숫자 (`int`, `float`), 그 외.
```

"`"로 감싸져 있기 때문에 파이썬 키워드를 나타냄을 알 수 있으므로 그대로 사용함이 맞습니다.

2024-01-17 02:33 UTC, hard-coders commented on docs/ko/docs/features.md
> +Pydantic을 기반으로 하는, 데이터 베이스를 위한 <abbr title="Object-Relational Mapper">ORM</abbr>, <abbr title="Object-Document Mapper">ODM</abbr>을 포함한 외부 라이브러리를 포함합니다.
```suggestion
Pydantic을 기반으로 하는, 데이터베이스를 위한 <abbr title="Object-Relational Mapper">ORM</abbr>, <abbr title="Object-Document Mapper">ODM</abbr>을 포함한 외부 라이브러리를 포함합니다.
```

2024-01-17 02:33 UTC, hard-coders commented on docs/ko/docs/features.md
> +**FastAPI**를 사용하면 (모든 데이터 처리를 위해 FastAPI가 Pydantic을 기반으로 하기 있기에) **Pydantic**의 기능을 얻게 됩니다:
```suggestion
**FastAPI**를 사용하면 (모든 데이터 처리를 위해 FastAPI가 Pydantic을 기반으로 하기 있기에) **Pydantic**의  모든 기능을 얻게 됩니다:
```

생략가능하지만 원문의 `all of`을 살려서 모든이 추가되면 더 좋겠습니다.

2024-01-17 02:33 UTC, hard-coders commented on docs/ko/docs/features.md
> +    * Pydantic은 사용자 정의 데이터 타입을 정의할 수 있게 하거나, 검증자 데코레이터가 붙은 모델의 메서드를 사용하여 검증을 확장할 수 있습니다.
"method" 관련해서..
[한국 파이썬 용어집](https://docs.python.org/ko/3/glossary.html)과 통일성을 유지하기 위해 "메서드"가 더 나은 선택이지만,
기존에 "메소드"로 많이 번역을 했기 때문에 통일을 위해 대체했으면 합니다.....

2024-01-17 02:39 UTC, KaniKim commented on docs/ko/docs/features.md
> +어느 곳에서나 선택적 구성이 가능한 모든 것에 합리적인 기본값이 설정되어 있습니다. 모든 매개변수는 여러분이 필요하거나, 여러분이 원하는 API 정의하기 위해 미세하게 조정될 수 있습니다.
Short같은 부분의 번역이 어렵더라구요, "토막 정보"로도 번역해도 괜찮을 듯 합니다. :)

2024-01-17 02:40 UTC, KaniKim commented on docs/ko/docs/features.md
> +    * Pydantic은 사용자 정의 데이터 타입을 정의할 수 있게 하거나, 검증자 데코레이터가 붙은 모델의 메서드를 사용하여 검증을 확장할 수 있습니다.
넵 이 부분은 메소드로 대체하는 것이 좋겠네요, 기존 번역 컨벤션을 따르겠습니다 :)

2024-01-17 02:43 UTC, KaniKim commented on docs/ko/docs/features.md
> +* <abbr title="also known as: endpoints, routes">경로</abbr><abbr title="also known as HTTP methods, as POST, GET, PUT, DELETE">작동</abbr>, 매개변수, 본문 요청, 보안 그 외의 선언을 포함한 API 생성을 위한 <a href="https://githu
이 부분은 번역해서 커밋했습니다. 한번 확인 가능하시면 부탁드리겠습니다 : )

2024-01-17 02:49 UTC, tiangolo commented
📝 Docs preview for commit e05bf4b46cf30c24354aff3c7b05b67e96a147b2 at: https://b36954e0.fastapitiangolo.pages.dev

2024-01-17 03:48 UTC, hard-coders approved these changes
LGTM 🚀

2024-01-18 13:12 UTC, tiangolo commented
📝 Docs preview for commit a68914ce45d462449b15eec8e38dedd108c43586 at: https://53dd1e53.fastapitiangolo.pages.dev

2024-01-23 14:04 UTC, merged

2024-01-23 14:04 UTC, alejsdev commented
Thank you! @KaniKim 🙇‍♀️ 

And thanks for the review @hard-coders 🤓