🌐 Add Korean translation for `docs/ko/docs/tutorial/dependencies/index.md`
fastapi/fastapi pull request #10989
Opened 2024-01-18 12:57 UTC by KaniKim

- Add Korean translation for docs/ko/docs/tutorial/dependencies/index.md
- I referred to #5605, Thanks to Author

2024-01-18 13:09 UTC, tiangolo commented
📝 Docs preview for commit cc06e3d4937bbd56d4003b03dbcc0e7c7e892ecf at: https://2cd29979.fastapitiangolo.pages.dev

2024-01-18 13:17 UTC, tiangolo commented
📝 Docs preview for commit f9d48d8fdaee75ae6896c99af96d5a9dc3821988 at: https://66197e59.fastapitiangolo.pages.dev

2024-01-26 14:50 UTC, KimJoonSeo requested changes
I did some changes to make the sentences more clear.

2024-01-26 14:50 UTC, KimJoonSeo commented on docs/ko/docs/tutorial/dependencies/index.md
> +**"의존성 주입"**은 프로그래밍에서 여러분의 코드(이 경우, 경로 동작 함수)가 작동하고 사용하는 데 필요로 하는 것, "의존성"을 선언할 수 있는 방법을 의미합니다.
```suggestion
**"의존성 주입"**은 프로그래밍에서 여러분의 코드(이 경우, 경로 동작 함수)가 작동하고 사용하는 데 필요로 하는 것, 즉 "의존성"을 선언할 수 있는 방법을 의미합니다.
```

2024-01-26 14:50 UTC, KimJoonSeo commented on docs/ko/docs/tutorial/dependencies/index.md
> +그 후에, 시스템(이 경우 FastAPI)은 여러분의 코드가 요구하는 의존성을 제공하기 위해 필요한 필요한 모든 작업을 처리합니다.(의존성을 "주입"합니다)
```suggestion
그 후에, 시스템(이 경우 FastAPI)은 여러분의 코드가 요구하는 의존성을 제공하기 위해 필요한 모든 작업을 처리합니다.(의존성을 "주입"합니다)
```

2024-01-26 14:50 UTC, KimJoonSeo commented on docs/ko/docs/tutorial/dependencies/index.md
> +그저 단순한 *경로 작동 함수*가 가질 수 있는 모두 같은 매개변수를 가질 수 있는 함수입니다:
```suggestion
 *경로 작동 함수*가 가질 수 있는 모든 매개변수를 갖는 단순한 함수입니다:
```

2024-01-26 14:50 UTC, KimJoonSeo commented on docs/ko/docs/tutorial/dependencies/index.md
> +* 부가적인 쿼리 매개변수 `q`, `str`을 자료형으로 가집니다.
```suggestion
* 선택적인 쿼리 매개변수 `q`, `str`을 자료형으로 가집니다.
```

2024-01-26 14:50 UTC, KimJoonSeo commented on docs/ko/docs/tutorial/dependencies/index.md
> +* 부가적인 쿼리 매개변수 `skip`, `int`를 자료형으로 가지며 기본 값은 `0`입니다.
```suggestion
* 선택적인 쿼리 매개변수 `skip`, `int`를 자료형으로 가지며 기본 값은 `0`입니다.
```

2024-01-26 14:50 UTC, KimJoonSeo commented on docs/ko/docs/tutorial/dependencies/index.md
> +* 부가적인 쿼리 매개변수 `limit`,`int`를 자료형으로 가지며 기본 값은 `100`입니다.
```suggestion
* 선택적인 쿼리 매개변수 `limit`,`int`를 자료형으로 가지며 기본 값은 `100`입니다.
```

2024-01-26 14:50 UTC, KimJoonSeo commented on docs/ko/docs/tutorial/dependencies/index.md
> +*경로 작동 함수*의 매개변수에서 `Body`, `Query` 등을 사용하는 방식과 똑같이 새로운 매개변수와 같이 `Depends`를 사용합니다:
```suggestion
*경로 작동 함수*가 매개변수로 `Body`, `Query` 등을 사용하는 방식과 같이 새로운 매개변수로 `Depends`를 사용합니다:
```

2024-01-26 14:50 UTC, KimJoonSeo commented on docs/ko/docs/tutorial/dependencies/index.md
> +여러분은 직접 **호출하지 않았습니다** (끝에 괄호를 치지 않았습니다), 단지 `Depends()`에 매개변수처럼 넘겨 줬을 뿐입니다.
```suggestion
여러분은 직접 **호출하지 않았습니다** (끝에 괄호를 치지 않았습니다), 단지 `Depends()`에 매개변수로 넘겨 줬을 뿐입니다.
```

2024-01-26 14:50 UTC, KimJoonSeo commented on docs/ko/docs/tutorial/dependencies/index.md
> +그리고 그 함수는 매개변수를 *경로 작동 함수*가 작동하는 것과 같은 방식으로 매개변수를 받습니다.
```suggestion
그리고 그 함수는 *경로 작동 함수*가 작동하는 것과 같은 방식으로 매개변수를 받습니다.
```

2024-01-26 14:50 UTC, KimJoonSeo commented on docs/ko/docs/tutorial/dependencies/index.md
> +    여러분은 다음 장에서 함수를 제외하고서, "다른 것"이 어떻게 의존성으로 사용되는지 알게 될 것입니다.
```suggestion
    여러분은 다음 장에서 함수를 제외하고서, "다른 것들"이 어떻게 의존성으로 사용되는지 알게 될 것입니다.
```

2024-01-26 14:50 UTC, KimJoonSeo commented on docs/ko/docs/tutorial/dependencies/index.md
> +모든 요청 선언, 검증과 의존성(및 하위 의존성)에 대한 요구 사항은 동일한 OpenAPI스키마에 동합됩니다.
```suggestion
모든 요청 선언, 검증과 의존성(및 하위 의존성)에 대한 요구 사항은 동일한 OpenAPI 스키마에 통합됩니다.
```

2024-01-26 14:50 UTC, KimJoonSeo commented on docs/ko/docs/tutorial/dependencies/index.md
> +이를 보면, *경로 작동 함수*는 *경로*와 *작동*이 매칭되면 언제든지 사용되도록 정의되었으며, **FastAPI**는 올바른 매개변수를 가진 함수의 호출하고 요청에서 데이터를 추출합니다.
```suggestion
이를 보면, *경로 작동 함수*는 *경로*와 *작동*이 매칭되면 언제든지 사용되도록 정의되었으며, **FastAPI**는 올바른 매개변수를 가진 함수를 호출하고 해당 요청에서 데이터를 추출합니다.
```

2024-01-27 00:19 UTC, KaniKim commented
> I did some changes to make the sentences more clear.

Thank you for your suggestions, I changed it, please check it if you can.

2024-01-27 00:25 UTC, tiangolo commented
📝 Docs preview for commit 3d74851709129b39b19fb88c2dfc173cc2c91189 at: https://34b2bcbf.fastapitiangolo.pages.dev

2024-01-27 02:57 UTC, KimJoonSeo approved these changes

2024-01-27 09:12 UTC, merged

2024-01-27 09:12 UTC, alejsdev commented
Thank you! @KaniKim 🎉 

And thanks for your review @KimJoonSeo 🧐🔍