🌐 Add Korean translation for `/docs/ko/docs/tutorial/body.md`
fastapi/fastapi pull request #11000
Opened 2024-01-21 15:09 UTC by KaniKim

- Add Korean translation for /docs/ko/docs/tutorial/body.md

2024-01-21 15:17 UTC, tiangolo commented
📝 Docs preview for commit 63d28969333958e72cf9ceb66f90fa85d8e5f60f at: https://1d6a1f29.fastapitiangolo.pages.dev

2024-01-26 13:59 UTC, KimJoonSeo requested changes
@KaniKim  I did some changes to make the sentences more clear.

2024-01-26 13:59 UTC, KimJoonSeo commented on docs/ko/docs/tutorial/body.md
> +쿼리 매개변수를 선언할 때와 똑같이, 모델 어트리뷰트가 기본 값을 가지고 있어도 이는 필수가 아닙니다. 그외에는 필수입니다. 그저 `None`을 사용하여 선택적으로 만들 수 있습니다.
```suggestion
쿼리 매개변수를 선언할 때와 같이, 기본 값을 가지고 있는 모델 어트리뷰트는 본문에 필수로 넣지 않아도 됩니다. 그렇지 않은 어트리뷰트는 필수로 넣어야 합니다. `None`을 사용하여 어트리뷰트를 선택적으로 만들 수 있습니다.
```

2024-01-26 13:59 UTC, KimJoonSeo commented on docs/ko/docs/tutorial/body.md
> +...`description`과 `tax`는 (기본 값이 `None`으로 되어 있어) 선택적이기 때문에, 이 JSON "`object`" 다음과 같은 상황에서도 유효합니다:
```suggestion
...`description`과 `tax`는 (기본 값이 `None`으로 되어 있어) 선택적이기 때문에, 이 JSON "`object`"는 다음과 같은 상황에서도 유효합니다:
```

2024-01-26 14:03 UTC, KaniKim commented
> @KaniKim I did some changes to make the sentences more clear.

Thank you for your suggestions, I changed it.

2024-01-26 14:11 UTC, tiangolo commented
📝 Docs preview for commit 03ea86bb836917903f6730d8a73e2449e4ad2342 at: https://155337d7.fastapitiangolo.pages.dev

2024-01-26 14:18 UTC, KimJoonSeo approved these changes

2024-01-27 09:11 UTC, merged

2024-01-27 09:11 UTC, alejsdev commented
Thanks for your work! @KaniKim 🚀✨ 

And thanks for your help @KimJoonSeo 🤓