🌐 Add Turkish translation for `docs/tr/docs/about/history-design-future.md'`
fastapi/fastapi pull request #11012
Opened 2024-01-23 08:29 UTC by hasansezertasan

🌐 Add Turkish translation for `docs/tr/docs/about/history-design-future.md'`

Discussion: #9193

2024-01-23 08:30 UTC, hasansezertasan commented
@alperiox, @OzgunCaglarArslan, can you please leave a review?

2024-01-23 08:35 UTC, tiangolo commented
📝 Docs preview for commit d38dd625c502e7bab988943bbb3b825d0ec1c111 at: https://89e38dd4.fastapitiangolo.pages.dev

2024-01-23 08:46 UTC, hasansezertasan commented
@alperiox, @OzgunCaglarArslan @SametEmin, @mertssmnoglu, can you please leave a review?

2024-01-23 15:09 UTC, mertssmnoglu requested changes
Clear explanation. 
As general it's very good. But it can be more understandable the changes that i prefer. What do you think about them? @hasansezertasan

2024-01-23 15:09 UTC, mertssmnoglu commented on docs/tr/docs/history-design-future.md
> +En son <a href="https://www.jetbrains.com/research/python-developers-survey-2018/#development-tools" class="external-link" target="_blank">Python Developer Survey</a>'ine göre, kullanıcıların yaklaşı
"Bu editörler, en son yapılan Python Developer Survey'ine göre kullanıcıların yaklaşık %80'inin kullandığı editörler."
With this sentence, we can connect previous and after sentences.

2024-01-23 15:09 UTC, mertssmnoglu commented on docs/tr/docs/history-design-future.md
> +Bu demek oluyor ki **FastAPI**, Python geliştiricilerinin %80'inin kullandığı editörlerle test edildi. Ve diğer editörlerin çoğu benzer şekilde çalıştığından, bütün artıları neredeyse tüm editörlerde
According to the change that I prefer on the previous comment, the beginning can change to "Bu da demek oluyor ki..."

2024-01-23 16:18 UTC, hasansezertasan commented on docs/tr/docs/history-design-future.md
> +Bu demek oluyor ki **FastAPI**, Python geliştiricilerinin %80'inin kullandığı editörlerle test edildi. Ve diğer editörlerin çoğu benzer şekilde çalıştığından, bütün artıları neredeyse tüm editörlerde
Thank you for the review. I recommend you make a "suggestion" block for these "obvious" mistakes.

Take a look at this link: [How can I manually add suggestions in code reviews on GitHub? - Stack Overflow](https://stackoverflow.com/questions/54239733/)

Thank you for this catch, I'll update it!

2024-01-23 16:24 UTC, alperiox reviewed
Looks pretty nice, I added minor changes that may fit better to the given context.

2024-01-23 16:24 UTC, alperiox commented on docs/tr/docs/history-design-future.md
> +Önceki alternatifleri kullanarak, hepsinden öğrenme şansım oldu, fikirleri alıp, kendim ve çalıştığım geliştirici ekipleri için en iyi şekilde birleştirebildim.
```suggestion
Önceki alternatifleri kullanarak hepsinden bir şeyler öğrenip, fikirler alıp, bunları kendim ve çalıştığım geliştirici ekipler için en iyi şekilde birleştirebilme şansım oldu.
```

2024-01-23 16:24 UTC, alperiox commented on docs/tr/docs/history-design-future.md
> +Sonuç olarak, **FastAPI**'ı kodlamaya başlamadan önce birkaç ay boyunca, OpenAPI, JSON Schema, OAuth2 ve benzerlerinin tanımlamalarını inceledim. İlişkilerini, örtüşdükleri noktaları ve farklılıkları
```suggestion
Sonuç olarak, **FastAPI**'ı kodlamaya başlamadan önce birkaç ay boyunca, OpenAPI, JSON Schema, OAuth2 ve benzerlerinin tanımlamalarını inceledim. İlişkilerini, örtüştükleri noktaları ve farklılıklarını anlamaya çalıştım.
```

2024-01-23 16:24 UTC, alperiox commented on docs/tr/docs/history-design-future.md
> +**FastAPI**'ı oluşturmaya başladığımda, parçaların çoğu zaten yerindeydi, tasarım tanımlanmıştı, gereksinimler ve araçlar hazırdı ve standartlar ve tanımlar hakkındaki bilgi net ve tazeydi.
```suggestion
**FastAPI**'ı oluşturmaya başladığımda, parçaların çoğu zaten yerindeydi, tasarım tanımlanmıştı, gereksinimler ve araçlar hazırdı, standartlar ve tanımlamalar hakkındaki bilgi net ve tazeydi.
```

2024-01-23 16:24 UTC, alperiox commented on docs/tr/docs/history-design-future.md
> +Şimdiye kadar, **FastAPI**'ın fikirleri birçok kişiye faydalı olduğu apaçık ortada.
```suggestion
Şimdiye kadar, **FastAPI**'ın fikirleriyle birçok kişiye faydalı olduğu apaçık ortada.
```

2024-01-23 16:25 UTC, hasansezertasan commented on docs/tr/docs/history-design-future.md
> +**FastAPI**'ın geçmişi, büyük ölçüde öncüllerinin geçmişini kapsıyor.
```suggestion
**FastAPI**'ın geçmişi, büyük ölçüde seleflerinin geçmişini kapsıyor.
```

Nasıl duruyor @alperiox

2024-01-23 16:27 UTC, hasansezertasan commented on docs/tr/docs/history-design-future.md
> +**FastAPI**'ın geçmişi, büyük ölçüde öncüllerinin geçmişini kapsıyor.
Uygun görmezsen, en uygun gördüğün öneriyi gönderebilirsin, direkt ekleyeceğim.

2024-01-23 16:44 UTC, alperiox approved these changes
I think it is pretty accurate now, thank you for the hard work!

2024-01-23 16:51 UTC, mertssmnoglu approved these changes

2024-01-23 17:01 UTC, hasansezertasan commented
> I think it is pretty accurate now, thank you for the hard work!

Thank you for the great review 🙏

2024-01-23 17:58 UTC, tiangolo commented
📝 Docs preview for commit 6082448f82e0e7efcbfed755ef3a566f7b7ded05 at: https://491d1788.fastapitiangolo.pages.dev

2024-01-23 18:23 UTC, alperiox commented on docs/tr/docs/history-design-future.md
> +**FastAPI**'ın geçmişi, büyük ölçüde öncüllerinin geçmişini kapsıyor.
```suggestion
**FastAPI**'ın geçmişi, büyük ölçüde önceden geliştirilen araçların geçmişini kapsıyor.
```

Böyle bir şey daha uygun olabilir, açıkçası 'selef' bence yanlış değil ve buraya gayet uygun fakat ne kadar bilinen ve kullanılan bir kelime olduğundan emin değilim. @hasansezertasan

2024-01-23 18:34 UTC, hasansezertasan commented on docs/tr/docs/history-design-future.md
> +**FastAPI**'ın geçmişi, büyük ölçüde öncüllerinin geçmişini kapsıyor.
Önerin uygun, commitleyeceğim. Sonrasında son bir review atabilirsen sevinirim. Çok teşekkür ederim 🎂

2024-01-23 18:41 UTC, tiangolo commented
📝 Docs preview for commit 8415434eaad98f9b4709f4f47714345e58724a3a at: https://4f6317fd.fastapitiangolo.pages.dev

2024-01-24 00:29 UTC, egndz commented
pretty good one and easily understandable by Turkish speakers. Cheers!

2024-01-24 12:53 UTC, OzgunCaglarArslan approved these changes

2024-01-24 13:02 UTC, hasansezertasan commented
Thank you @OzgunCaglarArslan for the review!

2024-01-24 13:42 UTC, OzgunCaglarArslan requested changes

2024-01-24 13:42 UTC, OzgunCaglarArslan commented on docs/tr/docs/history-design-future.md
> +Sonuç olarak, **FastAPI**'ı kodlamaya başlamadan önce birkaç ay boyunca, OpenAPI, JSON Schema, OAuth2 ve benzerlerinin tanımlamalarını inceledim. İlişkilerini, örtüştükleri noktaları ve farklılıkları
```suggestion
Sonuç olarak, **FastAPI**'ı kodlamaya başlamadan önce, birkaç ay boyunca OpenAPI, JSON Schema, OAuth2 vb. özelliklerini inceledim. İlişkilerini, örtüştükleri noktaları ve farklılıklarını anlamaya çalıştım.
```

2024-01-24 13:42 UTC, OzgunCaglarArslan commented on docs/tr/docs/history-design-future.md
> +Bu da demek oluyor ki **FastAPI**, Python geliştiricilerinin %80'inin kullandığı editörlerle test edildi. Ve diğer editörlerin çoğu benzer şekilde çalıştığından, bütün artıları neredeyse tüm editörle
```suggestion
Bu da demek oluyor ki **FastAPI**, Python geliştiricilerinin %80'inin kullandığı editörlerle test edildi. Ve diğer editörlerin çoğu benzer şekilde çalıştığından, avantajları neredeyse tüm editörlerde çalışacaktır.
```

2024-01-24 14:21 UTC, hasansezertasan commented on docs/tr/docs/history-design-future.md
> +Sonuç olarak, **FastAPI**'ı kodlamaya başlamadan önce birkaç ay boyunca, OpenAPI, JSON Schema, OAuth2 ve benzerlerinin tanımlamalarını inceledim. İlişkilerini, örtüştükleri noktaları ve farklılıkları
Burada "özellikleri" değilde "tanımlamaları" daha uygun bir kullanım ancak virgül düzeltmesini yapabiliriz.

```suggestion
Sonuç olarak, **FastAPI**'ı kodlamaya başlamadan önce, birkaç ay boyunca OpenAPI, JSON Schema, OAuth2 ve benzerlerinin tanımlamalarını inceledim. İlişkilerini, örtüştükleri noktaları ve farklılıklarını anlamaya çalıştım.
```

2024-01-24 14:23 UTC, hasansezertasan commented
Thank you @OzgunCaglarArslan for the review. I fixed the parts you highlighter. Can you please take a look at it again?

2024-01-25 14:59 UTC, merged