🌐 Add Turkish translation for `docs/tr/docs/tutorial/query-params.md`
fastapi/fastapi pull request #11078
Opened 2024-02-02 06:42 UTC by emrhnsyts

🌐 Add Turkish translation for `docs/tr/docs/tutorial/query-params.md`

[Original File](https://github.com/tiangolo/fastapi/blob/master/docs/en/docs/tutorial/query-params.md)

Discussion: https://github.com/tiangolo/fastapi/discussions/9193

2024-02-03 19:27 UTC, tiangolo commented
📝 Docs preview for commit 20ddffb54707c651b91715e7119efa1413a5d2ac at: https://e1ff5de5.fastapitiangolo.pages.dev

2024-02-16 20:57 UTC, hasansezertasan requested changes
Eline sağlık, oldukça lezzetli görünüyor 😋

Bıraktığım yorumlarda yer alan problemler giderildiğinde incelememi devam ettireceğim.

2024-02-16 20:57 UTC, hasansezertasan commented on docs/tr/docs/tutorial/query-params.md
> +Yol parametrelerinin parçası olmayan diğer fonksiyon parametreleri tanımlandığında bunlar otomatik olarak "sorgu" parametresi olarak yorumlanır.
```suggestion
Fonksiyonda yol parametrelerinin parçası olmayan diğer tanımlamalar otomatik olarak "sorgu" parametresi olarak yorumlanır.
```

2024-02-16 20:57 UTC, hasansezertasan commented on docs/tr/docs/tutorial/query-params.md
> +Parametreler URL'nin bir parçası oldukları için doğal olarak string olarak değerlendirilirler.
```suggestion
Parametreler bağlantının bir parçası oldukları için doğal olarak string olarak değerlendirilirler.
```

2024-02-16 20:57 UTC, hasansezertasan commented on docs/tr/docs/tutorial/query-params.md
> +Sorgu, URL'deki `?` kısmından sonra gelen ve `&` işareti ile ayrılan anahtar-değer çiftlerinin oluşturduğu bir kümedir.
```suggestion
Sorgu, bağlantıdaki `?` kısmından sonra gelen ve `&` işareti ile ayrılan anahtar-değer çiftlerinin oluşturduğu bir kümedir.
```

2024-02-16 20:57 UTC, hasansezertasan commented on docs/tr/docs/tutorial/query-params.md
> +Örneğin, aşağıdaki URL'de:
```suggestion
Örneğin, aşağıdaki bağlantı da:
```

2024-02-16 20:57 UTC, hasansezertasan commented on docs/tr/docs/tutorial/query-params.md
> +* Veri <abbr title="HTTP isteği ile birlikte gelen string'i Python verisine dönüştürme">"ayrıştırma"</abbr>
```suggestion
* Veri "<abbr title="HTTP isteği ile birlikte gelen string'i Python verisine dönüştürme">ayrıştırma</abbr>"
```

Bunu böyle yapalım, Sebastian önceki sayfada olduğu gibi bir yaklaşım yapmamış, emin olamadım.

2024-02-16 20:57 UTC, hasansezertasan commented on docs/tr/docs/tutorial/query-params.md
> +Sorgu parametreleri, adres yolunun sabit bir parçası olmadıklarından dolayı opsiyoneldirler ve varsayılan değere sahip olabilirler.
```suggestion
Sorgu parametreleri, adres yolunun sabit bir parçası olmadıklarından dolayı isteğe bağlı ve varsayılan değere sahip olabilirler.
```

2024-02-16 20:57 UTC, hasansezertasan commented on docs/tr/docs/tutorial/query-params.md
> +Yani, aşağıdaki URL'ye gitmek:
```suggestion
Yani, aşağıdaki bağlantıya gitmek:
```

2024-02-16 20:57 UTC, hasansezertasan commented on docs/tr/docs/tutorial/query-params.md
> +* `skip=20`: çünkü URL'de böyle tanımlandı.
```suggestion
* `skip=20`: çünkü bağlantıda böyle tanımlandı.
```

2024-02-16 20:57 UTC, hasansezertasan commented on docs/tr/docs/tutorial/query-params.md
> +Ve parametreleri, herhangi belirli bir sıraya koymanıza da gerek yoktur.
```suggestion
Ve parametreleri, herhangi bir sıraya koymanıza da gerek yoktur.
```

2024-02-16 20:57 UTC, hasansezertasan commented on docs/tr/docs/tutorial/query-params.md
> +Fakat, bir sorgu parametresini zorunlu yapmak istiyorsanız varsayılan bir değer atama gibi bir hakkınız bulunmamaktadır:
```suggestion
Fakat, bir sorgu parametresini zorunlu yapmak istiyorsanız varsayılan bir değer atamamanız yeterli olacaktır:
```

2024-02-16 20:57 UTC, hasansezertasan commented on docs/tr/docs/tutorial/query-params.md
> +Burada `needy` parametresi `str` tipinden oluşan bir sorgu parametresidir.
```suggestion
Burada `needy` parametresi `str` tipinden oluşan zorunlu bir sorgu parametresidir.
```

2024-02-16 20:57 UTC, hasansezertasan commented on docs/tr/docs/tutorial/query-params.md
> +Eğer tarayıcınızda şu URL'yi:
```suggestion
Eğer tarayıcınızda şu bağlantıyı:
```

2024-02-16 20:57 UTC, hasansezertasan commented on docs/tr/docs/tutorial/query-params.md
> +`needy` zorunlu bir parametre olduğundan dolayı URL adresinde onu tanımlamak mecburidir:
```suggestion
`needy` zorunlu bir parametre olduğundan dolayı bağlantıda tanımlanması gerekir:
```

2024-02-16 20:57 UTC, hasansezertasan commented on docs/tr/docs/tutorial/query-params.md
> +* `limit`, opsiyonel bir `int`.
```suggestion
* `limit`, isteğe bağlı bir `int`.
```

2024-02-16 20:57 UTC, hasansezertasan commented on docs/tr/docs/tutorial/query-params.md
> +Aynı şekilde, varsayılan değerlerini `None` olarak atayarak opsiyonel parametreler tanımlayabilirsiniz:
```suggestion
Aynı şekilde, varsayılan değerlerini `None` olarak atayarak isteğe bağlı parametreler tanımlayabilirsiniz:
```

2024-02-16 20:57 UTC, hasansezertasan commented on docs/tr/docs/tutorial/query-params.md
> +## Opsiyonel Parametreler
```suggestion
## İsteğe Bağlı Parametreler
```

2024-02-16 20:57 UTC, hasansezertasan commented on docs/tr/docs/tutorial/query-params.md
> +Bu durumda, `q` fonksiyon parametresi opsiyonel olacak ve varsayılan değer olarak `None` alacaktır.
```suggestion
Bu durumda, `q` fonksiyon parametresi isteğe bağlı olacak ve varsayılan değer olarak `None` alacaktır.
```

2024-02-16 20:57 UTC, hasansezertasan commented on docs/tr/docs/tutorial/query-params.md
> +Parametre için belirli bir değer atamak istemeyip parametrenin sadece opsiyonel olmasını istiyorsanız değerini `None` olarak atayabilirsiniz.
```suggestion
Parametre için belirli bir değer atamak istemeyip parametrenin sadece isteğe bağlı olmasını istiyorsanız değerini `None` olarak atayabilirsiniz.
```

2024-02-16 20:57 UTC, hasansezertasan commented on docs/tr/docs/tutorial/query-params.md
> +    Ayrıca, [Yol Parametrelerinde](path-params.md#predefined-values){.internal-link target=_blank} de kullanıldığı şekilde `Enum` sınıfından faydalanabilirsiniz.
```suggestion
    Ayrıca, [Yol Parametreleri](path-params.md#predefined-values){.internal-link target=_blank}nde de kullanıldığı şekilde `Enum` sınıfından faydalanabilirsiniz.
```

2024-02-17 12:12 UTC, tiangolo commented
📝 Docs preview for commit bedab6494bc0c5544b99113a908379bc7b4720f1 at: https://2b6ce036.fastapitiangolo.pages.dev

2024-02-17 18:08 UTC, hasansezertasan approved these changes
Eline sağlık 🙏

2024-02-18 12:20 UTC, merged

2024-02-18 12:20 UTC, alejsdev commented
Thank you! @emrhnsyts 🤓 

And thanks for the review @hasansezertasan 🚀✨