🌐 Add Turkish translation for `docs/tr/docs/tutorial/body.md`
fastapi/fastapi pull request #11087
Opened 2024-02-03 20:14 UTC by emrhnsyts

🌐 Add Turkish translation for `docs/tr/docs/tutorial/body.md`

[Original File](https://github.com/tiangolo/fastapi/blob/master/docs/en/docs/tutorial/body.md)

Discussion: https://github.com/tiangolo/fastapi/discussions/9193

2024-02-03 20:22 UTC, tiangolo commented
📝 Docs preview for commit e1251b451a7cc5011620c024829cdadd50d2ff92 at: https://47ec9017.fastapitiangolo.pages.dev

2024-02-17 12:18 UTC, tiangolo commented
📝 Docs preview for commit af2b5b5a775470872d5a975a310e9d58f5166aff at: https://6d2e672b.fastapitiangolo.pages.dev

2025-06-16 10:32 UTC, YuriiMotov commented on docs/tr/docs/tutorial/body.md
> +Bütün güç ve avantajlarından faydalınılarak <a href="https://pydantic-docs.helpmanual.io/" class="external-link" target="_blank">Pydantic</a> modelleri, **istek** gövdeleri oluşturmak için kullanılır
```suggestion
Bütün güç ve avantajlarından faydalınılarak <a href="https://docs.pydantic.dev/" class="external-link" target="_blank">Pydantic</a> modelleri, **istek** gövdeleri oluşturmak için kullanılır.
```

2025-06-19 10:29 UTC, Rekl0w requested changes

2025-06-19 10:29 UTC, Rekl0w commented on docs/tr/docs/tutorial/body.md
> +Sorgu parametrelerinde olduğu gibi, bir model özelliği, varsayılan değere sahipse o özellik zorunlu değildir, eğer sahip değilse zorunludur. Özellikler, `None` kullanılarak  isteğe bağlı hale getiril
```suggestion
Sorgu parametrelerinde olduğu gibi, bir model özelliği, varsayılan değere sahipse o özellik zorunlu değildir, eğer sahip değilse zorunludur. Özellikler, `None` kullanılarak  isteğe bağlı hale getirilebilir.
```

2025-06-19 10:29 UTC, Rekl0w commented on docs/tr/docs/tutorial/body.md
> +Bütün güç ve avantajlarından faydalınılarak <a href="https://docs.pydantic.dev/" class="external-link" target="_blank">Pydantic</a> modelleri, **istek** gövdeleri oluşturmak için kullanılır.
```suggestion
Bütün güç ve avantajlarından faydalanılarak <a href="https://docs.pydantic.dev/" class="external-link" target="_blank">Pydantic</a> modelleri, **istek** gövdeleri oluşturmak için kullanılır.
```

2025-06-19 10:29 UTC, Rekl0w commented on docs/tr/docs/tutorial/body.md
> +Modellerimizin JSON şemaları, interaktif API dokümanında gösterilmek üzere OpenAPI tarafından oluşturulan şemanın bir parçası olur:
```suggestion
Modellerimizin JSON şemaları, etkileşimli API dokümanında gösterilmek üzere OpenAPI tarafından oluşturulan şemanın bir parçası olur:
```

2025-06-19 10:29 UTC, Rekl0w commented on docs/tr/docs/tutorial/body.md
> +Bahsedilen durumun uygulanması tavsiye edilmediğinden dolayı `GET` isteği kullanılırken Swagger UI destekli interaktif doküman, gövde için ek alan göstermeyecektir. Ayrıca aradaki proxyler de bunu de
```suggestion
Bahsedilen durumun uygulanması tavsiye edilmediğinden dolayı `GET` isteği kullanılırken Swagger UI destekli etkileşimli doküman, gövde için ek alan göstermeyecektir. Ayrıca aradaki proxyler de bunu desteklemeyebilir.
```

2025-09-05 09:07 UTC, YuriiMotov commented
As part of our recent decision to move to an automated translation process 🤖, we’re no longer accepting community-submitted translation PRs.

I’ll go ahead and close this PR. You can read more details in the announcement here: [https://fastapi.tiangolo.com/contributing/#translations](https://fastapi.tiangolo.com/contributing/?utm_source=chatgpt.com#translations)

Thank you very much for your time and efforts 🙏

2025-09-05 09:07 UTC, closed without merging