🌐 Update Turkish translation for `docs/tr/docs/tutorial/first-steps.md`
fastapi/fastapi pull request #11094
Opened 2024-02-05 19:51 UTC by hasansezertasan

🌐 Update Turkish translation for `docs/tr/docs/tutorial/first-steps.md`

Updates outdated. Fixes mistranslation.

[Original File](https://github.com/tiangolo/fastapi/blob/master/docs/en/docs/tutorial/first-steps.md)

Discussion: #9193

2024-02-06 10:31 UTC, emrhnsyts requested changes
Gerekli değişiklikler uygulandıktan sonra son olarak tekrar gözden geçireceğim. Ellerinize sağlık.

2024-02-06 10:31 UTC, emrhnsyts commented on docs/tr/docs/tutorial/first-steps.md
> +Bu tüm API'yı oluşturmak için ana etkileşim noktası olacaktır.
```suggestion
Bu, tüm API'yı oluşturmak için ana etkileşim noktası olacaktır.
```

2024-02-06 10:31 UTC, emrhnsyts commented on docs/tr/docs/tutorial/first-steps.md
> +`uvicorn` komutunda atıfta bulunulan `app` ile aynıdır.
```suggestion
Bu `app` değişkeni, `uvicorn` komutunda atıfta bulunulan değişkenin ta kendisidir.
```

2024-02-06 10:31 UTC, emrhnsyts commented on docs/tr/docs/tutorial/first-steps.md
> +### Adım 3: *Yol Operasyonu* Oluşturmak
```suggestion
### Adım 3: Bir *Yol Operasyonu* Oluşturalım
```

2024-02-06 10:31 UTC, emrhnsyts commented on docs/tr/docs/tutorial/first-steps.md
> +    "Yol" genellikle "<abbr title="Endpoint: Bitim Noktası">endpoint</abbr>" veya "<abbr title="Route: Yönlendirme/Yön">route</abbr>" olarak adlandırılabilir.
```suggestion
    "Yol" genellikle "<abbr title="Endpoint: Bitim Noktası">endpoint</abbr>" veya "<abbr title="Route: Yönlendirme/Yön">route</abbr>" olarak adlandırılır.
```

2024-02-06 10:31 UTC, emrhnsyts commented on docs/tr/docs/tutorial/first-steps.md
> +Bir API oluştururken, "yol", "kaynakları" ile "endişeleri" ayırmanın ana yoludur.
```suggestion
Bir API oluştururken, "yol", "kaynaklar" ile "endişeleri" ayırmanın ana yoludur.
```

2024-02-06 10:31 UTC, emrhnsyts commented on docs/tr/docs/tutorial/first-steps.md
> +HTTP protokolünde, bu "metodlardan" birini (veya daha fazlasını) kullanarak her yol ile iletişim kurabilirsiniz.
```suggestion
HTTP protokolünde, bu "metodlardan" birini (veya daha fazlasını) kullanarak her bir yol ile iletişim kurabilirsiniz.
```

2024-02-06 10:31 UTC, emrhnsyts commented on docs/tr/docs/tutorial/first-steps.md
> +API'lar oluştururkan, belirli bir amaca hizmet eden belirli HTTP methodlarını kullanırsınız.
```suggestion
API'lar oluştururkan, belirli bir amaca hizmet eden belirli HTTP metodlarını kullanırsınız.
```

2024-02-06 10:31 UTC, emrhnsyts commented on docs/tr/docs/tutorial/first-steps.md
> +Bu nedenle, OpenAPI'de HTTP methodlarından her birine "operasyon" denir.
```suggestion
Bu nedenle, OpenAPI'de HTTP metodlarından her birine "operasyon" denir.
```

2024-02-06 10:31 UTC, emrhnsyts commented on docs/tr/docs/tutorial/first-steps.md
> +Bizde onlara "**operasyonlar**" diyeceğiz.
```suggestion
Biz de onları "**operasyonlar**" olarak adlandıracağız.
```

2024-02-06 10:31 UTC, emrhnsyts commented on docs/tr/docs/tutorial/first-steps.md
> +`@app.get("/")` **FastAPI**'a hemen altındaki fonksiyonun aşağıdaki durumlardan sorumlu olduğunu söyler:
```suggestion
`@app.get("/")` dekoratörü, **FastAPI**'a hemen altındaki fonksiyonun aşağıdaki durumlardan sorumlu olduğunu söyler:
```

2024-02-06 10:31 UTC, emrhnsyts commented on docs/tr/docs/tutorial/first-steps.md
> +    Dekoratörü bir fonksiyonun üzerine koyarsınız. Dekoratif bir şapka gibi (sanırım terim buradan geliyor).
```suggestion
    Dekoratörler, dekoratif bir şapka gibi (muhtemelen bu sebeple öyle adlandırılıyor), fonksiyonların üzerlerine yerleştirilirler.
```

2024-02-06 10:31 UTC, emrhnsyts commented on docs/tr/docs/tutorial/first-steps.md
> +    Bizim durumumzda kullandığımız dekoratör **FastAPI**'a altındaki fonksiyonun `/` yoluna gelen `get` metodlu isteklerden sorumlu olduğunu söyler.
```suggestion
    Bizim durumumuzda, kullandığımız dekoratör, **FastAPI**'a altındaki fonksiyonun `/` yoluna gelen `get` metodlu isteklerden sorumlu olduğunu söyler.
```

2024-02-06 10:31 UTC, emrhnsyts commented on docs/tr/docs/tutorial/first-steps.md
> +    Bu bir **yol operasyon dekoratörü**.
```suggestion
    Bu bir **yol operasyonu dekoratörüdür**.
```

2024-02-06 10:31 UTC, emrhnsyts commented on docs/tr/docs/tutorial/first-steps.md
> +Ayrıca diğer operasyonları de kullanabilirsiniz:
```suggestion
Ayrıca diğer operasyonları da kullanabilirsiniz:
```

2024-02-06 10:31 UTC, emrhnsyts commented on docs/tr/docs/tutorial/first-steps.md
> +Daha az kullanılanları da kullanabilirsiniz:
```suggestion
Daha egzotik olanları da tercih edebilirsiniz:
```

2024-02-06 10:31 UTC, emrhnsyts commented on docs/tr/docs/tutorial/first-steps.md
> +Aşağıdakiler bizim **yol operasyonu fonksiyonlarımızdır**:
```suggestion
Aşağıdaki, bizim **yol operasyonu fonksiyonumuzdur**:
```

2024-02-06 10:31 UTC, emrhnsyts commented on docs/tr/docs/tutorial/first-steps.md
> +* **fonksiyon**: "dekorar"ün (`@app.get("/")`) altındaki fonksiyondur.
```suggestion
* **fonksiyon**: "dekoratör"ün (`@app.get("/")`'in) altındaki fonksiyondur.
```

2024-02-06 10:31 UTC, emrhnsyts commented on docs/tr/docs/tutorial/first-steps.md
> +Bir `GET` işlemi kullanarak "`/`" bağlantısına bir istek geldiğinde **FastAPI** tarafından çağrılır.
```suggestion
Bu fonksiyon, ne zaman bir `GET` işlemi kullanılarak "`/`" bağlantısına bir istek geldiğinde **FastAPI** tarafından çağrılır.
```

2024-02-06 10:31 UTC, emrhnsyts commented on docs/tr/docs/tutorial/first-steps.md
> +Bu durumda bir `async` fonksiyonudur.
```suggestion
Bu durumda bu fonksiyon bir `async` fonksiyondur.
```

2024-02-06 10:31 UTC, emrhnsyts commented on docs/tr/docs/tutorial/first-steps.md
> +Bunu `async def` yerine normal bir fonksiyon olarakta tanımlayabilirsiniz.
```suggestion
Bu fonksiyonu `async def` yerine normal bir fonksiyon olarak da tanımlayabilirsiniz.
```

2024-02-06 10:31 UTC, emrhnsyts commented on docs/tr/docs/tutorial/first-steps.md
> +Bir `dict`, `list`veya `str`, `int` gibi tekil değerler döndürebilirsiniz.
```suggestion
Bir `dict`, `list` veya `str`, `int` gibi tekil değerler döndürebilirsiniz.
```

2024-02-06 10:31 UTC, emrhnsyts commented on docs/tr/docs/tutorial/first-steps.md
> +Ayrıca, Pydantic modellerini de döndürebilirsiniz (bununla ilgili daha sonra ayrıntılı bilgi göreceksiniz).
```suggestion
Ayrıca, Pydantic modelleri de döndürebilirsiniz (bu konu ileriki aşamalarda irdelenecektir).
```

2024-02-06 10:31 UTC, emrhnsyts commented on docs/tr/docs/tutorial/first-steps.md
> +* **yol operasyonu fonksiyonu** (`def root(): ...` gibi) yazdık.
```suggestion
* Bir **yol operasyonu dekoratörü** (`@app.get("/")` gibi) oluşturduk.
* Bir **yol operasyonu fonksiyonu** (`def root(): ...` gibi) oluşturduk.
```

2024-02-06 15:06 UTC, tiangolo commented
📝 Docs preview for commit 1562798cc363e99e74577dfaa777d11d165f7ac1 at: https://995b1286.fastapitiangolo.pages.dev

2024-02-06 15:45 UTC, hasansezertasan commented on docs/tr/docs/tutorial/first-steps.md
> +Bir `GET` işlemi kullanarak "`/`" bağlantısına bir istek geldiğinde **FastAPI** tarafından çağrılır.
Önerin devrik duruyor, tekrar edebilir misin?

2024-02-06 15:50 UTC, tiangolo commented
📝 Docs preview for commit 33345a10b93f22f9425812a27fc5b7db60e65827 at: https://dcf44357.fastapitiangolo.pages.dev

2024-02-06 16:02 UTC, hasansezertasan commented on docs/tr/docs/tutorial/first-steps.md
> +Burada `app` değişkeni `FastAPI` sınıfının bir örneği olacaktır.
Daha önce bir nesnenin türevi  yani "instance"'ı için "örnek" kullanımı var diye hatırlıyorum.

2024-02-06 16:43 UTC, tiangolo commented
📝 Docs preview for commit bba4cb908f498828e6f5c9f0011636d348e1d48a at: https://aab9f6d7.fastapitiangolo.pages.dev

2024-02-06 19:07 UTC, tiangolo commented
📝 Docs preview for commit 57f0bd8767546d08a913ceb48f0cfda567494d0f at: https://f21b0ecf.fastapitiangolo.pages.dev

2024-02-07 16:50 UTC, emrhnsyts requested changes

2024-02-07 16:50 UTC, emrhnsyts commented on docs/tr/docs/tutorial/first-steps.md
> +Bu şema tanımı, API yollarınızla birlikte yollarınızın aldığı olası parametreleri gibi tanımlamaları içerir.
```suggestion
Bu şema tanımı, API yollarınızla birlikte yollarınızın aldığı olası parametreler gibi tanımlamaları içerir.
```

2024-02-07 16:50 UTC, emrhnsyts commented on docs/tr/docs/tutorial/first-steps.md
> +#### OpenAPI Ne İçindir?
```suggestion
#### OpenAPI Ne İşe Yarar?
```

2024-02-07 16:50 UTC, emrhnsyts commented on docs/tr/docs/tutorial/first-steps.md
> +Bir API oluştururken, "yol", "kaynaklar" ile "endişeleri" ayırmanın ana yoludur.
```suggestion
Bir API oluştururken, "yol", "kaynaklar" ile "endişeleri" ayırmanın ana yöntemidir.
```

2024-02-07 16:50 UTC, emrhnsyts commented on docs/tr/docs/tutorial/first-steps.md
> +API'lar oluştururkan, belirli bir amaca hizmet eden belirli HTTP metodlarını kullanırsınız.
```suggestion
API oluştururkan, belirli bir amaca hizmet eden belirli HTTP metodlarını kullanırsınız.
```

2024-02-07 16:50 UTC, emrhnsyts commented on docs/tr/docs/tutorial/first-steps.md
> +    Dekoratörler, dekoratif bir şapka gibi (sanırım terim buradan geliyor), fonksiyonların üzerlerine yerleştirilirler.
```suggestion
    Dekoratörler, dekoratif bir şapka gibi (sanırım terim buradan geliyor) fonksiyonların üzerlerine yerleştirilirler.
```

2024-02-07 23:04 UTC, tiangolo commented
📝 Docs preview for commit b9c3133461f961bd1e1afbc44263faaf4552aad8 at: https://1bea8536.fastapitiangolo.pages.dev

2024-02-08 10:40 UTC, emrhnsyts approved these changes

2024-02-08 10:40 UTC, tiangolo commented
📝 Docs preview for commit eac59cc90164498516dd5c2873919d9a62126a5d at: https://c914899d.fastapitiangolo.pages.dev

2024-02-08 10:42 UTC, hasansezertasan commented
Thank you @emrhnsyts for the review!

2024-02-08 13:10 UTC, merged

2024-02-08 13:11 UTC, alejsdev commented
Nice, thank you! @hasansezertasan 🥳🎉 

And thanks for the review @emrhnsyts 🔍🧐