🌐 Add Korean translation for `/docs/ko/docs/tutorial/body-fields.md`
fastapi/fastapi pull request #11112
Opened 2024-02-08 07:28 UTC by KaniKim

- Add Korean translation for /docs/ko/docs/tutorial/body-fields.md

2024-02-08 07:34 UTC, tiangolo commented
📝 Docs preview for commit 88ed1c25675341256dc9c9826732de0c824fd98b at: https://17b29546.fastapitiangolo.pages.dev

2024-02-08 15:10 UTC, KimJoonSeo requested changes
I made some changes to make it clearer

2024-02-08 15:10 UTC, KimJoonSeo commented on docs/ko/docs/tutorial/body-fields.md
> +    주목할 점은 어떻게 타입 그고 기본 값과 `Field`로 이루어진 각기 모델의 어트리뷰트가 `Path`, `Query`와 `Body`대신 `Field`를 사용하는 *경로 작동 함수*의 매개변수와 같은 구를 가지는지 입니다.
주목할 점은 타입, 기본 값 및 `Field`로 이루어진 각 모델 어트리뷰트가 `Path`, `Query`, `Body` 대신 `Field`를 사용하는 *경로 작동 함수*의 매개변수와 같은 구조를 가진다는 점 입니다.

2024-02-08 15:18 UTC, KaniKim commented
> I made some changes to make it clearer

Thank you for your changes, I reflected it. Thanks again!

2024-02-09 02:08 UTC, tiangolo commented
📝 Docs preview for commit dc39883b21ad1449904738a9cfed806e429fd9cd at: https://c340dff4.fastapitiangolo.pages.dev

2024-02-09 02:44 UTC, riroan requested changes
Hi, I made some change to fix typo. :)

2024-02-09 02:44 UTC, riroan commented on docs/ko/docs/tutorial/body-fields.md
> +`Query`, `Path`와 `Body`룰 사용해 *경로 동작 함수* 매개변수 내에서 추가적인 검증이나 메타데이터를 선언한 것처럼 Pydantic의 `Field`를 사용하여 모델 내에서 검증과 메타데이터를 선언할 수 있습니다.
`Query`, `Path`와 `Body`를 사용해 *경로 동작 함수* 매개변수 내에서 추가적인 검증이나 메타데이터를 선언한 것처럼 Pydantic의 `Field`를 사용하여 모델 내에서 검증과 메타데이터를 선언할 수 있습니다.

2024-02-09 02:50 UTC, KaniKim commented on docs/ko/docs/tutorial/body-fields.md
> +`Query`, `Path`와 `Body`룰 사용해 *경로 동작 함수* 매개변수 내에서 추가적인 검증이나 메타데이터를 선언한 것처럼 Pydantic의 `Field`를 사용하여 모델 내에서 검증과 메타데이터를 선언할 수 있습니다.
Thanks for your change. I fixed it.

2024-02-09 02:51 UTC, riroan approved these changes

2024-02-09 02:56 UTC, tiangolo commented
📝 Docs preview for commit c0affeb5b0ba53b27f6b0c574736ca8ea1d0b617 at: https://6c711184.fastapitiangolo.pages.dev

2024-02-09 06:40 UTC, KimJoonSeo approved these changes

2024-02-09 10:36 UTC, merged

2024-02-09 10:36 UTC, alejsdev commented
Thanks @KaniKim 😄 

And thanks for the help @KimJoonSeo @riroan 🚀