🌐 Add Korean translation for `/docs/ko/docs/tutorial/cookie-params.md`
fastapi/fastapi pull request #11118
Opened 2024-02-08 16:53 UTC by riroan

🌐 Add Korean translation for `/docs/ko/docs/tutorial/cookie-params.md`

2024-02-08 17:00 UTC, tiangolo commented
📝 Docs preview for commit 31ffc827e2243e88b4ebbc44b6595d5bc5f586da at: https://dd6c5295.fastapitiangolo.pages.dev

2024-02-09 01:12 UTC, KaniKim requested changes
Hi, I make some changes to your translation.

2024-02-09 01:12 UTC, KaniKim commented on docs/ko/docs/tutorial/cookie-params.md
> +`Path`와 `Query`를 사용한 동일한 구조를 이용하여 쿠키 매개변수를 선언합니다.
그런 다음, `Path`와 `Query`처럼 동일한 구조를 사용하는 쿠키 매개변수를 선언합니다.

- Path와 Query를 사용하기 보다는, Path와 Query와 비슷하다는 점에 초첨을 맞춰서 맥락을 번역하면 될 것 같다는 의견입니다.

2024-02-09 01:12 UTC, KaniKim commented on docs/ko/docs/tutorial/cookie-params.md
> +    `Query`, `Path`, `Cookie` 그리고 다른 것들을 `fastapi`에서 임포트 할 때, 이들은 실제로 특별한 클래스를 반환하는 함수임을 기억하세요.
`Query`, `Path`, `Cookie` 그리고 다른 것들은 `fastapi`에서 임포트 할 때, 실제로는 특별한 클래스를 반환하는 함수임을 기억하세요.

2024-02-09 01:12 UTC, KaniKim commented on docs/ko/docs/tutorial/cookie-params.md
> +    쿠키를 선언하기 위해서 `Cookie`를 사용해야 합니다. 그렇지 않으면 해당 매개변수를 쿼리 매개변수로 해석하기 때문입니다.
쿠키를 선언하기 위해서는 `Cookie`를 사용해야 합니다. 그렇지 않으면 해당 매개변수를 쿼리 매개변수로 해석하기 때문입니다.

2024-02-09 02:26 UTC, tiangolo commented
📝 Docs preview for commit 59ee2b716028da7e9cfd6016e17f59500c21f1c4 at: https://33a68b1f.fastapitiangolo.pages.dev

2024-02-09 02:40 UTC, KaniKim approved these changes

2024-02-09 10:34 UTC, merged

2024-02-09 10:35 UTC, alejsdev commented
Thanks for your work @riroan 🤓 

And thanks for the review @riroan 🧐🔍