Add Korean translation for `/docs/ko/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md`
fastapi/fastapi pull request #11124
Opened 2024-02-09 11:56 UTC by riroan

Add Korean translation for `/docs/ko/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md`

2024-02-09 12:02 UTC, tiangolo commented
📝 Docs preview for commit dfa6427c5f3387c7c6ebb4468a49675e12da0a33 at: https://c9673e34.fastapitiangolo.pages.dev

2024-02-09 15:42 UTC, tiangolo commented
📝 Docs preview for commit 1490b4c7feb7e93ff58b12ca9710c747e8dc31db at: https://8f9fa83a.fastapitiangolo.pages.dev

2024-02-09 16:08 UTC, tiangolo commented
📝 Docs preview for commit 1ccbaa34448676ea54c6489695fc2e8f6e811b59 at: https://577bdac2.fastapitiangolo.pages.dev

2024-02-09 23:49 UTC, KaniKim requested changes

2024-02-09 23:49 UTC, KaniKim commented on docs/ko/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +어떤 경우엔, *경로 동작 함수* 안에서 의존성의 리턴 값이 필요하지 않습니다.
몇몇 경우에는, *경로 작동 함수* 안에서 의존성의 반환 값이 필요하지 않습니다.

- 확인해본 결과 번역에서 리턴 대신 반환을 써온 것이 많아 이렇게 표현하는 것이 좋을 것 같습니다.
- 경로 작동의 경우 https://github.com/tiangolo/fastapi/discussions/3167 을 참고 해주시면 감사하겠습니다.

2024-02-09 23:49 UTC, KaniKim commented on docs/ko/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +그런 경우에, `Depends`를 사용하여 *경로 동작 함수*의 매개변수로 선언하는 것보다 *경로 동작 데코레이터*에 `dependencies`의 `list`를 추가할 수 있습니다.
그런 경우에, `Depends`를 사용하여 *경로 작동 함수*의 매개변수로 선언하는 것보다 *경로 작동 데코레이터*에 `dependencies`의 `list`를 추가할 수 있습니다.

2024-02-09 23:49 UTC, KaniKim commented on docs/ko/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +## *경로 동작 데코레이터*에 `dependencies` 추가하기
## *경로 작동 데코레이터*에 `dependencies` 추가하기

2024-02-09 23:49 UTC, KaniKim commented on docs/ko/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +*경로 동작 데코레이터*는 `dependencies`라는 선택적인 인자를 받습니다.
*경로 작동 데코레이터*는 `dependencies`라는 선택적인 인자를 받습니다.

2024-02-09 23:49 UTC, KaniKim commented on docs/ko/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +그것은 `Depends()`의 `list`여야합니다:
`Depends()`로 된 `list`이어야합니다:

2024-02-09 23:49 UTC, KaniKim commented on docs/ko/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +이러한 의존성들은 기존 의존성들과 같은 방식으로 실행/해결됩니다. 그러나 값은 (무엇이든 반환한다면) *경로 동작 함수*에 제공되지 않습니다.
이러한 의존성들은 기존 의존성들과 같은 방식으로 실행/해결됩니다. 그러나 값은 (무엇이든 반환한다면) *경로 작동 함수*에 제공되지 않습니다.

2024-02-09 23:49 UTC, KaniKim commented on docs/ko/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +    일부 편집기에선 사용되지 않는 함수 매개변수를 검사하고 오류로 표시합니다.
일부 편집기에서는 사용되지 않는 함수 매개변수를 검사하고 오류로 표시합니다.

2024-02-09 23:49 UTC, KaniKim commented on docs/ko/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +    *경로 동작 데코레이터*에서 `dependencies`를 사용하면 편집기/툴 오류를 피하면서 실행되도록 할 수 있습니다.
*경로 작동 데코레이터*에서 `dependencies`를 사용하면 편집기/도구 오류를 피하며 실행되도록 할 수 있습니다.

2024-02-09 23:49 UTC, KaniKim commented on docs/ko/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +다음 의존성은 기존 의존성과 동일하게 오류를 `raise`시킬 수 있습니다:
다음 의존성은 기존 의존성과 동일하게 예외를 `raise`를 일으킬 수 있습니다:

- Exception의 뜻에 방점을 두는 것이 좋을 것 같습니다.

2024-02-09 23:49 UTC, KaniKim commented on docs/ko/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +값을 반환하거나 하지 않을 수 있으며 값은 사용되지 않습니다.
값을 반환하거나, 그러지 않을 수 있으며 값은 사용되지 않습니다.

2024-02-09 23:49 UTC, KaniKim commented on docs/ko/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +그래서 이미 다른 곳에서 사용된 (값을 반환하는) 기존 의존성을 재사용할 수 있고 값은 사용되지 않지만 의존성은 실행될 것입니다:
그래서 이미 다른 곳에서 사용된 (값을 반환하는) 일반적인 의존성을 재사용할 수 있고, 비록 값은 사용되지 않지만 의존성은 실행될 것입니다:

- "사용된"과 "기존"이 겹치는 듯 합니다.

2024-02-09 23:49 UTC, KaniKim commented on docs/ko/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +## *경로 동작* 그룹에 대한 의존성
## *경로 작동* 그룹에 대한 의존성

2024-02-09 23:49 UTC, KaniKim commented on docs/ko/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +나중에 여러 파일을 가지고 있을 수 있는 더 큰 애플리케이션을 구조화하는 법([더 큰 애플리케이션 - 여러 파일들](../../tutorial/bigger-applications.md){.internal-link target=_blank})을 읽을 때, *경로 동작* 그룹에 대한 단일 `dependencies` 매개변수를 선언하는 법에 대해서 배우게 될
나중에 여러 파일을 가지고 있을 수 있는 더 큰 애플리케이션을 구조화하는 법([더 큰 애플리케이션 - 여러 파일들](../../tutorial/bigger-applications.md){.internal-link target=_blank})을 읽을 때, *경로 작동* 모음에 대한 단일 `dependencies` 매개변수를 선언하는 법에 대해서 배우게 될 것입니다.

- 그룹에 대해서 애매한 감이 있지만 한국어로 쓰는 것을 지향하기에, 모음으로 저는 번역하긴 했습니다. 이 부분은 넘기셔도 상관 없을 것 같습니다.

2024-02-09 23:49 UTC, KaniKim commented on docs/ko/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +다음으로 각 *경로 동작*에 적용되도록 `FastAPI` 애플리케이션 전체에 의존성을 추가하는 법을 볼 것입니다.
다음으로 각 *경로 작동*에 적용되도록 `FastAPI` 애플리케이션 전체에 의존성을 추가하는 법을 볼 것입니다.

2024-02-09 23:49 UTC, KaniKim commented on docs/ko/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +# 경로 동작 데코레이터에서의 의존성
# 경로 작동 데코레이터에서의 의존성

2024-02-10 00:03 UTC, KaniKim commented
Hi, thank you for your translation👍 I make some changes and please check these.

2024-02-10 03:48 UTC, riroan commented on docs/ko/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +나중에 여러 파일을 가지고 있을 수 있는 더 큰 애플리케이션을 구조화하는 법([더 큰 애플리케이션 - 여러 파일들](../../tutorial/bigger-applications.md){.internal-link target=_blank})을 읽을 때, *경로 동작* 그룹에 대한 단일 `dependencies` 매개변수를 선언하는 법에 대해서 배우게 될
모음이 더 괜찮은 것 같습니다.

2024-02-10 03:50 UTC, riroan commented
@KaniKim Thanks for your detail review.

2024-02-10 03:54 UTC, tiangolo commented
📝 Docs preview for commit faad09b1b99955a222423fb9850d2bca7d27adec at: https://15a249f7.fastapitiangolo.pages.dev

2024-02-10 07:02 UTC, KaniKim approved these changes
LGTM!

2024-02-11 13:49 UTC, merged

2024-02-11 13:49 UTC, alejsdev commented
Thanks for your contribution @riroan 🥳🎉 

And thanks for the help @KaniKim 🤓