🌐 Add Korean translation for Add Korean translation for `/docs/ko/docs/tutorial/dependencies/global-dependencies.md`
fastapi/fastapi pull request #11123
Opened 2024-02-09 11:17 UTC by riroan

🌐 Add Korean translation for Add Korean translation for `/docs/ko/docs/tutorial/dependencies/global-dependencies.md`

2024-02-09 11:23 UTC, tiangolo commented
📝 Docs preview for commit d14774d26446345ad5e9c1771d4f50313ee630d4 at: https://e6d8c856.fastapitiangolo.pages.dev

2024-02-10 04:04 UTC, tiangolo commented
📝 Docs preview for commit 656329438e96a5760b47a0500eaad15f5798e6e0 at: https://010f8540.fastapitiangolo.pages.dev

2024-02-12 14:24 UTC, KimJoonSeo requested changes
I made a change to make it clearer.

2024-02-12 14:24 UTC, KimJoonSeo commented on docs/ko/docs/tutorial/dependencies/global-dependencies.md
> +나중에 여러 파일을 가지고 있을 수 있는 더 큰 애플리케이션을 구조화하는 법([더 큰 애플리케이션 - 여러 파일들](../../tutorial/bigger-applications.md){.internal-link target=_blank})을 읽을 때, *경로 작동* 그룹에 대한 단일 `dependencies` 매개변수를 선언하는 법에 대해서 배우게 될
이후에 여러 파일들을 가지는 더 큰 애플리케이션을 구조화하는 법([더 큰 애플리케이션 - 여러 파일들](../../tutorial/bigger-applications.md){.internal-link target=_blank})을 읽을 때, *경로 작동* 그룹에 대한 단일 `dependencies` 매개변수를 선언하는 법에 대해서 배우게 될 것입니다.

2024-02-13 12:08 UTC, riroan commented
@KimJoonSeo Thanks for your review :)

2024-02-13 12:18 UTC, tiangolo commented
📝 Docs preview for commit 03f1ed9dbb0b79194d2359e211e66d38b32b1cb8 at: https://b5c4124e.fastapitiangolo.pages.dev

2024-02-13 14:57 UTC, KimJoonSeo approved these changes

2024-02-14 15:05 UTC, merged

2024-02-14 15:05 UTC, alejsdev commented
Thank you! @riroan 🤓🎉 

And thanks for the help @KimJoonSeo ✌️