Updated the docs according to issue #10786
fastapi/fastapi pull request #11176
Opened 2024-02-21 13:08 UTC by Mkznd

Deleted the problematic line about RequestValidationError being a subclass of Pydantic ValidationError, according to issue #10786

2024-02-21 13:15 UTC, tiangolo commented
📝 Docs preview for commit 328a991b80cbcc43da32117e6507641af60b4a6f at: https://08b865a4.fastapitiangolo.pages.dev

2024-04-01 17:48 UTC, codespearhead commented
Issue #10786 was closed since it's a duplicate of #10424 .

Can you [link this PR](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) to that issue ( #10424 )?

2024-04-01 17:48 UTC, codespearhead approved these changes

2025-06-06 06:58 UTC, YuriiMotov commented
Alternative PR to solve the same issue: #11542

2025-07-17 19:39 UTC, YuriiMotov requested changes
@Mkznd, thanks for your interest and efforts, but I think things are more complicated here.

I looked at this part of docs and I think the whole [Override the default exception handlers](https://fastapi.tiangolo.com/tutorial/handling-errors/#override-the-default-exception-handlers) section should be revised and partially rewritten.
I will suggest my vision of it a bit later.
If anybody else is willing to take this over, please go ahead!

2025-07-17 19:39 UTC, YuriiMotov commented on docs/en/docs/tutorial/handling-errors.md
> +**FastAPI** uses `RequestValidationError` so that, if you use a Pydantic model in `response_model`, and your data has an error, you will see the error in your log.
This is actually wrong statement.
In case of error during the response validation, FastAPI raises `ResponseValidationError`

2025-07-26 11:39 UTC, tiangolo commented
Thanks for the interest! For now, I'll pass on this one. :coffee:

2025-07-26 11:39 UTC, closed without merging