Fix #9116 form and file order
fastapi/fastapi pull request #11194
Opened 2024-02-25 15:07 UTC by thomasleveil

This PR updates the fix (6185a92) from @jsg921019 so that tests pass with the latest FastAPI code (0.110.0).
It also adds a test to cover the case with multiple files, and another to ensure the order of parameters in an endpoint definition does not affect the way FastAPI handles the request.

**Problem**
When declaring an endpoint which accepts a `File` but also a `Form` parameter, the `File` parameter must be declared first or the endpoint would respond with error 422.

**Context**
- See discussion #9116
- And probably also #4625

2024-02-25 15:48 UTC, YuriiMotov requested changes
Nothing critical (except import from typing).

I think it would be better to put all these related tests into one file and get rid of some of them (like `test_post_form_no_file` (and so on) for multiple files)

2024-02-25 16:09 UTC, thomasleveil commented
Thank you for the feed back. I pushed force with your suggested changes. Let me know if anything else can be improved.

2024-02-25 16:17 UTC, yezz123 approved these changes

2024-02-25 16:17 UTC, YuriiMotov approved these changes
The solution works.
Tests cover the issue. Tests fail before changes and pass after

2024-11-22 13:39 UTC, cfreksen commented
I am wondering if this PR has been forgotten?

I am not that familiar with the workflow in this repository, so excuse me if these things just takes time or if this has low priority and there have been more important things to spend your time on.

However, I was affected by #9116 which led me to this PR, and since it has some approvals and it hasn't been touched in 9 months, I thought it would be ok to "bump" it.

2025-06-20 14:20 UTC, carl-sauter commented
Hey what about this pr? At least there should be a better error message. Wasted my time only for finding this.

2025-06-21 17:10 UTC, YuriiMotov commented
@thomasleveil, thanks for contributing to FastAPI!
Would you like to continue working on this PR?
There is a conflict with `master` that needs to be resolved

2025-06-22 17:23 UTC, thomasleveil commented
Here you go @YuriiMotov, fix re-written

2025-06-23 06:39 UTC, YuriiMotov commented
@thomasleveil, great job!

As the branch that handles list of files modified, I think it should also be covered by tests.
What do you think?
As I see it, it could be just adding 2 more endpoints (`file_list_before_form`, `file_list_after_form`) and adding them to `parametrize`

2025-06-23 10:03 UTC, thomasleveil commented
@YuriiMotov 
> As the branch that handles list of files modified

I don't get what you mean or refer to

2025-06-23 10:10 UTC, YuriiMotov commented
> I don't get what you mean or refer to

I'm talking about `elif` block:
```python
        elif (
            is_bytes_sequence_field(field)
            and isinstance(field_info, params.File)
            and value_is_sequence(value)
        ):
```
It handles list of files and it was also modified. So, I think it should be covered by tests

2025-06-23 13:03 UTC, thomasleveil commented
@YuriiMotov here you go.

2025-06-23 13:05 UTC, YuriiMotov approved these changes
LGTM!

2025-09-20 19:55 UTC, tiangolo approved these changes
Great, thank you! 🚀 🙌

2025-09-20 19:55 UTC, merged