Fix Separate OpenAPI Schemas Docs
fastapi/fastapi pull request #11201
Opened 2024-02-26 12:30 UTC by philipp-eisen

See https://github.com/tiangolo/fastapi/discussions/10453

2024-02-26 12:36 UTC, tiangolo commented
📝 Docs preview for commit 7f588fe219538c7bdea746b42e7da087e1a728dd at: https://143734ac.fastapitiangolo.pages.dev

2024-02-26 13:14 UTC, tiangolo commented
📝 Docs preview for commit 438195abebdf30fca2675cee298d78d35e031cb9 at: https://e03a48a7.fastapitiangolo.pages.dev

2024-02-26 13:22 UTC, tiangolo commented
📝 Docs preview for commit 5ecd7783315232d24c601e8a83b9a3111d63713e at: https://64765fed.fastapitiangolo.pages.dev

2025-06-10 10:01 UTC, YuriiMotov requested changes

2025-06-10 10:01 UTC, YuriiMotov commented on docs/en/docs/how-to/separate-openapi-schemas.md
> +    In the current behavior of pydantic separate output schemas are only created if the config
This statement is not true. `separate_input_output_schemas` is not only about fields with default value:

```python
from fastapi import FastAPI
from pydantic import BaseModel, Field

app = FastAPI(separate_input_output_schemas=True)

class Item(BaseModel):
    name: str = Field(serialization_alias="user_name")
    price: float

@app.post("/items/", response_model=Item)
def create_item(item: Item):
    return item
```
Result:
```json
      "Item-Input": {
        "properties": {
          "name": {
            "type": "string",
            "title": "Name"
          },
          "price": {
            "type": "number",
            "title": "Price"
          }
        },
        "type": "object",
        "required": [
          "name",
          "price"
        ],
        "title": "Item"
      },
      "Item-Output": {
        "properties": {
          "user_name": {
            "type": "string",
            "title": "User Name"
          },
          "price": {
            "type": "number",
            "title": "Price"
          }
        },
        "type": "object",
        "required": [
          "user_name",
          "price"
        ],
        "title": "Item"
      },
```

2025-07-10 22:18 UTC, closed without merging