🌐 Add Turkish translation for `docs/tr/docs/tutorial/body-fields.md`
fastapi/fastapi pull request #11207
Opened 2024-02-27 09:49 UTC by emrhnsyts

🌐 Add Turkish translation for `docs/tr/docs/tutorial/body-fields.md`

[Original File](https://github.com/tiangolo/fastapi/blob/master/docs/en/docs/tutorial/body-fields.md)

Discussion: https://github.com/tiangolo/fastapi/discussions/9193

2024-02-27 09:58 UTC, tiangolo commented
📝 Docs preview for commit 87f1969df073862b3cc6944a1d05ecbb1c1d6eca at: https://4ac4d3ce.fastapitiangolo.pages.dev

2025-06-19 10:30 UTC, Rekl0w requested changes

2025-06-19 10:30 UTC, Rekl0w commented on docs/tr/docs/tutorial/body-fields.md
> +`Field` ifadesi `Query`, `Path` ve `Body` ifadeleri gibi çalışır ve aynı parametrelere sahiptir vb.
This sentence needs examples for the `vb` word. Like `(örneğin title, description, example, gt, max_length gibi).`.

2025-09-05 09:06 UTC, YuriiMotov commented
As part of our recent decision to move to an automated translation process 🤖, we’re no longer accepting community-submitted translation PRs.

I’ll go ahead and close this PR. You can read more details in the announcement here: [https://fastapi.tiangolo.com/contributing/#translations](https://fastapi.tiangolo.com/contributing/?utm_source=chatgpt.com#translations)

Thank you very much for your time and efforts 🙏

2025-09-05 09:06 UTC, closed without merging