🌐 Add Azerbaijani translation for resources page and its subpages
fastapi/fastapi pull request #11218
Opened 2024-02-28 19:52 UTC by vusallyv

2024-02-28 20:10 UTC, tiangolo commented
📝 Docs preview for commit c12a7ebc5057db9e67ed0e88e6486ed93278ae69 at: https://33b54ba2.fastapitiangolo.pages.dev

2024-03-02 12:41 UTC, leylaeminova approved these changes

2024-03-14 17:24 UTC, TalehIlqar approved these changes

2024-03-31 17:25 UTC, codespearhead commented
Do you guys happen to know one more Azerbaijani developer you can ask a [PR review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) from?

2024-04-01 06:55 UTC, ibrahimshikhaliyev approved these changes

2024-04-01 07:11 UTC, tiangolo commented
📝 Docs preview for commit 5a15cbba87c7fbf6e3926fe57d1f52f51296c7f2 at: https://a5896171.fastapitiangolo.pages.dev

2024-04-01 07:55 UTC, codespearhead commented
There are 3 reviews @alejsdev . Seems to be ready to merge.

2024-04-02 04:10 UTC, tiangolo commented
Thanks @vusallyv! :nerd_face: 

Please separate this PR into multiple PRs, one per file. That way it's easier to review, approve, and merge them.

For example, the original file for `docs/az/docs/project-generation.md` was changed, and it's now obsolete in this PR, so I can't merge the other changes with it. :sweat_smile:

2024-04-25 08:40 UTC, nemoralis requested changes
There are also grammatical mistakes that I have not mentioned. This should be fixed before the merge

2024-04-25 08:40 UTC, nemoralis commented on docs/az/docs/external-links.md
> +"**FastAPI**"ın daimi olaraq böyüyən böyük bir icması var.
suffix should be "-nın"

2024-05-26 03:13 UTC, tiangolo commented
As this PR had requested changes to be applied but has been inactive for a while, it's now going to be closed. But if there's anyone interested, feel free to create a new PR.

2024-05-26 03:13 UTC, closed without merging