🌐 Add Bengali translations for `docs/bn/docs/python-types.md`
fastapi/fastapi pull request #11376
Opened 2024-03-30 10:48 UTC by imtiaz101325

This pull request adds Bengali translations for the `docs/bn/docs/python-types.md` file.

2024-03-30 10:54 UTC, tiangolo commented
📝 Docs preview for commit 9d15da25fd6a23ddd3790d8d6e26c31e0a67e4ff at: https://baa0dc1c.fastapitiangolo.pages.dev

2024-03-31 19:03 UTC, codespearhead commented
Do you happen to know three Bengali developers that you can ask a [PR review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) from? [This](https://github.com/tiangolo/fastapi/pulls?q=is%3Apr+bengali) might help.

2024-04-02 11:44 UTC, shabab477 approved these changes
Hi Bengali developer here, LGTM !

2024-04-03 03:57 UTC, tiangolo requested changes
Please remove the image files. :nerd_face:

2024-04-03 03:57 UTC, tiangolo commented on docs/bn/docs/img/python-types/image01.png
Please remove these images, using the original URLs from the original doc in English should work fine. :nerd_face:

2024-04-03 11:31 UTC, tiangolo commented
📝 Docs preview for commit d1eb957c20125f04ac17c9b46d6ae46afacfd291 at: https://37cc6e39.fastapitiangolo.pages.dev

2024-04-03 11:32 UTC, imtiaz101325 commented on docs/bn/docs/img/python-types/image01.png
Ah! Did not know. It wasn't working locally. Updated it!

2024-04-03 15:31 UTC, tiangolo commented on docs/bn/docs/img/python-types/image01.png
Great, thanks!

2024-04-03 15:31 UTC, tiangolo approved these changes

2024-04-03 15:34 UTC, merged