🌐 Add Russian translation for docs/ru/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
fastapi/fastapi pull request #11411
Opened 2024-04-05 07:32 UTC by anton2yakovlev

2024-04-05 07:37 UTC, tiangolo commented
📝 Docs preview for commit bccaf5d02b9f72ebe046a4d2f78b8bc8cef7df05 at: https://b583a413.fastapitiangolo.pages.dev

2024-04-05 09:16 UTC, arynoot requested changes

2024-04-05 09:18 UTC, arynoot commented on docs/ru/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +И они могут возвращать значения или нет, эти значения ипользоваться не будут.
typo: ипользоваться

2024-04-05 12:47 UTC, anton2yakovlev commented on docs/ru/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +Для таких ситуаций, вместо объявления *функции операции пути* с параметром `Depends`, вы можете добавить список зависимотей `dependencies` в *декоратор операции пути*.
> typo: зависимотей

fixed

2024-04-05 12:47 UTC, anton2yakovlev commented on docs/ru/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +И они могут возвращать значения или нет, эти значения ипользоваться не будут.
> typo: ипользоваться

fixed

2024-04-05 14:36 UTC, arynoot approved these changes

2024-04-05 16:11 UTC, s111d reviewed
В целом – хорошо. Нраица.

2024-04-05 16:11 UTC, s111d commented on docs/ru/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +### Вызов исключений
Либо "создание", "порождение".

2024-04-05 16:11 UTC, s111d commented on docs/ru/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +И они могут возвращать значения или нет, эти значения ипользоваться не будут.
"Они могут и возвращать и не возвращать значений – те использоваться не будут."

иСпользоваться

2024-04-05 16:11 UTC, s111d commented on docs/ru/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +Таким образом, вы можете переиспользовать обычную зависимость (возвращающую значение), которую вы уже используете где-то в другом месте. И хотя значение не будет использоваться, зависимость будет вып
Замечание: есть такая фишка в переводе, что предложения обычно не разрубают на части. Считается, что предложение должно переводиться предложением.

2024-04-05 16:11 UTC, s111d commented on docs/ru/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +## Dependencies для группы *операторов путей*
По докам сейчас используются "операцИИ пути". Хотя это довольно коряво, речь идёт просто о маршрутизации и её обработчиках.

2024-04-05 16:11 UTC, s111d commented on docs/ru/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +Позже, читая о том как структурировать большие приложения ([Bigger Applications - Multiple Files](../../tutorial/bigger-applications.md){.internal-link target=_blank}), возможно, с несколькими файлам
возможно, ИЗ нескольких файлов – либо "многофайловые"

можно подчеркнуть: "единый параметр" и, допустим, "для всей группы..."

2024-04-05 16:11 UTC, s111d commented on docs/ru/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +## Глобальный Dependencies
ГлобальныЕ ? Или это один объект?

2024-04-05 16:11 UTC, s111d commented on docs/ru/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +Далее мы увидим, как можно добавить dependencies для всего `FastAPI` приложения, так чтобы они применились к каждой *операции пути*.
ПрименЯлись, здесь несовершенное.

2024-04-06 09:11 UTC, tiangolo commented
📝 Docs preview for commit 4e9f38f57f9d1ef0ace9950b0b81d5d9ffa0aaaf at: https://75fad4e6.fastapitiangolo.pages.dev

2024-04-06 09:18 UTC, anton2yakovlev commented on docs/ru/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +### Вызов исключений
`Вызов исключений` это общепринятое выражение. Оно используется например известной книге _"Изучаем python", Марк Лутц_. 
Официальной документации python нет на русском, но во многих пользовательских документациях тоже используется `вызов исключений` [пример](https://pythonru.com/osnovy/obrabotka-iskljuchenij-python-blok-try-except-blok-finally)

2024-04-06 09:22 UTC, anton2yakovlev commented on docs/ru/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +## Исключения в dependencies и возвращаемые значения
В этом разделе речь как раз таки о питоновских исключениях и их вызове с помощью `raise`.

> Raise exceptions
> 
> These dependencies can raise exceptions, the same as normal dependencies:
> ```
> async def verify_token(x_token: Annotated[str, Header()]):
>     if x_token != "fake-super-secret-token":
>         raise HTTPException(status_code=400, detail="X-Token header invalid")
> ```

2024-04-06 09:24 UTC, anton2yakovlev commented
> В целом – хорошо. Нраица.

Привет, спасибо за ревью! Все поправил за исключением пары моментов, по ним отписался

2024-04-06 15:43 UTC, merged

2024-04-06 15:44 UTC, alejsdev commented
Thanks for the contribution! @anton2yakovlev :nerd_face: :rocket: 

And thanks for the review @arynoot @s111d :mag:

2024-04-06 15:58 UTC, s111d commented on docs/ru/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +### Вызов исключений
Большинство книг по IT сейчас – не аргумент в плане русского языка, вне зависимости от издателя. Так же как мнение большинства людей, "общепринятость" и т.п., – достаточно посмотреть как в этой документации перевели "path operation function". 
Очень плохо с переводами сейчас, как и с языком в целом. 
Здесь просто предложены альтернативы. Про исключения традиционно говорят "бросить", "возбудить" – чтобы подчеркнуть, что ситуация нестандартная. Почему обращаю внимание: вызывают обычно всё-таки функцию или метод. Call и Raise – не одно и то же, разные глаголы.

2024-04-06 16:01 UTC, s111d commented on docs/ru/docs/tutorial/dependencies/dependencies-in-path-operation-decorators.md
> +## Исключения в dependencies и возвращаемые значения
Не критично.

2025-06-18 08:59 UTC, Muaytie666 approved these changes