Add files via upload
fastapi/fastapi pull request #11429
Opened 2024-04-12 13:00 UTC by Mgcsuper

A possible translation in frensh of the doc file testing.md

2024-04-12 13:09 UTC, tiangolo commented
📝 Docs preview for commit 8d6b290d0943c286f72555bc2815577c3ff37edf at: https://a0d7986f.fastapitiangolo.pages.dev

2024-04-18 22:48 UTC, tiangolo commented
📝 Docs preview for commit a171dbd3f50465984c7b221a012f8f3d359f8ac4 at: https://f9b182bf.fastapitiangolo.pages.dev

2024-04-19 06:18 UTC, Mgcsuper commented
I don't know how to do two different pull requests

2024-04-19 06:21 UTC, tiangolo commented
📝 Docs preview for commit d49ee02f440787d064c6fdddf3468512c92ffcd0 at: https://cde026da.fastapitiangolo.pages.dev

2024-04-19 15:43 UTC, tiangolo commented
📝 Docs preview for commit ab36385ded0135479d421010c96a2a06ab217d44 at: https://962b54f3.fastapitiangolo.pages.dev

2024-04-20 11:20 UTC, tiangolo commented
📝 Docs preview for commit 04ec885accdf00f6f820dae9a1d45c2ec8b9eda4 at: https://1f7cc2c4.fastapitiangolo.pages.dev

2024-04-23 00:10 UTC, tiangolo commented
📝 Docs preview for commit dab148cba8f4b093174d66c2b0057943810a6d4a at: https://21a82c31.fastapitiangolo.pages.dev

2024-06-28 09:32 UTC, GDemay requested changes
I improved the translation and fixed the errors. To be transparent, I think there are still some mistakes in grammar, accents, etc., but it's a good improvement.

2024-06-28 09:32 UTC, GDemay commented on docs/fr/docs/tutorial/tests.md
> +Écrivez des instruction d'assertion `assert` simples avec les expressions Python standard qu'il est necessaire de vérifier (de nouveau, c'est une pratique standard de `pytest`)."
```suggestion
Écrivez des instructions d'assertion `assert` simples avec les expressions Python standard qu'il est necessaire de vérifier (de nouveau, c'est une pratique standard de `pytest`)."
```

2024-06-28 09:32 UTC, GDemay commented on docs/fr/docs/tutorial/tests.md
> +    il est utile de remarquer que les fonction de test sont normal `def`, et non `async def`
```suggestion
    il est important de remarquer que les fonction de tests sont normal `def`, et non `async def`
```

2024-06-28 09:32 UTC, GDemay commented on docs/fr/docs/tutorial/tests.md
> +    Et les appel au client sont aussi normaux, pas besoin d'utiliser `await`
```suggestion
    Les appels au client sont aussi normaux, pas besoin d'utiliser `await`
```

2024-06-28 09:32 UTC, GDemay commented on docs/fr/docs/tutorial/tests.md
> +    Si vous chercher tout de même à utiliser la foncion `async` dans vos test, à l'exeption d’envoyer des requêtes à votre application FastAPI (par exemple, des fonctions de base de données asynchron
```suggestion
        Si vous devez utiliser `async` dans vos tests (par exemple, pour des fonctions de base de données asynchrones), sauf pour envoyer des requêtes à votre application FastAPI, consultez les [Tests asynchrones](../advanced/async-tests.md) {.internal-link target=_blank} dans le tutoriel avancé.
.

```

2024-06-28 09:32 UTC, GDemay commented on docs/fr/docs/tutorial/tests.md
> +Et votre application **FastAPI** peut également être composée de plusieurs fichiers/modules, etc.
```suggestion
Votre application **FastAPI** peut également être composée de plusieurs fichiers/modules, etc.
```

2024-06-28 09:32 UTC, GDemay commented on docs/fr/docs/tutorial/tests.md
> +disons que vous ayez une structure de fichier comme décrit dans [application de grande taille (en)](./bigger-applications.md) {.internal-link target=_blank}:
```suggestion
Disons que vous ayez une structure de fichier comme décrit dans [application de grande taille (en)](./bigger-applications.md) {.internal-link target=_blank}:
```

2024-06-28 09:32 UTC, GDemay commented on docs/fr/docs/tutorial/tests.md
> +### fichier app de **FastAPI**
```suggestion
### Fchier app de **FastAPI**
```

2024-06-28 09:32 UTC, GDemay commented on docs/fr/docs/tutorial/tests.md
> +dans le fichier `main.py` vous avez votre application **FastAPI** :
```suggestion
Le fichier `main.py` vous permet d'accéder à votre application **FastAPI** :
```

2024-06-28 09:32 UTC, GDemay commented on docs/fr/docs/tutorial/tests.md
> +### fichier de test
```suggestion
### Fichier de test
```

2024-06-28 09:32 UTC, GDemay commented on docs/fr/docs/tutorial/tests.md
> +Allons plus loin dans cet exemple et ajoutons plus de détails pour voir comment tester différentes pièces.
```suggestion
Pour aller plus loin dans cet exemple, ajoutons plus de détails pour observer comment tester différentes pièces.
```

2024-06-28 09:32 UTC, GDemay commented on docs/fr/docs/tutorial/tests.md
> +### fichier app étendu de **FastAPI**
```suggestion
### Fichier App étendu de **FastAPI**
```

2024-06-28 09:32 UTC, GDemay commented on docs/fr/docs/tutorial/tests.md
> +Supposons que maintenant le fichier `main.py` avec votre application **FastAPI** a d’autres **opérations sur chemin d'accès**.
```suggestion
Supposons que maintenant le fichier `main.py` avec votre application **FastAPI** à d’autres **opérations sur chemin d'accès**.
```

2024-06-28 09:32 UTC, GDemay commented on docs/fr/docs/tutorial/tests.md
> +Et dispose d’une opération `POST` qui peut renvoyer plusieurs erreurs.
```suggestion
Il  dispose d’une opération `POST` qui peut renvoyer plusieurs erreurs.
```

2024-06-28 09:32 UTC, GDemay commented on docs/fr/docs/tutorial/tests.md
> +### fichier de test étendu
```suggestion
### Fichier de test étendu
```

2024-06-28 09:32 UTC, GDemay commented on docs/fr/docs/tutorial/tests.md
> +    à otez que le `TestClient` reçoit des données qui peuvent être converties en JSON, et non en modèles Pydantic.
```suggestion
    à noter que le `TestClient` reçoit des données qui peuvent être converties en JSON, et non en modèles Pydantic.
```

2024-06-28 09:32 UTC, GDemay commented on docs/fr/docs/tutorial/tests.md
> +Cela détectera automatiquement les fichiers et les tests, les exécutera et vous rapportera les résultats.
```suggestion
Cela détectera automatiquement les fichiers et les tests, les exécutera, puis vous rapportera les résultats.
```

2024-06-28 09:37 UTC, GDemay commented
Why does the smokeshow / coverage at 99% ? Can we start a new build? @Mgcsuper

2024-09-19 22:18 UTC, closed without merging