🌐 Add Chinese translation for docs/zh/docs/how-to/index.md and docs/zh/docs/how-to/general.md
fastapi/fastapi pull request #11443
Opened 2024-04-16 02:41 UTC by billzhong

2024-04-16 02:49 UTC, tiangolo commented
📝 Docs preview for commit 191022f52f482f28a80d89044acd5200a22ed7d9 at: https://21640f9f.fastapitiangolo.pages.dev

2024-04-16 03:02 UTC, tiangolo commented
📝 Docs preview for commit 528a5a9196c83e5ffe73bb974aa22f7bd1a67349 at: https://e60448e3.fastapitiangolo.pages.dev

2024-04-18 22:48 UTC, tiangolo commented
📝 Docs preview for commit 8b81a4988acf9a9177fcd7068dae9767111279b2 at: https://ac4f2875.fastapitiangolo.pages.dev

2024-04-19 01:58 UTC, waketzheng commented
原文为`How To - Recipes`
翻译成了`如何操作 - 食谱`
感觉怪怪的，Recipes译成`秘诀`或`诀窍`，是不是更贴切？

2024-04-19 02:18 UTC, tiangolo commented
📝 Docs preview for commit 924c56ff8ff202f885d5576c682c6c02b7ef1be7 at: https://c32fbe0a.fastapitiangolo.pages.dev

2024-04-20 05:16 UTC, nick-cjyx9 requested changes

2024-04-20 05:16 UTC, nick-cjyx9 commented on docs/zh/docs/how-to/general.md
> +这里是指向文档中其他部分的一些链接，用于解答一般性或常见问题。
应改为：
一些指向文档中其他部分的链接

ref: [多层定语顺序](https://baike.baidu.com/item/%E5%A4%9A%E5%B1%82%E5%AE%9A%E8%AF%AD%E9%A1%BA%E5%BA%8F/4483121)

2024-04-20 05:16 UTC, nick-cjyx9 commented on docs/zh/docs/how-to/general.md
> +在文档界面中添加*路径操作*的标签和进行分组，请阅读 [教程 - 路径操作配置 - Tags 参数](../tutorial/path-operation-configuration.md#tags){.internal-link target=_blank} 文档。
中文文本中通常不使用斜体，该用加粗

ref: [簡單做好中文排版](https://wanderer.tw/簡單做好中文排版/)第五项原则

2024-04-20 05:16 UTC, nick-cjyx9 commented on docs/zh/docs/how-to/general.md
> +在文档界面中添加*路径操作*的标签和进行分组，请阅读 [教程 - 路径操作配置 - Tags 参数](../tutorial/path-operation-configuration.md#tags){.internal-link target=_blank} 文档。
15, 21, 23行同

2024-04-20 23:41 UTC, nick-cjyx9 approved these changes

2024-04-20 23:45 UTC, tiangolo commented
📝 Docs preview for commit a5c774e105487e4014f995e787d7577e5da68b9f at: https://c3c132c6.fastapitiangolo.pages.dev

2024-04-21 00:07 UTC, nick-cjyx9 commented
@waketzheng Do you have time to review these changes?

2024-04-21 07:32 UTC, waketzheng approved these changes

2024-04-22 23:41 UTC, merged

2024-04-22 23:41 UTC, alejsdev commented
Thanks for the contribution! @billzhong  :nerd_face: 

And thanks for the reviews @waketzheng @nick-cjyx9 :smile_cat: :rocket: