🌐 Add Traditional Chinese translation for docs\zh-hant\benchmarks.md
fastapi/fastapi pull request #11484
Opened 2024-04-24 15:13 UTC by KNChiu

Add Traditional Chinese translation for docs\zh-hant\benchmarks.md

2024-04-25 06:30 UTC, mattwang44 reviewed
檔案位置好像放錯囉，應該要是 docs/zh-hant/docs/benchmarks.md
發 PR 記得 local build 或看看 [preview](https://5ef953b6.fastapitiangolo.pages.dev/zh-hant/benchmarks/) 是否如預期

2024-04-25 06:45 UTC, mattwang44 commented on docs/zh-hant/benchmarks.md
> +        * **FastAPI**：（使用 Starlette）（使用 Starlette）一個 API 微框架，具有用於建立 API 的多個附加功能、資料驗證等。
```suggestion
        * **FastAPI**：（使用 Starlette）一個 API 微框架，具有用於建立 API 的多個附加功能、資料驗證等。
```

2024-04-25 06:45 UTC, mattwang44 commented on docs/zh-hant/benchmarks.md
> +    * 如果您要與FastAPI比較，請將其與能夠提供資料驗證、序列化和文件的Web 應用程式框架（或工具集）進行比較，例如Flask-apispec、NestJS、Molten 等框架。
- [中英文之間需要增加空格](https://github.com/sparanoid/chinese-copywriting-guidelines#%E4%B8%AD%E8%8B%B1%E6%96%87%E4%B9%8B%E9%96%93%E9%9C%80%E8%A6%81%E5%A2%9E%E5%8A%A0%E7%A9%BA%E6%A0%BC)
- 前面 "Web" 有翻譯，這邊是否也要翻譯？
```suggestion
    * 如果您要與 FastAPI 比較，請將其與能夠提供資料驗證、序列化和文件的 Web 應用程式框架（或工具集）進行比較，例如 Flask-apispec、NestJS、Molten 等框架。
```

2024-04-25 06:45 UTC, mattwang44 commented on docs/zh-hant/benchmarks.md
> +由第三方機構 TechEmpower 的基準測試表明在 Uvicorn 下運行的 **FastAPI** 應用程式是 <a href="https://www.techempower.com/benchmarks/#section=test&runid=7464e520-0dc2-473d-bd34-dbdfd7e85911&hw=ph&test=query&l=zijzen-7" class=
中文部分應使用全形括號

```suggestion
由第三方機構 TechEmpower 的基準測試表明在 Uvicorn 下運行的 **FastAPI** 應用程式是 <a href="https://www.techempower.com/benchmarks/#section=test&runid=7464e520-0dc2-473d-bd34-dbdfd7e85911&hw=ph&test=query&l=zijzen-7" class="external-link" target="_blank">最快的 Python 可用框架之一</a>，僅次於 Starlette 和 Uvicorn 本身（於 FastAPI 內部使用）。
```

2024-04-25 06:45 UTC, mattwang44 commented on docs/zh-hant/benchmarks.md
> +具體來說，是將 Uvicorn，Starlette 和 FastAPI 同時進行比較（以及許多其他工具）。
```suggestion
具體來說，是將 Uvicorn、Starlette 和 FastAPI 同時進行比較（以及許多其他工具）。
```

2024-04-25 06:45 UTC, mattwang44 commented on docs/zh-hant/benchmarks.md
> +    * 您不會直接在 Uvicorn 中編寫應用程式。這意味著您的程式碼必須或多或少地包含 Starlette（或 **FastAPI**）提供的所有程式碼。如果您這樣做，您的最終應用程式將具有與使用框架相同的開銷並最大限度地減少應用程式程式碼和錯誤。
過去我們曾討論過希望官方文件都避免使用「您」([ref](https://github.com/tiangolo/fastapi/pull/11142#discussion_r1490293784))

2024-04-25 06:45 UTC, mattwang44 commented on docs/zh-hant/benchmarks.md
> +    * 繼 Uvicorn 之後的次一個最佳表現。事實上，Starlette 使用 Uvicorn 來運行。因此它將可能只透過執行更多程式碼而變得比 Uvicorn「慢」。
```suggestion
    * 繼 Uvicorn 之後的次佳表現。事實上，Starlette 使用 Uvicorn 來運行。因此它將可能只透過執行更多程式碼而變得比 Uvicorn「慢」。
```

2024-04-25 06:45 UTC, mattwang44 commented on docs/zh-hant/benchmarks.md
> +    * 但它為您提供了建立簡單 Web 應用程式的工具，以及基於路徑的路由等。
- 前面 "Web" 有翻譯，這邊是否也要翻譯？

2024-04-25 06:45 UTC, mattwang44 commented on docs/zh-hant/benchmarks.md
> +    * FastAPI 在 Starlette 基礎之上提供了更多功能。包含建構 API 時所需要的功能，例如資料驗證和序列化。FastAPI 可以幫助您自動產生 API文檔，（應用程式啟動時將會自動生成文件，所以不會增加應用程式運行時的開銷）。
```suggestion
    * FastAPI 在 Starlette 基礎之上提供了更多功能。包含建構 API 時所需要的功能，例如資料驗證和序列化。FastAPI 可以幫助您自動產生 API 文件，（應用程式啟動時將會自動生成文件，所以不會增加應用程式運行時的開銷）。
```

2024-04-25 07:27 UTC, KNChiu commented on docs/zh-hant/benchmarks.md
> +        * **FastAPI**：（使用 Starlette）（使用 Starlette）一個 API 微框架，具有用於建立 API 的多個附加功能、資料驗證等。
抱歉不小心重複數輸入XD

2024-04-25 07:30 UTC, KNChiu commented on docs/zh-hant/benchmarks.md
> +    * 如果您要與FastAPI比較，請將其與能夠提供資料驗證、序列化和文件的Web 應用程式框架（或工具集）進行比較，例如Flask-apispec、NestJS、Molten 等框架。
"Web" 統一翻譯成「網頁」好了

2024-04-25 07:38 UTC, tiangolo commented
📝 Docs preview for commit 7a89998a37a9731cb801c24d625d251115c466a0 at: https://bdf4be30.fastapitiangolo.pages.dev

2024-04-25 07:43 UTC, KNChiu commented on docs/zh-hant/benchmarks.md
> +    * 但它為您提供了建立簡單 Web 應用程式的工具，以及基於路徑的路由等。
將"Web" 統一翻譯成「網頁」好了
感謝

2024-04-25 07:54 UTC, tiangolo commented
📝 Docs preview for commit 005ecc35d6eb3526e72d0225050d1f975ed69dfa at: https://60367e93.fastapitiangolo.pages.dev

2024-04-25 08:07 UTC, mattwang44 reviewed
thx 只剩[檔案位置問題](https://github.com/tiangolo/fastapi/pull/11484#pullrequestreview-2021631973)

2024-04-25 08:56 UTC, tiangolo commented
📝 Docs preview for commit 50b29ac05fa95ea8862e36579e6025f4b3812a6f at: https://d3fde60c.fastapitiangolo.pages.dev

2024-04-25 08:57 UTC, mattwang44 approved these changes
preview is [here](https://d3fde60c.fastapitiangolo.pages.dev/zh-hant/benchmarks/)
LGTM

2024-04-25 14:24 UTC, hsuanchi requested changes

2024-04-25 14:24 UTC, hsuanchi commented on docs/zh-hant/docs/benchmarks.md
> +* **Uvicorn**:
冒號以全形為主

2024-04-25 14:24 UTC, hsuanchi commented on docs/zh-hant/docs/benchmarks.md
> +    * 因此透過使用 FastAPI，你可以節省開發時間、錯誤與程式碼數量，並且相比不使用 FastAPI 你很大可能會獲得相同或更好的性能（因為那樣你必須在程式碼中實現所有相同的功能）。
Performance 翻譯為"效能"較佳 [ref](https://zh.wikibooks.org/zh/%E5%A4%A7%E9%99%86%E5%8F%B0%E6%B9%BE%E8%AE%A1%E7%AE%97%E6%9C%BA%E6%9C%AF%E8%AF%AD%E5%AF%B9%E7%85%A7%E8%A1%A8)

2024-04-26 00:14 UTC, KNChiu commented on docs/zh-hant/docs/benchmarks.md
> +* **Uvicorn**:
感謝提醒已經修改了歐~

2024-04-26 00:16 UTC, KNChiu commented on docs/zh-hant/docs/benchmarks.md
> +    * 因此透過使用 FastAPI，你可以節省開發時間、錯誤與程式碼數量，並且相比不使用 FastAPI 你很大可能會獲得相同或更好的性能（因為那樣你必須在程式碼中實現所有相同的功能）。
已經整份文件中譯成「性能」替換成「效能」。

2024-04-26 00:19 UTC, tiangolo commented
📝 Docs preview for commit 3d096d7342762d810e9c9c9591cc1f640341c521 at: https://1f1d7ef2.fastapitiangolo.pages.dev

2024-04-26 02:34 UTC, hsuanchi commented on docs/zh-hant/docs/benchmarks.md
> +* **Uvicorn**:
還有下方的 Starlette: 和 FastAPI:～

2024-04-26 02:36 UTC, KNChiu commented on docs/zh-hant/docs/benchmarks.md
> +* **Uvicorn**:
啊啊不好意思!
馬上修改~

2024-04-26 02:45 UTC, tiangolo commented
📝 Docs preview for commit 7dafcaeaafaed11a9b078b179bdc557e4f53c5ec at: https://7d91e118.fastapitiangolo.pages.dev

2024-04-26 09:16 UTC, hsuanchi commented
preview is [here](https://7d91e118.fastapitiangolo.pages.dev/zh-hant/benchmarks/)
LGTM 🚀

2024-04-26 09:16 UTC, hsuanchi approved these changes

2024-04-27 14:30 UTC, merged

2024-04-27 14:31 UTC, alejsdev commented
Thanks for the contribution! @KNChiu :rocket: :sparkles: 

And thanks for the reviews @hsuanchi @mattwang44 :nerd_face: