Update the index.md file in the documents folder, because the translation is outdated
fastapi/fastapi pull request #11547
Opened 2024-05-07 14:51 UTC by dei8bit

EN: The Spanish translation have a gap with the documentation in English, regarding some new implementations that are considered pertinent to include as soon as possible. ☺

ES: La traducción en español tenia un desfasaje con la documentación en ingles , respecto a algunas implementaciones nuevas que se estiman pertinentes de incluir cuanto antes. ☺

2024-05-07 14:58 UTC, tiangolo commented
📝 Docs preview for commit 43aee89f174b393f8b3665a410ad272760cab6d9 at: https://e0a9ae14.fastapitiangolo.pages.dev

2024-05-07 15:56 UTC, JavierSanchezCastro commented on docs/es/docs/index.md
> +Por defecto,  `fastapi dev` empezara con auto-reload activado para desarrollo local.
*empezará

2024-05-07 15:56 UTC, JavierSanchezCastro commented on docs/es/docs/index.md
> +Puedes leer mas acerca de eso en <a href="https://fastapi.tiangolo.com/fastapi-cli/" target="_blank">FastAPI CLI docs</a>.
*más

2024-05-07 15:56 UTC, JavierSanchezCastro commented on docs/es/docs/index.md
> +El servidor `fastapi dev` se actualizara automaticamente
*actualizará

*automáticamente

2024-05-07 15:56 UTC, JavierSanchezCastro commented on docs/es/docs/index.md
> +* * `fastapi-cli` - para proveer el comando `fastapi`.
Borrar un *

2024-05-07 15:56 UTC, JavierSanchezCastro commented on docs/es/docs/index.md
> +Cuando instalas `fastapi` este viene con estas librerias por defecto
Punto final

*Librerías

2024-05-07 15:56 UTC, JavierSanchezCastro commented on docs/es/docs/index.md
> +Si no deseas las librerias que vienen por defecto, puede optar por instalar `fastapi-slim`.
*Librerías

2024-05-07 15:56 UTC, JavierSanchezCastro commented on docs/es/docs/index.md
> +Cuando haces la instalacion con el comando:
*Instalación

2024-05-07 15:56 UTC, JavierSanchezCastro commented on docs/es/docs/index.md
> +...esto incluye el mismo codigo y dependencias que:
*código

2024-05-07 15:56 UTC, JavierSanchezCastro commented on docs/es/docs/index.md
> +Las dependencias por deefcto son las mencionadas arriba previamente
*Defecto

Punto final

2024-05-07 15:56 UTC, JavierSanchezCastro commented on docs/es/docs/index.md
> +* Integracion de **GraphQL**  con <a href="https://strawberry.rocks" class="external-link" target="_blank">Strawberry</a> y otras librerias.
*Librerías

2024-05-07 15:56 UTC, JavierSanchezCastro commented on docs/es/docs/index.md
> +El comando `fastapi dev` lee tu archivo `main.py` , detecta  la aplicacion **FastAPI** en él, y comienza un servidor usando <a href="https://www.uvicorn.org" class="external-link" target="_blank">Uvi
"lanza" en vez de "comienza" puede quedar mejor?

2024-05-08 16:33 UTC, dei8bit reviewed
accents , and more corrections added

2024-05-08 16:33 UTC, dei8bit commented
Thanks for the cooperation ♥

2024-05-08 16:45 UTC, tiangolo commented
📝 Docs preview for commit 79a2de2617cd4aa8d3eaf5052e40cb93407d5a0f at: https://f7a5bc81.fastapitiangolo.pages.dev

2024-05-08 17:15 UTC, JavierSanchezCastro requested changes
Cambiar algunas mayúsculas por minúsculas y una tilde en "empezará"

2024-05-08 17:15 UTC, JavierSanchezCastro commented on docs/es/docs/index.md
> +Por defecto,  `fastapi dev` empezara con auto-reload activado para desarrollo local.
Aquí me refiero a: "Por defecto, `fastapi dev` empezará..."

2024-05-08 17:15 UTC, JavierSanchezCastro commented on docs/es/docs/index.md
> +* Integracion de **GraphQL**  con <a href="https://strawberry.rocks" class="external-link" target="_blank">Strawberry</a> y otras Librerías.
Mayus en Librerías?

2024-05-08 17:15 UTC, JavierSanchezCastro commented on docs/es/docs/index.md
> +Cuando instalas `fastapi` este viene con estas Librerías por defecto.
Mayus?

2024-05-08 17:15 UTC, JavierSanchezCastro commented on docs/es/docs/index.md
> +Si no deseas las Librerías que vienen por defecto, puede optar por instalar `fastapi-slim`.
Mayus igual aquí?

2024-05-08 17:15 UTC, JavierSanchezCastro commented on docs/es/docs/index.md
> +Cuando haces la Instalación con el comando:
Mayus?

2024-05-27 04:21 UTC, jaimescose commented on docs/es/docs/index.md
> +Si no deseas las Librerías que vienen por defecto, puede optar por instalar `fastapi-slim`.
```suggestion
Si no deseas las Librerías que vienen por defecto, puedes optar por instalar `fastapi-slim`.
```

2024-05-27 04:21 UTC, jaimescose commented on docs/es/docs/index.md
> +Las dependencias por defecto son las mencionadas arriba previamente.
Sería mejor dejar sin traducir el `standard` pues hace referencia a las dependencias?
```suggestion
Las dependencias extra `standard` son las mencionadas anteriormente.
```

2024-05-27 17:10 UTC, tiangolo commented
📝 Docs preview for commit 2d41a576bf22e4186b27182e225ddf0601b04620 at: https://5c82f9ee.fastapitiangolo.pages.dev

2024-05-29 23:05 UTC, tiangolo commented
📝 Docs preview for commit 264416d15f24cdcb809656adecbd6307baa240a2 at: https://05199720.fastapitiangolo.pages.dev

2024-06-03 14:33 UTC, JavierSanchezCastro requested changes

2024-06-03 14:33 UTC, JavierSanchezCastro commented on docs/es/docs/index.md
> +Por defecto,  `fastapi dev` empezara con auto-reload activado para desarrollo local.
*empezará

2024-06-03 14:33 UTC, JavierSanchezCastro commented on docs/es/docs/index.md
> +Cuando instalas `fastapi` este viene con estas Librerías por defecto.
*librerías

2024-06-03 14:33 UTC, JavierSanchezCastro commented on docs/es/docs/index.md
> +Si no deseas las Librerías que vienen por defecto, puede optar por instalar `fastapi-slim`.
*librerías

2024-06-03 14:33 UTC, JavierSanchezCastro commented on docs/es/docs/index.md
> +Cuando haces la Instalación con el comando:
*instalación

2024-06-03 14:33 UTC, JavierSanchezCastro commented on docs/es/docs/index.md
> +* Integracion de **GraphQL**  con <a href="https://strawberry.rocks" class="external-link" target="_blank">Strawberry</a> y otras Librerías.
*librerías

2024-06-28 07:47 UTC, closed without merging