📝 Update JWT auth documentation to use PyJWT instead of pyhon-jose
fastapi/fastapi pull request #11589
Opened 2024-05-16 23:50 UTC by estebanx64

2024-05-16 23:54 UTC, tiangolo commented
📝 Docs preview for commit 5a6859263bdb4db1386b244fd7fe5710d0379223 at: https://604f2b88.fastapitiangolo.pages.dev

2024-05-17 05:09 UTC, tiangolo commented
📝 Docs preview for commit f252dc622d44c8f8ad18a569fd0ca8b14e919fc4 at: https://d2e11754.fastapitiangolo.pages.dev

2024-05-17 05:29 UTC, tiangolo commented
📝 Docs preview for commit 6734f798a7e37665d0cdca135dfcc7391847e7eb at: https://ac0fd867.fastapitiangolo.pages.dev

2024-05-17 05:30 UTC, tiangolo commented
📝 Docs preview for commit 6734f798a7e37665d0cdca135dfcc7391847e7eb at: https://0c8011f7.fastapitiangolo.pages.dev

2024-05-18 13:08 UTC, YuriiMotov requested changes
Everything is perfect except one small mistake with code line highlighting.

2024-05-18 22:55 UTC, yezz123 approved these changes
As @YuriiMotov mentioned, everything is amazing, especially with the non-maintenance of python-jose. Therefore, pyjwt is the best alternative.

LGTM 🚀

2024-05-19 22:37 UTC, estebanx64 commented on docs/en/docs/advanced/security/oauth2-scopes.md
> +    ```Python hl_lines="105  108-116"
You are right, thanks!

2024-05-19 22:42 UTC, tiangolo commented
📝 Docs preview for commit 875c02576d84166f4d58dd17f99d455ea831512b at: https://83636c12.fastapitiangolo.pages.dev

2024-05-20 06:18 UTC, YuriiMotov approved these changes
Everything is good!
I paid special attention to highlighting the lines of code in all code blocks.
I also checked that all the necessary documentation pages have been corrected.

2024-05-20 17:37 UTC, merged