🌐 Update Chinese translation for docs/zh/docs/reference/*
fastapi/fastapi pull request #11597
Opened 2024-05-18 10:12 UTC by binaryYuki

2024-05-18 10:15 UTC, tiangolo commented
📝 Docs preview for commit a4f72942bddda8e7ec33711bf2bd4a5ad7afbd6d at: https://ea5d6a24.fastapitiangolo.pages.dev

2024-05-18 11:34 UTC, tiangolo commented
📝 Docs preview for commit 25e586c3bf0ffb7fab44f8aa5a5b727cf00a00d5 at: https://1eab456e.fastapitiangolo.pages.dev

2024-05-19 00:05 UTC, nick-cjyx9 requested changes

2024-05-19 00:05 UTC, nick-cjyx9 commented on docs/zh/docs/reference/index.md
> +[FastAPI Tutorial](https://fastapi.tiangolo.com/tutorial/).
fix: https://fastapi.tiangolo.com/zh/

2024-05-19 00:05 UTC, nick-cjyx9 commented on docs/zh/docs/reference/middleware.md
> +请参阅 [FastAPI docs for Middleware](https://fastapi.tiangolo.com/advanced/middleware/).
https://fastapi.tiangolo.com/zh/advanced/middleware/

2024-05-19 00:05 UTC, nick-cjyx9 commented on docs/zh/docs/reference/responses.md
> +请参阅 [FastAPI docs for Custom Response - HTML, Stream, File, others](https://fastapi.tiangolo.com/advanced/custom-response/).
https://fastapi.tiangolo.com/zh/advanced/custom-response/

2024-05-19 00:05 UTC, nick-cjyx9 commented on docs/zh/docs/reference/staticfiles.md
> +请参阅 [FastAPI docs for Static Files](https://fastapi.tiangolo.com/tutorial/static-files/).
以下链接问题均同上

2024-05-19 12:40 UTC, binaryYuki commented on docs/zh/docs/reference/staticfiles.md
> +请参阅 [FastAPI docs for Static Files](https://fastapi.tiangolo.com/tutorial/static-files/).
已修改

2024-05-19 12:40 UTC, binaryYuki commented on docs/zh/docs/reference/staticfiles.md
> +请参阅 [FastAPI docs for Static Files](https://fastapi.tiangolo.com/tutorial/static-files/).
> 以下链接问题均同上

已修改

2024-05-19 12:43 UTC, tiangolo commented
📝 Docs preview for commit 43d3386b73b0f04f5da04567a4bfff22055002d1 at: https://b1b2ab39.fastapitiangolo.pages.dev

2024-05-19 15:48 UTC, tiangolo commented
📝 Docs preview for commit e1d39be0e522a8ed5174afc45fc3fe347ab93ab8 at: https://a73f9e1a.fastapitiangolo.pages.dev

2024-05-19 15:53 UTC, tiangolo commented
📝 Docs preview for commit 3a9f7ae929f79ff2ee835bfff86b10aa795bfee9 at: https://0d2fec8d.fastapitiangolo.pages.dev

2024-05-19 15:59 UTC, closed without merging