🌐 Add Turkish translation for `docs/tr/docs/advanced/index.md`
fastapi/fastapi pull request #11606
Opened 2024-05-20 16:22 UTC by hasansezertasan

🌐 Add Turkish translation for `docs/tr/docs/advanced/index.md`

[Original File](https://github.com/tiangolo/fastapi/blob/master/docs/en/docs/advanced/index.md)

Discussion: #9193

2024-05-20 16:27 UTC, tiangolo commented
📝 Docs preview for commit ac8d5dd0519b629cf8559c4d4e6512cc7a5cf6b2 at: https://0e5ebbfc.fastapitiangolo.pages.dev

2024-05-20 20:02 UTC, tiangolo commented
📝 Docs preview for commit 8bd4dd11d2916a50e3b309d7ef484081332b2f1f at: https://524782fe.fastapitiangolo.pages.dev

2024-05-25 01:16 UTC, tiangolo commented
📝 Docs preview for commit 031a1f26972e5ecea0deceb8c0f5dc0ebc7dc4b5 at: https://457c05c3.fastapitiangolo.pages.dev

2024-05-26 18:11 UTC, OzgunCaglarArslan requested changes

2024-06-01 19:13 UTC, tiangolo commented
📝 Docs preview for commit d4972d532e686c6855b8ac37a0f54738d67f11ef at: https://9a158ca2.fastapitiangolo.pages.dev

2024-06-01 19:19 UTC, tiangolo commented
📝 Docs preview for commit 33d29056b1e07fabc7fcdfab5d398f79f2bfcc72 at: https://b5c5b06a.fastapitiangolo.pages.dev

2024-06-01 19:31 UTC, tiangolo commented
📝 Docs preview for commit b48d429dcb0538dd8a36bb3f175997de4d142316 at: https://1b73cdb9.fastapitiangolo.pages.dev

2024-06-02 10:30 UTC, OzgunCaglarArslan requested changes

2024-06-02 10:30 UTC, OzgunCaglarArslan commented on docs/tr/docs/advanced/index.md
> +!!! tip "İpucu"
```suggestion
!!! İpucu
```

2024-06-02 10:30 UTC, OzgunCaglarArslan commented on docs/tr/docs/advanced/index.md
> +[Tutorial - User Guide](../tutorial/index.md){.internal-link target=_blank} sayfasının ve bu **Gelişmiş Kullanıcı Rehberi**'nin öğretici olmak amacıyla (bir kitap gibi) yazılmış olmasına ve **FastAPI
```suggestion
[Tutorial - User Guide](../tutorial/index.md){.internal-link target=_blank} sayfası ve bu **Gelişmiş Kullanıcı Rehberi**, öğretici bir kılavuz (bir kitap gibi) şeklinde yazılmıştır ve **FastAPI'ı öğrenmek** için yeterli olsa da, ek kurslarla desteklemek isteyebilirsiniz.
```

2024-06-02 16:00 UTC, hasansezertasan commented on docs/tr/docs/advanced/index.md
> +!!! tip "İpucu"
Admonition notasyonu bu şekildedir, önerini uygularsak admonition bozulur.

2024-06-02 16:05 UTC, tiangolo commented
📝 Docs preview for commit 87441468f3288bb871975edc478b8deaf2aa4618 at: https://223123a5.fastapitiangolo.pages.dev

2024-06-02 16:22 UTC, OzgunCaglarArslan approved these changes

2024-06-05 00:05 UTC, merged

2024-06-05 00:06 UTC, alejsdev commented
Thank you! @hasansezertasan @OzgunCaglarArslan :partying_face: