🌐 Add Turkish translation for `docs/tr/docs/advanced/response-cookies.md`
fastapi/fastapi pull request #11614
Opened 2024-05-20 21:33 UTC by hasansezertasan

🌐 Add Turkish translation for `docs/tr/docs/advanced/response-cookies.md`

[Original File](https://github.com/tiangolo/fastapi/blob/master/docs/en/docs/advanced/response-cookies.md)

Discussion: #9193

2024-05-20 21:36 UTC, tiangolo commented
📝 Docs preview for commit cbe439aa1a71e7a4ccefcd511142c79c8cd9b328 at: https://4b0f8f6f.fastapitiangolo.pages.dev

2024-05-25 01:16 UTC, tiangolo commented
📝 Docs preview for commit a0fef35bbdab585eecb88507a2b67cddb4a6c57c at: https://e3b36904.fastapitiangolo.pages.dev

2024-06-01 19:31 UTC, tiangolo commented
📝 Docs preview for commit 5141cb3d29f7b5f90e8977736db059c61c064966 at: https://10bcd377.fastapitiangolo.pages.dev

2025-06-16 08:14 UTC, YuriiMotov commented on docs/tr/docs/advanced/response-cookies.md
> +```
```suggestion
{* ../../docs_src/response_cookies/tutorial002.py hl[1, 8:9] *}
```

2025-06-16 08:14 UTC, YuriiMotov commented on docs/tr/docs/advanced/response-cookies.md
> +```
```suggestion
{* ../../docs_src/response_cookies/tutorial001.py hl[10:12] *}
```

2025-06-16 08:14 UTC, YuriiMotov commented on docs/tr/docs/advanced/response-cookies.md
> +!!! tip "İpucu"
```suggestion
/// tip | İpucu
```

2025-06-16 08:14 UTC, YuriiMotov commented on docs/tr/docs/advanced/response-cookies.md
> +
```suggestion
///

```

2025-06-19 10:30 UTC, Rekl0w requested changes

2025-06-19 10:30 UTC, Rekl0w commented on docs/tr/docs/advanced/response-cookies.md
> +Bağımlılıklarda da `Response` parametresini belirtebilir ve çezerlezi belirleyebilirsiniz.
```suggestion
Bağımlılıklarda da `Response` parametresini belirtebilir ve çerezleri belirleyebilirsiniz.
```

2025-06-19 10:30 UTC, Rekl0w commented on docs/tr/docs/advanced/response-cookies.md
> +**FastAPI** bu *geçici* yanıtı çerezleri (ayrıca durum kodunu ve başlıkları) çıkarmak için kullanacak ve döndürdüğünüz değeri herhangi bir `response_model` tarafından filtreleyerek son yanıta koyacak
```suggestion
**FastAPI** bu *geçici* yanıtı çerezleri (ayrıca durum kodunu ve başlıkları) almak için kullanacak ve döndürdüğünüz değeri herhangi bir `response_model` tarafından filtreleyerek son yanıta koyacaktır.
```

2025-09-05 09:04 UTC, YuriiMotov commented
As part of our recent decision to move to an automated translation process 🤖, we’re no longer accepting community-submitted translation PRs.

I’ll go ahead and close this PR. You can read more details in the announcement here: [https://fastapi.tiangolo.com/contributing/#translations](https://fastapi.tiangolo.com/contributing/?utm_source=chatgpt.com#translations)

Thank you very much for your time and efforts 🙏

2025-09-05 09:04 UTC, closed without merging