🌐 Add Turkish translation for `docs/tr/docs/advanced/additional-status-codes.md`
fastapi/fastapi pull request #11613
Opened 2024-05-20 21:11 UTC by hasansezertasan

🌐 Add Turkish translation for `docs/tr/docs/advanced/additional-status-codes.md`

[Original File](https://github.com/tiangolo/fastapi/blob/master/docs/en/docs/advanced/additional-status-codes.md)

Discussion: #9193

2024-05-20 21:16 UTC, tiangolo commented
📝 Docs preview for commit a6fd201d3734fb72a8eee0872fcdb746b80be584 at: https://7b43fa37.fastapitiangolo.pages.dev

2024-05-25 01:12 UTC, tiangolo commented
📝 Docs preview for commit e26657871dbc3ce9879bac1d650599d3093ec998 at: https://021549db.fastapitiangolo.pages.dev

2024-06-01 19:28 UTC, tiangolo commented
📝 Docs preview for commit 1b5e7d831f1da466fc416598e53031f19e861dc9 at: https://9dfb6e86.fastapitiangolo.pages.dev

2025-06-16 08:41 UTC, YuriiMotov commented on docs/tr/docs/advanced/additional-status-codes.md
> +    ```
```suggestion
{* ../../docs_src/additional_status_codes/tutorial001_an_py310.py hl[4,25] *}
```

2025-06-16 08:41 UTC, YuriiMotov commented on docs/tr/docs/advanced/additional-status-codes.md
> +    **FastAPI**, geliştiricilere kolaylık sağlamak amacıyla `starlette.responses`'ı `fastapi.responses` olarak sağlar. Ancak mevcut yanıtların çoğu doğrudan Starlette'den gelir. Aynı durum `status` i
```suggestion
/// warning | Uyarı

Yukarıdaki örnekte olduğu gibi bir `Response` döndürdüğünüzde, doğrudan döndürülecektir.

Bu yanıt herhangi bir modelle dönüştürülme işlemine tabi tutulmayacaktır.

Yanıtın, istediğiniz veriye sahip olduğundan ve (eğer `JSONResponse` kullanıyorsanız) değerlerin geçerli JSON olduğundan emin olun.

///

/// note | Teknik Detaylar

Projenize dahil etmek için `from starlette.responses import JSONResponse` kullanabilirsiniz.

**FastAPI**, geliştiricilere kolaylık sağlamak amacıyla `starlette.responses`'ı `fastapi.responses` olarak sağlar. Ancak mevcut yanıtların çoğu doğrudan Starlette'den gelir. Aynı durum `status` için de geçerlidir.

///
```

2025-06-19 10:30 UTC, Rekl0w requested changes

2025-06-19 10:30 UTC, Rekl0w commented on docs/tr/docs/advanced/additional-status-codes.md
> +Aynı zamanda, yeni öğeler kabul etmek istiyorsunuz ve bu öğereler mevcut değilse öğeleri oluşturmak ve "Oluşturuldu" anlamına gelen 201 HTTP durum kodunu döndürmek istiyorsunuz.
```suggestion
Aynı zamanda, yeni öğeler kabul etmek istiyorsunuz ve bu öğeler mevcut değilse öğeleri oluşturmak ve "Oluşturuldu" anlamına gelen 201 HTTP durum kodunu döndürmek istiyorsunuz.
```

2025-06-19 10:30 UTC, Rekl0w commented on docs/tr/docs/advanced/additional-status-codes.md
> +Yanıtın, istediğiniz veriye sahip olduğundan ve (eğer `JSONResponse` kullanıyorsanız) değerlerin geçerli JSON olduğundan emin olun.
```suggestion
Yanıtın, istediğiniz veriye sahip olduğundan ve (eğer `JSONResponse` kullanıyorsanız) değerlerin geçerli bir JSON formatında olduğundan emin olun.
```

2025-09-05 09:05 UTC, YuriiMotov commented
As part of our recent decision to move to an automated translation process 🤖, we’re no longer accepting community-submitted translation PRs.

I’ll go ahead and close this PR. You can read more details in the announcement here: [https://fastapi.tiangolo.com/contributing/#translations](https://fastapi.tiangolo.com/contributing/?utm_source=chatgpt.com#translations)

Thank you very much for your time and efforts 🙏

2025-09-05 09:05 UTC, closed without merging