🌐 Add Turkish translation for `docs/tr/docs/advanced/response-change-status-code.md`
fastapi/fastapi pull request #11612
Opened 2024-05-20 20:45 UTC by hasansezertasan

🌐 Add Turkish translation for `docs/tr/docs/advanced/response-change-status-code.md`

[Original File](https://github.com/tiangolo/fastapi/blob/master/docs/en/docs/advanced/response-change-status-code.md)

Discussion: #9193

2024-05-20 20:48 UTC, tiangolo commented
📝 Docs preview for commit f64c84ed60e2870e156cc3017455bef4fff6a142 at: https://32eb0eee.fastapitiangolo.pages.dev

2024-05-20 21:21 UTC, tiangolo commented
📝 Docs preview for commit d990f6c4bc42afe882f8e4fabb85fbd6ecd3aa64 at: https://bde4cb7e.fastapitiangolo.pages.dev

2024-05-20 21:25 UTC, hasansezertasan commented on docs/tr/docs/advanced/response-change-status-code.md
> +Bağımlılıklarda da `Response` parametresini belirtebilir ve durum kodunu onlarda belirleyebilirsiniz. Ancak son belirlenen durum kodu kullanılacaktır.
```suggestion
Bağımlılıklarda da `Response` parametresini belirtebilir ve durum kodunu belirleyebilirsiniz. Ancak son belirlenen durum kodu kullanılacaktır.
```

2024-05-20 21:28 UTC, tiangolo commented
📝 Docs preview for commit f46de3c18f404e10d0af53ce8c785646c61990d2 at: https://ffe3e85a.fastapitiangolo.pages.dev

2024-05-25 01:16 UTC, tiangolo commented
📝 Docs preview for commit d35104247f5047bb7914074c835c4f228f9d9ca8 at: https://d8cc7e15.fastapitiangolo.pages.dev

2024-06-01 19:31 UTC, tiangolo commented
📝 Docs preview for commit 9f5b15f4026dee412d697a90d9a87c3fe3a4f413 at: https://86812c4c.fastapitiangolo.pages.dev

2025-06-19 10:30 UTC, Rekl0w requested changes

2025-06-19 10:30 UTC, Rekl0w commented on docs/tr/docs/advanced/response-change-status-code.md
> +Ancak veri mevcut değilse, oluşturmak ve "Oluşturuldu" anlamına gelen `201` HTTP durum kodunu döndürmek istiyorsunuz.
```suggestion
Ancak veri mevcut değilse, onu oluşturmak istiyor ve "Oluşturuldu" anlamına gelen `201` HTTP durum kodunu döndürmek istiyorsunuz.
```

2025-06-19 10:30 UTC, Rekl0w commented on docs/tr/docs/advanced/response-change-status-code.md
> +*yol operasyonu fonksiyonunuzda* `Response` türünde bir parametre belirleyebilirsiniz (çerezler ve headers için yapabileceğiniz gibi).
```suggestion
*yol operasyonu fonksiyonunuzda* `Response` türünde bir parametre belirleyebilirsiniz (çerezler ve başlıklar için yapabileceğiniz gibi).
```

2025-06-19 10:30 UTC, Rekl0w commented on docs/tr/docs/advanced/response-change-status-code.md
> +**FastAPI** bu *geçici* yanıtı durum kodunu (ayrıca çerezleri ve headers'ı) çıkarmak için kullanacak ve döndürdüğünüz değeri herhangi bir `response_model` tarafından filtreleyerek son yanıta koyacakt
```suggestion
**FastAPI** bu *geçici* yanıtı durum kodunu (ayrıca çerezleri ve başlıkları) çıkarmak için kullanacak ve döndürdüğünüz değeri herhangi bir `response_model` tarafından filtreleyerek son yanıta koyacaktır.
```

2025-09-05 09:05 UTC, YuriiMotov commented
As part of our recent decision to move to an automated translation process 🤖, we’re no longer accepting community-submitted translation PRs.

I’ll go ahead and close this PR. You can read more details in the announcement here: [https://fastapi.tiangolo.com/contributing/#translations](https://fastapi.tiangolo.com/contributing/?utm_source=chatgpt.com#translations)

Thank you very much for your time and efforts 🙏

2025-09-05 09:05 UTC, closed without merging