Tr/advanced/response headers.md
fastapi/fastapi pull request #11638
Opened 2024-05-25 01:01 UTC by hasansezertasan

🌐 Add Turkish translation for `docs/tr/docs/advanced/response-headers.md`

[Original File](https://github.com/tiangolo/fastapi/blob/master/docs/en/docs/advanced/response-headers.md)

Discussion: #9193

2024-05-25 01:16 UTC, tiangolo commented
📝 Docs preview for commit a9e2ed56c3bf056a36c60e8c65c6f63af1898d73 at: https://a0e76ef6.fastapitiangolo.pages.dev

2024-06-01 19:31 UTC, tiangolo commented
📝 Docs preview for commit 706e0998b39c8375915f13362f4b51bb903c8725 at: https://5ac6d07d.fastapitiangolo.pages.dev

2025-06-16 07:57 UTC, YuriiMotov commented on docs/tr/docs/advanced/response-headers.md
> +```
```suggestion
{* ../../docs_src/response_headers/tutorial002.py hl[1, 7:8] *}
```

2025-06-16 07:57 UTC, YuriiMotov commented on docs/tr/docs/advanced/response-headers.md
> +```
```suggestion
{* ../../docs_src/response_headers/tutorial001.py hl[10:12] *}
```

2025-06-16 07:57 UTC, YuriiMotov commented on docs/tr/docs/advanced/response-headers.md
> +    `Response` sıklıkla başlıkları ve çerezleri belirlemek için kullanılabileceği için, **FastAPI** ayrıca `fastapi.Response`'ı da sağlar.
```suggestion
/// note | "Teknik Detaylar"
    Projenize dahil etmek için `from starlette.responses import Response` veya `from starlette.responses import JSONResponse` kullanabilirsiniz.

    **FastAPI**, geliştiricilere kolaylık sağlamak amacıyla `starlette.responses`'ı `fastapi.responses` olarak sağlar. Ancak mevcut yanıtların çoğu doğrudan Starlette'den gelir. Aynı durum `status` için de geçerlidir.

    `Response` sıklıkla başlıkları ve çerezleri belirlemek için kullanılabileceği için, **FastAPI** ayrıca `fastapi.Response`'ı da sağlar.

///
```

2025-06-19 10:30 UTC, Rekl0w requested changes

2025-06-19 10:30 UTC, Rekl0w commented on docs/tr/docs/advanced/response-headers.md
> +**FastAPI** bu *geçici* yanıtı başlıkları (ayrıca durum kodunu ve çerezleri) çıkarmak için kullanacak ve döndürdüğünüz değeri herhangi bir `response_model` tarafından filtreleyerek son yanıta koyacak
```suggestion
**FastAPI** bu *geçici* yanıtı başlıkları (ayrıca durum kodunu ve çerezleri) almak için kullanacak ve döndürdüğünüz değeri herhangi bir `response_model` tarafından filtreleyerek son yanıta koyacaktır.
```

2025-09-05 09:04 UTC, YuriiMotov commented
As part of our recent decision to move to an automated translation process 🤖, we’re no longer accepting community-submitted translation PRs.

I’ll go ahead and close this PR. You can read more details in the announcement here: [https://fastapi.tiangolo.com/contributing/#translations](https://fastapi.tiangolo.com/contributing/?utm_source=chatgpt.com#translations)

Thank you very much for your time and efforts 🙏

2025-09-05 09:04 UTC, closed without merging