Update using PyJWT instead of python-jose in Japanese translation
fastapi/fastapi pull request #11696
Opened 2024-06-07 16:27 UTC by utopianf

2024-06-07 16:32 UTC, tiangolo commented
📝 Docs preview for commit f997fa49a41a4f6a8881829967bb1e847a27c806 at: https://f922eca4.fastapitiangolo.pages.dev

2024-08-19 16:29 UTC, svlandeg commented
@utopianf: do you have time to update this PR with the latest from `master`, and resolve the conflicts? 🙏

2024-08-20 07:25 UTC, utopianf commented
@svlandeg Here you are!

2025-02-21 16:02 UTC, k94-ishi requested changes
I have added a translation for the updated part of the original text. I didn’t find any other issues.

2025-03-24 22:18 UTC, closed without merging