🌐 Add Spanish translation for docs/es/docs/how-to/graphql.md
fastapi/fastapi pull request #11697
Opened 2024-06-07 21:33 UTC by camigomezdev

2024-06-07 21:41 UTC, tiangolo commented
📝 Docs preview for commit 50224d0595a9e02348d4f28e31fd7faf1303fd73 at: https://0a3f26fd.fastapitiangolo.pages.dev

2024-06-08 23:03 UTC, ajpinedam commented
@tiangolo This PR came from the GraphQL presentation at PyCon Colombia. It's nice to see someone step up and complete this translation, which will help others. 

Thank you @camigomezdev

2024-06-09 02:05 UTC, alejsdev requested changes
En general LGTM, faltan un par de tildes y corregir un typo. :smile_cat:

2024-06-09 03:12 UTC, ajpinedam commented on docs/es/docs/how-to/graphql.md
> +    Sí tu necesitas GraphQL, aún te recomendaría revisar <a href="https://strawberry.rocks/" class="external-link" target="_blank">Strawberry</a>, que es basada en anotaciones de tipo en vez de clase
Totalmente de acuerdo.

2024-06-09 03:30 UTC, camigomezdev commented on docs/es/docs/how-to/graphql.md
> +    Sí tu necesitas GraphQL, aún te recomendaría revisar <a href="https://strawberry.rocks/" class="external-link" target="_blank">Strawberry</a>, que es basada en anotaciones de tipo en vez de clase
Done 👍🏼

2024-06-09 03:31 UTC, camigomezdev commented on docs/es/docs/how-to/graphql.md
> +Esto fue deprecado de Starlette, pero sí aún tienes código que lo usa, puedes facilmente **migrar** a <a href="https://github.com/ciscorn/starlette-graphene3" class="external-link" target="_blank">st
Done 👍🏼

2024-06-09 03:31 UTC, camigomezdev commented on docs/es/docs/how-to/graphql.md
> +Puedes aprender mas sobre Strawberry en la <a href="https://strawberry.rocks/" class="external-link" target="_blank">documentación de Strawbeery</a>.
Done 👍🏼

2024-06-09 03:31 UTC, camigomezdev commented on docs/es/docs/how-to/graphql.md
> +Dependiendo de tus casos de uso, podrías preferir usar una librería diferente, pero sí tu me preguntas, probablemente te recomendaría **Strawberry**.
Done 👍🏼

2024-06-09 03:31 UTC, camigomezdev commented on docs/es/docs/how-to/graphql.md
> +Sí necesitas o quieres trabajar con **GraphQL**, <a href="https://strawberry.rocks/" class="external-link" target="_blank">**Strawberry**</a> es la librería **recomendada** por el diseño mas cercano
Done 👍🏼

2024-06-09 03:31 UTC, camigomezdev commented on docs/es/docs/how-to/graphql.md
> +    Asegúrate de evaluar sí los **beneficios** para tu caso de uso compensan las **desventajas.**🤓
Done 👍🏼

2024-06-09 03:31 UTC, camigomezdev commented on docs/es/docs/how-to/graphql.md
> +Tu puedes combinar *operaciones regulares de ruta* de la librería de FastAPI con GraphQL en la misma aplicación.
Done 👍🏼

2024-06-09 03:31 UTC, camigomezdev commented on docs/es/docs/how-to/graphql.md
> +Como **FastAPI** esta basado en el estándar **ASGI**, es muy facil integrar cualquier librería **GraphQL** que sea compatible con ASGI.
Done 👍🏼

2024-06-09 03:34 UTC, tiangolo commented
📝 Docs preview for commit 74aa87a7d45261d011a04e70dd2c1cc8ad994762 at: https://c58184f8.fastapitiangolo.pages.dev

2024-06-12 00:24 UTC, alejsdev reviewed
Hola! Es un detalle menor y creo que lo pasé por alto en el review anterior, pero cuando el "si" es condicional no lleva tilde.

Además, normalmente en la documentación se ha dejado la palabra "library" en inglés, ya que la traducción "librería" es incorrecta. No sé si se debería ajustar eso en este caso, ya que la palabra se usa varias veces. Thoughts? @tiangolo :thinking:

2024-06-12 00:24 UTC, alejsdev commented on docs/es/docs/how-to/graphql.md
> +    Asegúrate de evaluar sí los **beneficios** para tu caso de uso compensan las **desventajas.** 🤓
```suggestion
    Asegúrate de evaluar si los **beneficios** para tu caso de uso compensan las **desventajas.** 🤓
```

2024-06-12 00:24 UTC, alejsdev commented on docs/es/docs/how-to/graphql.md
> +Sí necesitas o quieres trabajar con **GraphQL**, <a href="https://strawberry.rocks/" class="external-link" target="_blank">**Strawberry**</a> es la librería **recomendada** por el diseño más cercano
```suggestion
Si necesitas o quieres trabajar con **GraphQL**, <a href="https://strawberry.rocks/" class="external-link" target="_blank">**Strawberry**</a> es la librería **recomendada** por el diseño más cercano a **FastAPI**, el cual es completamente basado en **anotaciones de tipo**.
```

2024-06-12 00:24 UTC, alejsdev commented on docs/es/docs/how-to/graphql.md
> +Dependiendo de tus casos de uso, podrías preferir usar una librería diferente, pero sí me preguntas, probablemente te recomendaría **Strawberry**.
```suggestion
Dependiendo de tus casos de uso, podrías preferir usar una librería diferente, pero si me preguntas, probablemente te recomendaría **Strawberry**.
```

2024-06-12 00:24 UTC, alejsdev commented on docs/es/docs/how-to/graphql.md
> +Esto fue deprecado de Starlette, pero sí aún tienes código que lo usa, puedes fácilmente **migrar** a <a href="https://github.com/ciscorn/starlette-graphene3" class="external-link" target="_blank">st
```suggestion
Esto fue deprecado de Starlette, pero si aún tienes código que lo usa, puedes fácilmente **migrar** a <a href="https://github.com/ciscorn/starlette-graphene3" class="external-link" target="_blank">starlette-graphene3</a>, la cual cubre el mismo caso de uso y tiene una **interfaz casi idéntica.**
```

2024-06-12 00:24 UTC, alejsdev commented on docs/es/docs/how-to/graphql.md
> +    Sí necesitas GraphQL, te recomendaría revisar <a href="https://strawberry.rocks/" class="external-link" target="_blank">Strawberry</a>, que es basada en anotaciones de tipo en vez de clases y tip
```suggestion
    Si necesitas GraphQL, te recomendaría revisar <a href="https://strawberry.rocks/" class="external-link" target="_blank">Strawberry</a>, que es basada en anotaciones de tipo en vez de clases y tipos personalizados.
```

2024-06-12 01:58 UTC, tiangolo commented
> Además, normalmente en la documentación se ha dejado la palabra "library" en inglés, ya que la traducción "librería" es incorrecta. No sé si se debería ajustar eso en este caso, ya que la palabra se usa varias veces. Thoughts? @tiangolo 🤔

Sip, de acuerdo con @alejsdev, tal cual todo 💯 Gracias! 🤓

2024-06-14 21:27 UTC, camigomezdev commented
Quedo atenta si hay mas comentarios :)

2024-06-14 21:27 UTC, tiangolo commented
📝 Docs preview for commit 246b6d0ad145dc5a5efbd2d852a6f94cd39c7843 at: https://a1c69998.fastapitiangolo.pages.dev

2024-07-14 16:18 UTC, alejsdev approved these changes

2024-07-14 16:21 UTC, tiangolo commented
📝 Docs preview for commit 65693b5be77fad2c6e2989f9008f3f670cb3bb25 at: https://cb0d308b.fastapitiangolo.pages.dev

2024-07-14 16:22 UTC, merged

2024-07-14 16:22 UTC, alejsdev commented
Hola! :nerd_face: 
Subí unos pequeños ajustes que había pasado por alto (https://github.com/tiangolo/fastapi/pull/11697/commits/65693b5be77fad2c6e2989f9008f3f670cb3bb25) :sweat_smile:
Gracias a los dos por la ayuda @camigomezdev @ajpinedam :smile_cat: :v: