🌐 Add Spanish translation for `docs/es/docs/fastapi-cli.md`
fastapi/fastapi pull request #11703
Opened 2024-06-09 04:18 UTC by camigomezdev

2024-06-09 04:23 UTC, tiangolo commented
📝 Docs preview for commit 662a30ffc8bbb3bc170a8c5407238ecd0eee41f8 at: https://ad737aed.fastapitiangolo.pages.dev

2024-06-12 00:59 UTC, alejsdev approved these changes

2024-06-12 07:10 UTC, fabianfalon approved these changes

2024-06-12 20:56 UTC, JavierSanchezCastro commented on docs/es/docs/fastapi-cli.md
> +Para correr tu aplicación de FastAPI para desarrollo, puedes usar el comando `fastapi dev`:
Pondría "lanzar" en vez de "correr"

2024-06-12 20:56 UTC, JavierSanchezCastro commented on docs/es/docs/fastapi-cli.md
> +De forma predeterminada, está habilitada la **recarga automática**, por lo que recargará automáticamente el servidor cuando realices cambios en tu código. Esto consume muchos recursos y podría ser me
Aquí pondría "Por defecto" al inicio de la frase

2024-06-12 20:57 UTC, JavierSanchezCastro reviewed
Creo que podría sonar mejor

2024-06-12 23:29 UTC, alejsdev commented on docs/es/docs/fastapi-cli.md
> +Para correr tu aplicación de FastAPI para desarrollo, puedes usar el comando `fastapi dev`:
Creo que "ejecutar" quedaría mejor :thinking:

2024-06-12 23:30 UTC, alejsdev commented on docs/es/docs/fastapi-cli.md
> +De forma predeterminada, está habilitada la **recarga automática**, por lo que recargará automáticamente el servidor cuando realices cambios en tu código. Esto consume muchos recursos y podría ser me
Ahora que lo dices, sí, estoy de acuerdo :sweat_smile:

2024-06-13 01:56 UTC, alejsdev requested changes

2024-06-13 01:56 UTC, alejsdev commented on docs/es/docs/fastapi-cli.md
> +FastAPI CLI toma la ruta del Python de tu ambiente y automáticamente detecta la variable de FastAPI (comúnmente nombrada `app`) y la importa para finalmente servir la aplicación.
```suggestion
FastAPI CLI toma la ruta de tu programa Python (por ejemplo, `main.py`) y detecta automáticamente la variable con FastAPI (comúnmente llamada `app`), cómo importarla, y luego la sirve.
```

Aquí se hace referencia al programa de Python, no al Python del ambiente. :sweat_smile:

2024-06-13 01:56 UTC, alejsdev commented on docs/es/docs/fastapi-cli.md
> +En la mayoría de los casos, tendrías (y deberías) tener un "proxy de terminación" que maneje HTTPS por ti, esto dependerá de cómo implementes tu aplicación; tu proveedor podría hacerlo por ti o podrí
```suggestion
En la mayoría de los casos, tendrías (y deberías tener) un "proxy de terminación" que maneje HTTPS por ti, esto dependerá de cómo implementes tu aplicación; tu proveedor podría hacerlo por ti o podrías necesitar configurarlo tú mismo.
```

2024-06-13 01:56 UTC, alejsdev commented on docs/es/docs/fastapi-cli.md
> +De forma predeterminada, está habilitada la **recarga automática**, por lo que recargará automáticamente el servidor cuando realices cambios en tu código. Esto consume muchos recursos y podría ser me
```suggestion
Por defecto, está habilitada la **recarga automática**, por lo que se recargará automáticamente el servidor cuando realices cambios en tu código. Esto consume muchos recursos y podría ser menos estable que sin ella; solo debes usarlo para desarrollo.
```

2024-06-13 01:56 UTC, alejsdev commented on docs/es/docs/fastapi-cli.md
> +De forma predeterminada, escuchará en la dirección IP `127.0.0.1`, que es la IP para que tu máquina se comunique consigo misma (localhost).
```suggestion
Por defecto, escuchará en la dirección IP `127.0.0.1`, que es la IP para que tu máquina se comunique consigo misma (localhost).
```

2024-06-14 21:38 UTC, tiangolo commented
📝 Docs preview for commit f1b644b2f2cba01de7dbd89fc806aed87d7cb3a1 at: https://59af3d38.fastapitiangolo.pages.dev

2024-06-26 16:02 UTC, camigomezdev commented
@alejsdev todos los comentarios fueron resueltos, me cuentas cualquier modificación adicional

2024-08-19 16:27 UTC, svlandeg commented
@alejsdev : are the required changes made? If so - can we move this one to Tiangolo's column for a final review to get it merged?

2024-08-19 17:09 UTC, alejsdev reviewed
Hi @camigomezdev!

The original FastAPI CLI documentation has been modified recently (`fastapi dev` and `fastapi run`). Could you please adjust them so we can check them again and merge them? Thanks!

Once the changes are made we can proceed @svlandeg :nerd_face:

2024-08-19 17:09 UTC, alejsdev commented on docs/es/docs/fastapi-cli.md
> +!!! tip
/// tip | "Consejo"

Este formato cambió recientemente.

2024-09-19 22:18 UTC, closed without merging