🌐 Add Portuguese translation for docs/pt/docs/advanced/benchmarks.md
fastapi/fastapi pull request #11713
Opened 2024-06-12 12:27 UTC by ceb10n

Added portuguese translation for `docs/pt/docs/advanced/benchmarks.md`

Any feedback is appreciated

2024-06-12 12:31 UTC, tiangolo commented
📝 Docs preview for commit 67682f7a19cc2e750a0b15652e076e1cd537626e at: https://50c16bc1.fastapitiangolo.pages.dev

2024-06-13 01:18 UTC, oandersonmagalhaes requested changes
Thanks, Rafael. Great translation! I've added some suggestions. 🚀

2024-06-13 01:18 UTC, oandersonmagalhaes commented on docs/pt/docs/advanced/benchmarks.md
> +Benchmarks independentes da TechEmpower mostra que aplicações **FastAPI** rodando com o Uvicorn como <a href="https://www.techempower.com/benchmarks/#section=test&runid=7464e520-0dc2-473d-bd34-dbdfd7
```suggestion
Benchmarks independentes da TechEmpower mostram que aplicações **FastAPI** rodando com o Uvicorn como <a href="https://www.techempower.com/benchmarks/#section=test&runid=7464e520-0dc2-473d-bd34-dbdfd7e85911&hw=ph&test=query&l=zijzen-7" class="external-link" target="_blank">um dos frameworks Python mais rápidos disponíveis</a>, ficando atrás apenas do Starlette e Uvicorn (utilizado internamente pelo FastAPI).
```

2024-06-13 01:18 UTC, oandersonmagalhaes commented on docs/pt/docs/advanced/benchmarks.md
> +Porém, ao verificar benchmarks e comparações você deve prestar atenção ao seguinte.
```suggestion
Porém, ao verificar benchmarks e comparações você deve prestar atenção ao seguinte:
```

2024-06-13 01:18 UTC, oandersonmagalhaes commented on docs/pt/docs/advanced/benchmarks.md
> +Quanto mais simples o problema resolvido pela ferramenta, melhor será a performance. E a maioria das análises não realiza testes das funcionalidades adicionais que são oferecidas pela ferramenta.
```suggestion
Quanto mais simples o problema resolvido pela ferramenta, melhor será a performance. E a maioria das análises não testa funcionalidades adicionais que são oferecidas pela ferramenta.
```

2024-06-13 01:18 UTC, oandersonmagalhaes commented on docs/pt/docs/advanced/benchmarks.md
> +    * Você não escreveria uma aplicação utilizando o Uvicorn diretamente. Isso significaria que o seu código teria que incluir pelo menos todo o código fornecido pelo Starlette (ou o **FastAPI**). E
```suggestion
    * Você não escreveria uma aplicação utilizando o Uvicorn diretamente. Isso significaria que o seu código teria que incluir pelo menos todo o código fornecido pelo Starlette (ou o **FastAPI**). E caso você fizesse isso, a sua aplicação final teria a mesma sobrecarga que teria se utilizasse um framework, minimizando o código e os bugs.
```

2024-06-13 01:18 UTC, oandersonmagalhaes commented on docs/pt/docs/advanced/benchmarks.md
> +    * Então, ao utilizar o FastAPI você está economizando tempo de programação, bugs, linhas de código, e você provavelmente terá a mesma performance (ou até melhor) que você teria caso você não o ut
```suggestion
    * Então, ao utilizar o FastAPI, você está economizando tempo de programação, evitando bugs, linhas de código, e provavelmente terá a mesma performance (ou até melhor) do que teria caso você não o utilizasse (já que você teria que implementar tudo no seu código).
```

2024-06-13 10:18 UTC, ceb10n commented
> Thanks, Rafael. Great translation! I've added some suggestions. 🚀

Thanks [oandersonmagalhaes](https://github.com/oandersonmagalhaes) ;) 
I accepted all suggestions ;)

2024-06-13 10:24 UTC, tiangolo commented
📝 Docs preview for commit 1803c7619f604c9304ef86353af610c4cd564a52 at: https://7589cd6d.fastapitiangolo.pages.dev

2024-06-13 15:35 UTC, oandersonmagalhaes approved these changes
Thank you! 🚀

2024-06-14 15:07 UTC, merged

2024-06-14 15:07 UTC, alejsdev commented
Nice!  Thanks for the help @ceb10n @oandersonmagalhaes  :partying_face: