🌐 Add Turkish translation for tutorial `docs/tr/docs/tutorial/index.md`
fastapi/fastapi pull request #11820
Opened 2024-07-10 08:52 UTC by Rekl0w

🌐 Add Turkish translation for tutorial `docs/tr/docs/tutorial/index.md`

2024-07-10 08:55 UTC, tiangolo commented
📝 Docs preview for commit 2ff982cc3adb45633758f558583f6a1d6f87bafa at: https://090d707e.fastapitiangolo.pages.dev

2025-02-11 18:32 UTC, hevalhazalkurt approved these changes
Looks good! The translation is clear and accurate.

2025-02-18 15:16 UTC, alejsdev commented on docs/tr/docs/tutorial/index.md
> +!!! Not
```suggestion
!!! note
```

This is currently broken

2025-06-16 07:40 UTC, YuriiMotov requested changes

2025-06-16 07:40 UTC, YuriiMotov commented on docs/tr/docs/tutorial/index.md
> +</pre>
```suggestion
$ <font color="#4E9A06">fastapi</font> dev <u style="text-decoration-style:solid">main.py</u>

  <span style="background-color:#009485"><font color="#D3D7CF"> FastAPI </font></span>  Starting development server 🚀

             Searching for package file structure from directories
             with <font color="#3465A4">__init__.py</font> files
             Importing from <font color="#75507B">/home/user/code/</font><font color="#AD7FA8">awesomeapp</font>

   <span style="background-color:#007166"><font color="#D3D7CF"> module </font></span>  🐍 main.py

     <span style="background-color:#007166"><font color="#D3D7CF"> code </font></span>  Importing the FastAPI app object from the module with
             the following code:

             <u style="text-decoration-style:solid">from </u><u style="text-decoration-style:solid"><b>main</b></u><u style="text-decoration-style:solid"> import </u><u style="text-decoration-style:solid"><b>app</b></u>

      <span style="background-color:#007166"><font color="#D3D7CF"> app </font></span>  Using import string: <font color="#3465A4">main:app</font>

   <span style="background-color:#007166"><font color="#D3D7CF"> server </font></span>  Server started at <font color="#729FCF"><u style="text-decoration-style:solid">http://127.0.0.1:8000</u></font>
   <span style="background-color:#007166"><font color="#D3D7CF"> server </font></span>  Documentation at <font color="#729FCF"><u style="text-decoration-style:solid">http://127.0.0.1:8000/docs</u></font>

      <span style="background-color:#007166"><font color="#D3D7CF"> tip </font></span>  Running in development mode, for production use:
             <b>fastapi run</b>

             Logs:

     <span style="background-color:#007166"><font color="#D3D7CF"> INFO </font></span>  Will watch for changes in these directories:
             <b>[</b><font color="#4E9A06">&apos;/home/user/code/awesomeapp&apos;</font><b>]</b>
     <span style="background-color:#007166"><font color="#D3D7CF"> INFO </font></span>  Uvicorn running on <font color="#729FCF"><u style="text-decoration-style:solid">http://127.0.0.1:8000</u></font> <b>(</b>Press CTRL+C
             to quit<b>)</b>
     <span style="background-color:#007166"><font color="#D3D7CF"> INFO </font></span>  Started reloader process <b>[</b><font color="#34E2E2"><b>383138</b></font><b>]</b> using WatchFiles
     <span style="background-color:#007166"><font color="#D3D7CF"> INFO </font></span>  Started server process <b>[</b><font color="#34E2E2"><b>383153</b></font><b>]</b>
     <span style="background-color:#007166"><font color="#D3D7CF"> INFO </font></span>  Waiting for application startup.
     <span style="background-color:#007166"><font color="#D3D7CF"> INFO </font></span>  Application startup complete.
```

2025-06-16 07:40 UTC, YuriiMotov commented on docs/tr/docs/tutorial/index.md
> +FastAPI'ı yüklemenin ilk adımı:
This part was updated in original (En) document:

```
The first step is to install FastAPI.

Make sure you create a [virtual environment](../virtual-environments.md){.internal-link target=_blank}, activate it, and then **install FastAPI**:
```

2025-06-16 07:40 UTC, YuriiMotov commented on docs/tr/docs/tutorial/index.md
> +$ pip install fastapi
```suggestion
$ pip install "fastapi[standard]"
```

2025-06-16 07:40 UTC, YuriiMotov commented on docs/tr/docs/tutorial/index.md
> +Bu isteğe bağlı bağımlılıklara sahip olmak istemiyorsanız, bunun yerine `pip install fastapi-slim` ile yükleyebilirsiniz.
This part was updated in original (En) document:

```
When you install with `pip install "fastapi[standard]"` it comes with some default optional standard dependencies.

If you don't want to have those optional dependencies, you can instead install `pip install fastapi`.
```

2025-06-16 07:42 UTC, YuriiMotov commented
@Rekl0w, thanks for contributing to FastAPI!
The original document has been updated and now this PR needs to be updated.
Would you like to work on it?

2025-06-19 09:14 UTC, Rekl0w commented
I'll open a new PR for this. @YuriiMotov

2025-06-19 09:31 UTC, YuriiMotov commented
Thanks!

Let's close this in favor of https://github.com/fastapi/fastapi/pull/13806

2025-06-19 09:31 UTC, closed without merging