🌐 Add Portuguese translation for docs/pt/docs/advanced/sub-applications.md
fastapi/fastapi pull request #11856
Opened 2024-07-17 04:15 UTC by marcelomarkus

- **Add translation:**
docs/pt/docs/advanced/sub-applications.md

2024-07-17 04:20 UTC, tiangolo commented
📝 Docs preview for commit 195c2ae1135c20d477b1ea88e43c7ad1ff34d2fe at: https://38176437.fastapitiangolo.pages.dev

2024-07-17 05:09 UTC, tiangolo commented
📝 Docs preview for commit dd45453428478ca64d48220f70c31473b720d128 at: https://ee1b34d7.fastapitiangolo.pages.dev

2024-07-17 05:19 UTC, tiangolo commented
📝 Docs preview for commit 5b678fd66560aab0f42faf74f8fe3aa63f46adfd at: https://6da2e833.fastapitiangolo.pages.dev

2024-07-17 05:52 UTC, tiangolo commented
📝 Docs preview for commit 71134c47dc9e1d25680cb9f4e90be014d29e96c4 at: https://25bce513.fastapitiangolo.pages.dev

2024-07-17 11:06 UTC, ceb10n requested changes
Great translation ✨

2024-07-17 11:06 UTC, ceb10n commented on docs/pt/docs/advanced/sub-applications.md
> +Primeiro, crie a aplicação principal, de nível superior, **FastAPI**, e suas *operações de caminho*:
Most translations in pt docs are using operações de rota when translating path operations

2024-07-17 11:06 UTC, ceb10n commented on docs/pt/docs/advanced/sub-applications.md
> +Em seguida, crie sua sub-aplicação e suas *operações de caminho*.
Most translations in pt docs are using operações de rota when translating path operations

2024-07-17 11:06 UTC, ceb10n commented on docs/pt/docs/advanced/sub-applications.md
> +Você verá a documentação automática da API para a aplicação principal, incluindo apenas suas próprias _operações de caminho_:
Most translations in pt docs are using operações de rota when translating path operations

2024-07-17 11:06 UTC, ceb10n commented on docs/pt/docs/advanced/sub-applications.md
> +Você verá a documentação automática da API para a sub-aplicação, incluindo apenas suas próprias _operações de caminho_, todas sob o prefixo de sub-caminho correto `/subapi`:
Most translations in pt docs are using operações de rota when translating path operations

2024-07-17 18:03 UTC, lucasbalieiro reviewed
**Tops! Just awaiting the fixes that @ceb10n highlited**

2024-07-17 18:15 UTC, tiangolo commented
📝 Docs preview for commit 59478911240a59a22b23210934210bb70c57b806 at: https://61fe8430.fastapitiangolo.pages.dev

2024-07-17 18:28 UTC, ceb10n approved these changes
🚀

2024-07-17 18:29 UTC, tiangolo commented
📝 Docs preview for commit 5c696f067e10fda7c22b4c736d9c46756ce95fe4 at: https://9eefbe8e.fastapitiangolo.pages.dev

2024-07-17 20:22 UTC, lucasbalieiro approved these changes
Let's go

2024-08-03 00:02 UTC, merged

2024-08-03 00:02 UTC, alejsdev commented
Yay! thanks for the help! @marcelomarkus  @ceb10n @lucasbalieiro :nerd_face: :v: