Add Japanese translation for docs/ja/docs/tutorial/dependencies/global-dependencies.md
fastapi/fastapi pull request #11888
Opened 2024-07-25 13:34 UTC by yodai-yodai

Add Japanese translation about global dependencies.

2024-11-13 06:45 UTC, TakakiMoriguchi requested changes
お疲れ様です。
自分も`yodai-yodai`さんを見習って翻訳に参加したいところではありますが、OSS参加が初めてということもあり、先ずはいくつかコメントしました。
よろしくお願い致します。

2025-01-18 06:33 UTC, k94-ishi reviewed
I am a native speaker, and aside from the parts I pointed out, I think it’s easy to read and well-written !

2025-01-18 06:33 UTC, k94-ishi commented on docs/ja/docs/tutorial/dependencies/global-dependencies.md
> +後で、より大きなアプリケーションの構造([Bigger Applications - Multiple Files](../../tutorial/bigger-applications.md){.internal-link target=_blank}))について読む時に、おそらく複数のファイルを使用して、*path operations*のグループに対して単一の`dependencies`パ
`([Bigger Applications - Multiple Files](../../tutorial/bigger-applications.md){.internal-link target=_blank}))`
の閉じ括弧')'が二重になっています。

2025-01-18 06:33 UTC, k94-ishi commented on docs/ja/docs/tutorial/dependencies/global-dependencies.md
> +後で、より大きなアプリケーションの構造([Bigger Applications - Multiple Files](../../tutorial/bigger-applications.md){.internal-link target=_blank}))について読む時に、おそらく複数のファイルを使用して、*path operations*のグループに対して単一の`dependencies`パ
原文の", possibly with multiple files"はおそらく手前の"bigger applications"への補足なので、内容的には以下のようになるかと思います。（表現がいまいちかもしれないですが）

``` src
後に、複数ファイルを持つようなより大きなアプリケーションの構築方法([Bigger Applications - Multiple Files](../../tutorial/bigger-applications.md){.internal-link target=_blank})について読む際に、*path operations*のグループに対して単一の`dependencies`パラメータを宣言する方法を学ぶでしょう。
```

2025-02-21 20:33 UTC, closed without merging