Add Japanese translation for `docs/ja/docs/advanced/response-change-status-code.md`
fastapi/fastapi pull request #11903
Opened 2024-07-27 12:17 UTC by yodai-yodai

2024-07-27 12:22 UTC, tiangolo commented
📝 Docs preview for commit 1f8220c35fc8e9a955c51a94de1fbb85478a9c89 at: https://482b19c3.fastapitiangolo.pages.dev

2024-07-27 13:21 UTC, tiangolo commented
📝 Docs preview for commit a230c9a33c0d599bc4cf1397f4dd38026c34f62c at: https://20a219ca.fastapitiangolo.pages.dev

2024-11-11 14:43 UTC, maru0123-2004 requested changes
お疲れ様です。
レビューは初めてなので至らないところがあるかと思いますが、ご確認のほどよろしくお願い致します。

2024-11-11 14:43 UTC, maru0123-2004 commented on docs/ja/docs/advanced/response-change-status-code.md
> +それに、返されたデータを`response_model`でフィルタリングして変換できるようにしたい場合もあります。
"それに"よりも"それでも"や"さらに"のほうが自然のように感じます。
また、語尾を"あります"ではなく"あるでしょう"にしたほうが次の文との接続が良いように思います。

2024-11-11 14:43 UTC, maru0123-2004 commented on docs/ja/docs/advanced/response-change-status-code.md
> +{!../../../docs_src/response_change_status_code/tutorial001.py!}
私の勘違いでしたら申し訳ないのですが、こちらのコードがページの方で表示されていないように思います。
```md
{* ../../docs_src/response_change_status_code/tutorial001.py hl[1,9,12] *}
```
こちらで確認した限り、[英語版](https://github.com/fastapi/fastapi/blob/5a48c37056397e47ab164ba4430807aa6fc9a710/docs/en/docs/advanced/response-change-status-code.md?plain=1#L23) ではこのようになっているようです。

2024-11-11 14:43 UTC, maru0123-2004 commented on docs/ja/docs/advanced/response-change-status-code.md
> +また、`response_model`を宣言した場合も、返されたオブジェクトをフィルタリングして変換します。
`返されたオブジェクトを引き続きフィルタリングして変換します。`
に変更したほうが新たな要素のように見えてしまわなくて良いように思います。

2025-01-20 23:18 UTC, k94-ishi reviewed
Since @maru0123-2004 has already pointed out most of the issues, there was little for me to add.

2025-01-20 23:18 UTC, k94-ishi commented on docs/ja/docs/advanced/response-change-status-code.md
> +_FastAPI_ はその _temporal_ レスポンスを使用してステータスコード(クッキーとヘッダも)を取り出し、任意の`response_model`によってフィルタリングされて、返したい値を含む最後のレスポンスに展開します。
太字`**FastAPI**`が斜体`_FastAPI_`になっています。

2025-02-20 22:18 UTC, closed without merging