Add Japanese translation for `docs/ja/docs/advanced/response-cookies.md`
fastapi/fastapi pull request #11900
Opened 2024-07-27 09:11 UTC by yodai-yodai

2024-07-27 09:16 UTC, tiangolo commented
📝 Docs preview for commit d2a24c41d851e5b5c8fe2b0d14469be8c99f5b25 at: https://16cfabd5.fastapitiangolo.pages.dev

2024-07-27 11:04 UTC, tiangolo commented
📝 Docs preview for commit 0808fc39c45dc80bc42990fdbe0661884b129f95 at: https://1f69d8d2.fastapitiangolo.pages.dev

2024-07-27 13:20 UTC, tiangolo commented
📝 Docs preview for commit c5857f1da260b2d4d138ff65b948caf18b18a99d at: https://e7946618.fastapitiangolo.pages.dev

2025-02-21 16:21 UTC, k94-ishi requested changes
This PR includes translations for files other than response-cookies.md, which suggests an issue with the scope of the PR. I would like to review it after you separate the PR by file.

2025-03-24 22:18 UTC, closed without merging