Add Chinese translation for index docs
fastapi/fastapi pull request #1191
Opened 2020-03-31 02:19 UTC by waynerv

We (a small team) are working to complete the doc translation of Chinese version in the next two months.

2020-03-31 03:50 UTC, RunningIkkyu commented
@waynerv I'm working on the Chinese trans too, may I have your wechat or email?

2020-03-31 05:21 UTC, RunningIkkyu requested changes
Great translations! @waynerv

2020-03-31 05:21 UTC, RunningIkkyu commented on docs/zh/docs/index.md
> +我们借助 Pydantic 来使用标准的 Python 类型声明请求体。
1. "Standard Python types"  is a proper noun, should be tranlated into `Python标准类型` not `标准的Python类型` .
2.  The relationship between `Pydantic` and `Standard Python types` should be parallel, not progressive。That could lead to ambiguity.

The translation should be 
```txt
我们借助 `Pydantic` 以及 `Python` 标准类型来声明请求体。
```

2020-03-31 05:21 UTC, RunningIkkyu commented on docs/zh/docs/index.md
> +* 编辑器支持， 包括：
Redundant space after "编辑器支持，".

2020-03-31 05:21 UTC, RunningIkkyu commented on docs/zh/docs/index.md
> +要了解更多，请查阅 <a href="https://fastapi.tiangolo.com/benchmarks/" class="internal-link" target="_blank">基准测试</a>章节。
Missing a space after "基准测试".

2020-03-31 05:22 UTC, waynerv commented
@RunningIkkyu Great! You can send your wechat to my gmail: ampedee@gmail.com. I will contact you later.

2020-03-31 15:34 UTC, Dustyposa commented on docs/zh/docs/index.md
> +简单来说， 你声明了 **一次** 参数、请求体等的类型。就和声明函数的参数类型一样。
I can’t make sure this sentence which  be translated is clear.
“总之，你只需要声明参数，请求体等类型一次。和函数参数声明类型相同。” this one is better? need other review

2020-03-31 15:34 UTC, Dustyposa commented on docs/zh/docs/index.md
> +* 安全性和身份验证，包括通过 **JWT 令牌** 和 **HTTP Basic** 身份认证来支持 **OAuth2**。
`HTTP Basic auth` is also called "HTTP 基本认证" in [wiki](https://zh.wikipedia.org/wiki/HTTP%E5%9F%BA%E6%9C%AC%E8%AE%A4%E8%AF%81).
It's can be translated.

2020-03-31 15:34 UTC, Dustyposa commented on docs/zh/docs/index.md
> +* <a href="https://github.com/Tinche/aiofiles" target="_blank"><code>aiofiles</code></a> - 使用 `FileResponse` 或 `StaticFiles`时安装。
MIss space before “时安装”

2020-04-01 09:19 UTC, jamesyangget commented
天哪，有翻译的人了，我也自己开了个[翻译项目](https://github.com/apachecn/fastapi-docs-cn)，我感觉自己在做无用功

2020-04-01 09:40 UTC, Dustyposa commented
> 天哪，有翻译的人了，我也自己开了个[翻译项目](https://github.com/apachecn/fastapi-docs-cn)，我感觉自己在做无用功

has interested in join our team? my email zmzposa@outlook.com

2020-04-01 18:30 UTC, tiangolo commented
This is amazing! Thanks everyone for doing this! :rocket: :earth_asia: :speech_balloon: 

And special thanks for the reviews from others, that's key here, as I don't know Chinese :sweat_smile: 

When others feel like this is complete, that there are no more corrections necessary, and hopefully that the style of "conversation" is similar, please add a new review approving the changes of this PR.

That way, after seeing that there's some consensus on the translation I'll be able to merge it. :tada:

2020-04-02 02:51 UTC, RunningIkkyu approved these changes

2020-04-18 15:52 UTC, tiangolo commented
@Dustyposa do you think this is ready? You can let me know with a review approving it :smile: :+1: 

@phy25 if you have the chance, could you help me with a review here?

I'm just waiting for more reviews approving it before merging. :globe_with_meridians: :rocket:

2020-04-20 01:47 UTC, waynerv commented
@tiangolo I can ask the Chinese community for some help. More and more Chinese developers have started to use FastAPI recently.

2020-04-20 02:29 UTC, Dustyposa approved these changes

2020-04-23 13:46 UTC, lpdswing approved these changes
checked, i approve this

2020-04-24 06:56 UTC, RunningIkkyu approved these changes

2020-05-16 09:58 UTC, merged

2020-05-16 10:00 UTC, tiangolo commented
This is awesome! :rocket: :earth_asia: :bow: 

Thanks for all the work @waynerv ! :cake: :clap: :tada: 

Thanks for the reviews and comments @RunningIkkyu , @Dustyposa , @lpdswing , @jamesyangget :muscle: :nerd_face: :bow: :cake: