translation features.md to Chinese
fastapi/fastapi pull request #1192
Opened 2020-03-31 05:10 UTC by Dustyposa

We have a small team doing that translation en docs to Chinese.
If you are interested on this thing. Can join us,and speed the translate.:smile:

2020-03-31 07:21 UTC, waynerv commented on docs/zh/docs/features.md
> +    直接将`second_user_data`字典的键和值直接作为key-value参数传递，等同于：`User(id=4, name="Mary", joined="2018-11-30")`
duplicate "直接", suggest to be "将`second_user_data`字典的键值对直接作为关键字参数传递"

2020-03-31 07:21 UTC, waynerv commented on docs/zh/docs/features.md
> +所有的框架都被设计得易于使用且直观，所有的决定都在开发之前就在多个编辑器上进行了测试，来确保最佳的开发体验。
"所有的框架" should be "整个框架"

2020-03-31 07:21 UTC, waynerv commented on docs/zh/docs/features.md
> +你就不需要经常再来看这个文档。
“你不会需要经常回来看文档”  reads better.

2020-03-31 07:21 UTC, waynerv commented on docs/zh/docs/features.md
> +你将在代码中完成你在之前可能曾认为不可能的事。例如，在来自请求 JSON 体（可能是嵌套的）中的键`price`。
"completion in code" should be "代码补全" not "在代码中完成"

2020-03-31 07:21 UTC, waynerv commented on docs/zh/docs/features.md
> +### 总结
"Short" should be “简洁" or "简短"?

2020-03-31 07:21 UTC, waynerv commented on docs/zh/docs/features.md
> +但是默认情况下，所有都是**“能够工作”**。
"在默认情况下，一切都能顺利工作" reads better?

2020-04-21 06:24 UTC, waynerv commented on docs/zh/docs/features.md
> +这也意味着在很多情况下，你可以将从请求中获得的相同对象**直接传到数据库**，因为所有的验证都是自动的。
“因为所有的验证都是自动的。”should be “因为一切都会被自动验证”

2020-04-21 06:24 UTC, waynerv commented on docs/zh/docs/features.md
> +通过 **FastAPI** 你可以获得所有 **Pydantic**  (FastAPI 基于 Pydantic 做了所有的数据处理)：
missing “features”

通过 **FastAPI** 你可以获得所有 **Pydantic** 的特性  (因为 FastAPI 整个的数据处理部分都是基于 Pydantic 的)：

2020-04-21 06:24 UTC, waynerv commented on docs/zh/docs/features.md
> +    * 如果你知道 Python types，你就知道如何使用 Pydantic。
如果你了解 Python 的类型

2020-04-21 06:24 UTC, waynerv commented on docs/zh/docs/features.md
> +    * 没有新的模式定义 micro-language 需要学习。
不需要学习一套新的规则或语言用来定义模式

2020-04-21 06:24 UTC, waynerv commented on docs/zh/docs/features.md
> +    * Pydantic 允许定义自定义数据类型或者你可以用验证器装饰器对被装饰的模型上的方法扩展验证。
Pydantic 允许自定义数据类型，或者你可以用验证器装饰器装饰数据模型的方法来扩展验证功能。

2020-04-22 10:44 UTC, RunningIkkyu requested changes

2020-04-22 10:44 UTC, RunningIkkyu commented on docs/zh/docs/features.md
> +* 用于创建API的 <a href="https://github.com/OAI/OpenAPI-Specification" class="external-link" target="_blank"><strong>OpenAPI</strong></a> 包含了<abbr title="也被叫做: endpoints, routes">路径</abbr><abbr title="也叫做
Leave space before and after `API`:
"用于创建API的" should be  "用于创建 API 的"

2020-04-22 10:44 UTC, RunningIkkyu commented on docs/zh/docs/features.md
> +* 使用 <a href="http://json-schema.org/" class="external-link" target="_blank"><strong>JSON Schema</strong></a> ( OpenAPI 本身就是基于 JSON Schema 的)自动生成数据模型文档。
1. 应该使用中文符号（括号）。
2. as 应该翻译出来：因为

```
* 使用 <a href="http://json-schema.org/" class="external-link" target="_blank"><strong>JSON Schema</strong></a> 自动生成数据模型文档（因为OpenAPI 本身就是基于 JSON Schema 的）。
```

2020-04-22 10:44 UTC, RunningIkkyu commented on docs/zh/docs/features.md
> +### 自动生成文档
Better leave a blank line before this line.

2020-04-22 10:44 UTC, RunningIkkyu commented on docs/zh/docs/features.md
> +交互式 API 文档以及具探索性 web 界面。因为该框架是基于 OpenAPI，所以有很多可选选项，默认情况下只设置了两个。
It's hard to understand "默认情况下只设置了两个". 补全主语宾语会更容易理解。

因为该框架是基于 OpenAPI，所以有很多可选项，**FastAPI** 默认自带两个交互式 API 文档。

2020-04-22 10:44 UTC, RunningIkkyu commented on docs/zh/docs/features.md
> +在最近的 Python 开发者调查中，我们能看到<a href="https://www.jetbrains.com/research/python-developers-survey-2017/#tools-and-features" class="external-link" target="_blank">被使用最多的功能是"自动补全"</a>。
Leave a space before and after `<a href="https://www.jetbrains.com/research/python-developers-survey-2017/#tools-and-features" class="external-link" target="_blank">`

2020-04-22 10:44 UTC, RunningIkkyu commented on docs/zh/docs/features.md
> +你不会需要经常回来看文档。
"不会需要"  -> "几乎不需要"

2020-04-22 10:44 UTC, RunningIkkyu commented on docs/zh/docs/features.md
> +在这里可以看到你的编辑器是如何帮助你的：
"你的编辑器可能会这样帮助你:"   可能更符合语言习惯。

2020-04-22 10:44 UTC, RunningIkkyu commented on docs/zh/docs/features.md
> +你将能进行代码补全，这是在之前你可能曾认为不可能的事。例如，在来自请求 JSON 体（可能是嵌套的）中的键`price`。
Leave a space before `price`.

2020-04-22 10:44 UTC, RunningIkkyu commented on docs/zh/docs/features.md
> +不会再输错键名，来回翻看文档，或者来回滚动寻找你最后使用的`username`或者`user_name`。
Leave spaces before and after English words.

2020-04-22 10:44 UTC, RunningIkkyu commented on docs/zh/docs/features.md
> +任何类型都有合理的**默认值**，任何和地方都有可选配置。所有的参数被微调，来满足你的需求，定义成你需要的API。
Leave spaces before and after English words.

2020-04-22 10:44 UTC, RunningIkkyu commented on docs/zh/docs/features.md
> +* 测试客户端基于`requests`。
Leave spaces before and after `requests`.

2020-04-22 10:44 UTC, RunningIkkyu commented on docs/zh/docs/features.md
> +    * 验证器允许复杂的数据架构能被清晰简单地定义，检查并记录为 JSON Schema。
1. 物作主语时 `allow` 应该翻译成 **使得** ， 参考 Collins 词典。
2. defined, checked, documented 三者为并列关系。
> V-T If one thing allows another thing to happen, the first thing creates the opportunity for the second thing to happen. 

验证器使我们能够简单清楚的将复杂的数据模式定义、检查并记录为 JSON Schema。

2020-04-22 14:31 UTC, Dustyposa commented
Thanks for your review.
@waynerv @RunningIkkyu 
😄 
🚀

2020-04-23 05:02 UTC, waynerv approved these changes

2020-04-23 06:45 UTC, RunningIkkyu approved these changes

2020-05-16 10:18 UTC, merged

2020-05-16 10:18 UTC, tiangolo commented
Awesome! Thanks for your contribution @Dustyposa ! :coffee: :bow: :clap: 

And thanks for the reviews @waynerv and @RunningIkkyu ! :bow: :cake: