🌐 Add Portuguese translation for docs/pt/docs/reference/
fastapi/fastapi pull request #11969
Opened 2024-08-08 02:50 UTC by marcelomarkus

- Portuguese translation:
docs/pt/docs/reference/encoders.md
docs/pt/docs/reference/fastapi.md
docs/pt/docs/reference/httpconnection.md
docs/pt/docs/reference/middleware.md
docs/pt/docs/reference/parameters.md
docs/pt/docs/reference/request.md
docs/pt/docs/reference/response.md
docs/pt/docs/reference/responses.md
docs/pt/docs/reference/staticfiles.md
docs/pt/docs/reference/status.md
docs/pt/docs/reference/templating.md
docs/pt/docs/reference/testclient.md
docs/pt/docs/reference/uploadfile.md
docs/pt/docs/reference/websockets.md

2024-08-09 10:53 UTC, ceb10n requested changes
Great!

Just missing a closing ` in `staticfiles.md`

2024-08-12 11:55 UTC, nazarepiedady approved these changes

2024-08-12 20:18 UTC, cassiobotaro approved these changes

2024-08-15 15:29 UTC, tiangolo commented
Thank you for your contribution! :bow: 

I recently realized that there are some sections where the benefit of translating them has a tradeoff with the content... for example, the content of the reference is injected from the source files, and most of the content in that section ends up being in English either way... and then there's a chance that if the reference is updated including other objects to be injected, the translation would be obsolete. :pensive: 

So I decided not to translate some sections, including the reference. https://fastapi.tiangolo.com/contributing/#dont-translate-these-pages

So, I'm gonna close this one, but thanks for the effort! :bow:

2024-08-15 15:29 UTC, closed without merging