🌐 Add Portuguese translation for docs/pt/docs/tutorial/bigger-applications.md
fastapi/fastapi pull request #11971
Opened 2024-08-08 04:40 UTC by marcelomarkus

- Portuguese translation:
docs/pt/docs/tutorial/bigger-applications.md

2024-08-08 05:41 UTC, nazarepiedady approved these changes

2024-08-09 10:40 UTC, ceb10n requested changes
Great! ✨

2024-08-09 10:40 UTC, ceb10n commented on docs/pt/docs/tutorial/bigger-applications.md
> +/// info
I think it's nice to keep the translations of tip too:

`/// info | "Informação"`

Other translations are doing this:

![example](https://github.com/user-attachments/assets/3a39512b-808f-4bae-b61d-0cfaa081365a)

2024-08-09 10:40 UTC, ceb10n commented on docs/pt/docs/tutorial/bigger-applications.md
> +Mas ele ainda faz parte da mesma **FastAPI** aplicação/web API (faz parte do mesmo "pacote Python").
I think it makes more sense to put FastAPI after *aplicação/web API*:

`Mas ele ainda faz parte da mesma aplicação/web API **FastAPI** `

2024-08-09 10:40 UTC, ceb10n commented on docs/pt/docs/tutorial/bigger-applications.md
> +/// info
The same here:

`/// info | "Informação"`

2024-08-09 10:40 UTC, ceb10n commented on docs/pt/docs/tutorial/bigger-applications.md
> +/// info
The same:

`/// info | "Informação"`

2024-08-13 08:53 UTC, nazarepiedady approved these changes

2024-08-14 21:43 UTC, ceb10n approved these changes

2024-08-15 15:38 UTC, merged

2024-08-15 15:39 UTC, alejsdev commented
Nice! Thanks for your contribution @marcelomarkus :nerd_face: 
And thanks for the reviews @ceb10n @nazarepiedady :v: