🌐 Add Portuguese translation for `docs/pt/docs/advanced/testing-dependencies.md`
fastapi/fastapi pull request #11995
Opened 2024-08-12 12:48 UTC by ceb10n

2024-08-12 13:36 UTC, wesinalves requested changes
Nice job, Just 1 typo found.

2024-08-12 13:36 UTC, wesinalves commented on docs/pt/docs/advanced/testing-dependencies.md
> +## Sobreponto dependências durante os testes
There is a typo in Sobreponto

2024-08-12 14:31 UTC, nazarepiedady approved these changes

2024-08-12 15:22 UTC, ceb10n commented on docs/pt/docs/advanced/testing-dependencies.md
> +## Sobreponto dependências durante os testes
I'll fix it, thank you ♥️

2024-08-12 20:19 UTC, cassiobotaro approved these changes

2024-08-15 15:35 UTC, merged

2024-08-15 15:36 UTC, alejsdev commented
Cool! Thank you for the help @ceb10n @wesinalves @cassiobotaro @nazarepiedady :100: :rocket: