Add Chinese translation for tutorial intro doc
fastapi/fastapi pull request #1202
Opened 2020-04-01 13:46 UTC by waynerv

2020-04-05 03:42 UTC, songzhi approved these changes

2020-04-06 05:32 UTC, RunningIkkyu requested changes

2020-04-06 05:32 UTC, RunningIkkyu commented on docs/zh/docs/tutorial/index.md
> +    并且安装`uvicorn`来作为服务器：
Leave space before and after `uvicorn`.

2020-04-06 05:36 UTC, RunningIkkyu reviewed
Great trans.

2020-05-16 10:32 UTC, merged

2020-05-16 10:32 UTC, tiangolo commented
Awesome! Thanks @waynerv ! :rocket: :bow: 

And thanks @RunningIkkyu and @songzhi for the reviews! :clap: :rocket: