Add the docs\zh\docs\environment-variables.md
fastapi/fastapi pull request #12091
Opened 2024-08-30 06:00 UTC by skyanye

2024-08-30 07:50 UTC, nick-cjyx9 requested changes

2024-08-30 07:50 UTC, nick-cjyx9 commented on docs/zh/docs/environment-variables.md
> +环境变量（有时也被称为" **env var** "）是在种存在于Python代码 **外面** 的变量, 例如在 **操作系统** 中。它可以被Python代码读取，当然也可以被其他程序读取。
env var 两侧空格可去，中文单词两侧不用加空格，会降低阅读连续性，中英混排是英语单词两侧加空格。

“例如”翻译不准确

```suggestion
环境变量（有时也被称为"**env var**"）是一种存在于**操作系统**中，Python 代码**之外**的变量。它可以被你的 Python 代码读取（当然也可以被其他程序读取）。
```

2024-08-30 07:50 UTC, nick-cjyx9 commented on docs/zh/docs/environment-variables.md
> +环境变量在处理应用 **设置** 时非常有用，例如在 **安装** Python时。
空格问题

2024-08-30 07:50 UTC, nick-cjyx9 commented on docs/zh/docs/environment-variables.md
> +你可以在 **终端或命令行** 中 **创建** 和使用环境变量，而不需要打开Python。
duplicated

2024-08-30 07:50 UTC, nick-cjyx9 commented on docs/zh/docs/environment-variables.md
> +例如，你可以有一个文件“main.py”，其中包含：
有 -> 新建

2024-08-30 07:50 UTC, nick-cjyx9 commented on docs/zh/docs/environment-variables.md
> +您还可以在 Python **外部**、在终端中（或使用任何其他方法）创建环境变量，然后 **在Python中读取它们** 。
空格问题

2024-08-30 07:50 UTC, nick-cjyx9 commented on docs/zh/docs/environment-variables.md
> +您还可以仅为 **特定程序调用** 创建环境变量，该变量仅对该程序可用。同时，它仅在其设定的时间内可用。
以下仍存在空格问题，不再一一标注

2024-08-30 07:50 UTC, nick-cjyx9 commented on docs/zh/docs/environment-variables.md
> +您可以在<a href="https://en.wikipedia.org/wiki/Environment_variable" class="external-link" target="_blank">Wikipedia for Environment Variable</a>了解更多信息。
https://zh.wikipedia.org/wiki/%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F

2024-09-07 14:34 UTC, nick-cjyx9 commented
@skyanye Can you spend some time to apply these changes?

2024-09-07 14:50 UTC, skyanye commented
> @skyanye Could you spend some time applying these changes?

@nick-cjyx9 Sorry, I reject to continue translate anymore. I think the content you marked above does not need to be modified. Because the translation is for people who only know Chinese, in order to express clearly, it is usually not translated directly from English. I saw the translated content on other pages of your website, which is difficult to understand. It is better to read it directly in English. In addition, your website does not parse markdown correctly. If you do not add spaces, there are a lot of asterisks on the website, which greatly affects the reading experience. Please log in to the page and check it yourself.

2024-09-07 16:08 UTC, nick-cjyx9 commented
Thank you for bringing this to my attention; I will review it later. However, I must respectfully disagree, as I believe the spacing plays an important role in enhancing the reading experience. Inconsistent typesetting can lead to a disorganized presentation, so I won't be able to approve this change.

Apologies for any inconvenience caused.

2024-09-08 00:02 UTC, closed without merging