🌐 Add Portuguese translation for `docs/pt/docs/how-to/graphql.md`
fastapi/fastapi pull request #12215
Opened 2024-09-18 14:51 UTC by AnandaCampelo

🌐 Add Portuguese translation for `docs/pt/docs/how-to/graphql.md`

2024-09-18 16:16 UTC, JoaoGustavoRogel requested changes
Great text!!

2024-09-18 16:17 UTC, JoaoGustavoRogel requested changes

2024-09-18 16:17 UTC, JoaoGustavoRogel commented on docs/pt/docs/how-to/graphql.md
> +/// tip
You can add translation for this:
```
/// tip | "Dica"
```

2024-09-18 16:17 UTC, JoaoGustavoRogel commented on docs/pt/docs/how-to/graphql.md
> +/// tip
You can add translation for this:
```
/// tip | "Dica"
```

2024-09-18 16:21 UTC, nazarepiedady approved these changes
Despite the parts that need a little revision, the rest is good enough to be merged after correction is applied.

2024-09-18 17:04 UTC, JoaoGustavoRogel approved these changes
Great job!

2024-09-18 17:22 UTC, ceb10n approved these changes
Thank You Ananda 💯 

I've made just some few considerations. None of them are blocking, and you can change if you feel it's right.

Thank you 🚀

2024-09-18 17:22 UTC, ceb10n commented on docs/pt/docs/how-to/graphql.md
> +Você pode combinar *operações de caminho* normais do FastAPI com GraphQL na mesma aplicação.
although "operações de caminho" is also used, the most common translation in the docs is "operações de rota". I think it's nice to keep de standard 😃

2024-09-18 17:22 UTC, ceb10n commented on docs/pt/docs/how-to/graphql.md
> +Como **FastAPI** é baseado no padrão **ASGI**, é muito fácil integrar qualquer biblioteca **GraphQL** também compatível com ASGI.
I would use *o* before FastAPI:

"Como **o** FastAPI é baseado..."

and:

...GraphQL que também **é** compatível com **o** ASGI

2024-09-18 17:22 UTC, ceb10n commented on docs/pt/docs/how-to/graphql.md
> +Dependendo no seu caso de uso, você pode preferir usar uma biblioteca diferente, mas se você me perguntasse, eu provavelmente sugeriria que você experimentasse o **Strawberry**.
I would change **no** for **do**:

"Dependendo **do** seu caso de uso..."

2024-09-19 00:39 UTC, marcelomarkus commented on docs/pt/docs/how-to/graphql.md
> +
Suggestion. ✨
`em Strawberry documentation` to `na documentação do Strawberry`

2024-09-19 19:30 UTC, ceb10n approved these changes
❤️

2024-10-04 11:15 UTC, merged

2024-10-04 11:15 UTC, alejsdev commented
Thanks for your contribution! @AnandaCampelo :nerd_face: :rocket: