🌐 Add Portuguese translation for `docs/pt/docs/deployment/concepts.md`
fastapi/fastapi pull request #12219
Opened 2024-09-19 02:05 UTC by marcelomarkus

**- Portuguese translation**
docs/pt/docs/deployment/concepts.md

2024-09-19 08:14 UTC, nazarepiedady approved these changes

2024-09-19 10:53 UTC, ceb10n requested changes
Great work 🚀 

You missed a line (still needs translation), and I made a few suggestions too.

✨

2024-09-19 10:53 UTC, ceb10n commented on docs/pt/docs/deployment/concepts.md
> +No final, o objetivo final é ser capaz de **atender seus clientes de API** de uma forma **segura**, **evitar interrupções** e usar os **recursos de computação** (por exemplo, servidores remotos/máqui
I would change:

"No final, o objetivo final..."

for something like:

"No final, o principal objetivo..."

It's odd to use final two times in a row

2024-09-19 10:53 UTC, ceb10n commented on docs/pt/docs/deployment/concepts.md
> +I'll give you more concrete examples in the next chapters.
You missed this line. Still needs the translation

2024-09-19 10:53 UTC, ceb10n commented on docs/pt/docs/deployment/concepts.md
> +### Trabalhador Processos e Portas
I would change this title to:

"Processos do Trabalhador e Portas"

2024-09-24 11:26 UTC, ceb10n approved these changes
✨

2024-09-28 19:28 UTC, cassiobotaro approved these changes

2024-10-04 11:04 UTC, merged

2024-10-04 11:05 UTC, alejsdev commented
Thanks for one more contribution! @marcelomarkus :sunglasses: