🌐 Add Spanish translation for `docs/es/docs/environment-variables.md`
fastapi/fastapi pull request #12211
Opened 2024-09-17 21:16 UTC by tintayadev

2024-09-18 06:53 UTC, JavierSanchezCastro requested changes

2024-09-18 06:53 UTC, JavierSanchezCastro commented on docs/es/docs/environment-variables.md
> +También puedes crear variables de entorno **por fuera** de Python, en la terminal (o por cualquier otra método), y luego **leerlas en Python**.
```suggestion
También puedes crear variables de entorno **por fuera** de Python, en la terminal (o por cualquier otro método), y luego **leerlas en Python**.
```

2024-09-19 14:02 UTC, JavierSanchezCastro requested changes

2024-09-19 14:02 UTC, JavierSanchezCastro commented on docs/es/docs/environment-variables.md
> +/// tip
```suggestion
/// tip | Consejo
```

2024-09-19 14:02 UTC, JavierSanchezCastro commented on docs/es/docs/environment-variables.md
> +/// tip
```suggestion
/// tip | Consejo
```

2024-09-19 14:02 UTC, JavierSanchezCastro commented on docs/es/docs/environment-variables.md
> +/// tip
```suggestion
/// tip | Consejo
```

2024-09-19 20:36 UTC, tintayadev commented
Hey @JavierSanchezCastro 
Thanks so much for your review, I miss those typos.

2024-09-19 21:30 UTC, JavierSanchezCastro approved these changes

2024-12-30 18:55 UTC, tiangolo commented
This was covered in another PR, so I'll close this one now, thanks for the effort! :cake: :coffee:

2024-12-30 18:55 UTC, closed without merging