added Russian localization for environment_variables
fastapi/fastapi pull request #12436
Opened 2024-10-12 16:15 UTC by wisderfin

2024-10-12 16:44 UTC, kohiry reviewed
I am waiting for corrections.

2024-10-12 16:44 UTC, kohiry commented on docs/en/mkdocs.yml
> +  - media: (prefers-color-scheme)
Why you do this? U tested that?

2024-10-12 16:44 UTC, kohiry commented on docs/en/mkdocs.yml
> -  # - navigation.instant.preview
Ты действительно считаешь что обязательно было убирать комменты? 
Уверен что их просто так комментировали?

2024-10-12 16:44 UTC, kohiry commented on docs/en/mkdocs.yml
> +  abbr: null
Зачем null?

2024-10-12 16:44 UTC, kohiry commented on docs/en/mkdocs.yml
> +      - icon: material/emoticon-happy-outline
Почему ты вообще это правил? Ты уверен что не сломал yml файл?

2024-10-12 16:44 UTC, kohiry commented on docs/en/mkdocs.yml
>    name: material
Почему ты правил mkdocs английский вообще... Даже не русскиий

2024-10-12 16:44 UTC, kohiry commented on docs/ru/docs/environment-variables.md
> +Вы можете **создавать** и использовать переменные окружения в **оболочке (терминале)**, не прибегая к помощи Python:
Слишком много Вы можете. Чувствуется машинный перевод. Попробуй перефразировать, к примеру: 

"Можно", "Есть возможность" и т.п.

2024-10-12 16:44 UTC, kohiry commented on docs/ru/docs/environment-variables.md
> +// Вы можете создать переменную окружения MY_NAME с помощью
^

2024-10-12 16:44 UTC, kohiry commented on docs/ru/docs/environment-variables.md
> +// Затем вы можете использовать его с другими программами, например
^

2024-10-12 16:44 UTC, kohiry commented on docs/ru/docs/environment-variables.md
> +// Создайте переменную окружения MY_NAME
^

2024-10-12 16:44 UTC, kohiry commented on docs/ru/docs/environment-variables.md
> +Вы также можете создавать переменные окружения **вне** Python, в терминале (или любым другим способом), а затем **читать их в Python**.
^

2024-10-12 16:44 UTC, kohiry commented on docs/ru/docs/environment-variables.md
> +Например, у вас может быть файл `main.py`:
"..у вас есть.." или как то так, суди по контексту.

2024-10-12 16:44 UTC, kohiry commented on docs/ru/docs/environment-variables.md
> +Затем вы можете вызвать эту программу на Python:
^

2024-10-12 16:44 UTC, kohiry commented on docs/ru/docs/environment-variables.md
> +// Теперь она может прочитать переменную окружения
"теперь она прочитает.."

2024-10-12 16:44 UTC, kohiry commented on docs/ru/docs/environment-variables.md
> +Подробнее об использовании переменных окружения для работы с **настройками приложения** вы узнаете в [Advanced User Guide - Settings and Environment Variables](./advanced/settings.md){.internal-link
Мог бы название главы и перевести

2024-10-12 16:44 UTC, kohiry commented on docs/ru/docs/environment-variables.md
> +Эта информация будет полезна при изучении [Virtual Environments](virtual-environments.md){.internal-link target=_blank}.
Same, переведи главу

2024-10-12 16:44 UTC, kohiry commented on docs/ru/docs/environment-variables.md
> +Подробнее о них вы также можете прочитать в <a href="https://en.wikipedia.org/wiki/Environment_variable" class="external-link" target="_blank">Wikipedia for Environment Variable</a>.
same

2024-10-12 16:44 UTC, kohiry commented on docs/ru/docs/environment-variables.md
> +Например, эта информация понадобится вам в следующем разделе, посвященном [Virtual Environments](virtual-environments.md).
same

2024-10-12 18:51 UTC, wisderfin commented on docs/en/mkdocs.yml
> +  - media: (prefers-color-scheme)
Thank you very much, corrected

2024-10-12 18:51 UTC, wisderfin commented on docs/en/mkdocs.yml
> -  # - navigation.instant.preview
Thank you very much, corrected

2024-10-12 18:51 UTC, wisderfin commented on docs/en/mkdocs.yml
> +  abbr: null
Thank you very much, corrected

2024-10-12 18:51 UTC, wisderfin commented on docs/en/mkdocs.yml
> +      - icon: material/emoticon-happy-outline
Thank you very much, corrected

2024-10-12 18:51 UTC, wisderfin commented on docs/en/mkdocs.yml
>    name: material
Thank you very much, corrected

2024-10-12 18:52 UTC, wisderfin commented on docs/ru/docs/environment-variables.md
> +Эта информация будет полезна при изучении [Virtual Environments](virtual-environments.md){.internal-link target=_blank}.
Thank you very much, corrected

2024-10-12 18:52 UTC, wisderfin commented on docs/ru/docs/environment-variables.md
> +Подробнее об использовании переменных окружения для работы с **настройками приложения** вы узнаете в [Advanced User Guide - Settings and Environment Variables](./advanced/settings.md){.internal-link
Thank you very much, corrected

2024-10-12 18:52 UTC, wisderfin commented on docs/ru/docs/environment-variables.md
> +Подробнее о них вы также можете прочитать в <a href="https://en.wikipedia.org/wiki/Environment_variable" class="external-link" target="_blank">Wikipedia for Environment Variable</a>.
Thank you very much, corrected

2024-10-12 18:52 UTC, wisderfin commented on docs/ru/docs/environment-variables.md
> +Например, эта информация понадобится вам в следующем разделе, посвященном [Virtual Environments](virtual-environments.md).
Thank you very much, corrected

2024-10-12 18:52 UTC, wisderfin commented on docs/ru/docs/environment-variables.md
> +Вы можете **создавать** и использовать переменные окружения в **оболочке (терминале)**, не прибегая к помощи Python:
Thank you very much, corrected

2024-10-12 18:52 UTC, wisderfin commented on docs/ru/docs/environment-variables.md
> +// Вы можете создать переменную окружения MY_NAME с помощью
Thank you very much, corrected

2024-10-12 18:52 UTC, wisderfin commented on docs/ru/docs/environment-variables.md
> +// Затем вы можете использовать его с другими программами, например
Thank you very much, corrected

2024-10-12 18:52 UTC, wisderfin commented on docs/ru/docs/environment-variables.md
> +// Создайте переменную окружения MY_NAME
Thank you very much, corrected

2024-10-12 18:53 UTC, wisderfin commented on docs/ru/docs/environment-variables.md
> +Вы также можете создавать переменные окружения **вне** Python, в терминале (или любым другим способом), а затем **читать их в Python**.
Thank you very much, corrected

2024-10-12 18:53 UTC, wisderfin commented on docs/ru/docs/environment-variables.md
> +Например, у вас может быть файл `main.py`:
Thank you very much, corrected

2024-10-12 18:53 UTC, wisderfin commented on docs/ru/docs/environment-variables.md
> +Затем вы можете вызвать эту программу на Python:
Thank you very much, corrected

2024-10-12 18:55 UTC, wisderfin reviewed
Self-checked, waiting for confirmation from the community

2024-10-12 19:20 UTC, kohiry commented
> Self-checked, waiting for confirmation from the community
All fine.

2024-10-13 10:30 UTC, gitgernit requested changes
Decent but has some major mistakes.

2024-10-13 10:30 UTC, gitgernit commented on docs/ru/docs/environment-variables.md
> +Так же существует возможность создания переменных окружения **вне** Python, в терминале (или любым другим способом), а затем **читать их в Python**.
It's "а затем **чтения их в Python**", not "а затем **читать их в Python**".

2024-10-13 10:30 UTC, gitgernit commented on docs/ru/docs/environment-variables.md
> +## `PATH` Environment Variable
Is there a reason why you left that header untranslated?

2024-10-13 10:30 UTC, gitgernit commented on docs/ru/docs/environment-variables.md
> +Эта информация будет полезна при изучении [Виртуального окружения](virtual-environments.md){.internal-link target=_blank}.
Should be plural: "[Виртуальных окружений]", not "[Виртуального окружения]"

2024-10-13 10:30 UTC, gitgernit commented on docs/ru/docs/environment-variables.md
> +Благодаря этому вы должны иметь базовое представление о том, что такое **переменные окружения** и как их использовать в Python.
IMHO it's better as "что такое **переменные окружения** и как использовать их в Python.", not "что такое **переменные окружения** и как их использовать в Python.". Edit at your discretion.

2024-10-13 10:30 UTC, gitgernit commented on docs/ru/docs/environment-variables.md
> +Например, эта информация понадобится вам в следующем разделе, посвященном [Вертуальным окружениям](virtual-environments.md).
It's "[Виртуальным окружениям]", not "[Вертуальным окружениям]".

2024-10-13 10:30 UTC, gitgernit commented on docs/ru/docs/environment-variables.md
> +Во многих случаях не очень очевидно, как переменные окружения могут быть полезны и применимы сразу же. Но они постоянно появляются в различных сценариях разработки, поэтому знать о них полезно.
I believe "right away" serves as an addition to "not very obvious", as "In many cases it's not very obvious right away", so the correct translation would be something like "Во многих случаях не всегда очевидно, как переменные окружения могут быть полезны и применимы."

2024-10-14 10:57 UTC, gitgernit requested changes
Much better but still has some typos left. Thanks!

2024-10-14 10:57 UTC, gitgernit commented on docs/ru/docs/environment-variables.md
> +Так же существует возможность создания переменных окружения **вне** Python, в терминале (или любым другим способом), а затем **читения их в Python**.
"чтения", not "читения".
```suggestion
Так же существует возможность создания переменных окружения **вне** Python, в терминале (или любым другим способом), а затем **чтения их в Python**.
```

2024-10-14 10:57 UTC, gitgernit commented on docs/ru/docs/environment-variables.md
> +Эта информация будет полезна при изучении [Виртуальых окружений](virtual-environments.md){.internal-link target=_blank}.
I think you missed an "н".
```suggestion
Эта информация будет полезна при изучении [Виртуальных окружений](virtual-environments.md){.internal-link target=_blank}.
```

2024-10-14 11:19 UTC, s111d commented
Качество, нраицца.

2024-10-14 22:42 UTC, wisderfin commented
I apologize to all those who pointed out silly mistakes to me. I'm really embarrassed.

2024-10-14 22:48 UTC, gitgernit approved these changes
Seems fine now. Good job! Thanks!

2024-10-15 06:50 UTC, kohiry approved these changes

2024-10-15 11:38 UTC, merged

2024-10-15 11:39 UTC, alejsdev commented
Thanks for your contribution! @wisderfin :nerd_face: 

And thanks for the reviews @kohiry @gitgernit :mag: