🌐 Add Portuguese translation for `docs/pt/docs/tutorial/header-param-models.md`
fastapi/fastapi pull request #12437
Opened 2024-10-12 19:13 UTC by Joao-Pedro-P-Holanda

2024-10-14 09:54 UTC, nazarepiedady approved these changes

2024-10-14 10:30 UTC, ceb10n requested changes
Great work! ✨ 

Just missed the `tip` translations :D

2024-10-14 10:30 UTC, ceb10n commented on docs/pt/docs/tutorial/header-param-models.md
> +/// tip
missed the tip translation:

/// tip | Dica

2024-10-14 10:30 UTC, ceb10n commented on docs/pt/docs/tutorial/header-param-models.md
> +/// tip
missed the tip translation:

/// tip | Dica

2024-10-14 10:30 UTC, ceb10n commented on docs/pt/docs/tutorial/header-param-models.md
> +/// tip
missed the tip translation:

/// tip | Dica

2024-10-14 10:30 UTC, ceb10n commented on docs/pt/docs/tutorial/header-param-models.md
> +/// tip
missed the tip translation:

/// tip | Dica

2024-10-14 10:30 UTC, ceb10n commented on docs/pt/docs/tutorial/header-param-models.md
> +/// tip
missed the tip translation:

/// tip | Dica

2024-10-14 10:30 UTC, ceb10n commented on docs/pt/docs/tutorial/header-param-models.md
> +/// tip
missed the tip translation:

/// tip | Dica

2024-10-14 17:30 UTC, Joao-Pedro-P-Holanda commented
Fixed @ceb10n, thanks for noticing!

2024-10-15 04:02 UTC, nazarepiedady approved these changes

2024-10-15 04:03 UTC, nazarepiedady commented
@ceb10n, are the corrections good enough to approve the whole pull request?

2024-10-15 08:24 UTC, andersonrocha0 approved these changes

2024-10-15 08:24 UTC, andersonrocha0 commented on docs/pt/docs/tutorial/header-param-models.md
> +O **FastAPI** irá **extrair** os dados de **cada campo** a partir dos **cabeçalhos** da requisição e te retornará o modelo do Pydantic que você definiu.
**Suggestion:** Here you could use "extrairá" instead of "irá extrair"

2024-10-15 08:24 UTC, andersonrocha0 commented on docs/pt/docs/tutorial/header-param-models.md
> +Por exemplo, se o cliente tentar enviar um cabeçalho `tool` com o valor `plumbus`, ele irá receber uma resposta de **erro** informando que o parâmetro do cabeçalho `tool` não é permitido:
**Suggestion:** Here you could use "receberá" instead of "irá receber"

2024-10-15 08:24 UTC, andersonrocha0 commented
@Joao-Pedro-P-Holanda I gave you some suggestions. BTW, I already approved the PR.

2024-10-15 10:04 UTC, ceb10n approved these changes
✨

2024-10-15 16:48 UTC, cassiobotaro approved these changes

2024-10-22 20:41 UTC, merged

2024-10-22 20:41 UTC, alejsdev commented
Thanks for your help! @Joao-Pedro-P-Holanda :partying_face: 

And thanks to all for the reviews :sparkles: