docs(ru): Create & translate docs/tutorial/query-param-models.md
fastapi/fastapi pull request #12445
Opened 2024-10-13 16:23 UTC by gitgernit

Translated the [Query Parameter Models](https://fastapi.tiangolo.com/tutorial/query-param-models/) page to Russian. Looking forward to feedback & reviews!

2024-11-23 21:29 UTC, Xewus requested changes

2024-11-25 09:38 UTC, gitgernit commented on docs/ru/docs/tutorial/query-param-models.md
> +Спойлер: вы также можете использовать Pydantic-модели для группировки куки и заголовков, но об этом вы прочитаете позже. 🤫
Вы правы, "кук" более наглядно обозначает множественное число. Благодарю за помощь!

2024-11-25 19:16 UTC, Xewus approved these changes

2024-11-25 22:48 UTC, alv2017 approved these changes

2024-11-25 22:48 UTC, alv2017 commented on docs/ru/docs/tutorial/query-param-models.md
> +В некоторых случаях (не особо часто встречающихся) вам может понадобиться **ограничить** query-параметры, которые вы хотите получать.
```suggestion
В некоторых случаях (не особо часто встречающихся) вам может понадобиться **ограничить** query-параметры, которые вы хотите получить.
```

2024-11-25 22:48 UTC, alv2017 commented on docs/ru/docs/tutorial/query-param-models.md
> +Вы можете сконфигурировать Pydantic-модель так, чтобы `forbid` (запретить) все `extra` (лишние) поля.
```suggestion
Вы можете сконфигурировать Pydantic-модель так, чтобы запретить (`forbid`) все дополнительные (`extra`) поля.
```

2024-11-25 22:48 UTC, alv2017 commented on docs/ru/docs/tutorial/query-param-models.md
> +Если клиент попробует отправить **лишние** данные в **query-параметрах**, то в ответ он получит **ошибку**.
```suggestion
Если клиент попробует отправить **дополнительные** данные в **query-параметрах**, то в ответ он получит **ошибку**.
```

2024-11-25 22:48 UTC, alv2017 commented on docs/ru/docs/tutorial/query-param-models.md
> +Спойлер: вы также можете использовать Pydantic-модели для группировки кук и заголовков, но об этом вы прочитаете позже. 🤫
```suggestion
Спойлер: вы также можете использовать Pydantic-модели для группировки кук (cookies) и заголовков (headers), но об этом вы прочитаете позже. 🤫
```

2024-11-25 22:48 UTC, alv2017 commented on docs/ru/docs/tutorial/query-param-models.md
> +Вы можете использовать **Pydantic-модели** для группировки и получения **query-параметров** в **FastAPI**. 😎
```suggestion
Вы можете использовать **Pydantic-модели** для объявления **query-параметров** в **FastAPI**. 😎
```

2024-11-25 22:48 UTC, alv2017 commented on docs/ru/docs/tutorial/query-param-models.md
> +Если у вас есть группа связанных **query-параметров**, то вы можете создать для них одну **Pydantic-модель**.
```suggestion
Если у вас есть группа связанных **query-параметров**, то вы можете объединить их в одну **Pydantic-модель**.
```

2024-11-25 22:48 UTC, alv2017 commented on docs/ru/docs/tutorial/query-param-models.md
> +Это позволит вам **переиспользовать модель** в **разных местах**, устанавливать валидаторы и метаданные, в том числе для сразу всех параметров, в одном месте. 😎
```suggestion
Это позволит вам **переиспользовать модель** в **разных местах**,  а также объявить валидации и метаданные в одном месте для всех параметров. 😎
```

2024-11-25 22:49 UTC, alv2017 approved these changes
Добавила поправки (на твое усмотрение)

2024-11-26 21:36 UTC, merged

2024-11-26 21:38 UTC, alejsdev commented
Thank you! @gitgernit :rocket: :nerd_face: 
And thanks for the reviews @Xewus @alv2017 :mag: