🌐 Add Portuguese translation for docs/pt/docs/how-to/extending-openapi.md 9
fastapi/fastapi pull request #12470
Opened 2024-10-16 12:59 UTC by ilacftemp

2024-10-16 13:49 UTC, nazarepiedady approved these changes

2024-10-18 03:08 UTC, nazarepiedady commented
@cassiobotaro, could you do the kindness of reviewing this pull request?

2024-10-18 03:11 UTC, cassiobotaro approved these changes

2024-10-18 11:22 UTC, ceb10n requested changes
✨

2024-10-18 11:22 UTC, ceb10n commented on docs/pt/docs/how-to/extending-openapi.md
> +/// info
You can add a translation to the admonition here:

```
/// info | Informação
```

2024-10-18 11:22 UTC, ceb10n commented on docs/pt/docs/how-to/extending-openapi.md
> +### Normal **FastAPI**
It's a really strange phrase to translate, but I think it would be "FastAPI Normal" instead of "Normal FastAPI"

2024-10-18 12:42 UTC, ilacftemp commented
I fixed the page according to your suggestions @ceb10n . Thanks for the help!

2024-10-22 17:40 UTC, merged