Add Traditional Chinese translation for docs/zh-hant/docs/async.md
fastapi/fastapi pull request #12489
Opened 2024-10-18 13:28 UTC by ILoveSorasakiHina

2024-10-20 05:01 UTC, codingjenny commented on docs/zh-hant/docs/async.md
> +這與 FastAPI 為你呼叫*路徑操作函數*和依賴項的邏輯有所不同。
有 * 的 markdown 出現，前後如果是中文的話，要空一格，在網頁上呈現才會是斜體。

2024-10-20 07:33 UTC, codingjenny commented on docs/zh-hant/docs/async.md
> +無論如何，在上述哪種情況下，FastAPI 仍將以異步方式運行，並且速度非常快。
```suggestion
無論如何，在上述哪種情況下，FastAPI 仍將以非同步方式運行，並且速度非常快。
```

2024-10-20 07:33 UTC, codingjenny commented on docs/zh-hant/docs/async.md
> +現代版本的 Python 支持使用 **"協程"** 的 **`async` 和 `await`** 語法來寫 **"異步程式碼"**。
```suggestion
現代版本的 Python 支援使用 **「協程」** 的 **`async` 和 `await`** 語法來寫 **「非同步程式碼」**。
```
「支持」是簡中用法

2024-10-20 07:33 UTC, codingjenny commented on docs/zh-hant/docs/async.md
> +* **異步程式碼**
```suggestion
* **非同步程式碼**
```

2024-10-20 07:33 UTC, codingjenny commented on docs/zh-hant/docs/async.md
> +## 異步程式碼
```suggestion
## 非同步程式碼
```

2024-10-20 07:33 UTC, codingjenny commented on docs/zh-hant/docs/async.md
> +異步程式碼僅意味著程式語言 💬 有辦法告訴電腦/程式 🤖 在程式碼中的某個點，它 🤖 需要等待某些事情完成。讓我們假設這些事情被稱為 "慢速檔案"📝。
```suggestion
非同步程式碼僅意味著程式語言 💬 有辦法告訴電腦/程式 🤖 在程式碼中的某個點，它 🤖 需要等待某些事情完成。讓我們假設這些事情被稱為「慢速檔案」📝。
```

2024-10-20 07:33 UTC, codingjenny commented on docs/zh-hant/docs/async.md
> +因此，在等待 "慢速檔案"📝 完成的這段時間，電腦可以去處理一些其他工作。
```suggestion
因此，在等待「慢速檔案」📝 完成的這段時間，電腦可以去處理一些其他工作。
```

2024-10-20 07:33 UTC, codingjenny commented on docs/zh-hant/docs/async.md
> +這個 "等待其他事情" 通常指的是一些相對較慢的（與處理器和 RAM 記憶體的速度相比）的 <abbr title="Input and Output">I/O</abbr> 操作，比如說：
```suggestion
接下來，它 🤖 完成第一個工作（例如我們的「慢速檔案」📝）並繼續執行相關的所有操作。

這個「等待其他事情」通常指的是一些相對較慢的（與處理器和 RAM 記憶體的速度相比）的 <abbr title="Input and Output">I/O</abbr> 操作，比如說：
```

2024-10-20 07:33 UTC, codingjenny commented on docs/zh-hant/docs/async.md
> +* 遠端 API 調用
```suggestion
* 通過網路傳送來自用戶端的資料
* 從網路接收來自用戶端的資料
* 從磁碟讀取檔案內容
* 將內容寫入磁碟
* 遠端 API 操作
```

2024-10-20 07:33 UTC, codingjenny commented on docs/zh-hant/docs/async.md
> +之所以稱為 "異步"，是因為電腦/程式不需要與那些耗時的任務 "同步"，等待任務完成的精確時間，然後才能取得結果並繼續工作。
```suggestion
之所以稱為「非同步」，是因為電腦/程式不需要與那些耗時的任務「同步」，等待任務完成的精確時間，然後才能取得結果並繼續工作。
```

2024-10-20 07:33 UTC, codingjenny commented on docs/zh-hant/docs/async.md
> +相對於 "異步"（asynchronous），"同步"（synchronous）也常被稱作 "順序性"（sequential），因為電腦/程式會依序執行所有步驟，即便這些步驟涉及等待，才會切換到其他任務。
```suggestion
相反地，非同步系統在任務完成後，可以讓任務稍微等一下（幾微秒），等待電腦/程式完成手頭上的其他工作，然後再回來取得結果繼續進行。

相對於「非同步」（asynchronous），「同步」（synchronous）也常被稱作「順序性」（sequential），因為電腦/程式會依序執行所有步驟，即便這些步驟涉及等待，才會切換到其他任務。
```

2024-10-20 07:33 UTC, codingjenny commented on docs/zh-hant/docs/async.md
> +上述異步程式碼的概念有時也被稱為 "並行"，它不同於 "平行"。
```suggestion
上述非同步程式碼的概念有時也被稱為「並行」，它不同於「平行」。
```

2024-10-25 05:25 UTC, ILoveSorasakiHina commented on docs/zh-hant/docs/async.md
> +有關路徑操作函數的 async def 語法的細節與異步(asynchronous)程式碼、並行(concurrency)與平行(parallelism)的一些背景知識。
感謝提醒，我腦子一直跑出激活函數，下意識就翻成函數，仔細想想激活函數確實是數學的函數而非程式的函式

2024-10-25 08:50 UTC, mattwang44 commented on docs/zh-hant/docs/async.md
> +這與 FastAPI 為你呼叫*路徑操作函數*和依賴項的邏輯有所不同。
update 一下，最近這件事被改掉囉，中文字之間不需空格
https://github.com/fastapi/fastapi/pull/12509

2024-10-25 09:08 UTC, codingjenny commented on docs/zh-hant/docs/async.md
> +有關路徑操作函數的 async def 語法的細節與異步(asynchronous)程式碼、並行(concurrency)與平行(parallelism)的一些背景知識。
不會哈哈，我一開始也是寫「函數」，是 @mattwang44 之前提點我的，現學現賣哈哈！

2024-10-25 09:10 UTC, mattwang44 commented on docs/zh-hant/docs/async.md
> +這就是為什麼對於 Web API 來說，使用異步程式碼 ⏸🔀⏯ 是非常有意義的。
```suggestion
這就是為什麼對於 Web API 來說，使用非同步程式碼 ⏸🔀⏯ 是非常有意義的。
```

2024-10-25 09:10 UTC, mattwang44 commented on docs/zh-hant/docs/async.md
> +這種類型的異步性正是 NodeJS 成功的原因（儘管 NodeJS 不是平行的），這也是 Go 語言作為編程語言的一個強大優勢。
```suggestion
這種類型的非同步性正是 NodeJS 成功的原因（儘管 NodeJS 不是平行的），這也是 Go 語言作為程式語言的一個強大優勢。
```

2024-10-25 09:10 UTC, mattwang44 commented on docs/zh-hant/docs/async.md
> +無論輪流執行與否(並行)，你都需要相同的工時完成任務，同時需要執行相同工作量。
```suggestion
無論輪流執行與否（並行），你都需要相同的工時完成任務，同時需要執行相同工作量。
```

2024-10-25 09:10 UTC, mattwang44 commented on docs/zh-hant/docs/async.md
> +* **電腦視覺**: 一張圖片由數百萬個像素組成，每個像素有3個值/顏色，處理這些像素通常需要同時進行大量計算;
```suggestion
* **電腦視覺**：一張圖片由數百萬個像素組成，每個像素有 3 個值/顏色，處理這些像素通常需要同時進行大量計算；
```

2024-10-25 09:10 UTC, mattwang44 commented on docs/zh-hant/docs/async.md
> +但你也可以利用平行與多行程(multiprocessing)（讓多個行程同時運行）的優勢來處理機器學習系統中的 **CPU 密集型** 工作。
```suggestion
但你也可以利用平行與多行程 (multiprocessing)（讓多個行程同時運行）的優勢來處理機器學習系統中的 **CPU 密集型**工作。
```

2024-10-25 09:10 UTC, mattwang44 commented on docs/zh-hant/docs/async.md
> +想了解如何在生產環境中實現這種平行性，請參見 [Deployment](deployment/index.md){.internal-link target=_blank}。
`Deployment` 要翻譯？

2024-10-25 09:10 UTC, mattwang44 commented on docs/zh-hant/docs/async.md
> +現代 Python 版本提供一種非常直觀的方式定義異步程式碼。這使得它看起來就像正常的「順序」程式碼，並在適當的時機「等待」。
```suggestion
現代 Python 版本提供一種非常直觀的方式定義非同步程式碼。這使得它看起來就像正常的「順序」程式碼，並在適當的時機「等待」。
```

2024-10-25 09:10 UTC, mattwang44 commented on docs/zh-hant/docs/async.md
> +當某個操作需要等待才能返回結果，並且支援這些新的 Python 特性時，你可以像這樣編寫程式碼：
```suggestion
當某個操作需要等待才能回傳結果，並且支援這些新的 Python 特性時，你可以像這樣編寫程式碼：
```

2024-10-25 09:10 UTC, mattwang44 commented on docs/zh-hant/docs/async.md
> +這裡的關鍵是 `await`。它告訴 Python 必須等待 ⏸ `get_burgers(2)` 完成它的工作 🕙， 然後將結果存儲在 `burgers` 中。如此，Python 就可以在此期間去處理其他事情 🔀 ⏯ （例如接收另一個請求）。
```suggestion
這裡的關鍵是 `await`。它告訴 Python 必須等待 ⏸ `get_burgers(2)` 完成它的工作 🕙， 然後將結果儲存在 `burgers` 中。如此，Python 就可以在此期間去處理其他事情 🔀 ⏯ （例如接收另一個請求）。
```

2024-10-25 09:10 UTC, mattwang44 commented on docs/zh-hant/docs/async.md
> +要讓 `await` 運作，它必須位於支持異步功能的函式內。為此，只需使用 `async def` 宣告函式：
```suggestion
要讓 `await` 運作，它必須位於支持非同步功能的函式內。為此，只需使用 `async def` 宣告函式：
```

2024-10-25 09:10 UTC, mattwang44 commented on docs/zh-hant/docs/async.md
> +### 編寫自己的異步程式碼
```suggestion
### 編寫自己的非同步程式碼
```

2024-10-25 09:10 UTC, mattwang44 commented on docs/zh-hant/docs/async.md
> +Starlette （和 **FastAPI**） 是基於 <a href="https://anyio.readthedocs.io/en/stable/" class="external-link" target="_blank">AnyIO</a> 實現的，這使得它們與 Python 標準庫兼容 <a href="https://docs.python.org/3/library/asyn
```suggestion
Starlette（和 **FastAPI**）是基於 <a href="https://anyio.readthedocs.io/en/stable/" class="external-link" target="_blank">AnyIO</a> 實作的，這使得它們與 Python 標準函式庫相容 <a href="https://docs.python.org/3/library/asyncio-task.html" class="external-link" target="_blank">asyncio</a> 和 <a href="https://trio.readthedocs.io/en/stable/" class="external-link" target="_blank">Trio</a>。
```

2024-10-25 09:10 UTC, mattwang44 commented on docs/zh-hant/docs/async.md
> +在較舊的 NodeJS / 瀏覽器 JavaScript 中，你會使用「回調」，這可能會導致 <a href="http://callbackhell.com/" class="external-link" target="_blank">回調地獄</a>。
|lang|call | callback|
|:-:|:-:|:-:|
|繁中|呼叫|回呼|
|簡中|調用|回調|

```suggestion
在較舊的 NodeJS / 瀏覽器 JavaScript 中，你會使用「回呼」，這可能會導致<a href="http://callbackhell.com/" class="external-link" target="_blank">回呼地獄</a>。
```

2024-10-25 09:10 UTC, mattwang44 commented on docs/zh-hant/docs/async.md
> +**協程**只是 `async def` 函式所返回的非常特殊的事物名稱。Python 知道它是一個類似函式的東西，可以啟動它，並且在某個時刻它會結束，但它也可能在內部暫停 ⏸，只要遇到 `await`。
```suggestion
**協程**只是 `async def` 函式所回傳的非常特殊的事物名稱。Python 知道它是一個類似函式的東西，可以啟動它，並且在某個時刻它會結束，但它也可能在內部暫停 ⏸，只要遇到 `await`。
```

2024-10-25 09:10 UTC, mattwang44 commented on docs/zh-hant/docs/async.md
> +如果你來自於其他不以這種方式運作的非同步框架，而且你習慣於使用普通的 `def` 定義僅進行簡單計算的路徑操作函式，目的是獲得微小的性能增益（大約100奈秒），請注意，在 FastAPI 中，效果會完全相反。在這些情況下，最好使用 `async def`，除非你的路徑操作函式執行阻塞的 <abbr title="輸入/輸出：磁碟讀寫或網路通訊">I/O</abbr> 的代码。
```suggestion
如果你來自於其他不以這種方式運作的非同步框架，而且你習慣於使用普通的 `def` 定義僅進行簡單計算的路徑操作函式，目的是獲得微小的性能增益（大約 100 奈秒），請注意，在 FastAPI 中，效果會完全相反。在這些情況下，最好使用 `async def`，除非你的路徑操作函式執行阻塞的 <abbr title="輸入/輸出：磁碟讀寫或網路通訊">I/O</abbr> 的程式碼。
```

2024-10-25 09:10 UTC, mattwang44 commented on docs/zh-hant/docs/async.md
> +### 依賴項(Dependencies)
翻譯尚未確定
https://github.com/fastapi/fastapi/pull/12441#discussion_r1804535440

2024-10-25 09:10 UTC, mattwang44 commented on docs/zh-hant/docs/async.md
> +你可以直接呼叫任何使用 `def` 或 `async def` 創建的其他輔助函式，FastAPI 不會影響你呼叫它們的方式。
```suggestion
你可以直接呼叫任何使用 `def` 或 `async def` 建立的其他輔助函式，FastAPI 不會影響你呼叫它們的方式。
```

2024-10-25 09:10 UTC, mattwang44 commented on docs/zh-hant/docs/async.md
> +如果你的輔助函式是用 `def` 宣告的，它將會被直接呼叫（按照你在程式碼中撰寫的方式），而不是在執行緒池中。如果該函數是用 `async def` 宣告，那麼你在呼叫時應該使用 `await` 等待其結果。
```suggestion
如果你的輔助函式是用 `def` 宣告的，它將會被直接呼叫（按照你在程式碼中撰寫的方式），而不是在執行緒池中。如果該函式是用 `async def` 宣告，那麼你在呼叫時應該使用 `await` 等待其結果。
```

2024-10-25 09:11 UTC, codingjenny commented on docs/zh-hant/docs/async.md
> +這與 FastAPI 為你呼叫*路徑操作函數*和依賴項的邏輯有所不同。
沒錯！再麻煩 @ILoveSorasakiHina 幫忙把有空格的地方都刪除，謝謝！

2024-10-25 14:58 UTC, codingjenny commented on docs/zh-hant/docs/async.md
> +然後，當輪到你時，你開始做真正「有生產力」的工作，處理菜單，決定你想要什麼，替戀人選擇餐點，付款，確認你給了正確的賬單或信用卡，檢查你是否被正確收費，確認訂單中的項目是否正確等等。
```suggestion
然後，當輪到你時，你開始做真正「有生產力」的工作，處理菜單，決定你想要什麼，替戀人選擇餐點，付款，確認你給了正確的帳單或信用卡，檢查你是否被正確收費，確認訂單中的項目是否正確等等。
```

2024-10-25 14:58 UTC, codingjenny commented on docs/zh-hant/docs/async.md
> +然後，當輪到你時，你開始做真正「有生產力」的工作，處理菜單，決定你想要什麼，替戀人選擇餐點，付款，確認你給了正確的賬單或信用卡，檢查你是否被正確收費，確認訂單中的項目是否正確等等。
雖然「帳」和「賬」為異體字，但慣用的用法還是「帳單」。

2024-10-25 14:58 UTC, codingjenny commented on docs/zh-hant/docs/async.md
> +一個更"現實"的例子，想像一間銀行。
```suggestion
一個更「現實」的例子，想像一間銀行。
```

2024-10-28 13:10 UTC, ILoveSorasakiHina commented
@mattwang44  @codingjenny  除了有爭議的部分，其他地方皆已更新完畢，感謝兩位的review。如有其他需要調整的地方，請務必再提醒我。

2024-11-08 01:30 UTC, ILoveSorasakiHina commented on docs/zh-hant/docs/async.md
> +### 依賴項(Dependencies)
根據討論，維持原翻譯。

2024-11-09 11:37 UTC, celestywang requested changes

2024-11-09 11:37 UTC, celestywang commented on docs/zh-hant/docs/async.md
> +**協程**只是 `async def` 函式所回傳的非常特殊的事物名稱。Python 知道它是一個類似函式的東西，可以啟動它，並且在某個時刻它會結束，但它也可能在內部暫停 ⏸，只要遇到 `await`。
I think you need a space after `**協程**`
![image](https://github.com/user-attachments/assets/96557c3c-e8b6-4a73-b41d-09f61f5931b6)

2024-11-10 03:49 UTC, codingjenny commented on docs/zh-hant/docs/async.md
> +**協程**只是 `async def` 函式所回傳的非常特殊的事物名稱。Python 知道它是一個類似函式的東西，可以啟動它，並且在某個時刻它會結束，但它也可能在內部暫停 ⏸，只要遇到 `await`。
The rendering issue is fixed in #12509

2024-11-10 03:49 UTC, codingjenny approved these changes

2024-11-10 15:05 UTC, celestywang approved these changes

2024-11-10 15:23 UTC, codingjenny commented on docs/zh-hant/docs/async.md
> +函數
```suggestion

```

2024-11-10 15:36 UTC, codingjenny commented on docs/zh-hant/docs/async.md
> +函數
Just fix this, and others LGTM.

2024-11-13 10:04 UTC, mattwang44 approved these changes

2024-11-15 08:58 UTC, closed without merging

2024-11-15 09:07 UTC, ILoveSorasakiHina commented
hi @alejsdev 

I hope this message finds you well. I recently realized that I accidentally deleted my forked repository, which contained the changes for this PR. I'm not sure if this PR has already been merged or if further adjustments are needed from my side.

If this PR is still under review, I’d be happy to re-submit the changes from a new fork. Please let me know how I can assist in moving this forward.

Apologies for the inconvenience, and thank you for your understanding!

Best regards

ILoveSorasakiHina