Portuguese translation for the history-design-future page
fastapi/fastapi pull request #1249
Opened 2020-04-12 22:50 UTC by marcosmmb

This PR translates the history-design-future.md and add this page to the mkdocs.yml file.

2020-04-12 23:38 UTC, cassiobotaro approved these changes
All looks good, except for a little NIT.

2020-04-12 23:38 UTC, cassiobotaro commented on docs/pt/docs/history-design-future.md
> +# História, design and futuro
```suggestion
# História, design e futuro
```

2020-04-15 01:49 UTC, Serrones requested changes

2020-04-15 01:49 UTC, Serrones commented on docs/pt/docs/history-design-future.md
> +Dessa forma eu pude encontrar a melhor maneira de reduzir duplicação de código o máximo possível, ter completação de texto em todos os lugares, conferência de tipos e erros etc.
Colocar vírgula antes de `etc`

2020-04-15 03:17 UTC, marcosmmb commented on docs/pt/docs/history-design-future.md
> +Dessa forma eu pude encontrar a melhor maneira de reduzir duplicação de código o máximo possível, ter completação de texto em todos os lugares, conferência de tipos e erros etc.
De acordo com o dicionário Houaiss, o uso de `etc.` nesse contexto não necessita da vírgula já que é uma abreviação para o latim "et coetera", significando "e outras coisas".

2020-04-15 21:44 UTC, Serrones approved these changes
LGTM

2020-05-16 12:46 UTC, merged

2020-05-16 12:46 UTC, tiangolo commented
Great! Thanks for your contribution @marcosmmb ! :clap: :bow: :rocket: 

And thanks @cassiobotaro and @Serrones for your reviews! :muscle: :nerd_face: :cake: