spanish translation for advanced/index.md
fastapi/fastapi pull request #1250
Opened 2020-04-13 03:09 UTC by jfunez

2020-04-14 14:58 UTC, mariacamilagl requested changes
Thank you for your work @jfunez ! 🚀 👍 

I suggested some minor changes. Mainly the change from "funcionalidades" to "características" so we can maintain consistency with the earlier translations.

2020-04-14 14:58 UTC, mariacamilagl commented on docs/es/docs/advanced/index.md
> +En las secciones siguientes verás otras opciones, configuraciones, y funcionalidades adicionales.
```suggestion
En las secciones siguientes verás otras opciones, configuraciones, y características adicionales.
```

2020-04-14 14:58 UTC, mariacamilagl commented on docs/es/docs/advanced/index.md
> +## Funcionalidades Adicionales
```suggestion
## Características Adicionales
```

2020-04-14 14:58 UTC, mariacamilagl commented on docs/es/docs/advanced/index.md
> +El [Tutorial - Guía de Usuario](../tutorial/){.internal-link target=_blank} principal debe ser suficiente para darte un paseo por todas las funcionalidades principales de **FastAPI**
```suggestion
El [Tutorial - Guía de Usuario](../tutorial/){.internal-link target=_blank} principal debe ser suficiente para darte un paseo por todas las características principales de **FastAPI**
```

2020-04-14 14:58 UTC, mariacamilagl commented on docs/es/docs/advanced/index.md
> +## Lea primero el Tutorial
```suggestion
## Lee primero el Tutorial
```

2020-04-14 14:58 UTC, mariacamilagl commented on docs/es/docs/advanced/index.md
> +Y en las siguientes secciones se asume que tu has leído y se asume que tu conoces las ideas principales.
```suggestion
Puedes continuar usando la mayoría de las características de **FastAPI** con el conocimiento del [Tutorial - Guía de Usuario](../tutorial/){.internal-link target=_blank} principal.

En las siguientes secciones se asume que lo has leído y conoces esas ideas principales.
```

2020-04-14 15:06 UTC, jfunez commented
thanks for the review @mariacamilagl 
I will adjust and review the other PRs I sent the apply your suggestions there also.

2020-04-16 02:13 UTC, AdrianDeAnda commented on docs/es/docs/advanced/index.md
> +## Lea primero el Tutorial
Maybe an infinitive verb would be more suited?

```suggestion
## Leer primero el Tutorial
```

2020-04-26 10:26 UTC, mariacamilagl approved these changes
Thank you for implementing the changes @jfunez ! 🚀

2020-05-16 12:58 UTC, merged

2020-05-16 12:58 UTC, tiangolo commented
Awesome! Thank you @jfunez ! :rocket: :tada: 

And thanks @AdrianDeAnda and @mariacamilagl for your reviews! :nerd_face: :memo: