spanish translation for advanced/path-operation-advanced-configuration.md
fastapi/fastapi pull request #1251
Opened 2020-04-13 03:14 UTC by jfunez

2020-04-26 12:27 UTC, mariacamilagl requested changes
Thanks for the translation, @jfunez  🚀 

I'm suggesting to leave all FastAPI specific terms, like path operations or path operation functions in English. They should be explained in earlier stages of the docs (like the beginner's tutorial) and this way we maintain consistency.

2020-04-26 12:27 UTC, mariacamilagl commented on docs/es/docs/advanced/path-operation-advanced-configuration.md
> +    Si llama manualmente a `app.openapi()`, debe actualizar el `operationId`s antes de eso.
```suggestion
    Si llamas manualmente a `app.openapi()`, debes actualizar el `operationId`s antes de hacerlo.
```

2020-04-26 12:27 UTC, mariacamilagl commented on docs/es/docs/advanced/path-operation-advanced-configuration.md
> +    Si hace esto, debes asegurarte de que cada una de tus *funciones de operación de camino* tenga un nombre único.
```suggestion
    Si haces esto, debes asegurarte de que cada una de tus *path operation  functions* tenga un nombre único.
```

2020-04-26 12:27 UTC, mariacamilagl commented on docs/es/docs/advanced/path-operation-advanced-configuration.md
> +Para excluir una *operación de camino* del esquema OpenAPI generado (y por tanto del la documentación generada automáticamente), use el parámetro `include_in_schema` y asigne el valor como `False`;
```suggestion
Para excluir una *path operation* del esquema OpenAPI generado (y por tanto del la documentación generada automáticamente), usa el parámetro `include_in_schema` y asigna el valor como `False`;
```

2020-04-26 12:27 UTC, mariacamilagl commented on docs/es/docs/advanced/path-operation-advanced-configuration.md
> +Puedes limitar las líneas usadas desde la docstring de una *operación de camino* para OpenAPI.
```suggestion
Puedes limitar las líneas usadas desde la docstring de una *path operation* para OpenAPI.
```

2020-04-26 12:27 UTC, mariacamilagl commented on docs/es/docs/advanced/path-operation-advanced-configuration.md
> +Adding an `\f` (an escaped "form feed" character) causes **FastAPI** to truncate the output used for OpenAPI at this point.
```suggestion

```

2021-07-04 12:44 UTC, mariacamilagl approved these changes
Thanks for your effort @jfunez!

2021-07-04 12:48 UTC, tiangolo commented
Awesome, thanks @jfunez! :coffee: :cake: 

And thanks @mariacamilagl for the reviews and corrections! :nerd_face: :coffee:

2021-07-04 12:49 UTC, merged