spanish translation for advanced/additional-status-codes.md
fastapi/fastapi pull request #1252
Opened 2020-04-13 03:18 UTC by jfunez

2020-04-26 12:37 UTC, mariacamilagl requested changes
Thanks for the translation @jfunez! 🚀 

Minor changes like the last ones.

2020-04-26 12:37 UTC, mariacamilagl commented on docs/es/docs/advanced/additional-status-codes.md
> +Por defecto, **FastAPI** retornará las respuestas utilizando una `JSONResponse`, poniendo el contenido que retornas en tu *operación de camino* dentro de esa `JSONResponse`.
```suggestion
Por defecto, **FastAPI** retornará las respuestas utilizando una `JSONResponse`, poniendo el contenido que retornas en tu *path operation* dentro de esa `JSONResponse`.
```

2020-04-26 12:37 UTC, mariacamilagl commented on docs/es/docs/advanced/additional-status-codes.md
> +Si tu quieres retornar códigos de estado adicionales además del principal, puedes hacerlo retornando directamente una `Response`, como una `JSONResponse`, y asignar directamente el código de estado a
```suggestion
Si quieres retornar códigos de estado adicionales además del principal, puedes hacerlo retornando directamente una `Response`, como una `JSONResponse`, y asignar directamente el código de estado adicional.
```

2020-04-26 12:37 UTC, mariacamilagl commented on docs/es/docs/advanced/additional-status-codes.md
> +Por ejemplo, digamos que tu quieres tener una *operación de camino* que permita actualizar ítems, y retornar códigos de estado HTTP 200 "OK" cuando sea satisfactorio.
```suggestion
Por ejemplo, digamos que quieres tener una *path operation* que permita actualizar ítems, y retornar códigos de estado HTTP 200 "OK" cuando sea satisfactorio.
```

2020-04-26 12:37 UTC, mariacamilagl commented on docs/es/docs/advanced/additional-status-codes.md
> +    Asegurate que la respuesta tenga los datos que tu quieras, y que los valores sean JSON válidos (si estás usando `JSONResponse`).
```suggestion
    Asegurate que la respuesta tenga los datos que quieras, y que los valores sean JSON válidos (si estás usando `JSONResponse`).
```

2020-04-26 12:37 UTC, mariacamilagl commented on docs/es/docs/advanced/additional-status-codes.md
> +Si tu quieres retornar adicionalmente códigos de estado y respuestas directamente, no estarán incluidas en el esquema OpenAPI (documentación de API), porque FastAPI no tiene una manera de conocer de
```suggestion
Si quieres retornar adicionalmente códigos de estado y respuestas directamente, no estarán incluidas en el esquema OpenAPI (documentación de API), porque FastAPI no tiene una manera de conocer de antemano lo que vas a retornar.
```

2020-04-26 12:37 UTC, mariacamilagl commented on docs/es/docs/advanced/additional-status-codes.md
> +Pero tu puedes documentar eso en tu código, usando [Respuestas Adicionales](additional-responses.md){.internal-link target=_blank}.
```suggestion
Pero puedes documentar eso en tu código, usando [Respuestas Adicionales](additional-responses.md){.internal-link target=_blank}.
```

2021-01-27 15:58 UTC, pedabraham reviewed
Hice una pequeña corrección.

2021-01-27 15:58 UTC, pedabraham commented on docs/es/docs/advanced/additional-status-codes.md
> +Utilizará el código de estado por defecto, o el que sea asignado en tu *operación de camino*.
```suggestion
Utilizará el código de estado por defecto, o el que sea asignado en tu *path operation*.
```

2021-07-04 14:11 UTC, mariacamilagl approved these changes
Thanks for the effort @jfunez! I implemented some changes and fixed a couple of grammar mistakes. 

This is ready now! 🎉

2021-07-04 14:14 UTC, tiangolo commented
Thanks for the contribution @jfunez! :cake: 

And thanks a lot for the reviews and fixes @mariacamilagl and @pedabraham! :bow: :cookie:

2021-07-04 14:14 UTC, merged