Add pt translations for docs/pt/docs/tutorial/security/simple-oauth2.md
fastapi/fastapi pull request #12520
Opened 2024-10-24 00:54 UTC by LidiaDomingos

Hi!! I would like to contribute with portuguese translations for the security part!

2024-10-24 10:59 UTC, nazarepiedady approved these changes

2024-10-26 12:27 UTC, cassiobotaro approved these changes

2024-10-28 11:30 UTC, ceb10n requested changes
Great work \o/

just one line that needs to be removed (283)

The other comments you can change if you want (it would be nice to keep the standards)

2024-10-28 11:30 UTC, ceb10n commented on docs/pt/docs/tutorial/security/simple-oauth2.md
> +/// info | "Informação"
You can remove the quotes here:

```
/// info |  Informação
```

2024-10-28 11:30 UTC, ceb10n commented on docs/pt/docs/tutorial/security/simple-oauth2.md
> +Mas para a *path operation* (operação de caminho) de login, precisamos usar esses nomes para serem compatíveis com a especificação (e poder, por exemplo, usar o sistema integrado de documentação da A
you can translate *path operation* to *operação de rota*

2024-10-28 11:30 UTC, ceb10n commented on docs/pt/docs/tutorial/security/simple-oauth2.md
> +Primeiro, importe `OAuth2PasswordRequestForm` e use-o como uma dependência com `Depends` na *path operation* (operação de caminho) para `/token`:
you can translate path operation to operação de rota

2024-10-28 11:30 UTC, ceb10n commented on docs/pt/docs/tutorial/security/simple-oauth2.md
> +/// tip | "Dica"
you can remove the quotes here to:

```
/// tip | Dica
```

2024-10-28 11:30 UTC, ceb10n commented on docs/pt/docs/tutorial/security/simple-oauth2.md
> +/// tip | "Dica"
you can remove the quotes here to:

```
/// tip | Dica
```

2024-10-28 11:30 UTC, ceb10n commented on docs/pt/docs/tutorial/security/simple-oauth2.md
> +/// tip | "Dica"
you can remove the quotes here to:

```
/// tip | Dica
```

2024-10-28 11:30 UTC, ceb10n commented on docs/pt/docs/tutorial/security/simple-oauth2.md
> +/// info | "Informação"
you can remove the quotes here to:

```
/// info | Informação
```

2024-10-28 11:30 UTC, ceb10n commented on docs/pt/docs/tutorial/security/simple-oauth2.md
> +/// tip | "Dica"
you can remove the quotes here to:

```
/// tip | Dica
```

2024-10-28 11:30 UTC, ceb10n commented on docs/pt/docs/tutorial/security/simple-oauth2.md
> +/// tip | "Dica"
you can remove the quotes here to:

```
/// tip | Dica
```

2024-10-28 11:30 UTC, ceb10n commented on docs/pt/docs/tutorial/security/simple-oauth2.md
> +/// tip | "Dica"
you can remove the quotes here to:

```
/// tip | Dica
```

2024-10-28 11:30 UTC, ceb10n commented on docs/pt/docs/tutorial/security/simple-oauth2.md
> +/// tip | "Dica"
you can remove the quotes here to:

```
/// tip | Dica
```

2024-10-28 11:30 UTC, ceb10n commented on docs/pt/docs/tutorial/security/simple-oauth2.md
> +/// tip | "Dica"
you can remove the quotes here to:

```
/// tip | Dica
```

2024-10-28 11:30 UTC, ceb10n commented on docs/pt/docs/tutorial/security/simple-oauth2.md
> +`UserInDB(**user_dict)` means:
I think you forgot to remove this line

2024-10-28 11:30 UTC, ceb10n commented on docs/pt/docs/tutorial/security/simple-oauth2.md
> +/// tip | "Dica"
you can remove the quotes here to:

```
/// tip | Dica
```

2024-10-28 11:30 UTC, ceb10n commented on docs/pt/docs/tutorial/security/simple-oauth2.md
> +/// tip | "Dica"
you can remove the quotes here to:

```
/// tip | Dica
```

2024-10-28 11:30 UTC, ceb10n commented on docs/pt/docs/tutorial/security/simple-oauth2.md
> +/// tip | "Dica"
you can remove the quotes here to:

```
/// tip | Dica
```

2024-10-28 11:30 UTC, ceb10n commented on docs/pt/docs/tutorial/security/simple-oauth2.md
> +/// tip | "Dica"
you can remove the quotes here to:

```
/// tip | Dica
```

2024-10-28 11:30 UTC, ceb10n commented on docs/pt/docs/tutorial/security/simple-oauth2.md
> +/// tip | "Dica"
you can remove the quotes here to:

```
/// tip | Dica
```

2024-10-28 11:30 UTC, ceb10n commented on docs/pt/docs/tutorial/security/simple-oauth2.md
> +/// tip | "Dica"
you can remove the quotes here to:

```
/// tip | Dica
```

2024-10-28 11:30 UTC, ceb10n commented on docs/pt/docs/tutorial/security/simple-oauth2.md
> +/// info | "Informação"
you can remove the quotes here to:

```
/// info | Informação
```

2024-10-28 17:24 UTC, ceb10n approved these changes
Thank you ✨

2024-10-31 12:17 UTC, merged

2024-10-31 12:18 UTC, alejsdev commented
Thanks for the contribution! @LidiaDomingos :nerd_face: