spanish translation for advanced/response-directly.md
fastapi/fastapi pull request #1253
Opened 2020-04-13 03:21 UTC by jfunez

2020-04-26 12:56 UTC, mariacamilagl requested changes
Thank you for your work @jfunez 🚀

2020-04-26 12:56 UTC, mariacamilagl commented on docs/es/docs/advanced/response-directly.md
> +# Return a Response Directly
```suggestion
```

2020-04-26 12:56 UTC, mariacamilagl commented on docs/es/docs/advanced/response-directly.md
> +Cuando tu creas una *operación de camino*, tu puedes retornar normalmente cualquier dato: un `dict`, una `list`, un modelo Pydantic, modelo de base de datos, etc.
```suggestion
Cuando creas una *path operation*, puedes retornar normalmente cualquier dato: un `dict`, una `list`, un modelo Pydantic, modelo de base de datos, etc.
```

2020-04-26 12:56 UTC, mariacamilagl commented on docs/es/docs/advanced/response-directly.md
> +Luego, detrás de escena, pondría esos datos compatibles con JSON (por ejemplo, un `dict`) dentro de una `JSONResponse` que se usaría para enviar la respuesta al cliente.
```suggestion
Luego, detrás de escenas, pondría esos datos compatibles con JSON (por ejemplo, un `dict`) dentro de una `JSONResponse` que se usaría para enviar la respuesta al cliente.
```

2020-04-26 12:56 UTC, mariacamilagl commented on docs/es/docs/advanced/response-directly.md
> +Pero tu puedes retornar una `JSONResponse` directamente de tu *operación de camino*.
```suggestion
Pero puedes retornar una `JSONResponse` directamente de tu *path operation*.
```

2020-04-26 12:56 UTC, mariacamilagl commented on docs/es/docs/advanced/response-directly.md
> +Como **FastAPI** no realiza ningún cambion en la `Response` que tu retornas, debes asegurate que el contenido esta pronto.
```suggestion
Como **FastAPI** no realiza ningún cambion en la `Response` que tu retornas, debes asegurate que el contenido esta listo para ello.
```

2020-04-26 12:56 UTC, mariacamilagl commented on docs/es/docs/advanced/response-directly.md
> +El ejemplo anterior muestra las partes que tu precisas, pero no es muy útil todavía, como tu podrias simplemente retornar el `item` directamente, y **FastAPI** no pondría en una `JSONResponse` para t
```suggestion
El ejemplo anterior muestra las partes que necesitas, pero no es muy útil todavía, dado que podrías simplemente retornar el `item` directamente, y **FastAPI** lo pondría en una `JSONResponse` para ti, convirtiéndolo en un `dict`, etc. Todo esto por defecto.
```

2020-04-26 12:56 UTC, mariacamilagl commented on docs/es/docs/advanced/response-directly.md
> +Ahora, veamos cómo puedes usarlo, para retornar una respuesta personalizada.
```suggestion
Ahora, veamos cómo puedes usarlo para retornar una respuesta personalizada.
```

2020-04-26 12:56 UTC, mariacamilagl commented on docs/es/docs/advanced/response-directly.md
> +Digamos que tu quieres retornar una respuesta <a href="https://en.wikipedia.org/wiki/XML" class="external-link" target="_blank">XML</a>.
```suggestion
Digamos que quieres retornar una respuesta <a href="https://en.wikipedia.org/wiki/XML" class="external-link" target="_blank">XML</a>.
```

2020-04-26 12:56 UTC, mariacamilagl commented on docs/es/docs/advanced/response-directly.md
> +Puedes poner tu contenido    XML en una string, ponerla en una `Response` y retornarla:
```suggestion
Puedes poner tu contenido XML en un string, ponerlo en una `Response` y retornarlo:
```

2020-04-26 12:56 UTC, mariacamilagl commented on docs/es/docs/advanced/response-directly.md
> +Pero todavía es posible documentarlo, como es descrito en [Respuestas Adicionales en OpenAPI](additional-responses.md){.internal-link target=_blank}.
```suggestion
Pero todavía es posible documentarlo como es descrito en [Respuestas Adicionales en OpenAPI](additional-responses.md){.internal-link target=_blank}.
```

2021-07-04 17:04 UTC, mariacamilagl approved these changes
Thank you for the translation @jfunez!

2021-07-04 17:06 UTC, tiangolo commented
Thanks for the contribution @jfunez! :coffee: 

And thanks @mariacamilagl for the review and fixes! :cake: :nerd_face:

2021-07-04 17:06 UTC, merged