🌐 Add Portuguese translation for docs/pt/docs/tutorial/metadata.md
fastapi/fastapi pull request #12538
Opened 2024-10-25 00:00 UTC by LinkolnR

2024-10-25 11:21 UTC, ceb10n requested changes
Great work @LinkolnR ✨ 

Just some minor changes needed

2024-10-25 11:21 UTC, ceb10n commented on docs/pt/docs/tutorial/metadata.md
> +/// tip
The same here:

```
/// tip | Dica
```

2024-10-25 11:21 UTC, ceb10n commented on docs/pt/docs/tutorial/metadata.md
> +Use o parâmetro `tags` com suas *operações de caminho* (e `APIRouter`s) para atribuí-los a diferentes tags:
Most of the translations use operações de rota instead of operações de caminho. I think it would be nice the keep the pattern 😄

2024-10-25 11:21 UTC, ceb10n commented on docs/pt/docs/tutorial/metadata.md
> +/// info
You can translate the info to:

```
/// info | Informação
```

2024-10-25 11:51 UTC, nazarepiedady approved these changes
Besides the missing parts mentioned by @ceb10n, I think this pull request is ready to go forward right after of correcting the missing parts.

2024-10-25 11:52 UTC, nazarepiedady commented
@cassiobotaro, what do you think about this pull request?

2024-10-25 12:00 UTC, LinkolnR commented on docs/pt/docs/tutorial/metadata.md
> +## Metadata for API
I apologize for my distraction! Now i have corrected this.

2024-10-26 12:26 UTC, cassiobotaro approved these changes

2024-10-28 10:59 UTC, ceb10n approved these changes
🚀

2024-10-29 10:36 UTC, alejsdev commented
Thanks for your interest and contribution! @LinkolnR :raised_hands: 
And thanks to everyone for the reviews and help! :100: :medal_sports:

2024-10-29 10:36 UTC, merged