Add translation to docs/ko/docs/benchmarks.md
fastapi/fastapi pull request #12540
Opened 2024-10-25 08:55 UTC by Limsunoh

~~Started translation of `docs/ko/docs/benchmarks.md`~~
Add Korean translation for `docs/ko/docs/benchmarks.md`

2024-10-25 12:28 UTC, JaeHyuckSa reviewed
Hello! @Limsunoh, thank you for your review. 👍 There are a few revisions needed.

2024-10-25 12:28 UTC, JaeHyuckSa commented on docs/ko/docs/benchmarks.md
> +    * 직접 Uvicorn으로 애플리케이션을 작성하지는 않을 것입니다. 그렇게 한다면 Starlette(또는 **FastAPI**)가 제공하는 모든 코드를 포함해야 하기 때문입니다. 그리고 그렇게 만든다면 최종 애플리케이션은 프레임워크를 사용하는 것과 동일한 오버헤드를 가지며 앱 코드와 버그가 최소화됩니다.
```suggestion
    * 직접 Uvicorn으로 애플리케이션을 작성하지는 않을 것입니다. 즉, 사용자의 코드에는 적어도 Starlette(또는 **FastAPI**)에서 제공하는 모든 코드가 포함되어야 합니다. 그렇게 하면 최종 응용 프로그램은 프레임워크를 사용하고 앱 코드와 버그를 최소화하는 것과 동일한 오버헤드를 갖게 됩니다.
```

2024-10-25 12:28 UTC, JaeHyuckSa commented on docs/ko/docs/benchmarks.md
> +    * FastAPI는 Starlette 위에 더 많은 기능을 제공합니다. API를 구축할 때 거의 항상 필요한 데이터 검증 및 직렬화와 같은 기능이 포함되어 있습니다. 그리고 이를 사용하면 자동 문서화 기능도 제공됩니다(자동 문서화는 애플리케이션 실행 시 오버헤드를 추가하지 않고 시작 시 생성됩니다).
```suggestion
    * FastAPI는 Starlette에 추가적으로 더 많은 기능을 제공합니다. API를 구축할 때 거의 항상 필요한 데이터 검증 및 직렬화와 같은 기능이 포함되어 있습니다. 그리고 이를 사용하면 자동 문서화 기능도 제공됩니다(자동 문서화는 애플리케이션 실행 시 오버헤드를 추가하지 않고 시작 시 생성됩니다).
```

2024-10-25 12:35 UTC, JaeHyuckSa commented on docs/ko/docs/benchmarks.md
> +    * Uvicorn을 비교할 때는 Daphne, Hypercorn, uWSGI 등의 애플리케이션 서버와 비교하세요.
```suggestion
    * Uvicorn을 비교할 때는 Daphne, Hypercorn, uWSGI 등의 응용 프로그램 서버와 비교하세요.
```

2024-10-25 12:35 UTC, JaeHyuckSa commented on docs/ko/docs/benchmarks.md
> +    * 하지만 경로 기반 라우팅 등 간단한 웹 애플리케이션을 구축할 수 있는 도구를 제공합니다.
```suggestion
    * 하지만 경로 기반 라우팅 등 간단한 웹 응용 프로그램을 구축할 수 있는 도구를 제공합니다.
```

2024-10-25 12:41 UTC, JaeHyuckSa requested changes
Hello! @Limsunoh, thank you for your review. 👍 There are a few revisions needed. (Related issue: https://github.com/fastapi/fastapi/issues/2017)

2024-10-25 12:41 UTC, JaeHyuckSa commented on docs/ko/docs/benchmarks.md
> +    * 직접 Uvicorn으로 애플리케이션을 작성하지는 않을 것입니다. 그렇게 한다면 Starlette(또는 **FastAPI**)가 제공하는 모든 코드를 포함해야 하기 때문입니다. 그리고 그렇게 만든다면 최종 애플리케이션은 프레임워크를 사용하는 것과 동일한 오버헤드를 가지며 앱 코드와 버그가 최소화됩니다.
```suggestion
    * 직접 Uvicorn으로 응용 프로그램을 작성하지는 않을 것입니다. 즉, 사용자의 코드에는 적어도 Starlette(또는 **FastAPI**)에서 제공하는 모든 코드가 포함되어야 합니다. 그렇게 하면 최종 응용 프로그램은 프레임워크를 사용하고 앱 코드와 버그를 최소화하는 것과 동일한 오버헤드를 갖게 됩니다.
```

2024-10-25 12:41 UTC, JaeHyuckSa commented on docs/ko/docs/benchmarks.md
> +    * Uvicorn을 비교할 때는 Daphne, Hypercorn, uWSGI 등의 애플리케이션 서버와 비교하세요.
```suggestion
    * Uvicorn을 비교할 때는 Daphne, Hypercorn, uWSGI 등의 응용 프로그램 서버와 비교하세요.
```

2024-10-25 12:41 UTC, JaeHyuckSa commented on docs/ko/docs/benchmarks.md
> +    * 하지만 경로 기반 라우팅 등 간단한 웹 애플리케이션을 구축할 수 있는 도구를 제공합니다.
```suggestion
    * 하지만 경로 기반 라우팅 등 간단한 웹 응용 프로그램을 구축할 수 있는 도구를 제공합니다.
```

2024-10-25 12:41 UTC, JaeHyuckSa commented on docs/ko/docs/benchmarks.md
> +    * FastAPI는 Starlette 위에 더 많은 기능을 제공합니다. API를 구축할 때 거의 항상 필요한 데이터 검증 및 직렬화와 같은 기능이 포함되어 있습니다. 그리고 이를 사용하면 자동 문서화 기능도 제공됩니다(자동 문서화는 애플리케이션 실행 시 오버헤드를 추가하지 않고 시작 시 생성됩니다).
```suggestion
    * FastAPI는 Starlette에 추가적으로 더 많은 기능을 제공합니다. API를 구축할 때 거의 항상 필요한 데이터 검증 및 직렬화와 같은 기능들이 포함되어 있습니다. 그리고 이를 사용하면 자동 문서화 기능도 제공됩니다(자동 문서화는 응용 프로그램 실행 시 오버헤드를 추가하지 않고 시작 시 생성됩니다).
```

2024-10-25 12:41 UTC, JaeHyuckSa commented on docs/ko/docs/benchmarks.md
> +    * FastAPI를 사용하지 않고 직접 Starlette(또는 Sanic, Flask, Responder 등)를 사용했다면 데이터 검증 및 직렬화를 직접 구현해야 합니다. 따라서 최종 애플리케이션은 FastAPI를 사용한 것과 동일한 오버헤드를 가지게 될 것입니다. 많은 경우 데이터 검증 및 직렬화가 애플리케이션에서 작성된 코드 중 가장 많은 부분
```suggestion
    * FastAPI를 사용하지 않고 직접 Starlette(또는 Sanic, Flask, Responder 등)를 사용했다면 데이터 검증 및 직렬화를 직접 구현해야 합니다. 따라서 최종 응용 프로그램은 FastAPI를 사용한 것과 동일한 오버헤드를 가지게 될 것입니다. 많은 경우 데이터 검증 및 직렬화가 응용 프로그램에서 작성된 코드 중 가장 많은 부분을 차지합니다.
```

2024-10-25 12:41 UTC, JaeHyuckSa commented on docs/ko/docs/benchmarks.md
> +    * FastAPI를 비교할 때는 Flask-apispec, NestJS, Molten 등 데이터 검증, 직렬화 및 문서화가 통합된 자동 데이터 검증, 직렬화 및 문서화를 제공하는 웹 애플리케이션 프레임워크(또는 도구 세트)와 비교하세요.
```suggestion
    * FastAPI를 비교할 때는 Flask-apispec, NestJS, Molten 등 데이터 검증, 직렬화 및 문서화가 통합된 자동 데이터 검증, 직렬화 및 문서화를 제공하는 웹 응용 프로그램 프레임워크(또는 도구 집합)와 비교하세요.
```

2024-10-25 13:11 UTC, JaeHyuckSa approved these changes

2024-10-26 06:52 UTC, sodaMelon commented on docs/ko/docs/benchmarks.md
> +    * Starlette가 Uvicorn을 사용하고 Uvicorn보다 빨라질 수 없는 것과 마찬가지로, **FastAPI**는 Starlette를 사용하므로 더 빠를 수 없습니다.
```suggestion
    * Starlette가 Uvicorn을 사용하므로 Uvicorn보다 빨라질 수 없는 것과 마찬가지로, **FastAPI**는 Starlette를 사용하므로 더 빠를 수 없습니다.
```
동치가 되서, 문장이 명확해지도록 고쳐썼어요.

2024-10-26 06:55 UTC, sodaMelon commented on docs/ko/docs/benchmarks.md
> +    * FastAPI는 Starlette에 추가적으로 더 많은 기능을 제공합니다. API를 구축할 때 거의 항상 필요한 데이터 검증 및 직렬화와 같은 기능들이 포함되어 있습니다. 그리고 이를 사용하면 자동 문서화 기능도 제공됩니다(자동 문서화는 응용 프로그램 실행 시 오버헤드를 추가하지 않고 시작 시 생성됩니다).
```suggestion
    * FastAPI는 Starlette에 추가적으로 더 많은 기능을 제공합니다. API를 구축할 때 거의 항상 필요한 데이터 검증 및 직렬화와 같은 기능들이 포함되어 있습니다. 그리고 이를 사용하면 문서 자동화 기능도 제공됩니다(문서 자동화는 응용 프로그램 실행 시 오버헤드를 추가하지 않고 시작 시 생성됩니다).
```
automatic documentation = 문서 자동화 (in korea)

2024-10-26 07:00 UTC, sodaMelon reviewed
hi.  it's almost perfect
(i left some comments. If you think it's good, reflect it.)

2024-10-26 07:14 UTC, sodaMelon commented
@JaeHyuckSa hi.  for application, can we use ``응용 프로그램`` with ``애플리케이션``?
``응용 프로그램`` uses in 7 files 
``애플리케이션`` uses in 12 files.

2024-10-26 08:01 UTC, JaeHyuckSa commented
> @JaeHyuckSa hi. for application, can we use `응용 프로그램` with `애플리케이션`? `응용 프로그램` uses in 7 files `애플리케이션` uses in 12 files.

Hello @sodaMelon, we refer to the following link when translating into Korean, instead of basing on usage frequency:

https://github.com/fastapi/fastapi/issues/2017

In the case of "application," it can be translated as "응용 프로그램." Please refer to the link below:

https://www.flowdas.com/pages/python-docs-ko.html#:~:text=application%3A%20%EC%9D%91%EC%9A%A9%20%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%A8

For consistency, instances of the word "어플리케이션" across multiple files should be modified accordingly.

2024-10-26 08:11 UTC, sodaMelon commented
> > @JaeHyuckSa hi. for application, can we use `응용 프로그램` with `애플리케이션`? `응용 프로그램` uses in 7 files `애플리케이션` uses in 12 files.
> 
> Hello @sodaMelon, we refer to the following link when translating into Korean, instead of basing on usage frequency:
> 
> #2017
> 
> In the case of "application," it can be translated as "응용 프로그램." Please refer to the link below:
> 
> https://www.flowdas.com/pages/python-docs-ko.html#:~:text=application%3A%20%EC%9D%91%EC%9A%A9%20%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%A8
> 
> For consistency, instances of the word "어플리케이션" across multiple files should be modified accordingly.

oh thanks. i understand

2024-10-26 21:41 UTC, Limsunoh reviewed
Thank you so much for your help.

2024-10-26 21:41 UTC, Limsunoh commented on docs/ko/docs/benchmarks.md
> +    * FastAPI는 Starlette에 추가적으로 더 많은 기능을 제공합니다. API를 구축할 때 거의 항상 필요한 데이터 검증 및 직렬화와 같은 기능들이 포함되어 있습니다. 그리고 이를 사용하면 자동 문서화 기능도 제공됩니다(자동 문서화는 응용 프로그램 실행 시 오버헤드를 추가하지 않고 시작 시 생성됩니다).
Thank you. I'm just taking my first steps as a junior developer. I appreciate your help.

2024-10-27 13:34 UTC, sodaMelon approved these changes
LGTM

2024-10-27 15:01 UTC, merged

2024-10-27 15:03 UTC, alejsdev commented
Thanks so much for your interest in contributing to FastAPI! @Limsunoh @sodaMelon @JaeHyuckSa :rocket: