🌐 Add Portuguese Translation for `docs/pt/docs/advanced/custom-response.md`
fastapi/fastapi pull request #12631
Opened 2024-10-27 21:22 UTC by Joao-Pedro-P-Holanda

2024-10-28 04:49 UTC, nazarepiedady approved these changes

2024-10-28 10:57 UTC, ceb10n requested changes
Great work João 😃 

Just some typos and a few suggestions 😄

2024-10-28 10:57 UTC, ceb10n commented on docs/pt/docs/advanced/custom-response.md
> +Mas se você retornar uma `Response` diretamente (ou qualquer subclasse, como `JSONResponse`), os dados não serão convertidos automaticamente (memso que você declare um `response_model`), e a document
Just a typo here:

(memso que você declare um `response_model`)

should be

(*me**sm**o* que você declare um `response_model`)

2024-10-28 10:57 UTC, ceb10n commented on docs/pt/docs/advanced/custom-response.md
> +Obviamente, o cabeçalho `Content-Type`, o código de status, etc, irão vir do objeto `Response` que você retornou.
I think that "*irão vir*" is a little strange here. Maybe "*virão* do objeto" is better

2024-10-28 10:57 UTC, ceb10n commented on docs/pt/docs/advanced/custom-response.md
> +Você pode retorná-la direamente.
just a typo: **diretamente**

2024-10-28 10:57 UTC, ceb10n commented on docs/pt/docs/advanced/custom-response.md
> +Você ainda substituir `response_class` em *operações de rota* como antes.
missed the **pode**:

"*Você ainda **pode** substituir...*"

2024-10-28 17:46 UTC, Joao-Pedro-P-Holanda commented
Fixed @ceb10n, thanks for noticing!

2024-10-29 10:41 UTC, ceb10n approved these changes
❤️

2024-10-29 11:47 UTC, merged

2024-10-29 11:47 UTC, alejsdev commented
Thanks for the help! @Joao-Pedro-P-Holanda :rocket: 
And thanks for the reviews @ceb10n @nazarepiedady :mag: