Add translation to docs/ko/docs/advanced/advanced-dependencies.md
fastapi/fastapi pull request #12675
Opened 2024-10-28 14:30 UTC by kim-sangah

Add translation to docs/ko/docs/advanced/advanced-dependencies.md

2024-10-29 01:42 UTC, JaeHyuckSa requested changes
Hello! @kim-sangah, thank you for your contribute. 👍 There are a few revisions needed. (Related issue: https://github.com/fastapi/fastapi/issues/2017)

2024-10-29 01:42 UTC, JaeHyuckSa commented on docs/ko/docs/advanced/advanced-dependencies.md
> +이때 해당 고정된 콘텐츠를 매개변수화할 수 있길 바랍니다.
```suggestion
예를 들어, `q` 쿼리 매개변수가 특정 고정된 내용을 포함하고 있는지 확인하는 의존성을 원한다고 가정해 봅시다.

이때 해당 고정된 내용을 매개변수화할 수 있길 바랍니다.
```

2024-10-29 01:42 UTC, JaeHyuckSa commented on docs/ko/docs/advanced/advanced-dependencies.md
> +/// tip "팁"
```suggestion
/// tip "참고"
```

2024-10-29 01:42 UTC, JaeHyuckSa commented on docs/ko/docs/advanced/advanced-dependencies.md
> +/// tip "팁"
```suggestion
/// tip "참고"
```

2024-10-29 01:42 UTC, JaeHyuckSa commented on docs/ko/docs/advanced/advanced-dependencies.md
> +/// tip "팁"
```suggestion
/// tip "참고"
```

2024-10-29 01:42 UTC, JaeHyuckSa commented on docs/ko/docs/advanced/advanced-dependencies.md
> +/// tip "팁"
```suggestion
/// tip "참고"
```

2024-10-29 01:42 UTC, JaeHyuckSa commented on docs/ko/docs/advanced/advanced-dependencies.md
> +/// tip "팁"
```suggestion
/// tip "참고"
```

2024-10-29 01:42 UTC, JaeHyuckSa commented on docs/ko/docs/advanced/advanced-dependencies.md
> +보안 관련 장에서는 이와 같은 방식으로 구현된 유틸리티 함수들이 있습니다.
```suggestion
보안 관련 장에서는 이와 같은 방식으로 구현된 편의 함수들이 있습니다.
```

2024-10-29 03:42 UTC, JaeHyuckSa approved these changes

2024-10-29 10:02 UTC, alejsdev requested changes
Hi @kim-sangah, thanks for your interest in contributing to FastAPI.
However, I've noticed an error in the preview:

![image](https://github.com/user-attachments/assets/3779af8c-3487-4cac-9da8-66ea87beb7b2)

You can see the translations guidelines for more information here:
https://fastapi.tiangolo.com/contributing/#translations


Thanks!

2024-10-29 10:02 UTC, alejsdev commented on docs/ko/docs/advanced/advanced-dependencies.md
> +/// tip "참고"
```suggestion
/// tip | 참고
```

2024-11-07 20:42 UTC, alejsdev approved these changes
Fixed now! Thanks :nerd_face:

2024-11-07 20:43 UTC, merged

2024-11-07 20:45 UTC, alejsdev commented
Thanks for your contribution! :smile: @kim-sangah 
And thanks for your review :nerd_face: @JaeHyuckSa