🌐 Add Portuguese translation for docs/pt/docs/how-to/openapi-callbacks.md
fastapi/fastapi pull request #12705
Opened 2024-10-28 17:11 UTC by devfernandoa

2024-10-29 05:48 UTC, nazarepiedady approved these changes

2024-10-29 05:50 UTC, nazarepiedady commented
@devfernandoa, normally, it is recommended to only modify one single file per pull request, but I think in this one, we could benefit from an exception.

Keep following this path of collaborating with open-source initiatives.

2024-10-29 05:51 UTC, nazarepiedady commented
@ceb10n and @cassiobotaro, could you do the kindness of reviewing this pull request?

2024-10-29 09:08 UTC, tiangolo commented
@devfernandoa please separate this in 2 PRs, one for each file, this way it will be easier to review. 🤓☕

@nazarepiedady I'll ask you to please don't give instructions about managing the PRs or the repo, those things would be decided by someone in the FastAPI team, and getting external instructions could be confusing for people contributing. Also there's no need to ping others. Thanks!

2024-10-29 21:28 UTC, devfernandoa commented
Sorry guys, I forgot to remove the file when switching branches.
Fixed it here, and the other PR is already open as well!

2024-10-30 13:29 UTC, ceb10n requested changes
Great work @devfernandoa ✨ 

Just some lines that need to be removed, and some minor suggestions 😄

2024-10-30 13:29 UTC, ceb10n commented on docs/pt/docs/advanced/openapi-callbacks.md
> +* Send a notification back to the API user (the external developer).
You've forgotten to remove this line 😄

2024-10-30 13:29 UTC, ceb10n commented on docs/pt/docs/advanced/openapi-callbacks.md
> +/// tip | dica
Just a silly suggestion:

We alway start with a capital letter the translation of the admonitions

2024-10-30 13:29 UTC, ceb10n commented on docs/pt/docs/advanced/openapi-callbacks.md
> +The only new thing is the `callbacks=invoices_callback_router.routes` as an argument to the *path operation decorator*. We'll see what that is next.
this line to :D

2024-10-30 13:29 UTC, ceb10n commented on docs/pt/docs/advanced/openapi-callbacks.md
> +/// tip | dica
here to, just start with a capital letter if you want :D

2024-10-30 13:29 UTC, ceb10n commented on docs/pt/docs/advanced/openapi-callbacks.md
> +When implementing the callback yourself, you could use something like <a href="https://www.python-httpx.org" class="external-link" target="_blank">HTTPX</a> or <a href="https://requests.readthedocs.i
This line needs to be removed to

2024-10-30 13:29 UTC, ceb10n commented on docs/pt/docs/advanced/openapi-callbacks.md
> +/// tip | dica
here to, just start with a capital letter if you want :D

2024-10-30 13:29 UTC, ceb10n commented on docs/pt/docs/advanced/openapi-callbacks.md
> +/// tip | dica
here to, just start with a capital letter if you want :D

2024-10-30 13:29 UTC, ceb10n commented on docs/pt/docs/advanced/openapi-callbacks.md
> +/// tip | dica
here to, just start with a capital letter if you want :D

2024-10-30 13:30 UTC, ceb10n commented
Not a so important thing that I've noticed:

The title is incorrect: this file lives under `advanced`, not `how-to`

2024-10-30 13:54 UTC, devfernandoa commented
Just fixed these changes, thanks for the review @ceb10n !

2024-10-30 14:10 UTC, ceb10n approved these changes
🤗

2024-10-30 19:53 UTC, merged

2024-10-30 19:53 UTC, alejsdev commented
Thank you for being so interested in contributing to FastAPI! @devfernandoa :nerd_face: