🌐 Add Portuguese translation for `docs/pt/docs/advanced/websockets.md`
fastapi/fastapi pull request #12703
Opened 2024-10-28 16:55 UTC by devfernandoa

2024-10-29 05:44 UTC, nazarepiedady approved these changes
You did great work. Thanks for your collaboration.

2024-10-29 05:45 UTC, nazarepiedady commented
@ceb10n and @cassiobotaro, which one of you have time to review this pull request?

2024-10-30 14:37 UTC, ceb10n requested changes
Thank you @devfernandoa 

Just some typos and suggestions

And it would be nice to use the new style for includes described in the issue: Update docs include syntax for source examples https://github.com/fastapi/fastapi/issues/12554

2024-10-30 14:37 UTC, ceb10n commented on docs/pt/docs/advanced/websockets.md
> +Você pode usar  <a href="https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API" class="external-link" target="_blank">WebSockets</a> com **FastAPI**.
There are two spaces here:
Você pode usar  <a href...

Just remove one so it doesn't look strange :D

2024-10-30 14:37 UTC, ceb10n commented on docs/pt/docs/advanced/websockets.md
> +/// note | "Detalhes Técnicos"
You can remove the double quotes here:

```
/// note | Detalhes Técnicos
```

2024-10-30 14:37 UTC, ceb10n commented on docs/pt/docs/advanced/websockets.md
> +Em seu rota WebSocket você pode `await` por mensagens e enviar mensagens.
change to:

Em **sua** rota...

And I think it's a little strange: você pode `await` por mensagens

In english it makes sense, but when translating, it loses the sense...

I think you can translate using something like:

Em sua rota WebSocket você pode esperar (`await`) por mensagens e enviar mensagens.

2024-10-30 14:37 UTC, ceb10n commented on docs/pt/docs/advanced/websockets.md
> +Abra seu broser em: <a href="http://127.0.0.1:8000" class="external-link" target="_blank">http://127.0.0.1:8000</a>.
missed the **w** in browser: Abra seu bro**w**ser em...

But I think you can use:

Abra o seu navegador em...

2024-10-30 14:37 UTC, ceb10n commented on docs/pt/docs/advanced/websockets.md
> +They work the same way as for other FastAPI endpoints/*path operations*:
This line needs to be removed :D

2024-10-30 14:37 UTC, ceb10n commented on docs/pt/docs/advanced/websockets.md
> +//// tab | Python 3.10+
You can replace all the ```Python... with:

{* ../../docs_src/websockets/tutorial002_an_py310.py  hl[68:69,82] *}

See this issue for reference: Update docs include syntax for source examples https://github.com/fastapi/fastapi/issues/12554

2024-10-30 14:37 UTC, ceb10n commented on docs/pt/docs/advanced/websockets.md
> +```Python hl_lines="48-52"
Here you can use the new style for includes:

{* ../../docs_src/websockets/tutorial001.py hl[48:52] *}

See this issue for reference: Update docs include syntax for source examples https://github.com/fastapi/fastapi/issues/12554

2024-10-30 14:37 UTC, ceb10n commented on docs/pt/docs/advanced/websockets.md
> +/// info
You can add translation for the admonition here:

```
/// info | Informação
```

2024-10-30 14:37 UTC, ceb10n commented on docs/pt/docs/advanced/websockets.md
> +Abrar seu browser em: <a href="http://127.0.0.1:8000" class="external-link" target="_blank">http://127.0.0.1:8000</a>.
You can translate browser here (and remove the r in Abra):

Abra o seu navegador em: ...

2024-10-30 14:37 UTC, ceb10n commented on docs/pt/docs/advanced/websockets.md
> +//// tab | Python 3.9+
Here you can replace all the code with:

{* ../../docs_src/websockets/tutorial003_py39.py hl[79:81] *}

See this issue for reference: Update docs include syntax for source examples https://github.com/fastapi/fastapi/issues/12554

2024-10-30 14:37 UTC, ceb10n commented on docs/pt/docs/advanced/websockets.md
> +* Abrar o aplicativo com várias abas do navegador.
remove the **r**:

Abra o aplicativo...

2024-10-30 15:16 UTC, ceb10n approved these changes
That was fast! ⚡

2024-10-31 12:20 UTC, alejsdev commented
Thanks for your contribution! @devfernandoa :tada: 
And thanks for the reviews and suggestions @ceb10n :mag:

2024-10-31 12:20 UTC, merged