🌐 Add Korean translation for `docs/ko/docs/advanced/templates.md`
fastapi/fastapi pull request #12726
Opened 2024-10-30 14:20 UTC by Heumhub

Add Korean translation for docs/ko/docs/advanced/templates.md

2024-10-30 16:37 UTC, sodaMelon commented on docs/ko/docs/advanced/templates.md
> +가상 환경을 생성하고(virtual environment{.internal-link target=_blank}), 활성화한 후 jinja2를 설치해야 합니다:
```suggestion
가상 환경을 생성하고(virtual environment{.internal-link target=_blank}), 활성화한 후 jinja2를 설치해야 합니다:
```
markdown has broken.
please check your work with generated docs by github action

2024-10-30 16:40 UTC, sodaMelon commented on docs/ko/docs/advanced/templates.md
> +* 생성한 `templates`를 사용하여 `TemplateResponse`를 렌더링하고 반환합니다. 템플릿의 이름, 요청 객체 및 Jinja2 템플릿 내에서 사용될 키-값 쌍이 포함된 "컨텍스트" 사전도 전달합니다.
```suggestion
* 생성한 `templates`를 사용하여 `TemplateResponse`를 렌더링하고 반환합니다. 템플릿의 이름, 요청 객체 및 Jinja2 템플릿 내에서 사용될 키-값 쌍이 포함된 "컨텍스트" 딕셔너리도 전달합니다.
```

2024-10-30 16:41 UTC, sodaMelon commented on docs/ko/docs/advanced/templates.md
> +/// 노트
```suggestion
/// 노트
```
markdown has broken here

2024-10-30 16:42 UTC, sodaMelon commented on docs/ko/docs/advanced/templates.md
> +///
```suggestion
///

/// tip | 참고

`response_class=HTMLResponse`를 선언하면 문서 UI 응답이 HTML임을 알 수 있습니다.

///

/// 노트 | "기술 세부 사항"
`from starlette.templating import Jinja2Templates`를 사용할 수도 있습니다.

**FastAPI**는 개발자를 위한 편리함으로 `fastapi.templating` 대신 `starlette.templating`을 제공합니다. 하지만 대부분의 사용 가능한 응답은 Starlette에서 직접 옵니다. `Request` 및 `StaticFiles`도 마찬가지입니다.
///
```
you need to your generated docs (2)

2024-10-30 16:44 UTC, sodaMelon commented on docs/ko/docs/advanced/templates.md
> +그런 다음 `templates/item.html`에 다음과 같은 템플릿을 작성할 수 있습니다:
```suggestion
그런 다음 `templates/item.html`에 템플릿을 작성할 수 있습니다. 예를 들면:
```

2024-11-12 07:10 UTC, kim-sangah approved these changes

2024-11-12 07:10 UTC, kim-sangah commented on docs/ko/docs/advanced/templates.md
LGTM!

2024-11-12 10:34 UTC, Heumhub commented on docs/ko/docs/advanced/templates.md
thank you!

2024-11-13 08:17 UTC, sodaMelon approved these changes
LGTM!

2024-11-28 04:59 UTC, hard-coders requested changes
It's broken. See [Translation specific tips and guidelines](https://fastapi.tiangolo.com/contributing/#translation-specific-tips-and-guidelines) and https://github.com/fastapi/fastapi/discussions/3167#discussioncomment-721448

> In lines starting with `///` translate only the text part after `|`. Leave the rest unchanged.

2024-11-28 04:59 UTC, hard-coders commented on docs/ko/docs/advanced/templates.md
> +/// 노트
```suggestion
/// note | 참고
```

2024-11-28 04:59 UTC, hard-coders commented on docs/ko/docs/advanced/templates.md
> +/// tip | 참고
```suggestion
/// tip | 팁
```

2024-11-28 04:59 UTC, hard-coders commented on docs/ko/docs/advanced/templates.md
> +/// 노트 | "기술 세부 사항"
```suggestion
/// note | "기술 세부 사항"
```

2024-11-29 07:47 UTC, Heumhub commented on docs/ko/docs/advanced/templates.md
> +/// 노트 | "기술 세부 사항"
감사합니다

2024-12-09 13:07 UTC, merged

2024-12-09 13:07 UTC, alejsdev commented
Thanks for your contribution! @Heumhub :partying_face: 
And thanks for the reviews @sodaMelon, @hard-coders and @kim-sangah :mag: