🌐 Add Korean translation for `docs/ko/docs/how-to/conditional-openapi.md`
fastapi/fastapi pull request #12731
Opened 2024-10-31 06:52 UTC by sptcnl

2024-11-01 01:36 UTC, hard-coders commented on docs/ko/docs/how-to/conditional-openapi.md
> +그것은 API에 추가적인 보안을 제공하지 않으며, *경로 작업*은 여전히 동일한 위치에서 사용 할 수 있습니다.
```suggestion
이는 API에 추가적인 보안을 제공하지 않으며, *경로 작업*은 여전히 동일한 위치에서 사용 할 수 있습니다.
```
"그것은" is not natural.

2024-11-01 01:36 UTC, hard-coders commented on docs/ko/docs/how-to/conditional-openapi.md
> +그런 다음 `/openapi.json`, `/docs` 또는 `/redoc`의 URL로 이동하면 `404 Not Found`라는 오류가 다음과 같이 표시됩니다:
원문에도 "Then", "And then" 이런 식으로 되어 있긴 하지만..
"그런 다음"이 너무 반복되어서 조금 어색합니다. 가능하다면 접속사를 조금 다듬었으면 좋겠습니다.

2024-11-01 05:30 UTC, sptcnl commented on docs/ko/docs/how-to/conditional-openapi.md
> +그런 다음 `/openapi.json`, `/docs` 또는 `/redoc`의 URL로 이동하면 `404 Not Found`라는 오류가 다음과 같이 표시됩니다:
리뷰 감사합니다!

2024-11-01 06:15 UTC, hard-coders requested changes
Great job! Only one thing left to do.

2024-11-01 06:15 UTC, hard-coders commented on docs/ko/docs/how-to/conditional-openapi.md
> +* request body와 response에 대해 잘 정의된 Pydantic 모델을 사용하도록 하세요.
```suggestion
* 요청 본문과 응답에 대해 잘 정의된 Pydantic 모델을 사용하도록 하세요.
```
Untranslated "request body" and "response"

2024-11-01 06:33 UTC, hard-coders approved these changes
LGTM 🚀

2024-11-07 20:41 UTC, merged

2024-11-07 20:41 UTC, alejsdev commented
Cool! Thanks for the contribution @sptcnl :sparkles: 

And thanks for the review @hard-coders :nerd_face: