Spanish translation for section async
fastapi/fastapi pull request #1290
Opened 2020-04-19 18:18 UTC by alvaropernas

Hi, 
Here is my first approach.
Appreciate any comments, thks!!

2020-04-26 14:38 UTC, mariacamilagl requested changes
Thank you so much for your effort @alvaropernas 🚀 👍 

This was a long, complex one!

I know the changes may look a bit overwhelming, but they are minor details. Here's the summary of the suggestions: 

1. Removing double spaces and spaces after commas
2. Maintaining consistency between "tu" and "usted"
3. Keeping the central FastAPI terms like "path operation function" in English for consistency
4. Other typos}

Thanks again! 🎉 🍰

2020-04-26 14:38 UTC, mariacamilagl commented on docs/es/docs/async.md
> +Para que `await` funcione, tiene que estar dentro de una función que admita esta asincronía. Para hacer eso, simplemente lo declara con `async def`:
```suggestion
Para que `await` funcione, tiene que estar dentro de una función que admita esta asincronía. Para hacer eso, simplemente lo declaras con `async def`:
```

2020-04-26 14:38 UTC, mariacamilagl commented on docs/es/docs/async.md
> +Con `async def`, Python sabe que, dentro de esa función, debe tener en cuenta las expresiones` wait ', y que puede "pausar" la ejecución de esa función e ir a hacer otra cosa antes de regresar.
```suggestion
Con `async def`, Python sabe que, dentro de esa función, debe tener en cuenta las expresiones `wait` y que puede "pausar" la ejecución de esa función e ir a hacer otra cosa antes de regresar.
```

2020-04-26 14:38 UTC, mariacamilagl commented on docs/es/docs/async.md
> +Cuando desee llamar a una función `async def`, debe" esperarla ". Entonces, esto no funcionará:
```suggestion
Cuando desees llamar a una función `async def`, debes" esperarla ". Entonces, esto no funcionará:
```

2020-04-26 14:38 UTC, mariacamilagl commented on docs/es/docs/async.md
> +Por lo tanto, si está utilizando una biblioteca que le dice que puede llamarla con `await`, debe crear las *funciones de enrutado* que la usan con` async def`, como en:
```suggestion
Por lo tanto, si estás utilizando una biblioteca que te dice que puedes llamarla con `await`, debes crear las *path operation functions* que la usan con `async def`, como en:
```

2020-04-26 14:38 UTC, mariacamilagl commented on docs/es/docs/async.md
> +Pero al mismo tiempo, las funciones definidas con `async def` deben ser "esperadas". Por lo tanto, las funciones con `async def` solo se pueden invocar dentro de las funciones definidas con` async de
```suggestion
Pero al mismo tiempo, las funciones definidas con `async def` deben ser "esperadas". Por lo tanto, las funciones con `async def` solo se pueden invocar dentro de las funciones definidas con `async def` también.
```

2020-04-26 14:38 UTC, mariacamilagl commented on docs/es/docs/async.md
> +Es posible que haya notado que 'esperar' solo se puede usar dentro de las funciones definidas con 'async def'.
```suggestion
Es posible que hayas notado que `await` solo se puede usar dentro de las funciones definidas con `async def`.
```

2020-04-26 14:38 UTC, mariacamilagl commented on docs/es/docs/async.md
> +Si está trabajando con **FastAPI** no tiene que preocuparse por eso, porque esa "primera" función será su *función de enrutados*, y FastAPI sabrá cómo hacer lo pertinente.
```suggestion
Si estás trabajando con **FastAPI** no tienes que preocuparte por eso, porque esa "primera" función será tu *path operation function*, y FastAPI sabrá cómo hacer lo pertinente.
```

2020-04-26 14:38 UTC, mariacamilagl commented on docs/es/docs/async.md
> +En el caso de que desee usar `async` /` await` sin FastAPI, <a href="https://docs.python.org/3/library/asyncio-task.html#coroutine" class="external-link" target="_blank">check the official Python doc
```suggestion
En el caso de que desees usar `async` / `await` sin FastAPI, <a href="https://docs.python.org/3/library/asyncio-task.html#coroutine" class="external-link" target="_blank">revisa la documentación oficial de Python</a>.
```

2020-04-26 14:38 UTC, mariacamilagl commented on docs/es/docs/async.md
> +Este estilo de usar `async` y` await` es relativamente nuevo en el lenguaje.
```suggestion
Este estilo de usar `async` y `await` es relativamente nuevo en el lenguaje.
```

2020-04-26 14:38 UTC, mariacamilagl commented on docs/es/docs/async.md
> +En versiones anteriores de Python, podría haber utilizado hilos o <a href="http://www.gevent.org/" class="external-link" target="_blank">Gevent</a>. Pero el código es mucho más complejo de entender,
```suggestion
En versiones anteriores de Python, podrías haber utilizado hilos o <a href="http://www.gevent.org/" class="external-link" target="_blank">Gevent</a>. Pero el código es mucho más complejo de entender, depurar y desarrollar.
```

2020-04-26 14:38 UTC, mariacamilagl commented on docs/es/docs/async.md
> +En versiones anteriores de NodeJS / Browser JavaScript, habría utilizado "callbacks". Lo que conduce a <a href="http://callbackhell.com/" class="external-link" target="_blank"> callback hell </a>.
```suggestion
En versiones anteriores de NodeJS / Browser JavaScript, habrías utilizado "callbacks". Lo que conduce a <a href="http://callbackhell.com/" class="external-link" target="_blank">callback hell</a>.
```

2020-04-26 14:38 UTC, mariacamilagl commented on docs/es/docs/async.md
> +## Corutinas
```suggestion
## Coroutines
```

2020-04-26 14:38 UTC, mariacamilagl commented on docs/es/docs/async.md
> +**Coroutine** es el término guay para la cosa devuelta por una función `async def`. Python sabe que es algo así como una función que puede iniciar y que terminará en algún momento, pero que también p
```suggestion
**Coroutine** es un término sofisticado para referirse a la cosa devuelta por una función `async def`. Python sabe que es algo así como una función que puede iniciar y que terminará en algún momento, pero que también podría pausarse internamente, siempre que haya una `await` dentro de ella.
```

2020-04-26 14:38 UTC, mariacamilagl commented on docs/es/docs/async.md
> +Pero toda esta funcionalidad de usar código asincrónico con `async` y` await` se resume muchas veces como el uso de "corutinas". Es comparable a la característica principal de Go, las "Goroutines".
```suggestion
Pero toda esta funcionalidad de usar código asincrónico con `async` y `await` se resume muchas veces como el uso de "coroutines". Es comparable a la característica principal de Go, las "Goroutines".
```

2020-04-26 14:38 UTC, mariacamilagl commented on docs/es/docs/async.md
> +> Las versiones modernas de Python tienen soporte para **"código asíncrono"** usando algo llamado **"corutinas"**, con la sintaxis **`async` y` await`**.
```suggestion
> Las versiones modernas de Python tienen soporte para **"código asíncrono"** usando algo llamado **"coroutines"**, con la sintaxis **`async` y `await`**.
```

2020-04-26 14:38 UTC, mariacamilagl commented on docs/es/docs/async.md
> +    Si tienes bastante conocimiento técnico (corutinas, hilos, bloqueos, etc.) y tienes curiosidad acerca de cómo FastAPI gestiona `async def` vs normal `def`, continúa.
```suggestion
    Si tienes bastante conocimiento técnico (coroutines, threads, bloqueos, etc.) y tienes curiosidad acerca de cómo FastAPI gestiona `async def` vs `def` normal, continúa.
```

2020-04-26 14:38 UTC, mariacamilagl commented on docs/es/docs/async.md
> +### Funciones de enrutado
```suggestion
### Path operation functions 
```

2020-04-26 14:38 UTC, mariacamilagl commented on docs/es/docs/async.md
> +Cuando declara una *función de enrutado* con `def` normal en lugar de `async def`, se ejecuta en un conjunto de subprocesos externo que luego  espera, en lugar de ser llamado directamente (ya que blo
```suggestion
Cuando declaras una *path operation function* con `def` normal en lugar de `async def`, se ejecuta en un threadpool externo que luego espera, en lugar de ser llamado directamente (ya que bloquearía el servidor).
```

2020-04-26 14:38 UTC, mariacamilagl commented on docs/es/docs/async.md
> +Aún así, en ambas situaciones, es probable que **FastAPI** sea [aún más rápido](/#rendimiento) {.Internal-link target=_blank} que (o al menos comparable) a su framework anterior.
```suggestion
Aún así, en ambas situaciones, es probable que **FastAPI** sea [aún más rápido](/#rendimiento){.Internal-link target=_blank} que (o al menos comparable) a tu framework anterior.
```

2020-04-26 14:38 UTC, mariacamilagl commented on docs/es/docs/async.md
> +Si vienes de otro framework asíncrono que no funciona de la manera descrita anteriormente y estás acostumbrado a definir funciones de enrutado *del tipo sólo cálculo* con `def` simple para una pequeñ
```suggestion
Si vienes de otro framework asíncrono que no funciona de la manera descrita anteriormente y estás acostumbrado a definir *path operation functions* del tipo sólo cálculo con `def` simple para una pequeña ganancia de rendimiento (aproximadamente 100 nanosegundos), ten en cuenta que en **FastAPI** el efecto sería bastante opuesto. En estos casos, es mejor usar `async def` a menos que tus *path operation functions* usen un código que realice el bloqueo <abbr title="Input/Output: disk reading or writing, network communications.">IO</abbr>.
```

2020-04-26 14:38 UTC, mariacamilagl commented on docs/es/docs/async.md
> +Lo mismo se aplica para las dependencias. Si una dependencia es una función estándar `def` en lugar de` async def`, se ejecuta en el conjunto de hilos externo.
```suggestion
Lo mismo se aplica para las dependencias. Si una dependencia es una función estándar `def` en lugar de `async def`, se ejecuta en el threadpool externo.
```

2020-04-26 14:38 UTC, mariacamilagl commented on docs/es/docs/async.md
> +Puede tener múltiples dependencias y subdependencias que se requieren entre sí (como parámetros de las definiciones de función), algunas de ellas pueden crearse con `async def` y otras con` def` norm
```suggestion
Puedes tener múltiples dependencias y subdependencias que se requieren entre sí (como parámetros de las definiciones de función), algunas de ellas pueden crearse con `async def` y otras con `def` normal. Seguiría funcionando correctamente, y los creados con `def` normal se llamarían en un thread externo en lugar de ser "awaited".
```

2020-04-26 14:38 UTC, mariacamilagl commented on docs/es/docs/async.md
> +Cualquier otra función de utilidad que llame directamente se puede crear con `def` o` async def` normales y FastAPI no afectará la manera en que la llama.
```suggestion
Cualquier otra función de utilidad que llame directamente se puede crear con `def` o `async def` normales y FastAPI no afectará la manera en que la llamas.
```

2020-04-26 14:38 UTC, mariacamilagl commented on docs/es/docs/async.md
> +Esto choca con las funciones que FastAPI le solicita: *funciones de enrutado* y dependencias.
```suggestion
Esto contrasta con las funciones que FastAPI llama por ti: *path operation functions* y dependencias.
```

2020-04-26 14:38 UTC, mariacamilagl commented on docs/es/docs/async.md
> +Si su utility function es una función normal con `def`, se llamará directamente (tal cual la escribes en su código), no en un conjunto de hilos, si la función se crea con` async def`, entonces debes
```suggestion
Si tu utility function es una función normal con `def`, se llamará directamente (tal cual la escribes en tu código), no en un threadpool, si la función se crea con `async def`, entonces debes usar await en esa función cuando la llamas en tu código.
```

2020-04-26 22:31 UTC, alvaropernas commented on docs/es/docs/async.md
> +Tú y tu pareja os coméis las hamburguesas y os divertís.
Not sure about this one but... ;)

2020-04-26 22:58 UTC, alvaropernas commented
Thanks  Maria, I had doubts about what should be translated.
I will check the extra spaces and the use of "usted" for the next one.

2020-04-28 11:57 UTC, mariacamilagl commented
> Thanks Maria, I had doubts about what should be translated.
> I will check the extra spaces and the use of "usted" for the next one.

Hey, no worries. We are also always debating what should or shouldn't be translated. It isn't an exact science at all. 

Thank you for your work! 🍰 🚀

2020-04-28 12:00 UTC, mariacamilagl approved these changes
Thank you! 🚀

2020-05-16 18:53 UTC, merged

2020-05-16 18:54 UTC, tiangolo commented
Thanks for your contribution @alvaropernas ! :cake: :rocket: 

And thanks @mariacamilagl for your review and help :nerd_face: :coffee: