🌐 Add Spanish translation for docs/es/docs/virtual-environments.md
fastapi/fastapi pull request #12927
Opened 2024-11-14 17:29 UTC by JCTrapero

🌐 Add Spanish translation for docs/es/docs/virtual-environments.md

Best regards

2024-11-15 10:08 UTC, JavierSanchezCastro commented on docs/es/docs/virtual-environments.md
> +Ahora estás preparado para comennzar a trabajar en tu proyecto.
```suggestion
Ahora estás preparado para comenzar a trabajar en tu proyecto.
```

2024-11-15 10:17 UTC, JavierSanchezCastro requested changes
Typo

2024-11-15 10:21 UTC, JCTrapero commented on docs/es/docs/virtual-environments.md
> +Ahora estás preparado para comennzar a trabajar en tu proyecto.
Genial! Gracias!!

2024-11-15 10:27 UTC, JavierSanchezCastro approved these changes

2024-12-30 18:52 UTC, tiangolo commented
This was covered in another PR, so I'll close this one now, thanks for the effort! :cake: :coffee:

2024-12-30 18:52 UTC, closed without merging