🌐 Add Chinese translation for `docs/zh/docs/tutorial/query-param-models.md`
fastapi/fastapi pull request #12931
Opened 2024-11-14 18:27 UTC by Vincy1230

Add Chinese translation for query-param-models.md
为 query-param-models（查询参数模型）一章添加翻译

2024-11-25 15:20 UTC, Aruelius requested changes

2024-11-25 15:20 UTC, Aruelius commented on docs/zh/docs/tutorial/query-param-models.md
> +在一个 **Pydantic模型**中声明你需要的**查询参数**，然后将参数声明为 `Query`：
应该是 `Pydantic 模型`，字母与中文之间缺少空格

2024-11-25 15:31 UTC, Lenclove commented on docs/zh/docs/tutorial/query-param-models.md
> +如果客户端尝试在**查询参数**中发送一些**额外的**数据，他们将会收到一个**错误**响应。
“如果客户端尝试”与原文不一致,应为“如果一个客户端尝试”

2024-11-25 15:34 UTC, Vincy1230 commented on docs/zh/docs/tutorial/query-param-models.md
> +如果客户端尝试在**查询参数**中发送一些**额外的**数据，他们将会收到一个**错误**响应。
此处应该是英文中“不定冠词表存在”的情况，个人认为翻译时应当略去。
或者，我可以修改为 “假设有一个客户端尝试” ... “他将会收到一个” ...

2024-11-25 15:53 UTC, Lenclove approved these changes
OK.Thanks.

2024-11-25 15:53 UTC, Lenclove commented on docs/zh/docs/tutorial/query-param-models.md
> +如果客户端尝试在**查询参数**中发送一些**额外的**数据，他们将会收到一个**错误**响应。
我觉得后面一种可能比较好

2024-11-25 20:46 UTC, Vincy1230 commented on docs/zh/docs/tutorial/query-param-models.md
> +在一个 **Pydantic模型**中声明你需要的**查询参数**，然后将参数声明为 `Query`：
好的，已修改 :)

2024-11-26 00:16 UTC, Aruelius approved these changes

2024-11-26 22:06 UTC, merged

2024-11-26 22:07 UTC, alejsdev commented
Thanks to all of you for the help! :rocket: @Vincy1230 @Aruelius @Lenclove