🌐 Add Korean translation for `docs/ko/docs/tutorial/query-param-models.md`
fastapi/fastapi pull request #12940
Opened 2024-11-15 14:31 UTC by jts8257

2024-11-19 01:31 UTC, jts8257 commented
Hi @alejsdev ,

Thank you for reviewing my PR. I noticed that the PR is labeled with `lang-zh`, but it actually contains a Korean translation (`lang-ko`). Could you kindly update the label to `lang-ko` so it correctly reflects the content of the PR?

2024-11-19 10:28 UTC, alejsdev commented
My bad! Fixed.
Thanks @jts8257 :raised_hands:

2024-11-19 10:41 UTC, hard-coders requested changes
Great job! I reviewed only two points.

2024-11-19 10:41 UTC, hard-coders commented on docs/ko/docs/tutorial/query-param-models.md
> +이 기능은 FAST API 버전 `0.115.0`부터 제공됩니다. 🤓
```suggestion
이 기능은 FastAPI 버전 `0.115.0`부터 제공됩니다. 🤓
```

2024-11-19 10:41 UTC, hard-coders commented on docs/ko/docs/tutorial/query-param-models.md
> +# 쿼리 매개변수와 모델
```suggestion
# 쿼리 매개변수 모델
```
여기서는 새로운 기능인 매개변수 모델 자체를 의미하므로 "와"는 뻈으면 좋을거 같습니다.

2024-11-19 14:30 UTC, jts8257 commented
Thank you for promptly updating the label to `lang-ko`, @alejsdev . I appreciate your swift action! 🙏

2024-11-19 14:30 UTC, jts8257 commented
Thank you for your valuable feedback, @hard-coders. 
I've addressed the two points you mentioned. Please let me know if there's anything else I should consider.

2024-11-20 01:06 UTC, hard-coders approved these changes
LGTM 🚀

2024-11-20 19:24 UTC, merged

2024-11-20 19:24 UTC, alejsdev commented
Thanks for your contribution! @jts8257 :nerd_face: 
And thanks for your review! @hard-coders :rocket: