🌐 Add Korean translation for `docs/ko/docs/tutorial/request-forms.md`
fastapi/fastapi pull request #13003
Opened 2024-11-28 06:17 UTC by hard-coders

2024-12-05 04:28 UTC, hard-coders commented on docs/ko/docs/tutorial/request-forms.md
> +## Define `Form` parameters
넵, 맞습니다. 리뷰 감사합니다

2024-12-05 04:58 UTC, jts8257 requested changes
LGTM!

2024-12-05 04:59 UTC, jts8257 approved these changes
LGTM

2024-12-09 12:42 UTC, merged

2024-12-09 12:42 UTC, alejsdev commented
Thank you! @hard-coders :raised_hands: 
And thanks for your review @jts8257 :nerd_face: