🌐 Add Ukrainian translation for `docs/uk/docs/fastapi-cli.md`
fastapi/fastapi pull request #13020
Opened 2024-12-01 18:51 UTC by ykertytsky

Hey guys! This is my first contribution to fastapi docs :)

2024-12-09 13:01 UTC, rostik1410 requested changes

2024-12-09 13:01 UTC, rostik1410 commented on docs/uk/docs/fastapi-cli.md
> +В більшості випадків ви можете (і маєте) мати "termination proxy"  який обробляє HTTPS для вас, це залежить від способу розгортання вашого додатку, ваш провайдер може зробити це для вас, або вам потр
```suggestion
В більшості випадків Ви можете (і маєте) мати "termination proxy", який обробляє HTTPS для вас, це залежить від способу розгортання вашого додатку, Ваш провайдер може зробити це для вас, або вам потрібно налаштувати його самостійно.
```

2024-12-09 13:01 UTC, rostik1410 commented on docs/uk/docs/fastapi-cli.md
> +В більшості випадків ви можете (і маєте) мати "termination proxy"  який обробляє HTTPS для вас, це залежить від способу розгортання вашого додатку, ваш провайдер може зробити це для вас, або вам потр
@ykertytsky Great job. There are just several typos.

2024-12-09 13:52 UTC, mezgoodle commented on docs/uk/docs/fastapi-cli.md
> +Ви можете дізнатись більше про це у [документації для розгортування](deployment/index.md){.internal-link target=_blank}.
```suggestion
Ви можете дізнатись більше про це у [документації про розгортування](deployment/index.md){.internal-link target=_blank}.
```

2024-12-09 13:53 UTC, mezgoodle reviewed
@ykertytsky , great job! Agree with @rostik1410 , apply his suggestions please

2024-12-09 19:13 UTC, ykertytsky commented
> @ykertytsky , great job! Agree with @rostik1410 , apply his suggestions please.

Thank you! Critique is taken to account, will fix mentioned issues shortly.

2024-12-10 11:09 UTC, ykertytsky commented
Okay, @rostik1410 @mezgoodle all mentioned typos and mistakes corrected succesfully🫡

2024-12-10 11:10 UTC, mezgoodle approved these changes

2024-12-14 08:12 UTC, rostik1410 approved these changes

2024-12-16 19:34 UTC, ykertytsky commented
@alejsdev Hey! I am pretty sure we are done here :)

2024-12-17 20:12 UTC, rostik1410 commented
> @alejsdev Hey! I am pretty sure we are done here :)

sometimes a merge takes a lot of time, don't worry about it)

2024-12-17 21:33 UTC, merged

2024-12-17 21:34 UTC, alejsdev commented
Thanks for your contribution! @ykertytsky :nerd_face: 
And thanks for the help @mezgoodle @rostik1410 :100: