fix: docker docs type
fastapi/fastapi pull request #13048
Opened 2024-12-08 04:00 UTC by anklav24

2024-12-08 16:27 UTC, alv2017 approved these changes

2024-12-08 16:33 UTC, alv2017 requested changes
Hi @anklav24 

I suggest you to change the title of the PR:

- mention that you are fixing/updating **translated** document;
- mention the language of the document;
- it wouldn't harm to mention the reference of the document as well: docs/ru/docs/deployment/docker.md

So it won't get lost, and will be handled properly. :smiley:

2024-12-08 16:39 UTC, alv2017 commented
@anklav24 There is a discussion [Russion translation](https://github.com/fastapi/fastapi/discussions/9189), drop a message here as well (you will need 2-3 approvals for you PR to be accepted)

2024-12-09 12:32 UTC, alv2017 approved these changes

2024-12-11 08:10 UTC, gitgernit approved these changes

2024-12-12 22:48 UTC, merged

2024-12-12 22:48 UTC, alejsdev commented
Thanks for the update! @anklav24 :100: