🌐 Add Korean translation for `docs/ko/docs/tutorial/extra-models.md`
fastapi/fastapi pull request #13063
Opened 2024-12-12 11:02 UTC by jts8257

다음과 같이 번역하였습니다.
- unwrap -> 언랩(unwrap) #13061 의 accept 여부에 따라 번역 변경 예정
- unwraping -> 언래핑(unwrapping) #13061 의 accept 여부에 따라 번역 변경 예정
- type annotation -> 타입주석(type annotation)
- argument value -> 인자 값(argument value)

2025-02-10 16:55 UTC, yes0ng reviewed
Thank you for your excellent translation 👍 
I’m not very fluent in English, so I wrote the comment in Korean to better express my thoughts. Please let me know if the comment needs to be written in English :)

2025-02-10 16:55 UTC, yes0ng commented on docs/ko/docs/tutorial/extra-models.md
> +이 경우, 이를 **타입 주석(type annotation)** 이 아닌 **인자 값(argument value)** 으로 전달하고 있기 때문에 Python 3.10에서도 `Union`을 사용해야 합니다.
```suggestion
이 경우, 이를 **타입 어노테이션(type annotation)** 이 아닌 **인자 값(argument value)** 으로 전달하고 있기 때문에 Python 3.10에서도 `Union`을 사용해야 합니다.
```
타입 주석으로 번역할 경우 사람이 사용하는 주석(`/* */`나 `//` 같은)과 혼동될까 우려됩니다.
[파이썬 공식 문서](https://docs.python.org/ko/3/glossary.html#term-annotation) 번역에 따라 `annotaion`을 `어노테이션`으로 번역하는건 어떨지 의견드립니다.

2025-02-10 16:55 UTC, yes0ng commented on docs/ko/docs/tutorial/extra-models.md
> +만약 타입 주석에 사용한다면, 다음과 같이 수직 막대(|)를 사용할 수 있습니다:
```suggestion
만약 타입 어노테이션에 사용한다면, 다음과 같이 수직 막대(|)를 사용할 수 있습니다:
```

2025-02-10 16:55 UTC, yes0ng commented on docs/ko/docs/tutorial/extra-models.md
> +하지만 이를 `response_model=PlaneItem | CarItem`과 같이 할당하면 에러가 발생합니다. 이는 Python이 이를 타입 주석으로 해석하지 않고, `PlaneItem`과 `CarItem` 사이의 **잘못된 연산(invalid operation)**을 시도하기 때문입니다
```suggestion
하지만 이를 `response_model=PlaneItem | CarItem`과 같이 할당하면 에러가 발생합니다. 이는 Python이 이를 타입 어노테이션으로 해석하지 않고, `PlaneItem`과 `CarItem` 사이의 **잘못된 연산(invalid operation)**을 시도하기 때문입니다
```

2025-02-10 16:55 UTC, yes0ng commented on docs/ko/docs/tutorial/extra-models.md
> +절대 유저의 비밀번호를 평문으로 저장하지 마세요. 항상 이후에 검증 가능한 "안전한 해시(secure hash)"로 저장하세요.
```suggestion
절대 사용자의 비밀번호를 평문으로 저장하지 마세요. 항상 이후에 검증 가능한 "안전한 해시(secure hash)"로 저장하세요.
```
`유저`를 `사용자`로 번역하는게 어떨지 의견드립니다.

한국어 문서 전체적으로 `유저`와 `사용자`를 혼용해서 사용하는걸로 보이긴 하나,
바로 이전 문서인 [응답 모델](https://54a8563c.fastapitiangolo.pages.dev/ko/tutorial/response-model/)에서 사용자로 번역하였기에, 예제가 이어지는 해당 문서에서는 `사용자`로 작성하는게 자연스러울 것 같습니다.

2025-02-10 16:55 UTC, yes0ng commented on docs/ko/docs/tutorial/extra-models.md
> +특히 유저 모델의 경우에 그러한데, 왜냐하면:
```suggestion
특히 사용자 모델의 경우에 그러한데, 왜냐하면:
```

2025-02-10 16:55 UTC, yes0ng commented on docs/ko/docs/tutorial/extra-models.md
> +엔터티가 서로 다른 "상태"를 가져야 하는 경우, 엔터티당 단일 데이터 모델을 사용할 필요는 없습니다. 예를 들어, 유저 "엔터티"가 `password`, `password_hash`, 또는 비밀번호가 없는 상태를 포함할 수 있는 경우처럼 말입니다.
```suggestion
엔터티가 서로 다른 "상태"를 가져야 하는 경우, 엔터티당 단일 데이터 모델을 사용할 필요는 없습니다. 예를 들어, 사용자 "엔터티"가 `password`, `password_hash`, 또는 비밀번호가 없는 상태를 포함할 수 있는 경우처럼 말입니다.
```

2025-02-11 07:24 UTC, timothy-jeong commented on docs/ko/docs/tutorial/extra-models.md
> +이 경우, 이를 **타입 주석(type annotation)** 이 아닌 **인자 값(argument value)** 으로 전달하고 있기 때문에 Python 3.10에서도 `Union`을 사용해야 합니다.
@yes0ng 
good point, but let me check another korean translation references

2025-02-11 07:25 UTC, timothy-jeong commented on docs/ko/docs/tutorial/extra-models.md
> +절대 유저의 비밀번호를 평문으로 저장하지 마세요. 항상 이후에 검증 가능한 "안전한 해시(secure hash)"로 저장하세요.
@yes0ng 
another good point! thanks you

2025-02-11 07:44 UTC, timothy-jeong commented on docs/ko/docs/tutorial/extra-models.md
> +혹은 더 정확히 말하자면, `user_dict`를 직접 사용하여, 미래에 어떤 내용이 포함되더라도:
@yes0ng
Thanks to you, I've noticed that most translated Korean documents tend to add sentence endings.

While there are exceptions like the [tutorial/query-params](https://fastapi.tiangolo.com/ko/tutorial/query-params/) example, as long as completing the sentence doesn't change the original meaning, it seems like a good approach. 

I'll accept your suggestion!

2025-02-11 15:28 UTC, timothy-jeong commented on docs/ko/docs/tutorial/extra-models.md
> +이 경우, 이를 **타입 주석(type annotation)** 이 아닌 **인자 값(argument value)** 으로 전달하고 있기 때문에 Python 3.10에서도 `Union`을 사용해야 합니다.
Unfortunately, I couldn't find a suitable Korean translation for the term "type annotation." Instead, I found that many documents need to be updated.

[python-types](https://fastapi.tiangolo.com/ko/python-types/),
[tutorial/body](https://fastapi.tiangolo.com/ko/tutorial/body/),
[advanced/settings](https://fastapi.tiangolo.com/ko/advanced/settings/),
[tutorial/body-nested-models](https://fastapi.tiangolo.com/ko/tutorial/body-nested-models/)

2025-02-12 14:14 UTC, yes0ng approved these changes
LGTM 🔥

2025-02-19 04:31 UTC, sodaMelon commented on docs/ko/docs/tutorial/extra-models.md
> +# 추가 모델
I think we have to focus on meaning of **extra** model.🤔
current Korean subject isn't clear when read this. 

``추가 모델``이라고 했는데, ``추가``라는 말이 엑스트라 모델에는 뜻이 잘 안드러나는 것 같아요. 
``여분 모델``이나 ``엑스트라 모델``을 그대로 쓰는 건 어떠세요? 한국에서는 ``엑스트라``라는 말을 자주 쓰긴 합니다. (보조출연자라는 의미로요. 사실은 보조 모델으로 쓰기 위한 내용을 아래에 서술하고 있어서 적어봅니다..)

2025-02-19 04:45 UTC, sodaMelon commented on docs/ko/docs/tutorial/extra-models.md
> +혹은 더 정확히 말하자면, `user_dict`를 직접 사용하여, 미래에 어떤 내용이 포함되더라도 다음과 같이 생성합니다:
This sentence is not correct.
🤔 원문이랑 아예 안맞는데요?
(잠깐 고민해볼게요)

2025-02-19 05:01 UTC, sodaMelon commented on docs/ko/docs/tutorial/extra-models.md
> +혹은 더 정확히 말하자면, `user_dict`를 직접 사용하여, 미래에 어떤 내용이 포함되더라도 다음과 같이 생성합니다:
```suggestion
혹은 좀 더 정확하게, `user_dict`를 직접 사용합니다. :
(나중에 어떤 내용을 가지게 되더라도 *해당 딕셔너리의 모든 현재 키와 값을 자동으로 매개변수로 변환하여 전달한다. :역자 추가* )
```
added detail

2025-02-19 05:03 UTC, sodaMelon requested changes

2025-02-19 05:03 UTC, sodaMelon commented on docs/ko/docs/tutorial/extra-models.md
> +혹은 더 정확히 말하자면, `user_dict`를 직접 사용하여, 미래에 어떤 내용이 포함되더라도 다음과 같이 생성합니다:
"Or more exactly, using `user_dict` directly, with whatever contents it might have in the future:"라는 문장을 좀 더 살펴볼게요.

해당 문장의 앞에서 보여준 예시(매개변수들을 하나하나 명시적으로 입력하는 방식)는 현재 `user_dict`의 키와 값이 고정된 상태를 설명합니다. 하지만 실제로는 `user_dict`가 어떤 내용으로 구성되어 있는지에 따라 달라질 수 있기 때문에, 함수나 클래스에 `**user_dict`로 전달하면 *해당 딕셔너리의 모든 현재 키와 값을 자동으로 매개변수로 변환*하여 전달한다는 점을 **이번 문장에서** 강조하는 것입니다.

즉, `user_dict`의 키와 값이 바뀔 경우에도 `**user_dict`를 사용하면 자동으로 새로운 키와 값이 매핑되어 함수에 전달됩니다. 딕셔너리의 구조가 변동될 수 있을 때 매우 유용한 방식이라는 것을 나타내는 설명입니다.

원문 단어만으로는 사실 뉘앙스를 살리기 힘들어서... 
이정도는 추가해도 된다고 생각해요.

2025-02-19 05:14 UTC, sodaMelon commented on docs/ko/docs/tutorial/extra-models.md
> +#### 다른 Pydantic 모델의 데이터를 활용한 Pydantic 모델 생성
```suggestion
#### 다른 모델 데이터로 Pydantic 모델 생성
```

2025-02-19 05:14 UTC, sodaMelon commented on docs/ko/docs/tutorial/extra-models.md
> +...왜냐하면 `user_in.dict()`는 `dict`이며, 이를 `**`로 Python이 "언팩(unpack)"하도록 하여 `UserInDB`에 전달하기 때문입니다.
```suggestion
...왜냐하면 `user_in.dict()`는 `dict`이며, 이를 `**`로 Python이 "언팩"하도록 하여 `UserInDB`에 전달하기 때문입니다.
```

2025-02-19 05:16 UTC, sodaMelon commented on docs/ko/docs/tutorial/extra-models.md
> +#### `dict` 언패킹(Unpacking)과 추가 키워드
```suggestion
#### `dict` 언패킹과 추가 키워드
```

2025-02-19 08:26 UTC, sodaMelon requested changes

2025-02-19 08:27 UTC, timothy-jeong commented on docs/ko/docs/tutorial/extra-models.md
> +...왜냐하면 `user_in.dict()`는 `dict`이며, 이를 `**`로 Python이 "언팩(unpack)"하도록 하여 `UserInDB`에 전달하기 때문입니다.
@sodaMelon
Thank you very much for reviewing my PR.

Would you mind explaining why you prefer not to mix English with Korean in your commit messages? 
For your reference, the term was recently updated from "unwrap" to "unpack," and I intentionally included the English version to emphasize that change.

2025-02-19 08:28 UTC, sodaMelon commented on docs/ko/docs/tutorial/extra-models.md
> +혹은 더 정확히 말하자면, `user_dict`를 직접 사용하여, 미래에 어떤 내용이 포함되더라도 다음과 같이 생성합니다:
이부분 깃허브 시스템상 잘못 표기된것 같은데
코멘트 확인 부탁드립니다

2025-02-19 08:35 UTC, sodaMelon commented on docs/ko/docs/tutorial/extra-models.md
> +...왜냐하면 `user_in.dict()`는 `dict`이며, 이를 `**`로 Python이 "언팩(unpack)"하도록 하여 `UserInDB`에 전달하기 때문입니다.
@timothy-jeong 
here are the refs ( same content)
- https://fastapi.tiangolo.com/ja/tutorial/extra-models 
- https://fastapi.tiangolo.com/zh/tutorial/extra-models

2025-02-19 08:35 UTC, timothy-jeong commented on docs/ko/docs/tutorial/extra-models.md
> +# 추가 모델
@sodaMelon 
Thank you for your thorough review.

I must admit that I had been pondering how best to translate the term `extra`. Initially, I prioritized examples from previously translated documents—most notably, the example at [FastAPI's Korean tutorial](https://fastapi.tiangolo.com/ko/tutorial/extra-data-types/), where `extra` was translated as `추가` ("additional").

Since this document explains that it is not necessary to use only one Pydantic model to implement a particular use case, and that `additional` Pydantic models can also be used, I feel that `additional` better captures the intended nuance than `여분`.

Could you please explain in detail which aspects led you to feel that `여분` was more appropriate?

2025-02-19 08:48 UTC, timothy-jeong commented on docs/ko/docs/tutorial/extra-models.md
> +...왜냐하면 `user_in.dict()`는 `dict`이며, 이를 `**`로 Python이 "언팩(unpack)"하도록 하여 `UserInDB`에 전달하기 때문입니다.
@sodaMelon 
what an excellent reference! I always find it valuable to review translation examples from other languages.

However, in our Korean translated documents, we have several similar instances, such as:

like 
- [경로 매개변수](https://fastapi.tiangolo.com/ko/tutorial/path-params/#_17)
- [폼 모델](https://fastapi.tiangolo.com/ko/tutorial/request-form-models/#_3)
- [교차 출처 리소스공유](https://fastapi.tiangolo.com/ko/tutorial/cors/#_3) 
...

Additionally, incorporating English alongside Korean can actually enhance clarity in conveying the intended meaning.

I appreciate your review; however, if the rationale is "fixed repetition of words to make clear," I find it difficult to agree with that approach, especially since other Korean translation documents follow this convention.

2025-02-19 08:52 UTC, sodaMelon commented on docs/ko/docs/tutorial/extra-models.md
> +# 추가 모델
ah i understood your ref.
i thougth the context in the same kanji culture. 
now, If that's your intention, no problem. 👍

2025-02-19 08:53 UTC, timothy-jeong commented on docs/ko/docs/tutorial/extra-models.md
> +혹은 더 정확히 말하자면, `user_dict`를 직접 사용하여, 미래에 어떤 내용이 포함되더라도 다음과 같이 생성합니다:
@sodaMelon 
Oh, I'm sorry. While reading another review, I accidentally marked this excellent review as resolved. Thank you for waiting.

2025-02-19 08:59 UTC, sodaMelon commented on docs/ko/docs/tutorial/extra-models.md
> +...왜냐하면 `user_in.dict()`는 `dict`이며, 이를 `**`로 Python이 "언팩(unpack)"하도록 하여 `UserInDB`에 전달하기 때문입니다.
I think the problem is that the Korean rule was written too long ago.🤔(just written May, 2021. This is common with localization issues)

🤔🤔🤔If you need to sync with older docs, your way is great

2025-02-19 09:00 UTC, timothy-jeong commented on docs/ko/docs/tutorial/extra-models.md
> +혹은 더 정확히 말하자면, `user_dict`를 직접 사용하여, 미래에 어떤 내용이 포함되더라도 다음과 같이 생성합니다:
@sodaMelon 
yes your right, this sentence is not perfectly fit with original english document,
because in previous review, we little twist it,
and I 100% respect your point of view.

let's talk about this in the next conversation

2025-02-19 09:02 UTC, timothy-jeong commented on docs/ko/docs/tutorial/extra-models.md
> +#### 다른 Pydantic 모델의 데이터를 활용한 Pydantic 모델 생성
you clean up duplicated word! thank you

2025-02-19 09:21 UTC, timothy-jeong commented on docs/ko/docs/tutorial/extra-models.md
> +혹은 더 정확히 말하자면, `user_dict`를 직접 사용하여, 미래에 어떤 내용이 포함되더라도 다음과 같이 생성합니다:
@sodaMelon 
However, I'm a bit confused now.
If I understood you correctly, you're arguing that the sentence emphasizes the `flexibility of unpacking, like with **user_dict—as its advantage` 

Yet, when looking at the entire paragraph, it seems to simply indicate that you can directly use a dictionary's keys. Isn't it just presenting an alternative method rather than favoring one over the other? 

I haven't found any indication that one method is superior.

## Unpacking a dict

If we take a dict like user_dict and pass it to a function (or class) with **user_dict, Python will "unpack" it. It will pass the keys and values of the user_dict directly as key-value arguments.

So, continuing with the user_dict from above, writing:
```python
UserInDB(**user_dict)
```

would result in something equivalent to:

```python
UserInDB(
    username="john",
    password="secret",
    email="john.doe@example.com",
    full_name=None,
)
```

Or more exactly, using user_dict directly, with whatever contents it might have in the future:

```python
UserInDB(
    username = user_dict["username"],
    password = user_dict["password"],
    email = user_dict["email"],
    full_name = user_dict["full_name"],
)
```

2025-02-19 09:24 UTC, timothy-jeong commented on docs/ko/docs/tutorial/extra-models.md
> +그리고 다음과 같이 추가 키워드 인자 `hashed_password=hashed_password`를 포함하면:
@sodaMelon 

And then adding the extra keyword argument hashed_password=hashed_password, like in:


`포함하면` -> `추가하면` is very acceptable, but why do you think `추가` -> `여분` in this sentence? I need some explain 😢

2025-02-19 09:33 UTC, timothy-jeong commented on docs/ko/docs/tutorial/extra-models.md
> +...왜냐하면 `user_in.dict()`는 `dict`이며, 이를 `**`로 Python이 "언팩(unpack)"하도록 하여 `UserInDB`에 전달하기 때문입니다.
@sodaMelon 
yeah you can think about the korean rule is written too long ago. 
but in the reply section, as you know, we are talk about our standard.

It might come off as a bit blunt, but I think if we're going to change a convention, we should discuss it in our discussion forum.

2025-02-19 10:46 UTC, timothy-jeong commented on docs/ko/docs/tutorial/extra-models.md
> +#### `dict` 언패킹(Unpacking)과 추가 키워드
@sodaMelon 
based onour previous conversation, I think this issue has been resolved.

2025-02-19 10:55 UTC, timothy-jeong commented on docs/ko/docs/tutorial/extra-models.md
> +추가적으로 제공된 함수 `fake_password_hasher`와 `fake_save_user`는 데이터 흐름을 시연하기 위한 예제일 뿐이며, 실제 보안을 제공하지 않습니다.
@sodaMelon, regarding the sentence:

> "The supporting additional functions fake_password_hasher and fake_save_user are just to demo a possible flow of the data, but they of course are not providing any real security."

I believe that using `추가적으로 제공된 함수` is more appropriate than `지원된 추가적인 함수` for the following reasons (and I’d love to hear your thoughts as well):

1. It sounds odd to have both 지원된 and 추가적인 together.
2. Although "supporting" might be translated as 지원된 on a word-for-word basis, the overall context suggests that it refers to functions that are additionally provided (as in the case of fake_password_hasher).

2025-02-20 10:52 UTC, timothy-jeong commented
I rebase this branch and push the changes again

2025-02-20 10:53 UTC, timothy-jeong commented on docs/ko/docs/tutorial/extra-models.md
> +그리고 다음과 같이 추가 키워드 인자 `hashed_password=hashed_password`를 포함하면:
@sodaMelon 
I change `포함하면` to `추가하면` at this [commit](https://github.com/fastapi/fastapi/pull/13063/commits/900ba376762f1a5b71ed2463727ed0449b24b391)

2025-02-20 11:13 UTC, timothy-jeong commented on docs/ko/docs/tutorial/extra-models.md
> +혹은 더 정확히 말하자면, `user_dict`를 직접 사용하여, 미래에 어떤 내용이 포함되더라도 다음과 같이 생성합니다:
@sodaMelon  
I think this committed change makes sense. Please check out the [commit](https://github.com/fastapi/fastapi/pull/13063/commits/34884c4f114cfa8dbe3275c6d1286f7b6d1e5596) for details.

2025-05-30 13:38 UTC, merged