🌐 Add Chinese translation for `docs/zh/docs/advanced/async-tests.md`
fastapi/fastapi pull request #13074
Opened 2024-12-14 22:51 UTC by Zhongheng-Cheng

Add Chinese translation for `docs/zh/docs/advanced/async-tests.md`.
给 `docs/zh/docs/advanced/async-tests.md` 增加了中文翻译。

2024-12-15 17:04 UTC, Vincy1230 requested changes
为您提供一些优化建议，辛苦了！

2024-12-15 17:04 UTC, Vincy1230 commented on docs/zh/docs/advanced/async-tests.md
> +请注意，我们正在将 async/await 与新的 `AsyncClient` 一起使用 - 请求是异步的。
```suggestion
请注意，我们正在将 async/await 与新的 `AsyncClient` 一起使用——请求是异步的。
```

此处破折号似乎不太对劲，应该换成中文破折号。或者也可以试试翻译成冒号“：”，您看看哪种方式更好。

2024-12-15 17:23 UTC, Zhongheng-Cheng commented
@Vincy1230 感谢，确实修改之后更加通顺！

2024-12-15 17:34 UTC, Vincy1230 approved these changes
辛苦了！
Thanks for your work!

2024-12-17 21:49 UTC, merged

2024-12-17 21:49 UTC, alejsdev commented
Thank you! @Zhongheng-Cheng @Vincy1230 :rocket: :sparkles: