🌐 Add Chinese translation for `docs/zh/docs/advanced/openapi-webhooks.md`
fastapi/fastapi pull request #13091
Opened 2024-12-18 01:23 UTC by Zhongheng-Cheng

Add Chinese translation for `docs/zh/docs/advanced/openapi-webhooks.md`.
给 `docs/zh/docs/advanced/openapi-webhooks.md` 增加了中文翻译。

2024-12-18 20:12 UTC, Vincy1230 requested changes
辛苦了！这是一些修改建议，供您参考！

2024-12-18 20:12 UTC, Vincy1230 commented on docs/zh/docs/advanced/openapi-webhooks.md
> +### 检查文档
```suggestion
### 查看文档
```

2024-12-18 22:00 UTC, Zhongheng-Cheng commented
> 辛苦了！这是一些修改建议，供您参考！

Thanks! Looks better now!

2024-12-19 05:20 UTC, Vincy1230 approved these changes
LGTM :)

2024-12-19 06:06 UTC, under-tree approved these changes

2024-12-19 15:30 UTC, merged

2024-12-19 15:30 UTC, alejsdev commented
Thank you! @Zhongheng-Cheng :rocket: 
And thanks for your review @Vincy1230 :100: