🌐 Add Ukrainian translation for `docs/uk/docs/tutorial/middleware.md`
fastapi/fastapi pull request #13099
Opened 2024-12-20 21:56 UTC by ykertytsky

2024-12-22 21:38 UTC, rostik1410 requested changes

2024-12-22 21:38 UTC, rostik1410 commented on docs/uk/docs/tutorial/middleware.md
> +Ви модете додавати код, що буде запускатись з `request`, перед тим, як будь-яка *операція шляху* отримає його.
```suggestion
Ви можете додавати код, що буде запускатись з `request`, перед тим, як будь-яка *операція шляху* отримає його.
```

2024-12-22 21:39 UTC, rostik1410 commented
@ykertytsky looks good. just one little typo

2024-12-22 22:12 UTC, ykertytsky commented
Oooops, missed that one🫢

Fixed, thanks!

2024-12-22 23:47 UTC, rostyslav-ptashynskyi-breeoot approved these changes

2024-12-22 23:52 UTC, rostik1410 approved these changes

2024-12-22 23:58 UTC, rostyslav-ptashynskyi-breeoot commented
@ykertytsky @alejsdev  Sorry guys. I accidentally approved it from this account (work account of @rostik1410 ) Pls don't count approve from this account

2025-01-02 21:22 UTC, ykertytsky commented
I feel kinda confused.. I was trying to open another PR to put another trasnlation for review, but for some reason only option that i have while opening pull request is to add changes to this PR. How do i make this work?

2025-01-04 00:52 UTC, rostik1410 commented
> I feel kinda confused.. I was trying to open another PR to put another trasnlation for review, but for some reason only option that i have while opening pull request is to add changes to this PR. How do i make this work?

this happens because you did your PR from the master branch of your fork repository and I guess second one also was done in the master branch. For avoid any issues in the future pls create separate branches in you repository and then you will be able make several PR's and do not mix unrelated changes in one place

2025-02-19 20:08 UTC, rostik1410 commented
@mezgoodle @valentinDruzhinin could you guys pls review and approve this PR? Because looks like it was lost under tons of others

2025-02-19 23:23 UTC, valentinDruzhinin requested changes
Looks good! Just some little fixes, and may you rename the PR name? Because you translated another page :)

2025-02-19 23:23 UTC, valentinDruzhinin commented on docs/uk/docs/tutorial/body-updates.md
> +## Оновленння за допомогою `PUT`
```suggestion
## Оновлення за допомогою `PUT`
```

2025-02-19 23:23 UTC, valentinDruzhinin commented on docs/uk/docs/tutorial/body-updates.md
> +Ви можете використовувати `jsonable_encoder` щоб конвертувати вхідні дані у дані, які можуть зберігатись у форматі JSON (наприклад NoSQL бази даних). Наприклад, конвертувати `datetime` у `str`.
```suggestion
Ви можете використовувати `jsonable_encoder`, щоб конвертувати вхідні дані у дані, які можуть зберігатись у форматі JSON (наприклад NoSQL бази даних). Наприклад, конвертувати `datetime` у `str`.
```

2025-02-19 23:23 UTC, valentinDruzhinin commented on docs/uk/docs/tutorial/body-updates.md
> +`PUT` використовується, щоб отримати дані, які мають замінити вже інснуючі.
```suggestion
`PUT` використовується, щоб отримати дані, які мають замінити вже існуючі.
```

2025-02-19 23:23 UTC, valentinDruzhinin commented on docs/uk/docs/tutorial/body-updates.md
> +Це означаняє, що у випадку зміни елемента `bar` використовуючи `PUT`, що містить таке тіло:
```suggestion
Це означає, що у випадку зміни елемента `bar` використовуючи `PUT`, що містить таке тіло:
```

2025-02-19 23:23 UTC, valentinDruzhinin commented on docs/uk/docs/tutorial/body-updates.md
> +Ви **вільні** і можете використовувати їх як Ви забажаєте, **FastAPI** не створює ніяких обмежень відносно цього.
```suggestion
Ви **вільні** та можете використовувати їх як Ви забажаєте, **FastAPI** не створює ніяких обмежень відносно цього.
```

2025-02-19 23:23 UTC, valentinDruzhinin commented on docs/uk/docs/tutorial/body-updates.md
> +### Використання параметру `exclude_unset` з Pydantic
```suggestion
### Використання параметра `exclude_unset` з Pydantic
```

2025-02-19 23:23 UTC, valentinDruzhinin commented on docs/uk/docs/tutorial/body-updates.md
> +Якщо Ви хочете отримати часткове оновлення, дуже корисним буде використання параметру `exclude_unset` у моделі Pydantic `.model_dump()`.
```suggestion
Якщо Ви хочете отримати часткове оновлення, дуже корисним буде використання параметра `exclude_unset` у моделі Pydantic `.model_dump()`.
```

2025-02-19 23:23 UTC, valentinDruzhinin commented on docs/uk/docs/tutorial/body-updates.md
> +У Pydantic v1 метод називався `.dict()`, він застарів (але все ще підтримується) in Pydantic v2, і був переіменований на `.model_dump()`.
```suggestion
У Pydantic v1 метод називався `.dict()`, він застарів (але все ще підтримується) in Pydantic v2, і був перейменований на `.model_dump()`.
```

2025-02-19 23:23 UTC, valentinDruzhinin commented on docs/uk/docs/tutorial/body-updates.md
> +Це згенерує `dict` тільки з тими даними, що були встановлені при створені моделі `item`, виключаючи значення за замовчуванням.
```suggestion
Це згенерує `dict` тільки з тими даними, що були встановлені при створенні моделі `item`, виключаючи значення за замовчуванням.
```

2025-02-19 23:23 UTC, valentinDruzhinin commented on docs/uk/docs/tutorial/body-updates.md
> +У Pydantic v1 метод називався `.copy()`, він застарів (але все ще підтримується) in Pydantic v2, і був переіменований на `.model_copy()`.
```suggestion
У Pydantic v1 метод називався `.copy()`, він застарів (але все ще підтримується) in Pydantic v2, і був перейменований на `.model_copy()`.
```

2025-02-19 23:23 UTC, valentinDruzhinin commented on docs/uk/docs/tutorial/body-updates.md
> +### Пригадаємо як працють часткові оновлення
```suggestion
### Пригадаємо як працюють часткові оновлення
```

2025-02-19 23:23 UTC, valentinDruzhinin commented on docs/uk/docs/tutorial/body-updates.md
> +    * Таким чином ви можете оновити тільки ті дані, які були встановлені користувачем, замість перезапису значень, що вже збережеі з значеннями за замовчуванням у Вашій моделі.
```suggestion
    * Таким чином ви можете оновити тільки ті дані, які були встановлені користувачем, замість перезапису значень, що вже збережені зі значеннями за замовчуванням у Вашій моделі.
```

2025-02-19 23:23 UTC, valentinDruzhinin commented on docs/uk/docs/tutorial/body-updates.md
> +Щоб відрізняти моделі з опціональними значеннями для **оновлень** і моделі зі значеннями, необхідними для **створення**, ви можете використовувати ідеї, що описані у[Extra Models](extra-models.md){.i
```suggestion
Щоб відрізняти моделі з опціональними значеннями для **оновлень** і моделі зі значеннями, необхідними для **створення**, ви можете використовувати ідеї, що описані у [Extra Models](extra-models.md){.internal-link target=_blank}.
```

2025-02-21 08:47 UTC, closed without merging