⬆ Allow httpx 0.28.x, relax pins
fastapi/fastapi pull request #13114
Opened 2024-12-28 06:45 UTC by yan12125

2025-03-01 12:26 UTC, musicinmybrain commented
This works as a downstream patch in Fedora. Thank you!

2025-07-15 07:09 UTC, YuriiMotov requested changes
Let's simplify tests a bit by using `dirty_equals.IsOneOf`?

2025-07-15 07:09 UTC, YuriiMotov commented on tests/test_tutorial/test_custom_request_and_route/test_tutorial002.py
> +    ) | IsDict(
We can avoid duplicating this with the help of `dirty_equals.IsOneOf`:
```python
        {
            "detail": {
                "errors": [
                    {
                        "type": "list_type",
                        "loc": ["body"],
                        "msg": "Input should be a valid list",
                        "input": {"numbers": [1, 2, 3]},
                    }
                ],
                "body": IsOneOf('{"numbers": [1, 2, 3]}', '{"numbers":[1,2,3]}'),
            }
        }

```

2025-07-19 10:27 UTC, yan12125 commented
> Let's simplify tests a bit by using `dirty_equals.IsOneOf`?

Thank you, this is cool! Updated.

2025-07-19 12:20 UTC, YuriiMotov approved these changes
LGTM

2025-07-26 10:49 UTC, tiangolo approved these changes
Nice, thanks! 🚀

2025-07-26 10:49 UTC, merged