Portuguese translation for alternatives.md
fastapi/fastapi pull request #1325
Opened 2020-04-25 13:52 UTC by Serrones

2020-04-25 18:51 UTC, cassiobotaro requested changes
minor NIT's

2020-04-25 18:51 UTC, cassiobotaro commented on docs/pt/docs/alternatives.md
> +!!! nota
```suggestion
!!! note
```

2020-04-25 18:51 UTC, cassiobotaro commented on docs/pt/docs/alternatives.md
> +!!! checado "**FastAPI** inspirado para"
```suggestion
!!! check "**FastAPI** inspirado para"
```

2020-04-25 18:51 UTC, cassiobotaro commented on docs/pt/docs/alternatives.md
> +!!! checado "**FastAPI** inspirado para"
```suggestion
!!! check "**FastAPI** inspirado para"
```

2020-04-25 18:51 UTC, cassiobotaro commented on docs/pt/docs/alternatives.md
> +!!! checado "**FastAPI** isnpirado para"
```suggestion
!!! check "**FastAPI** isnpirado para"
```

2020-04-25 18:51 UTC, cassiobotaro commented on docs/pt/docs/alternatives.md
> +!!! checado "**FastAPI** inspirado para"
```suggestion
!!! check "**FastAPI** inspirado para"
```

2020-04-25 18:51 UTC, cassiobotaro commented on docs/pt/docs/alternatives.md
> +!!! checado "**FastAPI** inspirado para"
```suggestion
!!! check "**FastAPI** inspirado para"
```

2020-04-25 18:51 UTC, cassiobotaro commented on docs/pt/docs/alternatives.md
> +!!! checado "**FastAPI** inspirado para"
```suggestion
!!! check "**FastAPI** inspirado para"
```

2020-04-25 18:51 UTC, cassiobotaro commented on docs/pt/docs/alternatives.md
> +!!! checado "**FastAPI** inspirado para"
```suggestion
!!! check "**FastAPI** inspirado para"
```

2020-04-25 18:51 UTC, cassiobotaro commented on docs/pt/docs/alternatives.md
> +!!! checado "**FastAPI** inspirado para"
```suggestion
!!! check "**FastAPI** inspirado para"
```

2020-04-25 18:51 UTC, cassiobotaro commented on docs/pt/docs/alternatives.md
> +!!! checado "**FastAPI** inspirado para"
```suggestion
!!! check "**FastAPI** inspirado para"
```

2020-04-25 18:51 UTC, cassiobotaro commented on docs/pt/docs/alternatives.md
> +!!! nota "Detalhes técnicos"
```suggestion
!!! note "Detalhes técnicos"
```

2020-04-25 18:51 UTC, cassiobotaro commented on docs/pt/docs/alternatives.md
> +!!! checado "**FastAPI** inspirado para"
```suggestion
!!! check "**FastAPI** inspirado para"
```

2020-04-25 18:51 UTC, cassiobotaro commented on docs/pt/docs/alternatives.md
> +!!! checado "**FastAPI** inspirado para"
```suggestion
!!! check "**FastAPI** inspirado para"
```

2020-04-25 18:51 UTC, cassiobotaro commented on docs/pt/docs/alternatives.md
> +!!! checado "**FastAPI** inspirado para"
```suggestion
!!! check "**FastAPI** inspirado para"
```

2020-04-25 18:51 UTC, cassiobotaro commented on docs/pt/docs/alternatives.md
> +!!! checado "Idéias inspiradas para o **FastAPI**"
```suggestion
!!! check "Idéias inspiradas para o **FastAPI**"
```

2020-04-25 18:51 UTC, cassiobotaro commented on docs/pt/docs/alternatives.md
> +!!! checado "**FastAPI** inspirado para"
```suggestion
!!! check "**FastAPI** inspirado para"
```

2020-04-25 18:51 UTC, cassiobotaro commented on docs/pt/docs/alternatives.md
> +!!! checado "**FastAPI** usa isso para"
```suggestion
!!! check "**FastAPI** usa isso para"
```

2020-04-25 18:51 UTC, cassiobotaro commented on docs/pt/docs/alternatives.md
> +!!! nota "Detalhes Técnicos"
```suggestion
!!! note "Detalhes Técnicos"
```

2020-04-25 18:51 UTC, cassiobotaro commented on docs/pt/docs/alternatives.md
> +!!! checado "**FastAPI** usa isso para"
```suggestion
!!! check "**FastAPI** usa isso para"
```

2020-04-25 18:51 UTC, cassiobotaro commented on docs/pt/docs/alternatives.md
> +!!! checado "**FastAPI** recomenda isso para"
```suggestion
!!! check "**FastAPI** recomenda isso para"
```

2020-04-26 01:50 UTC, cassiobotaro approved these changes

2020-04-26 01:50 UTC, cassiobotaro commented
Thanks @Serrones !

2020-05-17 11:31 UTC, tiangolo commented
Awesome, thank you @Serrones ! :rocket: :tada: 

I just added a couple of small format and wording changes :heavy_check_mark: 

And thanks @cassiobotaro for the review! :nerd_face: :coffee:

2020-05-17 11:32 UTC, merged