traduccion de alternatives.md
fastapi/fastapi pull request #1346
Opened 2020-04-28 22:11 UTC by jorgerpo

**traduccion de alternatives.md**

2020-07-03 09:30 UTC, mariacamilagl commented
Hi @jorgerpo, thank you for your contribution.  ☕ 🌮 

I was just seeing that the translation is not finished, right? ⚙️ 

The next steps would be then to finish translating the entire file and erasing the extra files that seem to have been included in git. 🚀 

If you need further guidelines about the style of the translation you can refer to the original issue 😃  https://github.com/tiangolo/fastapi/issues/1218

2020-07-03 14:30 UTC, jorgerpo commented
Hello Camila
In my mind is was finished.
I'll check
I think that maybe I didn't run the markdown parser to verify how it outputs the html

for instance, when it says **!!!check**
I wrote **!!!mira**

And after sending the pull request I realized that wasn't meant to be translated.

But I am very open to check and finish if you please point out what is still undone.

2020-07-03 14:50 UTC, jorgerpo commented
![imagen](https://user-images.githubusercontent.com/12537771/86479702-43a26a80-bd12-11ea-9e2e-6ba87b5df58f.png)
para clarificar, lo que traduje fue alternatives.md
No sé como verificar que el markdown esté procesando bien
en la imagen se ve que donde decía !!! check yo puse !!! mira
y donde decía !!! note , puse !!! nota

creo que es lo único que falta

si me ayudas a verifcar eso, lo dejo listo y podría seguir traduciendo otras páginas
y perdon la primiparada en estos temas
gracias

2020-07-03 15:34 UTC, mariacamilagl requested changes
Thank you for your contribution @jorgerpo ! 🌮 

I added some comments here so you can check what's missing in the translation and the files that should be removed.

Don't worry, we were all beginners once 😃 Your effort is appreciated! 🚀

2020-07-03 15:34 UTC, mariacamilagl commented on docs/es/docs/alternatives.md
> +Given the simplicity of Flask, it seemed like a good match for building APIs. The next thing to find was a "Django REST Framework" for Flask.
Hi @jorgerpo, thank you for your super fast reply!  🚀 

As you can check here, from this line forward this file is in English.

2020-07-03 15:34 UTC, mariacamilagl commented on docs/es/docs/benchmarks.md
> +# Benchmarks
Please remove this file. 😄

2020-07-03 15:34 UTC, mariacamilagl commented on docs/es/docs/deployment.md
> +# Deployment
Please remove this file. 😄

2020-07-03 15:34 UTC, mariacamilagl commented on docs/es/docs/project-generation.md
> +# Project Generation - Template
Please remove this file. 😄

2020-07-03 15:34 UTC, mariacamilagl commented on docs/es/docs/release-notes.md
> +# Release Notes
Please remove this file. 😄

2023-06-26 16:41 UTC, tiangolo commented
I'm gonna close this one for now, to clean up stale PRs. But if you get the chance to fix those things at some point later, feel free to create a new PR! Thanks for the effort. ☕

2023-06-26 16:41 UTC, closed without merging