Update the mkdocs config, add the Spanish contributor's guide and
fastapi/fastapi pull request #1353
Opened 2020-04-29 20:19 UTC by blaisep

update the missing translation list.
@mariacamilagl perdona la demora y no tengas reparo en corregir. De pronto me di cuenta de que esta página representa la voz del jefe y presumo que @tiangolo querrá cambiarla a su gusto.

2020-05-14 16:03 UTC, AdrianDeAnda commented on docs/es/docs/contributing.md
> +# Desarollo - Aportando
```suggestion
# Desarrollo - Aportando
```

2020-05-14 16:05 UTC, AdrianDeAnda commented on docs/es/docs/contributing.md
> +## Desarollo
```suggestion
## Desarrollo
```

2020-05-14 16:05 UTC, AdrianDeAnda commented on docs/es/docs/contributing.md
> +Y ahora utilzas `flit` para installar las dependencias para el desarollo:
```suggestion
Y ahora utilzas `flit` para installar las dependencias para el desarrollo:
```

2020-05-14 16:05 UTC, AdrianDeAnda commented on docs/es/docs/contributing.md
> +Durante el desarollo local, se utiliza un script que construye el sitio y detecta cambios, recargando sobre la marcha.
```suggestion
Durante el desarrollo local, se utiliza un script que construye el sitio y detecta cambios, recargando sobre la marcha.
```

2020-05-14 16:40 UTC, blaisep commented on docs/es/docs/contributing.md
> +Durante el desarollo local, se utiliza un script que construye el sitio y detecta cambios, recargando sobre la marcha.
Oops!! Thank you AdrianDeAnda.

2020-05-14 19:36 UTC, blaisep commented on docs/es/docs/contributing.md
> +## Desarollo
Muchisimas gracias

2020-07-03 14:51 UTC, mariacamilagl requested changes
Thank you @blaisep for your contribution, and thank you @AdrianDeAnda for your review! 🎉 ☕ 

Also thanks for your patience! 😃 

I have added some suggestions that you can accept directly.

2020-07-03 14:51 UTC, mariacamilagl commented on docs/es/docs/contributing.md
> +* Utiliz las mismas imágenes, nombres de ficheros y enlaces. No hace falta cambiar nada para que funcione.
```suggestion
* Utiliza las mismas imágenes, nombres de ficheros y enlaces. No hace falta cambiar nada para que funcione.
```

2020-07-03 14:51 UTC, mariacamilagl commented on docs/es/docs/contributing.md
> +* Pega el ficher en el mismo lugar, correspondiente al idioma al que quieres traducir, por ejemplo:
```suggestion
* Pega el fichero en el mismo lugar, correspondiente al idioma al que quieres traducir, por ejemplo:
```

2020-07-03 14:51 UTC, mariacamilagl commented on docs/es/docs/contributing.md
> +Consultando la tabla de códigos, veras que la secuencia para "Creole" es `ht`.
```suggestion
Consultando la tabla de códigos, verás que la secuencia para "Creole" es `ht`.
```

2020-07-03 14:51 UTC, mariacamilagl commented on docs/es/docs/contributing.md
> +Lo sigiuente sería ejecutar el script que genera un nuevo directorio de traducciones:
```suggestion
Lo siguiente sería ejecutar el script que genera un nuevo directorio de traducciones:
```

2020-07-03 14:51 UTC, mariacamilagl commented on docs/es/docs/contributing.md
> +Now you can check in your code editor the newly created directory `docs/ht/`.
```suggestion
```

2020-07-03 14:51 UTC, mariacamilagl commented on docs/es/docs/contributing.md
> +    Asi otros podrán aportar cambios mientras traduces. 🚀
```suggestion
    Así otros podrán aportar cambios mientras traduces. 🚀
```

2020-07-03 14:51 UTC, mariacamilagl commented on docs/es/docs/contributing.md
> +En ese case, edita el `mkdocs.yml` para tu nuevo idioma:
```suggestion
En ese caso, edita el `mkdocs.yml` para tu nuevo idioma:
```

2020-07-03 14:51 UTC, mariacamilagl commented on docs/es/docs/contributing.md
> +Cuando ejectas el script `./scripts/docs.py` con el parámetro `live` sólo muestra los ficheros disponibles en el entorno local.
```suggestion
Cuando ejecutas el script `./scripts/docs.py` con el parámetro `live` sólo muestra los ficheros disponibles en el entorno local.
```

2020-07-03 14:51 UTC, mariacamilagl commented on docs/es/docs/contributing.md
> +Luego, el comando construye el sitio de MkDocs para cada idioma, los combina y finalmente produce las salida dentro de `./site/`.
```suggestion
Luego, el comando construye el sitio de MkDocs para cada idioma, los combina y finalmente produce las salidas dentro de `./site/`.
```

2020-07-03 14:51 UTC, mariacamilagl commented on docs/es/docs/contributing.md
> +Ahora podrás traducir el resto ye verás cómo aparece segun vayas progresando.
```suggestion
Ahora podrás traducir el resto, ya verás cómo aparece según vayas progresando.
```

2020-07-03 14:51 UTC, mariacamilagl commented on docs/es/docs/contributing.md
> +### Translations
```suggestion
### Traducciones
```

2020-07-03 14:51 UTC, mariacamilagl commented on docs/es/docs/contributing.md
> +Se agradecen muchísimo cualquier ayuda con los documententos, puesto que es imposible sin el apoyo de la comunidad. 🌎 🚀
```suggestion
Se agradece muchísimo cualquier ayuda con las traducciones, puesto que es imposible hacerlas sin el apoyo de la comunidad. 🌎 🚀
```

2020-07-03 14:51 UTC, mariacamilagl commented on docs/es/docs/contributing.md
> +Si instalas Typer CLI, puedes obtener auto-completamiento:
```suggestion
Tambien puedes aprovechar <a href="https://typer.tiangolo.com/typer-cli/" class="external-link" target="_blank">Typer CLI</a>, para obtener auto-completado.

Si instalas Typer CLI, puedes obtener auto-completado:
```

2020-07-03 14:51 UTC, mariacamilagl commented on docs/es/docs/contributing.md
> +#### Typer CLI (optional)
```suggestion
#### Typer CLI (opcional)
```

2020-07-04 05:44 UTC, blaisep commented
Listo, @mariacamilagl

2020-07-14 16:03 UTC, AdrianDeAnda approved these changes

2020-12-30 21:30 UTC, pedabraham requested changes

2020-12-30 21:30 UTC, pedabraham commented on docs/es/docs/contributing.md
> +Lo primero es comprobar que tienes tu entorno tal como hemos descrito, as se instalarán todos los requisitos.
```suggestion
Lo primero es comprobar que tienes tu entorno tal como hemos descrito, así se instalarán todos los requisitos.
```

2020-12-30 21:30 UTC, pedabraham commented on docs/es/docs/contributing.md
> +Todo el contenido de los documentos se encuentra en formato Markdown dentro del directorio `./docs/en/`. El texto en castellano se encuentra
```suggestion
Todo el contenido de la documentación se encuentra en formato Markdown dentro del directorio `./docs/en/`. El texto en castellano se encuentra
```

2020-12-30 21:30 UTC, pedabraham commented on docs/es/docs/contributing.md
> +* La mayoria de las prestaciones se describen en los documentos, comprobado por cobertura.
```suggestion
* La mayoría de las funciones se describen en los documentos, aseguradas por pruebas de cobertura.
```

2021-04-21 03:20 UTC, jovicon requested changes
There are some proposed changes and some fixes too.

2021-04-21 03:20 UTC, jovicon commented on docs/es/docs/contributing.md
> +Si ya has copiado el repositorio y sabes con certeza que necesitas indagar a fondo el código fuente,
```suggestion
Si ya has copiado el repositorio y sabes con certeza que necesitas indagar a fondo del código fuente,
```

2021-04-21 03:20 UTC, jovicon commented on docs/es/docs/contributing.md
> +* Los ejemplos se pueden ejectuar tál como están.
```suggestion
* Los ejemplos se pueden ejecutar tál como están.
```

2021-04-21 03:20 UTC, jovicon commented on docs/es/docs/contributing.md
> +como Uvicorn utiliza el puerto `8000` por defecto, los documentos en `8008` no confligen.
```suggestion
como Uvicorn utiliza el puerto `8000` por defecto, los documentos en el puerto `8008` no chocarán.
```

2021-07-21 21:26 UTC, blaisep commented
Thank you @pedabraham , @jovicon , I think I committed all the fixes. I'm sorry for the delay. I moved from California to Massachusetts and I expect that now I will be more responsive.

2024-02-07 12:51 UTC, tiangolo commented
As this PR had requested changes to be applied but has been inactive for a while, it's now going to be closed. But if there's anyone interested, feel free to create a new PR.

2024-02-07 12:51 UTC, closed without merging