Add Chinese docs for advanced/path-operation-advanced-configuration.md
fastapi/fastapi pull request #1447
Opened 2020-05-21 06:49 UTC by RunningIkkyu

Add Chinese docs for advanced/path-operation-advanced-configuration.md. Could you help review plz. @waynerv  @Dustyposa

2020-05-23 12:41 UTC, waynerv requested changes

2020-05-23 12:41 UTC, waynerv commented on docs/zh/docs/advanced/path-operation-advanced-configuration.md
> +你可以通过参数 `operation_id` 将 OpenAPI 的 `operationId` 设置为在路径操作中使用。
你可以在路径操作中通过参数 `operation_id` 设置要使用的 OpenAPI `operationId`。

2020-05-23 12:41 UTC, waynerv commented on docs/zh/docs/advanced/path-operation-advanced-configuration.md
> +你可以通过参数 `operation_id` 将 OpenAPI 的 `operationId` 设置为在路径操作中使用。
The segmentation should be "You can set the OpenAPI operationId to be used | in your path operation | with the parameter operation_id."

2020-05-23 12:41 UTC, waynerv commented on docs/zh/docs/advanced/path-operation-advanced-configuration.md
> +务必确保每次操作的 `operation_id` 都是唯一的。
"each operation" could translate to  "每个路径操作“

2020-05-23 12:41 UTC, waynerv commented on docs/zh/docs/advanced/path-operation-advanced-configuration.md
> +在此之前你要给所有函数添加 *路径操作*。
你应该在添加了所有路径操作之后执行此操作。

2020-05-23 12:41 UTC, waynerv commented on docs/zh/docs/advanced/path-operation-advanced-configuration.md
> +    如果你手动调动 `app.openapi()`，你应该在此之前更新 `operationId`。
”call“ always translate to "调用".Is here a typo?

2020-06-04 08:25 UTC, RunningIkkyu commented
@waynerv  Thanks for your review.

2020-06-04 12:34 UTC, waynerv approved these changes

2020-06-15 10:08 UTC, RunningIkkyu commented
@Dustyposa @phy25 @yanever @Laineyzhang55   Please take a look.

2020-11-21 14:42 UTC, Laineyzhang55 approved these changes

2020-11-25 17:10 UTC, tiangolo commented
Thank you @RunningIkkyu ! :clap: :clap: :cake: 

And thanks @waynerv and @Laineyzhang55 for the reviews :bowing_man: :coffee:

2020-11-25 17:12 UTC, merged