Add Chinese docs for advanced/response-directly
fastapi/fastapi pull request #1452
Opened 2020-05-22 09:16 UTC by RunningIkkyu

Add Chinese docs for advanced/response-directly

2020-05-23 12:56 UTC, waynerv requested changes

2020-05-23 12:56 UTC, waynerv commented on docs/zh/docs/advanced/response-directly.md
> +**FastAPI** 默认会使用 `jsonable_encoder` 将这些类型的返回值转换成 JSON 格式，`jsonable_encoder` 在 [JSON 编码器兼容](../tutorial/encoder.md){.internal-link target=_blank} 中有阐述。
"JSON Compatible Encoder" should be "JSON兼容编码器“

2020-05-23 12:56 UTC, waynerv commented on docs/zh/docs/advanced/response-directly.md
> +当你返回一个 `Response` 时，**FastAPI** 会自动忽略它。
”自动忽略“ could be ”直接传递“

2020-05-23 12:56 UTC, waynerv commented on docs/zh/docs/advanced/response-directly.md
> +The example above shows all the parts you need, but it's not very useful yet, as you could have just returned the `item` directly, and **FastAPI** would put it in a `JSONResponse` for you, converting
This line should be deleted.

2020-05-23 12:56 UTC, waynerv commented on docs/zh/docs/advanced/response-directly.md
> +当你直接返回 `Response` 时，它的数据既没有校验，又不会进行转换（序列化），也不会进行自动化文档。
"进行自动化文档" is a little weird.May be we should use "自动生成文档” here.

2020-06-15 10:07 UTC, RunningIkkyu commented
@Dustyposa @phy25 @yanever @Laineyzhang55  @waynerv Please take a look.

2020-06-15 12:40 UTC, waynerv approved these changes

2020-11-21 14:43 UTC, Laineyzhang55 approved these changes

2020-11-25 17:20 UTC, tiangolo commented
Awesome! Thank you @RunningIkkyu :cake: 

And thanks @waynerv and @Laineyzhang55 for the reviews :mag: :coffee:

2020-11-25 17:22 UTC, merged