Add Chinese docs for advance/custom-response.md
fastapi/fastapi pull request #1459
Opened 2020-05-23 09:52 UTC by RunningIkkyu

Add Chinese docs for advance/custom-response.md 
Please help review. @waynerv  @Dustyposa

2020-05-26 02:36 UTC, waynerv requested changes

2020-05-26 02:36 UTC, waynerv commented on docs/zh/docs/advanced/custom-response.md
> +但你可以直接返回 `Response`，返回数据不会自动转换，也不会自动生成文档（例如，在 HTTP 头 `Content-Type` 中包含特定的「媒体类型」作为生成的 OpenAPI 的一部分）。
missing the word "if",should be "但如果你直接返回一个 `Response`"

2020-05-26 02:36 UTC, waynerv commented on docs/zh/docs/advanced/custom-response.md
> +并且如果该 `Response` 有一个 JSON 媒体类型（`application/json`），比如使用 `JSONResponse` 或者 `UJSONResponse` 的时候，你返回的数据会自动转换成任何你在 *路径操作装饰器* 中声明的 Pydantic 的 `response_model` 类型。
Missing words "(and filtered) ".And "converted with" might means "using Pydantic response_model to converte" not "convert to"

2020-05-26 02:36 UTC, waynerv commented on docs/zh/docs/advanced/custom-response.md
> +* 将 `HTMLResponse` 作为你的 *路径操作* 的 `content_type` 参数传入。
There is a mistake in english docs,the `content_type` here should be "response_class"

2020-05-26 02:36 UTC, waynerv commented on docs/zh/docs/advanced/custom-response.md
> +如果你想要在函数内容重载响应，但是同时在 OpenAPI 中文档化「媒体类型」，你可以使用 `response_class` 参数并返回一个 `Response` 对象。
"内容“ should be "内".

2020-05-26 02:36 UTC, waynerv commented on docs/zh/docs/advanced/custom-response.md
> +接着`response_class` 参数只会被用来文档化 OpenAPI 的 *路径操作*，你的 `Response` 也是如此。
你的 `Response` 用来返回响应

2020-06-15 10:08 UTC, RunningIkkyu commented
@Dustyposa @phy25 @yanever @Laineyzhang55  @waynerv Please take a look.

2020-06-15 12:42 UTC, waynerv approved these changes

2020-11-21 14:45 UTC, Laineyzhang55 approved these changes

2020-11-25 17:21 UTC, tiangolo commented
Thank you @RunningIkkyu ! :rocket: :nerd_face: 

And thanks again for the reviews @waynerv and @Laineyzhang55 :bowing_man: :clap:

2020-11-25 17:27 UTC, merged