Add Chinese translation for path-params-numeric-validations.md
fastapi/fastapi pull request #1506
Opened 2020-06-03 07:02 UTC by waynerv

@Dustyposa @RunningIkkyu @phy25 @yanever @Laineyzhang55 Please take a look.

2020-06-03 14:16 UTC, Laineyzhang55 approved these changes
没什么大问题

2020-06-15 09:19 UTC, RunningIkkyu requested changes

2020-06-15 09:19 UTC, RunningIkkyu commented on docs/zh/docs/tutorial/path-params-numeric-validations.md
> +Python 将会报错如果你将带有「默认值」的参数放在没有「默认值」的参数之前。
Adjust the word order of the sentence: 

> 如果你将带有「默认值」的参数放在没有「默认值」的参数之前，Python 将会报错。

2020-06-17 06:50 UTC, yanever approved these changes

2020-06-27 18:10 UTC, merged

2020-06-27 18:10 UTC, tiangolo commented
Awesome! Thank you! :rocket: :tada: :cake: