Added Italian translation to docs file index.md
fastapi/fastapi pull request #1576
Opened 2020-06-15 10:34 UTC by csr

This PR translates the index.md to Italian. This page was already present in the mkdocs.yml file.

2021-01-23 21:28 UTC, pieromacaluso approved these changes
I inserted just a few typos and comments on the translation. After these quick fixes, it could be approved.

2021-01-23 21:28 UTC, pieromacaluso commented on docs/it/docs/index.md
> +## Esempio più avanzato
Maybe "Esempio di aggiornamento" could be better for the context.

2021-01-23 21:28 UTC, pieromacaluso commented on docs/it/docs/index.md
> +Puoi farlo usando le annotazioni di tipo standard di Python.
Suggestion: "le annotazioni ~~di tipo~~ standard"

2021-01-23 21:28 UTC, pieromacaluso commented on docs/it/docs/index.md
> +Dichiara il _body_ usando le annotazioni di tipo standard di Python, grazie a Pydantic.
Suggestion: "le annotazioni ~~di tipo~~ standard"

2021-01-23 21:28 UTC, pieromacaluso commented on docs/it/docs/index.md
> +FastAPI è un web framework moderno e veloce (ad alte prestazioni) per progettare API con Python 3.6+, basato sulle annotazioni di tipo standard di Python.
Suggestion: "le annotazioni ~~di tipo~~ standard"

2021-01-23 21:28 UTC, pieromacaluso commented on docs/it/docs/index.md
> +Non c'è bisogno di imparare una nuova sintassi, metodi o classi specifici a una libreria, ecc.
"Non c'è bisogno di imparare nuovi metodi, sintassi o classi di una specifica libreria, ecc."
[reference](https://www.impariamoinsieme.com/aggettivo-e-concordanza-con-il-nome/#:~:text=Gli%20aggettivi%20concordano%20sempre%20nel,pi%C3%B9%20il%20discorso%20%C3%A8%20diverso.&text=se%20i%20nomi%20sono%20tutti,concorda%20al%20femminile%20plurale.)

2021-01-23 21:28 UTC, pieromacaluso commented on docs/it/docs/index.md
> +    * Controlle che abbia un attributo obbligatorio `name`, e che sia una `str`.
"Controlla" or "Controllerà"

2021-01-30 17:56 UTC, csr commented
Thank you so much @pieromacaluso! I'll try to get this done asap.

2021-09-28 19:37 UTC, rpalloni commented on docs/it/docs/index.md
> +    <em>Framework FastAPI, alte prestazioni, facile da imparare, veloce da programmare, pronto per il rilascio in produzione</em>
<em>Framework FastAPI, elevate prestazioni, facile da imparare, veloce da programmare, pronto per il rilascio in produzione</em>

2021-09-28 19:50 UTC, rpalloni requested changes
IT docs suggestions

2021-09-28 19:50 UTC, rpalloni commented on docs/it/docs/index.md
> +    <em>Framework FastAPI, alte prestazioni, facile da imparare, veloce da programmare, pronto per il rilascio in produzione</em>
<em>Framework FastAPI, prestazioni elevate, facile da imparare, veloce da programmare, pronto per il rilascio in produzione</em>

2021-09-28 19:50 UTC, rpalloni commented on docs/it/docs/index.md
> +FastAPI è un web framework moderno e veloce (ad alte prestazioni) per progettare API con Python 3.6+, basato sulle annotazioni di tipo standard di Python.
(con prestazioni elevate)

2021-09-28 19:50 UTC, rpalloni commented on docs/it/docs/index.md
> +* **Breve**: Minimizza la duplicazione di codice. Multiple funzionalità con ciascuna dichiarazione di parametri. Meno errori.
* **Sintetico**

2021-09-28 19:50 UTC, rpalloni commented on docs/it/docs/index.md
> +Se vuoi approfondire, consulta la sezione _"In a hurry?"_ su <a href="https://fastapi.tiangolo.com/async/#in-a-hurry" target="_blank">`async` e `await` nella documentazione</a>.
_"Di fretta?"_

2022-01-31 14:54 UTC, bsab commented on docs/it/docs/index.md
> +* **Veloce da programmare**: Velocizza il lavoro consentendoti di rilasciare nuove funzionalità tra il 200% e il 300% più velocemente. *
```suggestion
* **Veloce da programmare**: Velocizza il lavoro consentendo il rilascio di nuove funzionalità tra il 200% e il 300% in maniera più rapida. *
```

2022-01-31 14:54 UTC, bsab commented on docs/it/docs/index.md
> +* **Robusto**: Scrivi codice pronto per essere rilasciato in produzione con una documentazione dell'API interattiva generata automaticamente.
```suggestion
* **Robusto**: Scrittura di codice pronto per essere rilasciato in produzione con una documentazione dell'API interattiva generata automaticamente.
```

2022-01-31 14:54 UTC, bsab commented on docs/it/docs/index.md
> +<small>* Questa stima è basata su test eseguiti all'interno di un team di sviluppo di applicazioni professionali.</small>
```suggestion
<small>* Stima basata sull'esito di test eseguiti da un team di sviluppo per applicazioni professionali.</small>
```

2022-01-31 14:54 UTC, bsab commented on docs/it/docs/index.md
> +Avrai anche bisogno di un server ASGI per il rilascio in produzione come <a href="http://www.uvicorn.org" class="external-link" target="_blank">Uvicorn</a> oppure <a href="https://gitlab.com/pgjones/
```suggestion
Per il rilascio in produzione, sarà necessario un server ASGI come <a href="http://www.uvicorn.org" class="external-link" target="_blank">Uvicorn</a> oppure <a href="https://gitlab.com/pgjones/hypercorn" class="external-link" target="_blank">Hypercorn</a>.
```

2022-01-31 14:54 UTC, bsab commented on docs/it/docs/index.md
> +* `app`: l'oggetto creato dentro `main.py` con la riga di codice `app = FastAPI()`.
```suggestion
* `app`: l'oggetto istanziato all'interno del `main.py` tramite l'istruzione `app = FastAPI()`.
```

2022-01-31 14:54 UTC, bsab commented on docs/it/docs/index.md
> +* Riceve richieste HTTP ai _paths_ `/` e `/items/{item_id}`.
```suggestion
* Riceve richieste HTTP sui _paths_ `/` e `/items/{item_id}`.
```

2022-01-31 14:54 UTC, bsab commented on docs/it/docs/index.md
> +* Entrambi i _paths_ ricevono `GET` <em>operations</em> (anche chiamati <abbr title="metodi HTTP">HTTP _methods_</abbr>).
```suggestion
* Entrambi i _paths_ accettano`GET` <em>operations</em> (conosciuti anche come <abbr title="metodi HTTP">HTTP _methods_</abbr>).
```

2022-01-31 14:54 UTC, bsab commented on docs/it/docs/index.md
> +### Aggiornamento della documentazione alternativa
I am not convinced :/

2022-01-31 14:54 UTC, bsab commented on docs/it/docs/index.md
> +### Ricapitolando
```suggestion
### Riepilogo
```

2022-01-31 14:54 UTC, bsab commented on docs/it/docs/index.md
> +Per esempio, per un `int`:
```suggestion
Per esempio, per il tipo `int`:
```

2022-01-31 14:54 UTC, bsab commented on docs/it/docs/index.md
> +...e osserva come il tuo editor di testo autocompleterà gli attributi e saprà i loro tipi:
```suggestion
...e osserva come il tuo editor di testo autocompleterà gli attributi e sarà in grado di conoscere i loro tipi:
```

2022-01-31 14:54 UTC, bsab commented on docs/it/docs/index.md
> +Questa è solo la punta dell'iceberg, ma dovresti avere già un'idea di come il tutto funziona.
```suggestion
Questa è solo la punta dell'iceberg, ma si dovrebbe avere già un'idea di come il tutto funziona.
```

2022-02-01 09:20 UTC, bsab requested changes
I have added some comments and changes. I think the file can be merged.

2022-02-01 09:23 UTC, csr commented
Thank you so much for contributing and for suggesting changes. I'm not actively participating in the translation efforts any longer but I would encourage you to create a separate pull request with all this good stuff.

2022-02-01 09:23 UTC, closed without merging