Add Japanese translation for features.md
fastapi/fastapi pull request #1625
Opened 2020-06-25 16:52 UTC by tokusumi

This PR translates the features.md to Japanese.
Please review features.md.

Issue #1571 generates a new directory to support Japanese. 
I will fix dependency after #1571 is merged.

2020-08-15 08:31 UTC, SwftAlpc requested changes
Thank you for the excellent translation.
There are a few things that I noticed and I would like to suggest some corrections.

2020-08-15 08:31 UTC, SwftAlpc commented on docs/ja/docs/features.md
> +すべてに適切な**デフォルト**があり、どこにでもオプションの構成があります。必要なことを実行し、必要なAPIを定義するためにすべてのパラメーターを調整できます。
すべてに適切な**デフォルト**があり、オプションの構成ができます。

2020-08-15 08:31 UTC, SwftAlpc commented on docs/ja/docs/features.md
> +* 階層または **依存関係の"グラフ"** を作成することで、依存関係でさえも依存関係を持つことができます。
依存関係でさえも依存関係を持つことができ、階層または **依存関係の"グラフ”** を作成することができます。

2020-08-15 08:31 UTC, SwftAlpc commented on docs/ja/docs/features.md
> +    * 学習するべき新しいスキーマ定義のマイクロ言語はありません。
新しいスキーマ定義のマイクロ言語を学習する必要はありません。

2020-08-15 10:37 UTC, tokusumi commented
@SwftAlpc Thank you for your good suggestions. I improved translation. Please re-review and approve this PR if you want.

2020-08-15 11:12 UTC, SwftAlpc approved these changes
Thanks for the quick response.
LGTM!

2020-08-21 16:11 UTC, ryuckel approved these changes

2020-09-26 11:48 UTC, tokusumi commented
Hi, @tiangolo  
This PR has been approved by two reviewers (github actions to label approved PR didn't work, though). 
Would you like to require something more for this to be merged?

2020-10-16 20:08 UTC, merged

2020-10-16 20:11 UTC, tiangolo commented
Awesome! Thank you @tokusumi ! :bow: :cake: 

And thank you @ryuckel and @SwftAlpc for the reviews :clap: :coffee: 

Indeed, the GitHub action to manage the labels wasn't working correctly, so I just created a new one that is finally working :smile: :robot: