translated index.md to german
fastapi/fastapi pull request #1641
Opened 2020-06-28 08:10 UTC by SebastianLuebke

2020-07-01 19:47 UTC, Kludex commented
@SebastianLuebke You might want to check [this issue](https://github.com/tiangolo/fastapi/issues/1497) or create a new one talking about the possibility of supporting German. If there's already an issue with it, ignore me :)

2020-07-06 14:36 UTC, JeromeK13 reviewed
Some little typos I've found.

2020-07-06 14:36 UTC, JeromeK13 commented on docs/de/docs/index.md
> +**Typer** ist soetwas wie FastAPI's kleiner Bruder und soll das **FastAPI der CLIs** sein. ⌨️ 🚀
"soetwas" -> so etwas

2020-07-06 14:36 UTC, JeromeK13 commented on docs/de/docs/index.md
> +Verändern Sie nun die Datei `main.py` um den Body von einer `PUT` Anfrage zu empfangen.
"Verändern Sie nun die Datei `main.py` um den Body von einer `PUT` Anfrage zu empfangen." ->

Verändern Sie nun die Datei `main.py` um den Body einer `PUT` Anfrage zu empfangen

2021-01-29 19:02 UTC, kuchosauronad0 requested changes
I've found a few typos. The rest looks good I guess :) Thanks for putting the work into the translation

2021-01-29 19:02 UTC, kuchosauronad0 commented on docs/de/docs/index.md
> +Dieses Projekt ist unter den Bedingungen der MIT Lizenz lizensiert.
lizensiert -> lizenziert

2021-02-04 08:15 UTC, SebastianLuebke commented
So many typos :D will fix them today

2021-02-06 12:18 UTC, SebastianLuebke commented
Fixed the typos now

2022-08-30 14:16 UTC, closed without merging