Add Japanese translation for tutorial/index.md
fastapi/fastapi pull request #1656
Opened 2020-06-30 14:06 UTC by tokusumi

This PR translates the tutorial/index.md to Japanese.
Please review tutorial/index.md.

Issue #1571 generates a new directory to support Japanese.
I will fix dependency after #1571 is merged.

2020-08-15 12:42 UTC, SwftAlpc requested changes
It was an almost perfect translation. Thank you.
I have added and corrected some of the missing parts.
Please check.

2020-08-15 12:42 UTC, SwftAlpc commented on docs/ja/docs/tutorial/index.md
> +各セクションは前のセクションを踏まえた内容になっています。しかし、トピックごとに分割されているので、特定のAPIの要求を満たすようなセクションに直接たどり着けるようになっています。
各セクションは前のセクションを踏まえた内容になっています。しかし、トピックごとに分割されているので、特定のAPIの要求を満たすようなトピックに直接たどり着けるようになっています。

2020-08-15 12:42 UTC, SwftAlpc commented on docs/ja/docs/tutorial/index.md
> +また、エディターで使用することで、FastAPIの利点が実際に示されます。作成する必要があるコードの量、すべての型チェック、自動補完などを確認できます。
また、エディターで使用することで、書く必要のあるコードがどれだけ少ないか、すべての型チェック、自動補完などを確認して、FastAPIの利点を実感することができます。

2020-08-15 12:42 UTC, SwftAlpc commented on docs/ja/docs/tutorial/index.md
> +!!! note "注意"
備考

2020-08-15 12:42 UTC, SwftAlpc commented on docs/ja/docs/tutorial/index.md
> +    This is what you would probably do once you want to deploy your application to production:
以下は、アプリケーションを本番環境にデプロイしたいと思ったときに、おそらく行うであろうことです:

2020-08-15 12:42 UTC, SwftAlpc commented on docs/ja/docs/tutorial/index.md
> +    Also install `uvicorn` to work as the server:
また、サーバーとして動作するように`uvicorn`をインストールします。

2020-08-15 12:42 UTC, SwftAlpc commented on docs/ja/docs/tutorial/index.md
> +    And the same for each of the optional dependencies that you want to use.
そして、使用したいそれぞれのオプションの依存関係についても同様にインストールすることができます。

2020-08-15 12:42 UTC, SwftAlpc commented on docs/ja/docs/tutorial/index.md
> +完全なアプリケーションを**チュートリアル-ユーザーガイド**だけで構築し、**高度なユーザーガイド**のアイデアを使用して、ニーズに応じたさまざまな拡張を行えるように設計されています 。
**チュートリアル - ユーザーガイド**だけで完全なアプリケーションを構築できるように設計されており、**高度なユーザーガイド**のアイデアのいくつかを使用して、ニーズに応じて様々な方法で拡張することができます。

2020-08-15 14:54 UTC, tokusumi commented on docs/ja/docs/tutorial/index.md
> +!!! note "注意"
御存知かもしれませんが、マークダウンの「!!! note」の記法は少なくとも3種類あって、
以下の記号と英単語のペアになって表示されます。(記号は近いものを使っています) 日本語の記事だと全て備考かなと思っています。
区別するために、自分が翻訳しているものでは右の日本語を充てているんですが、どれもしっくりきていないのでまとめて意見を頂けるとありがたいです。（きれいに区別できていないので意訳できていないです。辞書を引いて最初にでてきた単語を使っています）

* ✏️ note: 注意
* ℹ️ info: 情報
* 🔥 tip: 豆知識

2020-08-15 16:09 UTC, SwftAlpc commented on docs/ja/docs/tutorial/index.md
> +!!! note "注意"
丁寧にありがとうございます。
noteについては「備考」だと思います。
「注意」だとwarningと捉えられそうです。
その他3つの日本語については異論ありません。

2020-08-15 16:17 UTC, tokusumi commented on docs/ja/docs/tutorial/index.md
> +!!! note "注意"
ありがとうございます。では、この4つはそのように統一しましょうか。
ただ、原文で「!!! note "hogehoge"」の様に指定されている場合はそちらの翻訳を優先させた方がいいと思います。

2020-08-15 16:40 UTC, SwftAlpc commented on docs/ja/docs/tutorial/index.md
> +!!! note "注意"
> ただ、原文で「!!! note "hogehoge"」の様に指定されている場合はそちらの翻訳を優先させた方がいいと思います。

これについては私も同意見です。

2020-08-15 16:42 UTC, SwftAlpc approved these changes
LGTM!
Thanks for the quick response!

2020-08-21 16:28 UTC, ryuckel approved these changes
LGTM!

2020-09-26 11:59 UTC, tokusumi commented
Hi, @tiangolo
This PR has been approved by two reviewers (github actions to label approved PR didn't work, though).
Would you like to require something more for this to be merged?

2020-10-17 06:02 UTC, merged

2020-10-17 06:03 UTC, tiangolo commented
Awesome! Thank you @tokusumi :bow: :coffee: 

And thanks @ryuckel and @SwftAlpc for the reviews! :clap: :nerd_face: