Add Japanese translation for tutorial/first-steps.md
fastapi/fastapi pull request #1658
Opened 2020-06-30 17:38 UTC by tokusumi

This PR translates the tutorial/first-steps.md to Japanese.
Please review tutorial/first-steps.md.

Issue #1571 generates a new directory to support Japanese.
I will fix dependency after #1571 is merged.

2020-07-03 16:27 UTC, ryuckel commented
I checked Japanese translation. I have no proposal of change about this document. Thank you so much!

2020-08-15 14:24 UTC, SwftAlpc requested changes
It's almost perfect!
I was wondering about some of the details, so if you would like to correct them, please do so.

2020-08-15 14:24 UTC, SwftAlpc commented on docs/ja/docs/tutorial/first-steps.md
> +APIを構築する際、「パス」は「懸念」と「リソース」を分離するための主要な方法です。
APIを構築する際、「パス」は「関心事」と「リソース」を分離するための主要な方法です。

2020-08-15 14:24 UTC, SwftAlpc commented on docs/ja/docs/tutorial/first-steps.md
> +!!! info "`@decorator` Info"
!!! info "`@decorator` 情報"

2020-08-15 14:24 UTC, SwftAlpc commented on docs/ja/docs/tutorial/first-steps.md
> +    私たちの場合、このデコレーターは**FastAPI**に、直下の関数が**オペレーション** `get`を使用した**パス**` / `に対応することを通知します。
私たちの場合、このデコレーターは直下の関数が**オペレーション** `get`を使用した**パス**` / `に対応することを**FastAPI**に通知します。

2020-08-15 14:24 UTC, SwftAlpc commented on docs/ja/docs/tutorial/first-steps.md
> +### Step 4: **パスオペレーション**を定義
### Step 4: **パスオペレーション関数**を定義

2020-08-15 14:24 UTC, SwftAlpc commented on docs/ja/docs/tutorial/first-steps.md
> +* **関数**: 「デコレータ」の直下にある関数is the function (`@app.get("/")`の直下).
* **関数**:  は「デコレータ」の直下にある関数 (`@app.get("/")`の直下).

2020-08-15 14:24 UTC, SwftAlpc commented on docs/ja/docs/tutorial/first-steps.md
> +これは、Python関数です。
これは、Pythonの関数です。

2020-08-15 14:24 UTC, SwftAlpc commented on docs/ja/docs/tutorial/first-steps.md
> +It will be called by **FastAPI** whenever it receives a request to the URL "`/`" using a `GET` operation.
消し忘れです。

2020-08-15 14:24 UTC, SwftAlpc commented on docs/ja/docs/tutorial/first-steps.md
> +!!! note "注意"
!!! note "備考"

2020-08-15 14:27 UTC, SwftAlpc requested changes
I thought it would be better to abstract.

2020-08-15 14:27 UTC, SwftAlpc commented on docs/ja/docs/tutorial/first-steps.md
> +!!! note "技術詳細"
備考で抽象化した方が良さそうですが、いかがでしょう？

2020-08-15 15:38 UTC, tokusumi commented on docs/ja/docs/tutorial/first-steps.md
> +!!! note "技術詳細"
ここだけ珍しく原文がnoteだけでなく、
!!! note "Technical details"
なので、残したほうがいいかなと思っています。

2020-08-15 16:12 UTC, SwftAlpc commented on docs/ja/docs/tutorial/first-steps.md
> +!!! note "技術詳細"
本当ですね...!!
すみません、こちらはこのままでいきましょう。

2020-08-15 16:43 UTC, SwftAlpc approved these changes
I think it's so much better!

2020-08-21 16:15 UTC, ryuckel approved these changes

2020-09-26 12:00 UTC, tokusumi commented
Hi, @tiangolo
This PR has been approved by two reviewers (github actions to label approved PR didn't work, though).
Would you like to require something more for this to be merged?

2020-10-17 06:09 UTC, merged

2020-10-17 06:09 UTC, tiangolo commented
Excellent! Thank you for doing it @tokusumi ! :bow: :cake: 

And thanks @ryuckel and @SwftAlpc for the reviews :clap: :clap: :nerd_face: