Add Japanese translation for tutorial/path-params.md
fastapi/fastapi pull request #1671
Opened 2020-07-05 06:48 UTC by tokusumi

This PR translates the tutorial/path-params.md to Japanese.
Please review tutorial/path-params.md

Issue #1571 generates a new directory to support Japanese.
I will fix dependency after #1571 is merged.

2020-08-15 15:08 UTC, SwftAlpc requested changes
Thanks for the translation!
We need to make some corrections.
Please check.

2020-08-15 15:08 UTC, SwftAlpc commented on docs/ja/docs/tutorial/path-params.md
> +*path operation* から*列挙型メンバ*を返すことができます。JSONボディ（`dict` など）でネストすることもできます。
JSON ボディ (例: dict) に入れ子になっている場合でも、*path operation*から*列挙型メンバ*を返すことができます。

2020-08-15 15:08 UTC, SwftAlpc commented on docs/ja/docs/tutorial/path-params.md
> +OpenAPIは*パス*を内部に含んだ*パスパラメータ*の宣言をサポートしていません。したがって、テストと定義が困難です。
OpenAPIは、テストや定義が困難なシナリオにつながる可能性があるため、内部に*パス*を含む*パスパラメータ*の宣言をサポートしていません。

2020-08-15 18:12 UTC, SwftAlpc approved these changes
LGTM 👍

2020-08-21 16:16 UTC, ryuckel approved these changes
LGTM!

2020-09-26 12:00 UTC, tokusumi commented
Hi, @tiangolo
This PR has been approved by two reviewers (github actions to label approved PR didn't work, though).
Would you like to require something more for this to be merged?

2020-10-17 06:14 UTC, tiangolo commented
This is amazing! Thanks for all the work you have been doing with this @tokusumi ! :clap: :clap: :bow: :coffee: 

And thanks @ryuckel and @SwftAlpc for the reviews! :cake: :nerd_face:

2020-10-17 06:15 UTC, merged