Add Japanese translation for tutorial/query-params.md
fastapi/fastapi pull request #1674
Opened 2020-07-05 13:15 UTC by tokusumi

This PR translates the tutorial/query-params.md to Japanese.
Please review tutorial/query-params.md

Issue #1571 generates a new directory to support Japanese.
I will fix dependency after #1571 is merged.

2020-08-15 15:31 UTC, SwftAlpc requested changes
Thank you for the hard translation!
There were a few things that I would like to see corrected, so please correct them.

2020-08-15 15:31 UTC, SwftAlpc commented on docs/ja/docs/tutorial/query-params.md
> +クエリはURL内で `?` の後ろに書かれており、 `&` で分けられているキーとバリューの組の集合です。
クエリはURL内で `?` の後に続くキーとバリューのセットで、 `&` で区切られています。

2020-08-15 15:31 UTC, SwftAlpc commented on docs/ja/docs/tutorial/query-params.md
> +以下の例では、`skip=0` と `limit=10` というデフォルト値を持っています。
上述の例では

2020-08-15 15:31 UTC, SwftAlpc commented on docs/ja/docs/tutorial/query-params.md
> +
抜けています。

!!! note "備考"
    FastAPIは`= None`であるため、`q`がオプショナルであることを知っています。
    `Optional[str]`の`Optional`はFastAPIによっては使用されていません（FastAPIは`str`の部分のみ使用します）が、`Optional[str]`はエディタがコードのエラーを見つけるのを助けてくれます。

2020-08-15 15:31 UTC, SwftAlpc commented on docs/ja/docs/tutorial/query-params.md
> +!!! 警告
これより下はen版からは削除されているようです。

2020-08-15 16:39 UTC, SwftAlpc approved these changes
LGTM!

2020-08-15 16:39 UTC, tokusumi commented
@SwftAlpc Thank you for your good suggestions. I improved translation. Please re-review and approve this PR if you want.

2020-08-21 16:24 UTC, ryuckel approved these changes
LGTM!

2020-09-26 12:01 UTC, tokusumi commented
Hi, @tiangolo
This PR has been approved by two reviewers (github actions to label approved PR didn't work, though).
Would you like to require something more for this to be merged?

2020-10-17 06:23 UTC, tiangolo commented
Thanks a lot! Awesome @tokusumi ! :rocket: :cake: 

And thanks @ryuckel and @SwftAlpc for the reviews :bow: :clap: :clap:

2020-10-17 06:23 UTC, merged