Add Japanese translation for tutorial/body.md
fastapi/fastapi pull request #1683
Opened 2020-07-07 14:25 UTC by tokusumi

This PR translates the tutorial/body.md to Japanese.
Please review tutorial/body.md

Issue #1571 generates a new directory to support Japanese.
I will fix dependency after #1571 is merged.

2020-08-15 15:54 UTC, SwftAlpc requested changes
Thanks for the translation!
There have been some changes in the original text, please correct them.

2020-08-15 15:54 UTC, SwftAlpc commented on docs/ja/docs/tutorial/body.md
> +エディターによる型ヒントと補完が関数内で利用できます (Pydanticモデルではなく `dict` を受け取ると、同じサポートは受けられないかもしれません):
同じサポートは受けられません

2020-08-15 15:54 UTC, SwftAlpc commented on docs/ja/docs/tutorial/body.md
> +
Noteが追加されています

!!! note "備考"
FastAPIはデフォルト値が`=None`なので、`q`の値が必要ないことがわかります。
`Optional[str]`の`Optional`はFastAPIでは使用されませんが、エディタがより良いサポートを提供し、エラーを検出できるようになります。

2020-08-15 15:54 UTC, SwftAlpc commented on docs/ja/docs/tutorial/body.md
> +もしPydanticモデルを使用したくない場合は、**ボディ**パラメータが利用できます。[Body - Multiple Parameters: Singular values in body](body-multiple-params.md#singular-values-in-body){.internal-link target=_blank}を確認してください。
この項目は削除されたようです。

2020-08-15 15:54 UTC, SwftAlpc commented on docs/ja/docs/tutorial/body.md
> +    データを送るには、`POST` (もっともよく使われる)、`PUT`、`DELETE` または `PATCH` を使わなければいけません。
en版ではinfoの部分がガラッと変わっているようです。

データを送るには、`POST` (もっともよく使われる)、`PUT`、`DELETE` または `PATCH` を使わなければいけません。
`GET` リクエストでボディを送信することは、仕様では未定義の動作ですが、FastAPI でサポートされており、非常に複雑な（極端な）ユースケースにのみ対応しています。
奨励されていないので、Swagger UIを使った対話型のドキュメントでは`GET`を使ったときにボディのドキュメントが表示されず、途中のプロキシが対応していない可能性があります。

2020-08-16 03:38 UTC, SwftAlpc approved these changes
LGTM :)

2020-08-21 16:26 UTC, ryuckel approved these changes
LGTM！

2020-09-26 12:01 UTC, tokusumi commented
Hi, @tiangolo
This PR has been approved by two reviewers (github actions to label approved PR didn't work, though).
Would you like to require something more for this to be merged?

2020-10-17 06:31 UTC, tiangolo commented
Thanks a lot for doing this! @tokusumi :bow: :clap: :clap: 

And thanks @ryuckel and @SwftAlpc for the reviews :nerd_face: :coffee:

2020-10-17 06:31 UTC, merged