Add Japanese translation for help-fastapi.md
fastapi/fastapi pull request #1692
Opened 2020-07-08 16:31 UTC by tokusumi

This PR translates the help-fastapi.md to Japanese.
Please review help-fastapi.md

Issue #1571 generates a new directory to support Japanese.
I will fix dependency after #1571 is merged.

2020-08-15 08:51 UTC, SwftAlpc requested changes
I think it's a very good translation, but you forgot to erase a few sentences, so if you could fix that it would be perfect!

2020-08-15 08:51 UTC, SwftAlpc commented on docs/ja/docs/help-fastapi.md
> +## Tweet about **FastAPI**
消し忘れでしょうか？

2020-08-15 08:51 UTC, SwftAlpc commented on docs/ja/docs/help-fastapi.md
> +## Vote for FastAPI
こちらも消し忘れ

2020-08-15 08:51 UTC, SwftAlpc commented on docs/ja/docs/help-fastapi.md
> +* ドキュメントのタイポを訂正。
ドキュメントのタイプミスを修正

2020-08-15 11:24 UTC, SwftAlpc approved these changes
Thank you!

LGTM

2020-09-25 03:36 UTC, komtaki reviewed
Thanks for your translate. 👍 
I commented to make it read easier as Japanese.

2020-09-25 03:36 UTC, komtaki commented on docs/ja/docs/help-fastapi.md
> +<a href="https://github.com/tiangolo/fastapi/issues" class="external-link" target="_blank">既存のissues</a>を確認して、他の人を助けて見てください。皆さんが回答を知っているかもしれないような質問がほとんどです。🤓
```suggestion
<a href="https://github.com/tiangolo/fastapi/issues" class="external-link" target="_blank">既存のissues</a>を確認して、他の人を助けてみてください。皆さんが回答を知っているかもしれない質問がほとんどです。🤓
```

微妙ですが、「見」は変換しない方が意味があってる気がします。 🤔 
「ような」はない方が読みやすいかもしれません。

2020-09-25 03:36 UTC, komtaki commented on docs/ja/docs/help-fastapi.md
> +GitHub issuesではテンプレートが良い回答を得やすいような質問ができるように、もしくは、質問する前に自身で解決できるようにガイドしてくれます。そして、GitHubではたとえ時間がかかっても全てに答えているか確認できます。個人的にはGitterチャットでは同じことはできないです。😅
```suggestion
GitHub issuesでは良い回答を得やすい質問ができるように、もしくは、質問する前に自身で解決できるようにテンプレートがガイドしてくれます。そして、GitHubではたとえ時間がかかっても全てに答えているか確認できます。個人的にはGitterチャットでは同じことはできないです。😅
```

語順の入れかえ

2020-09-25 03:36 UTC, komtaki commented on docs/ja/docs/help-fastapi.md
> +以下のスポンサーなることもできます:
### 
```suggestion
以下のスポンサーになることもできます:
```

タイポです。

2020-09-25 14:24 UTC, tokusumi commented
@komtaki 
Thank you!

2020-09-26 02:49 UTC, komtaki commented
LGTM 🙆‍♂️

2020-09-26 03:20 UTC, tokusumi commented
@komtaki  could you approve this?

2020-09-26 05:30 UTC, komtaki approved these changes

2020-09-26 12:02 UTC, tokusumi commented
Hi, @tiangolo
This PR has been approved by two reviewers (github actions to label approved PR didn't work, though).
Would you like to require something more for this to be merged?

2020-10-17 06:37 UTC, tiangolo commented
Awesome! Thanks @tokusumi ! :coffee: :rocket: 

And thanks @SwftAlpc and @komtaki for the reviews :bow: :nerd_face:

2020-10-17 06:38 UTC, merged