Introduce free form queries
fastapi/fastapi pull request #1885
Opened 2020-08-12 18:48 UTC by yeralin

This PR addresses #1543 

* Introduced `fastapi.dependencies.utils.mapping_shapes: dict`
* Currently `mapping_shapes` includes only `pydantic.fields.SHAPE_MAPPING`
* Introduced `fastapi.dependencies.utils.mapping_types: tuple` with `(dict)` type
* Introduced `fastapi.dependencies.utils.is_scalar_mapping_field` method that checks whether a field is a mapping field
* Modified `fastapi.dependencies.utils.get_dependant` method's logic to accept mapping parameter as a field
* Modified `fastapi.dependencies.utils.request_params_to_args` method's logic to parse incoming request query params as a mapping

2022-01-30 19:16 UTC, cikay requested changes

2022-01-30 19:16 UTC, cikay commented on fastapi/dependencies/utils.py
> +        if field.sub_fields is not None:
Reverse the condition and return early. [Do not move the requirements literally to the code.](https://szymonkrajewski.pl/why-should-you-return-early/)

2025-10-30 10:44 UTC, YuriiMotov commented
@yeralin, thank you for your interest and efforts!

This PR is outdated and looks abandoned..
Let's focus on https://github.com/fastapi/fastapi/pull/9837

2025-12-02 05:15 UTC, tiangolo commented
Thanks all! I'll close this one for now to continue in the other one. :coffee:

2025-12-02 05:15 UTC, closed without merging