Add tutorial/query-params-str-validations.md
fastapi/fastapi pull request #1901
Opened 2020-08-16 08:51 UTC by SwftAlpc

This PR translates the tutorial/query-params-str-validations.md to Japanese.
Please review tutorial/query-params-str-validations.md

Issue #1571 generates a new directory to support Japanese.
PR #1656 generates a new directory for tutorial.
I will fix dependency after #1571 & #1656  are merged.

2020-08-20 14:59 UTC, tokusumi commented on docs/ja/docs/tutorial/query-params-str-validations.md
> +この例では、`str`の値をバリデーションを宣言する方法を見てきました。
この例では、`str`の値のバリデーションを宣言する方法を見てきました。

2020-08-20 15:59 UTC, SwftAlpc commented
@tokusumi 
Thank you for your review!
I fixed it.

2020-08-21 17:25 UTC, tokusumi requested changes
most "hl_lines" is two less than original text.

2020-08-22 18:30 UTC, tokusumi approved these changes

2020-10-04 13:39 UTC, Attsun1031 reviewed
Thank you for your great work !
Please check suggestions I made.

2020-10-04 13:39 UTC, Attsun1031 commented on docs/ja/docs/tutorial/query-params-str-validations.md
> +クエリパラメータ`q`は`str`型でデフォルトは`None`のため、オプショナルです。
```suggestion
クエリパラメータ `q` は `Optional[str]` 型で、`None` を許容する `str` 型を意味しており、デフォルトは `None` です。そのため、FastAPIはそれが必須ではないと理解します。
```
```

2020-10-04 13:39 UTC, Attsun1031 commented on docs/ja/docs/tutorial/query-params-str-validations.md
> +
```suggestion

!!! note "備考"
    FastAPIは、 `q` はデフォルト値が `=None` であるため、必須ではないと理解します。

    `Optional[str]` における `Optional` はFastAPIには利用されませんが、エディターによるより良いサポートとエラー検出を可能にします。
```

(Missing "note" section translation)

2020-10-04 13:39 UTC, Attsun1031 commented on docs/ja/docs/tutorial/query-params-str-validations.md
> +q: str = Query(None)
```suggestion
q: Optional[str] = Query(None)
```

Original document has `Optional`

2020-10-04 13:39 UTC, Attsun1031 commented on docs/ja/docs/tutorial/query-params-str-validations.md
> +q: str = None
```suggestion
q: Optional[str] = None
```

2020-10-04 13:39 UTC, Attsun1031 commented on docs/ja/docs/tutorial/query-params-str-validations.md
> +
```suggestion

!!! info "情報"
    FastAPIは以下の部分を気にすることを覚えておいてください:

    ```Python
    = None
    ```

    もしくは:

    ```Python
    = Query(None)
    ```

    そして、 `None` を利用することでクエリパラメータが必須ではないと検知します。

    `Optional` の部分は、エディターによるより良いサポートを可能にします。

```

(Missing info section)

2020-10-04 13:39 UTC, Attsun1031 commented on docs/ja/docs/tutorial/query-params-str-validations.md
> +これにより、データを検証し、データが有効でない場合は明確なエラーを表示し、OpenAPIスキーマの*path operation*でパラメータを文書化します。
```suggestion
これにより、データを検証し、データが有効でない場合は明確なエラーを表示し、OpenAPIスキーマの　*path operation* にパラメータを記載します。
```

more readable ?

2020-10-04 13:39 UTC, Attsun1031 commented on docs/ja/docs/tutorial/query-params-str-validations.md
> +しかし、あなたがそれらを必要とし、学ぶときにはすでに、 **FastAPI**で直接それらを使用することができることを知っています。
```suggestion
しかし、あなたがそれらを必要とし、学ぶときにはすでに、 **FastAPI**で直接それらを使用することができます。
```

2020-10-04 13:39 UTC, Attsun1031 commented on docs/ja/docs/tutorial/query-params-str-validations.md
> +    デフォルト値を指定すると、パラメータはオプションになります。
```suggestion
    デフォルト値を指定すると、パラメータは任意になります。
```

2020-10-04 13:39 UTC, Attsun1031 commented on docs/ja/docs/tutorial/query-params-str-validations.md
> +q: str = None
```suggestion
q: Optional[str] = None
```

2020-10-04 13:39 UTC, Attsun1031 commented on docs/ja/docs/tutorial/query-params-str-validations.md
> +q: str = Query(None, min_length=3)
```suggestion
q: Optional[str] = Query(None, min_length=3)
```

2020-10-04 13:39 UTC, Attsun1031 commented on docs/ja/docs/tutorial/query-params-str-validations.md
> +これは **FastAPI** にこのパラメータが必要であることを知らせます。
```suggestion
これは **FastAPI** にこのパラメータが必須であることを知らせます。
```

2020-10-04 13:39 UTC, Attsun1031 commented on docs/ja/docs/tutorial/query-params-str-validations.md
> +## クエリパラメータのリスト/複数の値
```suggestion
## クエリパラメータのリスト / 複数の値
```

2020-10-04 13:39 UTC, Attsun1031 commented on docs/ja/docs/tutorial/query-params-str-validations.md
> +### デフォルト値を持つ、クエリパラメータのリスト/複数の値
```suggestion
### デフォルト値を持つ、クエリパラメータのリスト / 複数の値
```

2020-10-04 13:39 UTC, Attsun1031 commented on docs/ja/docs/tutorial/query-params-str-validations.md
> +## さらにメタデータを宣言する
```suggestion
## より多くのメタデータを宣言する
```
more fluent ?

2020-10-04 13:39 UTC, Attsun1031 commented on docs/ja/docs/tutorial/query-params-str-validations.md
> +その時、`alias`を宣言することができます。エイリアスはパラメータの値を見つけるのに使用されます:
```suggestion
それならば、`alias`を宣言することができます。エイリアスはパラメータの値を見つけるのに使用されます:
```

2020-10-29 10:42 UTC, SwftAlpc commented
@Attsun1031 
Thanks for the review!
Could you re-review it that has been corrected?

2020-10-29 12:03 UTC, Attsun1031 approved these changes
LGTM 👍

2020-11-01 21:51 UTC, tiangolo commented
Awesome, thanks @SwftAlpc ! :clap: 

And thanks @Attsun1031  and @tokusumi for the reviews :bow:

2020-11-01 21:54 UTC, merged