Add tutorial/body-multiple-params.md
fastapi/fastapi pull request #1903
Opened 2020-08-16 10:46 UTC by SwftAlpc

This PR translates the tutorial/body-multiple-params.md to Japanese.
Please review tutorial/body-multiple-params.md

Issue #1571 generates a new directory to support Japanese.
PR #1656 generates a new directory for tutorial.
I will fix dependency after #1571 & #1656 are merged.

2020-08-20 15:27 UTC, tokusumi commented on docs/ja/docs/tutorial/body-multiple-params.md
> +```Python hl_lines="15"
```Python hl_lines="17"

2020-08-20 16:07 UTC, SwftAlpc commented
@tokusumi 
Thanks for your reveiw!
I didn't know the reference had changed at any time.

2020-08-21 17:16 UTC, tokusumi requested changes
I had overlooked similar corrections

2020-08-23 07:21 UTC, tokusumi approved these changes

2023-06-26 16:48 UTC, tiangolo commented
📝 Docs preview for commit 950acbc57842a7082c5f3016387349bdd0c2a5da at: https://6499c133706d0c007b5a1665--fastapi.netlify.app

2024-01-15 15:48 UTC, alejsdev commented
Thanks for your help @SwftAlpc and @tokusumi for the review 🤓💯

2024-01-15 15:48 UTC, merged