🌐 Translate index.md to Turkish
fastapi/fastapi pull request #1908
Opened 2020-08-17 11:36 UTC by ycd

I created the setup for Turkish docs in #1905 

Then i translated index.md to Turkish.

But also as far as i know, pushes and pulls operate at a commit level they won't split them apart so this pull request includes the same commits from #1905.  But when #1905 is merged this pull request will only include my latest commit jfyk. 

Main issue: #1892

2020-08-22 15:35 UTC, umitkaanusta requested changes

2020-08-22 20:15 UTC, umitkaanusta approved these changes

2021-09-01 12:22 UTC, BilalAlpaslan approved these changes

2021-10-05 12:45 UTC, tiangolo commented
Awesome, thanks @ycd! :cake: 

And thanks for the reviews @BilalAlpaslan and @umitkaanusta :bow:

2021-10-05 12:46 UTC, merged