Add tutorial/schema-extra-example.md. Japanese ver.
fastapi/fastapi pull request #1931
Opened 2020-08-20 15:09 UTC by SwftAlpc

This PR translates the tutorial/schema-extra-example.md to Japanese.
Please review tutorial/schema-extra-example.md.

Issue #1571 generates a new directory to support Japanese.
PR #1656 generates a new directory for tutorial.
I will fix dependency after #1571 & #1656 are merged.

2020-08-21 18:36 UTC, tokusumi requested changes

2020-08-22 19:44 UTC, tokusumi approved these changes

2023-06-26 16:52 UTC, tiangolo commented
📝 Docs preview for commit b7379a6dfd44d2382720cd5fd13dd67ff65922d9 at: https://6499c2228f963500a17ce1a3--fastapi.netlify.app

2024-01-15 15:35 UTC, tiangolo commented
As this was done by @SwftAlpc and reviewed by @tokusumi, champions of the Japanese translations, I'm gonna merge this. 🚀

2024-01-15 15:35 UTC, merged