Add tutorial/extra-data-types.md. Japanese ver.
fastapi/fastapi pull request #1932
Opened 2020-08-20 15:36 UTC by SwftAlpc

This PR translates the tutorial/extra-data-types.md to Japanese.
Please review tutorial/extra-data-types.md. 

Issue #1571 generates a new directory to support Japanese.
PR #1656 generates a new directory for tutorial.
I will fix dependency after #1571 & #1656 are merged.

2020-08-21 18:49 UTC, tokusumi requested changes

2020-08-26 15:25 UTC, tokusumi approved these changes
LGTM

2020-08-26 17:29 UTC, rkbeatss commented on docs/ja/docs/tutorial/extra-data-types.md
> +```Python hl_lines="1 2 11 12 13 14 15"
`hl_lines` supports ranges (i.e, 12-16) and would be more readable / maintainable.  issue for reference: #1859

2020-12-31 14:14 UTC, delhi09 reviewed
It looks mostly good.
I pointed out some details.

2020-12-31 14:14 UTC, delhi09 commented on docs/ja/docs/tutorial/extra-data-types.md
> +    * Pythonの`datetime.time`.
"です。" is better at the view of the consistency.

2020-12-31 14:14 UTC, delhi09 commented on docs/ja/docs/tutorial/extra-data-types.md
> +    * リクエストやレスポンスでは`float`と同じように扱います。
"扱われます。" is better at the view of the consistency.

2023-06-26 17:31 UTC, tiangolo commented
📝 Docs preview for commit 549e72092b7feeff14853e3463b536269c24b8bb at: https://6499cb481d7654047104dee1--fastapi.netlify.app

2024-01-15 16:00 UTC, alejsdev commented
Thanks for your help @SwftAlpc and @tokusumi 🤓

2024-01-15 16:02 UTC, alejsdev commented
Thanks for your help @SwftAlpc and your review @tokusumi 🤓🚀✨

2024-01-15 16:37 UTC, tiangolo commented
📝 Docs preview for commit 9231c7983b59c12edb280b23660d07834568d866 at: https://fb5c19c5.fastapitiangolo.pages.dev

2024-01-22 20:01 UTC, merged

2024-01-22 20:01 UTC, alejsdev commented
Thank you! @nearnear 😃 

And everyone else for the reviews 🚀✨

2024-01-22 20:06 UTC, alejsdev commented
Thank you! @SwftAlpc 😃 

And everyone else for the reviews 🚀✨