Add tutorial/cookie-params.md. Japanese ver.
fastapi/fastapi pull request #1933
Opened 2020-08-20 17:09 UTC by SwftAlpc

This PR translates the cookie-params.md to Japanese.
Please review cookie-params.md

Issue #1571 generates a new directory to support Japanese.
I will fix dependency after #1571 is merged.

2020-08-21 18:53 UTC, tokusumi requested changes

2020-08-22 18:31 UTC, tokusumi approved these changes

2020-12-31 13:55 UTC, delhi09 approved these changes
LGTM！

2021-01-09 18:16 UTC, tiangolo commented
Awesome! Thanks @SwftAlpc ! :bow: 

And thank you @tokusumi and @delhi09 for the reviews! :coffee:

2021-01-09 18:19 UTC, merged