Add tutorial/header-params.md. Japanese ver.
fastapi/fastapi pull request #1935
Opened 2020-08-20 17:44 UTC by SwftAlpc

This PR translates the tutorial/header-params.md to Japanese.
Please review tutorial/header-params.md.

Issue #1571 generates a new directory to support Japanese.
PR #1656 generates a new directory for tutorial.
I will fix dependency after #1571 & #1656 are merged.

2020-08-21 19:07 UTC, tokusumi requested changes

2020-08-22 18:33 UTC, tokusumi approved these changes

2020-10-03 07:47 UTC, Attsun1031 approved these changes
I've check it all and it's fine.
LGTM 👍

2020-10-17 13:55 UTC, tiangolo commented
Awesome! Thank you @SwftAlpc ! :rocket: :bow: :coffee: 

And thanks @Attsun1031 and @tokusumi for the reviews! :clap: :clap: :cake:

2020-10-17 13:55 UTC, merged