Add  tutorial/response-model.md. Japanese ver.
fastapi/fastapi pull request #1938
Opened 2020-08-20 18:43 UTC by SwftAlpc

This PR translates the tutorial/response-model.md to Japanese.
Please review tutorial/response-model.md.

Issue #1571 generates a new directory to support Japanese.
PR #1656 generates a new directory for tutorial.
I will fix dependency after #1571 & #1656 are merged.

2020-08-21 19:34 UTC, tokusumi requested changes

2020-08-22 19:48 UTC, tokusumi approved these changes

2020-09-30 11:36 UTC, Attsun1031 reviewed
Thank you for your review 👍 
Please check out some of the comments I made.

2020-09-30 11:36 UTC, Attsun1031 commented on docs/ja/docs/tutorial/response-model.md
> +しかし、ID`bar`の項目のように、モデルのフィールドにデフォルト値が設定されている場合、データに値が設定されています:
```suggestion
しかし、ID`bar`のitemのように、デフォルト値が設定されているモデルのフィールドに値が設定されている場合:
```

（id=fooではdescriptionとtaxが設定されていなかったのでレスポンスモデルにも設定されていないが、barではデフォルトではない固有の値が設定されているため、レスポンスにも含まれる、という動作を説明しているのだと思います。）

2020-09-30 11:36 UTC, Attsun1031 commented on docs/ja/docs/tutorial/response-model.md
> +ID`baz`の項目のようにデフォルト値と同じ値を持つデータの場合:
```suggestion
ID`baz`のitemのようにデフォルト値と同じ値を持つデータの場合:
```

2020-09-30 11:36 UTC, Attsun1031 commented on docs/ja/docs/tutorial/response-model.md
> +これらは`str`の`set`を受け取り、それに含まれる（残りの部分を省略する）または除外される（残りの部分を含む）属性の名前をつけます。
```suggestion
属性名を持つ`str`の`set`を受け取り、含める(残りを省略する)か、除外(残りを含む)します。
```

2020-09-30 11:36 UTC, Attsun1031 commented on docs/ja/docs/tutorial/response-model.md
> +
```suggestion

    同様に動作する`response_model_by_alias`にも当てはまります。

```

（１行抜けていました）

2020-09-30 11:36 UTC, Attsun1031 commented on docs/ja/docs/tutorial/response-model.md
> +*path operationデコレータの*`response_model`パラメータを使用して、レスポンスモデルを定義し、特にプライベートデータがフィルタリングされていることを確認します。
```suggestion
*path operationデコレータの*`response_model`パラメータを使用して、レスポンスモデルを定義し、特にプライベートデータがフィルタリングされていることを保証します。
```

2020-12-22 17:53 UTC, delhi09 reviewed
It looks mostly good.
I pointed out some details.

2020-12-22 17:53 UTC, delhi09 commented on docs/ja/docs/tutorial/response-model.md
> +    レスポンスモデルは、関数の戻り値のアノテーションではなく、このパラメータで宣言されています。なぜなら、パス関数は実際にはそのレスポンスモデルを返すのではなく、`dict`やデータベースオブジェクト、あるいは他のモデルを返し、`response_model`を使用してフィールドの制限やシリアライズを行うからです。
It may be a little better to modify "このパラメータ" to "関数のパラメータ" because it's a little hard for readers to undeastand what “この” refers to.

2020-12-22 17:53 UTC, delhi09 commented on docs/ja/docs/tutorial/response-model.md
> +FastAPIは十分に賢いので（実際には、Pydanticが十分に賢い）`description`や`tax`、`tags`はデフォルト値と同じ値を持っているにもかかわらず、明示的に設定されていることを理解しています。（デフォルトから取得するのではなく）
It's better to modify "デフォルトから取得するのではなく" to "デフォルトから取得されたのではなく" because " taken from" is the passive voice.

2020-12-22 17:53 UTC, delhi09 commented on docs/ja/docs/tutorial/response-model.md
> +*path operationデコレータ*として`response_model_include`と`response_model_exclude`も使用することができます。
It's a little better to add "のパラメータ" after "path operationデコレータ".

2020-12-22 17:53 UTC, delhi09 commented on docs/ja/docs/tutorial/response-model.md
> +属性名を持つ`str`の`set`を受け取り、含める(残りを省略する)か、除外(残りを含む)します。
I think the following sentence is better .
「これらのパラメータは、含める(残りを省略する)もしくは除外(残りを含む)する対象の属性名のstrのsetを受け取ります。」

[理由]
1. ベースの文は"They take a set of str"です。
2. "str"に"with the name of the attributes"がかかっています。
3. "attributes"に"to include (omitting the rest) or to exclude (including the rest)."がかかっています。("attributes"は"include","exclude"の目的語です。)

2023-06-26 17:28 UTC, tiangolo commented
📝 Docs preview for commit b6e0d804c67f123a815221a050efeada2c111cfa at: https://6499ca738f963504c47ce17f--fastapi.netlify.app

2024-01-15 16:01 UTC, alejsdev commented
Thanks @SwftAlpc 🤓 

Thanks for the reviews @tokusumi @Attsun1031 ✌️

2024-01-15 16:01 UTC, merged