🌐 Add Japanese translation for `docs/ja/docs/tutorial/extra-models.md`
fastapi/fastapi pull request #1941
Opened 2020-08-21 14:49 UTC by SwftAlpc

This PR translates the tutorial/extra-models.md to Japanese.
Please review tutorial/extra-models.md

~Issue #1571 generates a new directory to support Japanese.
PR #1656 generates a new directory for tutorial.
I will fix dependency after #1571 & #1656 are merged.~

2020-09-03 14:23 UTC, tokusumi requested changes

2020-09-03 14:23 UTC, tokusumi commented on docs/ja/docs/tutorial/extra-models.md
> +#### 別の内容からのPydanticモデル
#### 別のモデルからつくるPydanticモデル

2020-09-03 14:23 UTC, tokusumi commented on docs/ja/docs/tutorial/extra-models.md
> +レスポンスを２つの型の`Union`と宣言することができます。
レスポンスを２つの型の`Union`として宣言することができます。

2020-10-29 11:34 UTC, SwftAlpc commented on docs/ja/docs/tutorial/extra-models.md
> +    password = user_dict["password"],これやばい
変な日本語入ってましたね...;;
修正しました！

2020-10-29 11:34 UTC, SwftAlpc commented on docs/ja/docs/tutorial/extra-models.md
> +# 追加モデル
良い和訳だと思います！修正しました

2020-10-29 11:36 UTC, SwftAlpc commented
@tokusumi 
Thanks for the review!
I apologize for taking so long to respond.
Could you re-review?

2020-10-29 12:30 UTC, tokusumi approved these changes
your awesome works are really helpful. Thank you🎉

2023-06-26 16:56 UTC, tiangolo commented
📝 Docs preview for commit 4b6e845ef8e2993f1d1f1ef0a745170591e132b4 at: https://6499c2f1bac8cd0083555671--fastapi.netlify.app

2024-01-15 15:36 UTC, tiangolo commented
As this was done by @SwftAlpc and reviewed by @tokusumi, champions of the Japanese translations, I'm gonna merge this. 🚀

2024-01-15 15:36 UTC, merged