Add japanese translation for deployment.md
fastapi/fastapi pull request #1948
Opened 2020-08-22 03:25 UTC by tokusumi

This PR translates the deployment.md to Japanese.
Please review deployment.md

~Issue #1571 generates a new directory to support Japanese.
I will fix dependency after #1571 is merged.~

2020-08-23 07:12 UTC, SwftAlpc requested changes
Thank you for translating a very difficult chapter.
I was concerned about some minor wording, so if you can fix that, it's not a problem.

2020-08-27 14:47 UTC, tokusumi commented on docs/en/docs/deployment.md
> +But if you are doing all that, you might just use the Docker image that does it automatically.
ignore them. I reverted commit to delete these change

2020-08-27 14:51 UTC, tokusumi commented
@SwftAlpc 
I have improved translation wrt your suggestions.
Please re-review if you want.

2020-09-25 08:11 UTC, komtaki reviewed
Appreciate for your nice translate. 👍 
I commented to more improve your translate.

2020-09-25 08:11 UTC, komtaki commented on docs/ja/docs/deployment.md
> +このアイデアは、証明書の取得と更新を自動化して、安全なHTTPSを無料で永久に使用できるようにするためのものです。
```suggestion
このアイデアは、証明書の取得と更新を自動化して、安全なHTTPSを無料で永久に使用可能にするためのものです。
```

It will be shorter, so it might be easier to read.

2020-09-25 14:23 UTC, tokusumi commented
@komtaki 
Thank you for your review.

2020-09-26 02:51 UTC, komtaki commented
LGTM 🙆‍♂️

2020-09-26 05:33 UTC, komtaki approved these changes
LGTM 🙆‍♂️

2020-11-06 03:20 UTC, tokusumi commented
This section is separated into some sections in the latest docs.
I am going to separate This PR to update.

2020-11-06 03:20 UTC, closed without merging