🌐 Add Turkish translation for `docs/features.md`
fastapi/fastapi pull request #1950
Opened 2020-08-22 13:48 UTC by ycd

This PR translates features.md to Turkish, and adds a line to `docs/tr/mkdocs.yml` **features.md**

afaik pushes and pulls operate at a commit level they won't split them apart so this pull request includes the same commits from #1905 and #1908, but when they get merged this will only merge two commits.

I created the setup for Turkish docs in #1905

I translated index.md to Turkish in #1908

Main issue: #1892

2020-08-22 16:18 UTC, umitkaanusta requested changes
Submitted the changes about features.md here
Submitted the changes about index.md in #1908

2020-08-22 20:04 UTC, umitkaanusta approved these changes

2021-09-01 09:20 UTC, BilalAlpaslan commented on docs/tr/docs/features.md
> +Bütün hepsi tekrardan kullanılabilir aletler ve bileşenler olarak, kolayca sistemlerinize, data depolarınıza, ilişkisel ve NoSQL databaselerinize entegre edebileceğiniz şekilde yapıldı.
"SQL ve NoSQL" or "ilişkisel ve ilişkisel olmayan"

2021-09-01 09:21 UTC, BilalAlpaslan approved these changes

2021-09-01 09:22 UTC, BilalAlpaslan approved these changes

2021-10-05 13:01 UTC, tiangolo commented
Thanks @ycd! :cookie: 

For new PRs, it seems it's better to have an independent PR to avoid conflicts. Thanks for your contribution! :cake: 

And thanks for the reviews @BilalAlpaslan and @umitkaanusta! :coffee:

2021-10-05 13:01 UTC, merged