🌐 Add Japanese translation for `docs/ja/docs/tutorial/handling-errors.md`
fastapi/fastapi pull request #1953
Opened 2020-08-23 08:37 UTC by SwftAlpc

This PR translates the tutorial/handling-errors.md to Japanese.
Please review tutorial/handling-errors.md.

~Issue #1571 generates a new directory to support Japanese.
PR #1656 generates a new directory for tutorial.
I will fix dependency after #1571 & #1656 are merged.~

2020-08-27 15:12 UTC, tokusumi requested changes
I found some typo and unnecessary symbol

2020-08-27 15:12 UTC, tokusumi commented on docs/ja/docs/tutorial/handling-errors.md
> +### 結果のレスポンス
### レスポンス結果

2020-08-27 15:12 UTC, tokusumi commented on docs/ja/docs/tutorial/handling-errors.md
> +そのため、HTTPステータスコードが`418`で、JSONの内容が以下のような明確なエラーを受け取ることになります:
そのため、HTTPステータスコードが`418`で、JSONの内容が以下のような明確なエラーを受け取ることになります:

2020-08-27 15:12 UTC, tokusumi commented on docs/ja/docs/tutorial/handling-errors.md
> +例えば、これらのエラーに対しては、JSONではなくプレーンテキストを返すようにすることができます:
例えば、これらのエラーに対しては、JSONではなくプレーンテキストを返すようにすることができます:

2020-08-27 15:12 UTC, tokusumi commented on docs/ja/docs/tutorial/handling-errors.md
> +受信したボディを含むデータが無効であることを示しレスポンスが表示されます:
受信したボディを含むデータが無効であることを示すレスポンスが表示されます:

2020-10-29 15:29 UTC, SwftAlpc commented
@tokusumi 
Thanks for the review!
Cloud you check it out?

2020-10-29 15:35 UTC, tokusumi approved these changes
Your work is awesome. Thank you.

2023-06-26 17:00 UTC, tiangolo commented
📝 Docs preview for commit e3f638b3aebd6d2c7a85431d319f2e1d40e38567 at: https://6499c40866a23b009bfcc170--fastapi.netlify.app

2024-01-15 15:43 UTC, alejsdev commented
Thanks for your help! @SwftAlpc 😸 

And thanks for reviewing @tokusumi 🔍🧐

2024-01-15 15:43 UTC, merged