🌐 Add Japanese translation for `docs/ja/docs/tutorial/dependencies/index.md`
fastapi/fastapi pull request #1957
Opened 2020-08-23 12:45 UTC by SwftAlpc

This PR translates the tutorial/dependencies/index.md to Japanese.
Please review tutorial/dependencies/index.md.

~Issue #1571 generates a new directory to support Japanese.
PR #1656 generates a new directory for tutorial.
I will fix dependency after #1571 & #1656 are merged.~

2020-09-03 15:00 UTC, tokusumi requested changes
thank you for translating difficult chapter!

2020-10-29 15:53 UTC, SwftAlpc commented
@tokusumi 
I approved your suggetions! Thank you!

2020-10-29 15:59 UTC, tokusumi approved these changes
LGTM 🚀

2021-01-17 14:42 UTC, sh0nk reviewed
Let me add just a couple of suggestions against typo and nitpicks!

2021-01-17 14:42 UTC, sh0nk commented on docs/ja/docs/tutorial/dependencies/index.md
> +依存関係は **FastAPI**（*path operation関数*と同じ）からも呼び出されるため、関数を定義する際にも同じルールが適用されます。
```suggestion
依存関係も（*path operation関数*と同様に） **FastAPI** から呼び出されるため、関数を定義する際にも同じルールが適用されます。
```
To clarify the meaning of the sentence.

2021-01-17 14:42 UTC, sh0nk commented on docs/ja/docs/tutorial/dependencies/index.md
> +統合や「プラグイン」は **依存性注入** システムを使って構築することができます。しかし、実際には、**「プラグイン」を作成する必要はありません**。依存関係を使用することで、無限の数の統合やインタラクションを宣言することができ、それが**path operation関数*で利用可能になるからです。
```suggestion
統合や「プラグイン」は **依存性注入** システムを使って構築することができます。しかし、実際には、**「プラグイン」を作成する必要はありません**。依存関係を使用することで、無限の数の統合やインタラクションを宣言することができ、それが*path operation関数*で利用可能になるからです。
```
typo

2021-01-17 14:42 UTC, sh0nk commented on docs/ja/docs/tutorial/dependencies/index.md
> +依存関係（およびサブ依存関係）のすべてのリクエスト宣言、検証、および要件は、同じOpenAPIスキーマに統合されます。
```suggestion
依存関係（およびサブ依存関係）のすべてのリクエスト宣言、バリデーション、および要件は、同じOpenAPIスキーマに統合されます。
```
To be consistent with #L207. (The other way round is fine too.)

2023-06-26 17:32 UTC, tiangolo commented
📝 Docs preview for commit fcb10ad3cc7489530f7343338c38e1cf0471ad4a at: https://6499cb4e7bcac500837f92f0--fastapi.netlify.app

2024-01-15 16:22 UTC, closed without merging

2024-01-15 16:22 UTC, tiangolo commented
As this was handled in https://github.com/tiangolo/fastapi/pull/1958, I'll go ahead and close this one. Thank you! ☕