🌐 Add Japanese translation for `docs/ja/docs/tutorial/dependencies/index.md` and `docs/ja/docs/tutorial/dependencies/classes-as-dependencies.md`
fastapi/fastapi pull request #1958
Opened 2020-08-23 13:28 UTC by SwftAlpc

This PR translates the tutorial/dependencies/classes-as-dependencies.md to Japanese.
Please review tutorial/dependencies/classes-as-dependencies.md.

~Issue #1571 generates a new directory to support Japanese.
PR #1656 generates a new directory for tutorial.~
PR #1957 generates a new directoru for dependencies in tutorial.
I will fix dependency after ~#1571,  #1656 and~ #1957 are merged.

2020-09-03 16:30 UTC, tokusumi requested changes

2020-09-03 16:30 UTC, tokusumi commented on docs/ja/docs/tutorial/dependencies/classes-as-dependencies.md
> +この場合、以下にある最初の`CommonQueryParams`は:
この場合、以下にある最初の`CommonQueryParams`:

2020-09-03 16:30 UTC, tokusumi commented on docs/ja/docs/tutorial/dependencies/classes-as-dependencies.md
> +しかし、ここでは`CommonQueryParams`を２回書くというコードの繰り返しが発生していることがわかります:
しかし、ここでは`CommonQueryParams`を２回書くというコードの繰り返しが発生していることがわかります:

2020-09-03 16:30 UTC, tokusumi commented on docs/ja/docs/tutorial/dependencies/classes-as-dependencies.md
> +**FastAPI** はこのような場合のためのショートカットを提供しています。依存関係が*特定の*クラスである場合、**FastAPI** がクラス自体のインスタンスを作成するために「呼び出しする」クラスを指定します。
依存関係が、クラス自体のインスタンスを作成するために**FastAPI**が「呼び出す」*特定の*クラスである場合、**FastAPI** はこれらのケースのショートカットを提供しています。

2020-10-29 16:00 UTC, SwftAlpc commented
@tokusumi 
I fixed some translations.
I adopt some your suggetions. Thanks for your review!

2020-10-29 16:04 UTC, tokusumi approved these changes
LGTM!

2024-01-15 16:08 UTC, alejsdev commented
Thanks for your help @SwftAlpc and the review @tokusumi 🐱✨

2024-01-15 16:08 UTC, merged