🌐 Add Japanese translation for `docs/ja/docs/tutorial/dependencies/sub-dependencies.md`
fastapi/fastapi pull request #1959
Opened 2020-08-23 14:28 UTC by SwftAlpc

This PR translates the tutorial/dependencies/sub-dependencies.md to Japanese.
Please review tutorial/dependencies/sub-dependencies.md.

~Issue #1571 generates a new directory to support Japanese.
PR #1656 generates a new directory for tutorial.~
PR #1957 generates a new directoru for dependencies in tutorial.
I will fix dependency after ~#1571, #1656 and~ #1957 are merged.

2020-09-03 16:41 UTC, tokusumi requested changes

2020-09-03 16:41 UTC, tokusumi commented on docs/ja/docs/tutorial/dependencies/sub-dependencies.md
> +そして、別の依存関数（「依存可能なもの」）を作成して、同時にそれ自身の依存関係を宣言することができます（つまりそれ自身も「依存」です）:
そして、別の依存関数（「依存可能なもの」）を作成して、同時にそれ自身の依存関係を宣言することができます（つまりそれ自身も「依存」です）:

2020-09-03 16:41 UTC, tokusumi commented on docs/ja/docs/tutorial/dependencies/sub-dependencies.md
> +依存関係の１つが同じ*path operation*に対して複数回宣言されている場合、例えば、複数の依存関係が共通のサブ依存関係を持っている場合、**FastAPI** はリクエストごとに１回だけそのサブ依存関係を呼び出すことを知っています。
依存関係の１つが同じ*path operation*に対して複数回宣言されている場合、例えば、複数の依存関係が共通のサブ依存関係を持っている場合、**FastAPI** はリクエストごとに１回だけそのサブ依存関係を呼び出します。

2020-10-29 16:04 UTC, SwftAlpc commented
@tokusumi 
Thanks for your reveiw!!
Please check it out.

2020-10-29 16:07 UTC, tokusumi approved these changes
Thank you for your work!

2023-06-26 17:04 UTC, tiangolo commented
📝 Docs preview for commit 734d90227f0382a0bc67ee541889a41d8badf423 at: https://6499c4ed4a9646007dd7a740--fastapi.netlify.app

2024-01-15 16:24 UTC, tiangolo commented
As this was made by @SwftAlpc and approved by @tokusumi, champions of the Japanese translations, I'm gonna merge this right away. 🚀  Thank you! ☕

2024-01-15 16:43 UTC, merged