First translate of benchmarks.md
fastapi/fastapi pull request #1963
Opened 2020-08-23 19:03 UTC by wfpinedar

First try to contribute to FastaAPI with translations

2020-09-08 19:24 UTC, Frans06 requested changes

2020-09-08 19:24 UTC, Frans06 commented on docs/es/docs/benchmarks.md
> +  * No escribirías una aplicación en Uvicorn directamente. Eso significaría que su código tendría que incluir más o menos, al menos, todo el código proporcionado por Starlette (o ** FastAPI **). Y si
```suggestion
  * No escribirías una aplicación en Uvicorn directamente. Eso significaría que tu código tendría que incluir más o menos, al menos, todo el código proporcionado por Starlette (o ** FastAPI **). Y si hiciera eso, su aplicación final tendría la misma sobrecarga que haber usado un framework y minimizando el código y los errores de su aplicación.
```

2020-09-08 19:24 UTC, Frans06 commented on docs/es/docs/benchmarks.md
> +  * Tendrá el siguiente mejor desempeño, después de Uvicorn. De hecho, Starlette usa Uvicorn para ejecutarse. Por lo tanto, probablemente solo podria volverse "más lento" que Uvicorn al tener que eje
```suggestion
  * Tendrá el siguiente mejor desempeño, después de Uvicorn. De hecho, Starlette usa Uvicorn para ejecutarse. Por lo tanto, probablemente solo se volvería "más lento" que Uvicorn cuando tenga que ejecutar más código.
```

2020-09-08 19:24 UTC, Frans06 commented on docs/es/docs/benchmarks.md
> +  * FastAPI proporciona más funciones además de Starlette. Funciones que casi siempre se necesitan al crear APIs, como validación y serialización de datos. Y al usarlo, obtiene documentación automáti
```suggestion
  * FastAPI proporciona más funciones además de Starlette. Funciones que casi siempre se necesitan al crear APIs, como validación y serialización de datos. Y al usarlo, obtienes documentación automática gratis (la documentación automática ni siquiera agrega sobre carga a las aplicaciones en ejecución, esta se genera al inicio).
```

2020-09-08 19:24 UTC, Frans06 commented on docs/es/docs/benchmarks.md
> +  * Si no usó FastAPI y usó Starlette directamente (u otra herramienta, como Sanic, Flask, Responder, etc.), tendría que implementar toda la validación y serialización de datos usted mismo. Por lo ta
```suggestion
  * Si no usaste FastAPI y usaste Starlette directamente (u otra herramienta, como Sanic, Flask, Responder, etc.), tendrías que implementar toda la validación y serialización de datos tú mismo. Por lo tanto, tu aplicación final aún tendría la misma sobre carga que si se hubiera creado con FastAPI. Y en muchos casos, esta validación y serialización de datos es la mayor cantidad de código escrito en las aplicaciones.
```

2020-09-08 19:24 UTC, Frans06 commented on docs/es/docs/benchmarks.md
> +  * Entonces, usando FastAPI usted esta ahorrando tiempo de desarrollo, errores, lineas de codigo y probablemente obtendria el mismo desempeño (o mejor) que si usted no usare este (ya que tendría que
```suggestion
  * Entonces, usando FastAPI estas ahorrando tiempo de desarrollo, errores, lineas de código y probablemente obtendrias el mismo desempeño (o mejor) que si no usaras este (ya que tendría que implementarlo todo en su código ).
```

2020-09-08 19:24 UTC, Frans06 commented on docs/es/docs/benchmarks.md
> +  * Si está comparando FastAPI, compárelo con un framework de aplicación web (o un conjunto de herramientas) que proporciona validación de datos, serialización y documentación, como Flask-apispec, Ne
```suggestion
  * Si está comparando FastAPI, compárelo con un framework de aplicación web (o un conjunto de herramientas) que proporciona validación de datos, serialización y documentación, como Flask-apispec, NestJS, Molten, etc. Frameworks con validación de datos automática, serialización y documentación, integrados.
```

2020-09-08 19:30 UTC, Frans06 commented
@wfpinedar  I'm adding some suggestions. Most of it because on English there is not "Honorificos". usted ~= tu. I think it could be more standard. One to other misspelling and grammar. In any case great translation.  Don't forget to add section on mkdocs.yml.
```
site_name: FastAPI
# More stuff
nav:
- FastAPI: index.md
- Languages:
  - en: /
  - es: /es/
- benchmark.md
```

2020-09-09 14:12 UTC, wfpinedar commented on docs/es/docs/benchmarks.md
> +Cuanto más simple sea el problema resuelto por la herramienta, mejor rendimiento obtendrá. Y la mayoría de los puntos de referencia no prueban las funciones adicionales proporcionadas por la herramie
Solve in: 28a89ca56c0a50353d9ce4b1fcc0453ee512d3f2

2020-09-09 16:31 UTC, Frans06 approved these changes

2021-01-19 17:41 UTC, pedabraham reviewed
Hi! I found some typos.
Oye, Encontré unas faltas de ortografía.

2021-01-19 17:41 UTC, pedabraham commented on docs/es/docs/benchmarks.md
> +  * Si no usaste FastAPI y usaste Starlette directamente (u otra herramienta, como Sanic, Flask, Responder, etc.), tendrías que implementar toda la validación y serialización de datos tú mismo. Por l
```suggestion
  * Si no usaste FastAPI y usaste Starlette directamente (u otra herramienta, como Sanic, Flask, Responder, etc.), tendrías que implementar toda la validación y serialización de datos tú mismo. Por lo tanto, tu aplicación final aún tendría la misma sobrecarga que si se hubiera creado con FastAPI. Y en muchos casos, esta validación y serialización de datos es la mayor cantidad de código escrito en las aplicaciones.
```

2021-12-30 02:46 UTC, israteneda requested changes
Algunas pequeñas correcciones

2021-12-30 02:46 UTC, israteneda commented on docs/es/docs/benchmarks.md
> +Los puntos de referencia  independientes, TechEmpower, colocan a las apliaciones **FastAPI** que se ejecutan bajo Uvicorn como <a href="https://www.techempower.com/benchmarks/#section=test&runid=7464
```suggestion
Los puntos de referencia  independientes, TechEmpower, colocan a las aplicaciones **FastAPI** que se ejecutan bajo Uvicorn como <a href="https://www.techempower.com/benchmarks/#section=test&runid=7464e520-0dc2-473d-bd34-dbdfd7e85911&hw=ph&test=query&l=zijzen-7" class="external-link" target="_blank"> uno de los frameworks de python más rapidos disponibles</a>, solo por debajo de Starlette y Uvicorn (utilizados internamente por FastAPI). (*)
```

2021-12-30 02:46 UTC, israteneda commented on docs/es/docs/benchmarks.md
> +La jerarquia es algo como:
```suggestion
La jerarquía es algo como:
```

2021-12-30 02:46 UTC, israteneda commented on docs/es/docs/benchmarks.md
> +Pero cuando verificas los puntos de referencia y las comparaciones, deberias tener en mente lo siguiente.
```suggestion
Pero cuando verificas los puntos de referencia y las comparaciones, deberías tener en mente lo siguiente.
```

2021-12-30 02:46 UTC, israteneda commented on docs/es/docs/benchmarks.md
> +    * **FastAPI**: (usa Starlette) un API microframework con varias funcionaldades adicionales para la creación de APIs, con validación de datos, etc.
```suggestion
    * **FastAPI**: (usa Starlette) un API microframework con varias funcionalidades adicionales para la creación de APIs, con validación de datos, etc.
```

2021-12-30 02:46 UTC, israteneda commented on docs/es/docs/benchmarks.md
> +  * Pero este provee las herramientos para contruir aplicaciones web simples, con direccionamiento basadao en rutas, etc.
```suggestion
  * Pero este provee las herramientas para construir aplicaciones web simples, con direccionamiento basado en rutas, etc.
```

2021-12-30 14:14 UTC, wfpinedar commented on docs/es/docs/benchmarks.md
> +Pero cuando verificas los puntos de referencia y las comparaciones, deberias tener en mente lo siguiente.
solved in @90181d8

2022-01-24 04:48 UTC, israteneda approved these changes
LGTM ✅

2024-02-07 12:54 UTC, alejsdev commented
This one was covered in a more recent PR (https://github.com/tiangolo/fastapi/pull/1353), but thanks for the effort @wfpinedar and thanks to everyone for the help 🤓

2024-02-07 12:54 UTC, closed without merging