Add benchmarks.md Japanese ver.
fastapi/fastapi pull request #1992
Opened 2020-08-31 13:32 UTC by komtaki

This PR translates the benchmarks.md to Japanese.

2020-09-12 17:23 UTC, tokusumi requested changes
appreciate for translating difficult chapter.
I suggest some improvement. feel free to discuss my comments.

2020-09-12 17:23 UTC, tokusumi commented on docs/ja/docs/benchmarks.md
> +ベンチマークを確認する時、いくつかの異なるツールを同じものとして比較するのが一般的です。
ベンチマークを確認する時、異なるツールを同等なものと比較するのが一般的です。

(表現の変更)

2020-09-12 17:23 UTC, tokusumi commented on docs/ja/docs/benchmarks.md
> +このツールで解決する問題がよりシンプルなほど、パフォーマンスが向上します。また、ほとんどのベンチマークは、提供された追加機能をテストしていません。
ツールで解決する問題がシンプルなほど、パフォーマンスが向上します。また、ほとんどのベンチマークは、ツールから提供される追加機能をテストしていません。

(より簡潔に)

2020-09-12 17:23 UTC, tokusumi commented on docs/ja/docs/benchmarks.md
> +    * **Starlette**: (Uvicorn使用) WEBマイクロフレームワーク
(Uvicornを使用)

2020-09-12 17:23 UTC, tokusumi commented on docs/ja/docs/benchmarks.md
> +        * **FastAPI**: (Starlette使用) データバリデーションなどの、APIを構築する追加機能を備えたAPIマイクロフレームワーク
(Starletteを使用)

2020-09-13 03:13 UTC, komtaki commented
@tokusumi 

Thanks for the review!! 👍 
I fixed everything. So, check my fix please.

2020-09-13 04:02 UTC, tokusumi approved these changes
LGTM!

2020-10-05 10:39 UTC, Attsun1031 reviewed
Thank you for your great work !
I suggested one minor correction, so please check.

2020-10-05 10:39 UTC, Attsun1031 commented on docs/ja/docs/benchmarks.md
> +    * もしStarletteを比較する場合は、Sanic、Flask、DjangoなどのWEBフレームワークと比較してください。
```suggestion
    * もしStarletteを比較する場合は、Sanic、Flask、DjangoなどのWEBフレームワーク (もしくはマイクロフレームワーク) と比較してください。
```

2020-10-05 13:28 UTC, komtaki commented
@Attsun1031 

I appreciate for your review and suggestion. 😀 
I applied your suggestion. Could you check ?

2020-10-05 14:42 UTC, Attsun1031 approved these changes
LGTM 👍

2020-10-17 18:42 UTC, tiangolo commented
Awesome, thanks @komtaki ! :rocket: :coffee: 

And thanks @Attsun1031 and @tokusumi for the reviews :cake: :bow:

2020-10-17 18:43 UTC, merged