Add japanese doc history-design-future.md
fastapi/fastapi pull request #2002
Opened 2020-09-02 08:50 UTC by komtaki

This PR translates the  history-design-future.md to Japanese.

2020-09-12 18:09 UTC, tokusumi requested changes

2020-09-12 18:09 UTC, tokusumi commented on docs/ja/docs/history-design-future.md
> +そして、[あなたの貢献](help-fastapi.md){.internal-link target=_blank}に非常に感謝しています。
そして、[あなたの助け](help-fastapi.md){.internal-link target=_blank}を大いに歓迎します。

(文脈的に今後の話をしていそうなので、こちらの訳の方があっていそうですが、どうでしょうか)

2020-09-13 03:35 UTC, komtaki commented
@tokusumi 

Thanks for the review!! 👍 
I fixed everything. So, check my fix please.

2020-09-13 04:08 UTC, tokusumi approved these changes
LGTM!

2020-09-27 05:59 UTC, Attsun1031 reviewed
Thanks for your translation ! Most of the translation felt okay, 

I commented only about the consistency with alternatives.md translation.

2020-09-27 05:59 UTC, Attsun1031 commented on docs/ja/docs/history-design-future.md
> +[代替手段とインスピレーション、比較](alternatives.md){.internal-link target=_blank}のセクションでこう述べています:
```suggestion
[代替ツールから受けたインスピレーションと比較](alternatives.md){.internal-link target=_blank}のセクションでこう述べています:
```

alternatives.mdの日本語訳と整合性を取りました。
https://github.com/tiangolo/fastapi/pull/2043/files

2020-09-27 05:59 UTC, Attsun1031 commented on docs/ja/docs/history-design-future.md
> +<blockquote markdown="1">
ここの、alternatives.mdのIntroからの引用についても、整合性をとるとよさそうです。
以下が、現在Openされているalternatives.mdの翻訳PRです。7〜13行目が引用箇所にあたります。

https://github.com/tiangolo/fastapi/pull/2043/files#diff-8c2de13ace5af8415261629c58b6449aR5

2020-09-27 08:17 UTC, komtaki commented
@Attsun1031 

Thank you for your comment.
I fixed to match to https://github.com/tiangolo/fastapi/pull/2043/

Please check my fix.

2020-09-27 09:30 UTC, Attsun1031 approved these changes
LGTM👍

2020-09-29 08:56 UTC, tokusumi commented
Hi, @tiangolo
This PR has been approved by two reviewers (github actions to label approved PR didn't work, though).
Would you like to require something more for this to be merged?

2020-09-29 09:25 UTC, Mause commented
I believe @tiangolo is currently moving houses, so you'll have to be patient

2020-09-29 09:54 UTC, tokusumi commented
Oops. I'm really sorry for annoying notification :bow:

2020-10-18 05:26 UTC, merged

2020-10-18 05:26 UTC, tiangolo commented
Great! Thank you @komtaki ! :bow: :coffee: 

Thanks for the reviews @Attsun1031 and @tokusumi ! :cake: :nerd_face: 

And thanks @Mause for helping with the clarification! :smile: Indeed, finding a flat in Berlin is quite difficult and has a bunch of complications... I'm still waiting for the internet connection to be installed in my house :sweat_smile: 

But also thanks @tokusumi for pointing out the broken bot :man_facepalming: I wrote one to replace it and it should work fine from now on :robot: :rocket: