Add Japanese translation for alternatives.md
fastapi/fastapi pull request #2043
Opened 2020-09-13 06:18 UTC by Attsun1031

This PR translates the alternatives.md to Japanese.
Please review alternatives.md.

2020-09-13 06:19 UTC, Attsun1031 commented on docs/ja/mkdocs.yml
> +- alternatives.md
Only this line is edited manually, others are changed automatically by `python scripts/docs.py build-all
`.

2020-09-13 13:44 UTC, tokusumi requested changes
appreciate for tough work. most of your translation is perfect. 
I commented better word choices for unification and small corrections.

2020-09-13 13:44 UTC, tokusumi commented on docs/ja/docs/alternatives.md
> +!!! check "**FastAPI**への影響"
!!! check "**FastAPI**での使用用途"

2020-09-13 13:44 UTC, tokusumi commented on docs/ja/docs/alternatives.md
> +!!! check "**FastAPI**への影響"
!!! check "FastAPIでの使用用途"

2020-09-13 13:44 UTC, tokusumi commented on docs/ja/docs/alternatives.md
> +    `FastAPI`クラスそのものは、`Starlette`クラスを直接継承しています。
webに関するコアな部分を全て扱います。その上に機能を追加します。

    `FastAPI`クラスは、`Starlette`クラスを直接継承しています。

(1行抜けています。)

2020-09-13 13:44 UTC, tokusumi commented on docs/ja/docs/alternatives.md
> +基本的にはStarletteの強化版であるため、Starletteで可能なことは**FastAPI**で直接可能です。
基本的にはStarletteの強化版であるため、Starletteで可能なことは**FastAPI**で直接可能です。

(インデントの追加)

2020-09-13 13:44 UTC, tokusumi commented on docs/ja/docs/alternatives.md
> +!!! check "**FastAPI** への影響"
!!! check "**FastAPI** が推奨する理由"

2020-09-17 09:41 UTC, Attsun1031 commented on docs/ja/docs/alternatives.md
> +しかし、FastAPI は Requests からかなりのインスピレーションを得ています。
確かにそうですね。「影響」は少しニュアンスが違うような気がしますので、「インスピレーション」に統一しようと思います。

2020-09-17 10:36 UTC, Attsun1031 commented on docs/ja/docs/alternatives.md
> +**Requests**は(クライアントとして)APIと*通信*するためのライブラリであり、**FastAPI**は(サーバーとして)APIを*構築*するためのライブラリです。
ありがとうございます。「半角スペース + 半角括弧」で統一します。

2020-09-17 12:24 UTC, Attsun1031 commented
@tokusumi Thanks for your review! I fixed everything, so please check changes.

2020-09-17 12:43 UTC, tokusumi requested changes
your updates is perfect.

unfortunately, I found some correction to unify "!!!" syntax. please check docs preview what is problem.

2020-09-17 12:43 UTC, tokusumi commented on docs/ja/docs/alternatives.md
> +!!! 備考
!!! note "備考"

2020-09-17 12:43 UTC, tokusumi commented on docs/ja/docs/alternatives.md
> +!!! 情報
!!! info "情報"

2020-09-17 12:43 UTC, tokusumi commented on docs/ja/docs/alternatives.md
> +!!! 情報
!!! info "情報"

2020-09-17 12:43 UTC, tokusumi commented on docs/ja/docs/alternatives.md
> +!!! info
!!! info "情報"

2020-09-17 12:43 UTC, tokusumi commented on docs/ja/docs/alternatives.md
> +!!! 備考 "技術的な詳細"
!!! note "技術詳細"

2020-09-17 12:43 UTC, tokusumi commented on docs/ja/docs/alternatives.md
> +!!! 備考 "技術的な詳細"
!!! note "技術詳細"

2020-09-17 12:43 UTC, tokusumi commented on docs/ja/docs/alternatives.md
> +!!! 情報
!!! info "情報"

2020-09-17 12:43 UTC, tokusumi commented on docs/ja/docs/alternatives.md
> +!!! 情報
!!! info "情報"

2020-09-18 13:18 UTC, Attsun1031 commented
@tokusumi Thanks for your careful review ! I fixed all (and some other points) , so please check once again.
https://github.com/tiangolo/fastapi/pull/2043/commits/e8869eb493d7ffcd4d69adf4e2e15fcd7d35ef46

2020-09-18 16:30 UTC, tokusumi approved these changes
thank you for improvements 👍

2020-09-25 02:49 UTC, komtaki reviewed
Thank you for the tough work.
I commented to make it easier to read as Japanese.

2020-09-25 02:49 UTC, komtaki commented on docs/ja/docs/alternatives.md
> +バックエンドでHTMLを生成するために作られたものであり、現代的なフロントエンド (ReactやVue.js、Angularなど) や、他のシステム (IoTデバイスなど) と通信するためのAPIを構築するために作られたものではありません。
```suggestion
バックエンドでHTMLを生成するために作られたものであり、現代的なフロントエンド (ReactやVue.js、Angularなど) や、他のシステム (IoTデバイスなど) と通信するAPIを構築するために作られたものではありません。
```

「ため」が連続していて、日本語として少し違和感を感じました。

2020-09-25 02:49 UTC, komtaki commented on docs/ja/docs/alternatives.md
> +Django REST Frameworkは、Djangoを下敷きにしてWeb APIを構築するための柔軟なツールキットとして、APIの機能を向上させるために作られました。
```suggestion
Django REST Frameworkは、Djangoを下敷きにしてWeb APIを構築する柔軟なツールキットとして、APIの機能を向上させるために作られました。
```

「ため」が連続していて、日本語として少し違和感を感じました。

2020-09-25 02:49 UTC, komtaki commented on docs/ja/docs/alternatives.md
> +APIシステムで必要とされる主な機能の一つに、コード (Python) からデータを取り出して、ネットワークを介して送れるものに変換するという、データの「<abbr title="marshalling, conversion">シリアライゼーション</abbr>」があります。例えば、データベースのデータを含むオブジェクトをJSONオブジェクトに変換したり、`datetime` オブジェクトを文
```suggestion
APIシステムで必要とされる主な機能の一つに、コード (Python) からデータを取り出して、ネットワークを介して送れるものに変換するデータの「<abbr title="marshalling, conversion">シリアライゼーション</abbr>」があります。例えば、データベースのデータを含むオブジェクトをJSONオブジェクトに変換したり、`datetime` オブジェクトを文字列に変換するなどです。
```

冗長に感じました。ない方が読みやすい気がします。

2020-09-25 02:49 UTC, komtaki commented on docs/ja/docs/alternatives.md
> +同じフレームワークを使ってAPIとCLIを作成できるという、面白く珍しい機能を持っています。
```suggestion
同じフレームワークを使ってAPIとCLIを作成できる、面白く珍しい機能を持っています。
```
冗長に感じました。

2020-09-26 06:44 UTC, Attsun1031 commented
@komtaki Thanks for your careful review and suggestions ! I applied all your suggestions.

2020-09-26 08:11 UTC, komtaki approved these changes
Thank you. 👍 

LGTM 👌

2020-09-26 12:05 UTC, tokusumi commented
Hi, @tiangolo
This PR has been approved by two reviewers (github actions to label approved PR didn't work, though).
Would you like to require something more for this to be merged?

2020-10-18 05:35 UTC, tiangolo commented
Awesome! Thank you @Attsun1031 ! :bow: :cake: 

And thanks @komtaki and @tokusumi for the reviews! :rocket: :clap:

2020-10-18 05:38 UTC, merged