Add contributing.md Japanese ver.
fastapi/fastapi pull request #2067
Opened 2020-09-17 10:09 UTC by komtaki

This PR translates the contributing.md to Japanese.

According to the issue: #1572 

Thanks!!

2020-09-17 15:27 UTC, tokusumi requested changes
Thank you for good work. I propose some small correction and question.

2020-09-17 15:27 UTC, tokusumi commented on docs/ja/docs/contributing.md
> +* <a href="https://github.com/tiangolo/fastapi/issues" class="external-link" target="_blank">課題</a>をチェックして、あなたの言語に関連する翻訳があるかどうかを確認してください言語。
<a href="https://github.com/tiangolo/fastapi/issues" class="external-link" target="_blank">issues</a> をチェックして、あなたの言語に対応する翻訳があるかどうかを確認してください。

(GitHubは日本語ページがないので、課題と書くと何のことかわからないかもしれません)

2020-09-17 15:27 UTC, tokusumi commented on docs/ja/docs/contributing.md
> +自分が話さない言語については、他の何人かが翻訳をレビューするのを待って、マージします。
自分 -> 作者 or 私

(your languageの訳の「自分」が多用される中で、ここでtiangoloを指して「自分」というと、一瞬迷う人もいるかもしれないです)

2020-09-17 15:27 UTC, tokusumi commented on docs/ja/docs/contributing.md
> +スペイン語など、一部のページの翻訳がすでにある言語のページを翻訳するとします。
スペイン語の様に、既に一部のページが翻訳されている言語の翻訳を追加したいとしましょう。

(言い換え)

2020-09-17 15:27 UTC, tokusumi commented on docs/ja/docs/contributing.md
> +!!! tip 豆七機
!!! tip "豆知識"

2020-09-17 15:27 UTC, tokusumi commented on docs/ja/docs/contributing.md
> +上からリンクを確認すると、「クレオール語」のコードは `ht`です。
上記の

2020-09-17 15:27 UTC, tokusumi commented on docs/ja/docs/contributing.md
> +その後、「既存の言語」で、さきほどの手順がを続行してください。
手順を
(タイポ)

2020-09-17 15:27 UTC, tokusumi commented on docs/ja/docs/contributing.md
> +警告: これは非常にシンプルなサーバーです。開発中には、代わりにmkdocs serveを使用してください。
(これは、コメントではなくて、スクリプト実行時に実際に表示されるオリジナルの警告文ではないですか？そうであれば他の箇所と同様に原文のままがいいと思います)

2020-09-17 23:43 UTC, komtaki commented on docs/ja/docs/contributing.md
> +警告: これは非常にシンプルなサーバーです。開発中には、代わりにmkdocs serveを使用してください。
確かに、コマンドの警告文ですね。翻訳しすぎました。:sweat:

2020-09-18 00:02 UTC, komtaki commented
@tokusumi 

Thanks for the review!! 👍 I am embarrassed to many careless miss. 😓 
I fixed everything. So, check my fix please.

2020-09-18 03:12 UTC, tokusumi approved these changes
LGTM!
Never mind that. Finding careless mistakes is main task for reviewer.

2020-10-10 07:39 UTC, Attsun1031 reviewed
Thank you for your tough work !
I just made one comment, please check it out.

2020-10-10 07:39 UTC, Attsun1031 commented on docs/ja/docs/contributing.md
> +このコマンドは`./htmlcov/`ディレクトリを生成します。ブラウザーでファイル`./htmlcov/index.html`を開くと、テストでカバーされているコードの領域をインタラクティブに探索できます。それによりテストが不足しているかどうか気付くことができます。
```suggestion
このコマンドは`./htmlcov/`ディレクトリを生成します。ブラウザでファイル`./htmlcov/index.html`を開くと、テストでカバーされているコードの領域をインタラクティブに探索できます。それによりテストが不足しているかどうか気付くことができます。
```

「ブラウザー」 => 「ブラウザ」
(「ブラウザ」 is used at line 380.)

2020-10-10 11:47 UTC, komtaki commented
@Attsun1031 

Thank you for the suggestion.
I applied it. Check the fix please. 👍

2020-10-10 15:18 UTC, Attsun1031 approved these changes
LGTM 👍

2020-10-18 05:56 UTC, tiangolo commented
Awesome, thank you @komtaki ! :bow: :coffee: 

And thanks @Attsun1031 and @tokusumi for the reviews :nerd_face: :cake:

2020-10-18 05:57 UTC, merged