Add Chinese translation for benchmarks.md
fastapi/fastapi pull request #2119
Opened 2020-10-02 07:33 UTC by spaceack

@

2020-10-09 03:59 UTC, waynerv requested changes

2020-10-09 03:59 UTC, waynerv commented on docs/zh/docs/benchmarks.md
> +当您做基准测试检查时，通常会看到被视为等效的几种不同类型的工具。
当你查看基准测试时，几个不同类型的工具被等效地做比较是很常见的情况。

2020-10-09 03:59 UTC, waynerv commented on docs/zh/docs/benchmarks.md
> +    * 您不会直接在 Uvicorn 中编写应用程序。这意味着您的代码至少必须包含 Starlette（或 **FastAPI**）提供的代码。如果您这样做了，最终应用程序和框架会最大程度地减少应用程序代码的编码量和错误。
”And if you did that, your final application would have the same overhead as having used a framework and minimizing your app code and bugs.“ means "如果你这样做了（即直接在 Uvicorn 中编写应用程序），你最终的应用程序会和使用了框架并且最小化了应用代码和 bug 的情况具有相同的性能损耗。

2020-10-09 03:59 UTC, waynerv commented on docs/zh/docs/benchmarks.md
> +    * 因此，通过使用 FastAPI 意味着你可以节省开发时间，减少编码错误，用更少的编码实现其功能，如果您不使用 FastAPI，可能会获得同以前相同（或更好）的性能（因为您必须在代码中实现所有功能）。
"and you would probably get the same performance (or better) you would if you didn't use it (as you would have to implement it all in your code)." should be "并且相比不使用 FastAPI 你很大可能会获得相同或更好的性能（因为那样你必须在你的代码中实现所有相同的功能）

2020-10-09 13:10 UTC, spaceack commented on docs/zh/docs/benchmarks.md
> +    * 您不会直接在 Uvicorn 中编写应用程序。这意味着您的代码至少必须包含 Starlette（或 **FastAPI**）提供的代码。如果您这样做了，最终应用程序和框架会最大程度地减少应用程序代码的编码量和错误。
Thank you for your review

2020-10-10 02:09 UTC, waynerv approved these changes
LGTM.

2020-11-21 14:44 UTC, Laineyzhang55 approved these changes

2020-11-25 17:26 UTC, tiangolo commented
Great! Thank you @spaceack :bow: :rocket: 

And thanks @waynerv and @Laineyzhang55 for the reviews :clap: :clap: :coffee:

2020-11-25 17:35 UTC, merged