Add advanced/additional-status-codes.md Japanese ver.
fastapi/fastapi pull request #2145
Opened 2020-10-07 15:53 UTC by Attsun1031

This PR translates the advanced/additional-status-codes.md to Japanese.
Please review advanced/additional-status-codes.md and ja/mkdocs.yml.

2020-10-10 12:15 UTC, komtaki reviewed
Thank you for the translate.
I commented a few minor suggestion. 👍

2020-10-10 12:15 UTC, komtaki commented on docs/ja/docs/advanced/additional-status-codes.md
> +しかし、新しいitemも許可したいとします。itemが存在しない場合は、それらを作成して201 "Created"を返すとします。
```suggestion
しかし、新しいitemも許可したいです。itemが存在しない場合は、それらを作成して201 "Created"を返します。
```

You can see from the previous sentence that it is a hypothetical story. So I think this is more natural.

2020-10-10 12:15 UTC, komtaki commented on docs/ja/docs/advanced/additional-status-codes.md
> +
```suggestion
```

The original have the one new line.

2020-10-11 07:03 UTC, Attsun1031 commented
@komtaki Thank you for your review! I fixed everything, so please check again.

2020-10-11 10:43 UTC, komtaki approved these changes
LGTM 👌

2020-10-18 08:09 UTC, Attsun1031 commented
I resolved all conflicts. (All were mkdocs nav order)
https://github.com/tiangolo/fastapi/pull/2145/commits/6214f7492e15693d66628eb15f94c0152abc2798

2020-11-25 11:44 UTC, tokusumi requested changes
Thank you for your work! I'd like to propose some feedbacks.

2020-11-25 11:44 UTC, tokusumi commented on docs/ja/docs/advanced/additional-status-codes.md
> +メインのステータスコードとは別に追加のステータスコードを返したい場合は、追加のステータスコードが設定された `JSONResponse` のような `Response` を直接返します。
```suggestion
メインのステータスコードとは別に、他のステータスコードを返したい場合は、`Response` (`JSONResponse` など) に追加のステータスコードを設定して直接返します。
```

2020-11-25 11:44 UTC, tokusumi commented on docs/ja/docs/advanced/additional-status-codes.md
> +    上記の例のように `Response` を直接返す場合、それは直接返されます。
```suggestion
    上記の例のように `Response` を明示的に返す場合、それは直接返されます。
```
自然に

2020-11-25 11:44 UTC, tokusumi commented on docs/ja/docs/advanced/additional-status-codes.md
> +もし追加のステータスコードとレスポンスを直接返す場合、それらはOpenAPIスキーマ (APIドキュメント) には含まれません。なぜなら、FastAPIは何が返されるのか事前に知ることができないからです。
```suggestion
ステータスコードとレスポンスを直接返す場合、それらはOpenAPIスキーマ (APIドキュメント) には含まれません。なぜなら、FastAPIは何が返されるのか事前に知ることができないからです。
```
意味が通るなら、できる限り、additionalは訳さない方が読みやすいと思います。

2020-11-29 00:17 UTC, tokusumi approved these changes

2020-12-03 17:00 UTC, merged

2020-12-03 17:01 UTC, tiangolo commented
Thanks a lot @Attsun1031 for your work! :cake: :rocket: 

And thanks @tokusumi and @komtaki for the reviews! :bow: :coffee: