Add tutorial/security/first-steps.md Japanese ver.
fastapi/fastapi pull request #2153
Opened 2020-10-10 13:04 UTC by komtaki

This PR translates the `tutorial/security/first-steps.md` to Japanese.

According to the issue: #1572

I merged the PR for dependency: https://github.com/tiangolo/fastapi/pull/1656
So. Please check the commit : https://github.com/tiangolo/fastapi/commit/18f28de1e84cc3484a7258d738c1083363bccce2

Thanks!!

2020-10-11 08:14 UTC, Attsun1031 reviewed
Thank you for your tough work!
Please check comments I made.

2020-10-11 08:14 UTC, Attsun1031 commented on docs/ja/docs/tutorial/security/first-steps.md
> +    非常に厳格な「Pythonista」であれば、パラメーター名の`token_url`ではなく`tokenUrl`のスタイルが気に入らないかもしれません。
```suggestion
    非常に厳格な「Pythonista」であれば、パラメーター名のスタイルが`token_url`ではなく`tokenUrl`であることを気に入らないかもしれません。
```
Easier to read Japanese.

2020-10-11 08:14 UTC, Attsun1031 commented on docs/ja/docs/tutorial/security/first-steps.md
> +**FastAPI**は、この依存関係を使用してOpenAPIスキーマ(および自動APIドキュメント)で「セキュリティスキーム」を定義できることを知っています。
```suggestion
**FastAPI**は、この依存関係を使用してOpenAPIスキーマ (および自動APIドキュメント) で「セキュリティスキーム」を定義できることを知っています。
```

2020-10-11 08:14 UTC, Attsun1031 commented on docs/ja/docs/tutorial/security/first-steps.md
> +    OpenAPIと統合するセキュリティユーティリティ(および自動APIドキュメント)はすべて`SecurityBase`を継承しています。それにより、**FastAPI**はそれらをOpenAPIに統合する方法を知ることができます。
```suggestion
    OpenAPIと統合するセキュリティユーティリティ (および自動APIドキュメント) はすべて`SecurityBase`を継承しています。それにより、**FastAPI**はそれらをOpenAPIに統合する方法を知ることができます。
```

2020-10-11 08:14 UTC, Attsun1031 commented on docs/ja/docs/tutorial/security/first-steps.md
> +## 機能
```suggestion
## どのように動作するか
```

2020-10-11 10:42 UTC, komtaki commented
@Attsun1031 

Thank you for your review. 👍 
I applied your suggestion. So, check please.

2020-10-13 13:43 UTC, Attsun1031 approved these changes
LGTM 👍

2020-10-29 14:44 UTC, tokusumi requested changes
Thank you for tough work! I commented some improvements (there are a too tiny changes 😅 )

2020-10-29 14:44 UTC, tokusumi commented on docs/ja/docs/tutorial/security/first-steps.md
> +**FastAPI**が提供するツールを使って、セキュリティを制御してみます。
```suggestion
**FastAPI**が提供するツールを使って、セキュリティを制御してみましょう。
```

2020-10-29 14:44 UTC, tokusumi commented on docs/ja/docs/tutorial/security/first-steps.md
> +まずはこのコードを使って、どう動くか観察します。その後で、何が起こっているのか理解するために戻ってきましょう。
```suggestion
まずはこのコードを使って、どう動くか観察します。その後で、何が起こっているのか理解しましょう。
```

日本語ではこのぐらいシンプルな方が自然な気がします。

2020-10-29 14:44 UTC, tokusumi commented on docs/ja/docs/tutorial/security/first-steps.md
> +    これは、**OAuth2**が「ユーザー名」や「パスワード」を送信するために、**フォームデータ** を使うからです。
```suggestion
    これは、**OAuth2**が `ユーザー名` や `パスワード` を送信するために、「フォームデータ」を使うからです。
```

`hoge` はそのままで、"fuga" は「fuga」に変換するように統一されてきています。

2020-10-29 14:44 UTC, tokusumi commented on docs/ja/docs/tutorial/security/first-steps.md
> +インタラクティブなドキュメントにアクセスしてください: <a href="http://127.0.0.1:8000/docs" class="external-link" target="_blank">http://127.0.0.1:8000/docs</a>。
```suggestion
次のインタラクティブなドキュメントにアクセスしてください: <a href="http://127.0.0.1:8000/docs" class="external-link" target="_blank">http://127.0.0.1:8000/docs</a>。
```

好みの問題だと思うので微妙なら無視してください。

2020-10-29 14:44 UTC, tokusumi commented on docs/ja/docs/tutorial/security/first-steps.md
> +もちろん最終的なユーザーのためのフロントエンドではありません。しかし、すべてのAPIをインタラクティブにドキュメント化するための素晴らしい自動ツールです。
```suggestion
もちろんエンドユーザーのためのフロントエンドではありません。しかし、すべてのAPIをインタラクティブにドキュメント化するための素晴らしい自動ツールです。
```

2020-10-29 14:44 UTC, tokusumi commented on docs/ja/docs/tutorial/security/first-steps.md
> +これをフロントエンドチームが使用できます (また、あなた自身が使用することもできます) 。
```suggestion
フロントエンドチームはこれを利用できます (また、あなたも利用できます) 。
```
簡潔に

2020-10-29 14:44 UTC, tokusumi commented on docs/ja/docs/tutorial/security/first-steps.md
> +この例では、**Bearer**トークンを使用して**OAuth2**を**パスワード**フローで使用します。これには`OAuth2PasswordBearer`クラスを使用します。
password flowの訳は「パスワードのフロー」か「パスワードフロー」のどちらかに統一したほうがいいと思います。後者の方が適切に感じます。

2020-10-29 14:44 UTC, tokusumi commented on docs/ja/docs/tutorial/security/first-steps.md
> +クラス`OAuth2PasswordBearer`のインスタンスを作成する時に、パラメーター`tokenUrl`を渡します。このパラメーターには、クライアント (ユーザーのブラウザで動作するフロントエンド) がトークンを取得するために`ユーザー名`と`パスワード`を送信するURLを指定します。
```suggestion
`OAuth2PasswordBearer` クラスのインスタンスを作成する時に、パラメーター`tokenUrl`を渡します。このパラメーターには、クライアント (ユーザーのブラウザで動作するフロントエンド) がトークンを取得するために`ユーザー名`と`パスワード`を送信するURLを指定します。
```

2020-10-29 14:44 UTC, tokusumi commented on docs/ja/docs/tutorial/security/first-steps.md
> +    相対 URL を使うことは、[プロキシと接続](./.../advanced/behind-a-proxy.md){.internal-link target=_blank}のような高度なユースケースでもアプリケーションが動作し続けることを確認するために重要です。
```suggestion
    相対 URL を使うことは、[プロキシと接続](./.../advanced/behind-a-proxy.md){.internal-link target=_blank}のような高度なユースケースでもアプリケーションを動作させ続けるために重要です。
```
簡潔に

2020-10-29 14:44 UTC, tokusumi commented on docs/ja/docs/tutorial/security/first-steps.md
> +    **FastAPI**は、クラス`OAuth2PasswordBearer` (依存関係で宣言されている) を使用してOpenAPIのセキュリティスキームを定義できることを知っています。これは`fastapi.security.oauth2.OAuth2`、`fastapi.security.base.SecurityBase`を継承しているからです。
```suggestion
    **FastAPI**は、`OAuth2PasswordBearer` クラス (依存関係で宣言されている) を使用してOpenAPIのセキュリティスキームを定義できることを知っています。これは`fastapi.security.oauth2.OAuth2`、`fastapi.security.base.SecurityBase`を継承しているからです。
```

2020-11-02 14:17 UTC, komtaki commented on docs/ja/docs/tutorial/security/first-steps.md
> +この例では、**Bearer**トークンを使用して**OAuth2**を**パスワード**フローで使用します。これには`OAuth2PasswordBearer`クラスを使用します。
統一しました 🙇

2020-11-02 14:19 UTC, komtaki commented
@tokusumi 

Thanks for your review. I applied your suggestions and fixed. 👍 
So, check please.

2020-11-02 14:22 UTC, tokusumi approved these changes
LGTM!

2020-11-05 22:24 UTC, merged

2020-11-05 22:24 UTC, tiangolo commented
Awesome, thank you @komtaki ! :cake: :coffee: 

And thanks @tokusumi and @Attsun1031 for the reviews! :bow: