Set response model defaults at application and router levels
fastapi/fastapi pull request #2187
Opened 2020-10-17 08:15 UTC by frjonsen

This PR is currently lacking tests. I figured I would create a PR with this draft to get some feedback on the general idea first.

This would allow for setting the default value of `response_model_by_alias`, `response_model_exclude_unset`, `response_model_exclude_defaults` and `response_model_exclude_none` at an application or at a router level, rather than on each individual endpoint

2021-04-14 00:25 UTC, philipbjorge commented
@frjonsen --
This would be useful for our team as we're having to set this on every API route.

What needs to happen to get this PR reviewed/considered for main?

Thanks for all your hard work 🙇 !

2022-01-30 19:25 UTC, cikay requested changes

2022-01-30 19:25 UTC, cikay commented on fastapi/routing.py
>              if isinstance(route, APIRoute):
Reverse the condition and add the continue statement to the if statement to decrease the indentation level.

2023-02-21 13:28 UTC, dkatzan commented
@cikay @frjonsen 
will be happy to see this PR merged, as my team as well need to set these flags in every API route
looks like this PR is also a bit outdated and has conflicts

will be happy to pick it up from here and open a new PR

2023-02-22 06:21 UTC, frjonsen commented
> will be happy to pick it up from here and open a new PR

I have since moved on to different projects that don't use FastAPI, so feel free finish this yourself, if you want.

2026-05-23 15:34 UTC, tiangolo commented
Thanks for the interest and work on this! ☕

I want to implement a big refactor in how routers work that will solve many of these use cases.

I also need to do that before expanding the surface of what is supported with additional external PRs, because that also means I would have to keep maintaining and handling backwards compatibility for those new changes while doing that big refactor.

I have not wanted to close PRs that target the same or similar problems before I have an alternative, but then I have left many PRs open for too long, which is not useful or clear either. Sorry for that.

And then, after I make those big refactors, the problem might be solved... and if not, a bunch of conflicts will show up, so it will be better and easier to start from scratch (from the new code state).

So, I'll close this one for now to keep things clean.

For the specific use case, the best would be to document it in a new GitHub Discussion (or 👍 any existing one) with the specific problem to solve (without details of the implementation) to track the feature request.

Thank you! 🍰

2026-05-23 15:34 UTC, closed without merging