Add Japanese translation for Advanced - response-directly
fastapi/fastapi pull request #2191
Opened 2020-10-18 05:34 UTC by Attsun1031

This PR translates the advanced/response-directly.md to Japanese.

2020-10-29 14:56 UTC, tokusumi requested changes
Thank you for great work!

2020-10-29 14:56 UTC, tokusumi commented on docs/ja/docs/advanced/response-directly.md
> +デフォルトでは、**FastAPI** は [JSON Compatible Encoder](../tutorial/encoder.md){.internal-link target=_blank} で説明されている `jsonable_encoder` により、返される値を自動的にJSONに変換します。
```suggestion
デフォルトでは、**FastAPI** は [JSON互換エンコーダ](../tutorial/encoder.md){.internal-link target=_blank} で説明されている `jsonable_encoder` により、返す値を自動的にJSONに変換します。
```
PRにあるタイトルを使用。

2020-10-29 14:56 UTC, tokusumi commented on docs/ja/docs/advanced/response-directly.md
> +これは多くの柔軟性を提供します。任意のデータ型を返したり、任意のデータ宣言やバリデーションをオーバーライドしたりすることができます。
```suggestion
これは多くの柔軟性を提供します。任意のデータ型を返したり、任意のデータ宣言やバリデーションをオーバーライドできます。
```
簡潔に

2020-10-29 14:56 UTC, tokusumi commented on docs/ja/docs/advanced/response-directly.md
> +このようなケースでは、レスポンスにデータを含める前に `jsonable_encoder` を使ってデータ変換をすることができます。
```suggestion
このようなケースでは、レスポンスにデータを含める前に `jsonable_encoder` を使ってデータを変換できます。
```
簡潔に

2020-10-29 14:56 UTC, tokusumi commented on docs/ja/docs/advanced/response-directly.md
> +    また、`from starlette.responses import JSONResponse` も利用することができます。
```suggestion
    また、`from starlette.responses import JSONResponse` も利用できます。
```
簡潔に

2020-10-29 14:56 UTC, tokusumi commented on docs/ja/docs/advanced/response-directly.md
> +    **FastAPI** は開発者の利便性のために `starlette.responses` を `fastapi.responses` と同じものとして提供しています。しかし、利用可能なレスポンスのほとんどはStarletteから直接提供されます。
```suggestion
    **FastAPI** は開発者の利便性のために `fastapi.responses` という `starlette.responses` と同じものを提供しています。しかし、利用可能なレスポンスのほとんどはStarletteから直接提供されます。
```

2020-10-29 14:56 UTC, tokusumi commented on docs/ja/docs/advanced/response-directly.md
> +XMLを文字列にし、 `Response` に含め、それを返します。
```suggestion
XMLを文字列にし、`Response` に含め、それを返します。
```

2020-10-30 01:25 UTC, Attsun1031 commented
@tokusumi Thank you for your review ! Every your suggestion are applied, so please check again.

2020-10-30 03:09 UTC, tokusumi approved these changes
Thank you for cooperating!

2020-11-02 14:38 UTC, komtaki reviewed
Thank your for your work.

I commented a few small suggestions.

2020-11-02 14:38 UTC, komtaki commented on docs/ja/docs/advanced/response-directly.md
> +例えば、Pydanticモデルを `JSONResponse` に含めるには、すべてのデータ型 (`datetime` や `UUID` など) がJSON互換の型に変換された `dict` に変換しなければなりません。
```suggestion
例えば、Pydanticモデルを `JSONResponse` に含めるには、すべてのデータ型 (`datetime` や `UUID` など) をJSON互換の型に変換された `dict` に変換しなければなりません。
```

2020-11-02 14:38 UTC, komtaki commented on docs/ja/docs/advanced/response-directly.md
> +後のセクションで、カスタム `Response` を使用・宣言しながら、自動的なデータ変換やドキュメンテーションを行う方法を見ることができます。
```suggestion
後のセクションで、カスタム `Response` を使用・宣言しながら、自動的なデータ変換やドキュメンテーションを行う方法を説明します。
```

この方が自然だと思います。

2020-11-04 02:50 UTC, Attsun1031 commented
@komtaki Thank you for your review ! I fixed everything, so please check again.

2020-11-04 12:18 UTC, komtaki approved these changes
Thank you for update 👍

2020-11-05 22:50 UTC, merged

2020-11-05 22:51 UTC, tiangolo commented
Awesome, thank you @Attsun1031 ! :cake: :tada: 

And thanks for the reviews @komtaki and @tokusumi :bow: :coffee: