Add Japanese translation for Advanced - custom-response
fastapi/fastapi pull request #2193
Opened 2020-10-18 08:02 UTC by Attsun1031

This PR translates the advanced/custom-response.md to Japanese.

2020-10-29 15:13 UTC, tokusumi requested changes
Thank you for translation!

2020-10-29 15:13 UTC, tokusumi commented on docs/ja/docs/advanced/custom-response.md
> +使いたい `Response` クラス (サブクラス)　をインポートし、 *path operationデコレータ* に宣言します。
```suggestion
使いたい `Response` クラス (サブクラス) をインポートし、 *path operationデコレータ* に宣言します。
```

2020-10-29 15:13 UTC, tokusumi commented on docs/ja/docs/advanced/custom-response.md
> +[Return a Response directly](response-directly.md){.internal-link target=_blank}で見たように、レスポンスを直接返すことで、*path operation* の中でレスポンスをオーバーライドできます。
```suggestion
[レスポンスを直接返す](response-directly.md){.internal-link target=_blank}で見たように、レスポンスを直接返すことで、*path operation* の中でレスポンスをオーバーライドできます。
```

2020-10-29 15:13 UTC, tokusumi commented on docs/ja/docs/advanced/custom-response.md
> +`Response` を使って他の何かを返すこともできますし、カスタムのサブクラスを作ることもできることを覚えておいてください。
```suggestion
`Response` を使って他の何かを返せますし、カスタムのサブクラスも作れることを覚えておいてください。
```
簡潔に

2020-10-29 15:13 UTC, tokusumi commented on docs/ja/docs/advanced/custom-response.md
> +    **FastAPI** は開発者の利便性のために `starlette.responses` を `fastapi.responses` と同じものとして提供しています。しかし、利用可能なレスポンスのほとんどはStarletteから直接提供されます。
```suggestion
    **FastAPI** は開発者の利便性のために `fastapi.responses` として `starlette.responses` と同じものを提供しています。しかし、利用可能なレスポンスのほとんどはStarletteから直接提供されます。
```

2020-10-29 15:13 UTC, tokusumi commented on docs/ja/docs/advanced/custom-response.md
> +## 追加のドキュメント
```suggestion
## その他のドキュメント
```
additionalの訳は難しいので無理やり意訳したほうが違和感がないと思います。

2020-10-30 01:26 UTC, Attsun1031 commented
@tokusumi Thank you for your careful review ! I fixed everything, so please review again.

2020-10-30 03:11 UTC, tokusumi approved these changes
Thank you for update!

2020-11-03 04:56 UTC, komtaki reviewed
Thank you for your tough work. 👏 

I suggested a few change to improve.

2020-11-03 04:56 UTC, komtaki commented on docs/ja/docs/advanced/custom-response.md
> +    メディアタイプを指定せずにレスポンスクラスを利用すると、FastAPIは何もコンテンツがないことを期待するので、生成されるOpenAPIドキュメントにレスポンスフォーマットが記載されません。
```suggestion
    メディアタイプを指定せずにレスポンスクラスを利用すると、FastAPIは何もコンテンツがないことを期待します。そのため、生成されるOpenAPIドキュメントにレスポンスフォーマットが記載されません。
```

This is a long sentence, so separating the two sentences will make it easier to read.

2020-11-03 04:56 UTC, komtaki commented on docs/ja/docs/advanced/custom-response.md
> +    パラメータ `response_class` は、レスポンスの「メディアタイプ」を定義するために利用することもできます。
```suggestion
    パラメータ `response_class` は、レスポンスの「メディアタイプ」を定義するために利用されます。
```

More simple. And the original sentence doesn't seem to emphasize that you can do that much.

2020-11-03 04:56 UTC, komtaki commented on docs/ja/docs/advanced/custom-response.md
> +    そして、OpenAPIにはそのようにドキュメントされます。
```suggestion
    そして、OpenAPIにはそのようにドキュメント化されます。
```

This is more natural.

2020-11-03 04:56 UTC, komtaki commented on docs/ja/docs/advanced/custom-response.md
> +関数の中でレスポンスをオーバーライドしつつも、OpenAPI に「メディアタイプ」をドキュメントしたいなら、 `response_class` パラメータを使い、 `Response` オブジェクトを返します。
```suggestion
関数の中でレスポンスをオーバーライドしつつも、OpenAPI に「メディアタイプ」をドキュメント化したいなら、 `response_class` パラメータを使い、 `Response` オブジェクトを返します。
```

2020-11-03 04:56 UTC, komtaki commented on docs/ja/docs/advanced/custom-response.md
> +しかし、一方では `response_class` に `HTMLResponse` を渡しているため、 **FastAPI** はOpenAPIや対話的ドキュメントでHTMLとして `text/html` でドキュメントする方法を知っています。
```suggestion
しかし、一方では `response_class` に `HTMLResponse` を渡しているため、 **FastAPI** はOpenAPIや対話的ドキュメントでHTMLとして `text/html` でドキュメント化する方法を知っています。
```

2020-11-03 04:56 UTC, komtaki commented on docs/ja/docs/advanced/custom-response.md
> +    `ujson` は、いくつかのエッジケースの取り扱いについて、Pythonにビルトインされた実装よりも注意深くありません。
```suggestion
    `ujson` は、いくつかのエッジケースの取り扱いについて、Pythonにビルトインされた実装よりも作りこまれていません。
```

It's hard to say, but this might be more close to original.

2020-11-03 04:56 UTC, komtaki commented on docs/ja/docs/advanced/custom-response.md
> +    前に見たように、依然として *path operation* の中で `response_class` をオーバーライドできます。
```suggestion
    前に見たように、 *path operation* の中で `response_class` をオーバーライドできます。
```

2020-11-04 02:52 UTC, Attsun1031 commented
@komtaki Thank you for your careful review ! I fixed everything, so please check again.

2020-11-04 12:19 UTC, komtaki approved these changes
Thank you for update 👍

2020-11-25 17:27 UTC, tiangolo commented
Awesome! Thanks @Attsun1031 :bow: :rocket: 

And thank you @komtaki and @tokusumi for the reviews :nerd_face: :coffee:

2020-11-25 17:47 UTC, merged