Add chinese translate for tutorial-middleware
fastapi/fastapi pull request #2334
Opened 2020-11-10 06:41 UTC by lpdswing

2020-11-10 07:03 UTC, lpdswing commented
@tiangolo  I don't know why occured this error when build doc .
![image](https://user-images.githubusercontent.com/20874036/98640888-cf35a300-2365-11eb-97aa-123739533422.png)

2020-11-10 19:56 UTC, tiangolo commented
Hey @lpdswing ! Thanks for letting me know.

The error had nothing to do with you, it was caused by a recent change I made when I enabled the new features of [Material for MkDocs Insiders](https://squidfunk.github.io/mkdocs-material/insiders/), but I incorrectly handled the install in PRs from forks.

I just fixed it and updated your branch, so it's now passing and ready for review :tada:

2020-11-11 00:23 UTC, lpdswing commented
OK,thx发自我的华为手机-------- 原始邮件 --------发件人： Sebastián Ramírez <notifications@github.com>日期： 2020年11月11日周三 凌晨3:56收件人： tiangolo/fastapi <fastapi@noreply.github.com>抄送： lpdswing <lpdswing@qq.com>, Mention <mention@noreply.github.com>主    题： Re: [tiangolo/fastapi] Add chinese translate for tutorial-middleware (#2334)

Hey @lpdswing ! Thanks for letting me know.

The error had nothing to do with you, it was caused by a recent change I made when I enabled the new features of Material for MkDocs Insiders, but I incorrectly handled the install in PRs from forks.

I just fixed it and updated your branch, so it's now passing and ready for review 🎉



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

2020-11-11 10:26 UTC, waynerv requested changes

2020-11-11 10:26 UTC, waynerv commented on docs/zh/docs/tutorial/middleware.md
> +"middleware"是一个函数,它在处理每个特定*路径操作*的**request**前工作,并且在每个**response**返回之前工作.
「中间件」是一个函数，它在每个**请求**被特定的*路径操作*处理之前以及每个**响应**被返回之前工作.

2020-11-11 10:26 UTC, waynerv commented on docs/zh/docs/tutorial/middleware.md
> +* 它接收你的应用程序的每一个**request**.
`request` and `response` should be translated.

2020-11-11 10:26 UTC, waynerv commented on docs/zh/docs/tutorial/middleware.md
> +* 然后它将**request**传递给应用程序的其他部分 (通过某种*路径操作*).
然后它将**请求**传递给应用程序的其他部分（某个*路径操作*）进行处理。

2020-11-11 10:26 UTC, waynerv commented on docs/zh/docs/tutorial/middleware.md
> +* 然后它获取应用程序生产的**response** (通过某种*路径操作*).
然后它获取应用程序（某个*路径操作*）生成的**响应** 。

2020-11-11 10:26 UTC, waynerv commented on docs/zh/docs/tutorial/middleware.md
> +    如果你依赖了 `yield`, 退出代码将在执行中间件*后*执行.
如果你有使用了 `yield` 关键字的依赖，依赖中的退出代码将在执行中间件*之后*执行。

2020-11-11 10:26 UTC, waynerv commented on docs/zh/docs/tutorial/middleware.md
> +    **FastAPI** 为开发者提供了方便. 但是你也可以直接使用Starlette.
**FastAPI** 出于方便开发者的原因提供了该对象，但其实它直接来自于 Starlette。

2020-11-11 10:26 UTC, waynerv commented on docs/zh/docs/tutorial/middleware.md
> +你可以稍后再 [Advanced User Guide: Advanced Middleware](../advanced/middleware.md){.internal-link target=_blank}阅读更过关于中间件的教程.
你可以稍后在 [Advanced User Guide: Advanced Middleware](../advanced/middleware.md){.internal-link target=_blank}阅读更多关于中间件的教程。

2020-11-24 09:55 UTC, RunningIkkyu requested changes

2020-11-24 09:55 UTC, RunningIkkyu commented on docs/zh/docs/tutorial/middleware.md
> +中间件参数接收:
中间件函数接收如下参数：

2020-11-24 09:55 UTC, RunningIkkyu commented on docs/zh/docs/tutorial/middleware.md
> +    如果你使用了 `yield`关键字依赖, 依赖中的退出代码将在执行中间件*后*执行.
Leave a space after `yield`.

2020-11-24 09:55 UTC, RunningIkkyu commented on docs/zh/docs/tutorial/middleware.md
> +    * 这个函数将 `request` 传递个相应的 *路径操作*.
传递给

2020-11-24 09:55 UTC, RunningIkkyu commented on docs/zh/docs/tutorial/middleware.md
> +    **FastAPI** 为了开发者方便提供了该对象. 但其实它直接来自于Starlette.
Leave a space before `Starlette`.

2020-11-24 09:55 UTC, RunningIkkyu commented on docs/zh/docs/tutorial/middleware.md
> +    但是如果你想让浏览器中的客户端看到你的自定义请求头, 你需要把它们加到 CORS 配置 ([CORS (Cross-Origin Resource Sharing)](cors.md){.internal-link target=_blank}) 的 `expose_headers` 参数中,在 <a href="https://www.starlette.io/middleware/#
Leave spaces for `Starlette's CORS docs`.

2020-11-24 09:55 UTC, RunningIkkyu commented on docs/zh/docs/tutorial/middleware.md
> +在任何*路径操作*收到`request`前,可以添加要和请求一起运行的代码.
Wrap enlish words with a space.

2020-11-24 10:25 UTC, lpdswing commented on docs/zh/docs/tutorial/middleware.md
> +    如果你使用了 `yield`关键字依赖, 依赖中的退出代码将在执行中间件*后*执行.
删除空格?

2020-11-25 01:47 UTC, lpdswing commented on docs/zh/docs/tutorial/middleware.md
> +    * 这个函数将 `request` 传递个相应的 *路径操作*.
thx

2020-11-25 03:26 UTC, RunningIkkyu commented on docs/zh/docs/tutorial/middleware.md
> +    如果你使用了 `yield`关键字依赖, 依赖中的退出代码将在执行中间件*后*执行.
`yield` 后面加个空格

2020-11-25 03:28 UTC, RunningIkkyu approved these changes

2020-11-25 03:39 UTC, waynerv requested changes
You should also translate all the punctuation marks.

2020-11-25 03:39 UTC, waynerv commented on docs/zh/docs/tutorial/middleware.md
> +你可以稍后再 [Advanced User Guide: Advanced Middleware](../advanced/middleware.md){.internal-link target=_blank}阅读更多关于中间件的教程.
再 -> 在

2020-11-25 03:39 UTC, waynerv commented on docs/zh/docs/tutorial/middleware.md
> +例如你可以添加自定义请求头 `X-Process-Time` 包含以秒为单位的接收请求和生成相应的时间:
相应 -> 响应

2020-11-25 03:59 UTC, maoyibo approved these changes

2020-11-25 17:31 UTC, tiangolo commented
Awesome! Thank you @lpdswing for your contribution! :cake: :rocket: 

And thanks @waynerv, @RunningIkkyu, and @maoyibo for the reviews :bow: :coffee: 

---

I'm going to wait for the punctuation fixes and then the approval by @waynerv before merging :nerd_face: :memo:

2021-03-19 09:16 UTC, waynerv approved these changes
@tiangolo I think this PR is ready for merging.

2021-03-27 17:25 UTC, tiangolo commented
Excellent, thanks for the confirmation @waynerv ! :rocket:

2021-03-27 17:25 UTC, merged