Add `Generic types` Fix `Optional`
fastapi/fastapi pull request #2360
Opened 2020-11-17 06:17 UTC by maoyibo

Add `Generic types with type parameters` and `Generic types`, Fix the code file name of `Optional` and subsequent chapters.

2020-11-17 06:43 UTC, waynerv requested changes

2020-11-17 06:43 UTC, waynerv commented on docs/zh/docs/python-types.md
> +你也可以使用 `Optional` 来声明一个变量有一个类型，比如 `str`, 但是它是 "optional", 这意味着它也可以是 `None`:
但是它是 "optional" --》但是它是「可选的」

2020-11-17 06:43 UTC, waynerv commented on docs/zh/docs/python-types.md
> +* ...and others.
...及其他。

2020-11-17 13:02 UTC, waynerv approved these changes

2020-12-01 02:11 UTC, maoyibo commented on docs/zh/docs/python-types.md
> +你也可以使用 `Optional` 来声明一个变量有一个类型，比如 `str`, 但是它是 "optional", 这意味着它也可以是 `None`:
Fixed, Thanks.

2020-12-01 02:11 UTC, maoyibo commented on docs/zh/docs/python-types.md
> +* ...and others.
Fixed, Thanks.

2021-01-13 03:10 UTC, waynerv approved these changes

2024-01-12 14:45 UTC, tiangolo commented
Hum, as the branch was removed, I can't update this PR to see if there are any new changes, so I'll have to close it and wait for some new PR with the same (or other) changes. 😅

2024-01-12 14:45 UTC, closed without merging