Chinese translation add tutorial/sql-databases
fastapi/fastapi pull request #2408
Opened 2020-11-25 02:23 UTC by maoyibo

Chinese translation add tutorial/sql-databases

2020-12-18 10:14 UTC, blt232018 requested changes

2020-12-18 10:14 UTC, blt232018 commented on docs/zh/docs/tutorial/sql-databases.md
> +ORM拥有将代码中的 *objects* 和数据库表("*relations*")之间进行转换的工具。
因为发现排版问题较多，建议检查如下排版问题：
1. 中英文之间加空格
2. 部分标点未使用全角标点（中文标点）
3. 双引号换直角引号
4. 部分英文未翻译

2020-12-18 16:30 UTC, k1jason2082 approved these changes

2023-06-26 17:34 UTC, tiangolo commented
It seems this was translated in another PR, so I'll close this one here, but thanks! ☕

2023-06-26 17:34 UTC, closed without merging