Chinese translation add tutorial/extra-data-types
fastapi/fastapi pull request #2410
Opened 2020-11-25 02:32 UTC by maoyibo

Chinese translation add tutorial/extra-data-types

2020-11-25 12:55 UTC, waynerv requested changes

2020-11-25 12:55 UTC, waynerv commented on docs/zh/docs/tutorial/extra-data-types.md
> +And you will still have the same features as seen up to now:
This line should be deleted.

2020-11-25 12:55 UTC, waynerv commented on docs/zh/docs/tutorial/extra-data-types.md
> +    * A Python `datetime.time`.
Untranslated “A”

2020-11-25 12:55 UTC, waynerv commented on docs/zh/docs/tutorial/extra-data-types.md
> +    * A Python `datetime.timedelta`.
Untranslated “A”

2020-11-26 00:36 UTC, maoyibo commented on docs/zh/docs/tutorial/extra-data-types.md
> +And you will still have the same features as seen up to now:
Fixed, thanks.

2020-11-26 00:36 UTC, maoyibo commented on docs/zh/docs/tutorial/extra-data-types.md
> +    * A Python `datetime.time`.
Fixed, thanks.

2020-11-26 00:36 UTC, maoyibo commented on docs/zh/docs/tutorial/extra-data-types.md
> +    * A Python `datetime.timedelta`.
Fixed, thanks.

2020-11-27 10:43 UTC, waynerv approved these changes

2020-11-27 10:43 UTC, waynerv commented on docs/zh/docs/tutorial/extra-data-types.md
> +注意，函数内的参数有其天然的数据类型，你可以，例如，执行正常的日期操作，如:
natural -》 原生 Would be better to understand?

2020-11-30 01:02 UTC, maoyibo commented on docs/zh/docs/tutorial/extra-data-types.md
> +注意，函数内的参数有其天然的数据类型，你可以，例如，执行正常的日期操作，如:
Yes, "原生" is more appropriate, fixed, Thanks.

2020-11-30 02:59 UTC, waynerv approved these changes

2021-01-14 02:23 UTC, Laineyzhang55 approved these changes

2021-02-07 17:51 UTC, tiangolo commented
Thanks for your contribution @maoyibo ! :cake: :nerd_face: 

And thanks @waynerv and @Laineyzhang55 for your reviews. :bow: :rocket:

2021-02-07 17:52 UTC, merged