Chinese translation add tutorial/header-params
fastapi/fastapi pull request #2412
Opened 2020-11-25 02:48 UTC by maoyibo

Chinese translation add tutorial/header-params

2020-11-27 10:48 UTC, waynerv requested changes

2020-11-27 10:48 UTC, waynerv commented on docs/zh/docs/tutorial/header-params.md
> +然后使用和`Path`, `Query` and `Cookie` 一样的结构定义header 参
missing words.

2020-11-27 10:48 UTC, waynerv commented on docs/zh/docs/tutorial/header-params.md
> +    `Header` 是 `Path`, `Query` 和 `Cookie` 的兄弟类型。她也继承自通用的 `Param` 类.
她 -> 它

2020-11-30 01:09 UTC, maoyibo commented on docs/zh/docs/tutorial/header-params.md
> +    `Header` 是 `Path`, `Query` 和 `Cookie` 的兄弟类型。她也继承自通用的 `Param` 类.
Fixed Thanks.

2020-11-30 01:09 UTC, maoyibo commented on docs/zh/docs/tutorial/header-params.md
> +然后使用和`Path`, `Query` and `Cookie` 一样的结构定义header 参
Fixed, thanks.

2020-11-30 03:01 UTC, waynerv approved these changes

2021-01-14 02:24 UTC, Laineyzhang55 approved these changes

2021-02-07 17:54 UTC, tiangolo commented
Awesome! Thanks a lot @maoyibo ! :rocket: :coffee: 

And tdhanks @waynerv and @Laineyzhang55 for your reviews! :nerd_face: :mag:

2021-02-07 17:59 UTC, merged