🌐 Add Chinese translation for Tutorial - Request Forms and Files
fastapi/fastapi pull request #2422
Opened 2020-11-26 07:18 UTC by maoyibo

@waynerv and many other friends Please take a look.

2020-12-02 05:42 UTC, waynerv approved these changes
LGTM.

2021-05-17 02:14 UTC, jaystone776 commented on docs/zh/docs/tutorial/request-forms-and-files.md
> +使用和`Body` 或 `Query`类似的方法创建文件和表单参数：
创建文件和表单参数的方式与 `Body` 和 `Query` 一样：

2021-05-17 02:14 UTC, jaystone776 commented on docs/zh/docs/tutorial/request-forms-and-files.md
> +文件和表单字段将作为表单数据上传，您将收到文件和表单字段。
上传、接收文件与表单字段必须以表单数据的形式。

2021-05-17 02:14 UTC, jaystone776 commented on docs/zh/docs/tutorial/request-forms-and-files.md
> +你可以声明一些文件为 `bytes` 一些文件为`UploadFile`。
可以用 `bytes` 或 `UploadFile` 声明文件。

2021-05-17 02:14 UTC, jaystone776 commented on docs/zh/docs/tutorial/request-forms-and-files.md
> +    你可以在 *路径操作*  中定义多个 `File` 和 `Form` 参数，但你不能同时定义 `Body` 字段并期望以JSON的格式获得数据， 因为请求体将会使用 `multipart/form-data` 编码，而不是`application/json`。
可在 *路径操作* 中声明多个 `File` 与 `Form` 参数，但不能同时声明要接收 JSON 的  `Body` 字段。因为，此时请求体的编码为 `multipart/form-data`，不是 `application/json`。

2021-05-17 02:14 UTC, jaystone776 commented on docs/zh/docs/tutorial/request-forms-and-files.md
> +    这不是**FastAPI**的限制，它是HTTP协议的一部分。
这不是 **FastAPI** 的局限，而是 HTTP 协议的规定。

2021-05-17 02:14 UTC, jaystone776 commented on docs/zh/docs/tutorial/request-forms-and-files.md
> +## 回顾
## 小结

2021-05-17 02:14 UTC, jaystone776 commented on docs/zh/docs/tutorial/request-forms-and-files.md
> +当你需要在同一个请求中接收数据和文件时，请同时使用 `File` 和 `Form` 。
在同一个请求中接收数据和文件时，应同时使用 `File` 和 `Form` 。

2021-05-17 02:16 UTC, jaystone776 requested changes
Translations changed

2023-06-26 17:32 UTC, tiangolo commented
It seems this was translated in another PR, so I'll close this one, but thanks! 🍰

2023-06-26 17:32 UTC, closed without merging