🌐 Add Chinese translation for Tutorial - Global Dependencies
fastapi/fastapi pull request #2440
Opened 2020-11-30 06:00 UTC by maoyibo

🌐 Add Chinese translation for Tutorial - Global Dependencies

2020-12-04 04:37 UTC, blt232018 commented
这一章节是 0.62.0 版本新增内容，在之前的版本中不生效。所以添加一个版本提示可能更好

2020-12-14 01:55 UTC, maoyibo commented
> 
> 
> 这一章节是 0.62.0 版本新增内容，在之前的版本中不生效。所以添加一个版本提示可能更好

Hi blt232018，我翻译时已经注意到这是一个新增内容，但是官方文档中并没有相关版本提示的内容，因此并未添加，你可以再review 的时候在你认为合适的地方添加comment。

2020-12-22 05:40 UTC, blt232018 requested changes
@tiangolo may we make a note here to tell people that "your version of FastAPI must be greater than 0.61”？

2020-12-22 05:40 UTC, blt232018 commented on docs/zh/docs/tutorial/dependencies/global-dependencies.md
> +类似于您可以 [增加 `依赖项` 到 *路径操作装饰器*](dependencies-in-path-operation-decorators.md){.internal-link target=_blank}, 您可以将他们添加到 `FastAPI` 应用程序中。
```suggestion
类似于 [增加 `依赖项` 到*路径操作装饰器*](dependencies-in-path-operation-decorators.md){.internal-link target=_blank}，您可以将他们添加到 `FastAPI` 应用程序中。
```

2020-12-22 05:40 UTC, blt232018 commented on docs/zh/docs/tutorial/dependencies/global-dependencies.md
> +在这种情况下，它们将应用于应用程序中所有的*路径操作*:
```suggestion
在这种情况下，它们将应用于应用程序中所有的*路径操作*：
```

2020-12-22 05:40 UTC, blt232018 commented on docs/zh/docs/tutorial/dependencies/global-dependencies.md
> +所有关于 [增加 `依赖项` 到 *路径操作装饰器*](dependencies-in-path-operation-decorators.md){.internal-link target=_blank} 一章中的点子仍然适用， 但在本例中，适用于应用程序中的所有 *路径操作*。
```suggestion
所有关于 [增加 `依赖项` 到*路径操作装饰器*](dependencies-in-path-operation-decorators.md){.internal-link target=_blank} 一章中的点子仍然适用，但在本例中，适用于应用程序中的所有*路径操作*。
```

2020-12-22 05:40 UTC, blt232018 commented on docs/zh/docs/tutorial/dependencies/global-dependencies.md
> +## *路径操作* 组的依赖关系
```suggestion
## 一组*路径操作*的依赖项
```

2020-12-22 05:40 UTC, blt232018 commented on docs/zh/docs/tutorial/dependencies/global-dependencies.md
> +稍后，当您阅读如何构造大型应用程序 ([大型应用程序-多个文件](../../tutorial/bigger-applications.md){.internal-link target=_blank})时, 可能包含多个文件，您将了解如何为一组 *路径操作* 声明单个的 `依赖项` 参数。
```suggestion
在之后，当您阅读如何构造可能包含多个文件的大型应用程序 ([大型应用程序-多个文件](../../tutorial/bigger-applications.md){.internal-link target=_blank})时，您将了解如何为一组*路径操作*声明单个 `依赖项` 参数。
```

2023-06-26 22:05 UTC, tiangolo commented
It seems this was translated at some point in another PR. So I'll close this one, but thanks for the effort! ☕

2023-06-26 22:05 UTC, closed without merging