Add Chinese translation for Tutorial - Bigger Applications - Multiple Files
fastapi/fastapi pull request #2453
Opened 2020-12-01 09:58 UTC by waynerv

2020-12-18 02:06 UTC, Laineyzhang55 approved these changes

2020-12-20 16:33 UTC, blt232018 requested changes

2020-12-20 16:33 UTC, blt232018 commented on docs/zh/docs/tutorial/bigger-applications.md
> +我们还可以直接将*路径操作*添加到 FastAPI 应用中。
```suggestion
我们还可以直接将*路径操作*添加到 `FastAPI` 应用中。
```

2021-01-13 03:07 UTC, yanever approved these changes

2021-02-07 17:58 UTC, tiangolo commented
Thanks @waynerv! :clap: :clap: :rocket: 

And thanks for the reviews @yanever , @blt232018 , and @Laineyzhang55 :coffee: :cake:

2021-02-07 18:02 UTC, merged