🌐 Add Chinese translation for Tutorial - Background Tasks
fastapi/fastapi pull request #2464
Opened 2020-12-03 08:05 UTC by maoyibo

🌐 Add Chinese translation for Tutorial - Background Tasks

2020-12-21 17:23 UTC, blt232018 requested changes

2020-12-21 17:23 UTC, blt232018 commented on docs/zh/docs/tutorial/background-tasks.md
> +通过只使用 `BackgroundTasks` (而不是 `BackgroundTask` )，然后就可以使用它作为 *路径操作函数* 参数，并让 **FastAPI** 为您处理其余的，就像直接使用 `Request` 对象一样。
```suggestion
仅通过使用 `BackgroundTasks`（并不是 `BackgroundTask`），然后就可以把它作为*路径操作函数*参数使用，并让 **FastAPI** 为您处理其余操作，就像直接使用 `Request` 对象时一样。
```

2020-12-21 17:23 UTC, blt232018 commented on docs/zh/docs/tutorial/background-tasks.md
> +在 FastAPI 中仍然可以单独使用 `BackgroundTask` ，但你必须在代码中创建 `BackgroundTask` 对象并返回一个包含它的Starlette `Response` 。
```suggestion
在 FastAPI 中仍然可以单独使用 `BackgroundTask`，但你必须在代码中创建 `BackgroundTask` 对象并返回一个包含它的 Starlette `Response`。
```

2020-12-21 17:23 UTC, blt232018 commented on docs/zh/docs/tutorial/background-tasks.md
> +你可以在<a href="https://www.starlette.io/background/" class="external-link" target="_blank">Starlette后台任务的官方文档</a>中看到更多细节。
```suggestion
你可以在 <a href="https://www.starlette.io/background/" class="external-link" target="_blank">Starlette 后台任务的官方文档</a>中看到更多细节。
```

2020-12-21 17:23 UTC, blt232018 commented on docs/zh/docs/tutorial/background-tasks.md
> +如果你需要执行较重的后台计算，且不一定需要由相同的进程执行(例如,你不需要共享内存变量,等等)，你可能会受益于使用其他更大的工具,像<a href="https://docs.celeryproject.org" class="external-link" target="_blank">Celery</a>。
```suggestion
如果你需要执行繁重的后台计算，且不一定需要由同一进程执行（例如，你不需要共享内存、变量等），你可能会受益于使用其他更大型的工具，例如 <a href="https://docs.celeryproject.org" class="external-link" target="_blank">Celery</a>。
```

2020-12-21 17:23 UTC, blt232018 commented on docs/zh/docs/tutorial/background-tasks.md
> +它们往往需要更复杂的配置，一个消息/任务队列管理器，如 RabbitMQ 或 Redis ，但它们允许你在多个进程中运行后台任务，特别是在多个服务器中。
```suggestion
它们往往需要更复杂的配置，一个消息/任务队列管理器，如 RabbitMQ 或 Redis，但它们允许你在多个进程中运行后台任务，特别是在多个服务器中。
```

2020-12-21 17:23 UTC, blt232018 commented on docs/zh/docs/tutorial/background-tasks.md
> +要查看示例，请检查[Project Generators](../project-generation.md){.internal-link target=_blank}，它们都包含已经配置好的Celery。
```suggestion
要查看示例，请检查 [Project Generators](../project-generation.md){.internal-link target=_blank}，它们都包含已经配置好的 Celery。
```

2020-12-21 17:23 UTC, blt232018 commented on docs/zh/docs/tutorial/background-tasks.md
> +但是如果你需要从相同的 FastAPI 应用中访问变量和对象，或者你需要执行小的后台任务(比如发送邮件通知)，你可以简单地使用 `BackgroundTasks` 。
```suggestion
但是如果你需要在同一个 FastAPI 应用中访问变量和对象，或者需要执行小型的后台任务（比如发送邮件通知），那就可以简单地使用 `BackgroundTasks`。
```

2020-12-21 17:23 UTC, blt232018 commented on docs/zh/docs/tutorial/background-tasks.md
> +导入，并在 *路径操作函数* 和依赖项的参数中使用 `BackgroundTasks` 来添加后台任务。
```suggestion
导入，并在*路径操作函数*和依赖项的参数中使用 `BackgroundTasks` 来添加后台任务。
```

2023-06-26 17:17 UTC, tiangolo commented
📝 Docs preview for commit 8a138dc7e9861dc7c667b7805b5f02b038d1708b at: https://6499c7e9da96dc0080f3f275--fastapi.netlify.app

2024-01-29 15:25 UTC, tiangolo commented
As this PR had requested changes to be applied but has been inactive for a while, it's now going to be closed. But if there's anyone interested, feel free to create a new PR.

2024-01-29 15:25 UTC, closed without merging