🌐 Add Chinese translation for Tutorial - Static Files
fastapi/fastapi pull request #2465
Opened 2020-12-03 08:24 UTC by maoyibo

🌐 Add Chinese translation for Tutorial - Static Files

2020-12-22 16:36 UTC, blt232018 requested changes

2020-12-22 16:36 UTC, blt232018 commented on docs/zh/docs/tutorial/static-files.md
> +首先需要安装 `aiofiles`:
```suggestion
首先需要安装 `aiofiles`：
```

2020-12-22 16:36 UTC, blt232018 commented on docs/zh/docs/tutorial/static-files.md
> +* 导入 `StaticFiles`.
```suggestion
* 导入 `StaticFiles`。
```

2020-12-22 16:36 UTC, blt232018 commented on docs/zh/docs/tutorial/static-files.md
> +* 在特定路径中 "挂载" StaticFiles()实例。
```suggestion
* 在特定路径中「挂载」`StaticFiles()` 实例。
```

2020-12-22 16:36 UTC, blt232018 commented on docs/zh/docs/tutorial/static-files.md
> +    你也可以使用 `from starlette.staticfiles import StaticFiles`.
```suggestion
    你也可以使用 `from starlette.staticfiles import StaticFiles`。
```

2020-12-22 16:36 UTC, blt232018 commented on docs/zh/docs/tutorial/static-files.md
> +### 什么是 "挂载"
```suggestion
### 什么是「挂载」
```

2020-12-22 16:36 UTC, blt232018 commented on docs/zh/docs/tutorial/static-files.md
> +"挂载" 意味着在特定路径中添加一个完整的 "独立的" 应用程序，然后由它来处理所有的子路径。
```suggestion
「挂载」意味着在特定路径中添加一个完整「独立的」应用程序，然后由它负责处理所有的子路径。
```

2020-12-22 16:36 UTC, blt232018 commented on docs/zh/docs/tutorial/static-files.md
> +这不同于使用 `APIRouter` 作为一个挂载的应用程序是完全独立的。主应用程序的 OpenAPI 和文档不会包含挂载的应用程序中的任何内容，等。
```suggestion
这不同于使用 `APIRouter` 因为一个挂载的应用程序是完全独立的。主应用程序的 OpenAPI 和文档不会包含挂载的应用程序中的任何内容，等。
```

2020-12-22 16:36 UTC, blt232018 commented on docs/zh/docs/tutorial/static-files.md
> +你可以在 **高级用户指南** 中了解更多。
```suggestion
你可以在**高级用户指南**中了解更多相关信息。
```

2020-12-22 16:36 UTC, blt232018 commented on docs/zh/docs/tutorial/static-files.md
> +第一个 `"/static"` 指的是将 "挂载" 此 "子应用程序" 的子路径。因此，任何以 `"/static"` 开头的路径都将由它处理。
```suggestion
第一个 `"/static"` 指的是这个「子应用程序」会被「挂载」到的子路径。因此，任何以 `"/static"` 开头的路径都将由它处理。
```

2020-12-22 16:36 UTC, blt232018 commented on docs/zh/docs/tutorial/static-files.md
> +`name="static"` 给了它一个可以被 **FastAPI** 内部使用的名称。
```suggestion
`name="static"` 给它一个可以被 **FastAPI** 在内部使用的名称。
```

2020-12-22 16:36 UTC, blt232018 commented on docs/zh/docs/tutorial/static-files.md
> +更多细节和选项请检查<a href="https://www.starlette.io/staticfiles/" class="external-link" target="_blank">Starlette 关于静态文件的文档</a>。
```suggestion
更多细节和选项请检查 <a href="https://www.starlette.io/staticfiles/" class="external-link" target="_blank">Starlette 关于静态文件的文档</a>。
```

2023-06-26 17:13 UTC, tiangolo commented
It seems this was translated in another PR, so I'll close this one. But thanks again! ☕

2023-06-26 17:13 UTC, closed without merging