Add Chinese translation for Tutorial - Security - Get Current User
fastapi/fastapi pull request #2474
Opened 2020-12-06 04:38 UTC by waynerv

@RunningIkkyu @maoyibo @yanever Please take a look.

2020-12-15 11:07 UTC, blt232018 requested changes

2020-12-15 11:07 UTC, blt232018 commented on docs/zh/docs/tutorial/security/get-current-user.md
> +所有（或所需的任何部分）的端点都可以利用通过复用这些依赖项或你创建的其他依赖项带来的优势。
这句翻译有点绕口...
```suggestion
所有（或所需的任何部分）的端点，都可以利用这些依赖项或你创建的其他依赖项复用带来的优势。
```

2020-12-15 11:17 UTC, blt232018 commented
@waynerv just some suggestions. Actually it doesn't have any problem! I'll approve it tomorrow in case that you may accept any suggestion of me.

2020-12-16 02:50 UTC, blt232018 approved these changes

2020-12-17 07:05 UTC, waynerv commented on docs/zh/docs/tutorial/security/get-current-user.md
> +首先，让我们来创建一个用户 Pydantic 模型。
这里我特意将原文的顺序做了一些调整以符合中文的阅读习惯，比如我们我们通常会说「用户数据库模型」或「用户JSON模型」，而不会说「数据库用户模型」或「JSON用户模型」。

2020-12-17 07:11 UTC, waynerv commented on docs/zh/docs/tutorial/security/get-current-user.md
> +`get_current_user` 将具有一个我们之前所创建的同一个 `oauth2_scheme` 作为依赖项。
「和某某相同」应该有两个主体，但这里从原文看只有一个主体即`oauth2_scheme`，因此翻译成了同一个

2020-12-17 07:25 UTC, waynerv commented
@blt232018 Thanks for the review!

2020-12-17 13:36 UTC, blt232018 approved these changes

2020-12-18 02:05 UTC, Laineyzhang55 approved these changes

2021-01-09 18:52 UTC, tiangolo commented
Awesome! Thanks a lot @waynerv ! :bow: :cake: 

And thanks @blt232018 and @Laineyzhang55 for the reviews :coffee: :mag:

2021-01-09 18:53 UTC, merged