🌐 Add Korean translation for Tutorial - Body - Fields
fastapi/fastapi pull request #2489
Opened 2020-12-08 09:11 UTC by hard-coders

This PR translates `tutorial/body-fields.md` in Korean.

related: #2017

2020-12-09 02:28 UTC, PandaHun reviewed
🤩 I think it's almost perfect

2020-12-09 02:28 UTC, PandaHun commented on docs/ko/docs/tutorial/body-fields.md
> +모델 어트리뷰트꽈 함께 `Field`를 사용할 수 있습니다:
```suggestion
모델 어트리뷰트와 함께 `Field`를 사용할 수 있습니다:
```

2020-12-18 03:59 UTC, PandaHun approved these changes

2021-11-03 09:04 UTC, 0417taehyun requested changes
Bit appreciate your works 🚀 

Can you change the word `동작` as `작동`? It was describe in #3167 .

Also for solving conflicts, please update this file to latest version.

2021-11-03 09:04 UTC, 0417taehyun commented on docs/ko/docs/tutorial/body-fields.md
> +`Query`,`Path` 및`Body`를 사용하여 *경로 동작 함수* 매개변수에서 추가 검증 및 메타데이터를 선언할 수있는 것과 마찬가지로, Pydantic의 `Field`를 사용하여 Pydantic 모델 내부에서 검증 및 메타데이터를 선언할 수 있습니다.
```suggestion
`Query`,`Path` 및`Body`를 사용하여 *경로 작동 함수* 매개변수에서 추가 검증 및 메타데이터를 선언할 수있는 것과 마찬가지로, Pydantic의 `Field`를 사용하여 Pydantic 모델 내부에서 검증 및 메타데이터를 선언할 수 있습니다.
```

2021-11-03 09:04 UTC, 0417taehyun commented on docs/ko/docs/tutorial/body-fields.md
> +    타입, 기본값, 그리고 `Field`를 갖는 각 모델의 어트리뷰트가 `Field` 대신 `Path`, `Query` 및 `Body`를 사용하여 *경로 동작 함수* 매개변수와 어떻게 동일한 구조를 갖는지 알아두세요.
```suggestion
    타입, 기본값, 그리고 `Field`를 갖는 각 모델의 어트리뷰트가 `Field` 대신 `Path`, `Query` 및 `Body`를 사용하여 *경로 작동 함수* 매개변수와 어떻게 동일한 구조를 갖는지 알아두세요.
```

2023-06-26 19:11 UTC, tiangolo commented
📝 Docs preview for commit b86af2569284533cf9948709edf24f6593acb0d2 at: https://6499e2bcf8ac9505d35fb644--fastapi.netlify.app

2024-01-15 15:48 UTC, closed without merging