🌐 Add Korean translation for Tutorial - Cookie Parameters
fastapi/fastapi pull request #2545
Opened 2020-12-20 08:01 UTC by hard-coders

This PR translates `tutorial/cookie-params.md` in Korean.

related: #2017

2021-02-20 01:21 UTC, PandaHun approved these changes
It's perfect done

2021-11-03 08:59 UTC, 0417taehyun requested changes
Bit appreciate of your works 🚀 

For solving some conflicts, can you update this file to latest version?

Feel free to check my reviews, it is just a SIMPLE thing.

2021-11-03 08:59 UTC, 0417taehyun commented on docs/ko/docs/tutorial/cookie-params.md
> +!!! note "기술 세부사항"
```suggestion
!!! note "기술적 세부사항"
```

Check [파이썬 공식 한국어 문서에 없는 용어 중 현재 사용하고 있는 용어
](https://github.com/tiangolo/fastapi/discussions/3167#discussioncomment-721448)

2023-06-26 19:11 UTC, tiangolo commented
📝 Docs preview for commit d049d590e1033374f54d0f2b62824f0f086a16be at: https://6499e2be5f77290548b8a60d--fastapi.netlify.app

2024-01-15 15:49 UTC, tiangolo commented
As this PR had requested changes to be applied but has been inactive for a while, it's now going to be closed. But if there's anyone interested, feel free to create a new PR.

2024-01-15 15:49 UTC, closed without merging