🌐 Add Japanese translation for Advanced - Conditional OpenAPI
fastapi/fastapi pull request #2631
Opened 2021-01-11 17:00 UTC by sh0nk

This PR translates advanced/conditional-openapi.md in Japanese.

This is my first PR to FastAPI docs by referring to https://fastapi.tiangolo.com/contributing/#existing-language . If I do any mistake, please let me know!

Also, I found [this comment](https://github.com/tiangolo/fastapi/issues/1572#issuecomment-694344684) in an issue. Let me try to review the open PRs for Japanese translation since a lot of parts are already done but not reviewed in progress.

2021-01-15 17:13 UTC, tokusumi requested changes
Thank you for translation, great work!
I propose some improvements (and alternative).

2021-01-16 06:19 UTC, sh0nk commented on docs/ja/docs/advanced/conditional-openapi.md
> +以下と全く同じPydanticの設定で、簡単にあなたが生成するOpenAPIとドキュメントUIを構成することができます。
I initially thought it's the same as the snippet below, but actually between the API and docs UI. Thanks for pointing out!

2021-01-16 06:21 UTC, sh0nk commented on docs/ja/docs/advanced/conditional-openapi.md
> +## セキュリティとAPI、ドキュメントについて
Just changed to "## セキュリティとAPI、およびドキュメントについて" since I think "AとBとC" is a bit hard to read. Please let me know if it does not follow your suggestion.

2021-01-16 06:22 UTC, sh0nk commented
@tokusumi Thank you for your quick review. Updated!

2021-01-16 07:36 UTC, tokusumi approved these changes

2021-01-16 07:37 UTC, tokusumi commented
LGTM👍

2022-04-04 16:45 UTC, wakabame reviewed
Excellent work!!

I propose that "conditional _noun_" would be translated as "条件付き _noun_". Since;
* In mathematical term, "conditional probability" and "conditional expectation" are translated as "条件付き確率" and "条件付き期待値", respectively.
* In azure doc ([en](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/concept-conditional-access-users-groups), [ja](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/active-directory/conditional-access/howto-conditional-access-policy-all-users-mfa.md)),  "conditional access" is translated as "条件付きアクセス".

and I leave some improvements. Please take them if you feel they make this article better!

2022-04-04 16:45 UTC, wakabame commented on docs/ja/docs/advanced/conditional-openapi.md
> +必要であれば、設定と環境変数を利用して、OpenAPIを環境に応じて構成することが可能です。また、完全にOpenAPIを無効にすることもできます。
"configure OpenAPI conditionally"
```suggestion
必要であれば、設定と環境変数を利用することで環境に応じた OpenAPI を条件付きで構成できます。また、完全にOpenAPIを無効にすることもできます。
```

2022-04-05 03:16 UTC, sh0nk commented
@wakabame 
Thanks for your suggestion. Yeah, thought that not all people are super familiar with "条件付き" representation initially, but the reference of Azure convinced me enough to follow.

All points makes sense enough and fixed all! could you check again?

2022-04-05 03:59 UTC, wakabame approved these changes
@sh0nk 
LGTM!

Thank you for your quick action!!

2022-05-09 18:29 UTC, tiangolo commented
Great, thank you @sh0nk! :cake: 

And thanks for the reviews @wakabame and @tokusumi ! :cookie:

2022-05-09 23:54 UTC, merged