🌐 Add Japanese translation for Tutorial - Security - Get Current User
fastapi/fastapi pull request #2681
Opened 2021-01-20 18:03 UTC by sh0nk

Relates to #1572 

This translates `tutorial/security/get-current-user.md` into Japanese.

I'll continue to try to work on the other docs in `tutorial/security/` directory.

2021-07-13 15:32 UTC, sattosan commented
The following article has been translated by me. I apologize if you have already worked on it.
https://github.com/tiangolo/fastapi/pull/3526

If you would like to review it, please do.

2021-07-13 15:32 UTC, sattosan commented
@sh0nk 
The following article has been translated by me. I apologize if you have already worked on it.
#3526

If you would like to review it, please do.

2021-07-16 17:14 UTC, tokusumi requested changes
Thank you for your translation!
I commented some feedbacks.

2021-07-16 17:14 UTC, tokusumi commented on docs/ja/docs/tutorial/security/get-current-user.md
> +`get_current_user` への依存を作ってみましょう。
```suggestion
依存関係 `get_current_user` を作ってみましょう。
```
`get_current_user` is the name of "dependency" will be created here.

2021-07-16 17:14 UTC, tokusumi commented on docs/ja/docs/tutorial/security/get-current-user.md
> +依存はサブ依存を持つことができるのを覚えていますか？
```suggestion
依存関係はサブ依存関係を持つことができるのを覚えていますか？
```

2021-07-16 17:14 UTC, tokusumi commented on docs/ja/docs/tutorial/security/get-current-user.md
> +ですので、ここで *path operation* の中で先ほどの `get_current_user` とともに全く同様に `Depends` を利用できます。
```suggestion
ですので、`get_current_user` に対して同様に*path operation* の中で `Depends` を利用できます。
```
Simplified

2021-07-16 17:14 UTC, tokusumi commented on docs/ja/docs/tutorial/security/get-current-user.md
> +こうするのは、その関数の中ですべての入力補完や型チェックを行う際に役に立ちます。
```suggestion
その関数の中ですべての入力補完や型チェックを行う際に役に立ちます。
```
For more natural

2021-07-16 17:14 UTC, tokusumi commented on docs/ja/docs/tutorial/security/get-current-user.md
> +これで、 *path operatio関数* の中で直接現在のユーザーを取得できるようになりました。
```suggestion
これで、 *path operation関数* の中で直接現在のユーザーを取得できるようになりました。
```
typo

2021-07-16 18:19 UTC, sh0nk commented
Thanks for your review @tokusumi !
As all the comments make sense, I've fixed them in https://github.com/tiangolo/fastapi/pull/2681/commits/a5479696dba668eb85d0f82606c4938d20ffb671.

2021-07-17 00:01 UTC, tokusumi approved these changes
thank you for your quick response!
LGTM 🚀

2022-11-15 03:59 UTC, komtaki reviewed
Thank you for your great work. I commented a few suggestion, so please check it. 👍

2022-11-15 03:59 UTC, komtaki commented on docs/ja/docs/tutorial/security/get-current-user.md
> +ボディを宣言するのにPydanticを使用するのと同じやり方で、Pydanticを別のどんなところでも使うことができます:
```suggestion
ボディを宣言するのにPydanticを使用するのと同じやり方で、Pydanticを他のどんなところでも使うことができます:
```

It might be more natural.

2022-11-15 03:59 UTC, komtaki commented on docs/ja/docs/tutorial/security/get-current-user.md
> +実際には、あなたのアプリケーションにはログインするようなユーザーはおらず、単にアクセストークンを持つロボットやボット、別のシステムがありますか？ここでも、全く同じようにすべて機能します。
```suggestion
実際には、あなたのアプリケーションにログインするのはユーザーではなく、アクセストークンだけを持つロボットやボット、別のシステムですか？繰り返しますが、すべて同じように機能します。
```

It might be more easy to read.

2023-06-26 22:19 UTC, tiangolo commented
📝 Docs preview for commit 6887e11cd7cecfcbd82118a16684a207062cf0d3 at: https://649a0ea6cc19e50d9fcacbf2--fastapi.netlify.app

2024-01-28 18:36 UTC, tiangolo commented
Thank you @sh0nk! 🚀 

As @tokusumi is one of the champions of Japanese translations and already approved this, I'm gonna take it. 🤓

2024-01-28 18:36 UTC, merged