🌐 Add Spanish translation of deployment/https.md
fastapi/fastapi pull request #2692
Opened 2021-01-22 20:28 UTC by pedabraham

Hello 👋!,
This Pull Request includes the Spanish translation of **deployment/https.md**

##### This pull request continues with the Spanish translation of #1218

2022-09-23 20:43 UTC, eavv requested changes

2022-09-23 20:43 UTC, eavv commented on docs/es/docs/deployment/https.md
> +    Si estas en un apuro o simplemente no te importa, continua con la siguientes secciones para ver una guía paso a paso para configurar todo con técnicas diferentes.
```suggestion
    Si estás en un apuro o simplemente no te importa, continua con las siguientes secciones para ver una guía paso a paso para configurar todo con técnicas diferentes.
```

2022-09-23 20:43 UTC, eavv commented on docs/es/docs/deployment/https.md
> +    * Esta extensión SNI permite que un servidor particular (con una sola dirección IP) pueda tener varios certificados HTTPS y servir multiples dominios/aplicaciones HTTPS.
```suggestion
    * Esta extensión SNI permite que un servidor particular (con una sola dirección IP) pueda tener varios certificados HTTPS y servir múltiples dominios/aplicaciones HTTPS.
```

2022-09-23 20:43 UTC, eavv commented on docs/es/docs/deployment/https.md
> +    * Para que esto funcione, un solo componente (programa) que este corriendo en el servidor, escuchando en la dirección IP publica, tenga todos los certificados HTTPS en el servidor.
```suggestion
    * Para que esto funcione, un solo componente (programa) que esté corriendo en el servidor, escuchando en la dirección IP pública, tenga todos los certificados HTTPS en el servidor.
```

2022-09-23 20:43 UTC, eavv commented on docs/es/docs/deployment/https.md
> +Es una practica común tener un servidor programa/HTTP corriendo en el servidor (la maquina, el huésped, etc.) y manejando todas las partes de HTTPS: enviando la desencriptada petición HTTP a la aplic
```suggestion
Es una práctica común tener un servidor programa/HTTP corriendo en el servidor (la máquina, el huésped, etc.) y manejando todas las partes de HTTPS: enviando la petición HTTP desencriptada a la aplicación HTTP actual que está corriendo en el mismo servidor (la aplicación con **FastAPI**, en este caso), tome la respuesta HTTP de la aplicación,  la encripte usando el certificado apropiado y la envié de vuelta al cliente usando HTTPS. Este servidor es comúnmente llamado un <a href="https://en.wikipedia.org/wiki/TLS_termination_proxy" class="external-link" target="_blank">TLS Termination Proxy</a>.
```

2024-01-15 15:25 UTC, tiangolo commented
As this PR had requested changes to be applied but has been inactive for a while, it's now going to be closed. But if there's anyone interested, feel free to create a new PR.

2024-01-15 15:25 UTC, closed without merging