🌐 Add Spanish translation of deployment/deta.md
fastapi/fastapi pull request #2699
Opened 2021-01-25 17:43 UTC by pedabraham

Hello 👋!,
This Pull Request includes the Spanish translation of **deployment/deta.md**

##### This pull request continues with the Spanish translation of #1218

2021-04-23 19:15 UTC, jovicon requested changes

2021-04-24 14:41 UTC, pedabraham commented
The changes were merged in the PR. Thank you @jovicon for the review.

2021-04-24 16:28 UTC, jovicon approved these changes

2021-05-07 12:52 UTC, bezaca approved these changes

2024-01-31 13:45 UTC, tiangolo commented
Thank you @pedabraham and everyone for the reviews! 🍰 

As this page was removed from the English version, this is no longer necessary. So I'll close this one now. But thanks for the effort! ☕

2024-01-31 13:45 UTC, closed without merging