Translate benchmarks.md to Turkish
fastapi/fastapi pull request #2729
Opened 2021-01-30 12:51 UTC by Telomeraz

This pr translates benchmarks.md file to Turkish.

Main issue: #1892

2021-02-21 10:07 UTC, ycd requested changes
Eline sağlık, ufak önermeler var sadece.

2021-02-21 10:07 UTC, ycd commented on docs/tr/docs/benchmarks.md
> +    * FastAPI'ı kullanmadıysanız ve Starlette'i doğrudan kullandıysanız (veya başka bir araç, Sanic, Flask, Responder, vb.) tüm data validation'ı ve serialization'ı kendiniz sağlamanız gerekir. Dolay
> Ve çoğu durumda, bu data validation ve serialization, uygulamalarda yazılan en büyük kod miktarıdır.

Çoğu durumda, uygulamalarda yazılan kodun büyük çoğunluğunu data validation ve serialization oluşturur.

2021-09-01 12:54 UTC, BilalAlpaslan approved these changes

2021-09-10 13:53 UTC, dogukanteber approved these changes

2021-09-11 15:45 UTC, ycd approved these changes

2021-10-05 12:47 UTC, tiangolo commented
Thank you @Telomeraz! :cake: :tada: 

And thanks for the reviews @dogukanteber, @BilalAlpaslan, @ycd :bow:

2021-10-05 12:50 UTC, merged