🌐 translate tutorial/static-files.md
fastapi/fastapi pull request #2957
Opened 2021-03-16 15:22 UTC by jeesang7

This is my first PR translates tutorial/static-files.md in Korean.
Frankly, I'm not used to it yet, so I chose the part that I know well and don't feel pressured.
Please review the translation, thanks.

안녕하세요, 이렇게 번역 기여에 참여하게 되어 기쁩니다.
비록 많이 부족하고 양도 적지만, 조금이라도 도움이 되고 싶어 PR 올립니다.
어색하거나 이견이 있으시면 피드백 부탁드립니다. 감사합니다.

related: #2017

2021-03-16 21:37 UTC, ArcLightSlavik commented
Could you change the name of PR to "Japanese translation for tutorial/static-files.md"

2021-03-17 00:17 UTC, jeesang7 commented
> Could you change the name of PR to "Japanese translation for tutorial/static-files.md"

Yes, it's not Japanese, this is Korean.

2021-03-17 10:32 UTC, JeongHyeongKim commented on docs/ko/docs/tutorial/static-files.md
> +* 특정 경로에 `StaticFiles()` 인스턴스를 "Mount" 합니다.
```suggestion
* 특정 경로에 `StaticFiles()` 인스턴스를 마운트 합니다.
```

how about this?  you translate mount to "마운트"  already in this docs

2021-03-17 13:59 UTC, jeesang7 commented on docs/ko/docs/tutorial/static-files.md
> +* 특정 경로에 `StaticFiles()` 인스턴스를 "Mount" 합니다.
That's a good capture for me. Thank you very much.

2021-03-19 14:55 UTC, akagaeng reviewed
살짝 자연스럽게 다듬어 봤습니다 :)

2021-03-19 14:55 UTC, akagaeng commented on docs/ko/docs/tutorial/static-files.md
> +"마운팅"은 특정 경로에 완전한 "독립적인" 애플리케이션을 추가한 후 모든 하위 경로를 처리하는 것을 의미합니다.
```suggestion
"마운팅"은 특정 경로에 완전한 "독립적인" 애플리케이션을 추가하는 것을 말하는데, 그 후에는 모든 하위 경로에 대해서도 적용됩니다.
```

2021-03-19 14:55 UTC, akagaeng commented on docs/ko/docs/tutorial/static-files.md
> +마운트된 애플리케이션이 완전히 독립적이기 때문에 `APIRouter`를 사용하는 것과는 다릅니다. OpenAPI 및 응용 프로그램의 문서에는 마운트된 응용 프로그램의 어떤 것도 포함되지 않습니다.
```suggestion
마운트된 애플리케이션은 완전히 독립적이기 때문에 `APIRouter`를 사용하는 것과는 다릅니다. OpenAPI 및 응용 프로그램의 문서는 마운트된 응용 프로그램 등에서 어떤 것도 포함하지 않습니다.
```

2021-03-20 12:36 UTC, jeesang7 commented
> 살짝 자연스럽게 다듬어 봤습니다 :)

훨씬 자연스러운 것 같습니다 😄

2021-11-05 14:33 UTC, 0417taehyun requested changes
Big appreciate of your works and great honor to check it.

Feel free to check my reviews 🚀 

I think the `aiofiles` section was deprecated so please update (fetch) the your file to the latest version.

2021-11-05 14:33 UTC, 0417taehyun commented on docs/ko/docs/tutorial/static-files.md
> +## `aiofiles` 설치
I think this section, **Install `aiofiles`** is deprecated. Please update (fetch) the files to the latest version.

2021-11-05 14:33 UTC, 0417taehyun commented on docs/ko/docs/tutorial/static-files.md
> +* 특정 경로에 `StaticFiles()` 인스턴스를 마운트 합니다.
```suggestion
* 특정 경로에 `StaticFiles()` 인스턴스를 "마운트" 합니다.
```

2021-11-05 14:33 UTC, 0417taehyun commented on docs/ko/docs/tutorial/static-files.md
> +!!! note "기술 세부사항"
```suggestion
!!! note "기술적 세부사항"
```

Check *파이썬 공식 한국어 문서에 없는 용어 중 현재 사용하고 있는 용어* in #3167 .

2021-11-05 14:33 UTC, 0417taehyun commented on docs/ko/docs/tutorial/static-files.md
> +    **FastAPI**는 개발자인 당신에게 편의를 제공하기 위해 `fastapi.static files` 와 동일한 `starlett.static files`를 제공합니다. 하지만 사실은 starlett에서 직접 온 것입니다.
```suggestion
    **FastAPI**는 단지 개발자인, 당신에게 편의를 제공하기 위해 `fastapi.static files` 와 동일한 `starlett.static files`를 제공합니다. 하지만 사실 이것은 Starlett에서 직접 온 것입니다.
```

2021-11-05 14:33 UTC, 0417taehyun commented on docs/ko/docs/tutorial/static-files.md
> +마운트된 애플리케이션은 완전히 독립적이기 때문에 `APIRouter`를 사용하는 것과는 다릅니다. OpenAPI 및 응용 프로그램의 문서는 마운트된 응용 프로그램 등에서 어떤 것도 포함하지 않습니다.
```suggestion
마운트된 응용 프로그램은 완전히 독립적이기 때문에 `APIRouter`를 사용하는 것과는 다릅니다. OpenAPI 및 응용 프로그램의 문서는 마운트된 응용 프로그램 등에서 어떤 것도 포함하지 않습니다.
```

2021-11-05 14:33 UTC, 0417taehyun commented on docs/ko/docs/tutorial/static-files.md
> +자세한 내용은 **고급 사용자 안내서**에서 확인할 수 있습니다.
```suggestion
자세한 내용은 **숙련된 사용자 안내서**에서 확인할 수 있습니다.
```

2021-11-05 14:33 UTC, 0417taehyun commented on docs/ko/docs/tutorial/static-files.md
> +"마운팅"은 특정 경로에 완전한 "독립적인" 애플리케이션을 추가하는 것을 말하는데, 그 후에는 모든 하위 경로에 대해서도 적용됩니다.
```suggestion
"마운팅"은 특정 경로에 완전히 "독립적인" 응용 프로그램을 추가하는 것을 의미하는데, 그 후 모든 하위 경로에 대해서도 적용됩니다.
```

2021-11-05 14:33 UTC, 0417taehyun commented on docs/ko/docs/tutorial/static-files.md
> +이 모든 매개변수는 "`static`"과 다를 수 있으며, 사용자 애플리케이션의 요구 사항 및 구체적인 세부 정보에 따라 매개변수를 조정할 수 있습니다.
```suggestion
이 모든 매개변수는 "`static`"과 다를 수 있으며, 사용자 응용 프로그램의 요구 사항 및 구체적인 세부 정보에 따라 매개변수를 조정할 수 있습니다.
```

2021-11-05 14:33 UTC, 0417taehyun commented on docs/ko/docs/tutorial/static-files.md
> +자세한 내용과 옵션을 보려면 <a href="https://www.starlette.io/staticfiles/" class="external-link" target="_blank">Starlette의 정적 파일에 관한 문서</a>를 확인하십시오.
```suggestion
자세한 내용과 선택 사항을 보려면 <a href="https://www.starlette.io/staticfiles/" class="external-link" target="_blank">Starlette의 정적 파일에 관한 문서</a>를 확인하십시오.
```

2021-11-05 14:33 UTC, 0417taehyun commented on docs/ko/docs/tutorial/static-files.md
> +첫 번째 `"/static"`은 이 "하위 애플리케이션"이 "마운트"될 하위 경로를 가리킵니다. 따라서 `"/static"`으로 시작하는 모든 경로는 `"/static"`으로 처리됩니다.
```suggestion
첫 번째 `"/static"`은 이 "하위 응용 프로그램"이 "마운트"될 하위 경로를 가리킵니다. 따라서 `"/static"`으로 시작하는 모든 경로는 `"/static"`으로 처리됩니다.
```

2021-11-05 14:33 UTC, 0417taehyun commented on docs/ko/docs/tutorial/static-files.md
> +## 추가정보
```suggestion
## 추가 정보
```

2023-06-26 19:11 UTC, tiangolo commented
📝 Docs preview for commit a52b9eb6e79dea0dcb3dfbe720c3cd162ce2fa05 at: https://6499e2c757a4bc039ac9416d--fastapi.netlify.app

2024-01-16 02:22 UTC, akagaeng commented on docs/ko/docs/tutorial/static-files.md
> +마운트된 애플리케이션은 완전히 독립적이기 때문에 `APIRouter`를 사용하는 것과는 다릅니다. OpenAPI 및 응용 프로그램의 문서는 마운트된 응용 프로그램 등에서 어떤 것도 포함하지 않습니다.
[Korean translations](https://github.com/tiangolo/fastapi/issues/2017) 이슈의 📚 Glossary 에서는 다음 문서를 참고하라고 되어있네요!

* https://docs.python.org/ko/3/glossary.html
* https://www.flowdas.com/pages/python-docs-ko.html

위 링크에서 확인해보면 `application: 응용 프로그램` 으로 사용하고 있어서 응용프로그램으로 하는게 일관성 측면에서 좋을 것 같습니다^^

<img width="777" alt="image" src="https://github.com/tiangolo/fastapi/assets/17076841/8eb45da3-33a6-4cb5-82cc-ebddf2efbad3">

**이미지 출처: https://www.flowdas.com/pages/python-docs-ko.html > 용어집**

2024-01-16 14:14 UTC, jeesang7 commented on docs/ko/docs/tutorial/static-files.md
> +마운트된 애플리케이션은 완전히 독립적이기 때문에 `APIRouter`를 사용하는 것과는 다릅니다. OpenAPI 및 응용 프로그램의 문서는 마운트된 응용 프로그램 등에서 어떤 것도 포함하지 않습니다.
오 좋은 가이드와 함께 의견 감사합니다.
제안 반영 하겠습니다 👍

2024-01-16 14:25 UTC, tiangolo commented
📝 Docs preview for commit 6fa91ab51d1856601d7ab87c0ff6bf95939141cd at: https://8a20da10.fastapitiangolo.pages.dev

2024-01-17 05:38 UTC, akagaeng approved these changes
LGTM

2024-01-22 19:42 UTC, merged