🌐 Add Russian translation for Python Types Intro
fastapi/fastapi pull request #3039
Opened 2021-04-03 20:21 UTC by dukkee

#1362

2021-06-27 16:03 UTC, BugLight requested changes

2021-06-27 16:03 UTC, BugLight commented on docs/ru/docs/python-types.md
> +Допустим, у вас есть класс `Person` с именем:
"Допустим, у вас есть класс `Person` с полем `name`:"

2021-06-27 16:03 UTC, BugLight commented on docs/ru/docs/python-types.md
> +    Чтобы узнать больше о <a href="https://pydantic-docs.helpmanual.io/" class="external-link" target="_blank">Pydantic, проверьте его документацию</a>.
Again not "проверьте", but "читайте" or "смотрите"

2021-06-27 16:03 UTC, BugLight commented on docs/ru/docs/python-types.md
> +**FastAPI** получает преимущества аннотации типов, чтобы выполнять следующие задачи.
"**FastAPI** использует преимущества аннотаций типов для выполнения определенных задач."

2021-06-28 16:30 UTC, dukkee commented on docs/ru/docs/python-types.md
> +**Аннотация типов** является специальным синтаксисом, который позволяет определять <abbr title="например: str, int, float, bool">тип</abbr> переменной.
@BugLight yes, it makes sense, thanks

2021-06-28 16:55 UTC, dukkee commented on docs/ru/docs/python-types.md
> +* Преобразовывает первую букву содержимого каждой переменной в верхний регистр с `title()`.
@BugLight I thought if it sounds better and I'm not sure. What is the motivation?

2021-06-28 17:32 UTC, dukkee commented on docs/ru/docs/python-types.md
> +Вы также можете объявить класс как тип переменной.
@BugLight Где там "пользовательский" в оригинале? И по смыслу тоже не подходит. Возможно, я б заменил "как" на "в качестве", но это больше вкусовщина, я думаю. Как и замена "объявить" на "использовать"...

2021-06-28 17:47 UTC, BugLight commented on docs/ru/docs/python-types.md
> +* Преобразовывает первую букву содержимого каждой переменной в верхний регистр с `title()`.
There are two kinds of verbs in russian grammar: совершенного вида and невосовершенного вида. "Преобразует" describes completed action, "преобразовывает" describes the process. It's a little more complex than my explanation, but this is the key difference. At most I rely on my native speaker's intuition.

2021-06-28 17:49 UTC, BugLight commented on docs/ru/docs/python-types.md
> +Вы также можете объявить класс как тип переменной.
Не посмотрел в оригинал. Вне контекста о другом подумал.

2021-06-28 17:51 UTC, dukkee commented on docs/ru/docs/python-types.md
> +* Преобразовывает первую букву содержимого каждой переменной в верхний регистр с `title()`.
I know the difference between those variants and I translated it exactly because of the process accent, honestly.

2021-06-28 17:55 UTC, dukkee commented on docs/ru/docs/python-types.md
> +Вы также можете объявить класс как тип переменной.
ок, без проблем 👍

2021-06-28 17:56 UTC, BugLight commented on docs/ru/docs/python-types.md
> +* Преобразовывает первую букву содержимого каждой переменной в верхний регистр с `title()`.
https://context.reverso.net/перевод/английский-русский/converts#преобразует

2021-06-28 17:57 UTC, dukkee commented on docs/ru/docs/python-types.md
> +* Преобразовывает первую букву содержимого каждой переменной в верхний регистр с `title()`.
аргумент, тогда обновляю 👍

2021-06-28 18:00 UTC, dukkee commented
@BugLight thank you very much for your review, please check if you have any thoughts about other parts.

+ I will be happy if you check my other translation PRs and contact me via the FastAPI official server (you can easily find me via GitHub username) or Telegram e.g. (with the same GitHub username).

2021-07-02 12:57 UTC, dukkee commented
@BugLight Could you please also accept this PR?

2021-07-02 14:12 UTC, BugLight approved these changes

2021-07-19 09:34 UTC, solomein-sv approved these changes

2021-07-19 09:34 UTC, solomein-sv commented on docs/ru/docs/python-types.md
> +# Введение в Python-типы
```suggestion
# Введение в аннотации типов Python
```

2021-07-19 09:34 UTC, solomein-sv commented on docs/ru/docs/python-types.md
> +При объявлении типов для ваших переменных редакторы и инструменты могут предоставить вам лучшую поддержку.
```suggestion
Объявление типов для переменных позволяет улучшить поддержку вашего кода  редакторами и различными инструментами.
```

2021-07-19 09:34 UTC, solomein-sv commented on docs/ru/docs/python-types.md
> +* <abbr title="Объединяет их как одно целое. С содержимым одно за другим.">Соединяет</abbr> их с пробелом посередине.
```suggestion
* <abbr title="Объединяет в одно целое, последовательно, друг за другом.">Соединяет</abbr> их через пробел.
```

2021-07-19 09:34 UTC, solomein-sv commented on docs/ru/docs/python-types.md
> +### Отредактируем это
```suggestion
### Отредактируем пример
```

2021-07-21 06:17 UTC, dukkee commented
@solomein-sv great work, thanks a lot. Also, I will check your other suggestions in the near time. Please review the current PR again and approve, if it's okay in your opinion.

2021-07-21 07:30 UTC, solomein-sv approved these changes

2021-07-29 20:18 UTC, tiangolo commented
Awesome, thanks for your contribution @dukkee! :tada: :rocket: 

And thanks for the reviews @BugLight and @solomein-sv :cake:

2021-07-29 20:22 UTC, merged