Add Korean translation for Tutorial - Body - Updates
fastapi/fastapi pull request #3120
Opened 2021-04-23 08:32 UTC by NEONKID

Add translate about tutorial/body-updates

2021-04-23 15:18 UTC, baek9652 commented
#2017 It's a tag for tracking

2021-11-05 13:53 UTC, 0417taehyun requested changes
Big appreciate of your works and great honor to check yours!

Feel free to check my reviews 🚀 

Also, can you replace the markdown syntax `-` to `*`, which refers to list because the origin document uses `*` instead of `-`.

2021-11-05 13:53 UTC, 0417taehyun commented on docs/ko/docs/tutorial/body-updates.md
> +항목을 업데이트 하기 위해 <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT" class="external-link" target="_blank">HTTP `PUT`</a>을 사용할 수 있습니다.
```suggestion
항목을 수정 하기 위해 <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT" class="external-link" target="_blank">HTTP `PUT`</a>을 사용할 수 있습니다.
```

2021-11-05 13:53 UTC, 0417taehyun commented on docs/ko/docs/tutorial/body-updates.md
> +# 본문 - 업데이트
```suggestion
# 본문 - 수정
```

> use less English as you can.

Check #2017 .

2021-11-05 13:53 UTC, 0417taehyun commented on docs/ko/docs/tutorial/body-updates.md
> +## `PUT`을 이용한 업데이트
```suggestion
## `PUT`을 이용한 수정
```

2021-11-05 13:53 UTC, 0417taehyun commented on docs/ko/docs/tutorial/body-updates.md
> +`jsonable_encoder`를 사용하여 입력 데이터를 JSON(예: NoSQL 데이터베이스 데이터)으로 저장 가능한 데이터로 변환할 수 있습니다. 예를 들면, `datetime` 타입을 `str`로 변환하게 됩니다.
```suggestion
`jsonable_encoder`를 사용하여 입력 데이터를 (예를 들어, NoSQL 데이터베이스에서 사용 가능한) JSON으로 저장 가능하게 변환할 수 있습니다. 예를 들면, `datetime` 자료형을 `str`로 변환하게 됩니다.
```

2021-11-05 13:53 UTC, 0417taehyun commented on docs/ko/docs/tutorial/body-updates.md
> +본문이 포함된 `PUT`을 사용하여 `bar` 항목을 업데이트 하려면:
```suggestion
본문이 포함된 `PUT`을 사용하여 `bar` 항목을 수정하려면:
```

2021-11-05 13:53 UTC, 0417taehyun commented on docs/ko/docs/tutorial/body-updates.md
> +데이터를 부분적으로 업데이트 하기; 위해 HTTP <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH" class="external-link" target="_blank">HTTP `PATCH`</a> 를 사용할 수도 있습니다.
```suggestion
데이터를 부분적으로 수정하기 위해 <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH" class="external-link" target="_blank">HTTP `PATCH`</a> 를 사용할 수도 있습니다.
```

2021-11-05 13:53 UTC, 0417taehyun commented on docs/ko/docs/tutorial/body-updates.md
> +## `PATCH`를 이용한 부분 업데이트
```suggestion
## `PATCH`를 이용한 부분 수정
```

2021-11-05 13:53 UTC, 0417taehyun commented on docs/ko/docs/tutorial/body-updates.md
> +즉, 업데이트하려는 데이터만 보내고, 나머지는 그대로 둘 수 있습니다.
```suggestion
즉, 수정하려는 데이터만 보내고, 나머지는 그대로 둘 수 있습니다.
```

2021-11-05 13:53 UTC, 0417taehyun commented on docs/ko/docs/tutorial/body-updates.md
> +일반적으로 `PATCH`보다 `PUT`이 더 일반적으로 사용되고, 잘 알려져 있습니다.
Isn't it need to indent?

2021-11-05 13:53 UTC, 0417taehyun commented on docs/ko/docs/tutorial/body-updates.md
> +    그리고 많은 팀이 부분 업데이트를 위해서도 `PUT`만 사용합니다.
```suggestion
    그리고 많은 팀이 부분 수정을 할 때도, `PUT`만 사용합니다.
```

2021-11-05 13:53 UTC, 0417taehyun commented on docs/ko/docs/tutorial/body-updates.md
> +    무엇을 사용하든 FastAPI에서는 어떠한 제한도 없습니다.
```suggestion
    원하는 대로 **자유롭게** 사용할 수 있습니다, **FastAPI**는 이를 제한하지 않습니다.
```

2021-11-05 13:53 UTC, 0417taehyun commented on docs/ko/docs/tutorial/body-updates.md
> +    하지만 이 가이드는 각 메소드가 어떻게 사용되는지를 보여줍니다.
```suggestion
    하지만 이 지침서는 각 메서드가 어떻게 사용되는 지를 보여줍니다.
```

2021-11-05 13:53 UTC, 0417taehyun commented on docs/ko/docs/tutorial/body-updates.md
> +위 데이터를 사용하여 설정된 데이터(요청에서 전송됨)만으로 `dict`를 생성하고 기본값을 생략할 수 있습니다:
```suggestion
위 데이터를 사용하여 설정된 (요청에서 전송된) 데이터만으로 `dict`를 생성하고 기본값을 생략할 수 있습니다:
```

2021-11-05 13:53 UTC, 0417taehyun commented on docs/ko/docs/tutorial/body-updates.md
> +Pydantic 모델의 `.dict()`에서 `exclude_unset` 매개변수를 사용하는 것은 부분 업데이트를 위해 매우 유용합니다.
```suggestion
Pydantic 모델의 `.dict()`에서 `exclude_unset` 매개변수를 사용하는 것은 부분 수정을 위해 매우 유용합니다.
```

2021-11-05 13:53 UTC, 0417taehyun commented on docs/ko/docs/tutorial/body-updates.md
> +이제 `.copy()`를 이용하여 기존 모델의 복사본을 만들고 업데이트 할 데이터가 포함된 `dict`와 함께 `update` 매개변수를 전달할 수 있습니다.
```suggestion
이제 `.copy()`를 이용하여 기존 모델의 복사본을 만들고 수정할 데이터가 포함된 `dict`와 함께 `update` 매개변수를 전달할 수 있습니다.
```

2021-11-05 13:53 UTC, 0417taehyun commented on docs/ko/docs/tutorial/body-updates.md
> +### 부분 업데이트 요약
```suggestion
### 부분 수정 요약
```

2021-11-05 13:53 UTC, 0417taehyun commented on docs/ko/docs/tutorial/body-updates.md
> +부분 업데이트를 적용하는 방법을 요약하면:
```suggestion
부분 수정을 적용하는 방법을 요약하면:
```

2021-11-05 13:53 UTC, 0417taehyun commented on docs/ko/docs/tutorial/body-updates.md
> +-   위 모델에서 기본값 없는 `dict`를 생성합니다. (`exclude_unset` 사용).
```suggestion
-   위 모델에서 (`exclude_unset`을 사용하여) 기본값 없는 `dict`를 생성합니다.
```

2021-11-05 13:53 UTC, 0417taehyun commented on docs/ko/docs/tutorial/body-updates.md
> +    -   이렇게 하면 모델에 이미 기본값으로 저장된 값을 재정의하는 대신 클라이언트가 실제로 설정한 값만 업데이트 할 수 있습니다.
```suggestion
    -   이렇게 하면 모델에 이미 기본값으로 저장된 값을 재정의하는 대신 클라이언트가 실제로 설정한 값만 수정할 수 있습니다.
```

2021-11-05 13:53 UTC, 0417taehyun commented on docs/ko/docs/tutorial/body-updates.md
> +-   복사된 모델을 DB에 저장할 수 있는 형태로 변환합니다. (예를 들면, `jsonable_encoder` 함수를 사용한 JSON 데이터 변환).
```suggestion
-   (예를 들면, `jsonable_encoder`를 사용한 것과 같이) 복사된 모델을 DB에 저장할 수 있는 형태로 변환합니다.
```

2021-11-05 13:53 UTC, 0417taehyun commented on docs/ko/docs/tutorial/body-updates.md
> +!!! note
```suggestion
!!! note "참고"
```

2021-11-14 08:29 UTC, NEONKID commented
@0417taehyun 
Thank you for reviewing. I have actively accepted and reflected your opinions.

2023-06-26 19:12 UTC, tiangolo commented
📝 Docs preview for commit 4a69087a74f2b873815107f086e4e4fe8938f9df at: https://6499e2c9cad46e052d3acc50--fastapi.netlify.app

2024-03-30 23:07 UTC, tiangolo commented
Thank you! I'm still waiting for others to review this to be able to merge it, meanwhile, maybe you could help me review some of the other Korean translations, that way if they are approved by each other, I could merge them. :nerd_face: 

https://github.com/tiangolo/fastapi/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Alang-ko+label%3Aawaiting-review

Maybe @0417taehyun could review it again after the requested changes? :coffee:

2025-06-05 08:02 UTC, YuriiMotov commented
This PR contains broken markdown, quite old and probably outdated.
Considering Author seems to be not interested in improving it, I would suggest we close it

2025-07-26 09:44 UTC, closed without merging