:globe_with_meridians: Add Spanish translation of Advanced User - WSGI
fastapi/fastapi pull request #3126
Opened 2021-04-24 04:19 UTC by bezaca

Hi there :handshake: !
This pull request include the Spanish translation of advanced/wsgi.md

This pull request continues with the Spanish translation of #1218

2021-04-24 18:13 UTC, jovicon requested changes

2021-04-24 18:13 UTC, jovicon commented on docs/es/docs/advanced/wsgi.md
> +Puedes montar aplicaciones WSGI como observaste en [Sub Aplicaciones - Montajes](./sub-applications.md){.internal-link target=_blank}, [Detrás de un Proxy](./behind-a-proxy.md){.internal-link target=
example
```suggestion
Puedes montar aplicaciones WSGI como visté en [Sub Aplicaciones - Montajes](./sub-applications.md){.internal-link target=_blank}, [Detrás de un Proxy](./behind-a-proxy.md){.internal-link target=_blank}.
```

2021-04-24 18:13 UTC, jovicon commented on docs/es/docs/advanced/wsgi.md
> +Para esto , puedes utilizar `WSGIMiddleware` y posteriormente utilizarlo para empaquetar tú aplicación WSGI , por ejemplo , Flask, Django, etc.
Para eso
```suggestion
Para eso, puedes utilizar `WSGIMiddleware` y posteriormente utilizarlo para empaquetar tú aplicación WSGI , por ejemplo , Flask, Django, etc.
```

2021-04-24 18:13 UTC, jovicon commented on docs/es/docs/advanced/wsgi.md
> +Y el resto va ser manejado por **FastAPI**.
```suggestion
Y el resto será manejado por **FastAPI**.
```

2024-12-30 18:57 UTC, closed without merging

2024-12-30 18:57 UTC, tiangolo commented
This was covered in another PR, so I'll close this one now, thanks for the effort! :cake: :coffee: