Add Spanish translation of Advanced User - WebSockets
fastapi/fastapi pull request #3134
Opened 2021-04-27 15:53 UTC by bezaca

Hi there handshake !
This pull request include the Spanish translation of advanced/websockets.md

This pull request continues with the Spanish translation of #1218

2021-05-02 06:44 UTC, anthonycepeda requested changes
Hi,

Please check my recomendations.
Take into account that in spanish, the trailed comma(,) need to be sticked to the last word without spaces:
"En tu sistema de producción, posiblemente..."

2021-05-02 06:44 UTC, anthonycepeda commented on docs/es/docs/advanced/websockets.md
> +Y si utilizas <abbr>WebSockets</abbr> para comunicarte con tu <abbr>backend</abbr> muy probablemente utilices las <abbr>utilities</abbr> de tú <abbr>frontend</abbr>.
Y si utilizas <abbr>WebSockets</abbr> para comunicarte con tu <abbr>backend</abbr> muy probablemente utilices las <abbr>funcionalidades</abbr> de tú aplicación<abbr>frontend</abbr>.

2021-05-02 06:44 UTC, anthonycepeda commented on docs/es/docs/advanced/websockets.md
> +O posiblemente cuentes con otra manera de comunicarte con el <abbr>WebSocket</abbr> del <abbr>endpoint</abbr>.
O tal vez tengas otra forma de comunicarte con el<abbr>endpoint</abbr> del <abbr>WebSocket</abbr>

2021-05-02 06:44 UTC, anthonycepeda commented on docs/es/docs/advanced/websockets.md
> +    **FastAPI** proporciona el mismo <abbr>`WebSocket`</abbr> directamente solo como una conveniencia para ti , el desarrollador. Pero viene directamente de Starlette.
**FastAPI** proporciona el mismo <abbr>`WebSocket`</abbr> directamente solo por comodidad para ti , el desarrollador. Pero viene directamente de Starlette.

2021-05-02 06:44 UTC, anthonycepeda commented on docs/es/docs/advanced/websockets.md
> +En la ruta de tu <abbr>WebSocket</abbr> puedes `esperar` por mensajes y enviar mensajes.
En la ruta de tu <abbr>WebSocket</abbr> puedes esperar (`await`) por mensajes y enviar mensajes.

2021-05-02 06:44 UTC, anthonycepeda commented on docs/es/docs/advanced/websockets.md
> +Verás una simple pagina parecida a esto:
Verás una pagina simple parecida a esta:

2021-05-02 06:44 UTC, anthonycepeda commented on docs/es/docs/advanced/websockets.md
> +Puedes escribir mensajes en la caja de entrada , y luego enviarlos:
Puedes escribir mensajes en el cuadro de texto, y luego enviarlos:

2021-05-02 06:44 UTC, anthonycepeda commented on docs/es/docs/advanced/websockets.md
> +Trabajan de las misma manera que otros <abbr>endpoints</abbr>/*operaciones de <abbr>path</abbr>* en FastAPI:
Funcionan de la misma forma que otros <abbr>endpoints</abbr>/*operaciones de <abbr>path</abbr>* en FastAPI:

2021-05-02 06:44 UTC, anthonycepeda commented on docs/es/docs/advanced/websockets.md
> +    En un <abbr>WebSocket</abbr> realmente no vale la pena causar un <abbr>`HTTPException`</abbr>. Por lo tanto es mejor cerrar directamente la conexión al <abbr>WebSocket</abbr>.
Debido a que en un <abbr>WebSocket</abbr> no es necesario lanzar un <abbr>`HTTPException`</abbr>, lo mejor sería cerrar directamente la conexión al <abbr>WebSocket</abbr>.

2021-05-02 14:47 UTC, bezaca commented on docs/es/docs/advanced/websockets.md
> +Y si utilizas <abbr>WebSockets</abbr> para comunicarte con tu <abbr>backend</abbr> muy probablemente utilices las <abbr>utilities</abbr> de tú <abbr>frontend</abbr>.
Gracias Anthony por tus sugerencias.

2021-05-02 18:32 UTC, anthonycepeda approved these changes
Great. Thanks

2024-12-30 18:56 UTC, tiangolo commented
This was covered in another PR, so I'll close this one now, thanks for the effort! :cake: :coffee:

2024-12-30 18:56 UTC, closed without merging