Moved duplicated code portion to the staticmethod in the super class
fastapi/fastapi pull request #3142
Opened 2021-04-29 07:28 UTC by ShahriyarR

The code block below was used 3 times:
```
        if not api_key:
            if auto_error:
                raise HTTPException(
                    status_code=HTTP_403_FORBIDDEN, detail="Not authenticated"
                )
            else:
                return None
        return api_key
 ```
 
 I have moved this portion to the `staticmethod` into the super class as it will be shared by inheritance to all 3 subclasses.

2022-02-03 21:56 UTC, cikay requested changes

2022-02-03 21:56 UTC, cikay commented on fastapi/security/api_key.py
> +            else:
Remove else statement.

2022-05-13 10:13 UTC, ShahriyarR commented on fastapi/security/api_key.py
> +            else:
Done

2022-05-13 20:55 UTC, yezz123 approved these changes

2022-05-15 12:26 UTC, BilalAlpaslan approved these changes

2024-08-09 12:59 UTC, patrick91 approved these changes
Nice!

2024-08-14 10:32 UTC, svlandeg commented
@patrick91 : could you have another look at this PR, as it's not succeeding the linting step? 🙏

2024-09-03 13:13 UTC, svlandeg approved these changes

2025-01-30 12:17 UTC, tiangolo approved these changes
Nice, thank you! :rocket: 

And thanks for the reviews and help! :coffee:

2025-01-30 12:17 UTC, merged