Add Spanish translation of Advanced User - graphQL
fastapi/fastapi pull request #3150
Opened 2021-05-01 01:54 UTC by bezaca

Hi there :handshake:!
This pull request include the Spanish translation of advanced/graphql.md 

This pull request continues with the Spanish translation of #1218

2021-05-02 06:14 UTC, anthonycepeda requested changes
Hi,
I've added some changes request.
Thanks

2021-05-02 06:14 UTC, anthonycepeda commented on docs/es/docs/advanced/graphql.md
> +**FastAPI** tiene soporte opcional para GraphQL (proveído por Starlette directamente), usando la librería de `graphene`.
Hi, maybe: 
**FastAPI** cuenta con soporte opcional para GraphQL, usando la librería `graphene` de Startlette.

2021-05-02 06:14 UTC, anthonycepeda commented on docs/es/docs/advanced/graphql.md
> +GraphQL es implementado mediante Graphene, puedes mirar la <a href="https://docs.graphene-python.org/en/latest/quickstart/" class="external-link" target="_blank"> documentación de Graphene </a> para
GraphQL ha sido implementado usando Graphene, puedes revisar la documentación oficial de Graphene para más detalles

2021-05-02 06:14 UTC, anthonycepeda commented on docs/es/docs/advanced/graphql.md
> +Para más detalles , incluyendo :
Para conocer más detalles sobre:

2024-02-07 12:56 UTC, tiangolo commented
Thanks @bezaca! 🤓 

As this section changed a lot in the original in English, I'm gonna pass on this one, but thanks for the effort! ☕

2024-02-07 12:56 UTC, closed without merging