Add Spanish translation of Advanced User -  Templates
fastapi/fastapi pull request #3157
Opened 2021-05-01 22:35 UTC by bezaca

Hi there :handshake: !
This pull request include the Spanish translation of advanced/templates.md

This pull request continues with the Spanish translation of #1218

2022-09-23 20:24 UTC, eavv requested changes
Litlle punctuation details

2022-09-23 20:24 UTC, eavv commented on docs/es/docs/advanced/templates.md
> +    Observa que debes pasar la petición como parte de las parejas clave-valor en el contexto de Jinja2. por lo tanto , debes declararlo también en tus *operaciones de <abbr title="ruta">path</abbr>*.
```suggestion
    Observa que debes pasar la petición como parte de las parejas clave-valor en el contexto de Jinja2. Por lo tanto, debes declararlo también en tus *operaciones de <abbr title="ruta">path</abbr>*.
```

2022-09-23 20:24 UTC, eavv commented on docs/es/docs/advanced/templates.md
> +    Declarando `response_class=HTMLResponse` , la documentación de la interfaz gráfica sabrá que la respuesta será un HTML.
```suggestion
    Declarando `response_class=HTMLResponse`, la documentación de la interfaz gráfica sabrá que la respuesta será un HTML.
```

2022-09-23 20:24 UTC, eavv commented on docs/es/docs/advanced/templates.md
> +Además puedes usar `url_for()` dentro de una plantilla, y utilizarlo por ejemplo, con <abbr title="Archivos Estáticos">`StaticFiles`</abbr> que hayas montado.
```suggestion
Además, puedes usar `url_for()` dentro de una plantilla y utilizarlo, por ejemplo, con <abbr title="Archivos Estáticos">`StaticFiles`</abbr> que hayas montado.
```

2022-09-23 20:24 UTC, eavv commented on docs/es/docs/advanced/templates.md
> +Y como estas utilizando `StaticFiles`, ese archivo CSS será proporcionado automáticamente por tu aplicación de **FastAPI** en la URL `/static/styles.css` .
```suggestion
Y como estas utilizando `StaticFiles`, ese archivo CSS será proporcionado automáticamente por tu aplicación de **FastAPI** en la URL `/static/styles.css`.
```

2024-01-31 13:46 UTC, tiangolo commented
As this PR had requested changes to be applied but has been inactive for a while, it's now going to be closed. But if there's anyone interested, feel free to create a new PR.

2024-01-31 13:46 UTC, closed without merging