🌐 Add Spanish translation of Advanced User Guide - Events
fastapi/fastapi pull request #3187
Opened 2021-05-07 02:22 UTC by bezaca

Hi there :handshake: !
This pull request include the Spanish translation of advanced/events.md

This pull request continues with the Spanish translation of #1218 

I would apreciate it very much if someone can check and review the translation.

2021-12-30 03:36 UTC, israteneda requested changes
Buen trabajo 📖 dejo algunos comentarios

2021-12-30 03:36 UTC, israteneda commented on docs/es/docs/advanced/events.md
> +Puedes definir controladores de eventos (funciones) que necesiten ser ejecutados antes de que inicie la aplicación, o cuando la aplicación se este cerrando.
```suggestion
Puedes definir controladores de eventos (funciones) que necesiten ser ejecutados antes de que inicie la aplicación, o cuando la aplicación se esté cerrando.
```

2021-12-30 03:36 UTC, israteneda commented on docs/es/docs/advanced/events.md
> +Solamente los controladores de eventos para la aplicación principal serán ejecutados, no se ejecutaran [Sub Aplicaciones - Montaje](./sub-applications.md){.internal-link target=\_blank}.
```suggestion
Solamente los controladores de eventos para la aplicación principal serán ejecutados, no se ejecutarán [Sub Aplicaciones - Montaje](./sub-applications.md){.internal-link target=\_blank}.
```

2021-12-30 03:36 UTC, israteneda commented on docs/es/docs/advanced/events.md
> +En este caso, el evento <abbr title="inicio">`startup`</abbr> inicializara los elementos de la "base de datos" (como un `diccionario`) con algunos valores.
```suggestion
En este caso, el evento <abbr title="inicio">`startup`</abbr> inicializará los elementos de la "base de datos" (como un `diccionario`) con algunos valores.
```

2021-12-30 03:36 UTC, israteneda commented on docs/es/docs/advanced/events.md
> +Y tú aplicación no recibirá peticiones hasta que todos los controladores de eventos de tipo <abbr>`startup`</abbr> se hallan completado.
```suggestion
Y tú aplicación no recibirá peticiones hasta que todos los controladores de eventos de tipo <abbr>`startup`</abbr> se hayan completado.
```

2021-12-30 03:36 UTC, israteneda commented on docs/es/docs/advanced/events.md
> +Para añadir una función que debe ejecutarse cuando la aplicación se esta cerrando, debe declarase con el evento <abbr>`"shutdown"`</abbr>:
```suggestion
Para añadir una función que debe ejecutarse cuando la aplicación se está cerrando, debe declararse con el evento <abbr>`"shutdown"`</abbr>:
```

2021-12-30 03:36 UTC, israteneda commented on docs/es/docs/advanced/events.md
> +Aquí , el controlador de evento <abbr>`shutdown`</abbr> escribirá una linea de texto <abbr title="Cierre de aplicación">`"Application shutdown"`</abbr> a un archivo `log.txt`.
```suggestion
Aquí , el controlador de evento <abbr>`shutdown`</abbr> escribirá una línea de texto <abbr title="Cierre de aplicación">`"Application shutdown"`</abbr> a un archivo `log.txt`.
```

2021-12-30 03:36 UTC, israteneda commented on docs/es/docs/advanced/events.md
> +En la función `open()`, el <abbr title="modo">`mode="a"`</abbr> significa <abbr title="agregar">"append"</abbr>, por lo tanto, la linea sera añadida después de cualquier elemento que halla en el arch
```suggestion
En la función `open()`, el <abbr title="modo">`mode="a"`</abbr> significa <abbr title="agregar">"append"</abbr>, por lo tanto, la línea será añadida después de cualquier elemento que halla en el archivo, sin llegar a sobreescribir el contenido previo.
```

2021-12-30 03:36 UTC, israteneda commented on docs/es/docs/advanced/events.md
> +    Observa que en este caso estamos utilizando la función estándar `open()` de Python para interactúa con el archivo.
```suggestion
    Observa que en este caso estamos utilizando la función estándar `open()` de Python para interactuar con el archivo.
```

2021-12-30 03:36 UTC, israteneda commented on docs/es/docs/advanced/events.md
> +    Entonces , involucramos I/O <abbr title="entrada/salida">(input/output)</abbr>, que requiere "esperar" para que los elementos se escriban en el disco.
```suggestion
    Entonces, involucramos I/O <abbr title="entrada/salida">(input/output)</abbr>, que requiere "esperar" para que los elementos se escriban en el disco.
```

2021-12-30 03:36 UTC, israteneda commented on docs/es/docs/advanced/events.md
> +    Para ello, declaramos un controlador de evento utilizando `def` en vez de `async def`.
Ya que en la línea anterior estamos empleando la palabra `utiliza` en esta línea podríamos utilizar una palabra diferente.
```suggestion
    Para ello, declaramos un controlador de evento usando `def` en vez de `async def`.
```

2022-01-24 04:41 UTC, israteneda approved these changes
✅  Looks good

2024-12-30 18:56 UTC, tiangolo commented
This was covered in another PR, so I'll close this one now, thanks for the effort! :cake: :coffee:

2024-12-30 18:56 UTC, closed without merging