Add Chinese translation for Tutorial - Body - Updates
fastapi/fastapi pull request #3237
Opened 2021-05-17 04:09 UTC by jaystone776

as title

2021-05-17 06:29 UTC, waynerv requested changes

2021-05-17 06:29 UTC, waynerv commented on docs/zh/docs/tutorial/body-updates.md
> +这段代码生成的 `dict` 只包含创建 `item` 模型时设置的数据，排除了默认值。
```suggestion
这段代码生成的 `dict` 只包含创建 `item` 模型时显式设置的数据，而不包括默认值。
```

2021-05-17 06:29 UTC, waynerv commented on docs/zh/docs/tutorial/body-updates.md
> +然后再用它生成一个只含（在发出请求时）设置的数据，且省略了默认值的 `dict`：
```suggestion
然后再用它生成一个只含已设置（在请求中所发送）数据，且省略了默认值的 `dict`：
```

2021-05-17 06:29 UTC, waynerv commented on docs/zh/docs/tutorial/body-updates.md
> +接下来，用 `.copy()` 为已有模型创建调用 `update` 参数的副本，该参数为包含更新数据的`dict`。
```suggestion
现在，你可以使用 `.copy()` 为已有的模型创建一个副本，并且传入 `update` 参数，参数值为包含将要更新数据的`dict`。
```

2021-05-17 06:29 UTC, waynerv commented on docs/zh/docs/tutorial/body-updates.md
> +    因此，如果希望接收的部分更新数据可以省略其他所有属性，则要把模型中所有（使用默认值或 `None`）的属性标记为可选。
```suggestion
    因此，如果希望接收的部分更新数据可以省略其他所有属性，则要把模型中所有的属性标记为可选（使用默认值或 `None`）。
```

2021-05-18 06:07 UTC, waynerv approved these changes

2021-05-31 14:56 UTC, Laineyzhang55 approved these changes

2021-06-25 03:39 UTC, voidf approved these changes
nice

2021-07-02 14:23 UTC, tiangolo commented
Great, thank you @jaystone776 ! :tada: :cake: 

And thanks a lot for the reviews @voidf, @waynerv, and @Laineyzhang55 :rocket: :bow:

2021-07-02 14:23 UTC, merged