Add Chinese translation for Tutorial - Request - Files
fastapi/fastapi pull request #3244
Opened 2021-05-18 06:20 UTC by jaystone776

as title

2021-05-18 08:11 UTC, waynerv requested changes

2021-05-18 08:11 UTC, waynerv commented on docs/zh/docs/tutorial/request-files.md
> +* `file`： <a href="https://docs.python.org/zh-cn/3/library/tempfile.html#tempfile.SpooledTemporaryFile" class="external-link" target="_blank">`SpooledTemporaryFile`</a>（ <a href="https://docs.python.
```suggestion
* `file`： <a href="https://docs.python.org/zh-cn/3/library/tempfile.html#tempfile.SpooledTemporaryFile" class="external-link" target="_blank">`SpooledTemporaryFile`</a>（ <a href="https://docs.python.org/zh-cn/3/glossary.html#term-file-like-object" class="external-link" target="_blank">文件类</a>对象）。其实就是 Python文件，可直接传递给其他预期 `file-like` 对象的函数或支持库。
```

2021-05-18 08:11 UTC, waynerv commented on docs/zh/docs/tutorial/request-files.md
> +    可在一个 *路径操作* 中声明多个 `File` 和 `Form` 参数，但不能同时声明要接收 JSON 的 `Body` 字段。因为此时请求体的编码是 `multipart/form-data`，不是 `application/json`。
```suggestion
    可在一个*路径操作*中声明多个 `File` 和 `Form` 参数，但不能同时声明要接收 JSON 的 `Body` 字段。因为此时请求体的编码是 `multipart/form-data`，不是 `application/json`。
```

2021-05-19 03:58 UTC, waynerv approved these changes

2021-05-19 04:39 UTC, waynerv approved these changes

2021-05-31 14:56 UTC, Laineyzhang55 approved these changes

2021-06-29 12:24 UTC, tiangolo commented
Awesome, thank you @jaystone776 ! :rocket: :bow: 

And thanks @waynerv and @Laineyzhang55 for the reviews! :cake:

2021-06-29 12:24 UTC, merged