🌐 Add Spanish traslation for Middleware
fastapi/fastapi pull request #3257
Opened 2021-05-20 17:28 UTC by bezaca

Hi there :handshake:  !
This pull request include the Spanish translation of middleware.md_es
This pull request continues with the Spanish translation of #1218

2021-12-30 03:07 UTC, israteneda requested changes
Muy buena traducción, solo algunas recomendaciones

2021-12-30 03:07 UTC, israteneda commented on docs/es/docs/tutorial/middleware.md
> +Un "middleware" es una función que se ejecuta con cada **petición** antes de que se procesada por cualquier <abbr title="path operation">*operación de ruta*</abbr>. Y antes de devolver cada **respues
```suggestion
Un "middleware" es una función que se ejecuta con cada **petición** antes de que sea procesada por cualquier <abbr title="path operation">*operación de ruta*</abbr>. Y antes de devolver cada **respuesta**.
```

2021-12-30 03:07 UTC, israteneda commented on docs/es/docs/tutorial/middleware.md
> +* Posteriormente toma la **petición** para ser procesada por el resto de la aplicación (por alguna *operación de path*).
```suggestion
* Posteriormente, toma la **petición** para ser procesada por el resto de la aplicación (por alguna *operación de path*).
```

2021-12-30 03:07 UTC, israteneda commented on docs/es/docs/tutorial/middleware.md
> +Para crear un middleware debemos utilizar el decorador `@app.middleware("http")` encima de la función.
Hay algunos lugares en los que usamos `utilizar` por lo que estaría bien utilizar una palabra diferente con el mismo significado.
```suggestion
Para crear un middleware debemos usar el decorador `@app.middleware("http")` encima de la función.
```

2021-12-30 03:07 UTC, israteneda commented on docs/es/docs/tutorial/middleware.md
> +    * Posteriormente retorna la `respuesta` generada por la *operación de path*.
```suggestion
    * Posteriormente, retorna la `respuesta` generada por la *operación de path*.
```

2021-12-30 03:07 UTC, israteneda commented on docs/es/docs/tutorial/middleware.md
> +* Luego, puedes modificar aun más la `respuesta` antes de devolverla.
```suggestion
* Luego, puedes modificar aún más la `respuesta` antes de devolverla.
```

2021-12-30 03:07 UTC, israteneda commented on docs/es/docs/tutorial/middleware.md
> +    Pero, si tienes headers personalizados que deseas que un cliente pueda visualizar en un navegador, debes agregarlos a tus configuraciones de CORS ([CORS (Cross-Origin Resource Sharing)](cors.md){
```suggestion
    Pero, si tienes headers personalizados que deseas que un cliente pueda visualizar en un navegador, debes agregarlos a tus configuraciones de CORS ([CORS (Cross-Origin Resource Sharing)](cors.md){.internal-link target=_blank}) empleando el parámetro `expose_headers`, puedes consultar más en <a href="https://www.starlette.io/middleware/#corsmiddleware" class="external-link" target="_blank">la documentación de Starlette acerca de CORS</a>.
```

2021-12-30 03:07 UTC, israteneda commented on docs/es/docs/tutorial/middleware.md
> +Puedes leer más acerca de otros middlewares en [Guia de Usuario Avanzado: Middleware Avanzado](../advanced/middleware.md){.internal-link target=_blank}.
```suggestion
Puedes leer más acerca de otros middlewares en [Guía de Usuario Avanzado: Middleware Avanzado](../advanced/middleware.md){.internal-link target=_blank}.
```

2021-12-30 13:58 UTC, bezaca commented
> Muy buena traducción, solo algunas recomendaciones
Muchas gracias por tus aportes Israel.

2024-12-30 18:57 UTC, tiangolo commented
This was covered in another PR, so I'll close this one now, thanks for the effort! :cake: :coffee:

2024-12-30 18:57 UTC, closed without merging