Added new article link to list of external links
fastapi/fastapi pull request #3271
Opened 2021-05-21 14:39 UTC by ShahriyarR

2021-05-21 15:22 UTC, ArcLightSlavik requested changes
We have an unwritten rule where new articles go to the bottom of the list, not the top.

2021-05-21 19:34 UTC, ShahriyarR commented
@ArcLightSlavik We love unwritten rules :) Done as requested.

2021-05-22 14:50 UTC, ArcLightSlavik approved these changes

2021-05-25 22:37 UTC, ycd approved these changes

2021-07-21 12:27 UTC, tiangolo commented
Great, thanks for your contribution @ShahriyarR! :coffee:

2021-07-21 12:28 UTC, merged