Note about email validator
fastapi/fastapi pull request #3367
Opened 2021-06-12 20:02 UTC by manlix

I have installed `FastAPI` in standart way as described in chapter [Installation](https://fastapi.tiangolo.com/#installation):

`
$ pip install fastapi
`

But later got error running one of example from chapter [Response Model](https://fastapi.tiangolo.com/tutorial/response-model/) because type `EmailStr` requires installed package `email-validator`.

One example code from this chapter:

```python3
from typing import Optional

from fastapi import FastAPI
from pydantic import BaseModel, EmailStr

app = FastAPI()

class UserIn(BaseModel):
    username: str
    password: str
    email: EmailStr
    full_name: Optional[str] = None

# Don't do this in production!
@app.post("/user/", response_model=UserIn)
async def create_user(user: UserIn):
    return user
```

Got error after running:
```
ImportError: email-validator is not installed, run `pip install pydantic[email]`
```

This PR adding note about required additional package `email-validator` to docs before running this example.

2021-06-16 16:52 UTC, Bluenix2 requested changes

2021-06-16 16:52 UTC, Bluenix2 commented on docs/en/docs/tutorial/response-model.md
> +
Personally I rather see this as a note under the code worded more like:
```suggestion
!!! note
    `EmailStr` uses <a href="https://github.com/JoshData/python-email-validator" class="external-link" target="_blank">`email-validator`</a>, you will have to install this package to use `EmailStr`.

```

2021-06-16 23:05 UTC, Bluenix2 requested changes
This is misleading, now the user is let on to belive that to use `response_model` you need to install `email-validator`.

2022-04-13 21:54 UTC, vrslev commented
I don’t think the instructions belong here. Pydantic uses `email-validator`. Imagine what it would be like if FastAPI would follow and add all remarks from its dependencies 😃

2022-08-26 13:19 UTC, tiangolo commented
Thank you! This was solved recently in another PR.

Given that, I'll close this one now. But thanks for the effort! :cake:

2022-08-26 13:19 UTC, closed without merging