🌐 Add French translation for Concurrency and async / await
fastapi/fastapi pull request #3416
Opened 2021-06-27 22:28 UTC by Smlep

Hey everyone!

Here is the PR to translate the async await doc page section into french.
See the french translation tracking issue [here](https://github.com/tiangolo/fastapi/issues/1972).

Thanks for the reviews👌

2021-07-02 14:56 UTC, rjNemo commented on docs/fr/docs/async.md
> +Si vous utilisez des fonctions ant d'autres bibliothèques qui nécessitent d'être appelées avec `await`, telles que :
```suggestion
Si vous utilisez des fonctions et d'autres bibliothèques qui nécessitent d'être appelées avec `await`, telles que :
```

2021-07-02 14:56 UTC, rjNemo commented on docs/fr/docs/async.md
> +À la place, en étant "asynchrone", une fois terminée, une tâche peut légèrement attendre (quelques microseconds) que l'ordinateur / le programme finisse ce qu'il était en train de faire, et revienne
```suggestion
À la place, en étant "asynchrone", une fois terminée, une tâche peut légèrement attendre (quelques microsecondes) que l'ordinateur / le programme finisse ce qu'il était en train de faire, et revienne récupérer le résultat.
```

2021-07-02 14:56 UTC, rjNemo commented on docs/fr/docs/async.md
> +Puis le seveur 💁 dit "J'ai fini de préparer les burgers" 🍔 en mettant votre numéro sur l'affichage du comptoir, mais vous ne courrez pas immédiatement au moment où votre numéro s'affiche. Vous savez
```suggestion
Puis le serveur 💁 dit "J'ai fini de préparer les burgers" 🍔 en mettant votre numéro sur l'affichage du comptoir, mais vous ne courrez pas immédiatement au moment où votre numéro s'affiche. Vous savez que personne ne volera vos burgers 🍔 car vous avez votre numéro et les autres clients ont le leur.
```

2021-07-02 14:56 UTC, rjNemo commented on docs/fr/docs/async.md
> +C'est donc l'histoire équivalente parrallèle pour les burgers 🍔.
```suggestion
C'est donc l'histoire équivalente parallèle pour les burgers 🍔.
```

2021-07-02 14:56 UTC, rjNemo commented on docs/fr/docs/async.md
> +Mais dans ce cas, si pouviez amener 8 ex-serveurs/cuisiners/devenus-nettoyeurs 👨‍🍳👨‍🍳👨‍🍳👨‍🍳👨‍🍳👨‍🍳👨‍🍳👨‍🍳, et que chacun d'eux (plus vous) pouvait prendre une zone de la maison pour la nettoyer, vous p
```suggestion
Mais dans ce cas, si pouviez amener 8 ex-serveurs/cuisiniers/devenus-nettoyeurs 👨‍🍳👨‍🍳👨‍🍳👨‍🍳👨‍🍳👨‍🍳👨‍🍳👨‍🍳, et que chacun d'eux (plus vous) pouvait prendre une zone de la maison pour la nettoyer, vous pourriez faire tout le travail en parallèle, et finir plus tôt.
```

2021-07-02 14:56 UTC, rjNemo commented on docs/fr/docs/async.md
> +Vous attendez donc que votre crush 😍 finisse son histoire, souriez gentillement et dites que vous allez chercher les burgers ⏸.
```suggestion
Vous attendez donc que votre crush 😍 finisse son histoire, souriez gentiment et dites que vous allez chercher les burgers ⏸.
```

2021-07-02 14:56 UTC, rjNemo commented on docs/fr/docs/async.md
> +Avec **FastAPI** vous pouvez bénéficier de la concurrence mais vous pouvez aussi profiter du parallélisme et mutliprocessing afin de gérer des charges **CPU bound** qui sont récurrentes dans les syst
```suggestion
Avec **FastAPI** vous pouvez bénéficier de la concurrence mais vous pouvez aussi profiter du parallélisme et multiprocessing afin de gérer des charges **CPU bound** qui sont récurrentes dans les systèmes de *Machine Learning*.
```

2021-07-02 14:56 UTC, rjNemo commented on docs/fr/docs/async.md
> +Ça, ajouté au fait que Python soit le langage le plus populaire pour la **Data Science**, le **Machine Learning** et surtout le **Deep Leaning**, font de **FastAPI** un très bon choix pour les APIs d
```suggestion
Ça, ajouté au fait que Python soit le langage le plus populaire pour la **Data Science**, le **Machine Learning** et surtout le **Deep Learning**, font de **FastAPI** un très bon choix pour les APIs de **Data Science** / **Machine Learning**.
```

2021-07-02 19:43 UTC, rjNemo approved these changes

2021-07-16 20:01 UTC, Cajuteq requested changes
I left comments on the section that could be better imo. It is great work overall and the suggested changes may not all be relevant.

2021-08-10 09:09 UTC, Smlep commented
@Cajuteq I've updated the PR according to your suggestions, if everything's fine with you now you can approve the PR.

2021-08-10 14:37 UTC, Cajuteq approved these changes

2021-08-18 13:18 UTC, tiangolo commented
Awesome, thank you @Smlep! 🚀

And thank you for the reviews @Cajuteq and @rjNemo :bow:

2021-08-18 13:19 UTC, merged