🌐 Portuguese translation of Tutorial - Body - Fields
fastapi/fastapi pull request #3420
Opened 2021-06-28 18:00 UTC by ComicShrimp

This PR adds a translation to `body-fileds.md`.

2021-06-28 21:38 UTC, vitumenezes requested changes
Ótima tradução, @ComicShrimp ! Vê se minhas sugestões fazem sentido pra você! Lembrando: são apenas sugestões. Um abraço!

2021-06-28 21:38 UTC, vitumenezes commented on docs/pt/docs/tutorial/body-fields.md
> +Da mesma forma que você pode declarar validações adicionais e metadados nos parâmetros de *função de operações de caminho* com `Query`, `Path` e `Body`, você pode declarar validações e metadados dent
O termo "funções de operações de caminho" me parece estranho no português. Não sei se pode existir uma tradução mais adequada (talvez nem exista).

Sugiro "funções de operações de rota" ou somente "funções de rotas".

Ficaria, então: 

> "Da mesma forma que você pode declarar validações adicionais e metadados nos parâmetros das *funções de rota* [...]"

2021-06-28 21:38 UTC, vitumenezes commented on docs/pt/docs/tutorial/body-fields.md
> +## Importar `Field`
## Importe `Field`

2021-06-28 21:38 UTC, vitumenezes commented on docs/pt/docs/tutorial/body-fields.md
> +Você pode utilizar `Field` com atributos do modelo:
Você pode então utilizar `Field` com atributos do modelo:

2021-06-28 21:38 UTC, vitumenezes commented on docs/pt/docs/tutorial/body-fields.md
> +    Na realidade, `Query`, `Path` e outros que você verá em seguida, criam objetos de subclasses de uma classe `Param` comum, que é ela mesma uma subclasse da classe `FieldInfo` do Pydantic.
Sugestão:

> Na realidade, `Query`, `Path` e outros que você verá em seguida criam objetos de subclasses de uma classe `Param` em comum, que é, ela mesma, uma subclasse da classe `FieldInfo` do Pydantic.

Talvez o "em comum" possa ser removido. É um detalhe mais técnico (saber se é em comum ou é apenas comum). A tradução dá essa margem, creio eu.

2021-06-28 21:38 UTC, vitumenezes commented on docs/pt/docs/tutorial/body-fields.md
> +    `Body` também retorna um objeto de uma subclasse de `FieldInfo` diretamente. E tem outras que você verá mais tarde que são subclasses da classe `Body`.
"retorna objetos"

2021-06-28 21:38 UTC, vitumenezes commented on docs/pt/docs/tutorial/body-fields.md
> +    Lembre-se que quando você importa `Query`, `Path`, e outros de `fastapi`, esse são na realidade funções que retornam classes especiais.
Sugestão:

> Lembre-se que quando você importa `Query`, `Path`, e outros de `fastapi`, são estes na realidade funções que retornam classes especiais.

2021-06-28 21:38 UTC, vitumenezes commented on docs/pt/docs/tutorial/body-fields.md
> +    Note como cada atributo do modelo com um tipo, valor padrão e `Field` possuem a mesma estrutura que parâmetros de *função de operações de caminho*, com `Field` ao invés de `Path`, `Query` e `Body
Mesma sugestão que citei anteriormente sobre "função de operação de caminho"

2021-06-29 01:15 UTC, ComicShrimp commented on docs/pt/docs/tutorial/body-fields.md
> +# Corpo - Campos
Eu decidi por traduzir para corpo por conta de outras ocorrências na documentação traduzida, mais precisamente [aqui](https://fastapi.tiangolo.com/pt/features/?h=corpo#baseado-em-padroes-abertos). Desde modo, preferi manter a consistência.

2021-06-29 01:15 UTC, ComicShrimp commented on docs/pt/docs/tutorial/body-fields.md
> +Da mesma forma que você pode declarar validações adicionais e metadados nos parâmetros de *função de operações de caminho* com `Query`, `Path` e `Body`, você pode declarar validações e metadados dent
Concordo que a tradução ficou estranha."funções de operações de rota" fica mais completo, em minha opinião, a versão reduzida pode levar a alguma confusão no entendimento.
Irei fazer a alteração, obrigado pela sugestão !!!

2021-06-29 01:18 UTC, ComicShrimp commented on docs/pt/docs/tutorial/body-fields.md
> +    `Body` também retorna um objeto de uma subclasse de `FieldInfo` diretamente. E tem outras que você verá mais tarde que são subclasses da classe `Body`.
Obrigado pela sugestão, irei fazer a alteração !

2021-06-29 12:09 UTC, ComicShrimp commented on docs/pt/docs/tutorial/body-fields.md
> +    Na realidade, `Query`, `Path` e outros que você verá em seguida, criam objetos de subclasses de uma classe `Param` comum, que é ela mesma uma subclasse da classe `FieldInfo` do Pydantic.
Preferi por deixar o em comum, pois fica mais idêntico com a documentação original, tirando um pouco a minha interpretação. Concordo que possui essa margem de interpretação, mas creio que esteja mais atrelado a documentação em inglês mesmo.

2021-06-29 18:05 UTC, vitumenezes commented on docs/pt/docs/tutorial/body-fields.md
> +# Corpo - Campos
Ótimo! Não tinha visto.

2021-06-29 18:11 UTC, Kludex commented on docs/pt/docs/tutorial/body-fields.md
> +# Corpo - Campos
You can mention those kinds of decisions on #1211 and ping the author of that PR, so they can update the conventions for the language.

2021-06-30 18:09 UTC, KomeilParseh approved these changes

2021-06-30 19:33 UTC, ComicShrimp commented on docs/pt/docs/tutorial/body-fields.md
> +# Corpo - Campos
Thanks for the advice @Kludex !!!. I wroted on the issue about this convention, now everyone can discuss about this convention. 👍🏼

2021-06-30 19:57 UTC, cassiobotaro approved these changes

2021-06-30 20:12 UTC, vitumenezes approved these changes

2021-07-02 13:51 UTC, lsglucas approved these changes

2021-07-02 14:51 UTC, tiangolo commented
Awesome, thanks @ComicShrimp! :rocket: 

And thanks for the reviews @Kludex, @cassiobotaro, @vitumenezes, @lsglucas, @KomeilParseh! :tada: :coffee:

2021-07-02 15:00 UTC, merged