Add French translation for Histoire, conception et avenir
fastapi/fastapi pull request #3451
Opened 2021-07-02 15:21 UTC by rjNemo

2021-07-02 16:37 UTC, Smlep requested changes

2021-07-02 16:37 UTC, Smlep commented on docs/fr/mkdocs.yml
> +- history-design-future.md
In the English doc, `history-design-future` comes between `alternatives.md` and `external-links.md`.

2021-07-02 16:37 UTC, Smlep commented on docs/fr/docs/history-design-future.md
> +Voici un peu bout de cette histoire.
```suggestion
Voici un petit bout de cette histoire.
```

2021-07-02 16:37 UTC, Smlep commented on docs/fr/docs/history-design-future.md
> +Mais à un moment donné, il n'y avait pas d'autre option que de créer quelque chose qui offre toutes ces fonctionnalités, en prenant les meilleures idées des outils précédents, et en les combinant de
The french name for Python's `type hints` is `annotations de type`.

See the Python's french doc.

2021-07-02 16:37 UTC, Smlep commented on docs/fr/docs/history-design-future.md
> +Par exemple, il était clair que l'idéal était de se baser sur les indices de type Python standard.
```suggestion
Par exemple, il était clair que l'idéal était de se baser sur les annotations de type Python standard.
```

See the explanation from the previous comment.

2021-07-02 16:37 UTC, Smlep commented on docs/fr/docs/history-design-future.md
> +Elle a été préférée aux autres solutions précédentes parce qu'elle convient mieux à de nombreux cas d'utilisation.
```suggestion
Elle a été préférée aux solutions précédentes parce qu'elle convient mieux à de nombreux cas d'utilisation.
```
or 
```suggestion
Elle a été préférée aux autres solutions parce qu'elle convient mieux à de nombreux cas d'utilisation.
```

2021-07-02 18:57 UTC, Smlep approved these changes

2022-07-06 23:17 UTC, arthurio approved these changes
Très bonne traduction! Just couple of suggestions/questions.

2022-07-06 23:17 UTC, arthurio commented on docs/fr/docs/history-design-future.md
> +Je crée des API avec des exigences complexes depuis plusieurs années (Machine Learning, systèmes distribués, jobs asynchrones, bases de données NoSQL, etc), en dirigeant plusieurs équipes de développ
Do we use the plural form in french for API? ¯\_(ツ)_/¯ 

```suggestion
Je crée des APIs avec des exigences complexes depuis plusieurs années (Machine Learning, systèmes distribués, jobs asynchrones, bases de données NoSQL, etc), en dirigeant plusieurs équipes de développeurs.
```

2022-07-06 23:17 UTC, arthurio commented on docs/fr/docs/history-design-future.md
> +Ainsi, avant même de commencer à coder **FastAPI**, j'ai passé plusieurs mois à étudier les spécifications d'OpenAPI, JSON Schema, OAuth2, etc. Comprendre leurs relations, leurs chevauchements et leu
chevauchement is correct but sounds a bit weird, WDYT?

```suggestion
Ainsi, avant même de commencer à coder **FastAPI**, j'ai passé plusieurs mois à étudier les spécifications d'OpenAPI, JSON Schema, OAuth2, etc. Comprendre leurs relations, leurs similarités et leurs différences.
```

2022-07-06 23:17 UTC, arthurio commented on docs/fr/docs/history-design-future.md
> +D'après le dernier <a href="https://www.jetbrains.com/research/python-developers-survey-2018/#development-tools" class="external-link" target="_blank">Python Developer Survey</a>, cela couvre environ
Should we translate the Survey title?

```suggestion
D'après la dernière <a href="https://www.jetbrains.com/research/python-developers-survey-2018/#development-tools" class="external-link" target="_blank">Enquête Développeurs Python</a>, cela couvre environ 80% des utilisateurs.
```

2022-07-07 06:40 UTC, rjNemo commented on docs/fr/docs/history-design-future.md
> +Je crée des API avec des exigences complexes depuis plusieurs années (Machine Learning, systèmes distribués, jobs asynchrones, bases de données NoSQL, etc), en dirigeant plusieurs équipes de développ
I don't think so.

2022-08-18 16:01 UTC, tiangolo commented
Awesome, thanks @rjNemo! :cake: 

And thanks for the reviews @arthurio and @Smlep! :coffee:

2022-08-18 16:01 UTC, merged