Add Portuguese translation of Tutorial-Security-Index
fastapi/fastapi pull request #3507
Opened 2021-07-09 03:18 UTC by oandersonmagalhaes

This PR translates the tutorial/security/index.md and add this page to the mkdocs.yml file.

2021-07-12 16:07 UTC, vitumenezes requested changes
Olá, Anderson. Meus parabéns pela tradução!

Sugeri algumas mudanças e gostaria de saber se faz sentido pra você!

Ah, uma outra coisa. É importante comentar todas as traduções para o Português dentro da issue específica para documentação. Esta aqui: #1211 
Desta forma fica tudo centralizado. Então, vai lá e comenta a tua contribuição para que o pessoal possa fazer a review e, consequentemente, aprovar!

2021-07-12 16:07 UTC, vitumenezes commented on docs/pt/docs/tutorial/security/index.md
> +No próximo capítulo você ira ver como adicionar segurança à sua API usando essas ferramentas disponibilizadas por **FastAPI**.
Nos próximos capítulos você ira ver como adicionar segurança à sua API usando essas ferramentas disponibilizadas pelo **FastAPI**.

2021-07-12 16:07 UTC, vitumenezes commented on docs/pt/docs/tutorial/security/index.md
> +E você irá ver também como pegar isso integrado automaticamente dentro do sistema de documentação interativo.
E você irá ver também como isso é automaticamente integrado dentro do sistema de documentação interativo.

2021-07-14 18:14 UTC, oandersonmagalhaes commented on docs/pt/docs/tutorial/security/index.md
> +Em vários frameworks e sistemas só implementam segurança e autenticação com muito esforço e código (em muitos casos isso pode ser 50% ou mais de todo o código escrito).
> Olá, Anderson. Meus parabéns pela tradução!
> 
> Sugeri algumas mudanças e gostaria de saber se faz sentido pra você!
> 
> Ah, uma outra coisa. É importante comentar todas as traduções para o Português dentro da issue específica para documentação. Esta aqui: #1211
> Desta forma fica tudo centralizado. Então, vai lá e comenta a tua contribuição para que o pessoal possa fazer a review e, consequentemente, aprovar!

Olá, Victor, obrigado.

Fiz as mudanças que você sugeriu, faziam sentido.

Também comentei na #1211 

Obrigado! :smile:

2021-07-15 12:39 UTC, izaguerreiro commented on docs/pt/docs/tutorial/security/index.md
> +Ela é apenas uma extensão do OAuth2 especificando algumas coisas que são relativamente ambíguas no OAuth2, tentar fazer mais interoperável.
Acredito que a frase ficaria com mais sentido se alterasse a parte final, ficando assim:

```suggestion
Ela é apenas uma extensão do OAuth2 especificando algumas coisas que são relativamente ambíguas no OAuth2, para tentar torná-lo mais interoperável.
```

2021-07-15 12:39 UTC, izaguerreiro commented on docs/pt/docs/tutorial/security/index.md
> +    * Vários desses flows são apropriados para construir um provedor de autenticação OAuth2 (como Google, Facebook, Twitter, GitHub, etc):
Concordo com o @vitumenezes, seria melhor trocar a palavra `flow` por `fluxo.`

2021-07-15 12:39 UTC, izaguerreiro commented on docs/pt/docs/tutorial/security/index.md
> +Nos próximos capítulos você ira ver como adicionar segurança à sua API usando essas ferramentas disponibilizadas pelo **FastAPI**.
```suggestion
Nos próximos capítulos você irá ver como adicionar segurança à sua API usando essas ferramentas disponibilizadas pelo **FastAPI**.
```

2021-07-15 19:41 UTC, izaguerreiro approved these changes

2021-07-15 20:30 UTC, vitumenezes approved these changes

2021-07-15 22:17 UTC, lsglucas approved these changes

2021-07-15 23:15 UTC, cassiobotaro approved these changes

2021-07-19 12:44 UTC, tiangolo commented
Awesome, thank you @oandersonmagalhaes! :nerd_face: :rocket: 

And thanks for the reviews @izaguerreiro, @cassiobotaro, @vitumenezes, @lsglucas! :bow: :cake:

2021-07-19 12:46 UTC, merged