🌐 Add Spanish traslation for Tutorial - Path Parameters and Numeric Validations
fastapi/fastapi pull request #3540
Opened 2021-07-16 19:21 UTC by JuanBenitezDev

Hi there guys

According to Spanish Translation feature: #1218 
This PR includes the Spanish translation for tutorial/path-params-numeric-validations.md

Thanks!

2021-09-07 15:41 UTC, AdrianDeAnda approved these changes

2021-12-30 02:59 UTC, israteneda requested changes
Buena traducción 🎉  solo algunos pequeños comentarios

2021-12-30 02:59 UTC, israteneda commented on docs/es/docs/tutorial/path-params-numeric-validations.md
> +Pero tu puedes reordenarlos, y tener el attributo sin valor por defecto (el parámetro de query `q`) primero.
```suggestion
Pero tu puedes reordenarlos, y tener el atributo sin valor por defecto (el parámetro de query `q`) primero.
```

2021-12-30 02:59 UTC, israteneda commented on docs/es/docs/tutorial/path-params-numeric-validations.md
> +    Un parámetro de path siempre es requerido ya que tiene que ser parte de la <abbr title="path">*ruta*</abbr>.
```suggestion
    Un parámetro de path siempre es requerido, ya que tiene que ser parte de la <abbr title="path">*ruta*</abbr>.
```

2021-12-30 02:59 UTC, israteneda commented on docs/es/docs/tutorial/path-params-numeric-validations.md
> +Para **FastAPI** esto no importa. FastAPI detectará los parámetros por sus nombres, tipos y declaraciones predeterminadas (`Query`, `Path`, etc), no se preocupa por el orden.
```suggestion
Para **FastAPI** esto no importa. FastAPI detectará los parámetros por sus nombres, tipos y declaraciones predeterminadas (`Query`, `Path`, etc.), no se preocupa por el orden.
```

2021-12-30 02:59 UTC, israteneda commented on docs/es/docs/tutorial/path-params-numeric-validations.md
> +Si quieres declarar el parámetro de query `q` sin un `Query` or cualquier valor por defecto, y el parámetro de path `item_id` usando `Path`, y tenerlos en un orden diferente, Python tiene una sintaxi
```suggestion
Si quieres declarar el parámetro de query `q` sin un `Query` o cualquier valor por defecto, y el parámetro de path `item_id` usando `Path`, y tenerlos en un orden diferente, Python tiene una sintaxis especial para eso.
```

2021-12-30 02:59 UTC, israteneda commented on docs/es/docs/tutorial/path-params-numeric-validations.md
> +Con `Query` y `Path` (y otros que verás más adelante) puedes declarar restriciones para strings, pero también restricciones para números.
```suggestion
Con `Query` y `Path` (y otros que verás más adelante) puedes declarar restricciones para strings, pero también restricciones para números.
```

2021-12-30 02:59 UTC, israteneda commented on docs/es/docs/tutorial/path-params-numeric-validations.md
> +    Estas funciones estan allí (en vez de usar las clases directamente) para que tu editor no marque errores por sus tipos.
```suggestion
    Estas funciones están allí (en vez de emplear las clases directamente) para que tu editor no marque errores por sus tipos.
```

2021-12-30 02:59 UTC, israteneda commented on docs/es/docs/tutorial/path-params-numeric-validations.md
> +    De esta manera puedes usar tu editor y herramientas para codificar sin tener que agregar configuraciones especiales para ignorar esos errores.
```suggestion
    De esta manera puedes utilizar tu editor y herramientas para codificar sin tener que agregar configuraciones especiales para ignorar esos errores.
```

2021-12-30 02:59 UTC, israteneda commented on docs/es/docs/tutorial/path-params-numeric-validations.md
> +Pero tu puedes reordenarlos, y tener el attributo sin valor por defecto (el parámetro de query `q`) primero.
```suggestion
Pero tú puedes reordenarlos, y tener el attributo sin valor por defecto (el parámetro de query `q`) primero.
```

2024-01-15 15:24 UTC, tiangolo commented
As this PR had requested changes to be applied but has been inactive for a while, it's now going to be closed. But if there's anyone interested, feel free to create a new PR.

2024-01-15 15:24 UTC, closed without merging