Add Russian translation for Tutorial Index and First Steps
fastapi/fastapi pull request #3562
Opened 2021-07-20 13:50 UTC by solomein-sv

#1362

2021-07-21 12:48 UTC, tiangolo commented
Awesome! Thanks for the contribution! :bow: 

It's probably better to separate both files in different PRs, that will make it easier for others to review them. Thanks!

2021-07-21 13:26 UTC, solomein-sv commented
@tiangolo , thanks. I'll keep that in mind.

2021-07-30 06:32 UTC, kunansy requested changes

2021-07-30 06:32 UTC, kunansy commented on docs/ru/docs/tutorial/first-steps.md
> +Это строка отображает URL, по которому доступно приложение, на вашей локальной машине.
The second comma is unnecessary.

2021-07-30 06:32 UTC, kunansy commented on docs/ru/docs/tutorial/first-steps.md
> +В этом случае, она описывает атрибуты JSON и их типы, и т.п.
The first comma is unnecessary, «в этом случае» it not a discursive construction.

2021-07-30 06:32 UTC, kunansy commented on docs/ru/docs/tutorial/first-steps.md
> +В данном случае, <a href="https://github.com/OAI/OpenAPI-Specification" class="external-link" target="_blank">OpenAPI</a> - это спецификация, которая диктует, как определить схему вашего API.
The first comma is unnecessary, «в данном случае» it not a discursive construction.

2021-07-30 06:32 UTC, kunansy commented on docs/ru/docs/tutorial/first-steps.md
> +Схема OpenAPI необходима для работы двух, включенных в поставку, систем интерактивной документации.
All commas are unnecessary, because the participle is behind the main word.

2021-07-30 06:32 UTC, kunansy commented on docs/ru/docs/tutorial/first-steps.md
> +    Класс `FastAPI` наследует напрямую от `Starlette`.
Наследует**ся** or унаследован, that is passive voice.

2021-07-30 06:32 UTC, kunansy commented on docs/ru/docs/tutorial/first-steps.md
> +    Поэтому, чере `FastAPI` вам также доступны и все возможности <a href="https://www.starlette.io/" class="external-link" target="_blank">Starlette</a>.
Чере**з**.

2021-07-30 06:32 UTC, kunansy commented on docs/ru/docs/tutorial/first-steps.md
> +Если вы создатите приложение вот так:
Созда**д**ите.

2021-07-30 06:32 UTC, kunansy commented on docs/ru/docs/tutorial/first-steps.md
> +"Путь" в данном случае означает часть URL начинающуюся с первого `/` (прим.пер.: после имени хоста).
...часть URL**,** начинающуюся...

2021-07-30 06:32 UTC, kunansy commented on docs/ru/docs/tutorial/first-steps.md
> +В процессе построения API, "путь" - это основной способ разделить "проблемы" и "ресурсы".
The comma is unnecessary.

2021-07-30 06:32 UTC, kunansy commented on docs/ru/docs/tutorial/first-steps.md
> +Вы также можете определить ее как обычную функцию вместо `async def`:
...функцию**,** вместо...

2021-07-30 07:50 UTC, solomein-sv commented on docs/ru/docs/tutorial/first-steps.md
> +Схема OpenAPI необходима для работы двух, включенных в поставку, систем интерактивной документации.
перенес оборот в конец предложения:
Схема OpenAPI необходима для работы двух систем интерактивной документации, включенных в поставку.

2021-07-30 08:00 UTC, solomein-sv commented on docs/ru/docs/tutorial/first-steps.md
> +Вы также можете определить ее как обычную функцию вместо `async def`:
почему? можно "пруф"?
http://new.gramota.ru/spravka/punctum?layout=item&id=58_287 -- тут пишут, что не надо.

2021-07-30 08:01 UTC, solomein-sv reviewed
@kunansy , thank you for the proofreading and corrections

2021-07-30 10:10 UTC, kunansy commented on docs/ru/docs/tutorial/first-steps.md
> +Вы также можете определить ее как обычную функцию вместо `async def`:
You are right, that is recommended rule, not mandatory.

The page you link contains this: «...рекомендация обособлять конструкцию с предлогом «вместо»...»  

http://new.gramota.ru/spravka/punctum?layout=item&id=58_287#:~:text=%D0%AE.,%D0%BA.

2021-07-30 10:47 UTC, solomein-sv commented on docs/ru/docs/tutorial/first-steps.md
> +Вы также можете определить ее как обычную функцию вместо `async def`:
thank you

2021-08-03 09:36 UTC, mrparalon reviewed
Короткие предложения проще читаются. Больше шансов, что новичок дочитает до конца и попробует

2021-08-03 09:36 UTC, mrparalon commented on docs/ru/docs/tutorial/index.md
> +Набор кода в редакторе демонстрирует преимущества FastAPI, вы видите, как мало кода вам нужно писать, видите все проверки типов, автозаполнение и т.д.
```suggestion
Набирайте код в редакторе, чтобы увидеть преимущества FastAPI. Вы увидите, как мало кода вам нужно писать, все проверки типов, автозаполнение и т.д.
```

2021-08-03 09:36 UTC, mrparalon commented on docs/ru/docs/tutorial/index.md
> +В рамках данного руководства, возможно, вы захотите установить все необязательные зависимости и возможности
```suggestion
Чтобы пройти руководство, установите все необязательные зависимости и возможности
```

2021-08-03 09:36 UTC, mrparalon commented on docs/ru/docs/tutorial/index.md
> +...которые включают `uvicorn`, используемый в качестве сервера, который запускает ваш код.
```suggestion
...которые включают `uvicorn`. Это сервер, который запускает ваш код.
```

2021-08-03 09:36 UTC, mrparalon commented on docs/ru/docs/tutorial/index.md
> +    Для того, чтобы запустить ваше приложение в продуктовой среде, вам необходимо выполнить команды (скорее всего, единожды):
```suggestion
    Чтобы запустить ваше приложение в продуктовой среде, выполните команды:
```

2021-08-03 09:36 UTC, mrparalon commented on docs/ru/docs/tutorial/index.md
> +    А также необходимо установить `uvicorn` в качестве сервера:
```suggestion
    Установите `uvicorn` в качестве сервера:
```

2021-08-03 09:36 UTC, mrparalon commented on docs/ru/docs/tutorial/index.md
> +Также есть **Расширенное руководство пользователя**, которое вы можете изучить после прохождения данного **Руководства пользователя**.
```suggestion
Вы можете изучить **Расширенное руководство пользователя** прохождения этого **Руководства пользователя**.
```

2021-08-03 09:36 UTC, mrparalon commented on docs/ru/docs/tutorial/index.md
> +Руководство разработано таким образом, чтобы вы могли создать полное приложение, используя только **Руководство пользователя**, а затем расширять его, в зависимости от ваших потребностей, используя н
```suggestion
С помощью только **Руководство пользователя**  вы создадите полноценное приложение. Расширить приложение под потребности можно идеями из **Расширенного руководства пользователя**.
```

2021-08-03 09:36 UTC, mrparalon commented on docs/ru/docs/tutorial/index.md
> +Каждый следующий раздел основывается на предыдущих, но при этом разделы структурированы по отдельным темам, так что можно перейти непосредственно к разделу для решения ваших конкретных потребностей A
```suggestion
Каждый следующий раздел основывается на предыдущих. При этом разделы структурированы по отдельным темам, так что можно перейти непосредственно к разделу для решения ваших конкретных потребностей API.
```

2021-08-05 10:56 UTC, solomein-sv commented on docs/ru/docs/tutorial/index.md
> +Также есть **Расширенное руководство пользователя**, которое вы можете изучить после прохождения данного **Руководства пользователя**.
может все-таки оставить "после":
Вы можете изучить **Расширенное руководство пользователя** после прохождения этого **Руководства пользователя**.
?

2021-08-05 10:58 UTC, solomein-sv commented on docs/ru/docs/tutorial/index.md
> +Руководство разработано таким образом, чтобы вы могли создать полное приложение, используя только **Руководство пользователя**, а затем расширять его, в зависимости от ваших потребностей, используя н
Тогда падеж надо изменить: "С помощью только **Руководства...". Или "Используя только **Руководство...".

2021-08-06 05:52 UTC, mrparalon commented on docs/ru/docs/tutorial/index.md
> +Руководство разработано таким образом, чтобы вы могли создать полное приложение, используя только **Руководство пользователя**, а затем расширять его, в зависимости от ваших потребностей, используя н
Изменил падеж

2021-08-06 05:53 UTC, mrparalon commented on docs/ru/docs/tutorial/index.md
> +Также есть **Расширенное руководство пользователя**, которое вы можете изучить после прохождения данного **Руководства пользователя**.
Да, случайно пропустил

2021-10-13 08:25 UTC, solomein-sv commented
@dukkee could you review? by the way, you are the contributor already, do you want to continue translating?

2021-10-13 08:33 UTC, solomein-sv reviewed
fixed

2023-06-26 18:07 UTC, tiangolo commented
It seems this was translated at some point in another PR. So I'll close this one, but thanks for the effort! ☕

2023-06-26 18:07 UTC, closed without merging