Translating index.md and alternatives.md
fastapi/fastapi pull request #3625
Opened 2021-07-29 14:33 UTC by pace-noge

Sorry, forgot to do pull request foreach page.

2021-08-18 13:53 UTC, tiangolo commented
Awesome! Thanks for your contribution. 🚀

These translations depend mainly on having more people that speak the language review them, once I have two reviews approving a translation PR I can merge it.

I just created a new issue to track these translations, you can comment there and subscribe, and probably also check if there are other PRs by others you could review. 🤓

https://github.com/tiangolo/fastapi/issues/3717


---

Also, please separate the two files into two PRs, that way will be easier for others to review one by one and I'll be able to merge them one by one. 🙏

2021-08-24 02:12 UTC, siarie requested changes
Well, I'm not advance in english. But, I hope my review can make the translation much better.

I haven't fully reviewed the alternatives page yet. but, i think it's look good.

---
huh.. I forgot to save the review...

2021-08-24 02:21 UTC, siarie requested changes

2021-08-24 02:21 UTC, siarie commented on docs/id/docs/alternatives.md
> +Apa yang menginspirasi **FastAPI**, bagaimana bila dibandingkan dengan alternatif lain dan apa yang dapat kita pelajari dari sana.
`kita pelajari`?. how about `dipelajari`?

2021-08-24 02:21 UTC, siarie commented on docs/id/docs/alternatives.md
> +Django dibuat untuk menghasilkan HTML di backend, bukan untuk membuat API yang digunakan oleh frontend modern (seperti React, Vue.js, dan Angular) atau oleh sistem lain (seperti <abbr title="Internet
```diff
- (seperti <abbr title="Internet of Things">IoT</abbr > perangkat)
+ (seperti perangkat <abbr title="Internet of Things">IoT</abbr >)
```

2021-08-24 02:21 UTC, siarie commented on docs/id/docs/alternatives.md
> +Pemisahan bagian-bagian ini, dan menjadi "kerangka mikro" yang dapat diperluas untuk mencakup apa yang dibutuhkan adalah fitur utama yang ingin saya pertahankan.
See line 41. It uses `microframework`, but it uses `kerangka mikro`

2021-08-24 02:21 UTC, siarie commented on docs/id/docs/index.md
> +FastAPI adalah kerangka kerja web yang moderen, kencang (ber-performa tinggi), untuk membuat antar muka pemrograman aplikasi dengan Python 3.6+ berdasarkan standar petunjuk tipe Python.
`moderen` it must be `modern`

2021-08-24 02:21 UTC, siarie commented on docs/id/docs/index.md
> +Perintah `uvicorn main:app` di dasarkan pada:
I think the word `merujuk` is more suitable than `di dasarkan`

2021-08-24 02:21 UTC, siarie commented on docs/id/docs/index.md
> +### Peningkatan Dokumentasi API Interktif
Typo `Interktif`

2021-08-24 02:21 UTC, siarie commented on docs/id/docs/index.md
> +"_Apabila anda berencana mempelajari salah satu **Kerangka Moderen** untuk membuat REST Pemrograman Antarmuka Aplikasi, cobalah **FastAPI** [...] cepat, mudah digunakan dan mudah dipelajari [...]_"
`**Kerangka Moderen**` typo again.

2021-08-24 02:21 UTC, siarie commented on docs/id/docs/index.md
> +Anda melakukan itu menggunakan tipe standar Python yang moderen.
typo again `moderen`

2021-08-29 00:07 UTC, closed without merging