Add French translation for `deployment/versions.md`
fastapi/fastapi pull request #3690
Opened 2021-08-12 08:15 UTC by rjNemo

🤗 

Here is the PR to translate the deployment intro.
See the french translation tracking issue [here](https://github.com/tiangolo/fastapi/issues/1972).

Thanks for the reviews

2021-09-12 18:31 UTC, Smlep requested changes

2021-09-12 18:31 UTC, Smlep commented on docs/fr/docs/deployment/versions.md
> +!!! tip
```suggestion
!!! tip "Astuce"
```

2021-09-12 18:31 UTC, Smlep commented on docs/fr/docs/deployment/versions.md
> +!!! tip
```suggestion
!!! tip "Astuce"
```

2021-09-12 18:31 UTC, Smlep commented on docs/fr/docs/deployment/versions.md
> +internal-link target=_blank}
The linebreak breaks the link, see the built [docs](https://61220d5a3aa06f8654ae3335--fastapi.netlify.app/fr/deployment/versions/#mise-a-jour-des-versions-fastapi), the link does not work

2021-09-12 18:31 UTC, Smlep commented on docs/fr/docs/deployment/versions.md
> +de `1.0.0`) sont toujours compatibles avec FastAPI.
```suggestion
de `1.0.0`) sont toujours compatibles avec **FastAPI**.
```

2021-09-12 20:01 UTC, Smlep approved these changes

2022-10-12 07:01 UTC, axel584 approved these changes
J'aurai peut-être utilisé le terme "figer une version" plutôt que "épingler une version"... Mais c'est un avis personnel.

2022-10-31 17:34 UTC, tiangolo commented
Great, thanks @rjNemo! :cookie: 

And thanks for the reviews @axel584 and @Smlep! :bow:

2022-10-31 17:39 UTC, merged