🌐 Add French translation for `deployment/https.md`
fastapi/fastapi pull request #3691
Opened 2021-08-12 10:56 UTC by rjNemo

🤗 

Here is the PR to translate the deployment https.
See the french translation tracking issue [here](https://github.com/tiangolo/fastapi/issues/1972).

Thanks for the reviews

2021-09-12 18:40 UTC, Smlep requested changes

2021-09-12 18:40 UTC, Smlep commented on docs/fr/mkdocs.yml
> +- Deploiement:
```suggestion
- Déploiement:
```

In your other PRs you use `Déploiement`

2021-09-12 18:40 UTC, Smlep commented on docs/fr/docs/deployment/https.md
> +Le processus d'acquisition d'un de ces certificats était auparavant lourd, nécessitait pas mal de paperasse et les certificats étaient assez chers.
```suggestion
Le processus d'acquisition d'un de ces certificats était auparavant lourd, nécessitait pas mal de paperasses et les certificats étaient assez chers.
```

2021-09-12 18:48 UTC, rjNemo commented on docs/fr/mkdocs.yml
> +- Deploiement:
Nice catch

2021-09-12 20:02 UTC, Smlep approved these changes

2022-10-09 20:12 UTC, axel584 commented
@rjNemo : L'expression `une tierce partie` me semble un peu étrange. En recherchant un peu, j'ai trouvé :  "Autorité de Certification" et "tiers de confiance" (j'ai aussi trouvé "une partie tierce", mais ça me semble toujours assez vague).

Pour la dernière phrase, je trouve que ça fait redondance avec l'avant dernière phrase, je l'aurai tourné ainsi : 

`L'automatisation de l'acquisition et du renouvellement de ces certificats permet de disposer d'un HTTPS sécurisé, gratuit et pérenne.`

Ce sont des suggestions, si tu préfères garder tes formulations, dis le moi et je validerai ta PR.

2022-10-13 15:19 UTC, axel584 approved these changes
L'expression `une tierce partie` me semble un peu étrange. En recherchant un peu, j'ai trouvé :  "Autorité de Certification" et "tiers de confiance" (j'ai aussi trouvé "une partie tierce", mais ça me semble toujours assez vague).

Pour la dernière phrase, je trouve que ça fait redondance avec l'avant dernière phrase, je l'aurai tourné ainsi : 

`L'automatisation de l'acquisition et du renouvellement de ces certificats permet de disposer d'un HTTPS sécurisé, gratuit et pérenne.`

2022-10-31 17:39 UTC, tiangolo commented
Great, thank you @rjNemo! :cake: 

And thanks for the reviews @Smlep and @axel584! :bow: :bow:

2022-10-31 17:45 UTC, merged