🌐 Add French translation for `deployment/deta.md`
fastapi/fastapi pull request #3692
Opened 2021-08-12 11:36 UTC by rjNemo

🤗 

Here is the PR to translate the deployment on deta.
See the french translation tracking issue [here](https://github.com/tiangolo/fastapi/issues/1972).

Thanks for the reviews

2021-09-12 19:40 UTC, Smlep requested changes

2021-09-12 19:40 UTC, Smlep commented on docs/fr/docs/deployment/deta.md
> +!!! tip
```suggestion
!!! tip "Astuce"
```

2021-09-12 19:40 UTC, Smlep commented on docs/fr/docs/deployment/deta.md
> +!!! tip
```suggestion
!!! tip "Astuce"
```

2021-09-12 19:40 UTC, Smlep commented on docs/fr/docs/deployment/deta.md
> +!!! tip
```suggestion
!!! tip "Astuce"
```

2021-09-12 19:40 UTC, Smlep commented on docs/fr/docs/deployment/deta.md
> +Vous pouvez également les modifier et les réécouter.
```suggestion
Vous pouvez également les modifier et les rejouer.
```
or 
```suggestion
Vous pouvez également les modifier et les relancer.
```

2021-09-12 20:03 UTC, Smlep approved these changes

2022-10-10 17:10 UTC, axel584 approved these changes

2022-10-31 17:53 UTC, tiangolo commented
Great, thanks @rjNemo! :cake: 

And thanks for the reviews @axel584 and @Smlep! :coffee:

2022-10-31 18:07 UTC, merged