🌐 Add French translation for `deployment/docker.md`
fastapi/fastapi pull request #3694
Opened 2021-08-12 15:09 UTC by rjNemo

🤗 

Here is the PR to translate the manual deployment.
See the french translation tracking issue [here](https://github.com/tiangolo/fastapi/issues/1972).

Thanks for the reviews

2021-08-12 15:23 UTC, yezz123 approved these changes

2021-08-21 11:13 UTC, Smlep commented on docs/fr/docs/deployment/docker.md
> +## Créez le code **FastAPI**.
```suggestion
## Créer le code **FastAPI**.
```

Your other sections names use "infinitif", such as `## Créer un Dockerfile`

2021-08-21 11:14 UTC, Smlep commented on docs/fr/docs/deployment/docker.md
> +## Vérifiez
```suggestion
## Vérifier
```

same reason as for the other section name

2021-08-21 11:14 UTC, Smlep commented on docs/fr/docs/deployment/docker.md
> +* Exécuter un conteneur basé sur votre image :
```suggestion
* Exécutez un conteneur basé sur votre image :
```

2021-08-21 11:19 UTC, Smlep requested changes

2021-08-21 11:19 UTC, Smlep commented on docs/fr/docs/deployment/docker.md
> +Vous devriez pouvoir accéder via l'URL de votre conteneur Docker, par exemple : <a href="http://192.168.99.100/items/5?q=somequery" class="external-link" target="_blank">http://192.168.99.100/items/5
```suggestion
Vous devriez pouvoir accéder à votre application via l'URL de votre conteneur Docker, par exemple : <a href="http://192.168.99.100/items/5?q=somequery" class="external-link" target="_blank">http://192.168.99.100/items/5?q=somequery</a> ou <a href="http://127.0.0.1/items/5?q=somequery" class="external-link" target="_blank">http://127.0.0.1/items/5?q=somequery</a> (ou équivalent, en utilisant votre hôte Docker).
```

2021-08-21 11:19 UTC, Smlep commented on docs/fr/docs/deployment/docker.md
> +Il est également intégré à Docker. Ainsi, vous pouvez déclarer vos domaines dans les configurations de chaque application et faire en sorte qu'elle lise ces configurations, génère les certificats HTT
```suggestion
Il est également intégré à Docker. Ainsi, vous pouvez déclarer vos domaines dans les configurations de chaque application et faire en sorte qu'elles lisent ces configurations, génèrent les certificats HTTPS et servent via HTTPS à votre application automatiquement, sans nécessiter aucune modification de leurs configurations.
```

2021-08-21 11:19 UTC, Smlep commented on docs/fr/docs/deployment/docker.md
> +Il est conçu pour être intégré à ce cluster Docker Swarm avec Traefik et HTTPS décrit ci-dessus.
```suggestion
Le génerateur de projet adéquat est conçu pour être intégré à ce cluster Docker Swarm avec Traefik et HTTPS décrit ci-dessus.
```

2021-09-12 20:35 UTC, Smlep requested changes

2021-09-12 20:35 UTC, Smlep commented on docs/fr/mkdocs.yml
> +- Deploiement:
```suggestion
- Déploiement:
```

2021-09-12 20:35 UTC, Smlep commented on docs/fr/docs/deployment/docker.md
> +!!! tip
```suggestion
!!! tip "Astuce"
```

2021-09-12 20:35 UTC, Smlep commented on docs/fr/docs/deployment/docker.md
> +* Générez et déployez une application **FastAPI** complète, en utilisant votre cluster Docker Swarm, avec HTTPS, etc. En environ **10 min**.
```suggestion
* Générer et déployer une application **FastAPI** complète, en utilisant votre cluster Docker Swarm, avec HTTPS, etc. En environ **10 min**.
```

2021-09-12 20:35 UTC, Smlep commented on docs/fr/docs/deployment/docker.md
> +Vous disposez maintenant d'un serveur FastAPI optimisé dans un conteneur Docker. Réglé automatiquement pour votre
```suggestion
Vous disposez maintenant d'un serveur FastAPI optimisé dans un conteneur Docker. Configuré automatiquement pour votre 
```

2021-09-12 20:35 UTC, Smlep commented on docs/fr/docs/deployment/docker.md
> +Le projet généré a des instructions pour le déployer et le faire prend encore 2 min.
```suggestion
Le projet généré a des instructions pour le déployer et le faire prend 2 min de plus.
```

2021-09-12 21:21 UTC, Smlep approved these changes

2021-10-05 12:25 UTC, tiangolo commented
Awesome, thank you @rjNemo! :cake: 

And thanks for the reviews @Smlep and @yezz123 :coffee:

2021-10-05 12:27 UTC, merged