🌐 Add German translation for `docs/features.md`
fastapi/fastapi pull request #3699
Opened 2021-08-13 11:46 UTC by mawassk

2021-08-18 13:44 UTC, tiangolo commented
Awesome! Thanks for your contribution. 🚀

These translations depend mainly on having more people that speak the language review them, once I have two reviews approving a translation PR I can merge it.

I just created a new issue to track these translations, you can comment there and subscribe, and probably also check if there are other PRs by others you could review. 🤓

https://github.com/tiangolo/fastapi/issues/3716

2021-08-20 18:29 UTC, d-e-h-i-o approved these changes
Just found this one issue. Otherwise looks great!

2021-08-20 18:29 UTC, d-e-h-i-o commented on docs/de/docs/features.md
> +* **automatische Umsetzung** durch FastAPI.
This could start with a capital letter too, to be more consistent with the other bullet points.

2021-08-28 17:51 UTC, rogerbrinkmann requested changes

2021-08-28 17:51 UTC, rogerbrinkmann commented on docs/de/docs/features.md
> +Sie müssen selten zu der Dokumentation von FastAPI zurückkehren.
Sie müssen selten in die Dokumentation schauen.

2021-08-28 17:51 UTC, rogerbrinkmann commented on docs/de/docs/features.md
> +So kann ihr Editor ihnen helfen:
So kann ihr Editor Sie unterstützen:

2021-08-28 17:51 UTC, rogerbrinkmann commented on docs/de/docs/features.md
> +Sie bekommen Autovervollständigung an Stellen, an dennen Sie vorher dies für nicht möglich gehalten haben. Zum Beispiel der `price` Schlüssel aus einem JSON Datensatz (dieser könnte auch verschachtel
Typo: dennen -> denen
Sie bekommen Autovervollständigung an Stellen, an denen Sie dies vorher nicht für möglich gehalten hätten.

2021-08-28 17:51 UTC, rogerbrinkmann commented on docs/de/docs/features.md
> +Hierdurch werden Sie nie wieder einen falschen Schlüsselnamen benutzen und sparen sich lästige Zeit in Dokumentationen, um beispielsweise herauszufinden ob Sie `username` oder `user_name` als Schlüss
... sparen sich lästiges Suchen in der Dokumentation ...

2021-08-28 17:51 UTC, rogerbrinkmann commented on docs/de/docs/features.md
> +FastAPI nutzt sensible **Standard-Einstellung** für alles, welche aber überall konfiguriert werden können. Alle Parameter können ganz genau an Ihre Bedürfnisse angepasst werden, sodass sie genau die
FastAPI nutzt für alles sensible **Standard-Einstellungen**, welche optional überall konfiguriert werden können.

2021-08-28 17:51 UTC, rogerbrinkmann commented on docs/de/docs/features.md
> +    * Zeichenketten (`str`), mit minimaler und maximaler Länge.
* Zeichenketten (`str`), mit definierter minimaler und maximaler Länge.

2021-08-28 17:51 UTC, rogerbrinkmann commented on docs/de/docs/features.md
> +    * Zahlen (`int`, `float`) mit minimaler und maximaler Größe, etc.
etc -> usw.

2021-08-28 17:51 UTC, rogerbrinkmann commented on docs/de/docs/features.md
> +Unterstützt alle Sicherheitsschemata, die von OpenAPI definiert wurden, hierzu gejören:
Unterstützt alle von OpenAPI definierten Sicherheitsschemata, hierzu gehören:

2021-08-28 17:51 UTC, rogerbrinkmann commented on docs/de/docs/features.md
> +* **OAuth2** (auch mit **JWT Zugriffstokens**). Schauen Sie hierzu dieses Tutorial [OAuth2 mit JWT](tutorial/security/oauth2-jwt.md){.internal-link target=_blank}.
Schauen Sie sich hierzu dieses Tutorial an ...

2021-08-28 17:51 UTC, rogerbrinkmann commented on docs/de/docs/features.md
> +FastAPI bringt ein extrem einfaches, aber extrem mächtiges <abbr title='oft verwendet im Zusammenhang von: Komponenten, Resourcen, Diensten, Dienstanbieter'><strong>Dependency Injection</strong></abb
bringt -> enthält

2021-08-28 17:51 UTC, rogerbrinkmann commented on docs/de/docs/features.md
> +* Alle Abhängigkeiten können Daten von Anfragen erforderb und können **Erweiterungen der Pfadoperations-**Eischränkungen und der automatischen Dokumentation hervornehmen.
Typo: erforderb -> erfordern

2021-08-28 17:51 UTC, rogerbrinkmann commented on docs/de/docs/features.md
> +* Alle Abhängigkeiten können Daten von Anfragen erforderb und können **Erweiterungen der Pfadoperations-**Eischränkungen und der automatischen Dokumentation hervornehmen.
Typo: Pfadoperations -> Pfadoperationen

2021-08-28 17:51 UTC, rogerbrinkmann commented on docs/de/docs/features.md
> +* Alle Abhängigkeiten können Daten von Anfragen erforderb und können **Erweiterungen der Pfadoperations-**Eischränkungen und der automatischen Dokumentation hervornehmen.
Typo: Eischränkungen -> Einschränkungen

2021-08-28 17:51 UTC, rogerbrinkmann commented on docs/de/docs/features.md
> +* Alle Abhängigkeiten können Daten von Anfragen erforderb und können **Erweiterungen der Pfadoperations-**Eischränkungen und der automatischen Dokumentation hervornehmen.
* Alle abhängigen Komponenten könnten Daten von Anfragen, **Erweiterungen der Pfadoperations-**Einschränkungen und der automatisierten Dokumentation benötigen.

2021-08-28 17:51 UTC, rogerbrinkmann commented on docs/de/docs/features.md
> +* Unterstütz komplexe Benutzerauthentifizierungssysteme, mit **Datenbankverbindungen**, etc.
etc. -> usw.

2021-08-28 17:51 UTC, rogerbrinkmann commented on docs/de/docs/features.md
> +* **Keine Kompromisse** mit Datenbanken, Eingängen, etc. Aber einfache Integration mit allen von ihnen..
* **Keine Kompromisse** bei Datenbanken, Eingabemasken, usw. Sondern einfache Integration von allen.

2021-08-28 17:51 UTC, rogerbrinkmann commented on docs/de/docs/features.md
> +### Unlimitierte Erweiterungen
### Unbegrenzte Erweiterungen

2021-08-28 17:51 UTC, rogerbrinkmann commented on docs/de/docs/features.md
> +Oder in anderen Worten, werden sie nicht benötigt: importieren und nutzen Sie den Quellcode, den Sie benötigen.
Oder mit anderen Worten, sie werden nicht benötigt. Importieren und nutzen Sie Quellcode nach Bedarf.

2021-08-28 17:51 UTC, rogerbrinkmann commented on docs/de/docs/features.md
> +**FastAPI** ist vollkommen kompatibel (und basiert auf) <a href="https://www.starlette.io/" class="external-link" target="_blank"><strong>Starlette</strong></a>. Das bedeutet, dass jeder zusätliche S
Typo: zusätliche -> zusätzliche
Das bedeutet, auch ihr eigner Starlett Quellcode funktioniert.

2021-08-28 17:51 UTC, rogerbrinkmann commented on docs/de/docs/features.md
> +`FastAPI` ist eigentlich einer Unterklasse von `Starlette`. Wenn sie also bereits Starlette kennen oder benutzen, können Sie das meiste Ihres Wissen direkt anwenden.
Typo: einer -> eine

2021-08-28 17:51 UTC, rogerbrinkmann commented on docs/de/docs/features.md
> +* Erheblich beeindruckende Performanz. Es ist <a href="https://github.com/encode/starlette#performance" class="external-link" target="_blank">eines der schnellsten Python frameworks, auf Augenhöhe mi
Stark beeindruckende Performanz.

2021-08-28 17:51 UTC, rogerbrinkmann commented on docs/de/docs/features.md
> +* Hintergrundauufgaben im selben Prozess.
Typo: Hintergrundauufgaben -> Hintergrundaufgaben

2021-08-28 17:51 UTC, rogerbrinkmann commented on docs/de/docs/features.md
> +* Events für das Starten und Herunterfahren.
Events -> Ereignisse

2021-08-28 17:51 UTC, rogerbrinkmann commented on docs/de/docs/features.md
> +**FastAPI** ist vollkommen kompatibel (und basiert auf) <a href="https://pydantic-docs.helpmanual.io" class="external-link" target="_blank"><strong>Pydantic</strong></a>. Das bedeutet, dass jeder zus
Das bedeutet, auch jeder zusätzliche Pydantic Quellcode funktioniert.

2021-08-29 09:27 UTC, mawassk commented
Thank you for your feedback @rogerbrinkmann! I updated my PR :rocket:

2021-08-29 12:22 UTC, rogerbrinkmann approved these changes

2021-09-13 16:54 UTC, tiangolo commented
Awesome, thank you @mawassk! :cake: :coffee: 

And thanks for the reviews @rogerbrinkmann and @d-e-h-i-o! :clap:

2021-09-13 17:29 UTC, merged