Remove unnecesarry branch for default empty list
fastapi/fastapi pull request #3724
Opened 2021-08-19 08:30 UTC by EdwardBlair

```python
list(dependencies or [])
```

is identical behaviour to

```python
list(dependencies or []) or []
```

Is it not?

2022-01-09 14:21 UTC, cikay requested changes

2022-01-09 14:21 UTC, cikay commented on fastapi/routing.py
> +        self.dependencies = list(dependencies or [])
`self.dependencies = dependencies or []` this is good enough.

2022-01-09 19:09 UTC, EdwardBlair commented
I disagree

On Sun, 9 Jan 2022 at 14:21, cikay ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In fastapi/routing.py
> <https://github.com/tiangolo/fastapi/pull/3724#discussion_r780787847>:
>
> > @@ -460,7 +460,7 @@ def __init__(
>              ), "A path prefix must not end with '/', as the routes will start with '/'"
>          self.prefix = prefix
>          self.tags: List[str] = tags or []
> -        self.dependencies = list(dependencies or []) or []
> +        self.dependencies = list(dependencies or [])
>
> self.dependencies = dependencies or [] this is good enough.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tiangolo/fastapi/pull/3724#pullrequestreview-847264746>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAB2QODL7DHLMK42L3PTQFLUVGKYFANCNFSM5CNWT4AA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-01-09 19:16 UTC, EdwardBlair commented
self.dependencies was previously a List, I’d argue it’s more ‘safe’ to
explicitly convert the passed param to list than assume its type? (it’s
exposed by a less strict interface). Can make the change if you wish makes
no difference to me any more, I was relying on it being a List as I was
messing around creating shivs for the dependency system but I’ve since
given up.

On Sun, 9 Jan 2022 at 19:09, Edward Blair ***@***.***> wrote:

> I disagree
>
> On Sun, 9 Jan 2022 at 14:21, cikay ***@***.***> wrote:
>
>> ***@***.**** requested changes on this pull request.
>> ------------------------------
>>
>> In fastapi/routing.py
>> <https://github.com/tiangolo/fastapi/pull/3724#discussion_r780787847>:
>>
>> > @@ -460,7 +460,7 @@ def __init__(
>>              ), "A path prefix must not end with '/', as the routes will start with '/'"
>>          self.prefix = prefix
>>          self.tags: List[str] = tags or []
>> -        self.dependencies = list(dependencies or []) or []
>> +        self.dependencies = list(dependencies or [])
>>
>> self.dependencies = dependencies or [] this is good enough.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/tiangolo/fastapi/pull/3724#pullrequestreview-847264746>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AAB2QODL7DHLMK42L3PTQFLUVGKYFANCNFSM5CNWT4AA>
>> .
>> Triage notifications on the go with GitHub Mobile for iOS
>> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
>> or Android
>> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>>
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2022-08-26 09:43 UTC, tiangolo commented
Hey there! It seems this was handled recently in another PR, so I'm gonna close this one. But thanks for the effort! :cake:

2022-08-26 09:43 UTC, closed without merging