Add Portuguese translation for docs/tutorial/query-params.md
fastapi/fastapi pull request #3732
Opened 2021-08-20 00:48 UTC by FelipeSilva93

#1211

2021-10-05 23:47 UTC, cassiobotaro commented on docs/en/mkdocs.yml
> -# Uncomment these 2 lines during development to more easily add highlights
Por que está alterando estas linhas?

2021-10-05 23:48 UTC, cassiobotaro commented on docs/pt/docs/tutorial/path-params.md
> +* Parsing de dados
Análise de dados?

2021-10-07 20:30 UTC, diogoduartec requested changes
**Actually you're translating the wrong page, the correct page is docs/tutorial/path-params.md.**

2023-01-22 02:11 UTC, LorhanSohaky commented
Can we close it? 

related #4775

2023-06-26 22:57 UTC, tiangolo commented
Thanks @LorhanSohaky!

As this was handled in another PR I'll close this one. ☕

2023-06-26 22:57 UTC, closed without merging