🌐 Add Korean translation for `docs/tutorial/request-files.md`
fastapi/fastapi pull request #3743
Opened 2021-08-21 05:40 UTC by NinaHwang

This PR translates tutorial/response-status-code.md in Korean.

2021-09-05 03:46 UTC, hard-coders reviewed
LGTM. It would be best if you used less "띄어쓰기".

e.g.
- `something` 입니다. -> `something`입니다.
- `something` : 설명 -> `something`: 설명

Let me know what you think.

2021-09-05 03:46 UTC, hard-coders commented on docs/ko/docs/tutorial/request-files.md
> +파일들은 “form data”의 형태로 업로드 됩니다.
```suggestion
파일들은 "form data"의 형태로 업로드 됩니다.
```

2021-09-05 03:46 UTC, hard-coders commented on docs/ko/docs/tutorial/request-files.md
> +이것은 전체 내용이 메모리에 저장된다는 것을 의미한다는걸 염두에  두세요. 이는 작은 크기의 파일들에 적합합니다.
```suggestion
이것은 전체 내용이 메모리에 저장된다는 것을 의미한다는걸 염두에 두세요. 이는 작은 크기의 파일들에 적합합니다.
```

2021-09-05 03:46 UTC, hard-coders commented on docs/ko/docs/tutorial/request-files.md
> +## “폼 데이터”란
```suggestion
## "폼 데이터"란
```

2021-09-06 02:43 UTC, NinaHwang commented
@hard-coders  Thank you for the feedback!

2021-09-06 02:48 UTC, hard-coders approved these changes

2021-11-05 09:43 UTC, 0417taehyun requested changes
Bit appreciate of your works and great honor to check it.

Feel free to check my reviews 🚀 

Also, please update (fetch) the file to the latest version.

2021-11-05 09:43 UTC, 0417taehyun commented on docs/ko/docs/tutorial/request-files.md
> +    업로드된 파일들은 "form data"의 형태로 전송되기 때문에 이 작업이 필요합니다.
```suggestion
    업로드된 파일들은 "폼 데이터"의 형태로 전송되기 때문에 이 작업이 필요합니다.
```

> use less English as you can.

Check #2017 .

2021-11-05 09:43 UTC, 0417taehyun commented on docs/ko/docs/tutorial/request-files.md
> +    하지만 `fastapi`로부터 `Query`, `Path`, `File` 등을 임포트 할 때, 이것들은 특별한 클래스들을 반환하는 함수라는 것을 기억하세요.
```suggestion
    하지만 `fastapi`로부터 `Query`, `Path`, `File` 등을 임포트 할 때, 이것들은 특별한 클래스들을 반환하는 함수라는 것을 기억하기 바랍니다.
```

> 비격식체(Informal)인 해요체를 지양하고 격식체(Formal)인 합쇼체를 지향합니다.

Check #2017 .

2021-11-05 09:43 UTC, 0417taehyun commented on docs/ko/docs/tutorial/request-files.md
> +파일들은 "form data"의 형태로 업로드 됩니다.
```suggestion
파일들은 "폼 데이터"의 형태로 업로드 됩니다.
```

2021-11-05 09:43 UTC, 0417taehyun commented on docs/ko/docs/tutorial/request-files.md
> +*경로 동작 함수*의 매개변수를 `bytes` 로 선언하는 경우 **FastAPI**는 파일을 읽고 `bytes` 형태의 내용을 전달합니다.
```suggestion
*경로 작동 함수*의 매개변수를 `bytes` 로 선언하는 경우 **FastAPI**는 파일을 읽고 `bytes` 형태의 내용을 전달합니다.
```

Check *파이썬 공식 한국어 문서에 없는 용어 중 현재 사용하고 있는 용어* in #3167 . **동작** is used to define the movement of living things such as human and **작동** is used to define the movement of machines.

2021-11-05 09:43 UTC, 0417taehyun commented on docs/ko/docs/tutorial/request-files.md
> +이것은 전체 내용이 메모리에 저장된다는 것을 의미한다는걸 염두에 두세요. 이는 작은 크기의 파일들에 적합합니다.
```suggestion
이것은 전체 내용이 메모리에 저장된다는 것을 의미한다는 걸 염두하기 바랍니다. 이는 작은 크기의 파일들에 적합합니다.
```

2021-11-05 09:43 UTC, 0417taehyun commented on docs/ko/docs/tutorial/request-files.md
> +* `file` :  <a href="https://docs.python.org/3/library/tempfile.html#tempfile.SpooledTemporaryFile" class="external-link" target="_blank">`SpooledTemporaryFile`</a> (<a href="https://docs.python.org/
```suggestion
* `file` :  <a href="https://docs.python.org/3/library/tempfile.html#tempfile.SpooledTemporaryFile" class="external-link" target="_blank">`SpooledTemporaryFile`</a> (<a href="https://docs.python.org/3/glossary.html#term-file-like-object" class="external-link" target="_blank">파일류</a> 객체)입니다. 이것은 "파일류" 객체를 필요로하는 다른 라이브러리에 직접적으로 전달할 수 있는 실질적인 파이썬 파일입니다.
```

It was translated as `파일류` in Python official document. Check [파이썬 한국어 번역 가이드라인](https://python.flowdas.com/glossary.html#glossary) and search `file-like`.

2021-11-05 09:43 UTC, 0417taehyun commented on docs/ko/docs/tutorial/request-files.md
> +`UploadFile` 은 다음과 같은 속성(attribute)이 있습니다:
```suggestion
`UploadFile` 은 다음과 같은 어트리뷰트가 있습니다:
```

It was translated as `어트리뷰트` in Python official document. Check [파이썬 한국어 번역 가이드라인](https://python.flowdas.com/glossary.html#glossary) and search `attribute`.

2021-11-05 09:43 UTC, 0417taehyun commented on docs/ko/docs/tutorial/request-files.md
> +예를들어, `async` *경로 동작 함수*의 내부에서 다음과 같은 방식으로 내용을 가져올 수 있습니다:
```suggestion
예를들어, `async` *경로 작동 함수*의 내부에서 다음과 같은 방식으로 내용을 가져올 수 있습니다:
```

2021-11-05 09:43 UTC, 0417taehyun commented on docs/ko/docs/tutorial/request-files.md
> +만약 일반적인 `def` *경로 동작 함수*의 내부라면, 다음과 같이 `UploadFile.file` 에 직접 접근할 수 있습니다:
```suggestion
만약 일반적인 `def` *경로 작동 함수*의 내부라면, 다음과 같이 `UploadFile.file` 에 직접 접근할 수 있습니다:
```

2021-11-05 09:43 UTC, 0417taehyun commented on docs/ko/docs/tutorial/request-files.md
> +!!! note  "`async` 기술 세부사항"
```suggestion
!!! note  "`async` 기술적 세부사항"
```

Check *파이썬 공식 한국어 문서에 없는 용어 중 현재 사용하고 있는 용어* in #3167 .

2021-11-05 09:43 UTC, 0417taehyun commented on docs/ko/docs/tutorial/request-files.md
> +    `async` 메소드들을 사용할 때 **FastAPI**는 스레드풀(treadpool)에서 파일 메소드들을 실행하고 그들을 기다립니다.
```suggestion
    `async` 메소드들을 사용할 때 **FastAPI**는 스레드풀에서 파일 메소드들을 실행하고 그들을 기다립니다.
```

2021-11-05 09:43 UTC, 0417taehyun commented on docs/ko/docs/tutorial/request-files.md
> +!!! note "Starlette 기술 세부사항"
```suggestion
!!! note "Starlette 기술적 세부사항"
```

2021-11-05 09:43 UTC, 0417taehyun commented on docs/ko/docs/tutorial/request-files.md
> +!!! note "기술 세부사항"
```suggestion
!!! note "기술적 세부사항"
```

2021-11-05 09:43 UTC, 0417taehyun commented on docs/ko/docs/tutorial/request-files.md
> +폼 데이터로써 입력 매개변수로 업로드할 파일을 선언할 경우 `File` 을 사용하세요.
```suggestion
폼 데이터로써 입력 매개변수로 업로드할 파일을 선언할 경우 `File` 을 사용하기 바랍니다.
```

2021-11-05 09:43 UTC, 0417taehyun commented on docs/ko/docs/tutorial/request-files.md
> +    **FastAPI**는 개발자인 당신의 편의를 위해 `fastapi.responses` 와 동일한 `starlette.responses` 도 제공합니다. 하지만 대부분의 응답들은 Starlette로부터 직접 제공됩니다.
```suggestion
    **FastAPI**는 개발자의 편의를 위해 `fastapi.responses` 와 동일한 `starlette.responses` 도 제공합니다. 하지만 대부분의 응답들은 Starlette로부터 직접 제공됩니다.
```

2021-11-05 09:43 UTC, 0417taehyun commented on docs/ko/docs/tutorial/request-files.md
> +!!! note "기술 세부사항"
```suggestion
!!! note "기술적 세부사항"
```

2021-11-05 09:43 UTC, 0417taehyun commented on docs/ko/docs/tutorial/request-files.md
> +다수의 파일을 한번에 업로드 할 수 있습니다.
```suggestion
여러 파일을 동시에 업로드 할 수 있습니다.
```

2021-11-05 09:43 UTC, 0417taehyun commented on docs/ko/docs/tutorial/request-files.md
> +이 기능을 사용하기 위해  `bytes` 의 `List` 또는 `UploadFile` 을 선언하세요:
```suggestion
이 기능을 사용하기 위해 , `bytes` 의 `List` 또는 `UploadFile` 를 선언하기 바랍니다:
```

2021-11-05 09:43 UTC, 0417taehyun commented on docs/ko/docs/tutorial/request-files.md
> +!!! note "참고"
I think this `note` section is deprecated in the docs. Please update (fetch) the file to the latest version.

2021-11-05 09:43 UTC, 0417taehyun commented on docs/ko/docs/tutorial/request-files.md
> +    폼의 데이터는 파일이 포함되지 않은 경우 일반적으로 "media type" `application/x-www-form-urlencoded` 을 사용해 인코딩 됩니다.
```suggestion
    폼의 데이터는 파일이 포함되지 않은 경우 일반적으로 "미디어 유형" `application/x-www-form-urlencoded` 을 사용해 인코딩 됩니다.
```

2021-11-05 09:43 UTC, 0417taehyun commented on docs/ko/docs/tutorial/request-files.md
> +    인코딩과 폼 필드에 대해 더 알고싶다면, <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST" class="external-link" target="_blank"><abbr title="Mozilla Developer Network">MDN</abbr> web docs f
```suggestion
    인코딩과 폼 필드에 대해 더 알고싶다면, <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST" class="external-link" target="_blank"><code>POST</code>에 관한<abbr title="Mozilla Developer Network">MDN</abbr>웹 문서</a> 를 참고하기 바랍니다,.
```

2021-11-05 09:43 UTC, 0417taehyun commented on docs/ko/docs/tutorial/request-files.md
> +    다수의 `File` 과 `Form` 매개변수를 한 *경로 동작*에 선언하는 것이 가능하지만, 요청의 본문이 `application/json` 가 아닌 `multipart/form-data` 로 인코딩 되기 때문에 JSON으로 받아야하는 `Body` 필드를 함께 선언할 수는 없습니다.
```suggestion
    다수의 `File` 과 `Form` 매개변수를 한 *경로 작동*에 선언하는 것이 가능하지만, 요청의 본문이 `application/json` 가 아닌 `multipart/form-data` 로 인코딩 되기 때문에 JSON으로 받아야하는 `Body` 필드를 함께 선언할 수는 없습니다.
```

2021-11-28 07:18 UTC, 0417taehyun approved these changes
LGTM 🚀

2021-12-08 15:46 UTC, tiangolo commented
Amazing, thanks @NinaHwang! :bow: :cookie: 

And thanks for the reviews @hard-coders and @0417taehyun! :rocket:

2021-12-08 15:52 UTC, merged