Add ability to set example=Undefined for models
fastapi/fastapi pull request #3770
Opened 2021-08-25 21:54 UTC by four43

Allows models to have a "null" value in output Schema

Fixes #2149

2021-11-03 13:20 UTC, four43 commented
yeah it was up to date but this project is a bit slow to review PRs ;)

2022-11-03 20:42 UTC, tiangolo commented
Thanks for the interest! :coffee:

How different would it be this to setting `example=None`?

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.

2022-11-03 21:01 UTC, four43 commented
Hey @tiangolo - Thanks for stopping by! See the use case in the attached issue that this solves, #2149. This is an example of of "unknown/default" vs. "explicit null".

2024-08-11 18:14 UTC, furiousteabag commented
Hey everyone! What's the status of this fix? Would love to have explicit `null`s in the OpenAPI schema. How can I help?

2025-07-11 14:43 UTC, YuriiMotov requested changes
@four43, thanks for contributing to FastAPI!

I think the general approach of this PR is nice, but it shouldn't be `Undefined`.
I think we should introduce a new value like `ExplicitNone` for this reason.

Also, the approach only works with Pydantic V1 and should be adjusted to work with V2.

What do you think?
Would you like to work on it?

2025-08-11 22:20 UTC, closed without merging