🌐 Add Russian translation for `docs/tutorial/header-params.md`
fastapi/fastapi pull request #3783
Opened 2021-08-28 19:58 UTC by dukkee

#1362

Hey. @TemaSpb, @solomein-sv, @BugLight if you are free, please review :smiley:

2021-09-10 03:36 UTC, solomein-sv approved these changes

2023-04-18 10:31 UTC, Xewus requested changes

2023-04-18 10:31 UTC, Xewus commented on docs/ru/docs/tutorial/header-params.md
> +Кроме того, названия HTTP-заголовков являются регистронезависимыми, поэтому вы можете объявлять их в обычном Python-стиле (который также известен как "змеиная нотация").
```suggestion
Кроме того, названия HTTP-заголовков являются регистронезависимыми, поэтому вы можете объявлять их в обычном Python-стиле (который также известен как  <dfn title="змеиная нотация">"snake_case"</dfn>.

2023-04-18 10:31 UTC, Xewus commented on docs/ru/docs/tutorial/header-params.md
> +!!! warning
```suggestion
!!! warning "Предупреждение"
```

2023-04-18 10:31 UTC, Xewus commented on docs/ru/docs/tutorial/header-params.md
> +!!! info
```suggestion
!!! info "Информация"
```

2023-04-18 10:31 UTC, Xewus commented on docs/ru/docs/tutorial/header-params.md
> +    Перед тем, как устанавливать `convert_underscores` в значение `False`, имейте в виду, что некоторые HTTP-прокси и серверы запрещают использование заголовков со знаками подчеркивания.
```suggestion
    Перед тем, как устанавливать `convert_underscores` в значение `False`, имейте в виду, что некоторые прокси-серверы запрещают использование заголовков со знаками подчеркивания.
```
Я даже загуглил, но с наскока отдельный термин "HTTP-прокси" не попался. Ннесмотря на то, что сам сторонник более развёрнутых пояснений, на кажется, что дополнительные буквы к "прокси-серверу" только усложнят понимание.

2023-04-18 10:31 UTC, Xewus commented on docs/ru/docs/tutorial/header-params.md
> +Возможно получить повторяющиеся заголовки. Это означает один и тот же заголовок с множеством значений.
```suggestion
Есть возможность получать повторяющиеся заголовки. Это означает один и тот же заголовок с множеством значений.
```

2023-04-18 10:31 UTC, Xewus commented on docs/ru/docs/tutorial/header-params.md
> +    Для объявления заголовков вам необходимо использовать `Header`, в противном случае эти параметры будут интерпретироваться как параметры запроса.
```suggestion
    Для объявления заголовков вам необходимо использовать `Header`, в противном случае эти параметры будут интерпретироваться как параметры "тела" запроса.
```

2023-04-19 07:29 UTC, solomein-sv commented on docs/ru/docs/tutorial/header-params.md
> +    Перед тем, как устанавливать `convert_underscores` в значение `False`, имейте в виду, что некоторые HTTP-прокси и серверы запрещают использование заголовков со знаками подчеркивания.
ИМХО здесь подразумевались прокси- и веб-серверы

2023-04-19 07:30 UTC, solomein-sv approved these changes

2023-04-19 16:36 UTC, Xewus commented on docs/ru/docs/tutorial/header-params.md
> +    Перед тем, как устанавливать `convert_underscores` в значение `False`, имейте в виду, что некоторые HTTP-прокси и серверы запрещают использование заголовков со знаками подчеркивания.
Да, Вы правы..

2023-04-19 16:41 UTC, Xewus commented
И страница не внесена в оглавление (`mkdocs.yml`) из-за чего на тестовом сервере она не показывается, то есть нельзя посмотреть её итоговый вид.

2023-06-26 23:47 UTC, tiangolo commented
A small note, I just upgrade the setup for building the docs, so there's no longer necessary to modify the `mkdocs.yml` file. 🎉

2023-06-26 23:55 UTC, tiangolo commented
📝 Docs preview for commit a1c6a2f86daf00205fefa8d0a6f24bb72d4a8275 at: https://649a254ab8e9671a691c1d7f--fastapi.netlify.app

2023-06-27 08:53 UTC, glsglsgls commented on docs/ru/docs/tutorial/header-params.md
> +    Для объявления заголовков вам необходимо использовать `Header`, в противном случае эти параметры будут интерпретироваться как параметры запроса.
Здесь скорее речь про query параметры, которые так и перевели в соответствующей главе.
https://fastapi.tiangolo.com/ru/tutorial/query-params/

Имхо, я бы так же здесь написал - "... будут интерпретироваться как Query параметры", просто чтобы названия в разных главах совпадали

2023-06-27 09:14 UTC, glsglsgls approved these changes

2023-06-27 09:14 UTC, glsglsgls commented on docs/ru/docs/tutorial/header-params.md
> +Если вы взаимодействуете с подобным *обработчиком пути*, отправляя два HTTP-заголовка вроде:
Возможно лучше писать "*операцией пути*" для единообразия

2023-06-27 09:14 UTC, glsglsgls commented on docs/ru/docs/tutorial/header-params.md
> +Возможно получить повторяющиеся заголовки. Это означает один и тот же заголовок с множеством значений.
@Xewus  поддерживаю

2023-06-27 09:14 UTC, glsglsgls commented on docs/ru/docs/tutorial/header-params.md
> +Например, для объявления заголовка `X-Token`, который может появиться больше раза, вы можете написать:
```suggestion
Например, для объявления заголовка `X-Token`, который может появиться больше одного раза, вы можете написать:
```

2023-06-29 21:39 UTC, Xewus commented on docs/ru/docs/tutorial/header-params.md
> +    Для объявления заголовков вам необходимо использовать `Header`, в противном случае эти параметры будут интерпретироваться как параметры запроса.
Это про заголовки запросов - Autorization, Referer, User-Agent и т.п.

2023-06-29 21:41 UTC, Xewus commented on docs/ru/docs/tutorial/header-params.md
> +# Header-параметры
```suggestion
# Заголовки запросов
```

2023-06-29 21:42 UTC, Xewus commented on docs/ru/docs/tutorial/header-params.md
> +Вы можете определить Header-параметры точно так же, как вы определяете `Query`, `Path` и `Cookie`-параметры.
```suggestion
Вы можете определить заголовки запросов точно так же, как вы определяете `Query`, `Path` и `Cookie`-параметры.
```

2023-06-29 21:47 UTC, Xewus commented
Сдаётся, что изменения, предложенные коллегами, внесены в ПР не будут...

2023-09-27 20:50 UTC, tiangolo commented
It seems this was also added in another recent PR, so it has some conflicts. I'm going to close this one, but if there are things here that should be added to the current version, feel free to create a new PR updating the current file.

Thanks for the effort @dukkee! 🍰 

And thanks for the reviews @solomein-sv, @glsglsgls, @Xewus ☕

2023-09-27 20:50 UTC, closed without merging