Add Chinese Translation for docs/advanced/additional-responses.md
fastapi/fastapi pull request #3793
Opened 2021-08-31 08:45 UTC by jaystone776

as title

2021-09-05 12:46 UTC, waynerv requested changes

2021-09-05 12:46 UTC, waynerv commented on docs/zh/docs/advanced/additional-responses.md
> +本章学习使用附加状态码、媒体类型、描述等声明响应。
```suggestion
本章学习为响应声明额外的状态码、媒体类型和描述。
```

2021-09-05 12:46 UTC, waynerv commented on docs/zh/docs/advanced/additional-responses.md
> +但必须要确保这些响应与状态码和 `content` 一起直接以 `JSONResponse` 等方式返回。
```suggestion
但必须要确保这些响应与状态码和 `content` 一起直接以一个 `Response` 对象如 `JSONResponse` 返回。
```

2021-09-05 12:46 UTC, waynerv commented on docs/zh/docs/advanced/additional-responses.md
> +## 使用 `model` 的响应
```suggestion
## 以 `model` 声明额外响应
```

2021-09-05 12:46 UTC, waynerv commented on docs/zh/docs/advanced/additional-responses.md
> +# OpenAPI 中的附加响应
```suggestion
# OpenAPI 中的额外响应
```

2021-09-05 12:46 UTC, waynerv commented on docs/zh/docs/advanced/additional-responses.md
> +`response` 参数可以接收键是响应的状态码，如 `200`，值是响应信息的字典。
```suggestion
`responses` 参数可以接收以响应状态码为键，如 `200`，响应信息为值的字典。
```

2021-09-05 12:46 UTC, waynerv commented on docs/zh/docs/advanced/additional-responses.md
> +响应字典可以包含 Pydantic 模型的键 `model`，如 `response_model`。
```suggestion
响应信息本身是个字典，可以包含名为 `model` 的键，其值为和 `response_model` 类似的 Pydantic 模型。
```

2021-09-05 12:46 UTC, waynerv commented on docs/zh/docs/advanced/additional-responses.md
> +    **FastAPI** 在此接收 Pydantic 模型，生成 `JSON Schema`，并把它推送到正确的位置。
```suggestion
    **FastAPI** 在此接收 Pydantic 模型，生成 `JSON Schema`，并把它置于正确的位置。
```

2021-09-05 12:46 UTC, waynerv commented on docs/zh/docs/advanced/additional-responses.md
> +## 主响应的附加媒体类型
```suggestion
## 主响应的额外媒体类型
```

2021-09-05 12:46 UTC, waynerv commented on docs/zh/docs/advanced/additional-responses.md
> +*路径操作装饰器*支持 `response` 参数。
```suggestion
*路径操作装饰器*支持 `responses` 参数。
```

2021-09-05 12:46 UTC, waynerv commented on docs/zh/docs/advanced/additional-responses.md
> +带状态码 `200` 的响应不仅使用 `response_model`，还包含了自定义 `example`：
```suggestion
以及使用 `response_model` 状态码为 `200` 的响应，但是还包含了自定义的 `example`：
```

2021-09-05 12:46 UTC, waynerv commented on docs/zh/docs/advanced/additional-responses.md
> +此处使用 Python **字典解包**，即 `**dict_to_unpack`：
```suggestion
此处使用 Python **字典解包**，即通过 `**dict_to_unpack` 语法解包一个 `dict`：
```

2021-09-18 23:20 UTC, UP929312 commented
Why did you make 400 pull requests instead of having them all in one?

2021-09-28 08:29 UTC, thunderamur commented
> Why did you make 400 pull requests instead of having them all in one?

The Chinese bureaucracy requires the number of pull requests. I think the maintainers should reject all this spam.

2021-12-20 07:32 UTC, qysfblog approved these changes
ok

2023-06-26 19:14 UTC, tiangolo commented
📝 Docs preview for commit 70b2f42b94486e09164f6b4b0f24da864f41ebf4 at: https://6499e381a2e6b304e1ddcb48--fastapi.netlify.app

2024-01-29 15:09 UTC, tiangolo commented
Thank you @jaystone776! It seems this was covered by https://github.com/tiangolo/fastapi/pull/10325, so I'll now close this one.

But if you feel the current one can be improved, feel free to add more PRs. ☕

2024-01-29 15:09 UTC, closed without merging