Add Chinese Translation for docs\advanced\response-cookies.md
fastapi/fastapi pull request #3795
Opened 2021-08-31 08:52 UTC by jaystone776

As title

2021-09-05 12:52 UTC, waynerv requested changes

2021-09-05 12:52 UTC, waynerv commented on docs/zh/docs/advanced/response-cookies.md
> +现在，在*临时*响应对象中设置 cookie。
```suggestion
然后你可以在这个*临时*的响应对象中设置 cookie。
```

2021-09-05 12:52 UTC, waynerv commented on docs/zh/docs/advanced/response-cookies.md
> +    注意，不使用 `Response` 参数直接返回响应时，FastAPI 直接返回响应。
```suggestion
    注意，如果不使用 `Response` 参数而是直接返回一个响应对象，FastAPI 会将该响应不加处理直接返回给客户端。
```

2021-09-05 12:52 UTC, waynerv commented on docs/zh/docs/advanced/response-cookies.md
> +    而且不能发送经 `response_model` 筛选过的数据。
```suggestion
    而且不能发送需要通过 `response_model` 进行校验过滤的数据。
```

2021-09-05 12:52 UTC, waynerv commented on docs/zh/docs/advanced/response-cookies.md
> +所有可用参数及选项，详见 <a href="https://www.starlette.io/responses/#set-cookie" class="external-link" target="_blank">Starlette 官档</a>。
```suggestion
所有可用参数及选项，详见 <a href="https://www.starlette.io/responses/#set-cookie" class="external-link" target="_blank">Starlette 官方文档</a>。
```

2021-09-06 05:42 UTC, waynerv approved these changes

2023-06-26 18:04 UTC, tiangolo commented
It seems this was translated at some point in another PR. So I'll close this one, but thanks for the effort! ☕

2023-06-26 18:04 UTC, closed without merging