Add Chinese Translation for docs\advanced\response-headers.md
fastapi/fastapi pull request #3796
Opened 2021-08-31 08:55 UTC by jaystone776

As title

2021-09-05 12:57 UTC, waynerv requested changes

2021-09-05 12:57 UTC, waynerv commented on docs/zh/docs/advanced/response-headers.md
> +与声明 Cookie 响应一样，*路径操作函数*中还可以声明 `Response` 类型的参数。
```suggestion
*路径操作函数*中可以声明 `Response` 类型的参数（正如声明响应的 cookie 时的做法一样）。
```

2021-09-05 12:57 UTC, waynerv commented on docs/zh/docs/advanced/response-headers.md
> +现在，在*临时*响应对象中设置响应头。
```suggestion
然后在*临时*的响应对象中设置响应头。
```

2021-09-05 12:57 UTC, waynerv commented on docs/zh/docs/advanced/response-headers.md
> +但如果需要浏览器中的客户端查看自定义响应头，则要在 CORS 配置中（详见 [CORS（跨域资源共享）](../tutorial/cors.md){.internal-link target=_blank})使用 <a href="https://www.starlette.io/middleware/#corsmiddleware" class="external-link" target="
```suggestion
但如果需要浏览器中的客户端查看自定义响应头，则要在 CORS 配置中（详见 [CORS（跨域资源共享）](../tutorial/cors.md){.internal-link target=_blank})使用 <a href="https://www.starlette.io/middleware/#corsmiddleware" class="external-link" target="_blank">Starlette 官方文档 - CORS</a> 中的 `expose_headers` 参数。
```

2023-06-26 18:03 UTC, tiangolo commented
It seems this was translated at some point in another PR. So I'll close this one, but thanks for the effort! ☕

2023-06-26 18:03 UTC, closed without merging