Add Chinese Translation for docs\async.md
fastapi/fastapi pull request #3830
Opened 2021-09-01 04:02 UTC by jaystone776

as title

2022-02-09 13:46 UTC, zy7y approved these changes

2022-02-09 13:57 UTC, zy7y approved these changes

2022-07-15 06:28 UTC, mkdir700 requested changes

2022-07-15 06:28 UTC, mkdir700 commented on docs/zh/docs/async.md
> +但是使用 `async` 与 `await` 的异步编码的这种功能尝尝被统称为“携程”。它与 Go 的核心功能 “Goroutines” 相对应。
“携程” -> “协程”

```suggestion
但是使用 `async` 与 `await` 的异步编码的这种功能尝尝被统称为“协程”。它与 Go 的核心功能 “Goroutines” 相对应。
```

2022-07-15 06:28 UTC, mkdir700 commented on docs/zh/docs/async.md
> +如果你之前使用的异步框架不以上述方式运行，或者你习惯了定义琐碎的仅供计算的纯 `def` *路径操作函数*只为了提升些许性能（约 100 纳秒），请注意，在 **FastAPI** 中的效果正相反。在这些情况下，除非*路径操作函数*使用执行阻塞 <abbr title="输入/输出：磁盘读取与写入，网络通信d。">I/O</abbr> 的代码，最好使用 `async def`。
```suggestion
如果你之前使用的异步框架不以上述方式运行，或者你习惯了定义琐碎的仅供计算的普通`def` *路径操作函数*而只为了提升些许性能（约 100 纳秒），请注意，在 **FastAPI** 中的效果正相反。在这些情况下，最好使用 `aysnc def`，除非*路径操作函数*使用阻塞式 <abbr title="输入/输出：磁盘读取与写入，网络通信">I/O</abbr> 的代码。
```

2023-06-26 23:47 UTC, tiangolo commented
📝 Docs preview for commit 99fac02a2d2c9d87a2ad45d6711330b62888f01a at: https://649a2380c3bf901b5aa9e53c--fastapi.netlify.app

2024-01-28 18:19 UTC, tiangolo commented
Thank you! It seems this one was handled in another PR, so I'll pass on this one, but feel free to add new PRs updating the current version if you think that's needed!

Thanks! ☕ 🍰

2024-01-28 18:19 UTC, closed without merging