Add Chinese Translation for docs\tutorial\security\first-steps.md
fastapi/fastapi pull request #3841
Opened 2021-09-01 06:48 UTC by jaystone776

as title

2022-01-13 09:36 UTC, zy7y requested changes

2022-01-13 09:36 UTC, zy7y commented on docs/zh/docs/tutorial/security/first-steps.md
> +## 运行
运行它

2022-01-13 09:38 UTC, zy7y requested changes
ok

2022-01-13 09:41 UTC, zy7y approved these changes

2022-01-13 09:41 UTC, zy7y commented on docs/zh/docs/tutorial/security/first-steps.md
> +## 运行
## 运行它

2022-06-13 09:33 UTC, notnotype approved these changes

2022-06-13 09:33 UTC, notnotype commented on docs/zh/docs/tutorial/security/first-steps.md
> +但为了节省开发者的时间，不要只为了查找很少的内容，不得不阅读冗长的规范文档。
翻译建议（Translation suggestions）：
有时候，仅仅为了查找一些你需要的信息，我们不得不去阅读冗长又规范的文档。
为了节省这些时间，我们建议使用 FastAPI 的安全工具。

2022-08-18 15:53 UTC, tiangolo commented
Thanks for the contribution @jaystone776! :cake: 

And thanks for the reviews @notnotype and @zy7y! :coffee:

2022-08-18 15:57 UTC, merged