Update Chinese Translation for docs\tutorial\security\simple-oauth2.md
fastapi/fastapi pull request #3844
Opened 2021-09-01 06:59 UTC by jaystone776

as title

2022-11-07 08:40 UTC, mkdir700 approved these changes

2023-06-26 23:10 UTC, tiangolo commented
📝 Docs preview for commit 62212be26dea7977ce803d3084110b8b2a8fafc0 at: https://649a1ad41636a413a2534ba0--fastapi.netlify.app

2023-09-04 20:23 UTC, xzmeng approved these changes
LGTM.
This PR attempts to polish the sentences to make the chapter more easier to read, and there is no change in meaning.

2023-09-06 10:29 UTC, Sefank requested changes

2023-09-25 23:05 UTC, tiangolo commented
Thanks @jaystone776! 🚀 

And thanks for the reviews @Sefank, @xzmeng, @mkdir700! 🙇 

I'll merge this one for now, but if there are changes needed on top we can handle them in additional PRs. 🤓

2023-09-25 23:06 UTC, merged