feat: support exclude_none in dataclass response models
fastapi/fastapi pull request #3849
Opened 2021-09-01 11:26 UTC by sbelzile-nexapp

2022-01-09 14:15 UTC, cikay requested changes

2022-01-09 14:15 UTC, cikay commented on fastapi/routing.py
> +        return lambda data: dict(x for x in data if x[1] is not None)
`{x for x in data if x[1] is not None}` is faster.

2022-04-01 22:55 UTC, BilalAlpaslan approved these changes

2025-07-11 13:59 UTC, YuriiMotov reviewed
@sbelzile-nexapp, thanks for your efforts!

The usage of `exclude_none` is discouraged.
I think we shouldn't fix it and instead deprecate this parameter in the future

2025-09-20 15:29 UTC, tiangolo commented
Yep, as @YuriiMotov said. So, for now I'll pass on this one, but thanks for the interest! :cake:

2025-09-20 15:29 UTC, closed without merging