Add Russian translation for `docs/tutorial/body`
fastapi/fastapi pull request #3885
Opened 2021-09-10 05:31 UTC by solomein-sv

2021-09-10 05:31 UTC, solomein-sv commented
#1362

2021-11-12 12:10 UTC, RuslanTer requested changes

2021-11-12 12:10 UTC, RuslanTer commented on docs/ru/docs/tutorial/body.md
> +Если вы не хотите использовать модели Pydantic, вы все еще можете использовать параметры **тела запроса**. Читайте в документации раздел [Тело - Несколько параметров: Единичные значения в теле](body-
"вы все еще можете использовать параметры **тела запроса**" -> "вы также можете использовать параметры с типом **Body** "

2021-11-12 12:47 UTC, solomein-sv commented on docs/ru/docs/tutorial/body.md
> +Чтобы объявить тело **запроса**, необходимо использовать модели <a href="https://pydantic-docs.helpmanual.io/" class="external-link" target="_blank">Pydantic</a>, с всей их мощью и преимуществами.
согласен

2021-11-12 12:51 UTC, solomein-sv commented on docs/ru/docs/tutorial/body.md
> +Также она будет указана в документации по API внутри каждой *операции пути*, в которой используются:
если честно, меня подбешивают эти "операции пути", но я пока ничего лучше не придумал ))) "маршруты" рассматривал, но мне кажется, что это не идентичное понятие.

2021-11-12 12:52 UTC, solomein-sv commented on docs/ru/docs/tutorial/body.md
> +Но у вас будет такая же поддержка и с <a href="https://www.jetbrains.com/pycharm/" class="external-link" target="_blank">PyCharm</a>, и вообще с любым редактором Python:
у автора все-таки "любым", а не "большинством"... т.е. это спорный вопрос и с ним -- к автору ))

2021-11-12 12:53 UTC, solomein-sv commented on docs/ru/docs/tutorial/body.md
> +Если вы не хотите использовать модели Pydantic, вы все еще можете использовать параметры **тела запроса**. Читайте в документации раздел [Тело - Несколько параметров: Единичные значения в теле](body-
чем не нравится "тело запроса"?

2021-11-12 13:42 UTC, RuslanTer commented on docs/ru/docs/tutorial/body.md
> +Если вы не хотите использовать модели Pydantic, вы все еще можете использовать параметры **тела запроса**. Читайте в документации раздел [Тело - Несколько параметров: Единичные значения в теле](body-
Потому что "параметры **тела запроса**" - звучит, как часть сущности "тело запроса", и понять по этой фразе, что имеется ввиду очень сложно.

2021-11-12 13:42 UTC, RuslanTer commented on docs/ru/docs/tutorial/body.md
> +Также она будет указана в документации по API внутри каждой *операции пути*, в которой используются:
может их вообще не переводить?

2021-11-12 17:48 UTC, solomein-sv commented on docs/ru/docs/tutorial/body.md
> +Также она будет указана в документации по API внутри каждой *операции пути*, в которой используются:
оставить path? имхо, некрасиво и неправильно

2022-02-19 08:56 UTC, ev-horrosh requested changes

2022-02-19 08:56 UTC, ev-horrosh commented on docs/ru/docs/tutorial/body.md
> +Также она будет указана в документации по API внутри каждой *операции пути*, в которой используются:
А также будет использована в API документации внутри каждой операции с ресурсами по необходимости

2022-02-19 16:29 UTC, FedorGN requested changes

2022-02-19 16:29 UTC, FedorGN commented on docs/ru/docs/tutorial/body.md
> +```
Изменить на:

```suggestion
=== "Python 3.6 и выше"

    ```Python hl_lines="4"
    {!> ../../../docs_src/body/tutorial001.py!}
    ```

=== "Python 3.10 и выше"

    ```Python hl_lines="2"
    {!> ../../../docs_src/body/tutorial001_py310.py!}
    ```
```

2022-02-19 16:29 UTC, FedorGN commented on docs/ru/docs/tutorial/body.md
> +```
```suggestion
=== "Python 3.6 и выше"

    ```Python hl_lines="7-11"
    {!> ../../../docs_src/body/tutorial001.py!}
    ```

=== "Python 3.10 и выше"

    ```Python hl_lines="5-9"
    {!> ../../../docs_src/body/tutorial001_py310.py!}
    ```
```

2022-02-19 16:29 UTC, FedorGN commented on docs/ru/docs/tutorial/body.md
> +```
```suggestion
=== "Python 3.6 и выше"

    ```Python hl_lines="18"
    {!> ../../../docs_src/body/tutorial001.py!}
    ```

=== "Python 3.10 и выше"

    ```Python hl_lines="16"
    {!> ../../../docs_src/body/tutorial001_py310.py!}
    ```
```

2022-02-19 16:29 UTC, FedorGN commented on docs/ru/docs/tutorial/body.md
> +```
```suggestion
=== "Python 3.6 и выше"

    ```Python hl_lines="21"
    {!> ../../../docs_src/body/tutorial002.py!}
    ```

=== "Python 3.10 и выше"

    ```Python hl_lines="19"
    {!> ../../../docs_src/body/tutorial002_py310.py!}
    ```
```

2022-02-19 16:29 UTC, FedorGN commented on docs/ru/docs/tutorial/body.md
> +```
```suggestion
=== "Python 3.6 и выше"

    ```Python hl_lines="17-18"
    {!> ../../../docs_src/body/tutorial003.py!}
    ```

=== "Python 3.10 и выше"

    ```Python hl_lines="15-16"
    {!> ../../../docs_src/body/tutorial003_py310.py!}
    ```
```

2022-02-19 16:29 UTC, FedorGN commented on docs/ru/docs/tutorial/body.md
> +```
```suggestion
=== "Python 3.6 and above"

    ```Python hl_lines="18"
    {!> ../../../docs_src/body/tutorial004.py!}
    ```

=== "Python 3.10 and above"

    ```Python hl_lines="16"
    {!> ../../../docs_src/body/tutorial004_py310.py!}
    ```
```

2022-05-15 17:22 UTC, Xewus commented
It seems, the Russian translation is dead.

2022-05-22 11:41 UTC, Xewus commented
Так вот, же у Вас тут набрано три человека...

2022-05-22 12:25 UTC, solomein-sv commented
Может быть, они просто нажимают Review, а там ещё Approve )))

2023-02-13 14:09 UTC, Xewus commented
> Может быть, они просто нажимают Review, а там ещё Approve )))

Кстати, нынче достаточно 2 человек.
Но у Вас почему-то и автотесты не пройдены...

2023-02-13 14:40 UTC, Xewus requested changes

2023-02-13 14:40 UTC, Xewus commented on docs/ru/docs/tutorial/body.md
> +Тело **запроса** --- это данные, отправляемые клиентом в ваш API. Тело **ответа** --- это данные, которые ваш API отправляет клиенту.
Три тире - это какая-то фича для `md`?

2023-02-13 14:40 UTC, Xewus commented on docs/ru/docs/tutorial/body.md
> +Ваш API почти всегда отправляет тело **ответа**. Но клиентам не обязательно всегда отправлять тело **запроса**.
> не обязательно всегда

не всегда обязательно.

2023-02-13 14:40 UTC, Xewus commented on docs/ru/docs/tutorial/body.md
> +Чтобы объявить тело **запроса**, необходимо использовать модели <a href="https://pydantic-docs.helpmanual.io/" class="external-link" target="_blank">Pydantic</a>, с всей их мощью и преимуществами.
> с всей их мощью

со всей их мощью.

 Возможно. независимо от оригинала, стоит уточнить, что объявить нужно в функции-получателе.

2023-02-13 14:40 UTC, Xewus commented on docs/ru/docs/tutorial/body.md
> +!!! info
Перевод заголовков табличек уже применён в большей части немногих переведённых страниц.

!!! info "Информация"

2023-02-13 14:40 UTC, Xewus commented on docs/ru/docs/tutorial/body.md
> +    Чтобы отправить данные, необходимо использовать один из методов: `POST` (обычно), `PUT`, `DELETE` или `PATCH`.
> данные, необходимо использовать

данные, следует использовать один из указанных/перечисленных

> `POST` (обычно),

`POST` (в большинстве случаев),

2023-02-13 14:40 UTC, Xewus commented on docs/ru/docs/tutorial/body.md
> +    Поскольку это не рекомендуется, интерактивная документация со Swagger UI не будут отображать документацию для тела при использовании GET, а промежуточные прокси-серверы могут не поддерживать его.
> при использовании GET

при использовании метода GET

> могут не поддерживать его.

Кого - его?
могут не поддерживать такое решение.

2023-02-13 14:40 UTC, Xewus commented on docs/ru/docs/tutorial/body.md
> +После этого вы описываете вашу модель данных как класс, наследующий от `BaseModel`.
> наследующий
 Не знаю, как правильнее - наследующий или наследующийся...

2023-02-13 14:40 UTC, Xewus commented on docs/ru/docs/tutorial/body.md
> +Также как и при описании параметров запроса, когда атрибут модели имеет значение по умолчанию, он является необязательным. Иначе он обязателен. Используйте `None`, чтобы сделать его необязательным бе
> Также как и при описании параметров запроса, когда атрибут модели имеет значение по умолчанию, он является необязательным. Иначе он обязателен.

Также как и при описании параметров запроса, если атрибут модели имеет значение по умолчанию, он является необязательным, иначе он обязателен.

2023-02-13 14:40 UTC, Xewus commented on docs/ru/docs/tutorial/body.md
> +...поскольку `description` и `tax` являются необязательными (с `None` в качестве значения по умолчанию), вот такой JSON "объект" также подходит:
> (с `None` в качестве значения по умолчанию), вот такой JSON "объект" также подходит:

(с `None` в качестве значения по умолчанию), то такой JSON "объект" также подходит:

2023-02-13 14:40 UTC, Xewus commented on docs/ru/docs/tutorial/body.md
> +* Читает тело запроса как JSON.
Перед "как" вроде запятая положена?

2023-02-13 14:40 UTC, Xewus commented on docs/ru/docs/tutorial/body.md
> +    * Если данные некорректны, будет возращена читаемая и понятная ошибка, показывающая что именно и в каком месте некорректно в данных.
И перед "что" тоже.

2023-02-13 14:40 UTC, Xewus commented on docs/ru/docs/tutorial/body.md
> +!!! tip
!!! tip "Подсказка"

2023-02-13 14:40 UTC, Xewus commented on docs/ru/docs/tutorial/body.md
> +    * инспектирования.
> * инспектирования.

Точка в конце закралась.

2023-02-13 14:40 UTC, Xewus commented on docs/ru/docs/tutorial/body.md
> +**FastAPI** распознает какие параметры функции соответствуют параметрам пути и должны быть **получены из пути**, а какие параметры функции, объявленные как модели Pydantic, должны быть **получены из
> **FastAPI** распознает какие параметры

**FastAPI** распознает, какие параметры

2023-02-13 14:40 UTC, Xewus commented on docs/ru/docs/tutorial/body.md
> +!!! note
!!! note "Заметка"

2023-02-14 12:40 UTC, solomein-sv commented on docs/ru/docs/tutorial/body.md
> +Тело **запроса** --- это данные, отправляемые клиентом в ваш API. Тело **ответа** --- это данные, которые ваш API отправляет клиенту.
нет, это "фича" latex ))) просто длинное тире

2023-02-14 12:42 UTC, solomein-sv commented on docs/ru/docs/tutorial/body.md
> +Ваш API почти всегда отправляет тело **ответа**. Но клиентам не обязательно всегда отправлять тело **запроса**.
оба варианта допустимы, имеют один и тот же смысл

2023-02-14 12:51 UTC, solomein-sv commented on docs/ru/docs/tutorial/body.md
> +    Чтобы отправить данные, необходимо использовать один из методов: `POST` (обычно), `PUT`, `DELETE` или `PATCH`.
мне кажется, вы слишком заморачиваетесь ) не вижу принципиальной разницы

2023-02-14 12:54 UTC, solomein-sv commented on docs/ru/docs/tutorial/body.md
> +    Поскольку это не рекомендуется, интерактивная документация со Swagger UI не будут отображать документацию для тела при использовании GET, а промежуточные прокси-серверы могут не поддерживать его.
заменил "его" на "такой вариант запроса"

2023-02-14 13:12 UTC, solomein-sv commented on docs/ru/docs/tutorial/body.md
> +* Читает тело запроса как JSON.
имхо, здесь можно заменить как на сочетание "в качестве". в этом случае запятая **не** ставится.

2023-02-14 13:12 UTC, solomein-sv commented on docs/ru/docs/tutorial/body.md
> +    * Если данные некорректны, будет возращена читаемая и понятная ошибка, показывающая что именно и в каком месте некорректно в данных.
нет. в данном случае не ставится

2023-02-14 13:12 UTC, solomein-sv commented on docs/ru/docs/tutorial/body.md
> +    * инспектирования.
Так предложение закончилось ))) тут скорее запятых не хватает...

2023-02-14 13:51 UTC, Xewus commented on docs/ru/docs/tutorial/body.md
> +    * Если данные некорректны, будет возращена читаемая и понятная ошибка, показывающая что именно и в каком месте некорректно в данных.
Ох уж этот русский язык...

2023-02-14 13:51 UTC, Xewus approved these changes

2023-02-14 13:54 UTC, Xewus commented
Ткните палкой ранее отметившихся, может удосужатся апрувнуть...

2023-04-27 17:12 UTC, AGolicyn approved these changes

2023-04-27 22:14 UTC, RuslanTer approved these changes

2023-05-29 11:10 UTC, Alexandrhub approved these changes

2023-05-29 11:16 UTC, Alexandrhub commented
Автор, сделайте пожалуйста обновление ПРа, чтобы пройти пре-коммит проверку :)

2023-06-03 12:54 UTC, tiangolo commented
Thanks @solomein-sv! 🍰 

And thanks for the reviews @ev-horrosh, @RuslanTer, @Xewus, @AGolicyn, @Alexandrhub, @FedorGN ☕

2023-06-03 14:19 UTC, merged