Update orjson support non str keys
fastapi/fastapi pull request #3892
Opened 2021-09-11 08:59 UTC by baby5

the detail see: https://github.com/ijl/orjson/issues/197

my case is `<class 'sqlalchemy.sql.elements.quoted_name'>`

2021-10-05 10:27 UTC, adam-tokarski requested changes
Please provide any tests for that.

2021-10-06 10:28 UTC, baby5 commented
@adam-tokarski done

2021-10-06 11:07 UTC, adam-tokarski commented on tests/test_default_response_class.py
> +    return {key: "Hello World"}
Isn't that `key` still a string? It seems like it should be working even before the fix (I didn't check that though).

Also, you could provide a test with some integer as a key maybe?

2021-10-06 14:48 UTC, adam-tokarski approved these changes

2022-09-02 10:05 UTC, tiangolo commented
Great, thank you @baby5! And thanks for adding tests! :cake: 

And thanks @adam-tokarski for the help and review! :coffee:

2022-09-02 10:17 UTC, merged

2024-04-04 10:56 UTC, NikosAlexandris commented
What is the status of this issue regarding support for NumPy arrays ?