Improve german translation
fastapi/fastapi pull request #3905
Opened 2021-09-15 11:53 UTC by jomue

I've fixed a few typos in the german translation.

2021-09-15 12:17 UTC, mawassk requested changes

2021-09-15 12:17 UTC, mawassk commented on docs/de/docs/features.md
> +* **Keine Kompromisse** bei Datenbanken, Eingabemasken, usw. sondern einfache Integration von allen.
* **Keine Kompromisse** bei Datenbanken, Eingabemasken, usw., sondern einfache Integration von allen.

2021-09-15 12:22 UTC, jomue commented on docs/de/docs/features.md
> +* **Keine Kompromisse** bei Datenbanken, Eingabemasken, usw. sondern einfache Integration von allen.
Thanks 👍

2021-09-15 12:24 UTC, mawassk approved these changes

2021-09-22 02:42 UTC, ArcLightSlavik commented
Could you update the name of PR to `Update German Translation for docs/features.md`

2022-02-05 09:45 UTC, rogerbrinkmann approved these changes
Proposed changes are necessary and correct

2022-02-10 11:28 UTC, jsbeckr approved these changes
fixes typos and mistranslation 👍

2022-05-09 18:15 UTC, tiangolo commented
Awesome, thank you @jomue! :bow: 

And thanks for the reviews @jsbeckr, @rogerbrinkmann, @mawassk! :cake: 

And thanks for the help @ArcLightSlavik! :sunglasses:

2022-05-09 18:16 UTC, merged