Added Portuguese translation for docs/tutorial/body.md
fastapi/fastapi pull request #3960
Opened 2021-09-28 16:21 UTC by leandrodesouzadev

This PR translates the tutorial/body.md and add this page to the mkdocs.yml file.

2021-09-28 16:34 UTC, Kludex commented on docs/pt/docs/tutorial/body.md
> +Quando você precisa enviar dados de um cliente (Como de um navegador web) para sua API, você envia como um **corpo da requisição**.
```suggestion
Quando você precisa enviar dados de um cliente (como de um navegador web) para sua API, você o envia como um **corpo da requisição**.
```

2021-10-05 23:46 UTC, cassiobotaro approved these changes
LGTM

2021-10-27 22:36 UTC, diogoduartec requested changes

2022-01-18 01:04 UTC, lsglucas requested changes

2022-01-18 01:04 UTC, lsglucas commented on docs/pt/docs/tutorial/body.md
> +!!! Observação
```suggestion
!!! note "Observação"
```
Just a small fix

2022-01-18 12:08 UTC, lsglucas approved these changes

2022-02-22 23:42 UTC, peidrao approved these changes

2022-02-23 10:46 UTC, Riverfount approved these changes
Great Job!

2022-05-09 18:25 UTC, merged