🌐 Add Russian translation for `docs/async.md`
fastapi/fastapi pull request #4036
Opened 2021-10-11 19:35 UTC by Winand

- Отмечу сразу, что я только знакомлюсь с фреймворком и в проектах его ещё не использовал.
- Как я понимаю переведённый файл необходимо добавлять в `mkdocs.yml`? В других PR этого не увидел.
- В разделе "Path operation functions" есть фраза "it's better to use `async def` unless your <...> functions use code that performs blocking I/O". Нужно уточнить, верно ли я передал смысл в [переводе](https://github.com/tiangolo/fastapi/pull/4036/files#diff-0c2cdf8b5bd824c3c2b17b6b300fa9b522c92e5742df4b2cca214d75de028a5bR457-R460).

2021-10-15 00:35 UTC, ArcLightSlavik commented
>Как я понимаю переведённый файл необходимо добавлять в mkdocs.yml? В других PR этого не увидел.

Yes, you need to add it to `mkdocs.yml` not sure why it's not consistent though 🤔

2022-01-08 07:05 UTC, dimaqq approved these changes

2022-02-08 08:46 UTC, solomein-sv approved these changes

2022-02-19 12:05 UTC, FedorGN requested changes
Перевод хороший, пара комментариев: 

1. Добавить один параграф "Write your own async code". Написал его перевод в комментарии.

2022-02-21 07:50 UTC, Winand commented
I'm not completely sure about translation of "path operation function".
---
Я сам не уверен по поводу термина "**функция обработки пути**" (path operation function), поскольку path - это действительно путь (endpoint, route), но operation - это HTTP-метод (GET, POST и т.п.)

2022-02-21 09:53 UTC, FedorGN approved these changes

2022-04-02 18:02 UTC, h0rn3t commented
I think need to delete russian documentation because of 
fascist war against Ukraine, 38 days of war was died more then 150 children and many civilian, many towns was destroyed

2022-05-09 18:30 UTC, merged