Add default API error schema
fastapi/fastapi pull request #4042
Opened 2021-10-12 22:21 UTC by caiofauza

Closes #3650 

We implemented a way to define a default API error schema, as suggested on #3650. 
The error object can be passed in the constructor of the FastAPI class (optional parameter) or defined by variable attribution.

Example code:
```py from fastapi import FastAPI
from pydantic import BaseModel

class Response(BaseModel):
    status: bool
    
default_error = {
    'status': 400,
    'name': 'DefaultError',
    'description': 'DefaultError',
    'properties': {
        'message': {'title': 'Message', 'type': 'string'},
        'metadata': {'title': 'Metadata', 'type': 'string'}
    },
    'required': ['message']
}

app = FastAPI(default_error_schema=default_error)

@app.get('/status', response_model=Response)
def retrieve_status():
    return { 'status': True }
```

![image](https://user-images.githubusercontent.com/38479437/137036491-1ecae3c9-8ef7-4afe-8afe-10ce39923c6e.png)

@zMendes @Gustavobb

2025-07-11 11:16 UTC, YuriiMotov requested changes
@caiofauza, thanks for your work!

I really like the idea of this PR and it works, but there are a few things that need to be done to get it approved and merged:
* the type of `default_error_schema` is declared as `Optional[DefaultErrorSchema]`, but in fact it's `Optional[dict]` (we pass it as `dict` and it's handled as `dict` in code). Typing needs to be fixed. It can be done by converting `DefaultErrorSchema` into `TypedDict`. Another option is to accept both `dict[str, Any]` or `DefaultErrorSchema` and handle it in code.
* `DefaultErrorSchema` should align with the real schema of expected `dict`. Now `name`, `properties` and `required` are missing, but `model` exists instead.
* I think we should add the default values for `status` (maybe rename to `status_code`?), `name` and `description`.
* Feature should be covered by tests

@caiofauza, would you like to work on this?

2025-07-25 23:01 UTC, mvanderlee commented
Not sure this is needed anymore since we can define custom response models already, and we can do so by using Pydantic models.

```python
app = FastAPI(
    responses={422: {"model": YourErrorModel}}
)
```

2025-07-27 00:21 UTC, YuriiMotov commented
> Not sure this is needed anymore since we can define custom response models already, and we can do so by using Pydantic models.
> 
> ```python
> app = FastAPI(
>     responses={422: {"model": YourErrorModel}}
> )
> ```

This PR aims to simplify the process if you need to change the status code used for error responses.
For example, if you want it to be `400` instead of `422`.
For now it's easy to add response, but to remove default response you need to use hack:
```py
app = FastAPI(
    responses={400: {"model": YourErrorModel}, 422: None}
)
```

Ideally this PR should also change the status code FastAPI uses to send error response in case of request validation error

2025-07-27 11:31 UTC, mvanderlee commented
> > Not sure this is needed anymore since we can define custom response models already, and we can do so by using Pydantic models.
> > ```python
> > app = FastAPI(
> >     responses={422: {"model": YourErrorModel}}
> > )
> > ```
> 
> This PR aims to simplify the process if you need to change the status code used for error responses. For example, if you want it to be `400` instead of `422`. For now it's easy to add response, but to remove default response you need to use hack:
> 
> ```python
> app = FastAPI(
>     responses={400: {"model": YourErrorModel}, 422: None}
> )
> ```
> 
> Ideally this PR should also change the status code FastAPI uses to send error response in case of request validation error

I disagree. This PR specifically talks about the eror schema. 
I also think it's fine for FastAPI to have opinions, but I may be biased because I strongly agree with them. A validation error should be a 422. If a developer feels differently he can overwrite it already. 

1. If they define any of `422, "4XX", or "default"`, then FastAPI does not add the default schema
    ```python
    responses={422: {"model": YourErrorModel}}
    responses={"4XX": {"model": YourErrorModel}}
    responses={"default": {"model": YourErrorModel}}
    ```
    
    Note that neither of these work
    ```python
     # Your example of a hack raises an error!
    responses={422: None} 
    # 422 still shows up in the OpenAPI schema.
    responses={422: {"model": None}}
    ```
    
2. To overwrite the actual response status code the developer can add a custom error handler
    ```python
    async def my_request_validation_exception_handler(
        request: Request, exc: RequestValidationError
    ) -> JSONResponse:
        return JSONResponse(
            status_code=400,
            content={"detail": jsonable_encoder(exc.errors())},
        )
        
    fastapi = FastAPI(exception_handlers={RequestValidationError: my_request_validation_exception_handler})
    ```

The only issue left is that the user can't simply disable the 422 documentation. They must define either a default, or `4XX` both of which may be inaccurate as they cover too many other status codes. 
This could be solved with a simple boolean. e.g.: `include_default_validation_response_in_schema`

2025-07-27 17:02 UTC, YuriiMotov commented
> This could be solved with a simple boolean. e.g.: `include_default_validation_response_in_schema`

I agree with this. `include_default_validation_response_in_schema` is simpler

2025-08-27 22:18 UTC, closed without merging