🌐 Add Portuguese translation for `docs/pt/docs/tutorial/schema-extra-example.md`
fastapi/fastapi pull request #4065
Opened 2021-10-19 13:43 UTC by luccasmmg

2022-09-22 15:38 UTC, lsglucas requested changes

2022-09-22 15:38 UTC, lsglucas commented on docs/pt/docs/tutorial/schema-extra-example.md
> +!!! dica
```suggestion
!!! tip "dica"
```

2022-09-22 15:38 UTC, lsglucas commented on docs/pt/docs/tutorial/schema-extra-example.md
> +!!! atenção
```suggestion
!!! warning "atenção"
```

2022-10-27 14:33 UTC, Lahiry requested changes
Just need to fix some spacing and a word choice, good job!

2022-10-27 14:33 UTC, Lahiry commented on docs/pt/docs/tutorial/schema-extra-example.md
> +Para `Path()`, `Query()`, `Header()`, e `Cookie()`, o `example` e `examples` são adicionados a<a href="https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#parameter-object" class
```suggestion
Para `Path()`, `Query()`, `Header()`, e `Cookie()`, o `example` e `examples` são adicionados a <a href="https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#parameter-object" class="external-link" target="_blank">definição do OpenAPI, dentro do `Parameter Object` (na especificação)</a>.
```

2022-10-27 14:33 UTC, Lahiry commented on docs/pt/docs/tutorial/schema-extra-example.md
> +Por outro lado, há uma versão mais recente do OpenAPI: **3.1.0**, lançada recentemente. Baseado no JSON Schema mais recente e a maioria das modificações da versão customizada do OpenAPI do JSON Schem
```suggestion
Por outro lado, há uma versão mais recente do OpenAPI: **3.1.0**, lançada recentemente. Baseado no JSON Schema mais recente e a maioria das modificações da versão customizada do OpenAPI do JSON Schema são removidas, em troca dos recursos das versões recentes do JSON Schema, portanto, todas essas pequenas diferenças são reduzidas. No entanto, a UI do Swagger atualmente não oferece suporte a OpenAPI 3.1.0, então, por enquanto, é melhor continuar usando as opções acima.
```

2023-01-02 14:07 UTC, lsglucas approved these changes

2023-01-29 01:51 UTC, LorhanSohaky reviewed
I think with these modifications the reading will be more fluid

2023-01-29 01:51 UTC, LorhanSohaky commented on docs/pt/docs/tutorial/schema-extra-example.md
> +    Por exemplo, você pode usar isso para adicionar metadados em uma interface de usuário de front-end, etc.
```suggestion
    Por exemplo, você pode usar isso para adicionar metadados para uma interface de usuário de front-end, etc.
```

2023-01-29 01:51 UTC, LorhanSohaky commented on docs/pt/docs/tutorial/schema-extra-example.md
> +!!! tip "dica"
```suggestion
!!! tip "Dica"
```

2023-01-29 01:51 UTC, LorhanSohaky commented on docs/pt/docs/tutorial/schema-extra-example.md
> +!!! warning "atenção"
```suggestion
!!! warning "Atenção"
```

2023-01-29 01:51 UTC, LorhanSohaky commented on docs/pt/docs/tutorial/schema-extra-example.md
> +você também pode declarar um dado `example` ou um grupo de `examples` com informações adicionais que serão adicionadas à **OpenAPI**.
```suggestion
você também pode declarar um dado `example` ou um grupo de `examples` com informações adicionais que serão adicionadas ao **OpenAPI**.
```

2023-01-29 01:51 UTC, LorhanSohaky commented on docs/pt/docs/tutorial/schema-extra-example.md
> +Com qualquer um dos métodos acima, os `/docs` vão ficar assim:
```suggestion
Com qualquer um dos métodos acima, ficaria assim na `/docs`:
```

2023-01-29 01:51 UTC, LorhanSohaky commented on docs/pt/docs/tutorial/schema-extra-example.md
> +Alternativamente ao único `example`, você pode passar `examples` usando um `dict` com **vários examples**, cada um com informações extras que serão adicionadas no **OpenAPI** também.
```suggestion
Alternativamente ao único `example`, você pode passar `examples` usando um `dict` com **vários exemplos**, cada um com informações extras que serão adicionadas no **OpenAPI** também.
```

2023-01-29 01:51 UTC, LorhanSohaky commented on docs/pt/docs/tutorial/schema-extra-example.md
> +* `summary`: Pequena descrição para o exemplo.
```suggestion
* `summary`: Pequena descrição do exemplo.
```

2023-01-29 01:51 UTC, LorhanSohaky commented on docs/pt/docs/tutorial/schema-extra-example.md
> +* `externalValue`: alternativo a `value`, uma URL apontando para o exemplo. Embora isso possa não ser suportado por tantas ferramentas quanto `value`.
```suggestion
* `externalValue`: alternativa ao `value`, uma URL apontando para o exemplo. Embora isso possa não ser suportado por tantas ferramentas quanto `value`.
```

2023-01-29 01:51 UTC, LorhanSohaky commented on docs/pt/docs/tutorial/schema-extra-example.md
> +Com `examples` adicionado a `Body()`, os `/docs` vão ficar assim:
```suggestion
Com `examples` adicionados ao `Body()`, o `/docs` ficaria assim:
```

2023-01-29 01:51 UTC, LorhanSohaky commented on docs/pt/docs/tutorial/schema-extra-example.md
> +!!! warning "atenção"
```suggestion
!!! warning "Atenção"
```

2023-01-29 01:51 UTC, LorhanSohaky commented on docs/pt/docs/tutorial/schema-extra-example.md
> +Quando você adiciona um exemplo dentro de um modelo Pydantic, usando `schema_extra` ou` Field (example = "something") `esse exemplo é adicionado ao **JSON Schema** para esse modelo Pydantic.
```suggestion
Quando você adiciona um exemplo dentro de um modelo Pydantic, usando `schema_extra` ou` Field(example="something") `esse exemplo é adicionado ao **JSON Schema** para esse modelo Pydantic.
```

2023-02-02 10:11 UTC, LorhanSohaky commented on docs/pt/docs/tutorial/schema-extra-example.md
> +Com `examples` adicionado a `Body()`, os `/docs` vão ficar assim:
Missed that

2023-02-02 10:12 UTC, LorhanSohaky commented on docs/pt/docs/tutorial/schema-extra-example.md
> +Com qualquer um dos métodos acima, os `/docs` vão ficar assim:
Missed that

2023-06-26 23:26 UTC, tiangolo commented
📝 Docs preview for commit 3bfd1df971fb45887313535fd168d81bb01603c8 at: https://649a1e53d1bbbc159e60f87f--fastapi.netlify.app

2023-06-28 13:43 UTC, jessicapaz commented on docs/pt/docs/tutorial/schema-extra-example.md
> +Mas quando você usa `example` ou `examples` com qualquer um dos outros utilitários (`Query ()`, `Body ()`, etc.) esses exemplos não são adicionados ao JSON Schema que descreve esses dados (nem mesmo
```suggestion
Mas quando você usa `example` ou `examples` com qualquer um dos outros utilitários (`Query()`, `Body()`, etc.) esses exemplos não são adicionados ao JSON Schema que descreve esses dados (nem mesmo para versão própria do OpenAPI do JSON Schema), eles são adicionados diretamente à declaração da *operação de rota* no OpenAPI (fora das partes do OpenAPI que usam o JSON Schema).
```

2023-07-04 10:58 UTC, tiangolo commented
📝 Docs preview for commit b9e3edaf96b2939365035d0377e59f141762b3f0 at: https://64a3fb27ac978b0872bdbd79--fastapi.netlify.app

2024-01-12 13:22 UTC, tiangolo commented
Hello @LorhanSohaky, @jessicapaz, @Lahiry! 👋 

Would you think this is ready after the changes? Would you approve it? 🤓

2024-01-12 13:22 UTC, tiangolo commented
📝 Docs preview for commit eae3b01148eb496795e4e975c42ed6b89eb32910 at: https://0c8a6145.fastapitiangolo.pages.dev

2024-01-25 15:05 UTC, merged

2024-01-25 15:06 UTC, alejsdev commented
Thanks for your contribution @luccasmmg 😎 

And thanks to everyone for the reviews 🥳🎉