🌐 Add Korean translation for `docs/ko/docs/features`
fastapi/fastapi pull request #4137
Opened 2021-11-04 04:21 UTC by kty4119

* Add Korean translation for docs/ko/docs/features.md
* Related [FEATURE] Korean translations [FEATURE] Korean translations #2017

2021-11-22 02:13 UTC, DevDae requested changes
First of all, i'm really gratitude for your works!
Feel free to my opinions and please give your idea 😁

2021-11-22 02:13 UTC, DevDae commented on docs/ko/docs/features.md
> +- 면밀히 조사의 결과, 상층에 개설하는 것이 아니라, 이 기준에 그거해 설계되었습니다.
```suggestion
- 면밀히 조사의 결과, 상층에 개설하는 것이 아니라, 이 기준에 의거해 설계되었습니다.
```
Maybe you make mistake, what's mean of the word, "그거해"? 😄

2021-11-22 02:13 UTC, DevDae commented on docs/ko/docs/features.md
> +- 보다 이국적인 유형에 대한 검증, 예를 들면:
```suggestion
- 보다 익숙하지 않은 유형에 대한 검증, 예를 들면:
```
I think "익숙하지 않은" can represent the meaning of the "exotic" than "이국적인".

2022-08-05 15:55 UTC, joonas-yoon commented
Oh my. I didn't know about this PR.

I requested new PR and it has no conflict to merge into master branch - https://github.com/tiangolo/fastapi/pull/5237

2023-06-26 22:42 UTC, tiangolo requested changes

2023-06-26 22:42 UTC, tiangolo commented on docs/ko/docs/features.md
> +[![Swagger UI interaction](https://camo.githubusercontent.com/b8ead36860df4f2befd2203bfa1da701c57c09ceb16e4ac6b9881d698e9950ce/68747470733a2f2f666173746170692e7469616e676f6c6f2e636f6d2f696d672f696e64
```suggestion
![Swagger UI interaction](https://fastapi.tiangolo.com/img/index/index-03-swagger-02.png)
```

For these files you can keep the original ones instead.

2023-06-26 22:47 UTC, tiangolo commented
📝 Docs preview for commit ce3ce9e8696dae4f071465d7704c3da0fc31753a at: https://649a1544ce5a7609ebde0faf--fastapi.netlify.app

2024-01-29 15:32 UTC, closed without merging