🌐 Add Korean translation for `docs/ko/docs/help-fastapi.md`
fastapi/fastapi pull request #4139
Opened 2021-11-04 04:49 UTC by kty4119

* Add Korean translation for `docs/ko/docs/help-fastapi.md`
* Related [FEATURE] Korean translations [FEATURE] Korean translations [FEATURE] Korean translations #2017

2021-11-17 05:39 UTC, DevDae requested changes
Appreciate your hard works! 🙏 
I will wait your comments, thank you!

2021-11-17 05:39 UTC, DevDae commented on docs/ko/docs/help-fastapi.md
> +  아주 간단하게 응원할 수 있습니다 (몇 번의 클릭만으로).
```suggestion
  (몇 번의 클릭만으로) 아주 간단하게 응원할 수 있습니다 .
```
I think that if the expression "몇 번의 클릭만으로" comes in front of the sentence, it is easier to understand in Korean!
feel free to my opinion! thanks 🚀

2021-11-17 05:39 UTC, DevDae commented on docs/ko/docs/help-fastapi.md
> +  [**FastAPI와 친구** 뉴스레터](https://github.com/tiangolo/fastapi/blob/master/newsletter)를 구독하여 최신 정보를 유지할 수 있습니다{.internal-link target=_blank}:
```suggestion
  [**FastAPI와 친구** 뉴스레터](https://github.com/tiangolo/fastapi/blob/master/newsletter)를 구독하여 최신 정보를 얻을 수 있습니다{.internal-link target=_blank}:
```
I think "얻다" can replace the word "유지하다". 😄

2021-11-17 05:39 UTC, DevDae commented on docs/ko/docs/help-fastapi.md
> +    - 발표 또는 새로운 툴 출시할 때 들으십시오.
I can't understand what "툴" 's mean 😭 
please give your opinion! thanks

2021-11-17 05:39 UTC, DevDae commented on docs/ko/docs/help-fastapi.md
> +  기존 [지터 채팅](https://gitter.im/tiangolo/fastapi) 이 있지만 채널과 고급기능이 없어서 대화를 하기가 조금 어렵기 때문에 지금은 디스코드가 권장되는 시스템입니다.
```suggestion
  기존 [지터 채팅](https://gitter.im/tiangolo/fastapi) 이 있지만 채널과 고급기능이 없어서 대화를 하기가 조금 어렵기 때문에 지금은 디스코드가 권장되고 있습니다.
```

2021-11-17 05:39 UTC, DevDae commented on docs/ko/docs/help-fastapi.md
> +  GitHub 이슈에서의 템플릿은 올바른 질문을 작성하도록 안내하여 더 쉽게 좋은 답변을 얻거나 질문하기 전에 스스로 문제를 해결할 수도 있습니다. 그리고 GitHub에서는 시간이 조금 걸리더라도 항상 모든 것에 답할 수 있습니다. 채팅 시스템에서는 개인적으로 그렇게 할 수 없습니다. 😅
```suggestion
  GitHub 이슈에서의 템플릿은 올바른 질문을 작성하도록 안내하여 더 쉽게 좋은 답변을 얻거나 질문하기 전에 스스로 문제를 해결할 수도 있습니다. 그리고 GitHub에서는 시간이 조금 걸리더라도 항상 모든 것에 답을 얻을 수 있습니다. 채팅 시스템에서는 개인적으로 그렇게 할 수 없습니다. 😅
```

2023-06-26 19:13 UTC, tiangolo commented
📝 Docs preview for commit b033d6471a7c2bee9b89adc8569a1057332a161a at: https://6499e34684c0620543c16807--fastapi.netlify.app

2024-03-30 23:07 UTC, tiangolo commented
Thank you! I'm still waiting for others to review this to be able to merge it, meanwhile, maybe you could help me review some of the other Korean translations, that way if they are approved by each other, I could merge them. :nerd_face: 

https://github.com/tiangolo/fastapi/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Alang-ko+label%3Aawaiting-review

Maybe @DevDae could review it again after the requested changes? :pray:

2024-04-02 14:25 UTC, junah201 approved these changes

2024-04-02 22:36 UTC, merged

2024-04-02 22:37 UTC, alejsdev commented
Thanks for the help! @kty4119 :nerd_face: :100: 

And thanks for the reviews @DevDae @junah201 :mag: