🌐 Add Korean translation for Tutorial - Testing
fastapi/fastapi pull request #4200
Opened 2021-11-22 11:19 UTC by kimjaeyoonn

This PR translates ko/docs.tutorial/testing.md in Korean.
related: #2017

Please feel free to tell me if there's something to be improved.
Thank you.

2021-11-23 00:01 UTC, DevDae requested changes
I add the reviews because of word, 애플리케이션.

If you check 파이썬 한국어 번역 and search word, application, it is translated as 응용 프로그램 and because we follows the rules of that guide (check of it on #2017 ).

Big appreciate your works 🚀

2021-11-23 05:48 UTC, kimjaeyoonn commented
> I add the reviews because of word, 애플리케이션.
> 
> If you check 파이썬 한국어 번역 and search word, application, it is translated as 응용 프로그램 and because we follows the rules of that guide (check of it on #2017 ).
> 
> Big appreciate your works 🚀


Thank you so much for reviewing. Your feedback has been accepted and updated.🤗

2021-12-16 09:18 UTC, NinaHwang requested changes
Overall, your translation is great! But I suggest you to preview the result(check out [here](https://fastapi.tiangolo.com/contributing/?h=contri#preview-the-result)) so that you can prevent any unintended format errors.

2021-12-16 09:18 UTC, NinaHwang commented on docs/ko/docs/tutorial/testing.md
> +```파이썬 hl_lines="2 12 15-18"
```suggestion
```Python hl_lines="2  12  15-18"
```
Since it works as a syntax highlighter, it is not allowed to modify this.

2021-12-16 09:18 UTC, NinaHwang commented on docs/ko/docs/tutorial/testing.md
> +!!! 팁  테스트 함수는 `async def`가 아닌 일반 `def`입니다.
```suggestion
!!! tip "팁"  테스트 함수는 `async def`가 아닌 일반 `def`입니다.
```
I suggest you to check out #3167

2021-12-16 09:18 UTC, NinaHwang commented on docs/ko/docs/tutorial/testing.md
> +!!! 참고  "기술적 세부 사항"  `from starlette.testclient import TestClient`를 통해 사용할 수 있습니다.
```suggestion
!!! note "기술적 세부사항" `from starlette.testclient import TestClient`를 통해 사용할 수 있습니다.
```

2021-12-16 09:18 UTC, NinaHwang commented on docs/ko/docs/tutorial/testing.md
> +!!! 팁  FastAPI 애플리케이션(예: 비동기 데이터베이스 함수)에 요청을 보내는 것과 별도로 테스트에서 `async` 함수를 호출하려면 고급 자습서의 [Async Tests](../advanced/async-tests.md){internal-link target=_blank} 를 살펴보십시오.
```suggestion
!!! tip "팁"  FastAPI 애플리케이션(예: 비동기 데이터베이스 함수)에 요청을 보내는 것과 별도로 테스트에서 `async` 함수를 호출하려면 고급 자습서의 [Async Tests](../advanced/async-tests.md){internal-link target=_blank} 를 살펴보십시오.
```

2021-12-16 09:18 UTC, NinaHwang commented on docs/ko/docs/tutorial/testing.md
> +```파이썬
```suggestion
```Python
```

2021-12-16 09:18 UTC, NinaHwang commented on docs/ko/docs/tutorial/testing.md
> +```파이썬
```suggestion
```Python
```

2021-12-16 09:18 UTC, NinaHwang commented on docs/ko/docs/tutorial/testing.md
> +```파이썬
```suggestion
```Python
```

2021-12-16 09:18 UTC, NinaHwang commented on docs/ko/docs/tutorial/testing.md
> +```파이썬
```suggestion
```Python
```

2021-12-16 09:18 UTC, NinaHwang commented on docs/ko/docs/tutorial/testing.md
> +!!! 정보  `TestClient`는 Pydantic 모델이 아닌 JSON으로 변환할 수 있는 데이터를 수신합니다.
```suggestion
!!! info "정보"  `TestClient`는 Pydantic 모델이 아닌 JSON으로 변환할 수 있는 데이터를 수신합니다.

```

2021-12-16 09:18 UTC, NinaHwang commented on docs/ko/docs/tutorial/testing.md
> +```콘솔
```suggestion
```console
```

2021-12-16 09:18 UTC, NinaHwang commented on docs/ko/docs/tutorial/testing.md
> +```콘솔
```suggestion
```console
```

2021-12-16 09:18 UTC, NinaHwang commented on docs/ko/docs/tutorial/testing.md
> +<a href="https://requests.readthedocs.io" class="external-link" target="_blank">요청</a>을 기반으로 하므로 매우 친숙하고 직관적입니다.
```suggestion
<a href="https://requests.readthedocs.io" class="external-link" target="_blank">Requests</a>을 기반으로 하므로 매우 친숙하고 직관적입니다.
```
Here, `Requests` is the name of a python library. So I think it'd be better not translate it.

2021-12-16 09:18 UTC, NinaHwang commented on docs/ko/docs/tutorial/testing.md
> +`TestClient`를 가져옵니다.
```suggestion
`TestClient`를 임포트합니다.
```

2022-08-27 16:54 UTC, closed without merging