🌐 Add Portuguese translation for `docs/deployment/deta.md`
fastapi/fastapi pull request #4442
Opened 2022-01-18 00:08 UTC by lsglucas

Hey 👋🏻

This PR adds the Portuguese translation of `deployment/deta.md`.

2022-01-22 13:49 UTC, LorhanSohaky requested changes
I think with these suggestions the text is more natural

2022-01-22 13:49 UTC, LorhanSohaky commented on docs/pt/docs/deployment/deta.md
> +    Você não precisa instalar Uvicorn para realizar a implantação na Deta, embora você provavelmente vai querer instalá-lo para testar seu aplicativo localmente.
```suggestion
    Você não precisa instalar Uvicorn para realizar a implantação na Deta, embora provavelmente queira instalá-lo para testar seu aplicativo localmente.
```

2022-01-22 13:49 UTC, LorhanSohaky commented on docs/pt/docs/deployment/deta.md
> +Depois de ter sua conta criada, instale Deta <abbr title="Command Line Interface application">CLI</abbr>:
```suggestion
Depois de ter sua conta criada, instale Deta <abbr title="Interface de Linha de Comando">CLI</abbr>:
```

2022-01-22 13:49 UTC, LorhanSohaky commented on docs/pt/docs/deployment/deta.md
> +    Se você tiver problemas ao instalar a CLI, verifique a <a href="https://docs.deta.sh/docs/micros/getting_started?ref=fastapi" class="external-link" target="_blank">documentação oficial Deta</a>.
```suggestion
    Se você tiver problemas ao instalar a CLI, verifique a <a href="https://docs.deta.sh/docs/micros/getting_started?ref=fastapi" class="external-link" target="_blank">documentação oficial da Deta</a>.
```

2022-01-22 13:49 UTC, LorhanSohaky commented on docs/pt/docs/deployment/deta.md
> +## Logue com a CLI
```suggestion
## Login pela CLI
```

2022-01-22 13:49 UTC, LorhanSohaky commented on docs/pt/docs/deployment/deta.md
> +Agora faça login na Deta da CLI com:
```suggestion
Agora faça login na Deta pela CLI com:
```

2022-01-22 13:49 UTC, LorhanSohaky commented on docs/pt/docs/deployment/deta.md
> +Agora, abra seu navegador no URL do `endpoint`. No exemplo acima foi `https://qltnci.deta.dev`, mas o seu será diferente.
```suggestion
Agora, abra seu navegador na URL do `endpoint`. No exemplo acima foi `https://qltnci.deta.dev`, mas o seu será diferente.
```

2022-01-22 13:49 UTC, LorhanSohaky commented on docs/pt/docs/deployment/deta.md
> +## Permitindo acesso público
```suggestion
## Permitir acesso público
```

2022-01-22 13:49 UTC, LorhanSohaky commented on docs/pt/docs/deployment/deta.md
> +Agora você pode compartilhar esse URL com qualquer pessoa e eles conseguirão acessar sua API. 🚀
```suggestion
Agora você pode compartilhar essa URL com qualquer pessoa e elas conseguirão acessar sua API. 🚀
```

2022-01-22 13:49 UTC, LorhanSohaky commented on docs/pt/docs/deployment/deta.md
> +Além disso, observe que o Deta lida corretamente com HTTPS para você, para que você não precise cuidar disso e tenha certeza de que seus clientes terão uma conexão criptografada segura. ✅ 🔒
```suggestion
Além disso, observe que a Deta lida corretamente com HTTPS para você, para que você não precise cuidar disso e tenha a certeza de que seus clientes terão uma conexão criptografada segura. ✅ 🔒
```

2022-01-22 13:49 UTC, LorhanSohaky commented on docs/pt/docs/deployment/deta.md
> +Da UI da sua documentação (você estará em um URL como `https://qltnci.deta.dev/docs`) envie um request para *operação de rota* `/items/{item_id}`.
```suggestion
Na UI da sua documentação (você estará em um URL como `https://qltnci.deta.dev/docs`) envie um request para *operação de rota* `/items/{item_id}`.
```

2022-01-22 13:49 UTC, LorhanSohaky commented on docs/pt/docs/deployment/deta.md
> +## Aprenda mais
```suggestion
## Saiba mais
```

2022-01-22 13:49 UTC, LorhanSohaky commented on docs/pt/docs/deployment/deta.md
> +Em algum momento, você provavelmente desejará armazenar alguns dados para seu aplicativo de uma forma que persista ao longo do tempo. Para isso você pode usar <a href="https://docs.deta.sh/docs/base/
```suggestion
Em algum momento, você provavelmente desejará armazenar alguns dados para seu aplicativo de uma forma que persista ao longo do tempo. Para isso você pode usar <a href="https://docs.deta.sh/docs/base/py_tutorial?ref=fastapi" class="external-link" target="_blank">Deta Base</a>, que também tem um generoso **nível gratuito**.
```

2022-01-22 13:49 UTC, LorhanSohaky commented on docs/pt/docs/deployment/deta.md
> +Voltando aos conceitos que discutimos em [Deployments Concepts](./concepts.md){.internal-link target=_blank}, veja como cada um deles seria tratado com o Deta:
```suggestion
Voltando aos conceitos que discutimos em [Deployments Concepts](./concepts.md){.internal-link target=_blank}, veja como cada um deles seria tratado com a Deta:
```

2022-01-22 13:49 UTC, LorhanSohaky commented on docs/pt/docs/deployment/deta.md
> +* **Running on startup**: Realizado pela Deta, como parte de seu serviço.
```suggestion
* **Executando na inicialização**: Realizado pela Deta, como parte de seu serviço.
```

2022-01-22 13:49 UTC, LorhanSohaky commented on docs/pt/docs/deployment/deta.md
> +* **Restarts**: Realizado pela Deta, como parte de seu serviço.
```suggestion
* **Reinicialização**: Realizado pela Deta, como parte de seu serviço.
```

2022-01-22 13:49 UTC, LorhanSohaky commented on docs/pt/docs/deployment/deta.md
> +* **Replication**: Realizado pela Deta, como parte de seu serviço.
```suggestion
* **Replicação**: Realizado pela Deta, como parte de seu serviço.
```

2022-01-22 13:49 UTC, LorhanSohaky commented on docs/pt/docs/deployment/deta.md
> +* **Memory**: Limite predefinido pela Deta, você pode contatá-los para aumentá-lo.
```suggestion
* **Memória**: Limite predefinido pela Deta, você pode contatá-los para aumentá-lo.
```

2022-01-22 13:49 UTC, LorhanSohaky commented on docs/pt/docs/deployment/deta.md
> +* **Previous steps before starting**: Não suportado diretamente, você pode fazê-lo funcionar com o sistema Cron ou scripts adicionais.
```suggestion
* **Etapas anteriores a inicialização**: Não suportado diretamente, você pode fazê-lo funcionar com o sistema Cron ou scripts adicionais.
```

2022-01-22 19:24 UTC, LorhanSohaky approved these changes

2022-01-23 19:18 UTC, cassiobotaro approved these changes

2022-01-26 14:29 UTC, izaguerreiro approved these changes

2022-02-16 00:49 UTC, LorhanSohaky approved these changes

2022-05-09 18:33 UTC, tiangolo commented
Great, thank you @lsglucas ! :bow: 

And thanks for the reviews @izaguerreiro, @cassiobotaro, @LorhanSohaky ! :cake:

2022-05-09 18:34 UTC, merged