add Chinese translation for docs/advanced/wsgi.md
fastapi/fastapi pull request #4505
Opened 2022-02-03 08:40 UTC by ASpathfinder

as title

2022-10-12 02:06 UTC, 1320555911 approved these changes

2022-10-13 13:14 UTC, Jedore requested changes
I made a bit optimization.

2022-10-18 14:56 UTC, Jedore reviewed
Please check my review

2022-10-19 01:55 UTC, ASpathfinder reviewed
reviewed

2022-10-19 03:17 UTC, Jedore approved these changes

2022-10-31 17:43 UTC, merged