Add Polish translation for `docs/pl/docs/tutorial/index.md`
fastapi/fastapi pull request #4516
Opened 2022-02-06 06:37 UTC by MKaczkow

`docs/pl/tutorial/index.md` to polish translation

2022-02-08 18:59 UTC, rafsaf requested changes
Hi @MKaczkow 

Thanks for providing this PR 👍 
First of all, I've pulled your forked project so it's not only review by looking at changes.

This is kind of "important", because we will decide what translation of topics names `Advanced User Guide` and `Tutorial - User Guide` will be, this can be hardly changed ever in the future.

 I would definitely opt for my last review comment and change in `mkdocs.yml`, I've searched through other languages like PT, they seem to follow `mkdocs.yml` syntax just like I did. Rest of comments are just to consider. Have a good day ;)

2022-02-08 18:59 UTC, rafsaf commented on docs/pl/docs/tutorial/index.md
> +# Samouczek - Instrukcja - Wprowadzenie
I would change to simpler `# Samouczek - Wprowadzenie`, see my comment in `mkdocs.yml`

2022-02-08 18:59 UTC, rafsaf commented on docs/pl/docs/tutorial/index.md
> +    And the same for each of the optional dependencies that you want to use.
Shoudn't it be in English :trollface: 
Or maybe it's some convention to leave notes alone?

2022-02-08 18:59 UTC, rafsaf commented on docs/pl/docs/tutorial/index.md
> +
Personally, I would change `Instrukcja dla zaawansowanych` na `Zaawansowany poradnik`, it's shorter and sounds better.
Also, as noted in first lines, `Samouczek` alone is better than `Samouczek - Instrukcja` (and it's not really correct in Polish grammar as far as I know, we don't use upper case letters in middle of titles in Polish, we adopted that from English). There are also few mistypes over here

So at the end of day, the fixed part may look like:

```
## Zaawansowany poradnik

Jest też **Zaawansowany poradnik**, który możesz przeczytać po lekturze tego **Samouczka**.

**Zaawansowany poradnik** opiera się na tym samouczku, używa tych samych pojęć, żeby pokazać Ci kilka dodatkowych funkcji.

Najpierw jednak  powinieneś przeczytać **Samouczek** (czytasz go teraz).

Ten rozdział jest zaprojektowany tak, że możesz stworzyć kompletną aplikację używając tylko informacji tutaj zawartych, a następnie rozszerzać ją na różne sposoby, w zależności od potrzeb, używając kilku dodatkowych pomysłów z **Zaawansowanego poradnika**.
```

2022-02-08 18:59 UTC, rafsaf commented on docs/pl/mkdocs.yml
> +  - tutorial/index.md
And this is something I would **Definitely** change to 
```yml
- Samouczek:
  - tutorial/index.md
```
We should avoid naming this topic in English, its much better to use Polish here. FastAPI docs are smart enough to fill docs we don't cover in English even if we use Polish name (screenshot), this is probably detected by `tutorial/index.md`.

See current screenshot (I pulled your forked repo and changed code like above).


![image](https://user-images.githubusercontent.com/51059348/153054754-7be7e767-da9c-4ec8-96a7-a6dd2eeffe14.png)

2022-02-10 10:20 UTC, MKaczkow commented
Hi @rafsaf,
I've applied changes you suggested, hope everything is fine this time.

Thank you for reviewing this PR :-)

2022-02-10 10:53 UTC, rafsaf approved these changes
LGTM :P

Thanks again, now I belive we should wait for one more person (Polish native speaker) to approve it and this can be merged.

2022-03-12 22:31 UTC, kiwimic approved these changes
As polish native speaker I can approve that this polish translation is correct

2022-05-10 04:10 UTC, tiangolo commented
Awesome, thanks @MKaczkow ! :cake: 

And thanks for the reviews @kiwimic and and @rafsaf ! :bow:

2022-05-10 04:12 UTC, merged