🌐 Add Korean translation for `advanced/sub-applications.md`
fastapi/fastapi pull request #4543
Opened 2022-02-09 06:51 UTC by NinaHwang

Test complete

    related: #2017

2022-04-20 02:21 UTC, NinaHwang commented on docs/ko/docs/advanced/sub-applications.md
> +만약 각각의 독립적인 OpenAPI와 문서 UI를 갖는 두 개의 독립적인 FastAPI 애플리케이션이 필요하다면, 메인 어플리케이션에 하나 (또는 그 이상의) 하위-어플리케이션(들)을 “마운트"해서 사용할 수 있습니다.
`응용프로그램` 으로 통일했습니다. 감사합니다.

2022-05-10 00:30 UTC, tiangolo requested changes
Awesome! Can you please remove the `.DS_Store` file?

2023-06-26 23:15 UTC, tiangolo commented
📝 Docs preview for commit 74545f0ce43f419e40bda4198b3361252ca45464 at: https://649a1be8d1bbbc13f560f9af--fastapi.netlify.app

2024-03-30 23:01 UTC, tiangolo commented
Thank you! I'm still waiting for others to review this to be able to merge it, meanwhile, maybe you could help me review some of the other Korean translations, that way if they are approved by each other, I could merge them. :nerd_face: 

https://github.com/tiangolo/fastapi/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Alang-ko+label%3Aawaiting-review

2025-03-30 01:43 UTC, peacekimjapan approved these changes
LGTM

2025-06-05 08:25 UTC, YuriiMotov requested changes

2025-06-05 08:25 UTC, YuriiMotov commented on docs/ko/docs/advanced/sub-applications.md
> +```
```suggestion
{* ../../docs_src/sub_applications/tutorial001.py hl[3, 6:8] *}
```

2025-06-05 08:25 UTC, YuriiMotov commented on docs/ko/docs/advanced/sub-applications.md
> +```
```suggestion
{* ../../docs_src/sub_applications/tutorial001.py hl[11, 14:16] *}
```

2025-06-05 08:25 UTC, YuriiMotov commented on docs/ko/docs/advanced/sub-applications.md
> +```
```suggestion
{* ../../docs_src/sub_applications/tutorial001.py hl[11, 19] *}
```

2025-06-05 09:18 UTC, hard-coders approved these changes
It's been created a long time ago. 🤣
LGTM!

2025-06-05 09:48 UTC, YuriiMotov approved these changes

2025-06-12 06:37 UTC, sodaMelon approved these changes
LGTM👍  (i m korean)

2025-06-12 06:43 UTC, sodaMelon commented
hi @YuriiMotov @alejsdev , could check this PR? 
I think it's time to merge.🎶 (well it's been a long time lol)

2025-06-12 07:30 UTC, tiangolo approved these changes

2025-06-12 07:32 UTC, merged