🌐 Add Ukrainian translation for `docs/uk/docs/tutorial/first-steps.md`
fastapi/fastapi pull request #4569
Opened 2022-02-14 10:39 UTC by ss-o-furda

related: #1748

2023-04-26 23:20 UTC, MariiaRomanuik reviewed
You've done a great job in translation. l like it) Here are couple comments l would suggest

2023-06-26 23:57 UTC, tiangolo commented
📝 Docs preview for commit 43faacc1f83af8cbc17e434cdd88e3d3475049d2 at: https://649a25c61636a41a28534cdf--fastapi.netlify.app

2023-07-18 14:39 UTC, romashevchenko requested changes
Hi, 
I'm a part of the DreamProIT Team and a native speaker. I have reviewed this translation and made some suggestions. I hope they will make the text better.

2023-07-18 14:39 UTC, romashevchenko commented on docs/uk/docs/tutorial/first-steps.md
> +Відкрийте свій браузер за адресою <a href="http://127.0.0.1:8000" class="external-link" target="_blank">http://127.0.0.1:8000</a>.
```suggestion
Відкрийте у своєму браузері цю адресу <a href="http://127.0.0.1:8000" class="external-link" target="_blank">http://127.0.0.1:8000</a>.
```

2023-07-18 14:39 UTC, romashevchenko commented on docs/uk/docs/tutorial/first-steps.md
> +Це визначення схеми включає ваші шляхи API, можливі параметри, які вони беруть, тощо.
```suggestion
Це визначення схеми включає ваші шляхи API, можливі параметри, які вони приймають, тощо.
```

2023-07-18 14:39 UTC, romashevchenko commented on docs/uk/docs/tutorial/first-steps.md
> +    Ви розміщуєте його поверх функції. Як гарний декоративний капелюх (я здогадуюсь, звідки пішов цей термін).
```suggestion
    Ви розміщуєте його поверх функції. Як гарний декоративний капелюх (мабуть, звідси пішов цей термін).
```

2023-07-18 14:39 UTC, romashevchenko commented on docs/uk/docs/tutorial/first-steps.md
> +Існує багато інших об’єктів і моделей, які автоматично конвертуються в JSON (включаючи ORM тощо). Спробуйте використовувати свої улюблені, імовірно, що вони вже підтримуються.
```suggestion
Існує багато інших об’єктів і моделей, які автоматично конвертуються в JSON (включаючи ORM тощо). Спробуйте використовувати свої улюблені, дуже ймовірно, що вони вже підтримуються.
```

2024-01-15 16:12 UTC, tiangolo commented
As this PR had requested changes to be applied but has been inactive for a while, it's now going to be closed. But if there's anyone interested, feel free to create a new PR.

2024-01-15 16:12 UTC, closed without merging