🌐 Add Ukrainian translation for `docs/uk/docs/tutorial/path-params.md`
fastapi/fastapi pull request #4570
Opened 2022-02-14 12:17 UTC by ss-o-furda

related: https://github.com/tiangolo/fastapi/issues/1748

2023-06-26 22:43 UTC, tiangolo commented
📝 Docs preview for commit 8df3c84eb0ec176d0012e49e798f898ec764aef7 at: https://649a148205f6af108fd6d17d--fastapi.netlify.app

2023-06-27 06:01 UTC, mezgoodle commented on docs/uk/docs/tutorial/path-params.md
> +    Це надасть вам підтримку редактора всередині вашої функції, з перевіркою помилок, автозаповненням, тощо.
```suggestion
    Це надасть вам підтримку редактора всередині вашої функції, з перевіркою помилок, автозаповненням тощо.
```

2023-06-27 06:04 UTC, mezgoodle commented on docs/uk/docs/tutorial/path-params.md
> +    Знову ж таки, лише з тим самим оголошенням типу Python, **FastAPI** надає вам автоматичну інтерактивну документацію (інтегруючи інтерфейс користувача Swagger).
```suggestion
    Знову ж таки, лише з тим самим оголошенням типу Python, **FastAPI** надає вам автоматичну інтерактивну документацію (інтегруючи Swagger UI).
```

2023-06-27 06:10 UTC, mezgoodle commented on docs/uk/docs/tutorial/path-params.md
> +Оскільки доступні значення для *параметра шляху* попередньо визначені, інтерактивна документація може добре показати їх:
```suggestion
Оскільки доступні значення для *параметра шляху* попередньо визначені, інтерактивна документація може показати їх:
```

2023-06-27 06:13 UTC, mezgoodle commented on docs/uk/docs/tutorial/path-params.md
> +OpenAPI не підтримує спосіб оголосити *параметр шляху*, щоб він містив всередині *шлях*, оскільки це може призвести до сценаріїв, які важко перевірити та визначити.
```suggestion
OpenAPI не підтримує спосіб оголошення *параметра шляху*, щоб він містив всередині *шлях*, оскільки це може призвести до сценаріїв, які важко перевірити та визначити.
```

2023-06-27 06:15 UTC, mezgoodle commented on docs/uk/docs/tutorial/path-params.md
> +* Анотація API та автоматична документація
```suggestion
* Підтримку редактора: перевірка помилок, автозаповнення, тощо
* "<abbr title="converting the string that comes from an HTTP request into Python data">Парсинг</abbr>" даних
* Валідацію даних
* Анотації API та автоматична документацію
```

2023-06-27 06:15 UTC, mezgoodle commented on docs/uk/docs/tutorial/path-params.md
> +Ви можете оголосити "параметри" шляху або "змінні" з тим самим синтаксисом, що використовується строками Python:
```suggestion
Ви можете оголосити "параметри" шляху або "змінні" з тим самим синтаксисом, що використовується стрічками Python:
```

2023-07-18 13:35 UTC, romashevchenko requested changes
Hi there! 
I'm Romana from DreamProIT. As a native speaker, I have reviewed the translation and made a few suggestions to improve it.

2023-07-18 13:35 UTC, romashevchenko commented on docs/uk/docs/tutorial/path-params.md
> +Імпортуйте `Enum` та створюйте підклас, який успадковується від `str` та від `Enum`.
```suggestion
Імпортуйте `Enum` та створіть підклас, який успадковується від `str` та від `Enum`.
```

2023-07-18 13:35 UTC, romashevchenko commented on docs/uk/docs/tutorial/path-params.md
> +Значенням *параметра шляху* буде *членом перерахування*.
```suggestion
Значення *параметра шляху* буде *членом перерахування*.
```

2023-08-07 15:45 UTC, rostik1410 commented on docs/uk/docs/tutorial/path-params.md
> +Ви можете оголосити "параметри" шляху або "змінні" з тим самим синтаксисом, що використовується строками Python:
```suggestion
Ви можете оголосити "параметри" шляху або "змінні" з тим самим синтаксисом, що використовується рядками Python:
```

2023-08-07 15:50 UTC, rostik1410 commented on docs/uk/docs/tutorial/path-params.md
> +Значенням *параметра шляху* буде *членом перерахування*.
@romashevchenko Тоді вже краще `членом переліку` або `членом перелічення`

2024-01-15 16:12 UTC, closed without merging