🌐 Add Ukrainian translation for `docs/uk/docs/tutorial/query-params.md`
fastapi/fastapi pull request #4572
Opened 2022-02-14 13:23 UTC by ss-o-furda

related: https://github.com/tiangolo/fastapi/issues/1748

2023-06-26 22:40 UTC, tiangolo commented
📝 Docs preview for commit 317c1d6f1ecff747c9738de5f77adf450c1252be at: https://649a13ae05f6af1016d6cef2--fastapi.netlify.app

2023-07-18 13:50 UTC, romashevchenko requested changes
Hi there!
It's Romana from DreamProIT. I've reviewed your translation and added a few suggestions.

2023-07-18 13:50 UTC, romashevchenko commented on docs/uk/docs/tutorial/query-params.md
> +Оскільки вони є частиною URL-адреси, вони є «природними» рядками.
```suggestion
Оскільки вони є частиною URL-адреси, вони є «природно» рядками.
```

2023-08-07 15:21 UTC, rostik1410 commented
@ss-o-furda @romashevchenko  Hey, will anyone finish this?) I'm ready to approve, let's add more Ukraine translates. Stay safe, hope you guys are okay.
P.S. If nobody wants to finish could I create my own PR  based on this one with addressed comments?

2024-01-15 16:12 UTC, tiangolo commented
As this PR had requested changes to be applied but has been inactive for a while, it's now going to be closed. But if there's anyone interested, feel free to create a new PR.

2024-01-15 16:12 UTC, closed without merging