Only use default parameter values for path parameters (#450)
fastapi/fastapi pull request #464
Opened 2019-08-25 13:06 UTC by jonathanunderwood

This change allows endpoint functions to be defined with parameters with defaults, but for those defaults to be ignored if the function parameter subsequently appears as a path parameter. The default value is only operative if the parameter is a query parameter.

This change includes a new set of tests for this functionality.

2019-08-25 13:58 UTC, jonathanunderwood commented
WIP: this approach is too aggressive as it ignores all `Path()` specifications. Will fix later.

2019-08-26 07:13 UTC, jonathanunderwood commented
As far as I can see this should be mergeable. The travis runs are raising errors with incorrectly sorted imports in masses of other files unrelated to this commit, so I'm not sure what's going on there.

2019-08-26 07:23 UTC, euri10 commented
Install locally with flit as described in the doc

Le lun. 26 août 2019 à 9:13 AM, jonathanunderwood <notifications@github.com>
a écrit :

> As far as I can see this should be mergeable. The travis runs are raising
> errors with incorrectly sorted imports in masses of other files unrelated
> to this commit, so I'm not sure what's going on there.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tiangolo/fastapi/pull/464?email_source=notifications&email_token=AAINSPXBZIY3HT32XIEBNETQGN7BNA5CNFSM4IPI77S2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5DPYRQ#issuecomment-524745798>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAINSPUAYBDIVXS5M2Z4QFLQGN7BNANCNFSM4IPI77SQ>
> .
>

2019-08-26 07:25 UTC, jonathanunderwood commented
OK, fixed the import order issue. All should be good now.

2019-08-26 07:26 UTC, euri10 commented
> OK, fixed the import order issue. All should be good now.

been bitten by it before too ;) https://github.com/tiangolo/fastapi/issues/38#issuecomment-464840923

2019-09-06 08:25 UTC, jonathanunderwood commented
@tiangolo any feedback on this one?

2019-09-29 14:25 UTC, tiangolo requested changes
Good job! Thanks for your contribution! :rocket: :cake: :clap: 

I hadn't thought about this use case but I see how it could be useful in those cases.

LGTM in general :tada: 

Just a couple of nitpick formatting requests, I inlined them all, so you just have to "accept" them. Sorry for the many suggestions, GitHub doesn't let me do multiline suggestions :grimacing:

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +app = FastAPI()  # pylint: disable=invalid-name
```suggestion
app = FastAPI()
```

We are not using Pylint for linting the internal code, only `mypy`, `black`, and `isort`, so it's safe to remove this comment.

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +user_router = APIRouter()  # pylint: disable=invalid-name
```suggestion
user_router = APIRouter()
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +item_router = APIRouter()  # pylint: disable=invalid-name
```suggestion
item_router = APIRouter()
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +client = TestClient(app)  # pylint: disable=invalid-name
```suggestion
client = TestClient(app)
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +    """Check that /users returns expected data
```suggestion
    """Check that /users returns expected data"""
```

We can put this on the same line.

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +
```suggestion
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +    """
```suggestion
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +    """Check that /users/{user_id} returns expected data
```suggestion
    """Check that /users/{user_id} returns expected data"""
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +
```suggestion
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +    """
```suggestion
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +    """Check that /items returns expected data
```suggestion
    """Check that /items returns expected data"""
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +
```suggestion
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +    """
```suggestion
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +    """Check that /items returns expected data with user_id specified
```suggestion
    """Check that /items returns expected data with user_id specified"""
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +
```suggestion
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +    """
```suggestion
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +    """Check that /items/{}item_id} returns expected data
```suggestion
    """Check that /items/{item_id} returns expected data"""
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +
```suggestion
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +    """
```suggestion
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +    """Check that /items/{}item_id} returns expected data with user_id specified
```suggestion
    """Check that /items/{item_id} returns expected data with user_id specified"""
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +
```suggestion
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +    """
```suggestion
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +    """Check that /users/{user_id}/items returns expected data
```suggestion
    """Check that /users/{user_id}/items returns expected data"""
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +
```suggestion
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +    """
```suggestion
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +    """Check that /users/{user_id}/items returns expected data
```suggestion
    """Check that /users/{user_id}/items returns expected data"""
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +
```suggestion
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +    """
```suggestion
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +    """Check that the user_id is a required path parameter under /users
```suggestion
    """Check that the user_id is a required path parameter under /users"""
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +
```suggestion
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +    """
```suggestion
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +    """Check that the user_id is an optional query parameter under /items
```suggestion
    """Check that the user_id is an optional query parameter under /items"""
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +
```suggestion
```

2019-09-29 14:25 UTC, tiangolo commented on tests/test_infer_param_optionality.py
> +    """
```suggestion
```

2019-09-29 14:26 UTC, tiangolo commented
Thanks for the help here @euri10 ! :bowing_man: 

@dmontagu if you have time, could you give this a quick review?

2019-09-29 16:42 UTC, jonathanunderwood commented
All suggested formatting changes have been added.

2019-09-29 16:50 UTC, jonathanunderwood commented
MyPy tests are now failing in code unrelated to this change, which is strange.

2019-09-29 21:56 UTC, tiangolo commented
Thanks for the format changes!

Yeah, the same `mypy` error just happened in a couple of other PRs. It's related to some changes in a new version of `mypy`. I just rebased your branch from master, as it has those fixes (from these recent PRs). Let's see if that fixes it.

2019-09-29 22:00 UTC, tiangolo approved these changes
LGTM! :tada: :cake:

2019-09-29 22:03 UTC, merged

2019-09-29 22:04 UTC, tiangolo commented
Thanks for your contribution @jonathanunderwood ! :cake: :tada: :rocket:

2019-09-30 17:20 UTC, jonathanunderwood commented
Thanks for taking the time to review this change, much appreciated.