doc: remove unnecessary else
fastapi/fastapi pull request #4693
Opened 2022-03-17 05:18 UTC by adriangb

2022-04-20 09:39 UTC, AlexandreBiguet approved these changes

2022-05-11 17:50 UTC, tiangolo requested changes
As this is an example source file for the docs, it would require an update in the source docs at `additonal-responses.md` that use it too, to highlight the new line.

2022-05-27 14:42 UTC, adriangb commented
Sorry for the delay, done now @tiangolo

2022-08-26 13:32 UTC, tiangolo commented
Awesome, thank you @adriangb! :cake: :coffee:

2022-08-26 13:32 UTC, merged