🌐 Add translation to Portuguese for `tutorial/handling-errors.md`
fastapi/fastapi pull request #4769
Opened 2022-04-06 20:02 UTC by frnsimoes

2022-04-06 20:04 UTC, frnsimoes commented on docs/pt/docs/tutorial/handling-errors.md
> +O benefício de apontar uma exceção em vez de retornar um valor ficará mais evidente na seção sobre Dependências e Segurança.
Aqui decidi traduzir `raise` por `apontar`. Me avisem caso `levantar` seja uma opção que melhor se adeque ao padrão das traduções, por favor.

2022-04-11 20:50 UTC, cassiobotaro commented on docs/pt/docs/tutorial/handling-errors.md
> +O benefício de apontar uma exceção em vez de retornar um valor ficará mais evidente na seção sobre Dependências e Segurança.
Normalmente eu vejo o verbo lançar neste caso.

2022-04-11 20:52 UTC, cassiobotaro commented
Acho que faltou modificar  o arquivo `docs/pt/mkdocs.yml` adicionando este arquivo.

2022-04-12 23:15 UTC, frnsimoes commented on docs/pt/docs/tutorial/handling-errors.md
> +O benefício de apontar uma exceção em vez de retornar um valor ficará mais evidente na seção sobre Dependências e Segurança.
Show, Cássio. Vou fazer a alteração.

2022-04-12 23:48 UTC, frnsimoes commented on docs/pt/docs/tutorial/handling-errors.md
> +O benefício de apontar uma exceção em vez de retornar um valor ficará mais evidente na seção sobre Dependências e Segurança.
Feito! @cassiobotaro

2022-04-26 23:01 UTC, cassiobotaro requested changes

2022-04-26 23:33 UTC, cassiobotaro approved these changes
LGTM

2022-05-16 01:44 UTC, lsglucas requested changes

2022-05-16 01:44 UTC, lsglucas commented on docs/pt/docs/tutorial/handling-errors.md
> +!!! dica
```suggestion
!!! tip "Dica"
```

2022-05-16 01:44 UTC, lsglucas commented on docs/pt/docs/tutorial/handling-errors.md
> +Quando a requisição contém data inválida, **FastAPI** internamente lança para o `RequestValidationError`.
```suggestion
Quando a requisição contém dados inválidos, **FastAPI** internamente lança para o `RequestValidationError`.
```

2022-05-16 01:44 UTC, lsglucas commented on docs/pt/docs/tutorial/handling-errors.md
> +Para sobreescrevê-lo, importe o `RequestValidationError` e use-o com o `@app.exception_handler(RequestValidationError)` para decorar o manipulador de exceções.
```suggestion
Para sobrescrevê-lo, importe o `RequestValidationError` e use-o com o `@app.exception_handler(RequestValidationError)` para decorar o manipulador de exceções.
```

2022-05-16 01:44 UTC, lsglucas commented on docs/pt/docs/tutorial/handling-errors.md
> +!!! atenção
```suggestion
!!! warning "Aviso"
```

2022-05-16 01:44 UTC, lsglucas commented on docs/pt/docs/tutorial/handling-errors.md
> +!!! nota "Detalhes Técnicos"
```suggestion
!!! note "Detalhes Técnicos"
```

2022-06-28 16:01 UTC, jonatasoli approved these changes

2022-08-18 15:57 UTC, tiangolo commented
Thanks for the contribution @frnsimoes! :cake: 

And thanks for the reviews and suggestions @lsglucas, @cassiobotaro, @jonatasoli! :coffee:

2022-08-18 16:02 UTC, merged