Translation: tutorial/index.md [dutch/nl]
fastapi/fastapi pull request #4770
Opened 2022-04-07 00:09 UTC by thepieterdc

This PR translates the `tutorial/index.md` page of the documentation into Dutch.

2023-04-30 23:30 UTC, tony1658 requested changes

2023-04-30 23:30 UTC, tony1658 commented on docs/nl/docs/tutorial/index.md
> +De **Geavanceerde handleiding** steunt op de concepten die in deze handleiding worden geïntroduceerd en leert u kennismaken met extra functionaliteit, maar het is aangeraden om eerst de **Tutorial -
Suggestion: De **Geavanceerde handleiding** bouwt voort op de concepten die in deze handleiding zijn geïntroduceerd

2023-04-30 23:30 UTC, tony1658 commented on docs/nl/docs/tutorial/index.md
> +Elk hoofdstuk bouwt verder op de voorgaande, maar de handleiding is onderverdeeld in aparte onderwerpen, zodat u rechtstreeks naar het specifieke onderwerp kan gaan voor uw noden.
The word `noden` is fine but as far as I know not common in the Netherlands. Perhaps more common Belgium?

I suggest using `benodigheden` instead.

2023-04-30 23:30 UTC, tony1658 commented on docs/nl/docs/tutorial/index.md
> +De volledige handleiding is dusdanig opgesteld dat u een volledige applicatie kan bouwen met enkel de **Tutorial - Handleiding**, waarna u die op verschillende manieren kan uitbreiden door, afhankeli
I suggest using `benodigheden` instead of `noden`.

2023-06-26 23:58 UTC, tiangolo commented
📝 Docs preview for commit 88b00c05d5eca74f5425ec3f9f46d5bcea1dc33b at: https://649a260cc011271a21a55cd6--fastapi.netlify.app

2024-01-31 14:13 UTC, tiangolo commented
As this PR had requested changes to be applied but has been inactive for a while, it's now going to be closed. But if there's anyone interested, feel free to create a new PR.

2024-01-31 14:13 UTC, closed without merging