🌐 Add Korean translation for advanced/behind-a-proxy.md
fastapi/fastapi pull request #4774
Opened 2022-04-09 10:27 UTC by NinaHwang

Test complete

related: #2017

2022-05-11 17:44 UTC, tiangolo requested changes
Awesome! 🤩

Can you please remove the `docs/ko/docs/advanced/.DS_Store` file?

2023-06-26 22:02 UTC, tiangolo commented
📝 Docs preview for commit c4a397af331cfc5c138dae3cc8f6d0959d470a15 at: https://649a0acc5638650724126b7f--fastapi.netlify.app

2024-03-30 23:07 UTC, tiangolo commented
Thank you! I'm still waiting for others to review this to be able to merge it, meanwhile, maybe you could help me review some of the other Korean translations, that way if they are approved by each other, I could merge them. :nerd_face: 

https://github.com/tiangolo/fastapi/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Alang-ko+label%3Aawaiting-review

2024-11-03 06:55 UTC, BORA040126 reviewed
미숙하지만 검토해 주시면 감사하겠습니다

2024-11-03 06:55 UTC, BORA040126 commented on docs/ko/docs/advanced/behind-a-proxy.md
> +당신의 응용프로그램에서는 인식할 수 없는 경로 접두사를 추가하는 설정을 적용해서 Traefik 또는 Nginx와 같은 **프록시** 서버를 사용해야 하는 경우가 있습니다.
'경우에 따라 Traefik 또는 Nginx와 같은 **프록시** 서버를 사용해야 할 수 있으며, 이때 애플리케이션이 인식하지 못하는 추가 경로 접두사를 설정에 추가하는 경우가 있습니다.'로 수정하면 이해하기 쉬울 수 있습니다.

2024-11-03 06:55 UTC, BORA040126 commented on docs/ko/docs/advanced/behind-a-proxy.md
> +당신의 응용프로그램에서는 인식할 수 없는 경로 접두사를 추가하는 설정을 적용해서 Traefik 또는 Nginx와 같은 **프록시** 서버를 사용해야 하는 경우가 있습니다.
'응용 프로그램' 대신 '애플리케이션'을 주로 다른 문서에서 사용하고 있는 것 같습니다.

2024-11-03 06:55 UTC, BORA040126 commented on docs/ko/docs/advanced/behind-a-proxy.md
> +잘린 경로 접두사를 갖는 프록시가 있다는 것은, 당신의 코드에서 `/app`으로 경로를 선언한 뒤에, `/api/v1`와 같은 경로 아래에 당신의 **FastAPI** 응용프로그램을 담는 새로운 계층을 최상단(프록시) 위에 추가한다는 것을 의미합니다.
'Having a proxy with a stripped path prefix, in this case, means that you could declare a path at /app in your code, but then, you add a layer on top (the proxy) that would put your FastAPI application under a path like /api/v1.'를 참고해서 번역을 한 번 더 검토해 주시면 감사하겠습니다.

2024-11-03 06:55 UTC, BORA040126 commented on docs/ko/docs/advanced/behind-a-proxy.md
> +여기까지, 모든 것은 정상적으로 작동할 것입니다.
'여기까지->여기까지는'으로 바꾸면 자연스러울 것 같습니다.

2025-02-15 11:02 UTC, closed without merging