APIKey scheme name default changed
fastapi/fastapi pull request #4791
Opened 2022-04-12 19:42 UTC by BilalAlpaslan

2022-04-12 19:50 UTC, BilalAlpaslan commented
related issue #4635

2022-05-12 01:04 UTC, yezz123 approved these changes
Its look clean and work as expected 🚀

2022-05-16 20:41 UTC, JESSIEALOPAY approved these changes

2022-07-26 21:00 UTC, yberad approved these changes

2023-02-28 07:58 UTC, BilalAlpaslan commented
related discussion: https://github.com/tiangolo/fastapi/discussions/6335

2023-06-06 22:57 UTC, BilalAlpaslan commented
@Kludex can u review

2023-10-08 19:43 UTC, hasansezertasan approved these changes

2023-10-08 19:43 UTC, esrefzeki approved these changes

2023-10-18 15:12 UTC, hasansezertasan commented
I think it's stuck.

2023-11-17 06:55 UTC, BilalAlpaslan commented
Hi @tiangolo, it almost 2 year and still this little bug in fastapi: https://github.com/tiangolo/fastapi/discussions/9012#discussioncomment-7553951
can u review it :grin:

2024-01-26 08:42 UTC, karakuss approved these changes

2024-02-01 12:21 UTC, BilalAlpaslan commented
Hi @tiangolo. People can not create a multiple APIKey. Actually this pr report a bug not an feature request.  I mentioned that because this pr has a feature label :upside_down_face:  .

2024-02-21 12:05 UTC, zekiyasin reviewed
nice

2024-02-21 12:10 UTC, emrahyurttutan commented
nice @BilalAlpaslan

2024-02-21 12:11 UTC, emrahyurttutan approved these changes

2024-02-21 12:13 UTC, zekiyasin approved these changes

2024-03-01 15:52 UTC, YuriiMotov requested changes
This solution will fail if you use `APIKeyHeader` and `APIKeyQuery` (two different classes) with the same token key name:
```
from fastapi import FastAPI, Security
from fastapi.security import api_key

app = FastAPI()

api_key_header = api_key.APIKeyHeader(name="key_a")
api_key_query = api_key.APIKeyQuery(name="key_a")


@app.get("/a")
async def a(auth_token: str = Security(api_key_header)):
    pass


@app.get("/b")
async def b(auth_token: str = Security(api_key_query)):
    pass
```

`name` attribute of `APIKeyHeader` (and others) is a name of parameter that contain token.

I think this will solve the problem:
```
        self.scheme_name = scheme_name or f"{self.__class__.__name__}_{name}"
```

2024-03-21 15:04 UTC, BilalAlpaslan commented
> This solution will fail if you use `APIKeyHeader` and `APIKeyQuery` (two different classes) with the same token key name:
> 
> ```
> from fastapi import FastAPI, Security
> from fastapi.security import api_key
> 
> app = FastAPI()
> 
> api_key_header = api_key.APIKeyHeader(name="key_a")
> api_key_query = api_key.APIKeyQuery(name="key_a")
> 
> 
> @app.get("/a")
> async def a(auth_token: str = Security(api_key_header)):
>     pass
> 
> 
> @app.get("/b")
> async def b(auth_token: str = Security(api_key_query)):
>     pass
> ```
> 
> `name` attribute of `APIKeyHeader` (and others) is a name of parameter that contain token.
> 
> I think this will solve the problem:
> 
> ```
>         self.scheme_name = scheme_name or f"{self.__class__.__name__}_{name}"
> ```

Actually no one can create two variables with the same name. The same way, people doshould not be able to create two schema names with same name.  Maybe we can throw an error when someone used the same names more than two.

2024-03-21 15:42 UTC, YuriiMotov commented
Sorry, I don't quite understand what you mean.

In the example I mentioned before, endpoint "/a" expects the authorization token to be passed as a Header parameter with the name `key_a`. Endpoint "/b" expects the authorization token to be passed as a Query parameter with the name `key_a`. It's absolutely OK.
And talking about 'schema name', in our case schema name is not specified by user (parameter `scheme_name` is omitted), so it's FastAPI who sets this name. And it should be unique for all combinations of `Security scheme` and `parameter name`.

2025-07-09 07:16 UTC, YuriiMotov commented
I've looked at this PR again, and now I think it should be one of two solutions:
* "class name" + "param name" + "auto error"
* "class name" + index for duplicates. For example, for initial code example we will have `APIKeyHeader` and `APIKeyHeader_2`

I think that second is more preferable since it's not braking change (it will not change scheme name if there is only one instance of this class in the project).
To implement this I think we can use counter stored in class attribute.

@BilalAlpaslan, what do you think?

2025-08-08 22:20 UTC, closed without merging