Improve translation for spanish type-hints docs
fastapi/fastapi pull request #4910
Opened 2022-05-14 16:24 UTC by LeSZ0

2022-05-21 17:32 UTC, SepehrRasouli approved these changes

2022-08-26 14:02 UTC, jovicon approved these changes

2024-01-02 18:58 UTC, LeSZ0 commented
@tiangolo I think we can merge this PR now

2024-01-02 18:59 UTC, tiangolo commented
📝 Docs preview for commit f76cbf1ad78639a9dccacc3bedc4cd31f0efc986 at: https://c4e3d175.fastapitiangolo.pages.dev

2024-01-15 19:20 UTC, tiangolo requested changes
Thanks for the work! ☕ 

I have a few comments, several in line, but not all. Please revert all the inline code blocks, they should be included from the original examples. You can read more of the guidelines here: https://fastapi.tiangolo.com/contributing/#translations

2024-01-15 19:20 UTC, tiangolo commented on docs/es/docs/python-types.md
> +print(get_full_name("john", "doe"))
```suggestion
{!../../../docs_src/python_types/tutorial001.py!}
```

Please revert these changes, the original examples should be shown.

2024-01-15 19:20 UTC, tiangolo commented on docs/es/docs/python-types.md
> +    full_name = first_name.title() + " " + last_name.title()
The same here, please revert this change.

2024-01-15 19:20 UTC, tiangolo commented on docs/es/docs/python-types.md
>  ```
Same here.

2024-01-15 19:20 UTC, tiangolo commented on docs/es/docs/python-types.md
> +first_name: str, last_name: str
And this one

2024-01-15 19:20 UTC, tiangolo commented on docs/es/docs/python-types.md
> +<a href="https://pydantic-docs.helpmanual.io/" class="external-link" target="_blank">Pydantic</a> es una libreria de Python utilizada para llevar a cabo validación de datos.
Please revert the word "librería", even though it's sometimes used in Spanish, it's incorrect, it should be "biblioteca", but that's not commonly used, that's why I use the technical word in English.

2024-01-15 19:20 UTC, tiangolo commented on docs/es/docs/python-types.md
> +Luego creas un instancia de esa clase con algunos valores y Pydantic los validará, los convertirá al tipo apropiado (si ese es el caso) y te dará un objeto con todos los datos.
Please revert the word "instancia", even though it's sometimes used in Spanish, it's actually incorrect, "instance" means "ejemplar", that's why I keep the technical term in English.

2024-01-15 19:20 UTC, tiangolo commented on docs/es/docs/python-types.md
> -    Para aprender más sobre <a href="https://pydantic-docs.helpmanual.io/" class="external-link" target="_blank">Pydantic mira su documentación</a>.
Please revert removing this info box.

2024-01-15 19:20 UTC, tiangolo commented on docs/es/docs/python-types.md
> +**Información**
Please revert removing this info box.

2024-02-16 03:14 UTC, tiangolo commented
As this PR had requested changes to be applied but has been inactive for a while, it's now going to be closed. But if there's anyone interested, feel free to create a new PR.

2024-02-16 03:14 UTC, closed without merging