Update applications.py
fastapi/fastapi pull request #5008
Opened 2022-06-09 16:21 UTC by tsv19su254052

corrected indents and hyphens

2022-06-10 11:52 UTC, JarroVGIT requested changes
Recommendation: retract as it makes the code not PEP-8 compliant.

2022-06-10 11:52 UTC, JarroVGIT commented on fastapi/applications.py
> +            self.openapi_schema = get_openapi(title=self.title,
I have left a remark here: https://github.com/tiangolo/fastapi/pull/5016#issuecomment-1152278151

2022-06-10 13:58 UTC, tsv19su254052 commented
OK. It is a C++ Style.
I just wanted to show my style. If these changes do not comply with the PEP-8 standard, then you can refuse them

2022-06-12 22:59 UTC, MarcusVinniciuss approved these changes

2022-08-26 13:40 UTC, tiangolo commented
Thanks for the interest! FastAPI uses Black for formatting, and pre-commit to enforce it. In fact, it fixes the format and commits on top of PRs in CI, that's why you see a commit on top of yours and why it seems the PR has no changes.

As format is already handled, I'll close this PR now. But thanks for the interest! :coffee:

2022-08-26 13:40 UTC, closed without merging