🌐🇵🇱 Add Polish translation for `docs/pl/docs/tutorial/first-steps.md`
fastapi/fastapi pull request #5024
Opened 2022-06-11 16:38 UTC by Valaraucoo

Created `docs/pl/tutorial/first-steps.md` 🇵🇱 Polish translation.

2022-06-21 19:54 UTC, dominikwozniak approved these changes

2022-07-05 17:27 UTC, BartoszCki requested changes
In general it's OK but there are several places when translations don't feel natural

2022-07-05 17:27 UTC, BartoszCki commented on docs/pl/docs/tutorial/first-steps.md
> +#### "Schemat"
IMHO some keywords, including word "schema", should not be translated

2022-07-05 17:27 UTC, BartoszCki commented on docs/pl/docs/tutorial/first-steps.md
> +OpenAPI definiuje schemat API dla Twojego API. A ten schemat zawiera definicje (lub "schematy") danych wysyłanych i odbieranych przez Twój interfejs API przy użyciu **Schematu JSON**, standardu dla s
Translating  "JSON Schema" to "schemat JSON" makes no sense as it (JSON Schema) is a proper noun

2022-07-05 17:27 UTC, BartoszCki commented on docs/pl/docs/tutorial/first-steps.md
> +    "Ścieżka" jest zazwyczaj nazywana "endpoint" lub "route'.
How  about adding "path"? Like:
"Ścieżka" jest zazwyczaj nazywana "path", "endpoint" lub "route'.

2022-07-05 17:27 UTC, BartoszCki commented on docs/pl/docs/tutorial/first-steps.md
> +Podczas budowania API, "ścieżka" jest głównym sposobem na oddzielenie "troski" i „zasobów”.
I'm not sure what's a better translation but "troski" is definitely not the word ;)

2022-07-10 13:51 UTC, BartoszCki approved these changes
Ship it!

2022-07-14 11:30 UTC, tiangolo commented
Awesome, thank you @Valaraucoo! :bow: 

And thanks for the reviews @BartoszCki and @dominikwozniak ! :cake:

2022-07-14 11:30 UTC, merged