Add support to Client Credentials Flow (OAuth2)
fastapi/fastapi pull request #5052
Opened 2022-06-18 15:29 UTC by Riuzaky77

issue : https://github.com/tiangolo/fastapi/issues/774

2022-06-19 08:22 UTC, JarroVGIT reviewed
All for this! I do see you didn't provide any tests though, is that on the planning?

2022-06-20 14:55 UTC, Riuzaky77 commented on fastapi/security/oauth2.py
> +        @router.post("/login")
Good! will fix the comments and add some tests too!

2022-06-20 14:57 UTC, Riuzaky77 commented
> All for this! I do see you didn't provide any tests though, is that on the planning?

Will add test yep, sorry!

2022-06-25 14:59 UTC, Riuzaky77 commented
Ready to go!

2022-10-20 19:16 UTC, kokolem commented
Hey @JarroVGIT, just wondering, is there a chance to get this merged? I'm willing to pick this up if there's any additional work needed to be done before merging.

2022-10-20 19:36 UTC, JarroVGIT commented
@kokolem I am not the maintainer of this project; I just do some reviews now and then and help people out with issues. @tiangolo is the one that determines what is merged and not, but as you can see there is quite a backlog he is going through. Eventually he'll get to this, I'm sure :)

2022-11-22 22:00 UTC, petri commented
could some docs be added to the PR?

2023-01-03 05:05 UTC, Ryandaydev commented
Would it be appropriate to add some info about using this flow on the advanced/security/oauth2-scopes/ docs page?

2024-02-21 04:02 UTC, nkukard commented
@tiangolo is there any plans to implement client credentials flow?

2024-04-23 14:28 UTC, aidanwardman commented
Also looking for a good client credentials flow. Is this still going?

2024-07-09 14:13 UTC, greigs commented
Also here hoping for progress on the Client Credentials flow @tiangolo

2025-10-29 19:00 UTC, YuriiMotov requested changes
@Riuzaky77, thanks for your interest and efforts!

I think this should be much simpler, without

> This will allow the client to send its credentials either via headers or body with the request for a token.

Currently the implementation is a bit outdated, needs to be updated to align with the current implementation of other security classes.

Would you like to continue working on this?

2025-10-29 19:00 UTC, YuriiMotov commented on fastapi/security/oauth2.py
> +            scheme_name=SchemeName.OAUTH2_CLIENT_CREDENTIALS,
Why do we need this? Why don't we do it like in other classes (have `scheme_name` param and pass it to `super().__init__()`)?

2025-10-29 19:00 UTC, YuriiMotov commented on fastapi/security/oauth2.py
> +    This will allow the client to send its credentials either via headers or body with the request for a token.
I think we shouldn't describe the _"allow the client to send its credentials either via headers or body with the request for a token"_ use case.
Just:
```py
        def create_access_token(form: Annotated[OAuth2ClientCredentialsRequestForm, Depends()]):
```

The docstring should be updated to follow the style of current implementation for other classes

2025-11-29 22:19 UTC, closed without merging