🌐 Add Japanese translation for `docs/ja/docs/tutorial/sql-databases.md`
fastapi/fastapi pull request #5058
Opened 2022-06-22 06:52 UTC by Yoshino-Yukitaro

Relates to https://github.com/tiangolo/fastapi/issues/1572

This PR translates tutorial/sql-databases.md.

I am Japanese and I love FastAPI,  so I translated it.
This is my first pull request for this repository, so I apologize if there are any problems. I would appreciate it if you could check it.

2022-11-07 06:38 UTC, komtaki reviewed
I'm appreciate for your tough contribution. 👏 
I commented a few suggestion, so please confirm.

2022-11-07 06:38 UTC, komtaki commented on docs/ja/docs/tutorial/sql-databases.md
> +マイグレーション "とは、SQLAlchemy のモデルの構造を変更したり、新しい属性を追加した りするたびに、それらの変更をデータベースに再現し、新しいカラムやテーブルを追加する ために必要な一連のステップのことです。
```suggestion
「マイグレーション」とは、SQLAlchemy のモデルの構造を変更したり、新しい属性を追加した りするたびに、それらの変更をデータベースに再現し、新しいカラムやテーブルを追加する ために必要な一連のステップのことです。
```
I think the " should be handled in the same way like the above statement.

2022-11-07 06:38 UTC, komtaki commented on docs/ja/docs/tutorial/sql-databases.md
> + my_super_project`というディレクトリがあり、その中に `sql_app` というサブディレクトリがあることを思い出してください。
```suggestion
 `my_super_project`というディレクトリがあり、その中に `sql_app` というサブディレクトリがあることを思い出してください。
```

It might be missing.

2022-11-07 06:38 UTC, komtaki commented on docs/ja/docs/tutorial/sql-databases.md
> +そして、実際のデータベースからデータを読み出しながら、**FastAPI**アプリケーションと対話することができるようになります:
```suggestion
そして、実際のデータベースからデータを読み込みながら、**FastAPI**アプリケーションと対話できるようになります:
```

It might be a little unnatural.

2022-11-07 06:38 UTC, komtaki commented on docs/ja/docs/tutorial/sql-databases.md
> +### yield` やミドルウェアとの依存関係
```suggestion
### `yield` やミドルウェアとの依存関係
```

It might be lacked.

2022-12-05 10:04 UTC, Yoshino-Yukitaro commented
Thanks for your review @komtaki !
As all the comments make sense, I've fixed them in [1e7df12].(https://github.com/tiangolo/fastapi/pull/5058/commits/1e7df12e526ce4196874f7179578781b8ce1f8b7)

2022-12-06 13:31 UTC, komtaki approved these changes
Thanks for your improvement.
LGTM 👍

2022-12-07 15:24 UTC, tokusumi requested changes
Thank you for your first contribution!!!
It's really helpful to translate long but important chapter like this.
I would have some proposal to polish this more.

2022-12-07 15:24 UTC, tokusumi commented on docs/ja/docs/tutorial/sql-databases.md
> +    そして、`dict` の key-value ペアを SQLAlchemy の `Item` へのキーワード引数として渡しています。次のように。
```suggestion
    そして次のように、`dict` の key-value ペアを SQLAlchemy の `Item` へのキーワード引数として渡しています。
```
more natural

2022-12-07 15:24 UTC, tokusumi commented on docs/ja/docs/tutorial/sql-databases.md
> +    さらに、Pydantic *model* が提供しない別のキーワード引数 `owner_id` を、渡します。次のように。
```suggestion
    さらに次のように、Pydantic *model* が提供しない別のキーワード引数 `owner_id` を渡します。
```
more natural

2022-12-07 15:24 UTC, tokusumi commented on docs/ja/docs/tutorial/sql-databases.md
> +    返す値は、SQLAlchemy のモデル、あるいは SQLAlchemy のモデルのリストである ことに注意してください。
```suggestion
    返す値は、SQLAlchemy のモデル、あるいは SQLAlchemy のモデルのリストであることに注意してください。
```
typo

2022-12-07 15:24 UTC, tokusumi commented on docs/ja/docs/tutorial/sql-databases.md
> +    * もっとも、ここでは `SQLAlchemy` の動作にはあまり問題はないでしょうけど。
```suggestion
    * もっとも、ここでは `SQLAlchemy` の動作にはあまり問題はないでしょう。
```
too conversational

2023-06-26 23:03 UTC, tiangolo commented
📝 Docs preview for commit a8022e6064cebc460641079404eff645b4f84659 at: https://649a1931d1bbbc12fe60f919--fastapi.netlify.app

2024-01-28 18:33 UTC, tiangolo commented
As this PR had requested changes to be applied but has been inactive for a while, it's now going to be closed. But if there's anyone interested, feel free to create a new PR.

2024-01-28 18:33 UTC, closed without merging