:memo: Fixes a typo in the documentation for numeric validations
fastapi/fastapi pull request #5095
Opened 2022-06-30 18:34 UTC by frgfm

Hello there :wave: 

Thanks so much for this awesome library, which I use quite a lot whenever some back-end is involved!
I was checking the documentation about numeric validations and found a weird rendering issue:
![image](https://user-images.githubusercontent.com/26927750/176752051-24111354-7959-46ac-b164-603a66ad23a2.png)

The documentation section is https://fastapi.tiangolo.com/tutorial/path-params-numeric-validations/#number-validations-greater-than-or-equal

I figured someone might have done an automatic replacement somewhere which caused this. This PR simply fixes that!

Any feedback is welcome!

2022-06-30 18:58 UTC, frgfm commented
> memo Docs preview for commit [b661c22](https://github.com/tiangolo/fastapi/commit/b661c22535163df00fa7fadf57b41f505cdf71b2) at: https://62bded71abd38957507b41d6--fastapi.netlify.app

Impressive CI :relieved:

2022-07-04 20:17 UTC, JarroVGIT commented
I am not sure this is a mistake, but rather a reference to what the 'g' and 't' mean in `gt` or the 'l' and 'e' in `le`.

2022-07-04 20:44 UTC, JarroVGIT requested changes
The change that you are proposing is from documentation that has been the same for over 3.5 years. I think it is quite elegant in how it brings the point across (of the meaning of 'g' and 'e').

2022-07-04 21:41 UTC, frgfm commented
Oh actually now I see it :sweat_smile: 
I would perhaps suggest making those letters bold rather than in code-format, what do you think?
I can easily update the PR accordingly

2022-07-07 10:03 UTC, frgfm commented
That looks more intuitive to me now :point_right: https://62c6aabd77d8786b6aa5dfdd--fastapi.netlify.app/tutorial/path-params-numeric-validations/

Happy to close the PR if you don't think it's an improvement :)

2022-07-08 21:22 UTC, odiseo0 approved these changes
LGTM

2022-08-26 14:05 UTC, tiangolo commented
Thanks @frgfm and everyone for the conversation! I actually think that the "code" formatting makes it even more obvious that it refers to those letters. So I prefer to keep it as-is. Given that, I'll close this one now. But thanks for the effort and interest! :cake:

2022-08-26 14:05 UTC, closed without merging