Allow to set custom auto error detail
fastapi/fastapi pull request #5163
Opened 2022-07-15 08:13 UTC by mahenzon

Allow to set custom auto error detail for HTTP Security dependencies

Sometimes it's hard to find out which dependency returns a "Not authenticated" error. It would be handy if we could set custom error detail text to easily identify the error reason. For example "auth token not provided" for one HTTP Security object and "private id not provided" for another

2022-07-19 15:50 UTC, JarroVGIT requested changes
LGTM, but would recommend to add some test case(s) to improve coverage.

2023-03-11 11:59 UTC, mahenzon commented
Hey @JarroVGIT, sorry for the delay! 😅 

I've added some tests. Could you please check? 
Many thanks!

2023-10-01 05:46 UTC, Kludex approved these changes

2024-02-17 14:44 UTC, mahenzon commented
Hey there! I've rebased my branch onto master and solved all the conflicts. 
Could you please check? Thank you!

2024-09-02 08:44 UTC, svlandeg commented
Apologies for the delay and thanks - we'll have a look!

2024-09-02 14:59 UTC, svlandeg approved these changes
This mostly looks good to me, thanks again for your contribution!

I'll leave this up for Tiangolo for a final review. Should we consider adding a note in the documentation somewhere?

2024-09-02 14:59 UTC, svlandeg commented on fastapi/security/http.py
> +                It useful when you have multiple errors defined: set
```suggestion
                It's useful when you have multiple errors defined: set
```

2024-09-02 14:59 UTC, svlandeg commented on fastapi/security/http.py
> +                It useful when you have multiple errors defined: set
```suggestion
                It's useful when you have multiple errors defined: set
```

2024-09-02 14:59 UTC, svlandeg commented on fastapi/security/http.py
> +                It useful when you have multiple errors defined: set
```suggestion
                It's useful when you have multiple errors defined: set
```

2025-12-09 12:42 UTC, YuriiMotov reviewed
Although it might still be convenient to have such parameter, now there is quite simple way to implement this logic.

According to [docs](https://fastapi.tiangolo.com/how-to/authentication-error-status-code/) we can inherit from existing security class end override the `make_not_authenticated_error` method:

```py
class MyHTTPBasic(HTTPBasic):
    def __init__(self, *, auto_error: bool = True, auto_error_detail: str = "Not authorized"):
        super().__init__(auto_error=auto_error)
        self.auto_error_detail = auto_error_detail

    def make_not_authenticated_error(self) -> HTTPException:
        return HTTPException(
            status_code=status.HTTP_403_FORBIDDEN, detail=self.auto_error_detail
        )
```

<details><summary>Full code</summary>

```py
from typing import Optional

from fastapi import FastAPI, Security, HTTPException, status
from fastapi.security import HTTPBasic, HTTPBasicCredentials
from fastapi.testclient import TestClient

class MyHTTPBasic(HTTPBasic):
    def __init__(self, *, auto_error: bool = True, auto_error_detail: str = "Not authorized"):
        super().__init__(auto_error=auto_error)
        self.auto_error_detail = auto_error_detail

    def make_not_authenticated_error(self) -> HTTPException:
        return HTTPException(
            status_code=status.HTTP_403_FORBIDDEN, detail=self.auto_error_detail
        )


app = FastAPI()

error_message = "not a 20 minute adventure"
security = MyHTTPBasic(auto_error=True, auto_error_detail=error_message)


@app.get("/users/me")
def read_current_user(credentials: Optional[HTTPBasicCredentials] = Security(security)):
    return {"username": credentials.username, "password": credentials.password}


client = TestClient(app)


def test_security_http_basic():
    response = client.get("/users/me", auth=("john", "secret"))
    assert response.status_code == 200, response.text
    assert response.json() == {"username": "john", "password": "secret"}


def test_security_http_basic_no_credentials():
    response = client.get("/users/me")
    assert response.status_code == 403, response.text
    assert response.json() == {"detail": error_message}
```

</details>

2026-05-23 11:12 UTC, tiangolo commented
Thanks for the interest and work on this! ☕

I want to implement a few big refactors and features that might solve many of these use cases.

I also need to do that before expanding the surface of what is supported with additional external PRs, because that also means I would have to keep maintaining and handling backwards compatibility for those new changes while doing those big refactors.

I have not wanted to close PRs that target the same or similar problems before I have an alternative, but then I have left many PRs open for too long, which is not useful or clear either. Sorry for that.

And then, after I make those big refactors, the problem might be solved... and if not, a bunch of conflicts will show up, so it will be better and easier to start from scratch (from the new code state).

So, I'll close this one for now to keep things clean.

For the specific use case, the best would be to document it in a new GitHub Discussion (or 👍 any existing one) with the specific problem to solve (without details of the implementation) to track the feature request.

Thank you! 🍰

2026-05-23 11:12 UTC, closed without merging