feat: add ja doc for advanced teplates
fastapi/fastapi pull request #5170
Opened 2022-07-19 00:24 UTC by souhub

This PR translates advanced/templates.md in Japanese.

2022-08-26 14:58 UTC, tokusumi requested changes
Great work! I propose a little for not translated sentences remains.

2022-08-26 14:58 UTC, tokusumi commented on docs/ja/docs/advanced/templates.md
> +!!! note
```suggestion
!!! note "備考"
```

2022-08-26 14:58 UTC, tokusumi commented on docs/ja/docs/advanced/templates.md
> +!!! tip
```suggestion
!!! tip "豆知識"
```

2022-08-26 14:58 UTC, tokusumi commented on docs/ja/docs/advanced/templates.md
> +!!! note "Technical Details"
```suggestion
!!! note "技術詳細"
```

2022-08-26 14:58 UTC, tokusumi commented on docs/ja/docs/advanced/templates.md
> +    **FastAPI** provides the same `starlette.templating` as `fastapi.templating` just as a convenience for you, the developer. But most of the available responses come directly from Starlette. The sa
```suggestion
    **FastAPI** は開発者の便利のために `starlette.templating` を `fastapi.templating` として提供します。しかし、利用可能なレスポンスのほとんどは `Request` や `StaticFiles` と同様にStarletteから直接渡されます。 
```

2022-09-30 06:03 UTC, souhub commented on docs/ja/docs/advanced/templates.md
> +    **FastAPI** provides the same `starlette.templating` as `fastapi.templating` just as a convenience for you, the developer. But most of the available responses come directly from Starlette. The sa
Thank you sooooooo much:) let me fix!

2022-11-14 06:04 UTC, komtaki reviewed
Thanks you for your great work. I commented a few suggestion, so please check. 👍

2022-11-14 06:04 UTC, komtaki commented on docs/ja/docs/advanced/templates.md
> +`request`をJinja2のコンテキストのキーと値ののペアとして渡さなければいけないことに注意してください。そのため、*パスオペレーション*の中でもそれを宣言しなければなりません。
```suggestion
    `request`をJinja2のコンテキストのキーと値ののペアとして渡さなければいけないことに注意してください。そのため、*パスオペレーション*の中でもそれを宣言しなければなりません。
```

A following sentence in a tips or note block needs indent like English. If no indent, cause broken css style and not was surrounded block.

https://github.com/tiangolo/fastapi/blob/master/docs/en/docs/advanced/templates.md?plain=1#L35

2022-11-14 06:04 UTC, komtaki commented on docs/ja/docs/advanced/templates.md
> +`response_class=HTMLResponse`を宣言することで、docs UIはレスポンスがHTML形式であると知ることができます。
```suggestion
    `response_class=HTMLResponse`を宣言することで、docs UIはレスポンスがHTML形式であると知ることができます。
```

Same reason.

2022-11-14 06:04 UTC, komtaki commented on docs/ja/docs/advanced/templates.md
> +また、`from starlette.templating import Jinja2Templates`も使用できます。
```suggestion
    また、`from starlette.templating import Jinja2Templates`も使用できます。
```

Same reason.

2023-06-26 22:58 UTC, tiangolo commented
📝 Docs preview for commit fd64969f51a262501568241dcb3716c274f14220 at: https://649a17df51d130136dc7df41--fastapi.netlify.app

2024-01-29 15:52 UTC, tiangolo commented
As this PR had requested changes to be applied but has been inactive for a while, it's now going to be closed. But if there's anyone interested, feel free to create a new PR.

2024-01-29 15:52 UTC, closed without merging