Translated from English to Ukrainian
fastapi/fastapi pull request #5178
Opened 2022-07-20 12:47 UTC by ilkuzmenko

2022-07-21 16:35 UTC, ilkuzmenko commented
🌐 Add Ukrainian translation for docs/uk/docs/index.md

2022-07-25 20:21 UTC, python4eg reviewed
Дуже круто, тільки хотів сісти за переклад як бачу ви вже почали. Додав кілька айтемів стосовно адаптивного перекладу. Надіюся вони були корисними і ви погоджуєтеся. Ще раз дякую за пророблену роботу

2022-07-25 20:21 UTC, python4eg commented on docs/uk/docs/index.md
> +    * За відсутності `None` це було б обов'язковим (як і тіло у випадку з `PUT`).
він був би обов`язковим

2022-07-25 20:21 UTC, python4eg commented on docs/uk/docs/index.md
> +    * Перевірка навіть для глибоко вкладених об'єктів JSON.
Глибоко вкладені трішки ріже слух. Можливо подумати про альтернативу типу "Об`єкти в високим рівнем вкладеності" абощо.

2022-07-25 20:21 UTC, python4eg commented on docs/uk/docs/index.md
> +* Документує все за допомогою OpenAPI, та використовує в:
що може бути використано в:

2022-07-25 20:21 UTC, python4eg commented on docs/uk/docs/index.md
> +Спробуємо змінити рядок:
Якшо в тебе далі `і побачите` то тут краще писати `спробуйте` або лишити тут як є і там написати `і побачимо`

2022-07-25 20:21 UTC, python4eg commented on docs/uk/docs/index.md
> +*Дуже потужна і проста у використанні система **<abbr title="також відомий як: components, resources, providers, services, injectables">Ін'єкції Залежностей</abbr>** system.
Missing space.
Система...також відома як(система)...Ін'єкція Залежностей(однина)

2022-07-25 20:21 UTC, python4eg commented on docs/uk/docs/index.md
> +* Безпека та автентифікація, включаючи підтримку **OAuth2** з **JWT tokens** та **HTTP Basic** автентифікацією.
`**HTTP Basic** автентифікацію` так як це не частина OAuth2 окермий вид автентифікації

2022-07-25 20:21 UTC, python4eg commented on docs/uk/docs/index.md
> +* Багато додаткових функцій (завдяки Starlette) як:
як-от:
або 
, таких як:

2022-07-25 20:21 UTC, python4eg commented on docs/uk/docs/index.md
> +Незалежні тести TechEmpower показують програми **FastAPI**, що працюють під керуванням Uvicorn є <a href="https://www.techempower.com/benchmarks/#section=test&runid=7464e520-0dc2-473d-bd34-dbdfd7e859
Незалежні тести TechEmpower показують програми **FastAPI**, що працюють під керуванням Uvicorn ... як одні з найшвидших

2022-07-26 06:56 UTC, ilkuzmenko commented
> Дуже круто, тільки хотів сісти за переклад як бачу ви вже почали. Додав кілька айтемів стосовно адаптивного перекладу. Надіюся вони були корисними і ви погоджуєтеся. Ще раз дякую за пророблену роботу

Дякую за допомогу! Погоджуюсь з Вашими виправленнями. Якщо бажаєте приєднатися до перекладу - це супер, можемо розділити документацію на частини і робити переклад разом.

2022-08-08 16:16 UTC, python4eg commented
> > Дуже круто, тільки хотів сісти за переклад як бачу ви вже почали. Додав кілька айтемів стосовно адаптивного перекладу. Надіюся вони були корисними і ви погоджуєтеся. Ще раз дякую за пророблену роботу
> 
> Дякую за допомогу! Погоджуюсь з Вашими виправленнями. Якщо бажаєте приєднатися до перекладу - це супер, можемо розділити документацію на частини і робити переклад разом.

Звісно я тільки за. Давайте звяжемося і розділимо переклад. @python4eg мій нік в телеграмі

2023-04-27 00:14 UTC, ValeryVal reviewed
Thank you for your job! It's huge! Made some suggestions:)

2023-04-27 00:14 UTC, ValeryVal commented on docs/uk/docs/index.md
> +* _Шлях_ `/items/{item_id}` має опціональний `str` _параметр запиту_ `q`.
```suggestion
* _Шлях_ `/items/{item_id}` має необов'язковий `str` _параметр запиту_ `q`.
```

2023-04-27 00:14 UTC, ValeryVal commented on docs/uk/docs/index.md
> +Перейдемо сюди <a href="http://127.0.0.1:8000/docs" class="external-link" target="_blank">http://127.0.0.1:8000/docs</a>.
```suggestion
Тепер перейдімо сюди <a href="http://127.0.0.1:8000/docs" class="external-link" target="_blank">http://127.0.0.1:8000/docs</a>.
```

2023-04-27 00:14 UTC, ValeryVal commented on docs/uk/docs/index.md
> +### Альтернативні документи API
```suggestion
### Альтернативна документація API
```

2023-04-27 00:14 UTC, ValeryVal commented on docs/uk/docs/index.md
> +Тепер перейдемо сюди <a href="http://127.0.0.1:8000/docs" class="external-link" target="_blank">http://127.0.0.1:8000/docs</a>.
```suggestion
Тепер перейдімо сюди <a href="http://127.0.0.1:8000/docs" class="external-link" target="_blank">http://127.0.0.1:8000/docs</a>.
```

2023-04-27 00:14 UTC, ValeryVal commented on docs/uk/docs/index.md
> +Зараз перейдемо <a href="http://127.0.0.1:8000/redoc" class="external-link" target="_blank">http://127.0.0.1:8000/redoc</a>.
```suggestion
Зараз перейдімо <a href="http://127.0.0.1:8000/redoc" class="external-link" target="_blank">http://127.0.0.1:8000/redoc</a>.
```

2023-04-27 19:07 UTC, ValeryVal reviewed
Added some more formatting and translation suggestions)

2023-04-27 19:07 UTC, ValeryVal commented on docs/uk/docs/index.md
> +* <a href="https://pythonhosted.org/itsdangerous/" target="_blank"><code>itsdangerous</code></a> - Необхідно для підтримки `SessionMiddleware`.
```suggestion
* <a href="https://pythonhosted.org/itsdangerous/" target="_blank"><code>itsdangerous</code></a> - необхідно для підтримки `SessionMiddleware`.
```

2023-04-27 19:07 UTC, ValeryVal commented on docs/uk/docs/index.md
> +* <a href="https://pyyaml.org/wiki/PyYAMLDocumentation" target="_blank"><code>pyyaml</code></a> - Необхідно для підтримки `SchemaGenerator` Starlette (ймовірно, вам це не потрібно з FastAPI).
```suggestion
* <a href="https://pyyaml.org/wiki/PyYAMLDocumentation" target="_blank"><code>pyyaml</code></a> - необхідно для підтримки `SchemaGenerator` Starlette (ймовірно, вам це не потрібно з FastAPI).
```

2023-04-27 19:07 UTC, ValeryVal commented on docs/uk/docs/index.md
> +* <a href="https://graphene-python.org/" target="_blank"><code>graphene</code></a> - Необхідно для підтримки `GraphQLApp`.
```suggestion
* <a href="https://graphene-python.org/" target="_blank"><code>graphene</code></a> - необхідно для підтримки `GraphQLApp`.
```

2023-04-27 19:07 UTC, ValeryVal commented on docs/uk/docs/index.md
> +* <a href="https://github.com/esnme/ultrajson" target="_blank"><code>ujson</code></a> - Необхідно, якщо ви хочете використовувати `UJSONResponse`.
```suggestion
* <a href="https://github.com/esnme/ultrajson" target="_blank"><code>ujson</code></a> - необхідно, якщо ви хочете використовувати `UJSONResponse`.
```

2023-04-27 19:07 UTC, ValeryVal commented on docs/uk/docs/index.md
> +Використовується FastAPI / Starlette:
```suggestion
Використовується і у FastAPI, і в Starlette:
```

2023-04-27 19:07 UTC, ValeryVal commented on docs/uk/docs/index.md
> +* <a href="https://www.uvicorn.org" target="_blank"><code>uvicorn</code></a> - для сервера, який завантажує та обслуговує вашу програму.
```suggestion
* <a href="https://www.uvicorn.org" target="_blank"><code>uvicorn</code></a> - використовується для сервера, який завантажує та обслуговує вашу програму.
```

2023-04-27 19:07 UTC, ValeryVal commented on docs/uk/docs/index.md
> +* <a href="https://github.com/ijl/orjson" target="_blank"><code>orjson</code></a> - Необхідно, якщо ви хочете використовувати `ORJSONResponse`.
```suggestion
* <a href="https://github.com/ijl/orjson" target="_blank"><code>orjson</code></a> - необхідно, якщо ви хочете використовувати `ORJSONResponse`.
```

2023-04-27 19:08 UTC, ValeryVal reviewed
Added some more formatting and translation suggestions)

2023-06-13 07:13 UTC, akarev0 commented on docs/uk/docs/index.md
> +* **Інтуїтивний**: Чудова підтримка редакторами. <abbr title="також відоме як автозаповнення, IntelliSense.">Доповнення</abbr> всюди. Зменште час на налагодження.
стильстика речень відрізняється, тобто там де "інтуїтивний" за логікою та стилем має буть "зменшить замість зменште"

2023-06-13 07:15 UTC, akarev0 commented on docs/uk/docs/index.md
> +* **Надійний**: Ви матимете стабільний код готовий для продакшину з автоматичною інтерактивною документацією.
```suggestion
* **Надійний**: Ви матимете стабільний код готовий для розгортання з автоматичною інтерактивною документацією.
```

2023-06-13 07:16 UTC, akarev0 commented on docs/uk/docs/index.md
> +* **Стандартизований**: Оснований та повністю сумісний з відкритими стандартами для API: <a href="https://github.com/OAI/OpenAPI-Specification" class="external-link" target="_blank">OpenAPI</a> (prev
```suggestion
* **Стандартизований**: Заснований та повністю сумісний з відкритими стандартами для API: <a href="https://github.com/OAI/OpenAPI-Specification" class="external-link" target="_blank">OpenAPI</a> (previously known as Swagger) and <a href="https://json-schema.org/" class="external-link" target="_blank">JSON Schema</a>.
```

2023-06-13 07:17 UTC, akarev0 commented on docs/uk/docs/index.md
> +<small>* оцінка на основі тестів внутрішньої команди розробників, створення продуктових застосунків.</small>
@ValeryVal ґрунтується на основі це тавтологія, має бути щось одне :)

2023-06-13 07:22 UTC, akarev0 commented on docs/uk/docs/index.md
> +* `--reload`: перезапускає сервер після зміни коду. Використовуйте виключно для розробки.
```suggestion
* `--reload`: перезавантажує сервер після зміни коду. Використовуйте виключно для розробки.
```

2023-06-13 07:25 UTC, akarev0 commented on docs/uk/docs/index.md
> +Тепер модифікуйте файл `main.py` щоб отримати тіло запиту `PUT`.
```suggestion
Тепер модифікуйте файл `main.py` щоб отримати вміст запиту `PUT`.
```

2023-06-13 07:26 UTC, akarev0 commented on docs/uk/docs/index.md
> +Оголошуйте тіло запиту за допомогою стандартних типів Python завдяки Pydantic.
```suggestion
Опишіть вміст запиту за допомогою стандартних типів Python завдяки Pydantic.
```

2023-06-13 07:27 UTC, akarev0 commented on docs/uk/docs/index.md
> +* Інтерактивна документація API буде автоматично оновлена, включаючи нове тіло:
```suggestion
* Інтерактивна документація API буде автоматично оновлена, включаючи вміст:
```

2023-06-13 07:33 UTC, akarev0 commented on docs/uk/docs/index.md
>      * Convert Python types (`str`, `int`, `float`, `bool`, `list`, etc).
т.д це російське "так далєє" тому краще змінити на "тощо"

2023-06-13 07:35 UTC, akarev0 commented on docs/uk/docs/index.md
> +    * За відсутності `None` він був би обов'язковим (як і тіло у випадку з `PUT`).
```suggestion
    * За відсутності `None` він був би обов'язковим (як вміст у випадку з `PUT`).
```

2023-06-13 07:36 UTC, akarev0 commented on docs/uk/docs/index.md
> +...із:
```suggestion
...з:
```

2023-06-13 07:42 UTC, akarev0 commented on docs/uk/docs/index.md
> +* <a href="https://requests.readthedocs.io" target="_blank"><code>requests</code></a> - Необхідно, якщо ви хочете використовувати `TestClient`.
помилка

2023-07-18 14:12 UTC, romashevchenko requested changes
Hi)
I'm from DreamProiT and reviewed this translation.

2023-08-10 17:56 UTC, rostik1410 commented
@ilkuzmenko Hey, you made did a huge work there, are you able to finish this? I could approve this after fixing the comments that were left by reviewers. Or if you are not able or don't want to work on it anymore can I do my own based on your?
P.S. Hope you are okay now

2023-08-11 11:47 UTC, akarev0 commented
@rostik1410 let me know if you need any help

2024-01-15 16:12 UTC, tiangolo commented
As this PR had requested changes to be applied but has been inactive for a while, it's now going to be closed. But if there's anyone interested, feel free to create a new PR.

2024-01-15 16:12 UTC, closed without merging