Add Turkish translation for docs/async.md
fastapi/fastapi pull request #5191
Opened 2022-07-24 14:07 UTC by BilalAlpaslan

2022-11-07 19:06 UTC, hakancelikdev commented on docs/tr/docs/async.md
> +**Not**: *path operasyon fonksiyonlarında* istediğiniz şekilde `def` yada `async def` kullanabilirsiniz. Sizin için en iyi olan seçeneği kullanabilirsiniz. FastAPI onlarla doğru olanı yapacaktır.
```suggestion
**Not**: *path operasyon fonksiyonlarınızda* `def` ve `async def`'i ihtiyacınız olduğu kadar karıştırabilir ve her birini sizin için en iyi seçeneği kullanarak tanımlayabilirsiniz. FastAPI onlarla doğru olanı yapacaktır.
```

2022-11-07 19:06 UTC, hakancelikdev commented on docs/tr/docs/async.md
> +Yukarıdaki durumlardan herhangi birinde FastAPI yine de asenkron olarak çalışacak ve son derece hızlı olacaktır.
```suggestion
Her neyse, Yukarıdaki durumlardan herhangi birinde FastAPI yine de asenkron olarak çalışacak ve son derece hızlı olacaktır.
```

2023-04-15 00:36 UTC, hakancelikdev requested changes

2023-04-15 00:36 UTC, hakancelikdev commented on docs/tr/docs/async.md
> +# Eşzamanlılık ve async / await
I think that 'Concurrency' should not be translated into Turkish because it would lose its meaning.

2023-04-15 00:36 UTC, hakancelikdev commented on docs/tr/docs/async.md
> +Eğer onları `await` ile çağırmanızı söyleyen üçüncü taraf bir kütüphane kullanıyorsanız, örneğin:
```suggestion
Eğer `await` ile çağrılması gerektiğini belirten üçüncü taraf kütüphaneleri kullanıyorsanız, örneğin:
```

2023-04-15 00:36 UTC, hakancelikdev commented on docs/tr/docs/async.md
> +O zaman *path operasyon fonksiyonunu*  `async def` ile tanımlayın:
```suggestion
O zaman *path operasyon fonksiyonunu* `async def` ile tanımlayın örneğin:
```

2023-04-15 00:36 UTC, hakancelikdev commented on docs/tr/docs/async.md
> +    `await` yalnızca `async def` ile tanımlanan fonksiyonların içinde kullanılabilir.
```suggestion
    Sadece `async def` ile tanımlanan fonksiyonlar içinde `await` kullanabilirsiniz.
```

2023-04-15 00:36 UTC, hakancelikdev commented on docs/tr/docs/async.md
> +Eğer üçüncü parti kütüphaneler ile beraber birşeyler ile etkileşimde bulunuyorsak (veri tabanı,  API, dosya işlemleri, vb.) ve  `await` kulanımı desteklenmiyorsa, (birçok veri tabanı kütüphanesi için
```suggestion
Eğer bir veritabanı, bir API, dosya sistemi vb. ile iletişim kuran bir üçüncü taraf bir kütüphane kullanıyorsanız ve `await` kullanımını desteklemiyorsa, (bu şu anda çoğu veritabanı kütüphanesi için geçerli bir durumdur), o zaman *path operasyon fonksiyonunuzu* `def` kullanarak normal bir şekilde tanımlayın, örneğin:
```

2023-04-15 00:36 UTC, hakancelikdev commented on docs/tr/docs/async.md
> +Eğer uygulamanız (bir şekilde) başka bir şeyle iletişim kurması gerekmiyor ama  yanıt vermesini beklemeniz gerekiyorsa `async def` kullanabilirsiniz.
```suggestion
Eğer uygulamanız (bir şekilde) başka bir şeyle iletişim kurmak ve onun cevap vermesini beklemek zorunda değilse, `async def` kullanın.
```

2023-04-15 00:36 UTC, hakancelikdev commented on docs/tr/docs/async.md
> +**Not**: *path operasyon fonksiyonlarınızda* `def` ve `async def`'i ihtiyacınız olduğu kadar karıştırabilir ve her birini sizin için en iyi seçeneği kullanarak tanımlayabilirsiniz. FastAPI onlarla do
```suggestion
**Not**: *path operasyon fonksiyonlarınızda* `def` ve `async def`'i ihtiyaç duyduğunuz gibi karıştırabilir ve her birini sizin için en iyi seçeneği kullanarak tanımlayabilirsiniz. FastAPI onlarla doğru olanı yapacaktır.
```

2023-04-15 00:36 UTC, hakancelikdev commented on docs/tr/docs/async.md
> +Her neyse, Yukarıdaki durumlardan herhangi birinde FastAPI yine de asenkron olarak çalışacak ve son derece hızlı olacaktır.
```suggestion
Her neyse, yukarıdaki durumlardan herhangi birinde, FastAPI yine de asenkron olarak çalışacak ve son derece hızlı olacaktır.
```

2023-04-15 00:36 UTC, hakancelikdev commented on docs/tr/docs/async.md
> +Ancak yukarıdaki adımları takip ederek bazı performans optimizasyonları yapabiliriz
```suggestion
Ancak yukarıdaki adımları takip ederek, bazı performans optimizasyonları yapılabilecektir.
```

2023-04-15 00:36 UTC, hakancelikdev commented on docs/tr/docs/async.md
> +Python modern versiyonlarında **`async` ve `await`** sözdizimi ile **"coroutines"**  kullanan **"asenkron kod"** desteğine sahiptir.
```suggestion
Python'un modern versiyonlarında **`async` ve `await`** sözdizimi ile **"coroutines"**  kullanan **"asenkron kod"** desteğine sahiptir.
```

2023-04-15 00:40 UTC, hakancelikdev commented
Overall, I think it's good, there are just some small errors that cause a shift in meaning. After updating the PR, I'll take another look at all of them, thank you!

2023-06-27 00:40 UTC, tiangolo commented
📝 Docs preview for commit b7b3e76cb1282445ea04d5bc69285f0d2150bece at: https://649a2fbb219954200e358294--fastapi.netlify.app

2023-10-11 12:27 UTC, cun3yt requested changes
2 simple change requests. Happy to approve after they are addressed.

2023-10-11 12:27 UTC, cun3yt commented on docs/tr/docs/async.md
> +That, plus the simple fact that Python is the main language for **Data Science**, Machine Learning and especially Deep Learning, make FastAPI a very good match for Data Science / Machine Learning web
Fazlalik kalmis gibi, silinecek galiba?

2023-10-11 12:27 UTC, cun3yt commented on docs/tr/docs/async.md
> +...instead of `def`:
"`def` yerine:" ile degistirilmesi uygun olur.

2023-10-11 13:17 UTC, tiangolo commented
📝 Docs preview for commit 8715acab09c1ffe7a9f722465a880689bc235932 at: https://dc139c84.fastapitiangolo.pages.dev

2023-10-11 13:36 UTC, cun3yt approved these changes

2024-01-22 19:57 UTC, merged

2024-01-22 19:57 UTC, alejsdev commented
Thanks @BilalAlpaslan 🤓 

And thanks for the reviews @cun3yt and @hakancelikdev ✨