🌐 Add Turkish translation for `docs/tr/docs/project-generation.md`
fastapi/fastapi pull request #5192
Opened 2022-07-24 21:29 UTC by BilalAlpaslan

Turkish translate for project-generation.md
Main issue: https://github.com/tiangolo/fastapi/issues/1892

2023-06-26 23:55 UTC, tiangolo commented
📝 Docs preview for commit 0d3fa7e7db0fef56b647175a4b0fcde36c1a20a1 at: https://649a251ab8e9671a3f1c206a--fastapi.netlify.app

2023-10-11 12:19 UTC, cun3yt requested changes
A few small change requests. Happy to approve after they are resolved.

2023-10-11 12:19 UTC, cun3yt commented on docs/tr/docs/project-generation.md
> +    * **Standartlara dayalı**: API'ler için açık standartlara dayanır (ve tamammen uyumludur): <a href="https://github.com/OAI/OpenAPI-Specification" class="external-link" target="_blank">OpenAPI</a>
`tamammen` => `tamamen`

2023-10-11 12:19 UTC, cun3yt commented on docs/tr/docs/project-generation.md
> +* **JWT token** authentication.
authentication => kimlik doğrulama ?

2023-10-11 12:19 UTC, cun3yt commented on docs/tr/docs/project-generation.md
> +* **Pytest**'e dayalı, Docker ile entegre REST backend testleri ıle veritabanından bağımsız olarak tam API etkileşimini test edebilirsiniz. Docker'da çalıştığı için her seferinde sıfırdan yeni bir ve
`ıle` => `ile`

2023-10-11 12:19 UTC, cun3yt commented on docs/tr/docs/project-generation.md
> +sıfırdan bir projeye başlıyorsanız alternatiflerine bakın.
`sıfırdan` => `Sıfırdan`

2023-10-11 13:03 UTC, tiangolo commented
📝 Docs preview for commit a0ba04c90c02648a82d9eb15f8b1e5ba5a005210 at: https://37f80710.fastapitiangolo.pages.dev

2023-10-11 13:39 UTC, cun3yt commented on docs/tr/docs/project-generation.md
> +    * **Standartlara dayalı**: API'ler için açık standartlara dayanır (ve tamammen uyumludur): <a href="https://github.com/OAI/OpenAPI-Specification" class="external-link" target="_blank">OpenAPI</a>
Bir de bu vardi ^^

2023-10-11 14:14 UTC, tiangolo commented
📝 Docs preview for commit 7439779b7d695a9d4571b8b1c2e5fade6411d36c at: https://3d0e8e7c.fastapitiangolo.pages.dev

2023-10-11 17:13 UTC, cun3yt approved these changes

2024-01-22 19:55 UTC, alejsdev commented
Thanks for you contribution @BilalAlpaslan 😸 

And thanks for the review @cun3yt 💯

2024-01-22 19:55 UTC, merged