fix the description of make query paramter required
fastapi/fastapi pull request #5255
Opened 2022-08-10 08:18 UTC by hjlarry

I found there are some missing translations  of this part

2022-09-16 01:04 UTC, mcthesw approved these changes

2022-10-11 10:00 UTC, 1320555911 approved these changes

2022-10-14 13:49 UTC, Jedore requested changes
You omit different python version for `3.6 and above` `3.9 and above` `3.10 and above`.

2022-10-31 17:57 UTC, tiangolo commented
Great, thanks @hjlarry! :tada: 

And thanks for the reviews @Jedore, @1320555911, @mcthesw :coffee:

2022-10-31 17:57 UTC, merged