Add ja translate advanced events
fastapi/fastapi pull request #5270
Opened 2022-08-14 01:01 UTC by My-MC

Relates to #1572 

This PR is a translation of `docs/ja/docs/advanced/events.md`.

I'm Japanese. I like this framework so I translated it.

I am the first PR to this repository. I would appreciate a code review. Please let me know if it has any problems.

2023-06-26 22:34 UTC, tiangolo commented
📝 Docs preview for commit c179c237082e251dfb7841b89baa99b08194b9ad at: https://649a1242ec68df0f86e6b2db--fastapi.netlify.app

2024-03-30 23:19 UTC, tiangolo commented
Thank you! I'm still waiting for others to review this to be able to merge it, meanwhile, maybe you could help me review some of the other Japanese translations, that way if they are approved by each other, I could merge them. :nerd_face: 

https://github.com/tiangolo/fastapi/issues?q=is%3Aopen+label%3Alang-ja+sort%3Aupdated-desc+label%3Aawaiting-review

2024-04-01 13:27 UTC, codespearhead commented
@My-MC Do you happen to know three Japanese developers that you can ask a [PR review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) from? [This](https://github.com/tiangolo/fastapi/pulls?q=is%3Apr+Japanese) might help.

2025-01-19 16:59 UTC, k94-ishi commented
Previously, on_event() was used for startup and shutdown processes, but the recommended approach has now shifted to lifespan(). Along with this transition, the original document has been significantly updated, so it seems that this pull request will also require substantial updates to align with the changes...

2025-02-21 16:11 UTC, k94-ishi requested changes
Previously, on_event() was used for startup and shutdown processes, but the recommended approach has now shifted to lifespan(). Along with this transition, the original document has been significantly updated, so it seems that this pull request will also require substantial updates to align with the changes...

2025-02-22 08:15 UTC, My-MC commented
Yeah, I think so. I forgot this PR until your message came. I'll recreate a new PR about `Lifespan Events`.

2025-02-22 08:15 UTC, closed without merging