docs: update index.md docs for Russian
fastapi/fastapi pull request #5289
Opened 2022-08-19 20:37 UTC by impocode

2022-08-22 11:44 UTC, RobotToI requested changes

2022-08-22 11:44 UTC, RobotToI commented on docs/ru/docs/index.md
> +    <em>Фреймворк FastAPI, высокая производительность, простота в изучении, быстрота написания кода, готовность к производству</em>
`Фреймворк FastAPI, **высокопроизводительный**, **простой в изучении**` * и т.д.

2022-08-22 11:44 UTC, RobotToI commented on docs/ru/docs/index.md
> +    <img src="https://img.shields.io/pypi/pyversions/fastapi.svg?color=%2334D058" alt="Supported Python versions">
What is the matter of this changes?

2022-08-22 11:44 UTC, RobotToI commented on docs/ru/docs/index.md
> +* **Меньше ошибок**: Сократите примерно на 40 % ошибок, вызванных человеком (разработчиком). *
**Сокращает**
**Увеличивает**
Я думаю в этих предложениях более подходящими являются такие варианты переводов. НО - я могу ошибаться.

2022-08-22 11:44 UTC, RobotToI commented on docs/ru/docs/index.md
> +"_В последнее время я много где использую **FastAPI**. [...] На самом деле я планирую использовать его для всех **служб машинного обучения моей команды в Microsoft**. Некоторые из них интегрируются в
`служб` машинного обучения - скорее всего подразумевается как `сервисов` или же `приложений для`

2022-08-22 11:44 UTC, RobotToI commented on docs/ru/docs/index.md
> +* Создайте файл `main.py` с:
Возможно лучше дополнить `Создайте файл 'main.py' с содежимым:` или что-то на подобии?

2022-08-22 11:44 UTC, RobotToI commented on docs/ru/docs/index.md
> +Вы увидите ответ JSON как:
Возможно стоит убрать отсюда `как`?
К примеру `Вы увидите ответ в виде JSON:` или другие варианты)

2022-08-22 11:44 UTC, RobotToI commented on docs/ru/docs/index.md
> +* <abbr title="также известный как: сериализация, синтаксический анализ, маршалинг">Преобразование</abbr> входных данных: поступающие из сети в данные и типы Python. Чтение из:
`Преобразование входных данных поступающих из сети в объекты Python с соблюдением типов.` 
Тоже - не самый идеальный перевод - может быть явно улучшен.

2022-08-22 11:44 UTC, RobotToI commented on docs/ru/docs/index.md
> +    * Кук.
Кук? Такое слово есть в Русском? Возможно будет лучше оставить английское слово?

2022-08-22 11:44 UTC, RobotToI commented on docs/ru/docs/index.md
> +* <abbr title="также известный как: сериализация, синтаксический анализ, маршалинг">Преобразование</abbr> выходных данных: преобразование данных и типов Python в сетевые данные (как JSON):
`Преобразование выходных объектов и их типов в данные передаваемые по сети интернет (в виде JSON объектов)` - Тоже самое примечание что и на коментарий выше

2022-08-22 11:44 UTC, RobotToI commented on docs/ru/docs/index.md
> +Мы только поцарапали поверхность, но вы уже поняли, как все это работает.
`Scratched the surface` думаю стоит заменить на что-то более русское - например `немного капнули` или `поверхностно прошлись` что-то такого типа

2022-08-22 11:44 UTC, RobotToI commented on docs/ru/docs/index.md
> +* Объявление **параметров** из других мест, таких как: **заголовки**, **куки**, **поля формы** и **файлы**.
Здесь тоже самое со словом куки - оно хоть и есть в русском, даже если мы его только что придумали, но использовать его наверное не стоит и лучше использовать английского предка)

2022-08-22 11:44 UTC, RobotToI commented on docs/ru/docs/index.md
> +* **GraphQL** интеграция с <a href="https://strawberry.rocks" class="external-link" target="_blank">Strawberry</a> и другими библиотеками.
У вас немного выше переехал **GraphQL** чем должен быть

2022-08-22 11:44 UTC, RobotToI commented on docs/ru/docs/index.md
> +    * **Сеансы файлов Cookie**
Возможно `Cookie сеансы(сессии)` будет более корректно?

2022-08-22 11:44 UTC, RobotToI commented on docs/ru/docs/index.md
> +Чтобы узнать больше об этом, см. раздел <a href="https://fastapi.tiangolo.com/benchmarks/" class="internal-link" target="_blank">Тесты</a>.
Не совсем понятно какие `Тесты` - возможно стоит указать что это тесты производительности?

2022-08-22 11:44 UTC, RobotToI commented on docs/ru/docs/index.md
> +Вы можете установить все это с помощью `pip install "fastapi[all]"`.
А в чем суть двойных кавычек?

2022-08-22 16:31 UTC, Xewus commented on docs/ru/docs/index.md
> +    * **Сеансы файлов Cookie**
Только это куки сеансов/сессий.
Такие штуки, которые позволяют продолжить конкретный прерванный сеанс.

2022-08-22 17:56 UTC, Xewus requested changes

2022-08-22 17:56 UTC, Xewus commented on docs/ru/docs/index.md
> +* **На основе стандартов**: На основе (и полностью совместимых) открытых стандартов для API: <a href="https://github.com/OAI/OpenAPI-Specification" class="external-link" target="_blank">OpenAPI</a> (
>  На основе (и полностью совместимых)

Основан на открытых стандартах API и полностью совместим с ними.

2022-08-22 17:56 UTC, Xewus commented on docs/ru/docs/index.md
> +"_**Netflix** рада объявить о выпуске с открытым исходным кодом нашей системы оркестровки **антикризисного управления**: **Dispatch**! [создана с помощью **FastAPI**]_"
> рада объявить о выпуске с открытым исходным кодом нашей системы оркестровки **антикризисного управления**:

В оригинале "опенсорсный", как прилагательное и можно было б его вставить, сохранив порядок оригинального предложения, но если перевели, то в такой формулировке начинает разрываться смысл предложения.

"рада объявить о выпуске  нашего фреймворка для оркестровки **антикризисного управления** **Dispatch**! (с открытым исходным кодом)"

2022-08-22 17:56 UTC, Xewus commented on docs/ru/docs/index.md
> +"_Если вы хотите изучить один **современный фреймворк** для создания REST API, ознакомьтесь с **FastAPI** [...] Это быстро, просто в использовании и легко в освоении [...]_"
> хотите изучить один **современный фреймворк**

какой-нибудь

> Это быстро, просто в использовании и легко в освоении [...]_"

Он быстрый, лёгкий и прост в изучении.

2022-08-22 17:56 UTC, Xewus commented on docs/ru/docs/index.md
> +**Typer** — младший брат FastAPI. И он предназначен для использования в качестве **FastAPI of CLIs**. ⌨️ 🚀
> качестве **FastAPI of CLIs**.

интерфейса командной строки для FastAPI

2022-08-22 17:56 UTC, Xewus commented on docs/ru/docs/index.md
> +Вам также понадобится сервер ASGI для производства, такой как <a href="https://www.uvicorn.org" class="external-link" target="_blank">Uvicorn</a> или <a href="https://gitlab.com/pgjones/hypercorn" cl
> производства

Честно говоря, сам затрудняюсь с этим словом...
Тут англицизмы привычнее... Может  "развёртывание" подходит лучше...

2022-08-22 17:56 UTC, Xewus commented on docs/ru/docs/index.md
>  ### Interactive API docs
???

2022-08-22 17:56 UTC, Xewus commented on docs/ru/docs/index.md
>  The server should reload automatically (because you added `--reload` to the `uvicorn` command above).
???

2022-08-22 17:56 UTC, Xewus commented on docs/ru/docs/index.md
> +### Интерактивное обновление документов API
> документов

документации

2022-08-22 17:56 UTC, Xewus commented on docs/ru/docs/index.md
> +Теперь перейдите к <a href="http://127.0.0.1:8000/docs" class="external-link" target="_blank">http://127.0.0.1:8000/docs</a>.
> перейдите к

Общепринято - "перейдите по ссылке", "перейдите на".

2022-08-22 17:56 UTC, Xewus commented on docs/ru/docs/index.md
> +### Альтернативное обновление документов API
> документов

2022-08-22 17:56 UTC, Xewus commented on docs/ru/docs/index.md
> +А теперь перейдём в <a href="http://127.0.0.1:8000/redoc" class="external-link" target="_blank">http://127.0.0.1:8000/redoc</a>.
> перейдём в

2022-08-22 17:56 UTC, Xewus commented on docs/ru/docs/index.md
> +### Резюме
Под резюме в русском языке обычно понимается бумажка описывающая. работника.
Для данного случая - "Резюмируем", "Итого", "Выоды" и т.п.

2022-08-22 17:56 UTC, Xewus commented on docs/ru/docs/index.md
> +Вы делаете это со стандартными современными типами Python.
Опять `with` тут, это не `c`, a `используя`.

2022-08-22 17:56 UTC, Xewus commented on docs/ru/docs/index.md
> +Просто стандартный **Python 3.6+**.
> Просто

Только

2022-08-22 17:56 UTC, Xewus commented on docs/ru/docs/index.md
> +    * Модели баз данных.
Модели **для** баз данных.

2022-08-22 17:56 UTC, Xewus commented on docs/ru/docs/index.md
> +    * Без `None` это было бы необходимо (как тело в случае с `PUT`).
> Без `None` это было бы необходимо

Без `None` он был бы необходим.

Вам следует попрактиковаться со словом **It**.

2022-08-22 17:56 UTC, Xewus commented on docs/ru/docs/index.md
> +Мы только поцарапали поверхность, но вы уже поняли, как все это работает.
> немного капнули

копать != капать

2022-08-22 17:56 UTC, Xewus commented on docs/ru/docs/index.md
> +Более полный пример с дополнительными функциями см. в <a href="https://fastapi.tiangolo.com/tutorial/">Учебном руководстве - Руководство пользователя</a>.
> Учебном руководстве - Руководство пользователя

Руководстве пользователя

2022-08-22 17:56 UTC, Xewus commented on docs/ru/docs/index.md
> +* Как установить **ограничения проверки** как `maximum_length` или `regex`.
> **ограничения проверки** как

ограничительные ,,,, такие как

2022-08-24 13:36 UTC, impocode commented on docs/ru/docs/index.md
> +    <img src="https://img.shields.io/pypi/pyversions/fastapi.svg?color=%2334D058" alt="Supported Python versions">
Взял из английской версии главной страницы. Чтобы было однообразно.

2022-08-24 13:39 UTC, impocode commented on docs/ru/docs/index.md
> +    <em>Фреймворк FastAPI, высокая производительность, простота в изучении, быстрота написания кода, готовность к производству</em>
> Это уже, наверное, десятая попытка перевода главной страницы ))

Честно, я даже не видел. Надо было глянуть прежде чем править.

2022-08-24 14:39 UTC, Winand commented on docs/ru/docs/index.md
> +Вам также понадобится сервер ASGI для производства, такой как <a href="https://www.uvicorn.org" class="external-link" target="_blank">Uvicorn</a> или <a href="https://gitlab.com/pgjones/hypercorn" cl
@Xewus На этапе внедрения приложения вам понадобится сервер ASGI, например, Uvicorn или Hypercorn.

2022-08-24 16:45 UTC, impocode commented on docs/ru/docs/index.md
> +Вы можете установить все это с помощью `pip install "fastapi[all]"`.
Сделал по аналогии с оригиналом.

https://github.com/tiangolo/fastapi/blob/master/docs/en/docs/index.md#optional-dependencies

2022-08-24 16:55 UTC, impocode commented on docs/ru/docs/index.md
> +* **Меньше ошибок**: Сократите примерно на 40 % ошибок, вызванных человеком (разработчиком). *
Увеличивает скорость разработки
Сокращает количество ошибок

Это имеется ввиду?

Вообще я пытался отталкиваться от того как это будет восприниматься при чтении. То есть тут такая часть.

```
Ключевые особенности:

(Ключевые особенности какие?)

- Скорость
- Быстрота разработки
- Меньше ошибок(или меньшее кол-во ошибок при разработке)
- Интуитивно понятный(тут на самом деле немного не то, то есть нет ответа на вопрос "какие?", но и с альтернативой сложно. Если есть варианты можете предложить)

и т.д.
```

То есть если писать, что-то типа "сокращает" или "увеличивает" то это ответ на вопрос "что FastAPI делает?" и надо везде написать в таком стиле, а это уже проблема так как не везде это подходит.

2022-08-24 16:59 UTC, impocode commented on docs/ru/docs/index.md
> +"_В последнее время я много где использую **FastAPI**. [...] На самом деле я планирую использовать его для всех **служб машинного обучения моей команды в Microsoft**. Некоторые из них интегрируются в
Могу поправить на "сервисов машинного обучения...", думаю это будет более близкое по смыслу. Вариант `приложений для` как мне кажется не очень подходит.

2022-08-24 17:00 UTC, impocode commented on docs/ru/docs/index.md
> +* Создайте файл `main.py` с:
Как на счет "со следующим содержимым"?

2022-08-24 17:00 UTC, impocode commented on docs/ru/docs/index.md
> +Вы увидите ответ JSON как:
Вы увидите следующий JSON ответ
Вы увидите следующий ответ JSON

Как на счет этого?

2022-08-24 17:02 UTC, impocode commented on docs/ru/docs/index.md
> +    * Кук.
Ок, согласен. Поменяю)

2022-08-24 17:03 UTC, impocode commented on docs/ru/docs/index.md
> +Мы только поцарапали поверхность, но вы уже поняли, как все это работает.
Поддержу вариант "немного копнули"

2022-08-24 17:04 UTC, impocode commented on docs/ru/docs/index.md
> +* Объявление **параметров** из других мест, таких как: **заголовки**, **куки**, **поля формы** и **файлы**.
👍

2022-08-24 17:06 UTC, impocode commented on docs/ru/docs/index.md
> +* **GraphQL** интеграция с <a href="https://strawberry.rocks" class="external-link" target="_blank">Strawberry</a> и другими библиотеками.
Это не у меня, это у оригинала))

https://github.com/tiangolo/fastapi/commit/4b968c4e3907066a994e125de1fa90768e9c9188

2022-08-24 17:16 UTC, Xewus commented on docs/ru/docs/index.md
> +    <em>Фреймворк FastAPI, высокая производительность, простота в изучении, быстрота написания кода, готовность к производству</em>
В оригинале написано, как "FastAPI (это) ...", но, вероятно, предложение от @Winand  вполне достаточное, тем более, что этот блок текста повторяется часто в документации.

2022-08-24 19:25 UTC, impocode commented on docs/ru/docs/index.md
> +* **Меньше ошибок**: Сократите примерно на 40 % ошибок, вызванных человеком (разработчиком). *
В тоже время(сейчас заметил) тогда надо тогда и дальше в этом стиле написать. Лёгкость, краткость, надёжность и т.д.

2022-08-24 19:25 UTC, impocode commented on docs/ru/docs/index.md
> +* **Меньше ошибок**: Сократите примерно на 40 % ошибок, вызванных человеком (разработчиком). *
В тоже время(сейчас заметил) тогда надо тогда и дальше в этом стиле написать. Лёгкость, краткость, надёжность и т.д.

2022-08-25 12:19 UTC, Xewus commented on docs/ru/docs/index.md
> +* **Меньше ошибок**: Сократите примерно на 40% ошибок, вызванных человеком (разработчиком). *
_Здесь и далее я не буду настаивать на исправлении, но оставлю некоторые комментарии для рассмотрения переводчиком._
> на 40% ошибок

на 40% количество ошибок

2022-08-25 12:19 UTC, Xewus commented on docs/ru/docs/index.md
> +Теперь измените файл `main.py`, чтобы получить тело из `PUT` запроса.
Для этой строки и прочих, где `body` переводится, как `тело` .
Да, это наиболее используемый перевод, но на самом деле `body` означает некую цельную собранную конструкцию.
То есть, если фреймворк считать скелетом, то вместе со всеми навешанными зависимостями будет `body` .


Касательно данного случая. Читатель, конечно, поймёт о чём речь, но всё же, услышав слово `тело` , обычно представляется человечское тело, потому, возможно, стоит дополнить `тело ответа`. В оригинале такого уточнения нет, потому что в английском очень сильную роль играют окружающие контексты.

2022-08-25 12:19 UTC, Xewus approved these changes

2022-08-25 12:47 UTC, Winand commented on docs/ru/docs/index.md
> +FastAPI — это современный, быстрый (высокопроизводительный) веб-фреймворк для создания API используя Python 3.6+ на основе стандартных подсказок типов Python.
В старом переводе эта фраза выглядит лучше, мне кажется

[FastAPI - это современный, высокопроизводительный веб-фреймворк для построения API на Python 3.6+, в основе которого лежит стандартная аннотация типов.](https://github.com/tiangolo/fastapi/pull/2985/files#r672037797)

2022-08-25 12:53 UTC, Winand commented
Неплохо бы ещё сравнить с #2985 и #1363, если там встречаются удачные формулировки, чего им пропадать

2022-08-25 13:32 UTC, RobotToI commented on docs/ru/docs/index.md
> +* **Меньше ошибок**: Сократите примерно на 40 % ошибок, вызванных человеком (разработчиком). *
Вероятно ты прав, я тоже не посмотрел. Нужно уже у Себастиана спросить поддерживать ли однообразность перевода во всем тексте

2022-08-25 13:33 UTC, RobotToI commented on docs/ru/docs/index.md
> +"_В последнее время я много где использую **FastAPI**. [...] На самом деле я планирую использовать его для всех **служб машинного обучения моей команды в Microsoft**. Некоторые из них интегрируются в
Согласен - сервисов машинного обучения, хорошо звучит

2022-08-25 13:33 UTC, RobotToI commented on docs/ru/docs/index.md
> +* Создайте файл `main.py` с:
Супер

2022-08-25 13:35 UTC, RobotToI commented on docs/ru/docs/index.md
> +* **GraphQL** интеграция с <a href="https://strawberry.rocks" class="external-link" target="_blank">Strawberry</a> и другими библиотеками.
Ой(

2022-08-25 13:38 UTC, RobotToI approved these changes

2022-08-26 10:35 UTC, impocode commented
> Неплохо бы ещё сравнить с #2985 и #1363, если там встречаются удачные формулировки, чего им пропадать

Я посмотрел эти PR'ы. Думаю, мы уже взяли самые удачные формулировки) В остальном, как мне кажется, там очень много неудачных(неподходящих) переводов(Пример: перевод `Note` как `Хозяйке на заметку`😅😆).

Возможно, я что-то мог упустить, проглядеть. Если у вас есть предложения, можете написать.

2022-08-26 14:45 UTC, tiangolo commented
Thanks @impocode! :cake: 

And thanks for the reviews @Winand, @RobotToI, @Xewus! :coffee:

2022-08-26 14:45 UTC, merged

2022-08-29 11:57 UTC, Xewus commented
Штош, господа, теперь приглашаю вас поревьюить [тут](https://github.com/tiangolo/fastapi/pull/5315)