Add Russian translation for docs/deployment/index.md
fastapi/fastapi pull request #5336
Opened 2022-09-01 16:24 UTC by Xewus

2022-09-20 14:09 UTC, zhanymkanov requested changes

2022-09-20 14:09 UTC, zhanymkanov commented on docs/ru/docs/deployment/index.md
> +Для **веб-приложения** обычно требуется разместить его на удаленном компьютере с серверной программой, которая обеспечивает хорошую производительность, стабильность и т. д., Чтобы ваши пользователи м
беспрерывно и беспроблемно

2022-09-20 19:48 UTC, Xewus commented on docs/ru/docs/deployment/index.md
> +Для **веб-приложения** обычно требуется разместить его на удаленном компьютере с серверной программой, которая обеспечивает хорошую производительность, стабильность и т. д., Чтобы ваши пользователи м
Лет 15 назад прочитал некоего Левашова, до сих пор действует :))

2022-10-12 21:44 UTC, alldevic commented
Не смог нормально прочесть, постоянно чувствовал что-то не то. Текст небольшой, прогнал через glvrd. Разметка убилась, но возможно мои формулировки покажутся удачными. Английскую версию не читал, опирался на смысл перевода в реквесте.
---------------------------------------------------------
Развёртывание - Введение

Развернуть приложение FastAPI относительно легко.

Да что такое это - "развёртывание"?!

Термин развернуть приложение, англ. deployment, означает выполнение необходимых шагов, чтобы сделать приложение доступным для пользователей.

Традиционно для веб-приложения требуется размещение на удаленном компьютере с серверной программой, которая дает лучшие производительность, стабильность и надежность, чтобы пользователи могли эффективно, беспрерывно и беспроблемно обращаться к приложению.

Это отличется от разработки, когда код постоянно меняется, ломается и исправляется, сервер разработки останавливается и перезапускается и т. д.

Стратегии развертывания

Для каждого конкретного случая применимы различные способы развернуть приложение.
Это можно сделать и самостоятельно при помощи большого числа инструментов. Например, воспользоваться облачным сервисом, который возьмет часть работы на себя. Возможны и другие варианты.

В этом блоке я покажу некоторые концепции, которые стоит рассмотреть при развертывании приложения FastAPI, хотя большинство из них применимо и к остальным типам веб-приложений.

Вы узнаете больше деталей и методов развертывания в последующих разделах.

2022-10-13 07:21 UTC, Xewus commented
По мне, "главред", в данном случае, сработал плохо.

> `Да что такое это - "развёртывание"?!` VS  `Да что такое это ваше - "развёртывание"?!`
Тут просто отсылка к распространённому мему, из песни слов не выкинешь.

> ` развернуть приложение, англ. deployment`  VS ` развернуть приложение`
Зачем-то вставлено английское слово, хотя это и есть перевод с английского языка.

> `Традиционно для веб-приложения` VS `Обычно веб-приложения`
Масло масляное.
>  `код постоянно меняется, ломается` VS ` вы постоянно меняете код, ломаете его `
Разработка - это как раз процесс организованный кодером, то есть "вами", а не "оно само".

И т.д. Просто тасование слов, с места на место, замена на синонимы и т.п.

Тем не менее переставил пару слов тоже.

2022-10-29 13:49 UTC, Kirilex requested changes

2022-10-29 13:49 UTC, Kirilex commented on docs/ru/docs/deployment/index.md
> +Развернуть приложение **FastAPI** относительно легко.
Относительно чего? Как-то относительно звучит.

2022-10-29 13:49 UTC, Kirilex commented on docs/ru/docs/deployment/index.md
> +Термин **развёртыване** [приложения} означает выполнение необходимых шагов, чтобы сделать приложение **доступным для пользователей**.
>  **развёртыване*

2022-10-29 13:49 UTC, Kirilex commented on docs/ru/docs/deployment/index.md
> +Обычно **веб-приложения** размещают на удаленном компьютере с серверной программой, которая обеспечивает хорошую производительность, стабильность и т. д., Чтобы ваши пользователи могли эффективно, бе
> удаленном

Ё-моё!

2022-10-29 13:49 UTC, Kirilex commented on docs/ru/docs/deployment/index.md
> +Это отличется от **разработки**, когда вы постоянно меняете код, ломаете его и исправляете, останавливаете и перезапускаете сервер разработки и т. Д.
>  ломаете его

Делаете в нём ошибки

2022-10-29 13:49 UTC, Kirilex commented on docs/ru/docs/deployment/index.md
> +## Стратегии развертывания
> развертывания

Ё-моё!

2022-10-29 13:49 UTC, Kirilex commented on docs/ru/docs/deployment/index.md
> +Вы можете **развернуть сервер** самостоятельно, используя различные инструменты. Можно использовать **облачный сервис**, который выполнит часть работы за вас. Возможны и другие варианты.
> Можно использовать

Как насчёт "например"?

2022-10-29 13:49 UTC, Kirilex commented on docs/ru/docs/deployment/index.md
> +Вы узнаете больше деталей, которые нужно иметь в виду, и некоторые методы для этого в последующих разделах. ✨
"Последующие разделы" лучше в начало. Это "английское" построение фразы.

2022-10-29 16:58 UTC, Xewus reviewed
...

2022-10-31 18:17 UTC, Kirilex approved these changes

2022-11-01 06:45 UTC, zhanymkanov approved these changes

2022-11-03 11:45 UTC, tiangolo commented
Great, thank you @Xewus! :bow: 

And thanks for the reviews @zhanymkanov and @Kirilex :cake:

2022-11-03 11:51 UTC, merged