🌐 Add Dutch translation for `docs/nl/docs/index.md`
fastapi/fastapi pull request #5366
Opened 2022-09-09 12:56 UTC by maxscheijen

Relates to #4701

This translates`docs/index.md` into Dutch.

2022-09-17 11:37 UTC, Kludex commented
I guess it's duplicated of #4770 😟

A review there will probably be welcome 👀

2023-04-30 23:12 UTC, tony1658 requested changes
A couple typos and inconsistency with combining informal and formal writing.

2023-04-30 23:12 UTC, tony1658 commented on docs/nl/docs/index.md
> +* Valideren dat `item_id` van het type `int` is voor `GET` en `PUT` verzoeken.
Doesn't Validate that the `item_id` translate to Valideren dat **de** `ìtem_id`?

2023-04-30 23:12 UTC, tony1658 commented on docs/nl/docs/index.md
> +nafhankelijke TechEmpower benchmarks tonen **FastAPI** applicaties draaiend onder Uvicorn als <a href="https://www.techempower.com/benchmarks/#section=test&runid=7464e520-0dc2-473d-bd34-dbdfd7e85911&
Do you mean **Onafhankelijke** instead?

2023-04-30 23:12 UTC, tony1658 commented on docs/nl/docs/index.md
> +* <a href="https://andrew-d.github.io/python-multipart/" target="_blank"><code>python-multipart</code></a> - Vereist als je het <abbr title="chet omzetten van de string die uit een HTTP verzoek komt
Change `chet omzetten` to `het omzetten van`

2023-04-30 23:12 UTC, tony1658 commented on docs/nl/docs/index.md
> +U kunt deze allemaal installeren met `pip install "fastapi[all]"`.
You are using `je` and `u` isn't it better to either choose the formal or informal version instead for consistency?

2023-04-30 23:18 UTC, tony1658 commented
> I guess it's duplicated of #4770 😟
> 
> A review there will probably be welcome 👀

That one translates the tutorial instead of the index page. So, not a duplicate but yeah I can take a look.

2024-03-31 02:48 UTC, tiangolo commented
It seems this was handled in another PR, so I'm gonna close this one, but thanks for the effort! :coffee:

2024-03-31 02:48 UTC, closed without merging