🌐 🔠 📄 🐢 Translate docs to Emoji 🥳 🎉 💥 🤯 🤯
fastapi/fastapi pull request #5385
Opened 2022-09-13 17:24 UTC by LeeeeT

**I just really love 💕 🤩 the idea of adding some emojis 😄😁😅 here and there across the 📄 docs 📄. So I decided to write ✍ the entire documentation out of emojis 💥🎉🌟. All these words 🤮🤢 and... fancy-looking letters.. 👎👎👎 ugh... That's so boring 🥱. I believe reading documentation made of emojis will definitely (don't argues 😛🤪) be much funnier 😃 and easier 😻 for beginners. So here it is, don't thank me. 💥💯💫⭐🔥🔥**

2022-09-13 17:52 UTC, timoniq approved these changes

2022-09-13 18:24 UTC, FeeeeK approved these changes

2022-09-13 18:36 UTC, MadL1me requested changes

2022-09-13 18:36 UTC, MadL1me commented on docs/emj/docs/features.md
> +
I think "Security" in native emoji is more like "👮" then your translated "💂‍♂". However, the other parts is perfect, I like it

2022-09-13 18:36 UTC, MadL1me approved these changes

2022-09-13 18:36 UTC, yallxe approved these changes

2022-09-13 18:37 UTC, FeeeeK requested changes
It looks like the markup is a bit broken, making it hard to read such great documentation.
https://6320bdb2dc53d17efc1ba804--fastapi.netlify.app/emj/

2022-09-13 18:42 UTC, Dragonprod approved these changes

2022-09-13 18:51 UTC, HyperHowl approved these changes

2022-09-13 18:58 UTC, kiriharu approved these changes

2022-09-13 18:58 UTC, alexcher-im approved these changes

2022-09-13 18:59 UTC, kesha1225 approved these changes

2022-09-13 19:06 UTC, dhvcc approved these changes

2022-09-13 19:06 UTC, KurimuzonAkuma approved these changes

2022-09-13 23:11 UTC, vypivshiy commented on docs/emj/docs/tutorial/background-tasks.md
> +# 🖥 🎯
![image](https://tenor.com/bRqG6.gif)

2022-09-13 23:12 UTC, vypivshiy approved these changes

2022-09-14 02:22 UTC, txlyre approved these changes

2022-09-14 03:59 UTC, rmdlv approved these changes

2022-09-14 08:21 UTC, CringeDeveloper commented on docs/emj/mkdocs.yml
> +    name: en - English
Maybe you should use country flag instead?

2022-09-14 13:12 UTC, ichetiva approved these changes

2022-09-14 13:25 UTC, tiangolo commented
Hey there! Is this coming from a joke or something somewhere else? :sweat_smile: 

I imagine that given all the approvals and interactions, but I didn't see the original joke... :shrug:

2022-09-14 13:29 UTC, FeeeeK commented
> @FeeeeK 🔥🔥🔥 Fixed 🔥🔥🔥

Great💫, I think this is a very nice👍 change, making the documentation📝 much friendlier🙌. It's a pity that the previous⏮️ version of the `Concurrency and async / await` documentation was removed❌, I really miss it🥲.

2022-09-14 13:29 UTC, FeeeeK approved these changes

2022-09-14 13:40 UTC, mrMiiao commented
Really 😃😃😃 cool 😍😍🙂 idea 👍🧠🫦 bro 🥵😎🥵!!!

2022-09-14 13:55 UTC, KurimuzonAkuma approved these changes

2022-09-14 14:22 UTC, FeeeeK commented
@tiangolo You see right through us. Forgive us this joke. We're just really sad about the decision to remove the emojis in #3273. They made the documentation unusual and stand out from the documentation of other frameworks. That's why we wanted to bring back that distinctive feature, so we'd be very happy if you could merge this pull request.❤️

2022-09-14 17:47 UTC, LeeeeT commented
I think I could do a full translation of all the pages as well as fix a few formatting issues if you would ever consider adding an emoji version of the documentation, just for fun 😊

2022-09-19 02:03 UTC, d1snin approved these changes

2022-09-20 13:58 UTC, vypivshiy approved these changes

2022-09-20 15:58 UTC, eoftgge approved these changes

2022-09-24 10:28 UTC, baseplate-admin approved these changes

2022-09-24 20:35 UTC, adomerlee approved these changes

2022-09-30 10:00 UTC, VodoGamer approved these changes

2022-10-06 12:01 UTC, danielh2942 approved these changes
I hate it
LGTM

2023-02-07 16:25 UTC, tiangolo commented
So... I'm considering adding this for April Fool's Day. That's next April 1st. 🤓😂

2023-02-07 18:53 UTC, LeeeeT commented
Cool! 🥳 I'm going to finish up translating the remaining pages and prepare this for merging as promised. 😄

2023-03-10 23:57 UTC, BrycensRanch commented
LGTM

2023-03-13 02:20 UTC, FeeeeK commented
I tried to send a review, but for some reason github just gives an error, I have already contacted support, I hope they will help, but for now please wait a bit.

2023-03-17 02:31 UTC, dikiaap approved these changes

2023-03-20 15:31 UTC, notdanhan approved these changes
LGTM :+1:

2023-03-20 16:04 UTC, baseplate-admin approved these changes
LGTM

2023-03-31 09:35 UTC, FeeeeK commented
Now I know that github doesn't like this
![Screenshot_20230331-133513_GitHub.png](https://user-images.githubusercontent.com/26704473/229084167-fb90ba28-a13a-4572-9c47-999607f9f399.png)

2023-03-31 09:49 UTC, LeeeeT commented
@FeeeeK It's probably for the best... 😐

2023-04-01 09:25 UTC, tiangolo approved these changes
I'm actually impressed. You did an amazing job here. The consistency of the translation from the original is great. 🤓😎

---

I moved the content from `emj` to`em`, that simplifies the URLs and makes using the internal scripts simpler (to run the docs live locally, etc).

`em` is not assigned to any other language so that's fine. https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes#Table_of_all_possible_two_letter_codes

---

I imagine you automatized parts of it, I would love to know how you did it!

---

I'm also cracking up. 😂

---

Thank you for your contribution! 🙇🍰

2023-04-01 09:26 UTC, merged

2023-04-01 09:51 UTC, FeeeeK commented
> ---
> 
> I imagine you automatized parts of it, I would love to know how you did it!
> 
> ---
@tiangolo For all this, regexes were used to separate the text from code blocks, and then the translation through Yandex translator ([link](https://translate.yandex.com/?source_lang=en&target_lang=emj)), and after all this, I fixed some inaccuracies and broken emojis. I think this can also be automated and converted to GitHub action, but we need to make it a little more stable.

2023-04-01 10:46 UTC, LeeeeT commented
Yea, it required some reverse engineering and use of private API in order to automate translating with Yandex. 😅 And my script for extracting readable and translatable text from `md` files is... well, it's better not to see it. 😹😹 Also, Yandex translator is far from ideal and some manual editing is required. So I don't think it should (and can) be automated. 🫤

Anyway, I want to thank all the participants of this pull request. ❤️ You guys made the prank even funnier. 🤪🥰