Update LICENSE
fastapi/fastapi pull request #5402
Opened 2022-09-16 15:11 UTC by leirons

2022-09-16 15:16 UTC, ohld approved these changes

2022-09-16 15:17 UTC, insulineru approved these changes

2022-09-16 15:27 UTC, ohld commented
LGTM

2022-09-16 16:13 UTC, theshadowagent approved these changes

2022-09-16 17:38 UTC, qweered approved these changes

2022-09-18 20:23 UTC, JarroVGIT requested changes
You shouldn't update the year in your copyright statement, it should be the year when the work was first published. 

> The copyright symbol consists of a letter “c” in a circle, followed by the name of the owner of the copyright and the year the work was first published.

[Source](https://www.legalline.ca/legal-answers/using-copyright-symbol/)

Suggestion to close this PR.

2022-10-20 11:14 UTC, tiangolo commented
Thanks @JarroVGIT ! 🙇

Indeed, this is not necessary and actually invalid, so I'll close this one.

2022-10-20 11:14 UTC, closed without merging