Python snippet uses 3.10 not 3.9
fastapi/fastapi pull request #5405
Opened 2022-09-18 15:54 UTC by ShehabMMohamed

2022-09-18 18:02 UTC, Kludex approved these changes

2022-09-18 22:44 UTC, lieryan approved these changes

2022-09-18 23:23 UTC, yezz123 approved these changes

2022-09-19 08:08 UTC, mbroton approved these changes

2022-09-21 13:47 UTC, pedroimpulcetto approved these changes

2022-11-10 10:12 UTC, BilalAlpaslan approved these changes

2022-12-16 19:32 UTC, iudeen requested changes
This PR has no changes. Suggest this to be closed.

2023-06-22 11:26 UTC, tiangolo commented
Thank you! 🚀 

It seems this was solved in another PR, not sure which one. Given that I'll close this one, but thanks for your contribution! ☕ 🍰

2023-06-22 11:26 UTC, closed without merging