Add: russian translation for `docs/ru/docs/deployment/https.md`
fastapi/fastapi pull request #5494
Opened 2022-10-13 14:57 UTC by emp7yhead

Russian translate `docs/ru/docs/deployment/https.md`
related: #1362

2022-10-29 18:49 UTC, Xewus requested changes

2022-10-29 18:49 UTC, Xewus commented on docs/ru/docs/deployment/https.md
> +* Шифрование соединения происходит на **TCP-уровне**.
> на **TCP-уровне**.

на уровне протокола ТСР

2022-10-29 18:49 UTC, Xewus commented on docs/ru/docs/deployment/https.md
> +* **HTTPS-сертификаты** "сертифицируют" **определенный домен**, но протокол и шифрование происходит на TCP-уровне, **не зная** с каким доменом ведется работа.
> но протокол и шифрование

Честно говоря, непонятно, что понимается под термином протокол"...   

>на TCP-уровне, **не зная** с каким доменом ведется работа.

на уровне протокола ТСР, когда ещё не известно имя домена

2022-10-29 18:49 UTC, Xewus commented on docs/ru/docs/deployment/https.md
> +* Существует **расширение** протокола **TLS** (того, что управляет шифрованием на TCP-уровне, перед HTTP), которое называется **<a href="https://ru.wikipedia.org/wiki/Server_Name_Indication" class="e
> Индикация имени сервера

Указание имени сервера

2022-10-29 18:49 UTC, Xewus commented on docs/ru/docs/deployment/https.md
> +    * Для работы SNI необходимо, чтобы **один** компонент (программа), запущенный на сервере и слушающий **публичный IP-адрес**, должен иметь доступ ко **всем HTTPS-сертификатам** на сервере.
> должен иметь доступ

имел

2022-10-29 18:49 UTC, Xewus commented on docs/ru/docs/deployment/https.md
> +Нормальной практикой является ситуация, при которой **одна программа/HTTP-сервер**, запущенный на сервере (машине, хосте, и т.д.) и **управлениющий всеми частями HTTPS**: получение **зашифрованных HT
> (в нашем случае приложение **FastAPI**)

(в нашем случае приложению **FastAPI**)

> Такой сервер зовется

Такой сервер называется

2022-10-29 18:49 UTC, Xewus commented on docs/ru/docs/deployment/https.md
> +DNS-сервера подскажут браузеру  какой конкретный **IP-адрес** использовать. Это будет публичный IP-адрес, используемый вашим сервером, который вы настроили в DNS-серверах.
> браузеру какой

Между ними запятая или тире.

2022-10-29 18:49 UTC, Xewus commented on docs/ru/docs/deployment/https.md
> +**Только один процесс** на сервере может слушать определенный **порт** на определенном **IP-адресе**. Могут быть и другие процессы, слушающие на других портах тот же самый IP-адрес, но только один пр
> но только один процесс для каждой комбинации IP-адреса и порта.

но может быть только один процесс для каждой комбинации IP-адреса и порта.

2022-10-29 18:49 UTC, Xewus commented on docs/ru/docs/deployment/https.md
> +Прокси-сервер завершения TLS будет использовать выбранный способ шифрования для **расшифровки запроса**, и перенаправит **простой (расшифрованный) HTTP-запрос** процессу запущенного приложения (напри
> например процесс Uvicorn

например, процессу Uvicorn

2022-10-29 18:49 UTC, Xewus commented on docs/ru/docs/deployment/https.md
> +Прокси-сервер завершения TLS **зашифрует ответ** с использованием выбранного способа шифрования (that started with the certificate for `someapp.example.com`), и отправит его обратно браузеру.
> (that started with the certificate for `someapp.example.com`),

???

2022-10-29 18:49 UTC, Xewus commented on docs/ru/docs/deployment/https.md
> +Далее, браузер удостоверится что ответ валиден, зашифрован правильным криптографическим ключом и т.д. Затем он **расшифровывает ответ** и обрабатывает его.
> удостоверится что

удостоверится, что

2022-10-29 18:49 UTC, Xewus commented on docs/ru/docs/deployment/https.md
> +    * С другой стороны, you might have to stop the TLS Termination Proxy momentarily, start the renewal program to acquire the certificates, then configure them with the TLS Termination Proxy, and th
???

2022-10-29 18:52 UTC, Xewus commented
Is it necessary to copy pictures?

2022-10-31 18:00 UTC, Winand commented on docs/ru/docs/deployment/https.md
> +Итак, **с точки зрения разработчика** есть несколько вещей, которые надо держать в уме, размышляя о HTTPS:
С точки зрения разработчика нужно учитывать следующие особенности работы с HTTPS:

2022-11-02 16:38 UTC, emp7yhead commented
@Xewus idk what to do with pictures. I thought it can be useful if someone decide to translate them. Everything will be in one place

2022-11-02 21:44 UTC, Xewus reviewed
Кроме указанных двух моментов у меня предложений по улучшению нет. Как понадобится апрувнуть - тыкнешь справа верху на кнопку запрос.
И по картинкам. Учитывая скорость перевода документации - я б не стал надеяться, что кто-то за них возьмётся, а на перестановку ссылок всё-таки тратишь своё время.

2022-11-02 21:44 UTC, Xewus commented on docs/ru/docs/deployment/https.md
> +**С точки зрения разработчика** нужно учитывать следующие особенности работы функционирования HTTPS:
> работы функционирования

Может одно слово оставить?

2022-11-02 21:44 UTC, Xewus commented
После тестов даётся [ссылка](https://63629ce248363a2f0264b3d4--fastapi.netlify.app/), где можно глянуть результат. Там нет твоей страницы. Видимо запамятовал про `fastapi/docs/ru/mkdocs.yml`.

2022-11-03 08:06 UTC, Winand commented on docs/ru/docs/deployment/https.md
> +    Если вы торопитесь или вам неинтересно, читайте следующие разделы пошаговой инструкции по настройке развертывания с использованием различных технологий.
кажется, во фразе "по настройке развертывания" есть тавтология

2022-11-09 15:32 UTC, spacesphere commented on docs/ru/docs/deployment/https.md
> +    * Так что **сертификация и шифрование** выполняется **перед HTTP**.
> сертификация

я бы сказала, что "проверка/обработка сертификата" чаще используется в таком контексте

2022-11-09 15:34 UTC, spacesphere commented on docs/ru/docs/deployment/https.md
> +    * Несмортря на это, имеется **решение** данной проблемы.
> Несмортря

Очепяточка :)

2022-11-09 15:36 UTC, spacesphere commented on docs/ru/docs/deployment/https.md
> +Нормальной практикой является ситуация, при которой **одна программа/HTTP-сервер**, запущенный на сервере (машине, хосте, и т.д.) и **управлениющий всеми частями HTTPS**: получение **зашифрованных HT
> Нормальной практикой

скорее "распространённой"

2022-11-09 15:43 UTC, spacesphere commented on docs/ru/docs/deployment/https.md
> +Первая часть взаимодействия это просто установление соединения мужду клиентом и сервером для согласования используемых криптографических ключей и т.д.
Первая часть взаимодействия - это...

2022-11-09 15:54 UTC, spacesphere commented on docs/ru/docs/deployment/https.md
> +**Только один процесс** на сервере может слушать определенный **порт** на определенном **IP-адресе**. Могут быть и другие процессы, слушающие на других портах тот же самый IP-адрес, но может быть тол
> слушающие на других портах тот же самый IP-адрес

IP-адрес точно никто не слушает :)

2022-11-09 15:54 UTC, spacesphere commented on docs/ru/docs/deployment/https.md
> +В этом случает, будет использован сертификат для `someapp.example.com`.
```suggestion
В этом случае будет использован сертификат для `someapp.example.com`.
```

2022-11-09 15:56 UTC, spacesphere commented on docs/ru/docs/deployment/https.md
> +После этого, между клиентом и сервером устанавливается **зашифрованное TCP-соединение**, которое обеспечивает TLS. Это соединение используется для начала фактического **HTTP-соединения**.
> После этого,

запятая тут лишняя

2022-11-09 16:23 UTC, spacesphere commented on docs/ru/docs/deployment/https.md
> +Итак, клиент шлет **HTTPS-запрос**. Это всего лишь обычный HTTP-запрос переданный через зашифрованное TLS-соединение.
```suggestion
Итак, клиент шлет **HTTPS-запрос**. Это всего лишь обычный HTTP-запрос, переданный через зашифрованное TLS-соединение.
```

2022-11-09 16:28 UTC, spacesphere commented on docs/ru/docs/deployment/https.md
> +Прокси-сервер завершения TLS будет использовать выбранный способ шифрования для **расшифровки запроса**, и перенаправит **простой (расшифрованный) HTTP-запрос** процессу запущенного приложения (напри
```suggestion
Прокси-сервер завершения TLS будет использовать выбранный способ шифрования для **расшифровки запроса** и перенаправит **простой (расшифрованный) HTTP-запрос** процессу запущенного приложения (например, процессу Uvicorn с запущенным приложением FastAPI).
```

2022-11-09 16:28 UTC, spacesphere commented on docs/ru/docs/deployment/https.md
> +Прокси-сервер завершения TLS **зашифрует ответ** с использованием выбранного способа шифрования (который начался с сертификата для `someapp.example.com`), и отправит его обратно браузеру.
```suggestion
Прокси-сервер завершения TLS **зашифрует ответ** с использованием выбранного способа шифрования (который начался с сертификата для `someapp.example.com`) и отправит его обратно браузеру.
```

2022-11-09 16:29 UTC, spacesphere commented on docs/ru/docs/deployment/https.md
> +Первая часть взаимодействия это просто установление соединения мужду клиентом и сервером для согласования используемых криптографических ключей и т.д.
```suggestion
Первая часть взаимодействия - это просто установление соединения мужду клиентом и сервером для согласования используемых криптографических ключей и т.д.
```

2022-11-09 17:10 UTC, Winand commented on docs/ru/docs/deployment/https.md
> +**Только один процесс** на сервере может слушать определенный **порт** на определенном **IP-адресе**. Могут быть и другие процессы, слушающие на других портах тот же самый IP-адрес, но может быть тол
Согласен. И ещё слишком много раз глагол "мочь" повторяется. Могу предложить что-то такое:

**Только один процесс** на сервере слушает один определённый **порт** на определённом **IP-адресе**. Процессы могут прослушивать каждый свои порты на одном и том же IP-адресе, но любой комбинации IP-адреса и порта будет соответствовать только один процесс.

2022-11-09 19:37 UTC, Xewus commented on docs/ru/docs/deployment/https.md
> +Нормальной практикой является ситуация, при которой **одна программа/HTTP-сервер**, запущенный на сервере (машине, хосте, и т.д.) и **управлениющий всеми частями HTTPS**: получение **зашифрованных HT
> и **управлениющий всеми частями HTTPS**:

Опечатка.

2023-02-01 17:48 UTC, closed without merging