features.md page tamil translation
fastapi/fastapi pull request #5565
Opened 2022-10-31 18:13 UTC by arunppsg

This PR adds translation of `features.md` to tamil.

2022-11-03 11:47 UTC, tiangolo commented
Great! Let me know when the PR is ready for review and I'll add the label `awaiting review` so that others can come and review it and then I can merge it. :rocket:

2023-06-27 00:36 UTC, tiangolo commented
📝 Docs preview for commit f15f6bc0ea47fe57de3796b69eb9dc22a710a40e at: https://649a2f0297baca1ed99aa116--fastapi.netlify.app

2023-06-27 00:48 UTC, tiangolo commented
📝 Docs preview for commit 559aafe2f3b4d1654d55376b5b38ce967d09effb at: https://649a31ce1636a4208c534ca6--fastapi.netlify.app

2023-06-27 00:57 UTC, tiangolo commented
Great @dineshsrd! Yes, please help review the PR.

You can see the instructions here: https://fastapi.tiangolo.com/contributing/#translations that includes a link with instructions to add a review to a PR.

2024-03-31 02:49 UTC, tiangolo commented
@dineshsrd, it would be great if you could add your review to the PR. You would have to go to the "Files" tab and there click the button to add your review.

2024-04-01 13:21 UTC, codespearhead commented
@dineshsrd If you happen to know two other Tamil-speaking developers that you can also review this PR, even better. [Here's how you can review PRs btw](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request#starting-a-review).

2024-04-02 03:58 UTC, dineshsrd requested changes
Please do complete the translation for rest of the doc.

2024-04-02 03:58 UTC, dineshsrd commented on docs/ta/docs/features.md
> +That can then be used like:
Please add translation here.

2024-04-02 03:58 UTC, dineshsrd commented on docs/ta/docs/features.md
> +நிங்கள்
Please complete the translation for rest of the docs.

2024-04-02 03:59 UTC, dineshsrd commented
@tiangolo Review done and comments added.

2024-04-02 10:08 UTC, arunppsg commented
@dineshsrd thank you for the review. i will update the docs with suggestions by end of this week.

2024-06-02 08:58 UTC, arunppsg commented
I am closing this pull request as I am not able to prioritize time for this, sorry!

2024-06-02 08:58 UTC, closed without merging