Add Chinese translation for async.md
fastapi/fastapi pull request #5591
Opened 2022-11-04 14:12 UTC by mkdir700

This PR translates async.md in Chinese.

2022-11-08 10:29 UTC, Jedore requested changes
Some suggestion changes, especially for "CPU bound"/"IO bound"

2022-11-08 10:29 UTC, Jedore commented on docs/zh/docs/async.md
> +CPU 绑定操作的常见示例是需要复杂的数学处理。
```suggestion
CPU 密集型操作的常见示例是需要复杂的数学处理。
```

2022-11-08 10:29 UTC, Jedore commented on docs/zh/docs/async.md
> +由于大多数执行时间是由实际工作（而不是等待）占用的，并且计算机中的工作是由 <abbr title="Central Processing Unit">CPU</abbr> 完成的，所以他们称这些问题为"CPU 绑定"。
```suggestion
由于大多数执行时间是由实际工作（而不是等待）占用的，并且计算机中的工作是由 <abbr title="Central Processing Unit">CPU</abbr> 完成的，所以他们称这些问题为"CPU 密集型"。
```

2022-11-08 10:29 UTC, Jedore commented on docs/zh/docs/async.md
> +并且，您也可以利用并行和多进程（让多个进程并行运行）的优点来处理与机器学习系统中类似 **CPU 绑定** 的工作。
```suggestion
并且，您也可以利用并行和多进程（让多个进程并行运行）的优点来处理与机器学习系统中类似 **CPU 密集型** 的工作。
```

2022-11-08 10:29 UTC, Jedore commented on docs/zh/docs/async.md
> +这个执行的时间大多是在等待 <abbr title="Input and Output">I/O</abbr> 操作，因此它们被叫做 "I/O 绑定" 操作。
```suggestion
这个执行的时间大多是在等待 <abbr title="Input and Output">I/O</abbr> 操作，因此它们被叫做 "I/O 密集型" 操作。
```

2022-11-08 10:29 UTC, Jedore commented on docs/zh/docs/async.md
> +你可以跳过这里。
```suggestion
    你可以跳过这里。
```

2022-11-08 10:29 UTC, Jedore commented on docs/zh/docs/async.md
> +如果您使用过另一个不以上述方式工作的异步框架，并且您习惯于用普通的 `def` 定义普通的仅计算路径操作函数，以获得微小的性能增益（大约100纳秒），请注意，在 FastAPI 中，效果将完全相反。在这些情况下，最好使用 `async def`，除非路径操作函数内使用执行阻塞的代码。
```suggestion
如果您使用过另一个不以上述方式工作的异步框架，并且您习惯于用普通的 `def` 定义普通的仅计算路径操作函数，以获得微小的性能增益（大约100纳秒），请注意，在 FastAPI 中，效果将完全相反。在这些情况下，最好使用 `async def`，除非路径操作函数内使用执行阻塞 <abbr title="输入/输出：磁盘读写，网络通讯.">I/O</abbr> 的代码。
```

2022-11-08 10:29 UTC, Jedore commented on docs/zh/docs/async.md
> +否则，您最好应该遵守的指导原则<a href="#in-a-hurry">赶时间吗？</a>.
```suggestion
否则，您最好应该遵守的指导原则<a href="#_1">赶时间吗？</a>.
```

2022-11-08 11:33 UTC, mkdir700 commented
thank you @Jedore

2022-11-09 01:44 UTC, Jedore approved these changes
well done 👍

2022-11-14 09:15 UTC, Jedore commented on docs/zh/docs/async.md
> +CPU 绑定操作的常见示例是需要复杂的数学处理。
@mkdir700  what abous this?

2022-11-14 09:19 UTC, mkdir700 commented on docs/zh/docs/async.md
> +由于大多数执行时间是由实际工作（而不是等待）占用的，并且计算机中的工作是由 <abbr title="Central Processing Unit">CPU</abbr> 完成的，所以他们称这些问题为"CPU 绑定"。
I'm sorry.I didn't see it.

2022-11-22 10:07 UTC, Lenclove commented
Well, it seems someone have checked yet. Do I need to check the translation or give some suggestion? It seems this translation is done.

2022-11-22 14:50 UTC, Lenclove reviewed
Hi, I am very glad to review these tranlation. Could you please give me some advice for these changes?

2022-11-22 14:50 UTC, Lenclove commented on docs/zh/docs/async.md
> +使用 **FastAPI**，您可以利用 Web 开发中常见的并发机制（NodeJS 的主要吸引力）。
使用 **FastAPI**，您可以利用 Web 开发中常见的并发机制的优势（NodeJS 的主要吸引力）。

2022-11-22 14:50 UTC, Lenclove commented on docs/zh/docs/async.md
> +所有这些都是 FastAPI（通过 Starlette）的动力，也是它拥有如此令人印象深刻的性能的原因。
所有这些使得FastAPI（通过 Starlette）如此强大，也是它拥有如此令人印象深刻的性能的原因。

2022-11-22 14:50 UTC, Lenclove commented on docs/zh/docs/async.md
> +如果您使用过另一个不以上述方式工作的异步框架，并且您习惯于用普通的 `def` 定义普通的仅计算路径操作函数，以获得微小的性能增益（大约100纳秒），请注意，在 FastAPI 中，效果将完全相反。在这些情况下，最好使用 `async def`，除非路径操作函数内使用执行阻塞 <abbr title="输入/输出：磁盘读写，网络通讯.">I/O</abbr> 的代码。
如果您使用过另一个不以上述方式工作的异步框架，并且您习惯于用普通的 `def` 定义普通的仅计算路径操作函数，以获得微小的性能增益（大约100纳秒），请注意，在 FastAPI 中，效果将完全相反。在这些情况下，最好使用 `async def`，除非*路径操作函数*内使用执行阻塞 <abbr title="输入/输出：磁盘读写，网络通讯.">I/O</abbr> 的代码。

2022-11-22 14:59 UTC, mkdir700 commented
> 
👍  very nice, you can try use this: 

![](https://cdn.z2blog.com/utools/pic/1669129128214.png)

2022-11-22 15:13 UTC, mkdir700 commented on docs/zh/docs/async.md
> +如果您使用过另一个不以上述方式工作的异步框架，并且您习惯于用普通的 `def` 定义普通的仅计算路径操作函数，以获得微小的性能增益（大约100纳秒），请注意，在 FastAPI 中，效果将完全相反。在这些情况下，最好使用 `async def`，除非路径操作函数内使用执行阻塞 <abbr title="输入/输出：磁盘读写，网络通讯.">I/O</abbr> 的代码。
Sorry bro, I didn't find the difference between the two.

`<abbr title="输入/输出：磁盘读写，网络通讯.">I/O</abbr>` ，This sentence is needed.

<img width="702" alt="image" src="https://user-images.githubusercontent.com/56359329/203350236-b069af17-3aaf-4755-8bdc-cb331e713683.png">

2022-11-22 15:15 UTC, Lenclove requested changes
Improve Chinese translation of async.md

2022-11-22 15:21 UTC, mkdir700 commented
> 

Or give suggestions instead of comments.

<img width="803" alt="image" src="https://user-images.githubusercontent.com/56359329/203351907-5d287697-57d9-4fe5-8a41-da8c987e5ebd.png">

2022-11-22 15:21 UTC, Jedore commented
@Lenclove  You could try following steps, then suggested changes will like https://github.com/tiangolo/fastapi/pull/5591#discussion_r1016301828
<img width="655" alt="image" src="https://user-images.githubusercontent.com/17944025/203350985-035108e9-0c46-44ff-aa66-e4a00558c244.png">
<img width="688" alt="image" src="https://user-images.githubusercontent.com/17944025/203351357-df4cd8d5-1fd3-4023-bad5-d05c91caf6a4.png">

2022-11-22 15:29 UTC, Lenclove commented
> @Lenclove You could try following steps, then suggested changes will like [#5591 (comment)](https://github.com/tiangolo/fastapi/pull/5591#discussion_r1016301828) <img alt="image" width="655" src="https://user-images.githubusercontent.com/17944025/203350985-035108e9-0c46-44ff-aa66-e4a00558c244.png"> <img alt="image" width="688" src="https://user-images.githubusercontent.com/17944025/203351357-df4cd8d5-1fd3-4023-bad5-d05c91caf6a4.png">

Yes. It's awesome! I have experienced these operations which are very good.

2022-11-26 05:52 UTC, Lenclove approved these changes
Hi, I think it's OK to merge.

2022-12-15 04:33 UTC, Lenclove commented
It seems that `coverage` build steps interrupt this pull request. Could we solve it?

2023-06-26 22:53 UTC, tiangolo commented
📝 Docs preview for commit 1ad2e171f6d3cc19294772ce2a6bad76b158571b at: https://649a16c47e9b761214ba4bcd--fastapi.netlify.app

2023-07-10 11:41 UTC, wdh99 commented
`docs/zh/docs/async.md` 文件已经不存在了

2023-07-16 04:40 UTC, wdh99 requested changes

2023-09-04 20:36 UTC, xzmeng approved these changes
LGTM

2023-09-05 00:25 UTC, tiangolo commented
📝 Docs preview for commit ce7c520f356e3e7bf87f3007c2aa15e513031da6 at: https://c3d2ae96.fastapitiangolo.pages.dev

2023-09-27 20:47 UTC, tiangolo commented
Thank you @mkdir700! 🙇 

And thanks for the reviews @Jedore, @Lenclove, @xzmeng, @wdh99 🍰

2023-09-27 20:47 UTC, merged