:globe_with_meridians: Add Portuguese translation for deployment/docker.md
fastapi/fastapi pull request #5663
Opened 2022-11-19 21:12 UTC by ayr-ton

2022-11-22 12:38 UTC, guites commented on docs/pt/docs/deployment/docker.md
> +E você normalmente instalaria essas dependências de pacote com `pip`, por exemplo:
this line seems duplicated?

2022-11-22 13:44 UTC, ayr-ton commented on docs/pt/docs/deployment/docker.md
> +E você normalmente instalaria essas dependências de pacote com `pip`, por exemplo:
Fixed, thank you

2022-11-22 13:50 UTC, guites requested changes
Great translation!

2022-11-22 13:50 UTC, guites commented on docs/pt/docs/deployment/docker.md
> +    Eu vou mostrar um exemplo usando Poetry mais abaixo em uma seção abaixo. 👇
We could remove the duplicated "abaixo", and keep the "later" (depois) used in the en docs.

>Eu vou mostrar um exemplo usando Poetry depois em uma seção mais abaixo

2022-11-22 13:50 UTC, guites commented on docs/pt/docs/deployment/docker.md
> +def read_item(item_id: int, q: Optional[str] = None):
the en docs have

```
def read_item(item_id: int, q: Union[str, None] = None):
```

for that line

2022-11-22 13:50 UTC, guites commented on docs/pt/docs/deployment/docker.md
> +Dockers e ferramentas similares também usam um **cache interno** ao construir a imagem, se um arquivo não mudou desde a última vez que a imagem do contêiner foi construída, então ele irá **reutilizar
Dockers -> Docker

2022-11-22 13:50 UTC, guites commented on docs/pt/docs/deployment/docker.md
> +Somente evitar a cópia de arquivos não melhora as coisas muito, mas porque ele usou o cache para esse passo, ele pode **usar o cache para o próximo passo**. Por exemplo, ele pode usar o cache para a
nitpick: não melhora muito as coisas

2022-11-22 13:50 UTC, guites commented on docs/pt/docs/deployment/docker.md
> +* Build your FastAPI image:
Intruder line!

2022-11-22 13:50 UTC, guites commented on docs/pt/docs/deployment/docker.md
> +Você verá a documentação interativa automática de API (fornecida pelo <a href="https://github.com/swagger-api/swagger-ui" class="external-link" target="_blank">Swagger UI</a>):
I would change "de" to "da", as the "automatic interactive API documentation" refers to your specific API, not a generic idea of API?

2022-11-22 13:50 UTC, guites commented on docs/pt/docs/deployment/docker.md
> +Você pode estar implantando em um **único servidor** (não em um cluster) com o **Docker Compose**, então você não teria uma maneira fácil de gerenciar a replicação de contêineres (com o Docker Compos
The original goes

> while preserving the shared network and load balancing.

So I believe it's meant to be

>  enquanto preserva a rede compartilhada e o \*\*balanceamento de carga\*\*.

2022-11-22 13:50 UTC, guites commented on docs/pt/docs/deployment/docker.md
> +Se sua aplicação for **simples**, isso provavelmente **não será um problema**, e você pode não precisar especificar limites de memória rígidos. Mas se você estiver **usando muito memória** (por exemp
Any reason to use `muito` e `quanto` when refering to memory? (masculine instead of feminine)

2022-11-22 13:50 UTC, guites commented on docs/pt/docs/deployment/docker.md
> +If you use <a href="https://python-poetry.org/" class="external-link" target="_blank">Poetry</a> to manage your project's dependencies, you could use Docker multi-stage building:
another en intruder

2022-11-22 14:15 UTC, ayr-ton commented
@guites Thank you for your time reviewing! :smile:

2022-11-23 10:40 UTC, guites approved these changes
I believe the author fixed all points except for a few nitpicks, which is ok.

2022-11-23 17:32 UTC, izaguerreiro approved these changes

2022-11-23 19:01 UTC, ayr-ton commented
Thanks for your time reviewing! Working in @izaguerreiro suggestions and will let you know once is ready.

2022-11-23 23:40 UTC, ayr-ton commented on docs/pt/docs/deployment/docker.md
> +Usando contêineres Linux tem diversas vantagens incluindo **segurança**, **replicabilidade**, **simplicidade**, entre outras.
I will take the second one.

2022-11-24 10:30 UTC, ayr-ton commented
Ready

2022-11-24 18:11 UTC, ayr-ton commented
Missed the nitpicks. 
Just fixed them, @guites o/
Thanks again

2022-11-25 03:56 UTC, ayr-ton commented
The PR #5680 seems to fix the libffi error that is breaking the build.

2022-11-27 14:04 UTC, tiangolo commented
Awesome, thank you! :bow: 

And thanks a lot for the reviews @izaguerreiro and @guites :coffee: :cake:

2022-11-27 14:13 UTC, merged