:globe_with_meridians: Add Russian translation for docs/ru/docs/fastapi-people.md
fastapi/fastapi pull request #5665
Opened 2022-11-20 11:49 UTC by Xewus

It was in PR [#4909](https://github.com/tiangolo/fastapi/pull/4909), but Sebastian asked to split that pages.

And besides, the page itself has been changed since then.

Checked locally (Python 3.10 / Chrome).

2023-01-08 12:27 UTC, Kirilex requested changes

2023-01-08 12:27 UTC, Kirilex commented on docs/ru/docs/help-fastapi.md
> +Вы можете подписаться на (редкую) [новостную рассылку **FastAPI и его друзья**](/newsletter/){.internal-link target=_blank} и быть в курсе о:
Может быть можно удалить лишние скобки.

2023-01-08 12:27 UTC, Kirilex commented on docs/ru/docs/help-fastapi.md
> +Сделав это, Вы будете получать уведомления (на вашу электронную почту) каждый раз, когда появится новый релиз (новая версия) **FastAPI** с исправлениями ошибок и новыми возможностями.
Тут тоже про скобки.

2023-01-08 12:27 UTC, Kirilex commented on docs/ru/docs/help-fastapi.md
> +* Если на Вас нахлынуло великодушие, то можете попытаться **создать похожий пример** самостоятельно, основываясь только на описании проблемы. Но имейте в виду, что это может занять много времени и во
"возможно" - обернуть в запятые.

2023-01-08 12:27 UTC, Kirilex commented on docs/ru/docs/help-fastapi.md
> +* После того, как Вы поняли вопрос, Вы можете дать **ответ**.
"После того" - запятая не нужна.

2023-01-08 12:27 UTC, Kirilex commented on docs/ru/docs/help-fastapi.md
> +И повторюсь, постаратесь быть доброжелательным. 🤗
"пастаратесь" - пропущена "й".

2023-01-08 12:27 UTC, Kirilex commented on docs/ru/docs/help-fastapi.md
> +* Также есть вероятность, что пул-реквест не актуален, так как проблему возможно решить **другим путём**. В таком случае Вы может указать на этот факт.
"может" - нужно добавить "е".

2023-01-08 12:27 UTC, Kirilex commented on docs/ru/docs/help-fastapi.md
> +* Затем используя **комментарий** расскажите, что Вы сделали проверку, тогда я буду знать, что Вы действительно проверили код.
"используя комментарий" - обернуть в запятые.

2023-01-08 12:27 UTC, Kirilex commented on docs/ru/docs/help-fastapi.md
> +Существует также <a href="https://gitter.im/tiangolo/fastapi" class="external-link" target="_blank">чат в Gitter</a>, но, поскольку в нем нет каналов и расширенных функций, общение в нём сложнее, пот
после "но" запятая не нужна.

2023-01-08 12:27 UTC, Kirilex commented on docs/ru/docs/help-fastapi.md
> +Вы также можете оказать финансовую поддержку (мне) посредством <a href="https://github.com/sponsors/tiangolo" class="external-link" target="_blank">спонсорства через GitHub</a>.
тоже про скобки.

2023-01-14 13:25 UTC, personage-hub approved these changes

2023-01-14 16:35 UTC, Kirilex commented
There is an extra page "contributing.md".

2023-01-15 09:14 UTC, Xewus commented
> There is an extra page "contributing.md".

Yes, I had seen it,
It is not exist in my branch [Xewus:master](https://github.com/Xewus/fastapi).

I tried to change this through my repo and right here too.
Sorry, but I don't have access to this PR anymore.

I hope senior @triangolo will merge it as is or delete unnecessary files.

2023-01-16 09:40 UTC, Kirilex approved these changes

2023-01-16 09:40 UTC, Kirilex commented on docs/ru/docs/contributing.md
> +Чтобы он сортировал их правильно, необходимо, чтобы FastAPI был установлен локально в Вашей среде, с помощью команды из разделе выше, использующей флаг `-e`.
> Чтобы он сортировал их правильно, необходимо, чтобы

Лучше бы без повторяющихся слов.

2023-01-16 09:40 UTC, Kirilex commented on docs/ru/docs/contributing.md
> +Помощь с переводами ценится КРАЙНЕ ВЫСОКО! И переводы не  могут быть сделаны без помощи сообщества. 🌎 🚀
>  КРАЙНЕ

"чрезвычайно", как вариант

2023-02-07 13:28 UTC, closed without merging