#1892 Add Turkish translate for docs/tr/docs/tutorial/first_steps.md
fastapi/fastapi pull request #5691
Opened 2022-11-26 12:13 UTC by Kadermiyanyedi

I translated tutorial/first_steps.md to Turkish.

Main issue: https://github.com/tiangolo/fastapi/issues/1892

2022-11-26 19:59 UTC, BilalAlpaslan requested changes

2022-11-27 10:02 UTC, Kadermiyanyedi commented on docs/tr/docs/tutorial/first_steps.md
> +OpenAPI, API'niz için bir API şeması tanımlar. Ve bu şema, JSON veri şemaları standardı olan **JSON Şema** kullanılarak API'niz tarafından gönderilen ve alınan verilerin tanımlarını (veya "şemalarını
Buna gerek yok bence^^

2022-11-27 10:06 UTC, Kadermiyanyedi commented
@BilalAlpaslan  güncellemeleri gönderdim. Tekrar review edebilirsiniz :)

2022-11-27 18:13 UTC, BilalAlpaslan approved these changes

2022-11-28 09:55 UTC, onuralpszr approved these changes
Lgtm again (i did my review originally in previous pr)

2022-12-04 20:55 UTC, onuralpszr commented
friendly ping  @tiangolo maybe a merge time  :)

2023-01-10 12:35 UTC, tiangolo commented
Awesome, thank you @Kadermiyanyedi! :cake: :clap: 

And thanks for the reviews @onuralpszr and @BilalAlpaslan :bow:

2023-01-10 12:38 UTC, merged