Add Chinese translation for docs/advanced/settings.md
fastapi/fastapi pull request #5830
Opened 2023-01-03 05:52 UTC by Jasonw372

I want to add a translation for the Chinese document

2023-01-09 15:37 UTC, Jedore commented on docs/zh/docs/advanced/settings.md
> +如果你已经知道什么是 “环境变量” 以及如何使用它们，请直接跳到下面的章节。
```suggestion
    如果你已经知道什么是 “环境变量” 以及如何使用它们，请直接跳到下面的章节。
```

2023-01-09 16:06 UTC, Jedore requested changes
Good work. Just some little suggestions.

2023-01-09 16:06 UTC, Jedore commented on docs/zh/docs/advanced/settings.md
> +但每次我们都会这样做。
```suggestion
但每次我们都会这样做:
```

2023-01-09 16:10 UTC, Jedore commented on docs/zh/docs/advanced/settings.md
> +如果你已经知道什么是 “环境变量” 以及如何使用它们，请直接跳到下面的章节。
This sentence should be contained by `tip`.

2023-01-10 11:42 UTC, Jasonw372 commented
Thank you @Jedore

2023-02-10 09:20 UTC, Jasonw372 commented
Please tell me when this translation will be updated to the official website. There are still many documents on the official website that have not been translated into Chinese. Thank you!

2023-02-10 13:37 UTC, Jedore commented
> Please tell me when this translation will be updated to the official website. There are still many documents on the official website that have not been translated into Chinese. Thank you!

At least 2 reviewers review your PR.@Jasonw372

2023-06-26 23:40 UTC, tiangolo commented
It seems this was translated at some point in another PR. So I'll close this one, but thanks for the effort! ☕

2023-06-26 23:40 UTC, closed without merging