Removed redundant update method for adding key-value pair in dict.
fastapi/fastapi pull request #5852
Opened 2023-01-07 18:10 UTC by subedikushal

It is simpler to do it directly rather than via update method. This also eliminates the overhead of constructing another dictionary and calling a method, so should slightly improve performance. [ Read at Sourcery]

2023-01-07 18:23 UTC, PabloEmidio commented on docs_src/body_multiple_params/tutorial001.py
> +        results.["q"]= q
Remove `.` before `[`

2023-01-07 20:36 UTC, iudeen requested changes
Please ensure you verify basic syntax before marking PRs as ready for review :)

2023-01-07 20:36 UTC, iudeen commented on docs_src/body_multiple_params/tutorial001.py
> +        results.["q"]= q
```suggestion
        results["q"]= q
```

2023-01-17 13:20 UTC, r0b2g1t approved these changes

2023-01-18 01:19 UTC, PabloEmidio approved these changes

2023-01-18 23:32 UTC, Ryandaydev approved these changes
All tests pass.

2025-07-09 05:56 UTC, YuriiMotov commented
@subedikushal, thanks for your interest in FastAPI!

This PR changes only one occurrence, but there are many other similar (search for `.update(` in `docs_src` gives me 139 results in 112 files).

If we want to correct this, we need to do it consistently across the whole code base.
But, I'm not sure we need it. This is just code examples in docs.

2025-12-02 08:12 UTC, tiangolo commented
Thanks for the interest, I think it's fine as it is, so I'll pass on this one. :coffee:

2025-12-02 08:12 UTC, closed without merging