Add Russian translation for docs/ru/docs/contributing.md
fastapi/fastapi pull request #5870
Opened 2023-01-10 11:44 UTC by Xewus

2023-01-10 11:54 UTC, Xewus commented
Added translation of the specified page into Russian.

Checked locally (Python 3.10 / Chrome/Mozilla) and the test script from this page.

2023-01-14 13:24 UTC, personage-hub approved these changes

2023-01-16 11:58 UTC, da-maltsev approved these changes
Good translation, everything is OK. Спасибо за перевод!

2023-01-23 04:41 UTC, bnzone approved these changes

2023-01-23 13:00 UTC, simatheone commented on docs/ru/docs/contributing.md
> +Прежде всего, убедитесь, что Вы настроили свою окружение, как описано выше, для установки всех зависимостей.
Заметил опечатку: "... `своё` окружение"

2023-01-23 13:00 UTC, simatheone commented on docs/ru/docs/contributing.md
> +По по умолчанию Uvicorn будет использовать порт `8000` и не будет конфликтовать с сайтом документации, использующим порт `8008`.
Повтор "По по ... "

2023-01-23 13:04 UTC, simatheone commented on docs/ru/docs/contributing.md
> +!!! Подсказка
Здесь (и не только) необходимо оставить слово `tip` и рядом в кавычках добавить перевод. Иначе подсказка не будет обрамлена в зеленую рамку с огоньком, как в исходной документации.

2023-01-23 13:49 UTC, simatheone commented on docs/ru/docs/contributing.md
> +!!! Подсказка
!!! tip "Подсказка"

2023-01-23 13:49 UTC, simatheone commented on docs/ru/docs/contributing.md
> +!!! Подсказка
!!! tip "Подсказка"

2023-01-23 13:49 UTC, simatheone commented on docs/ru/docs/contributing.md
> +!!! Подсказка
!!! tip "Подсказка"

2023-01-23 13:50 UTC, simatheone commented on docs/ru/docs/contributing.md
> +!!! Подсказка
!!! tip "Подсказка"

2023-01-23 13:50 UTC, simatheone commented on docs/ru/docs/contributing.md
> +!!! Подсказка
!!! tip "Подсказка"

2023-01-23 13:53 UTC, Xewus commented on docs/ru/docs/contributing.md
> +!!! Подсказка
И действительно. Спасибо.

2023-01-23 15:11 UTC, bnzone requested changes

2023-01-23 15:11 UTC, bnzone commented on docs/ru/docs/contributing.md
> +Эта команда создаст директорию `./htmlcov/`, в которой будет файл `./htmlcov/index.html`. Открыв его в Вашем браузере, Вы можете в интерактивном режиме изучить все ли части кода охвачены тестами.
Hi 👋🏻
Нашел недостающую запятую.
```suggestion
Эта команда создаст директорию `./htmlcov/`, в которой будет файл `./htmlcov/index.html`. Открыв его в Вашем браузере, Вы можете в интерактивном режиме изучить, все ли части кода охвачены тестами.
```

2023-01-23 18:28 UTC, bnzone approved these changes

2023-01-23 20:12 UTC, simatheone commented on docs/ru/docs/contributing.md
> +    Ознакомьтесь с документацией о <a href="https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews" class="external-link" target="_blank">добавлении
```suggestion
    Ознакомьтесь с документацией о <a href="https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews" class="external-link" target="_blank">добавлении отзыва к пул-реквесту</a>, чтобы утвердить его или запросить изменения.
```

2023-01-23 20:19 UTC, simatheone commented on docs/ru/docs/contributing.md
> +Если при запуске скрипта `./scripts/docs.py live` Вы получаете сообщение об ошибке, что язык не поддерживается, что-то вроде
```suggestion
Если при запуске скрипта `./scripts/docs.py live` Вы получаете сообщение об ошибке, что язык не поддерживается, что-то вроде:
```

2023-01-24 07:00 UTC, simatheone approved these changes

2023-02-03 11:12 UTC, dimastbk approved these changes

2023-02-03 11:12 UTC, dimastbk commented on docs/ru/docs/contributing.md
> +Если Вы создаёте Python файл, который импортирует и использует FastAPI,а затем запускаете его интерпретатором Python из Вашего локального окружения, то он будет использовать код из локального FastAPI
Пробел после `FastAPI,`.

2023-02-07 13:04 UTC, tiangolo commented
Awesome, thank you for your contribution! 🙇🍰

And thanks for the reviews @bnzone, @dimastbk, @da-maltsev, @personage-hub, @simatheone. :coffee: :tada:

2023-02-07 13:04 UTC, merged