add __str__ method to HTTPException
fastapi/fastapi pull request #5879
Opened 2023-01-12 13:21 UTC by ebottos94

As mentioned in Iusse #5878 there's a bug in HTTPException's string representation, it seems that \__repr__ method in starlette.exceptions.HTTPException doesn't works correctly without explicit call \__repr__ method. To avoid this I've implemented a \__str__ method in fastapi.exceptions.HTTPException

### Current situation :

![image](https://user-images.githubusercontent.com/100039558/212074854-9b9b6413-4516-48ea-a734-f535a230a594.png)

### After my commit : 

![image](https://user-images.githubusercontent.com/100039558/212075063-bff91996-5478-4026-9206-9cb612906a36.png)

2023-01-12 14:36 UTC, odiseo0 requested changes
You should add tests to pass the coverage requirement.

2023-01-12 15:22 UTC, ebottos94 commented
> You should add tests to pass the coverage requirement.

Thank you, what kind of tests i have to add to pass coverage requirement?

2023-01-12 23:07 UTC, ebottos94 commented
> You should add tests to pass the coverage requirement.

Thank you @odiseo0, I've add test and change string representation as you suggested.

2023-01-13 08:34 UTC, yezz123 approved these changes
LGTM 🚀

2023-01-13 14:40 UTC, odiseo0 approved these changes

2023-01-13 19:01 UTC, iudeen commented
Does it make sense to add this Starlette itself?🤔 Just wondering

2023-01-17 13:04 UTC, r0b2g1t approved these changes
That looks good for me.

2023-02-04 12:33 UTC, LorhanSohaky approved these changes

2023-03-13 11:49 UTC, Harry-Lees commented on fastapi/exceptions.py
> +        return f"HTTPException(status_code: {self.status_code}, detail: {self.detail})"
Should this use `self.__class__.__name__` like in starlette (https://github.com/encode/starlette/blob/ada845cc8ad0b531b16749b9bf3a57114c60c679/starlette/exceptions.py#L22)

I haven't actually pulled this PR, but I think if I subclassed this class I'd end up with mismatching `__repr__` and `__str__`

```python
class CustomHTTPException(HTTPException):
    pass

exc = CustomHTTPException(status_code=400, detail="something went wrong")

print(exc)
#> HTTPException(status_code=400, detail='something went wrong')

print(repr(exc))
#> CustomHTTPException(status_code=400, detail='Something went wrong')
```

2023-06-09 14:45 UTC, Kyle-sandeman-mrdfood commented
Honestly you could just do `__str__ = __repr__` (in definition, not patched like below)
```python
>>> from fastapi.exceptions import HTTPException
>>> h = HTTPException(status_code=200)
>>> str(h), repr(h)
('', "HTTPException(status_code=200, detail='OK')")
>>> HTTPException.__str__ = HTTPException.__repr__
>>> str(h), repr(h)
("HTTPException(status_code=200, detail='OK')", "HTTPException(status_code=200, detail='OK')")
>>> class Custom(HTTPException):
...   pass
... 
>>> c = Custom(status_code=201)
>>> str(c), repr(c)
("Custom(status_code=201, detail='Created')", "Custom(status_code=201, detail='Created')")
```

2023-06-11 17:52 UTC, Kludex commented
We'll implement this in Starlette.

2023-07-18 19:55 UTC, Kludex commented
https://github.com/encode/starlette/pull/2181 was merged.

2023-09-27 21:26 UTC, tiangolo commented
Thanks @ebottos94! 🍰 

And thanks everyone for the discussion. As @Kludex points out, as this is now in Starlette, I'll close this one here. But thanks for the effort! ☕

2023-09-27 21:26 UTC, closed without merging