🌐 Add Russian translation for `docs/ru/docs/tutorial/cookie-params.md`
fastapi/fastapi pull request #5890
Opened 2023-01-16 23:08 UTC by bnzone

## Pull Request Description
This change adds Russian translation for the `docs/ru/docs/tutorial/cookie-params.md` page.

### Changes In This Pull Request
- Created a new file `cookie-params.md` for the translation
- Updated `mkdocs.yml` to contain the newly added file

2023-01-23 09:56 UTC, Xewus requested changes
Добро пожаловать в ряды.

Первые страницы переводил примерно также, но позволю себе ремарку, если Вы планируете и дальше этим заниматься.

Дайте себе больше свободы, не стоит придерживаться буквального значения и порядка слов из оригинала.

Кто знает английский - прочитает оригинал сам. Цель же перевода - донести смысл именно до тех, у кого с этим трудности.

2023-01-23 09:56 UTC, Xewus commented on docs/ru/docs/tutorial/cookie-params.md
> +    `Cookie` - это "сестринский" класс `Path` и `Query`. Он также наследуется от общего класса `Param`.
> это "сестринский" класс

Более по-русски: "это класс родственный".

2023-01-23 09:56 UTC, Xewus commented on docs/ru/docs/tutorial/cookie-params.md
> +    Но помните, что когда вы импортируете `Query`, `Path`, `Cookie` и другие из fastapi, это функции, которые возвращают специальные классы.
> Но помните, что когда вы импортируете

Так как будете вносить изменения, здесь "что" можно убрать. В целом оно не нарушает правил, но и нагрузки не несёт.

> и другие из fastapi, это функции,

Вместо "другие" лучше "другое", нечто неопределённое, но не факт,что во множественном числе.
Вокруг `fastapi` утеряны обратные кавычки.

2023-01-23 15:37 UTC, bnzone commented on docs/ru/docs/tutorial/cookie-params.md
> +    Но помните, что когда вы импортируете `Query`, `Path`, `Cookie` и другие из fastapi, это функции, которые возвращают специальные классы.
Доброго времени суток! 👋🏻
Спасибо за ревью. Я внес изменeния в текст, основываясь на указанных ремарках.

2023-01-23 18:33 UTC, Xewus approved these changes

2023-01-23 18:33 UTC, Xewus commented on docs/ru/docs/tutorial/cookie-params.md
> +!!! info
> !!! info 

Не желаете перевести?

2023-01-23 18:33 UTC, Xewus commented on docs/ru/docs/tutorial/cookie-params.md
> +Объявляйте cookies с помощью `Cookie`, используя тот же общий шаблон, что и `Query` и `Path`.
> и `Query` и `Path`.

Перечисление требует запятую.

2023-01-23 18:46 UTC, bnzone commented on docs/ru/docs/tutorial/cookie-params.md
> +!!! info
>  !!! info To declare cookies


Предлагаете изменить, чтобы было, например,  `!!! info Дополнительная информация` ?

2023-01-23 19:03 UTC, Xewus commented on docs/ru/docs/tutorial/cookie-params.md
> +!!! info
Да но не настаиваю. Предыдущие переводы всё равно вразнобой и возможно кто-то выкажет пожелание причесать их все под один стандарт.
Мне кажется, что лучше переводить весь доступный текст.

2023-01-23 19:49 UTC, simatheone commented on docs/ru/docs/tutorial/cookie-params.md
> +!!! info
@Xewus, я думаю в эти переводы можно сделать PR и обновить, чтобы везде было одинаково.

2023-01-23 21:05 UTC, simatheone approved these changes

2023-02-03 10:31 UTC, dimastbk commented on docs/ru/docs/tutorial/cookie-params.md
> +    Но помните, что когда вы импортируете `Query`, `Path`, `Cookie` и другое из `fastapi`, это функции, которые возвращают специальные классы.
> Но помните, что когда вы импортируете `Query`, `Path`, `Cookie` и другие "классы" из `fastapi`, вы импортируете функции, которые возвращают специальные классы.

> Но помните, что `Query`, `Path`, `Cookie` и другие "классы" , которые вы импортуете из `fastapi`, это функции, которые возвращают специальные классы.

Мне кажется, какой-нибудь из этих вариантов выглядит понятнее.

2023-02-03 10:36 UTC, dimastbk commented on docs/ru/docs/tutorial/cookie-params.md
> +    Но помните, что когда вы импортируете `Query`, `Path`, `Cookie` и другое из `fastapi`, это функции, которые возвращают специальные классы.
> Помните, что когда вы импортируете `Query`, `Path` и другое из `fastapi`, это фактически функции, которые возвращают специальные классы.

https://github.com/tiangolo/fastapi/pull/5898/files#diff-3a49da8aebe0f62caea883524669e92472a14dc769ee3b8b43f5d41766ad7a7dR49

Или вот в соседнем PR такой вариант. Имхо, стоит выбрать какой-то один на все страницы.

2023-02-07 14:06 UTC, bnzone commented on docs/ru/docs/tutorial/cookie-params.md
> +    Но помните, что когда вы импортируете `Query`, `Path`, `Cookie` и другое из `fastapi`, это функции, которые возвращают специальные классы.
Хорошая идея. 
Обновил как в https://github.com/tiangolo/fastapi/pull/5898/files#diff-3a49da8aebe0f62caea883524669e92472a14dc769ee3b8b43f5d41766ad7a7dR49

2023-02-07 14:18 UTC, simatheone approved these changes

2023-02-07 18:38 UTC, Xewus approved these changes

2023-02-09 19:27 UTC, tiangolo commented
Awesome, thank you @bnzone! :cake: 

And thanks for the reviews @dimastbk, @simatheone, @Xewus :coffee: :cookie:

2023-02-09 19:27 UTC, merged