🌐Add Russian translation for `docs/ru/docs/tutorial/body-fields.md`
fastapi/fastapi pull request #5898
Opened 2023-01-18 16:30 UTC by simatheone

### Pull Request Description
This change adds Russian translation for the `docs/ru/docs/tutorial/body-fields.md` page.

### Changes In This Pull Request
- Created a new file `body-fields.md` for the translation
- Updated `mkdocs.yml` to contain the newly added file

2023-01-21 12:33 UTC, Wilidon commented
Привет. 
Заметил опечатку на 58 строке. В конце предложения 

> когда будете изучать как задвать examples.

пропущена буква и не переведено слово

2023-01-23 07:54 UTC, simatheone commented
@Wilidon, спасибо, что заметил пропущенную букву (fixed). `examples` я умышленно не переводил.

В исходном виде предложение выглядит так: 
**"You will learn more about adding extra information later in the docs, when learning to declare examples."**
Если полностью перевести предложение, то будет непонятно о каких "примерах" идет речь.

Про `examples`, о которых говорится в предложении, рассказывается далее в документации в разделе [Declare Request Example Data](https://fastapi.tiangolo.com/tutorial/schema-extra-example/#field-additional-arguments). Чтобы оставить у читающего мысль, что где-то дальше будет говориться об `examples` в контексте `Field`, я решил не переводить данное слово.

2023-01-23 10:28 UTC, Xewus commented
> Привет. Заметил опечатку на 58 строке. В конце предложения
> 
> > когда будете изучать как задвать examples.
> 
> пропущена буква и не переведено слово

Если вас удовлетворяет PR, то следует его утвердить (специальной кнопкой). Перевод не будет принят, пока его не подтвердят минимум 2 человека.

2023-01-23 11:51 UTC, Xewus requested changes

2023-01-23 11:51 UTC, Xewus commented on docs/ru/docs/tutorial/body-fields.md
> +!!! tip
> !!! tip

Подсказка

2023-01-23 11:51 UTC, Xewus commented on docs/ru/docs/tutorial/body-fields.md
> +    `Body` также непосредственно возвращает объекты подкласса `FieldInfo`. Есть и другие, их вы увидите позже, которые являются подклассами класса `Body`.
> И `Field` из Pydantic также возвращает экземпляр `FieldInfo`.
    `Body` также непосредственно возвращает объекты подкласса `FieldInfo`. 

Можно сократить.
И `Field` (из Pydantic), и   `Body` , оба  возвращают объекты подкласса `FieldInfo`. 

> Есть и другие, их вы увидите позже, которые являются подклассами класса `Body`.

У класса `Body` есть и другие подклассы, с которыми Вы ознакомитесь позже.

2023-01-23 11:51 UTC, Xewus commented on docs/ru/docs/tutorial/body-fields.md
> +Вы узнаете больше о добавлении дополнительной информации позже в документации, когда будете изучать как задавать examples.
> когда будете изучать как задавать examples.

Перед  "как" запятая.

Examples - примеры принимаемых данных.

2023-01-23 11:51 UTC, Xewus commented on docs/ru/docs/tutorial/body-fields.md
> +!!! warning
не переведено.

2023-01-23 11:51 UTC, Xewus commented on docs/ru/docs/tutorial/body-fields.md
> +    Дополнительные ключи, переданные в `Field`, также будут присутствовать в полученной схеме OpenAPI вашего приложения.
> в полученной схеме OpenAPI

"в созданной схеме", "в сгенерированной схеме" либо ещё проще "в схеме".

2023-01-23 11:51 UTC, Xewus commented on docs/ru/docs/tutorial/body-fields.md
> +Вы можете использовать `Field` из Pydantic, чтобы задавать дополнительную валидацию и метаданные для атрибутов модели.
> `Field`

Не претензия, но, коли документация рассчитана на новичков, возможно, стоит перед подобными определениями добавлять - класс, объект, подкласс, функция...

2023-01-23 12:52 UTC, simatheone commented on docs/ru/docs/tutorial/body-fields.md
> +    `Body` также непосредственно возвращает объекты подкласса `FieldInfo`. Есть и другие, их вы увидите позже, которые являются подклассами класса `Body`.
Согласен, так намного лучше

2023-01-23 12:55 UTC, simatheone commented on docs/ru/docs/tutorial/body-fields.md
> +Вы можете использовать `Field` из Pydantic, чтобы задавать дополнительную валидацию и метаданные для атрибутов модели.
Имеет смысл. Главное, чтобы при переводе других разделов случайно не написали, что `Field` - это класс. Иначе может возникнуть путаница.

2023-01-23 12:56 UTC, simatheone commented on docs/ru/docs/tutorial/body-fields.md
> +Вы узнаете больше о добавлении дополнительной информации позже в документации, когда будете изучать как задавать examples.
> Examples - примеры принимаемых данных.
Не совсем понял. Дать пояснение в скобках ?

2023-01-23 18:46 UTC, Xewus commented on docs/ru/docs/tutorial/body-fields.md
> +Вы узнаете больше о добавлении дополнительной информации позже в документации, когда будете изучать как задавать examples.
Это значение слова `examples` в данном контескте. Зачем его оставлять не переведённым? Это не какой-то особый термин.

`        example=[
            {
                'name':  'Пример названия',
                'time_spent':  '12:27:54.123456',
                'description':  'Пример описания'
            }
        ]
    )`

2023-01-23 18:55 UTC, Xewus commented on docs/ru/docs/tutorial/body-fields.md
> +Вы можете использовать `Field` из Pydantic, чтобы задавать дополнительную валидацию и метаданные для атрибутов модели.
Вот в том и загвоздка, что `Field` - это функция, а не класс.

2023-01-23 20:25 UTC, simatheone commented on docs/ru/docs/tutorial/body-fields.md
> +Вы можете использовать `Field` из Pydantic, чтобы задавать дополнительную валидацию и метаданные для атрибутов модели.
@Xewus, да, как раз в этом разделе документации об этом и говорится.

2023-01-23 20:59 UTC, bnzone approved these changes

2023-01-23 21:03 UTC, Xewus approved these changes

2023-01-26 12:23 UTC, Wilidon approved these changes

2023-02-07 13:33 UTC, merged