:globe_with_meridians:  Add Russian translation for docs/ru/docs/history-design-future.md
fastapi/fastapi pull request #5986
Opened 2023-02-10 19:41 UTC by Xewus

2023-02-14 10:24 UTC, dimastbk approved these changes

2023-03-06 09:16 UTC, nifadyev requested changes

2023-03-06 09:16 UTC, nifadyev commented on docs/ru/docs/history-design-future.md
> +В рамках этого я исследовал, проверял и использовал многие фреймворки.
Аналогично, слишком общая формулировка. Возможно, `В рамках работы над этими проектами ...` или `Мои обязанности включяли исследование, проверку и использование различных фреймворков`

2023-03-06 09:16 UTC, nifadyev commented on docs/ru/docs/history-design-future.md
> +Использование предшествующих альтернатив позволило изучить их, предлагаемые ими идеи и скомбинировать всё наилучшим образом, найденным мной и моими коллегами.
```suggestion
Благодаря опыту использования существующих альтернатив, мы с коллегами изучили их основные идеи и скомбинировали собранные знания лучшим образом
```

2023-03-06 09:16 UTC, nifadyev commented on docs/ru/docs/history-design-future.md
> +Одновреммено, я также предложил изменения в <a href="https://www.starlette.io/" class="external-link" target="_blank">**Starlette**</a>, ещё одну основу FastAPI.
```suggestion
В то же время, я принимал участие в разработке <a href="https://www.starlette.io/" class="external-link" target="_blank">**Starlette**</a>, который является одним из основных компонентов FastAPI.
```

2023-03-08 12:25 UTC, Xewus commented on docs/ru/docs/history-design-future.md
> +> Какова история этого проекта? Создаётся впечатление, что он явился из ниоткуда, и завоевал мир за несколько недель [...]
Это синонимы,.
А вот запятая в этой строке, кажется, лишняя.

2023-03-09 11:49 UTC, nifadyev requested changes

2023-03-09 11:49 UTC, nifadyev commented on docs/ru/docs/history-design-future.md
> +Что ж, вот неболшая часть истории проекта.
Опечатка
```suggestion
Что ж, вот небольшая часть истории проекта.
```

2023-03-09 11:49 UTC, nifadyev commented on docs/ru/docs/history-design-future.md
> +В течении нескольких лет я, возглавляя разнличные команды разработчиков, создавал довольно сложные API для машинного обучения, распределённых систем, асинхронных задач, баз данных NoSQL и т.д.
Опечатка
```suggestion
В течении нескольких лет я, возглавляя различные команды разработчиков, создавал довольно сложные API для машинного обучения, распределённых систем, асинхронных задач, баз данных NoSQL и т.д.
```

2023-03-09 11:49 UTC, nifadyev commented on docs/ru/docs/history-design-future.md
> +Я всячески избегал создания нового фреймворка в течение нескольких лет. Сначала я пытался собрать все нужные функции, которые ныне есть в **FastAPI**, используя множество различных фреймворков, плаги
Может заменить `функции` на `особенности`? Слово `функция` ассоциируется с `def` и т.п.

2023-03-09 11:49 UTC, nifadyev commented on docs/ru/docs/history-design-future.md
> +Но в какой-то момент не осталось другого выбора, кроме как создать что-то, что предоставляло бы все эти функции сразу. Взять самые лучшие идеи из предыдущих инструментов и, используя новые возможност
Аналогично про слово `функции`

2023-03-09 13:43 UTC, Xewus commented on docs/ru/docs/history-design-future.md
> +Я всячески избегал создания нового фреймворка в течение нескольких лет. Сначала я пытался собрать все нужные функции, которые ныне есть в **FastAPI**, используя множество различных фреймворков, плаги
Ох, помню, неоднозначный перевод "фич" обсуждался ещё при попытках перевода главной страницы.

"Особенности", как мне кажется, это нечто выделяющие. В данном же контексте, опять же, по моему мнению, лучше подойдёт "возможности".
Для литературной красоты - перестроил следующее предложение, чтоб уменьшить повторы одного слова.

2023-03-09 15:27 UTC, nifadyev requested changes

2023-03-09 15:27 UTC, nifadyev commented on docs/ru/docs/history-design-future.md
> +В течении нескольких лет я, возглавляя различные команды разработчиков, создавал довольно сложные API для машинного обучения, распределённых систем, асинхронных задач, баз данных NoSQL и т.д.
```suggestion
В течение нескольких лет я, возглавляя различные команды разработчиков, создавал довольно сложные API для машинного обучения, распределённых систем, асинхронных задач, баз данных NoSQL и т.д.
```

2023-03-09 16:57 UTC, nifadyev approved these changes
Отличная работа :fire:

2023-03-10 18:42 UTC, tiangolo commented
Great, thank you @Xewus! :tada:

And thanks for the reviews @dimastbk and @nifadyev :bow:

2023-03-10 18:42 UTC, merged