:globe_with_meridians:  Add Russian translation for docs/ru/docs/alternatives.md
fastapi/fastapi pull request #5994
Opened 2023-02-13 13:58 UTC by Xewus

2023-02-14 10:22 UTC, dimastbk commented on docs/ru/docs/alternatives.md
> +Другая немаловажная функция API - <abbr title="чтение и преобразование данных в объекты Python">разбор и анализ</abbr> данных из входящих запросов.
"разбор и анализ" - слово `парсинг` вполне используется в русском языке (см. поиск по google.books, например).

2023-02-14 10:22 UTC, dimastbk commented on docs/ru/docs/alternatives.md
> +В APIStar была система внедрения зависимостей, которая тоже требовала предварительную регистрацию компонентов, как и ранее описанные инструменты
```suggestion
В APIStar была система внедрения зависимостей, которая тоже требовала предварительную регистрацию компонентов, как и ранее описанные инструменты.
```

2023-02-14 10:22 UTC, dimastbk commented on docs/ru/docs/alternatives.md
> +Я не смог использовать его в полноценном проекте, так как в нём были проблемы с безопасными интеграциями, из-за которых я не мог вставить все функции, которые у меня были в полноценных генераторах пр
"были проблемы с безопасными интеграциями" - мне кажется, имеется ввиду что-то другое. Отсутствие интеграций защиты?

2023-02-14 11:43 UTC, Xewus commented on docs/ru/docs/alternatives.md
> +Другая немаловажная функция API - <abbr title="чтение и преобразование данных в объекты Python">разбор и анализ</abbr> данных из входящих запросов.
Да, но всё же развернул этот термин.
Мне "парсинг" встречается обычно в контексте сбора информации с сайтов. Технически - это тоже "разбор и анализ", но боюсь, что у неискушённого читателя (а вся документация довольно лояльна к новичкам) могут возникнуть затруднения.

2023-02-14 12:09 UTC, Xewus commented on docs/ru/docs/alternatives.md
> +Я не смог использовать его в полноценном проекте, так как в нём были проблемы с безопасными интеграциями, из-за которых я не мог вставить все функции, которые у меня были в полноценных генераторах пр
Тут надеюсь на помощь сообщества с понятным переводом.
Данный фреймворк с рассматриваемым функционалом существовал до осени 2018 года.
И вероятно проблема обозначена здесь: https://github.com/encode/apistar/issues/515?ysclid=le46pjmr37357939435

По-видимому имеется ввиду внедрение в схему OpenAPI всяких паролей и токенов для автоматической авторизации из Swagger UI. Это нынче просто работает в FastAPI  и я не могу оценить - почему были какие-то проблемы в то время.

Может быть можно написать - " проблемы авторизации используя UI"...

2023-02-14 12:15 UTC, Xewus commented on docs/ru/docs/alternatives.md
> +Я не смог использовать его в полноценном проекте, так как в нём были проблемы с безопасными интеграциями, из-за которых я не мог вставить все функции, которые у меня были в полноценных генераторах пр
Mr. @tiangolo, can you explain the described problem in more detail?

> I was never able to use it in a full project, as **it didn't have security integration**, so, I couldn't replace all the features I was having with the full-stack generators based on Flask-apispec. I had in my backlog of projects to create a pull request adding that functionality.

2023-02-14 12:49 UTC, abhint approved these changes

2023-03-17 19:29 UTC, dedkot01 commented on docs/ru/docs/alternatives.md
> +Это самый популярный Python-фреймворк и он пользуется доверием.
Это сложносочинённое предложение, даже при союзе `и` его части должны разделяться запятой:
`Это самый популярный Python-фреймворк, и он пользуется доверием.`

2023-03-17 19:38 UTC, dedkot01 commented on docs/ru/docs/alternatives.md
> +Flask часто используется и для приложений, которым не нужна база данных, управление пользователями или любая из множества функций, предварительно встроенных в Django.
Смущает `управление пользователями`. Может лучше `управление для пользователей`?

2023-03-18 06:46 UTC, Xewus commented on docs/ru/docs/alternatives.md
> +Flask часто используется и для приложений, которым не нужна база данных, управление пользователями или любая из множества функций, предварительно встроенных в Django.
В Django предустановлено создание пользователей, авторизации, раздача прав и прочие подобные штуки.
Пользователь не может этим управлять, значит это не для пользователя.
Некоторая часть этого функционала доступна в админке, но админ всё же не обычный пользователь и все доступные возможности - это установка ограничений на пользователей рангом ниже, то есть "управление ими".

2023-03-21 09:14 UTC, dedkot01 requested changes
Хороший перевод такой полезной страницы. Есть несколько правок, которые хотелось бы рассмотреть.

2023-03-21 09:14 UTC, dedkot01 commented on docs/ru/docs/alternatives.md
> +Я не смог использовать его в полноценном проекте, так как были проблемы со встраиванием <abbr title="Авторизация и соответствующие допуски к операциям пути (эндпоинтам)">функций безопасности</abbr>,
Лишняя запятая после функций безопасности:

Я не смог использовать его в полноценном проекте, так как были проблемы со встраиванием <abbr title="Авторизация и соответствующие допуски к операциям пути (эндпоинтам)">функций безопасности</abbr> в схему OpenAPI, из-за которых невозможно было встроить все функции, применяемые в генераторах проектов на основе Flask-apispec.

2023-03-21 12:44 UTC, Xewus commented on docs/ru/docs/alternatives.md
> +    Должна быть простая и лёгкая в использовании система перенаправления запросов.
Да, действительно неоднозначно.

2023-03-21 14:33 UTC, dedkot01 approved these changes
LGTM!

2023-04-13 18:11 UTC, tiangolo commented
Nice, thank you @Xewus! :cake: 

And thanks for the reviews @abhint, @dedkot01, and @dimastbk. :coffee: 

Just to confirm, @abhint, do you speak Russian? Just because the idea with translation reviews is to check that the translation is correct, so you need to speak the language to be able to review it. :nerd_face:

2023-04-13 18:12 UTC, merged