Updating the Deta deployment tutorial for compatibility with Deta Space
fastapi/fastapi pull request #6004
Opened 2023-02-15 19:32 UTC by mikBighne98

2023-02-15 20:46 UTC, mikBighne98 commented
WIP / draft

2023-02-19 01:53 UTC, Ryandaydev commented
Are there any tests associated with this PR?

2023-02-21 07:23 UTC, mikBighne98 commented
> Are there any tests associated with this PR?
@Ryandaydev, no. Just an update on how to install the FastAPI app on the Deta for compatibility with Space

2023-02-23 13:35 UTC, santigandolfo commented on docs/en/docs/deployment/deta.md
> +		print({"item_id": item_id})
```suggestion
    print({"item_id": item_id})
```

2023-02-23 15:56 UTC, abdelhai requested changes

2023-02-23 15:56 UTC, abdelhai commented on docs/en/docs/deployment/deta.md
> +    print({"item_id": item_id})
would remove

2023-05-08 12:31 UTC, tiangolo commented
Thanks @mikBighne98! :cake: 

I tweaked the docs a bit, fixed a couple of things, updated a couple others for consistency, and fixed the console outputs, this is ready! :rocket:

2023-05-08 12:32 UTC, merged

2023-05-08 12:43 UTC, mikBighne98 commented
Thank you for reviewing and merging the PR, @tiangolo :slightly_smiling_face: