Add Russian translation for `docs/ru/docs/tutorial/query-params-str-validations.md`
fastapi/fastapi pull request #9267
Opened 2023-03-17 18:42 UTC by dedkot01

2023-03-17 18:51 UTC, dedkot01 commented
Кто-нибудь знает, можно ли как-то в заголовках вводить скрытый для отображения текст? (или альтернативное название)

Мне не нравится, как формируется ссылка с привязкой к конкретному разделу страницы:
http://127.0.0.1:8008/ru/tutorial/query-params-str-validations/#_2

Хотелось бы вместо `#_2` оригинальное название `#additional-validation`:
https://fastapi.tiangolo.com/tutorial/query-params-str-validations/#additional-validation

2023-03-18 12:55 UTC, Xewus requested changes
Страница довольно большая, потому и замечаний не мало.

Также зачем-то удалены глаголы из заголовков разделов...

2023-03-18 12:55 UTC, Xewus commented on docs/ru/docs/tutorial/query-params-str-validations.md
> +Когда вам не требуется валидация или дополнительные метаданные для параметра запроса, вы можете сделать его `q` обязательным просто не указывая значения по умолчанию. Например:
> Когда вам не требуется валидация

Когда вам не требуется дополнительная валидация.

Потому что указанием типа уже будет вызвана валидация - может ли входящие значение быть указанного типа и будет конвертировано в него.
Конечно, под тип 'str' пройдут любые данные, так как обычно все входные данные - [байтовые] строки.

> вы можете сделать его `q` обязательным

вы можете сделать параметр `q` обязательным

2023-03-18 12:55 UTC, Xewus commented on docs/ru/docs/tutorial/query-params-str-validations.md
> +Например, для параметра запроса `q` в URL указано несколько значений. Вы можете обработать это следующим образом:
Например, query-параметр `q` может быть указан в URL несколько раз и если вы ожидаете такой формат запроса, то можете указать это следующим образом:

2023-03-18 12:55 UTC, Xewus commented on docs/ru/docs/tutorial/query-params-str-validations.md
> +Пример URL:
Затем, получив такой URL:

2023-03-18 12:55 UTC, Xewus commented on docs/ru/docs/tutorial/query-params-str-validations.md
> +вы бы получили в `q` несколько значений (`foo` и `bar`) в виде Python `list` внутри вашей *функции обработки пути*, в *параметре функции* `q`.
вы бы получили несколько значений (`foo` и `bar`), которые относятся к параметру `q`

2023-03-18 12:55 UTC, Xewus commented on docs/ru/docs/tutorial/query-params-str-validations.md
> +### Множество значений для параметра запроса / значения по умолчанию
- Параметр запроса со множеством значений по умолчанию
- Параметр запроса со множеством значений, которые могут иметь предустановки по умолчанию

2023-03-18 12:55 UTC, Xewus commented on docs/ru/docs/tutorial/query-params-str-validations.md
> +Вы также можете определить значение по умолчанию типа `list` на случай, если его не укажут:
Вы также можете указать тип `list` со списком значений по умолчанию на случай, если вам их не предоставят.

2023-03-18 12:55 UTC, Xewus commented on docs/ru/docs/tutorial/query-params-str-validations.md
> +Вы можете указать `title`:
Возможно, для таких случаев стоит указать перевод, например:

Вы можете указать название используя параметр `title`

2023-03-18 12:55 UTC, Xewus commented on docs/ru/docs/tutorial/query-params-str-validations.md
> +В рассмотренных примерах вы могли увидеть объявление правил валидации для строковых значений `str`.
"могли" лишнее, мы же их увидели.

Или можно  написать "показано".

2023-03-18 12:55 UTC, Xewus commented on docs/ru/docs/tutorial/query-params-str-validations.md
> +# Параметры запроса и валидация строк
В английском языке есть  отличающиеся термины `query` и  `request`, но на русский их переводят одинаково из-за чего может быть недопонимание.
У меня, например, с термином `запрос` вызывается ассоция с глобальным объектом запроса (`request`).
Возможно, здесь и ниже стоит как-то конкретизировать, типа, `query-параметры`.

2023-03-18 17:14 UTC, Xewus commented
> Кто-нибудь знает, можно ли как-то в заголовках вводить скрытый для отображения текст? (или альтернативное название)

Это?

# [Видимый заголовок](## "подсказка")

2023-03-19 13:38 UTC, dedkot01 commented
> > Кто-нибудь знает, можно ли как-то в заголовках вводить скрытый для отображения текст? (или альтернативное название)
> 
> Это?
> 
> # [Видимый заголовок](##)

Попробовал - не получилось. Получается что это просто определяем ссылку, но всё ещё не переопределяем имя (идентификатор) заголовка, которое бы хотелось, чтобы участвовало в ссылке.

2023-03-19 13:45 UTC, dedkot01 commented on docs/ru/docs/tutorial/query-params-str-validations.md
> +    `Union` в `Union[str, None]` предоставит вашему редактору кода более лучшую поддержку и поможет найти ошибки.
`вам` и `вашему` как-то повторяются. Может быть, убрать одно из этих слов?

`Union` в `Union[str, None]` позволит вашему редактору кода оказать лучшую поддержку и найти ошибки.
Или:
`Union` в `Union[str, None]` позволит редактору кода оказать вам лучшую поддержку и найти ошибки.

2023-03-19 13:51 UTC, dedkot01 commented on docs/ru/docs/tutorial/query-params-str-validations.md
> +    `Union[str, None]` предоставит вашему редактору кода более лучшую поддержку. Но это не то, на что обращает внимание FastAPI для определения необязательности параметра.
Предпочитаю, когда в тексте нет лишних слов😁

2023-03-19 14:08 UTC, dedkot01 commented on docs/ru/docs/tutorial/query-params-str-validations.md
> +* `fixedquery`: в точности содержит строку `fixedquery`.
Это ведь описание части регулярки, что именно не пройдёт?
Ссылка на regex101 пустая без примеров, не могу проверить что имелось ввиду.

2023-03-19 14:13 UTC, Xewus commented
> 

Как оказалось оно и не везде работает. В гуглохроме всплывает подсказка, в MS Edge нет.
Эта строка была с Markdown разметкой, без ссылок, на похоже при выводе в браузере меняется на HTML.

2023-03-19 14:15 UTC, Xewus commented on docs/ru/docs/tutorial/query-params-str-validations.md
> +    `Union` в `Union[str, None]` предоставит вашему редактору кода более лучшую поддержку и поможет найти ошибки.
Я за последнее. Всё-так текст обращается к конкретному читателю.

2023-03-19 14:32 UTC, dedkot01 commented on docs/ru/docs/tutorial/query-params-str-validations.md
> +    `Union[str, None]` предоставит вашему редактору кода более лучшую поддержку. Но это не то, на что обращает внимание FastAPI для определения необязательности параметра.
@Xewus касательно предложения "Но для FastAPI это не имеет значения.". Мне кажется, что тут читателя текст может сбить столку, так как нет уточнения, что это касается определения необязательности параметра. Ведь глобально, для FastAPI это определяет тип параметра (`Union[str, None]`) и получается, что это имеет значение.

2023-03-19 15:29 UTC, dedkot01 commented
Заметил, что вчера с выходом версии 0.95 была затронута [оригинальная страница документации](https://fastapi.tiangolo.com/tutorial/query-params-str-validations/#import-query-and-annotated), в которой часть объяснения вынесена в предыдущий раздел [Python Types Intro](https://fastapi.tiangolo.com/python-types/#type-hints-with-metadata-annotations).

Как в таком случае стоит поступить? 
1. Добавить нововведения в текущий PR, не касаясь страницы [Python Types Intro](https://fastapi.tiangolo.com/python-types/#type-hints-with-metadata-annotations)? (кажется, более верным вариантом)
2. Или продолжать перевод для версии относительно остальных переведённых страниц?

Изменения связаны с введением в FastAPI использования `from typing import Annotated`.

2023-03-21 12:35 UTC, Xewus approved these changes

2023-03-21 12:37 UTC, Xewus commented
> Заметил, что вчера с выходом версии 0.95 была затронута [оригинальная страница документации](https://fastapi.tiangolo.com/tutorial/query-params-str-validations/#import-query-and-annotated), в которой часть объяснения вынесена в предыдущий раздел [Python Types Intro](https://fastapi.tiangolo.com/python-types/#type-hints-with-metadata-annotations).
> 
> Как в таком случае стоит поступить?
> 
> 1. Добавить нововведения в текущий PR, не касаясь страницы [Python Types Intro](https://fastapi.tiangolo.com/python-types/#type-hints-with-metadata-annotations)? (кажется, более верным вариантом)
> 2. Или продолжать перевод для версии относительно остальных переведённых страниц?
> 
> Изменения связаны с введением в FastAPI использования `from typing import Annotated`.

Мистер Себастьян просил не смешивать страницы.

2023-03-21 15:58 UTC, Xewus commented
> > > Заметил, что вчера с выходом версии 0.95 была затронута [оригинальная страница документации](https://fastapi.tiangolo.com/tutorial/query-params-str-validations/#import-query-and-annotated), в которой часть объяснения вынесена в предыдущий раздел [Python Types Intro](https://fastapi.tiangolo.com/python-types/#type-hints-with-metadata-annotations).
> > > Как в таком случае стоит поступить?
> > > 
> > > 1. Добавить нововведения в текущий PR, не касаясь страницы [Python Types Intro](https://fastapi.tiangolo.com/python-types/#type-hints-with-metadata-annotations)? (кажется, более верным вариантом)
> > > 2. Или продолжать перевод для версии относительно остальных переведённых страниц?
> > > 
> > > Изменения связаны с введением в FastAPI использования `from typing import Annotated`.
> > 
> > 
> > Мистер Себастьян просил не смешивать страницы.
> 
> Не смешивать в том смысле, что один Pull Request затрагивает одну страницу? Только что закончил добавлять изменения с `Annotated`, но могу откатить, если нужно.

Прощу прощения, что-то вместо "оригинальной" подумалось "главная" страница.

2023-03-21 16:04 UTC, Xewus commented
Посмотрел, без `Annotated` и короче, и понятнее, и привычнее.

2023-03-21 16:34 UTC, Xewus approved these changes
Точку зрения свою оставил, надеюсь примите к сведению.
Апрувну, чтоб не  было задержек.
Также крайне рекомендую дёрнуть кого-нибудь знакомого, чтоб он тоже апрувнул, иначе можно зависнуть на очень долго. Некоторые ПРы висят более года.

2023-03-21 16:34 UTC, Xewus commented on docs/ru/docs/tutorial/query-params-str-validations.md
> +Вместо этого, используйте обычное указание значения по умолчанию для параметра функции. Иначе, это было бы несовместимо.
"было бы" -> "будет"

2023-03-21 16:34 UTC, Xewus commented on docs/ru/docs/tutorial/query-params-str-validations.md
> +...или как в старом коде, который вы нашли:
"will" - про будущее.

Который вам может попасться/можете найти.

2023-03-21 16:34 UTC, Xewus commented on docs/ru/docs/tutorial/query-params-str-validations.md
> +Если вы вместо `Annotated` используете **(устаревший) стиль значений по умолчанию**, тогда при вызове этой функции без FastAPI в **другом месте** вам необходимо **помнить** о передаче аргументов функ
```
только когда операции внутри дадут сбой.
```
Учитывая, что через всю документацию канвой проходит "операции пути", может заменить на вычисления/функции.

2023-03-21 16:34 UTC, Xewus commented on docs/ru/docs/tutorial/query-params-str-validations.md
> +* `fixedquery`: в точности содержит строку `fixedquery`.
Ссылка на сайт была просто для примера - где можно проверить эту регулярку.
Она пропустит только строку `fixedquery`.
`fixedqueryyyyyyyyyyy`, которая точно **содержит** эту строку, через данную регулярку не пройдёт.

2023-03-21 19:37 UTC, Ernilia reviewed
Посмотрю в ближайшее время!

2023-03-22 16:11 UTC, Ernilia commented on docs/ru/docs/tutorial/query-params-str-validations.md
> +Помните, как ранее я говорил об `Annotated`, что он может быть использован для добавления метаданных для ваших параметров в разделе [Введение в аннотации типов Python](../python-types.md#type-hints-w
Выглядит будто нужно разделить одно предложение на два. 
(Помните, как ранее я говорил об `Annotated`? Он может быть использован для добавления метаданных для ваших параметров в разделе [Введение в аннотации типов Python](../python-types.md#type-hints-with-metadata-annotations){.internal-link target=_blank}?)
Возможно вкусовщина, но так будто выглядит более уместно.

2023-03-22 16:14 UTC, Ernilia commented on docs/ru/docs/tutorial/query-params-str-validations.md
> +Теперь, когда у нас есть `Annotated`, где мы может добавить больше метаданных, добавим `Query` со значением параметра `max_length` равным 50:
Можем вместо может?

2023-03-22 16:28 UTC, Ernilia commented on docs/ru/docs/tutorial/query-params-str-validations.md
> +Но когда они вам понадобятся и освоите их, то вы уже знаете, что можете их использовать в **FastAPI**.
Опять же вкусовщина , но на мой вкус звучит топорно. Будто бы лучше будет такая формулировка. 
(Но когда они вам понадобятся и вы закончите их освоение, то не будет проблемой использовать их в **FastAPI**.)

2023-03-22 16:44 UTC, Ernilia commented on docs/ru/docs/tutorial/query-params-str-validations.md
> +    Некоторые из них могут еще не отображать всю заявленную дополнительную информацию, хотя в большинстве случаев отсутствующая функция уже запланирована к разработке.
Некоторые из них могут не отображать (на данный момент) всю заявленную дополнительную информацию, хотя в большинстве случаев отсутствующая функция уже запланирована к разработке.

2023-03-22 16:49 UTC, Ernilia approved these changes
Пробежался по тексту, оставил несколько замечаний. В целом очень понятный перевод.

2023-03-22 17:12 UTC, dedkot01 commented on docs/ru/docs/tutorial/query-params-str-validations.md
> +Но когда они вам понадобятся и освоите их, то вы уже знаете, что можете их использовать в **FastAPI**.
Вызвало трудности у меня это предложение и не смог придумать лучше. Мне нравится предложенный вариант, спасибо👍

2023-03-22 17:13 UTC, dedkot01 commented on docs/ru/docs/tutorial/query-params-str-validations.md
> +    Запомните, в каждом случае, когда вам необходимо объявить query-параметр обязательным, вы можете просто не указывать параметр `default`. Таким образом, вам редко придётся использовать `...` или `
Уберу пожалуй вцелом `в каждом случае`, без него смысл предложения не изменится

2023-03-22 17:16 UTC, dedkot01 commented on docs/ru/docs/tutorial/query-params-str-validations.md
> +    Например, для `List[int]` список будет провалидирован (и задокументирован) на содержимое, что все его элементы целочисленные. Но для простого `list` такой проверки не будет.
Согласен, но может лучше такой вариант:

Например, для List[int] список будет провалидирован (и задокументирован) на содержание только целочисленных элементов.

2023-03-22 17:22 UTC, Ernilia approved these changes

2023-03-22 17:27 UTC, Ernilia approved these changes

2023-04-13 17:57 UTC, tiangolo commented
Thank you for your contribution @dedkot01! :bow: 

And thanks for the reviews @Xewus and @Ernilia :clap: :coffee:

2023-04-13 17:58 UTC, merged