:globe_with_meridians:  Add Russian translation for docs/ru/docs/benchmarks.md
fastapi/fastapi pull request #9271
Opened 2023-03-18 19:54 UTC by Xewus

There is already exist [3035]( https://github.com/tiangolo/fastapi/pull/3035) with the translation of this page.
But it seems dead and I decided to clean up the PRs a bit.

2023-03-23 10:25 UTC, dedkot01 requested changes
Хорошо бы всё таки разделить на 2 PR

2023-03-23 10:25 UTC, dedkot01 commented on docs/ru/docs/benchmarks.md
> +
Лишняя пустая строка

2023-03-23 10:25 UTC, dedkot01 commented on docs/ru/docs/benchmarks.md
> +
Лишняя пустая строка

2023-03-23 10:25 UTC, dedkot01 commented on docs/ru/mkdocs.yml
> +- help-fastapi.md
Причём здесь `help-fastapi.md`? PR же не затрагивает этот раздел.

Также нет страницы `project-generation.md`.

2023-03-23 10:25 UTC, dedkot01 commented on docs/ru/docs/project-generation.md
> +    * **Интуитивно понятный**: Отличная поддержка редактора. <abbr title="также известное как автозаполнение, интеллектуальность">Автозавершение</abbr> везде. Меньше времени на отладку.
Наиболее популярен термин `автодополнение` вместо `автозавершение`

2023-03-23 10:25 UTC, dedkot01 commented on docs/ru/docs/project-generation.md
> +* Простая интеграция Python с **Jupyter Kernels** для разработки удалённо или в Docker с расширениями похожими на  Atom Hydrogen или Visual Studio Code Jupyter.
Два пробела подряд:
`на  Atom Hydrogen `

2023-03-23 11:08 UTC, Xewus commented on docs/ru/docs/benchmarks.md
> +
> Хорошо бы всё таки разделить на 2 PR

Тут косяк какой-то вышел, генератора не должно быть и его удалял целенаправленно перед отправкой.

2023-03-23 11:18 UTC, Xewus commented on docs/ru/docs/project-generation.md
> +* Простая интеграция Python с **Jupyter Kernels** для разработки удалённо или в Docker с расширениями похожими на  Atom Hydrogen или Visual Studio Code Jupyter.
Этот файл удалён, но замечание учтено в соответствующем ПР.

2023-03-23 11:19 UTC, Xewus commented on docs/ru/docs/project-generation.md
> +    * **Интуитивно понятный**: Отличная поддержка редактора. <abbr title="также известное как автозаполнение, интеллектуальность">Автозавершение</abbr> везде. Меньше времени на отладку.
Этот файл удалён, но замечание учтено в соответствующем ПР.

2023-03-23 11:22 UTC, dedkot01 commented on docs/ru/mkdocs.yml
> +- help-fastapi.md
Интересно, в браузере её всё равно вижу, и она действительно есть, но не указана в этом файле. Понял, спасибо.

2023-03-23 11:23 UTC, dedkot01 approved these changes

2023-03-24 12:49 UTC, Kirilex approved these changes

2023-03-24 12:49 UTC, Kirilex commented on docs/ru/docs/benchmarks.md
> +Независимые тесты производительности приложений от TechEmpower показывают, что **FastAPI** под управлением Uvicorn <a href="https://www.techempower.com/benchmarks/#section=test&runid=7464e520-0dc2-47
С этой строкой можно что-то сделать? 
Текст в ссылке длинный, из-за чего в обычном окне браузера после Uvicorn идёт перенос на следующую строку.

2023-03-24 12:49 UTC, Kirilex commented on docs/ru/docs/benchmarks.md
> +    * **Starlette**: (использует Uvicorn) веб-микрофреймворк
```suggestion
    * **Starlette**: (использует Uvicorn) веб-микрофреймворк
```
Мне кажется то, что в скобках, должно быть до двоеточия.

2023-03-24 12:49 UTC, Kirilex commented on docs/ru/docs/benchmarks.md
> +        * **FastAPI**: (использует Starlette) API-микрофреймворк с дополнительными функциями для создания API, с валидацией данных и т.д.
Аналогично.

2023-04-13 17:52 UTC, tiangolo commented
Awesome, thank you @Xewus! :bow: 

And thanks for the reviews @dedkot01 and @Kirilex :coffee:

2023-04-13 17:52 UTC, merged

2023-04-14 08:42 UTC, Xewus commented
Thank you .
And @tiangolo  or @Kludex  I think we should close PR [3035](https://github.com/tiangolo/fastapi/pull/3035) now.