fix: Allow duplicated variable names in dependency
fastapi/fastapi pull request #9319
Opened 2023-03-27 09:41 UTC by kkosyl-rtbhouse

Fixes https://github.com/tiangolo/fastapi/issues/4610

2023-03-28 03:09 UTC, Ryandaydev approved these changes
Tests pass

2023-04-21 09:15 UTC, peku33 commented
Hi, is there any chance to have this merged anytime soon?

2023-05-08 09:23 UTC, jkbak commented
@Kludex I see that you added an `investigate` label. Is that still blocking this merge?

2023-05-18 13:41 UTC, peku33 commented
@Ryandaydev, maybe you have a chance to merge it after 2 months since it was initially created?

2023-05-19 03:28 UTC, Ryandaydev commented
> @Ryandaydev, maybe you have a chance to merge it after 2 months since it was initially created?

@tiangolo merges the PRs.

2023-06-23 10:38 UTC, peku33 commented
Is there anything else we can do, to move this forward? I believe we did everything to have it ready for merge. Three months later there is no single sign of decision in any direction and the bug still exists. @tiangolo @Ryandaydev

2025-07-10 07:20 UTC, YuriiMotov submitted a review, later dismissed
LGTM

`test_openapi_schema` test fails before changes in both Pydantic V1 and V2.
This PR fixes it.

`test_valid` and `test_missing` pass in current version (0.116.0).

I would rename this PR to `Fix openapi schema for single Body parameters with aliases`

2025-07-10 07:28 UTC, YuriiMotov requested changes
There is a problem here.
It only works if we have multiple body parameters (with different variable names) or set `embed=True`.
Otherwise FastAPI fails to understand that it should create body model for the endpoint.

```python
from fastapi import Body, Depends, FastAPI

app = FastAPI()

# Without embed=True

def dep_1(param: str = Body(..., alias="param_1")):
    return param


def dep_2(param: str = Body(..., alias="param_2")):
    return param


@app.post("/example")
def example(
    field_1: str = Depends(dep_1),
    field_2: str = Depends(dep_2),
) -> list[str]:
    return [field_1, field_2]

# With embed=True

def dep_1_emb(param: str = Body(..., alias="param_1", embed=True)):
    return param


def dep_2_emb(param: str = Body(..., alias="param_2", embed=True)):
    return param


@app.post("/example-emb")
def example_emb(
    field_1: str = Depends(dep_1_emb),
    field_2: str = Depends(dep_2_emb),
) -> list[str]:
    return [field_1, field_2]
```
This will show incorrect schema for `/example` endpoint
![image](https://github.com/user-attachments/assets/9716701e-fe9e-47c6-a0b3-c7de8d6a302f)

That's because FastAPI treats those parameters as one and doesn't force embedding them.

If we set `embed=True` then it works as we expect it (as it's shown in `/example-emb` endpoint):
![image](https://github.com/user-attachments/assets/20450d95-ea1f-465b-8462-f2b263ce8283)

@kkosyl-rtbhouse, could you please take a look?

2025-08-09 22:19 UTC, closed without merging