🌐 Add Portuguese translation for `docs/pt/docs/advanced/events.md`
fastapi/fastapi pull request #9326
Opened 2023-03-28 23:58 UTC by oandersonmagalhaes

2023-04-07 00:12 UTC, fcrozetta requested changes
Suggestions:
- One small grammar change (My spell check keeps pointing the accent should not be there 🤷🏻‍♂️)
- the phrase in parenthesis was not translated to BR🇧🇷

2023-04-07 00:12 UTC, fcrozetta commented on docs/pt/docs/advanced/events.md
> +Você pode definí-lo com lógica de *inicialização* e *desligamento* usando os parâmetros de `lifespan` da aplicação `FastAPI`, e um "gerenciador de contexto" (I'll show you what that is in a second).
```suggestion
Você pode defini-lo com lógica de *inicialização* e *desligamento* usando os parâmetros de `lifespan` da aplicação `FastAPI`, e um "gerenciador de contexto" (Te mostrarei o que é isso a seguir).
```

2023-04-07 00:12 UTC, fcrozetta commented on docs/pt/docs/advanced/events.md
> +Você pode definí-lo com lógica de *inicialização* e *desligamento* usando os parâmetros de `lifespan` da aplicação `FastAPI`, e um "gerenciador de contexto" (I'll show you what that is in a second).
The last phrase is written in first person, and I'm not sure this is a good idea, but I'm keeping it like this to match the english version

2023-04-08 21:17 UTC, fcrozetta approved these changes

2023-04-08 21:17 UTC, fcrozetta approved these changes

2023-04-26 11:03 UTC, LorhanSohaky commented
> @LorhanSohaky and @fabioueno, could you take a look at this PR, please? 😅

At the end of the day I will review

2023-04-27 11:49 UTC, LorhanSohaky requested changes
I fixed some typos, standardized some terms used throughout the text and
I think that with these suggestions the reading becomes more fluid

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +Pode ser muito útil para configurar **recursos** que você precisa usar por toda aplicação, e que são **compartilhadas** entre os requests, e/ou que você precisa **limpar** após. Por exemplo, o pool d
```suggestion
Pode ser muito útil para configurar **recursos** que você precisa usar por toda aplicação, e que são **compartilhados** entre as requisições, e/ou que você precisa **limpar** depois. Por exemplo, o pool de uma conexão com o banco de dados ou carregamento de um modelo compartilhado de aprendizado de máquina (_machine learning_).
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +Vamos imaginar que você tem algum **modelos de _machine learning_** que você quer usar para lidar com os requests. 🤖
```suggestion
Vamos imaginar que você tem alguns **modelos de _machine learning_** que deseja usar para lidar com as requisições. 🤖
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +Os mesmos modelos são compartilhados entre os requests, então, não é um modelo por request, ou um por usuário ou algo parecido.
```suggestion
Os mesmos modelos são compartilhados entre as requisições, então não é um modelo por requisição, ou um por usuário ou algo parecido.
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +Vamos imaginar que o carregamento do modelo pode **levar bastante tempo**, porque ele pode ler uma grande quantidade de **dados do disco**. Então você não quer fazer isso a cada request.
```suggestion
Vamos imaginar que o carregamento do modelo pode **demorar bastante tempo**, porque ele tem que ler muitos **dados do disco**. Então você não quer fazer isso a cada requisição.
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +Você poderia carregá-lo em um nível mais alto do módulo/arquivo, mas isso poderia também significaria **carregar o modelo** mesmo se você estiver executando um simples teste automatizado, então esse
```suggestion
Você poderia carregá-lo no nível mais alto do módulo/arquivo, mas isso também poderia significaria **carregar o modelo** mesmo se você estiver executando um simples teste automatizado, então esse teste poderia ser **lento** porque teria que esperar o carregamento do modelo antes de ser capaz de executar uma parte independente do código.
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +Isso é o que nós iremos resolver, vamos carregar o modelo antes das requests serem manuseadas, mas apenas um pouco antes da aplicação iniciar o recebimento de requests, não enquanto o código estiver
```suggestion
Isso é que nós iremos resolver, vamos carregar o modelo antes das requisições serem manuseadas, mas apenas um pouco antes da aplicação começar a receber requisições, não enquanto o código estiver sendo carregado.
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +## Lifespan
```suggestion
## Vida útil (_Lifespan_)
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +Você pode defini-lo com lógica de *inicialização* e *desligamento* usando os parâmetros de `lifespan` da aplicação `FastAPI`, e um "gerenciador de contexto" (Te mostrarei o que é isso a seguir).
```suggestion
Você pode definir essa lógica de *inicialização* e *encerramento* usando os parâmetros de `lifespan` da aplicação `FastAPI`, e um "gerenciador de contexto" (te mostrarei o que é isso a seguir).
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +Nós criamos uma função assíncrona chamada `lifespan()` com `yield` como isso:
```suggestion
Nós criamos uma função assíncrona chamada `lifespan()` com `yield` como este:
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +Aqui nós estamos simulando a *inicialização* custosa de carregamento do modelo colocando a (falsa) função modelo em um dicionário em um dicinário com modelo de _machine learning_ antes do `yield`. Es
```suggestion
Aqui nós estamos simulando a *inicialização* custosa do carregamento do modelo colocando a (falsa) função de modelo no dicionário com modelos de _machine learning_ antes do `yield`. Este código será executado **antes** da aplicação **começar a receber requisições**, durante a *inicialização*.
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +E então, logo após o `yield`, descarregaremos o modelo. Esse código será executado **após** a aplicação **terminar de lidar com os requests**, pouco antes do *desligamento*. Isso poderia, por exemplo
```suggestion
E então, logo após o `yield`, descarregaremos o modelo. Esse código será executado **após** a aplicação **terminar de lidar com as requisições**, pouco antes do *encerramento*. Isso poderia, por exemplo, liberar recursos como memória ou GPU.
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +!!! tip
```suggestion
!!! tip "Dica"
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +    O `shutdown` aconteceria quando você está **parando** a aplicação.
```suggestion
    O `shutdown` aconteceria quando você estivesse **encerrando** a aplicação.
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +A primeira coisa a notar, é que nós estamos definindo uma função assíncrona com `yield`. Isso é muito semelhante à Dependências com `yield`.
```suggestion
A primeira coisa a notar, é que estamos definindo uma função assíncrona com `yield`. Isso é muito semelhante à Dependências com `yield`.
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +A primeira parte da função, antes do `yield`, irá ser executada **antes** da aplicação começar.
```suggestion
A primeira parte da função, antes do `yield`, será  executada **antes** da aplicação inicializar.
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +E a parte posterior do `yield` irá executar **após** a aplicação ser finalizada.
```suggestion
E a parte posterior do `yield` irá executar **após** a aplicação ser encerrada.
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +Nas versões mais recentes de Python, há também um **gerenciador de contexto assíncrono**. Você deveria usar isso com `async with`:
```suggestion
Nas versões mais recentes de Python, há também um **gerenciador de contexto assíncrono**. Você o usaria com `async with`:
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +Quando você cria um gerenciador de contexto ou um gerenciador de contexto assíncrono como o mencionado acima, o que ele faz é que, antes de entrar no bloco `with`, ele irá executar o código anterior
```suggestion
Quando você cria um gerenciador de contexto ou um gerenciador de contexto assíncrono como mencionado acima, o que ele faz é que, antes de entrar no bloco `with`, ele irá executar o código anterior ao `yield`, e depois de sair do bloco `with`, ele irá executar o código depois do `yield`.
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +O parâmetro `lifespan` da aplicação `FastAPI` leva um **Gerenciador de Contexto Assíncrono**, então nós podemos passar nosso novo gerenciador de contexto assíncrono do `lifespan` para ele.
```suggestion
O parâmetro `lifespan` da aplicação `FastAPI` usa um **Gerenciador de Contexto Assíncrono**, então nós podemos passar nosso novo gerenciador de contexto assíncrono do `lifespan` para ele.
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +!!! warning
```suggestion
!!! warning "Aviso"
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +    O caminho recomendável para lidar com a *inicialização* e o *desligamento* é usando o parâmetro `lifespan` da aplicação `FastAPI` como descrito acima.
```suggestion
    A maneira recomendada para lidar com a *inicialização* e o *encerramento* é usando o parâmetro `lifespan` da aplicação `FastAPI` como descrito acima.
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +Há um caminho alternativo para refinir a execução dessa lógica durante *inicialização* e durante *desligamento*.
```suggestion
Existe uma forma alternativa para definir a execução dessa lógica durante *inicialização* e durante *encerramento*.
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +Você pode definir manipuladores de eventos (funções) que precisam ser executadas antes da aplicação começar, ou quando a aplicação está desligando.
```suggestion
Você pode definir manipuladores de eventos (funções) que precisam ser executadas antes da aplicação inicializar, ou quando a aplicação estiver encerrando.
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +Nesse caso, a função de manipulação de evento `startup` irá inicializar os itens do "database" (só um `dict`) com alguns valores.
```suggestion
Nesse caso, a função de manipulação de evento `startup` irá inicializar os itens do "banco de dados" (só um `dict`) com alguns valores.
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +E sua aplicação não irá começar a receber requests até que tudo da manipulação de evento `startup` esteja completo.
```suggestion
E sua aplicação não irá começar a receber requisições até que todos so manipuladores de eventos de `startup` sejam concluídos.
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +Para adicionar uma função que deve ser executada quando a aplicação estiver desligando, declare ela com o evento `"shutdown"`:
```suggestion
Para adicionar uma função que deve ser executada quando a aplicação estiver encerrando, declare ela com o evento `"shutdown"`:
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +!!! info
```suggestion
!!! info "Informação"
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +!!! tip
```suggestion
!!! tip "Dica"
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +    Então, isso envolve I/O (input/output), que requer "espera" para coisas serem escritas em disco.
```suggestion
    Então, isso envolve I/O (input/output), que exige"esperar" que coisas sejam escritas em disco.
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +Há uma grande chance que a lógica para sua *inicialização* e *desligamento* esteja conectada, você pode querer iniciar alguma coisa e então finalizá-la, adquirir um recurso e então liberá-lo, etc.
```suggestion
Há uma grande chance que a lógica para sua *inicialização* e *encerramento* esteja conectada, você pode querer iniciar alguma coisa e então finalizá-la, adquirir um recurso e então liberá-lo, etc.
```

2023-04-27 11:49 UTC, LorhanSohaky commented on docs/pt/docs/advanced/events.md
> +!!! info
```suggestion
!!! info "Informação"
```

2023-04-27 18:08 UTC, oandersonmagalhaes commented on docs/pt/docs/advanced/events.md
> +E sua aplicação não irá começar a receber requests até que tudo da manipulação de evento `startup` esteja completo.
```suggestion
E sua aplicação não irá começar a receber requisições até que todos os manipuladores de eventos de `startup` sejam concluídos.
```

2023-04-27 22:03 UTC, LorhanSohaky approved these changes
Nice!!!

2023-05-08 11:16 UTC, tiangolo commented
Awesome, thanks @oandersonmagalhaes! :rocket: 

And thanks for the reviews @LorhanSohaky and @fcrozetta :bow:

2023-05-08 11:16 UTC, merged