feature: Add a translation to Chinese for deployment
fastapi/fastapi pull request #9356
Opened 2023-04-06 06:54 UTC by ponponon

I added the Chinese translation about deployment, but only half of it is finished now. If the auditor thinks there is no problem, I will continue to complete the rest of the translation work

2023-04-13 18:23 UTC, tiangolo requested changes
Thanks for your effort!

I added a couple of comments to remove some files and lines that wouldn't be part of the PR. Thanks! :coffee:

2023-04-13 18:23 UTC, tiangolo commented on Pipfile
> +python_version = "3.10"
Please remove this file.

2023-04-13 18:23 UTC, tiangolo commented on docs/zh/docs/deployment/deta.md
> +    You can read more details in the <a href="https://docs.deta.sh/docs/micros/about/" class="external-link" target="_blank">Deta docs</a> to see if it's the right choice for you.
Please remove these extra files that are not part of the translation PR.

2023-04-13 18:23 UTC, tiangolo commented on docs/zh/mkdocs.yml
> +  - deployment/versions.md
Please include here only the translated files.

2023-04-20 10:02 UTC, ponponon commented
Great, I can't wait to see the new docs go live. I want to continue to finish the translation of the rest of the content.

2023-04-25 09:40 UTC, wdh99 commented
你要先把，除了文件`docs/zh/docs/deployment/versions.md`之外的所有修改复原。因为每个翻译的pull request只针对一个文件。

2023-06-26 23:57 UTC, tiangolo commented
📝 Docs preview for commit 02f797239e9eaeef216af5599e7a0ce0a42f7c9b at: https://649a25cf5638651834126b7a--fastapi.netlify.app

2024-01-29 15:34 UTC, tiangolo commented
As this PR had requested changes to be applied but has been inactive for a while, it's now going to be closed. But if there's anyone interested, feel free to create a new PR.

2024-01-29 15:34 UTC, closed without merging