Add Russian translation for docs/ru/docs/tutorial/response-status-code.md
fastapi/fastapi pull request #9370
Opened 2023-04-09 15:01 UTC by nadia3373

Предлагаю перевод на русский язык страницы [Response Status Code](https://fastapi.tiangolo.com/tutorial/response-status-code/). Рассмотрите, пожалуйста.

2023-04-11 11:08 UTC, Xewus requested changes
Я не стал подчёркивать каждую строчку, но считаю, что везде нужно заменить `код ответа` на `код статуса [ответа]`.
Практически во всех встреченных инструментах (и в браузерах , в том числе) используется именно такое именование.

2023-04-11 14:29 UTC, zxcq544 commented on docs/ru/docs/tutorial/response-status-code.md
> +## О кодах ответа HTTP
`HHTP` опечатка - должно быть `HTTP`

2023-04-17 04:10 UTC, nadia3373 commented
> Я не стал подчёркивать каждую строчку, но считаю, что везде нужно заменить `код ответа` на `код статуса [ответа]`.
> Практически во всех встреченных инструментах (и в браузерах , в том числе) используется именно такое именование.

Заменила "код ответа" везде на "код статуса [ответа]" и внесла другие изменения. Изначально руководствовалась документацией MDN, но, видимо, их вариант перевода не самый распространённый. Спасибо за корректировку.

2023-04-17 11:43 UTC, Xewus approved these changes

2023-04-17 11:46 UTC, Xewus commented
На самом деле, документация фреймворка очень хороша для новичков и моё мнение (но не требование, конечно), что некоторые термины для них могут быть непонятны и их можно уточнить, даже если в оригинале такого нет.

2023-04-17 14:53 UTC, zxcq544 approved these changes

2023-04-25 18:44 UTC, tiangolo commented
Great, thank you @nadia3373! :coffee: 

And thanks for the reviews @zxcq544 and @Xewus! :bow:

2023-04-25 18:44 UTC, merged