Add a new language, Lao.
fastapi/fastapi pull request #9396
Opened 2023-04-15 01:27 UTC by TheBrown

About Laos: Laos is a landlocked country in South-east Asia on the Indochinese peninsula between Thailand and Vietnam and north of Cambodia.

2023-04-25 18:43 UTC, tiangolo requested changes
Great! I'm asking you to remove a few files for translations, those should go in independent PRs, that way others can review and approve or ask for changes one by one.

2023-04-25 18:43 UTC, tiangolo commented on docs/lo/docs/alternatives.md
Please remove this file for this PR.

2023-04-25 18:43 UTC, tiangolo commented on docs/lo/docs/benchmarks.md
Please remove this file for this PR.

2023-04-25 18:43 UTC, tiangolo commented on docs/lo/docs/contributing.md
Please remove this file for this PR.

2023-04-25 18:43 UTC, tiangolo commented on docs/lo/docs/deployment/index.md
Please remove this file for this PR. It could go in an independent PR. :rocket:

2023-04-25 18:43 UTC, tiangolo commented on docs/lo/docs/fastapi-people.md
Please remove this file for this PR.

2023-04-25 18:43 UTC, tiangolo commented on docs/lo/docs/features.md
Please remove this file for this PR.

2023-04-25 18:43 UTC, tiangolo commented on docs/lo/docs/help-fastapi.md
Please remove this file for this PR.

2023-04-25 18:43 UTC, tiangolo commented on docs/lo/docs/history-design-future.md
Please remove this file for this PR.

2023-04-25 18:43 UTC, tiangolo commented on docs/lo/docs/index.md
Please reset this file for the original content (just a copy of the normal index plus the note at the top). And then this translation could go in an independent PR, so that others can more easily review it.

2023-04-25 18:43 UTC, tiangolo commented on docs/lo/docs/project-generation.md
Please remove this file for this PR.

2023-04-25 18:43 UTC, tiangolo commented on docs/lo/docs/python-types.md
Please remove this file for this PR.

2023-04-25 18:43 UTC, tiangolo commented on docs/lo/docs/tutorial/index.md
Please remove this file for this PR, it could go in another PR.

2023-04-25 18:43 UTC, tiangolo commented on docs/lo/docs/tutorial/security/oauth2-jwt.md
Please remove this file for this PR.

2023-04-25 18:43 UTC, tiangolo commented on docs/lo/release-notes.md
Please remove this file for this PR.

2023-04-26 03:28 UTC, TheBrown commented
Hi @tiangolo, I have resolved all changes requested.

2023-05-08 11:15 UTC, tiangolo commented
Great, thank you @TheBrown! :rocket:

2023-05-08 11:15 UTC, merged