Read field_info per body param instead of assuming it to be all equal.
fastapi/fastapi pull request #9410
Opened 2023-04-19 12:34 UTC by jsg921019

fixes #9116

2024-02-24 11:01 UTC, YuriiMotov approved these changes
Looks good!

Can confirm that:
1. Issue is still relevant for the current FastAPI version (0.109.2).
2. Tests fail before changes (`"type":"bytes_type","loc":["body","file"],"msg":"Input should be a valid bytes" ...`) and pass after changes
3. Solution and tests look nice

2024-02-24 11:30 UTC, YuriiMotov requested changes
After applying changes I mentioned I will be ready to approve this PR

2024-02-24 11:30 UTC, YuriiMotov commented on tests/test_request_form_file.py
> +    assert response.json() == file_and_token_required
This fails in current version of Pydantic.
Error message format was changed.
I world suggest removing this line (and in other tests with `response.status_code == 422`)

2024-02-24 11:30 UTC, YuriiMotov commented on tests/test_request_form_file.py
> +    "openapi": "3.0.2",
```suggestion
    "openapi": "3.1.0",
```
Current version is 3.1.0

2024-02-25 16:18 UTC, thomasleveil commented
@jsg921019 I took the liberty to resubmit your fix in #11194 so that it includes the latest FastAPI changes

2025-06-21 17:12 UTC, closed without merging

2025-06-21 17:16 UTC, YuriiMotov commented
@jsg921019, sorry, it was closed automatically.
We can re-open it if you are ready to continue working on it.
Thanks for your interest in FastAPI!