:globe_with_meridians:  Add Russian translation for `docs/ru/docs/deployment/manually.md`
fastapi/fastapi pull request #9417
Opened 2023-04-20 15:39 UTC by Xewus

2023-04-26 16:19 UTC, AGolicyn requested changes

2023-04-26 17:28 UTC, Xewus commented on docs/ru/docs/deployment/manually.md
> +Но если Вы желаете использовать **Trio**, то можете использовать совместимый с нею **Hypercorn**. ✨
> А почему Trio это она? :)

Исхожу из того, что это библиотека.

2023-04-26 17:46 UTC, Xewus commented on docs/ru/docs/deployment/manually.md
> +* Запуск нескольких экземпляров приложения (количество запущенных процессов)
Термин "репликация" мне попадался обычно в контексте баз данных, и там он подразумевает, что оба "клона" должны быть полностью идентичны, синхронизировать изменения и в любой момент времени максимально похожи. В то время как запущенные указанным образом экземпляры приложений будут  всегда в разном состоянии.
И в целом, стараюсь не перегружать техническими терминами.

2023-04-26 19:34 UTC, AGolicyn approved these changes

2023-04-29 08:09 UTC, AlexandrMaltsevYDX approved these changes
Good!

2023-05-08 11:13 UTC, tiangolo commented
Thank you @Xewus! :clap: :cake: 

And thanks for the reviews @AGolicyn and @AlexandrMaltsevYDX :bow:

2023-05-08 11:16 UTC, merged