🌐 Add Russian translation for `docs/ru/docs/deployment/https.md`
fastapi/fastapi pull request #9428
Opened 2023-04-23 10:27 UTC by Xewus

2023-04-25 12:13 UTC, onix2020 approved these changes

2023-04-26 15:26 UTC, AGolicyn requested changes
Проделана отличная работа!, предлагаю некоторые правки.

2023-04-26 16:02 UTC, Xewus commented on docs/ru/docs/deployment/https.md
> +* расшифровка запросов
> Не уверен, стоит ли здесь использовать буллет поинты, но это дело вкуса наверное :)

Насколько помню, в оригинале вовсе идёт перечисление всего этого в одну строку.
Есть мнение, что длинные предложения воспринимаются хуже, потому переделал в список.

2023-04-26 19:28 UTC, AGolicyn commented on docs/ru/docs/deployment/https.md
> +* расшифровка запросов
Просто при простом перечислении это явно выглядит как пайплайн, где все элементы зависимы и следуют по порядку друг за другом. А при отделении точками такое ощущение, словно все элементы независимы и порядок не важен. Но читается так однозначно легче, так что аппрув :)

2023-04-26 19:28 UTC, AGolicyn approved these changes

2023-04-26 21:39 UTC, Xewus commented on docs/ru/docs/deployment/https.md
> +* расшифровка запросов
Благодарю.

2023-05-08 11:10 UTC, tiangolo commented
Awesome, thank you @Xewus! :bow: 

And thank you for the reviews @onix2020 and @AGolicyn :coffee:

2023-05-08 11:11 UTC, merged