Allow integer constraints on openapi schema
fastapi/fastapi pull request #9453
Opened 2023-04-27 12:44 UTC by alesanfra

Hi everyone,

I'm opening this PR because I've recently found a weird behavior when dealing with constrained integers. Consider the following example:

```python
from typing import Annotated

from fastapi import FastAPI, Query

app = FastAPI()

@app.get("/item")
async def get_items(limit: Annotated[int, Query(ge=1, le=1000)] = 100):
    return {"message": f"Got items with limit {limit}"}
```

It will produce the following schema (not relevant sections elided):
```json
{
  "paths": {
    "/item": {
      "get": {
        "summary": "Get Items",
        "operationId": "get_items_item_get",
        "parameters": [
          {
            "required": false,
            "schema": {
              "title": "Limit",
              "maximum": 1000.0,
              "minimum": 1.0,
              "type": "integer",
              "default": 100
            },
            "name": "limit",
            "in": "query"
          }
        ],
  },
}
```

As you can see even though `ge=1` and `le=1000` were defined as integers, the internal pydantic model coherces them to floats (`"maximum": 1000.0` and `"minimum": 1.0`). This is a problem when using some security tools like [42 Crunch](https://42crunch.com/) because the mismatch between type and values is reported as a possible vulnerability.

With this PR fastapi will keep the constraints as defined in the source code leveraging the [smart union feature of pydantic](https://docs.pydantic.dev/usage/model_config/#smart-union), therefore in example above fastapi will produce the following schema:

```json
{
  "paths": {
    "/item": {
      "get": {
        "summary": "Get Items",
        "operationId": "get_items_item_get",
        "parameters": [
          {
            "required": false,
            "schema": {
              "title": "Limit",
              "maximum": 1000,
              "minimum": 1,
              "type": "integer",
              "default": 100
            },
            "name": "limit",
            "in": "query"
          }
        ],
  },
}
```

2023-04-27 13:07 UTC, leotac approved these changes
LGTM, much needed.

2023-04-27 19:47 UTC, Escollhas requested changes
You are changing 5 `fields` but:
1 - Not all fields you are changing have test (multipleOf)
2 - The change occurs in 5 fields, but you have not adjusted all the tests who use these fields

About point 2: the type `number` could be more representative, because can be (`int` or `float`), and is a pattern used in other tests for the same context

2025-07-04 15:13 UTC, YuriiMotov commented
Duplicate: https://github.com/fastapi/fastapi/pull/9517

This will convert values `100.0` to just `0` in schema.

2025-07-26 10:27 UTC, tiangolo commented
I would think the behavior from that tool is a bit strange. In JSON, there's no distinction between floats and integers, there's only one type "number". It's weird (and probably wrong) that a tool would flag and interpret different types of numbers. :thinking: 

Do you have a specific use case that needs this other than complying with what the tool is telling you?

2025-08-25 22:18 UTC, closed without merging