:globe_with_meridians: Add Russian translation for docs/ru/docs/tutorial/first-steps.md
fastapi/fastapi pull request #9471
Opened 2023-04-29 13:50 UTC by AGolicyn

The previous pull request for translating this section #3562 is no longer relevant.

2023-04-29 19:36 UTC, Xewus requested changes

2023-04-29 19:36 UTC, Xewus commented on docs/ru/docs/tutorial/first-steps.md
> +* Пишем **декоратор операции пути** (`@app.get("/")`).
```suggestion
* Пишем **декоратор операции пути** (такую как `@app.get("/")`).
```

2023-04-29 19:36 UTC, Xewus commented on docs/ru/docs/tutorial/first-steps.md
> +* Пишем **функцию операции пути** (`def root(): ...`).
```suggestion
* Пишем **функцию операции пути** (похожую на `def root(): ...`).
```

2023-04-29 19:36 UTC, Xewus commented on docs/ru/docs/tutorial/first-steps.md
> +* Запускаем сервер в режиме разработки (`uvicorn main:app --reload`).
```suggestion
* Запускаем сервер в режиме разработки (например, `uvicorn main:app --reload`).
```

2023-04-29 19:49 UTC, AGolicyn commented on docs/ru/docs/tutorial/first-steps.md
> +Теперь, перейдите по адресу <a href="http://127.0.0.1:8000/redoc" class="external-link" target="_blank">http://127.0.0.1:8000/redoc</a>.
Она несёт скорее смысловую паузу, но не суть)

2023-04-29 19:53 UTC, AGolicyn commented on docs/ru/docs/tutorial/first-steps.md
> +Вы также можете использовать OpenAPI для автоматической генерации кода для клиентов, которые взаимодействуют с API. Например, для фронтенд, мобильных или IoT-приложений.
Да надо повесить дефис
```suggestion
Вы также можете использовать OpenAPI для автоматической генерации кода для клиентов, которые взаимодействуют с API. Например, для фронтенд-, мобильных или IoT-приложений.
```

2023-04-29 20:10 UTC, AGolicyn commented on docs/ru/docs/tutorial/first-steps.md
> +* Пишем **функцию операции пути** (`def root(): ...`).
Здесь вот не уверен, что нужно явно указывать, что это пример. Просто поместив выражение в скобки, мы как бы уже говорим, что это пример, и дополнительно на это указывать избыточно.

2023-04-29 20:24 UTC, AGolicyn commented on docs/ru/docs/tutorial/first-steps.md
> +    Термин "path" также часто называется "endpoint" или "route".
Лучше приучать читателя к оригинальным терминам, а не указывать их в виде англицизмов, тем более "ручки" это вообще профессиональный жаргон.

2023-04-29 20:31 UTC, AGolicyn commented on docs/ru/docs/tutorial/first-steps.md
> +#### Определим *декоратор операции пути (path operation decorator)*
"Операции пути" очень сложно для восприятия, и не понятно как слова между собой связаны и почему. Ну у меня именно так :). Добавить к этому "декоратор" или "функцию" и это ещё более усложнит восприятие.
А английский аналог рядом как мостик для читателя, чтобы разобраться почему эти странные слова стоят вместе)

2023-04-29 20:40 UTC, AGolicyn commented on docs/ru/docs/tutorial/first-steps.md
> +    Вы помещаете его над функцией. Как красивую декоративную шляпу (думаю, что оттуда и происходит этот термин).
Так выше сказано, что рассматриваем синтаксис Python, а не языки вообще.

2023-04-29 20:55 UTC, AGolicyn commented on docs/ru/docs/tutorial/first-steps.md
> +Все действия для создания API будут происходить через неё.
Для "точки входа" обычно используют термин entry point. 
Учитывая, что это не просто условная фукнция main, а полноценный экзмпляр класса с кучей методов, посредством которого мы и взимодействуем с приложением. Это куда шире чем просто точка входа.

2023-04-29 21:09 UTC, AGolicyn commented on docs/ru/docs/tutorial/first-steps.md
> +### Шаг 3: определить *операцию пути (path operation)*
Внутри курсива не работает :(

2023-04-29 21:14 UTC, AGolicyn commented on docs/ru/docs/tutorial/first-steps.md
> +#### Путь (path)
Также убрал, скобки не отображаются

2023-04-29 21:18 UTC, AGolicyn commented on docs/ru/docs/tutorial/first-steps.md
> +Все действия для создания API будут происходить через неё.
Может так?
```suggestion
Это единая точка входа для взаимодействия и создания API.
```

2023-04-30 14:26 UTC, Xewus commented on docs/ru/docs/tutorial/first-steps.md
> +Все действия для создания API будут происходить через неё.
Пойдёт.

2023-04-30 14:26 UTC, Xewus approved these changes

2023-05-27 15:44 UTC, Alexandrhub approved these changes

2023-06-03 12:45 UTC, tiangolo commented
Great, thank you @AGolicyn! 🚀 

And thanks for the reviews @Xewus and @Alexandrhub 🍰 🙇

2023-06-03 14:05 UTC, merged