Fix: int values being serialized as floats in the OpenAPI schema
fastapi/fastapi pull request #9517
Opened 2023-05-10 07:33 UTC by alexturcea

Example:

```
app = FastAPI()

class Foo(BaseModel):
    bar: int = Field(..., ge=0, le=100, multiple_of=5)
    baz: float = Field(..., gt=0.1, lt=99.9, multiple_of=3.14)

@app.get("/foo")
def foo() -> Foo:
    return Foo(bar=5, baz=3.14)
```

Schema with the current version:

```
{
...
    "components": {
        "schemas": {
            "Foo": {
                "title": "Foo",
                "required": [
                    "bar",
                    "baz"
                ],
                "type": "object",
                "properties": {
                    "bar": {
                        "title": "Bar",
                        "multipleOf": 5.0,
                        "maximum": 100.0,
                        "minimum": 0.0,
                        "type": "integer"
                    },
                    "baz": {
                        "title": "Baz",
                        "multipleOf": 3.14,
                        "exclusiveMaximum": 99.9,
                        "exclusiveMinimum": 0.1,
                        "type": "number"
                    }
                }
            }
        }
    }
}
```

Schema with the proposed fix:

```
{
...
    "components": {
        "schemas": {
            "Foo": {
                "title": "Foo",
                "required": [
                    "bar",
                    "baz"
                ],
                "type": "object",
                "properties": {
                    "bar": {
                        "title": "Bar",
                        "multipleOf": 5,
                        "maximum": 100,
                        "minimum": 0,
                        "type": "integer"
                    },
                    "baz": {
                        "title": "Baz",
                        "multipleOf": 3.14,
                        "exclusiveMaximum": 99.9,
                        "exclusiveMinimum": 0.1,
                        "type": "number"
                    }
                }
            }
        }
    }
}
```

2023-05-15 07:50 UTC, alexturcea commented
Hi @tiangolo, please review this PR 😄

2023-05-17 04:57 UTC, Ryandaydev approved these changes
Tests pass.

2023-05-31 13:37 UTC, alexturcea commented
Thanks for taking a look @Ryandaydev - is there a process that needs to be followed to get this PR approved?

2024-02-23 13:02 UTC, YuriiMotov requested changes
1) Tests are needed
2) These changes don't work with Pydantic 1.10.14 (`3.0` turns into `3`)

Test example:

**test_application.py**
```
def test_openapi_schema_num_constraints_int_float():
    response = client.get("/openapi.json")
    assert response.status_code == 200, response.text
    response_json = response.json()
    assert isinstance(
        response_json["paths"]["/path/param-gt/{item_id}"]["get"]["parameters"][0][
            "schema"
        ]["exclusiveMinimum"],
        float,
    )

    assert isinstance(
        response_json["paths"]["/path/param-gt-int/{item_id}"]["get"]["parameters"][0][
            "schema"
        ]["exclusiveMinimum"],
        int,
    )
```
Test above works with Pydantic 2.6.1, but fails with Pydantic 1.10.14

2025-07-04 14:51 UTC, YuriiMotov commented
This solution now converts `0.0` to just `0`.

```python
from fastapi import FastAPI
from pydantic import BaseModel, Field

app = FastAPI()


class Foo(BaseModel):
    zero_float: float = Field(ge=0.0)
    non_zero_float: float = Field(ge=0.0)

@app.get("/foo")
def foo() -> Foo:
    pass
```

Results in:

```json
      "Foo": {
        "properties": {
          "zero_float": {
            "type": "number",
            "minimum": 0,                       <-- SHOULD BE 0.0
            "title": "Zero Float"
          },
          "non_zero_float": {
            "type": "number",
            "minimum": 0.1,                       <-- this is Ok
            "title": "Non Zero Float"
          }
        },
```

Not sure this behavior is better than converting all values to `float`s.

2025-07-26 10:24 UTC, tiangolo commented
Interesting, is there a specific use case you would need this for? It would probably be better to start in a discussion with your specific use case and a self contained example.

In JSON, there's no notion or difference between int and float, so having a float would be in theory valid. Are you consuming OpenAPI from something that interprets JSON with some difference between ints and floats?

For now I'll close this one, but if you want to discuss it more, it would be better in a GitHub Discussion. :coffee:

2025-07-26 10:24 UTC, closed without merging