🌐 Add german translation for `docs/de/docs/tutorial/first-steps.md`
fastapi/fastapi pull request #9530
Opened 2023-05-13 10:17 UTC by fhabers21

add german translation for tutorial/first-steps.md

2023-06-27 00:35 UTC, tiangolo commented
📝 Docs preview for commit 4eb2246124075e45bf7aa9a187df029880ac03b7 at: https://649a2ec1c3bf902028a9e518--fastapi.netlify.app

2023-08-31 14:19 UTC, creyD requested changes
Apart from the minor comments I had, I liked the translation.

2023-08-31 14:21 UTC, creyD commented
@tiangolo Would it be possible to adjust the docs so that the reader already knows that the article will be in another language than the selected one? Here i.e. there is no translated version yet for the section, so the reader will automatically be redirected to the English one, which is fine, just would be nice to have indication beforehand.
![Screenshot 2023-08-31 at 16 19 40](https://github.com/tiangolo/fastapi/assets/15138480/c854dd18-9ad7-415d-877b-0c16bd5e974a)

2023-08-31 18:56 UTC, fhabers21 commented
@creyD Thank you for your valuable feedback. I corrected the points you mentioned.

2023-09-01 08:10 UTC, creyD approved these changes
Thanks for the adjustments, I believe it is good to go now!

2023-09-02 15:27 UTC, tiangolo commented
📝 Docs preview for commit 4dca8ea03543eda8a4d9c2efad9c24176b791ec8 at: https://c7d03784.fastapitiangolo.pages.dev

2023-10-05 03:59 UTC, nilslindemann commented
Hello @fhabers21, good PR, I approved it.

Could you include the suggestions in the following .md?

[first-steps.md](https://github.com/tiangolo/fastapi/files/12812131/first-steps.md)

These are mostly changes suggested by GeorchW, who approved my other [closed PR](https://github.com/tiangolo/fastapi/pull/10289). Then he could approve this PR here too (ping, @GeorchW), and we can get this merged. :rocket:

2023-10-05 03:59 UTC, nilslindemann approved these changes

2023-10-09 11:00 UTC, GeorchW approved these changes
Nur kleinere Änderungen, eher subjektiver Natur.

2023-10-09 11:00 UTC, GeorchW commented on docs/de/docs/tutorial/first-steps.md
> +Sie können auch Pydantic Modelle zurückgeben (dazu später mehr).
```suggestion
Sie können auch Pydantic-Modelle zurückgeben (dazu später mehr).
```

2023-10-11 20:56 UTC, nilslindemann commented
Notice, there is still a link to https://fastapi.tiangolo.com/async/#in-a-hurry, which will become something like https://fastapi.tiangolo.com/async/#in-eile after that target document is translated. I have marked it as such [here](https://github.com/tiangolo/fastapi/discussions/9203#discussioncomment-7256485).

2023-10-16 17:30 UTC, nilslindemann commented
Current state of this document in my work branch, with [above link](https://github.com/tiangolo/fastapi/pull/9530#issuecomment-1758526621) translated:

[first-steps.md](https://github.com/tiangolo/fastapi/files/12919834/first-steps.md)

2023-10-22 18:56 UTC, nilslindemann commented
Current state of this document in my work branch:

[first-steps.md](https://github.com/tiangolo/fastapi/files/13064312/first-steps.md)

2023-11-11 13:13 UTC, fhabers21 commented
@nilslindemann, @GeorchW, big thanks for your valuable feedback. I've included your suggestions.

@tiangolo, we might be good to go.

2023-11-11 13:21 UTC, tiangolo commented
📝 Docs preview for commit 9713bcfb3de324713da93b2adb79f830a8d5ed5f at: https://04391ef4.fastapitiangolo.pages.dev

2023-11-11 23:47 UTC, nilslindemann approved these changes

2023-11-11 23:47 UTC, nilslindemann commented on docs/de/docs/tutorial/first-steps.md
> +In diesem Beispiel ist die Variable `app` eine "Instanz" der Klasse `FastAPI`.
Hier typografische Anführungszeichen vergessen. („Instanz“)

2023-11-11 23:50 UTC, nilslindemann commented
Superklasse! Kann meines Erachtens gemerged werden. Nur noch die eine Stelle, wo die „typografischen“ fehlen.

2023-11-12 12:00 UTC, fhabers21 commented
@nilslindemann danke für dein erneuten Review! Habe die Stelle ausgebessert.

2023-11-12 12:04 UTC, tiangolo commented
📝 Docs preview for commit addad7f40b43671d42632ae480f73601ab0efd98 at: https://d654ffb8.fastapitiangolo.pages.dev

2023-11-14 09:03 UTC, nilslindemann commented
Ich hab noch eine Kleinigkeit entdeckt: In Zeile 46 könnte man `JSON-Response` statt `JSON-Antwort` schreiben. Ist aber "Geschmäckle" :-)

2024-01-09 15:35 UTC, tiangolo commented
Nice, thank you @fhabers21! 🚀 

And thanks for the reviews @nilslindemann, @GeorchW, @creyD 🙇

2024-01-09 15:36 UTC, merged