:globe_with_meridians: Add Persian translation for docs/fa/docs/python-types.md
fastapi/fastapi pull request #9553
Opened 2023-05-19 20:22 UTC by amirbahador-hub

2023-06-15 20:21 UTC, amirbahador-hub commented
@Kludex 
Hi if someone reviews this 
I can start translating other pages

2023-06-27 00:39 UTC, tiangolo commented
📝 Docs preview for commit 5934115be5c9ffdc273e0e9e117810660d486797 at: https://649a2fb9b14d051fa5045fc4--fastapi.netlify.app

2023-08-12 04:40 UTC, aminkhani approved these changes

2023-12-03 18:49 UTC, erfan-rfmhr commented on docs/fa/docs/python-types.md
> +اما اگر حتی هیچوقت  **FastAPI**, استفاده نکنید . از کمی یادگیری  در مورد آنها سود خواهید برد.
I think this is a better translation:

> اما حتی اگر هرگز از FastAPI استفاده نمی کنید، کمی یادگیری درباره آن ها برای شما مفید خواهد بود.

2023-12-03 18:52 UTC, erfan-rfmhr commented on docs/fa/docs/python-types.md
> +    اگر شما یک متخصص پایتون هستید, و شما از قبل همه چیز را در مورد type hints می‌دانید, به فصل بعدی بروید.
> اگر شما یک متخصص پایتون هستید و از قبل همه چیز را در مورد type hints می‌دانید, به فصل بعدی بروید.

2023-12-09 18:45 UTC, erfan-rfmhr requested changes

2024-01-29 17:58 UTC, tiangolo commented
As this PR had requested changes to be applied but has been inactive for a while, it's now going to be closed. But if there's anyone interested, feel free to create a new PR.

2024-01-29 17:58 UTC, closed without merging