🌐 Add Russian translation for docs/ru/docs/tutorial/debugging.md
fastapi/fastapi pull request #9579
Opened 2023-05-27 17:03 UTC by Alexandrhub

2023-05-28 09:41 UTC, ivan-abc commented on docs/ru/docs/tutorial/debugging.md
> +* "Add configuration...".
* Перейдите на панель "Debug".
* Выберите "Add configuration...".

2023-05-28 10:01 UTC, ivan-abc approved these changes

2023-05-28 10:13 UTC, Alexandrhub commented on docs/ru/docs/tutorial/debugging.md
> +* Выбрать файл для отладки (в данном случае, `main.py`).
Оставил 2 строчки как и в оригинале, чтобы текст не поехал(если обьеденять их по смыслу, то можно так пол документации переделать)

2023-05-28 16:01 UTC, Xewus requested changes

2023-05-28 16:01 UTC, Xewus commented on docs/ru/docs/tutorial/debugging.md
> +Так как вы запускаете сервер Uvicorn напрямую из вашего кода, вы можете вызвать Python программу (ваше FastAPI приложение) напрямую из отладчика.
Просто меньше повторений одно и того же слова.

2023-05-28 16:11 UTC, Alexandrhub commented on docs/ru/docs/tutorial/debugging.md
> +Тогда, часть кода:
Я конечно согласен что так может и лучше звучит, но в оригигинале например "So, the line"
Понимаю что нет предела совершенства :)

2023-05-28 16:31 UTC, Scorpionchiques approved these changes

2023-05-28 18:14 UTC, Xewus approved these changes

2023-06-03 12:44 UTC, tiangolo commented
Nice, thank you @Alexandrhub! 🚀 

And thanks for the reviews @Scorpionchiques, @ivan-abc, @Xewus ☕ 🙇

2023-06-03 14:05 UTC, merged