🌐 Add Russian translation for docs/ru/docs/tutorial/static-files.md
fastapi/fastapi pull request #9580
Opened 2023-05-27 19:24 UTC by Alexandrhub

2023-05-28 16:30 UTC, Scorpionchiques approved these changes

2023-05-28 16:30 UTC, Scorpionchiques approved these changes

2023-05-28 16:43 UTC, Xewus requested changes

2023-05-28 16:43 UTC, Xewus commented on docs/ru/docs/tutorial/static-files.md
> +* "Монтируйте (.mount)" экземпляр `StaticFiles()` в определенной директории.
```suggestion
* "Примонтируйте" экземпляр `StaticFiles()` с указанием определенной директории.
```
Полагаю английское слово тут не нужно, "монтировать" (диски, папки) - устоявшийся термин.
В данном случае, конечно, это о приложении, но суть та же.

2023-05-28 16:43 UTC, Xewus commented on docs/ru/docs/tutorial/static-files.md
> +    **FastAPI** предоставляет те же `starlette.staticfiles`, что и `fastapi.staticfiles`, просто для вашего удобства, как разработчика. Но на самом деле это берётся напрямую из библиотеки Starlette.
```suggestion
    **FastAPI** предоставляет `starlette.staticfiles` под псевдонимом `fastapi.staticfiles`, просто для вашего удобства, как разработчика. Но на самом деле это берётся напрямую из библиотеки Starlette.
```

2023-05-28 16:43 UTC, Xewus commented on docs/ru/docs/tutorial/static-files.md
> +### Что такое "Mounting"
```suggestion
### Что такое "Монтирование"
```
Причины указаны выше.

2023-05-28 16:43 UTC, Xewus commented on docs/ru/docs/tutorial/static-files.md
> +"Mounting" означает добавление полноценного "независимого" приложения в определенную директорию, которое затем обрабатывает все подпути.
```suggestion
"Монтирование" означает добавление полноценного "независимого" приложения в определенную директорию, которое затем обрабатывает все подпути.
```
См. выше.


---
Может вместо "подпути" получится придумать что-то понятнее...
Да и в принципе, насколько помню, если не указывать дополнительные настройки, маршрут будет не вложенным, а такой же, как и у всех остальных функций: `domain/static`, так что может стоит написать просто - "путь" или "маршрут", несмотря на оригинал.

2023-05-28 16:43 UTC, Xewus commented on docs/ru/docs/tutorial/static-files.md
> +Это отличается от использования `APIRouter`, так как монтированное приложение является полностью независимым.
```suggestion
Это отличается от использования `APIRouter`, так как примонтированное приложение является полностью независимым.
```

2023-05-28 16:43 UTC, Xewus commented on docs/ru/docs/tutorial/static-files.md
> +OpenAPI и документация из вашего главного приложения не будет содержать ничего из монтированного приложения, и т.д.
```suggestion
OpenAPI и документация из вашего главного приложения не будет содержать ничего из примонтированного приложения, и т.д.
```

2023-05-28 16:43 UTC, Xewus commented on docs/ru/docs/tutorial/static-files.md
> +Первый `"/static"` относится к подпути, на котором это "подприложение" будет "монтированно". Таким образом, любой путь начинающийся с `"/static"` будет обработан приложением.
```suggestion
Первый параметр `"/static"` относится к подпути, по которому это "подприложение" будет "примонтировано". Таким образом, любой путь начинающийся с `"/static"` будет обработан этим приложением.
```
Соображения по поводу "подпуть" указаны выше. К тому же уже здесь, в одном предложении, и "путь" и "подпуть".

2023-05-28 16:43 UTC, Xewus commented on docs/ru/docs/tutorial/static-files.md
> +`name="static"` даёт имя, которое может быть использовано внутри **FastAPI**.
```suggestion
`name="static"` даёт имя маршруту, которое может быть использовано внутри **FastAPI**.
```

2023-05-28 16:48 UTC, Xewus commented on docs/ru/docs/tutorial/static-files.md
> +Для дополнительной информации и параметров<a href="https://www.starlette.io/staticfiles/" class="external-link" target="_blank">Документация Starlette о статических файлах</a>.
```suggestion
Для получения дополнительной информации о деталях и настройках ознакомьтесь с<a href="https://www.starlette.io/staticfiles/" class="external-link" target="_blank">Документацией Starlette о статических файлах</a>.
```

2023-05-28 16:58 UTC, Alexandrhub commented on docs/ru/docs/tutorial/static-files.md
> +Первый `"/static"` относится к подпути, на котором это "подприложение" будет "монтированно". Таким образом, любой путь начинающийся с `"/static"` будет обработан приложением.
Потому что в оригинале разделяют путь и подпуть, поэтому я и не стал исправлять смысл, лично я не уверен насчет вашего комментария насчет  вложенности маршрута( зачем тогда в оригинале написаны path и sub-path)
В общем спорно, смысл не теряется, хоть слово и может кому-то резать слух...

2023-05-28 18:15 UTC, Xewus approved these changes

2023-05-28 19:18 UTC, ivan-abc approved these changes

2023-06-03 12:19 UTC, tiangolo commented
Nice, thanks @Alexandrhub! 🍰 

And thanks for the reviews @Scorpionchiques, @ivan-abc, and @Xewus ☕ 👏

2023-06-03 14:18 UTC, merged