🌐 Add Russian translation for docs/tutorial/query-params.md
fastapi/fastapi pull request #9584
Opened 2023-05-28 16:14 UTC by Alexandrhub

2023-05-28 16:30 UTC, Scorpionchiques approved these changes

2023-05-28 17:00 UTC, d-ovs approved these changes

2023-05-28 18:00 UTC, Xewus requested changes

2023-05-28 18:00 UTC, Xewus commented on docs/ru/docs/tutorial/query-params.md
> +Но когда вы обьявляете их с помощью Python типизации (в примере выше, как `int`), они конвертируются в этот тип данных и проходят проверку на соответствие ему.
```suggestion
Но когда вы объявляете их с использованием аннотаций (в примере выше, как `int`), они конвертируются в указанный тип данных и проходят проверку на соответствие ему.
```

2023-05-28 18:00 UTC, Xewus commented on docs/ru/docs/tutorial/query-params.md
> +* Поддержка среды разработки (очевидно)
```suggestion
* Поддержка от редактора кода (очевидно)
```
Такой термин применён уже во всех страницах перевода.

2023-05-28 18:00 UTC, Xewus commented on docs/ru/docs/tutorial/query-params.md
> +Поскольку параметры запроса ("Query") не являются фиксированной частью пути, они могут быть не обязательными и иметь значения по умолчанию.
```suggestion
Поскольку query-параметры не являются фиксированной частью пути, они могут быть не обязательными и иметь значения по умолчанию.
```
Вообще под термином "Запрос"  в контексте Python-фреймворков обычно подразумевается глобальный объект `Request`, у которого есть свои параметры.
В более же общем смысле, это всё содержимое начина с букв GET (или иной метод) и заканчивая последним отправленным символом.

2023-05-28 18:00 UTC, Xewus commented on docs/ru/docs/tutorial/query-params.md
> +будет таким же, если перейти используя параметры по умолчанию:
```suggestion
будет таким же, как если перейти используя параметры по умолчанию:
```

2023-05-28 18:00 UTC, Xewus commented on docs/ru/docs/tutorial/query-params.md
> +Аналогично, вы можете обьявлять необязательные параметры запроса, установив их значение по умолчанию, равное `None`:
```suggestion
Аналогично, вы можете объявлять необязательные query-параметры, установив их значение по умолчанию, равное `None`:
```

2023-05-28 18:00 UTC, Xewus commented on docs/ru/docs/tutorial/query-params.md
> +    Также обратите внимание, что **FastAPI** достаточно умён чтобы заметить, что параметр `item_id` является параметром пути, а `q` нет, поэтому, это параметр запроса.
```suggestion
    Также обратите внимание, что **FastAPI** достаточно умён чтобы заметить, что параметр `item_id` является path-параметром, а `q` нет, поэтому, это параметр запроса.
```

2023-05-28 18:00 UTC, Xewus commented on docs/ru/docs/tutorial/query-params.md
> +Вы также можете обьявлять `bool` тип данных, которые будут преобразованы:
```suggestion
Вы также можете объявлять параметры с типом `bool`, которые будут преобразованы соответственно:
```

2023-05-28 18:00 UTC, Xewus commented on docs/ru/docs/tutorial/query-params.md
> +или в любом другом варианте написания (в верхнем регистре, с заглавной буквой, и т.п), внутри вашей функции параметр `short` будет `bool` типа данных, со значением равным`True`. В противном случае -
```suggestion
или в любом другом варианте написания (в верхнем регистре, с заглавной буквой, и т.п), внутри вашей функции параметр `short` будет иметь значение `True` типа данных `bool` . В противном случае - `False`.
```

2023-05-28 18:00 UTC, Xewus commented on docs/ru/docs/tutorial/query-params.md
> +## Множество параметров пути и запроса
```suggestion
## Смешивание query-параметров и path-параметров
```

2023-05-28 18:00 UTC, Xewus commented on docs/ru/docs/tutorial/query-params.md
> +Они будут определены по имени:
```suggestion
Они будут обнаружены по именам:
```

2023-05-28 18:00 UTC, Xewus commented on docs/ru/docs/tutorial/query-params.md
> +Но если вы хотите сделать параметр запроса обязательным, вы можете не указывать значение по умолчанию:
```suggestion
Но если вы хотите сделать query-параметр обязательным, вы можете просто не указывать значение по умолчанию:
```

2023-05-28 18:00 UTC, Xewus commented on docs/ru/docs/tutorial/query-params.md
> +* `needy`, обязательный `str`.
```suggestion
* `needy`, обязательный, с типом `str`.
```

2023-05-28 18:00 UTC, Xewus commented on docs/ru/docs/tutorial/query-params.md
> +* `skip`, типа `int` со значением по умолчанию `0`.
```suggestion
* `skip`, типа `int` и со значением по умолчанию `0`.
```

2023-05-28 18:00 UTC, Xewus commented on docs/ru/docs/tutorial/query-params.md
> +* `limit`, необязательный `int`.
```suggestion
* `limit`, типа `int` и необязательный.
```

2023-05-28 18:00 UTC, Xewus commented on docs/ru/docs/tutorial/query-params.md
> +!!! подсказка
```suggestion
!!! Подсказка
```

2023-05-28 18:00 UTC, Xewus commented on docs/ru/docs/tutorial/query-params.md
> +    Вы также можете использовать тип `Enum` в том же формате, что и с [Path Parameters](path-params.md#predefined-values){.internal-link target=_blank}.
```suggestion
    Вы можете использовать класс `Enum` также, как ранее применяли его с [Path-параметрами](path-params.md#predefined-values){.internal-link target=_blank}.
```

2023-05-28 18:03 UTC, Alexandrhub commented on docs/ru/docs/tutorial/query-params.md
> +* `needy`, обязательный `str`.
будет масло масляное 3 раза повтор типа, хотя и так понятно что тут идет перечисление типов(собственно в оригинале тут нет упоминания типа, поэтому я и пропустил)

2023-05-28 18:04 UTC, Alexandrhub commented on docs/ru/docs/tutorial/query-params.md
> +* `limit`, необязательный `int`.
Обьяснил выше.

2023-05-28 18:05 UTC, Alexandrhub commented on docs/ru/docs/tutorial/query-params.md
> +!!! подсказка
Нет разницы с большой или маленькой, идет обработка и на выход получается одно и тоже(специально проверял, оставил как в оригинале на всякий случай с маленькой)

2023-05-28 18:16 UTC, Xewus approved these changes

2023-06-03 12:14 UTC, tiangolo commented
Thanks @Alexandrhub! 🚀 

And thanks for the reviews @Scorpionchiques, @d-ovs, and @Xewus 🍰

2023-06-03 14:05 UTC, merged