Fix APIKeyCookie to accept websocket
fastapi/fastapi pull request #9591
Opened 2023-05-30 10:18 UTC by elysium31

2023-05-31 08:11 UTC, Kludex commented on fastapi/security/api_key.py
> -    async def __call__(self, request: Request) -> Optional[str]:
Can't you use `HTTPConnection` instead?

2024-02-22 15:37 UTC, YuriiMotov requested changes
I think it's quite useful PR.

I will be ready to approve it after the author makes the small corrections that I mentioned in the review.

I would also think about making the same with `APIKeyQuery`. Code is almost identical.

And.. I think adding the description to this PR will increase chances that it will be accepted soon!

2024-02-22 15:48 UTC, Kludex requested changes

2024-02-22 15:48 UTC, Kludex commented on fastapi/security/api_key.py
> +        api_key = (request or websocket).cookies.get(self.model.name)
```suggestion
    async def __call__(self, conn: HTTPConnection) -> Optional[str]:
        api_key = conn.cookies.get(self.model.name)
```

2024-02-23 08:03 UTC, YuriiMotov commented
Just found [PR 10147](https://github.com/tiangolo/fastapi/pull/10147) which also fixes this issue, but that PR is wider since it also fixes the same problem in other security tools.
I think we should close this PR and work on [PR 10147](https://github.com/tiangolo/fastapi/pull/10147)

2025-06-17 11:21 UTC, tiangolo commented
Thanks all! I'll go with @YuriiMotov's suggestion and will close this one in favor of https://github.com/fastapi/fastapi/pull/10147

Thanks for the effort! :coffee:

2025-06-17 11:21 UTC, closed without merging