🌐 Add Russian translation for docs/tutorial/body-nested-models.md
fastapi/fastapi pull request #9605
Opened 2023-06-01 20:15 UTC by Alexandrhub

2023-06-04 18:13 UTC, ivan-abc approved these changes

2023-06-04 18:13 UTC, ivan-abc commented on docs/ru/docs/tutorial/body-nested-models.md
> +В этом случае, вы принимаете `dict`, пока у него есть ключи типа `int` со значениями типа `float`:
Вообще мне кажется, что чем меньше запятых - тем лучше. Во многих случаях запятые по правилам не ставятся. Частый пример - выражение "в таком случае", после которого обычно нет запятой. Просто тогда предложения выглядят менее перегруженными и их легче читать :))

2023-06-04 18:13 UTC, ivan-abc commented on docs/ru/docs/tutorial/body-nested-models.md
> +* Автоматическая генерация документации
```suggestion
Но вместе со всеми преимуществами вы получаете:

* Поддержку редактора (автодополнение доступно везде!)
* Преобразование данных (также известно как парсинг / сериализация)
* Валидацию данных
* Документацию схемы данных
* Автоматическую генерацию документации
```

2023-06-11 08:09 UTC, Xewus requested changes

2023-06-11 08:09 UTC, Xewus commented on docs/ru/docs/tutorial/body-nested-models.md
> +## Тела запросов произвольных `dict`-ов
```suggestion
## Тела запросов с произвольными словарями (`dict` )
```

2023-06-11 08:09 UTC, Xewus commented on docs/ru/docs/tutorial/body-nested-models.md
> +Но вместе со всеми преимуществами вы получаете:
```suggestion
И дополнительно вы получаете:
```

2023-06-11 10:03 UTC, tiangolo commented
📝 Docs preview for commit 978645ad69a779253ae85150e826f95cda538b6b at: https://64859bc6691fdf7b33a038c7--fastapi.netlify.app

2023-06-11 10:42 UTC, tiangolo commented
📝 Docs preview for commit 7fcfeaf0f78598cc589eef20bd3c3cb4dcf466fb at: https://6485a4d9691fdf7f84a03806--fastapi.netlify.app

2023-06-11 10:50 UTC, tiangolo commented
📝 Docs preview for commit 4b4d95868c698602f6fb684d619f8917fa154e18 at: https://6485a6c32c003b7b6dbeaea7--fastapi.netlify.app

2023-06-11 11:04 UTC, Xewus approved these changes

2023-06-22 11:46 UTC, tiangolo commented
Awesome, thank you @Alexandrhub! 🍰 

And thanks for the reviews @ivan-abc and @Xewus 🙇

2023-06-22 11:46 UTC, merged