🌐 Add Russian translation for `docs/tutorial/cors.md`
fastapi/fastapi pull request #9608
Opened 2023-06-02 16:57 UTC by ivan-abc

2023-06-03 09:56 UTC, Alexandrhub commented on docs/ru/docs/tutorial/cors.md
> +В качестве списка источников можно указать подстановочный символ `"*"` ("wildcard"), чтобы обозначить все источники как разрешённые.
```suggestion
Также можно объявить список как подстановочный символ `"*"` ("wildcard"), чтобы обозначить все источники как разрешённые.
```

2023-06-03 09:57 UTC, Alexandrhub commented on docs/ru/docs/tutorial/cors.md
> +Но тогда не будут разрешены некоторые виды взаимодействия, включая всё связанное с учётными данными: куки, заголовки Authorization с Bearer-токенами наподобие тех, которые мы использовали ранее и т.п
```suggestion
Но тогда не будут разрешены некоторые виды взаимодействия, включая всё связанное с учётными данными: куки, заголовки Authorization с Bearer-токенами наподобие тех, которые мы использовали ранее и т.п.
```

2023-06-03 10:03 UTC, Alexandrhub commented on docs/ru/docs/tutorial/cors.md
> +Вы также можете разрешить вашему бэкенду использовать:
```suggestion
Вы также можете указать, разрешает ли ваш бэкенд использование :
```

2023-06-03 10:04 UTC, Alexandrhub commented on docs/ru/docs/tutorial/cors.md
> +Вы также можете разрешить вашему бэкенду использовать:
Если исправлять это, то перечисление дальше, тоже( Учётных данных вместо Учётные и тд.)

2023-06-03 10:11 UTC, Alexandrhub commented on docs/ru/docs/tutorial/cors.md
> +`CORSMiddleware` использует для параметров "запрещающие" значения по умолчанию, поэтому вам нужно явным образом разрешить использование отдельных источников, методов или заголовков, чтобы браузеры мо
```suggestion
Изначальные параметры, используемые реализацией `CORSMiddleware`, ограничены по умолчанию, поэтому вам нужно явным образом разрешить использование отдельных источников, методов или заголовков, чтобы браузеры могли использовать их в кросс-доменном контексте.
```

2023-06-03 10:14 UTC, Alexandrhub commented on docs/ru/docs/tutorial/cors.md
> +### Предварительные (preflight) CORS-запросы
```suggestion
### CORS-запросы с предварительной проверкой
```

2023-06-03 10:16 UTC, Alexandrhub approved these changes

2023-06-04 17:06 UTC, ivan-abc commented on docs/ru/docs/tutorial/cors.md
> +В качестве списка источников можно указать подстановочный символ `"*"` ("wildcard"), чтобы обозначить все источники как разрешённые.
Второй вариант ближе к оригиналу, но мне кажется первый звучит естественнее 🤔

2023-06-04 17:08 UTC, ivan-abc commented on docs/ru/docs/tutorial/cors.md
> +Но тогда не будут разрешены некоторые виды взаимодействия, включая всё связанное с учётными данными: куки, заголовки Authorization с Bearer-токенами наподобие тех, которые мы использовали ранее и т.п
Да, тут мне показалось сначала что "не будут разрешены" и "включая" звучит более явно, чем "будут разрешены" и "исключая". Но похоже второй вариант действительно лучше и к тому же ближе к оригиналу

2023-06-04 17:11 UTC, ivan-abc commented on docs/ru/docs/tutorial/cors.md
> +`CORSMiddleware` использует для параметров "запрещающие" значения по умолчанию, поэтому вам нужно явным образом разрешить использование отдельных источников, методов или заголовков, чтобы браузеры мо
Тут я не знаю, как лучше перевести "restrictive". Но, по-моему, "ограничены" не совсем понятно звучит

2023-06-05 15:42 UTC, Alexandrhub approved these changes

2023-06-11 08:26 UTC, Xewus requested changes
Excellent!

2023-06-11 08:26 UTC, Xewus commented on docs/ru/docs/tutorial/cors.md
> +Источник - это совокупность протокола (`http`, `https`), домена (`myapp.com`, `localhost`, `localhost.tiangolo.com`), и порта (`80`, `443`, `8080`).
```suggestion
Источник - это совокупность протокола (`http`, `https`), домена (`myapp.com`, `localhost`, `localhost.tiangolo.com`),и порта (`80`, `443`, `8080`).
```

2023-06-11 08:26 UTC, Xewus commented on docs/ru/docs/tutorial/cors.md
> +В качестве списка источников можно указать подстановочный символ `"*"` ("wildcard"), чтобы обозначить все источники как разрешённые.
```suggestion
В качестве списка источников можно указать подстановочный символ `"*"` ("wildcard"), чтобы разрешить любые источники.
```

2023-06-11 08:28 UTC, Xewus approved these changes

2023-06-11 16:32 UTC, tiangolo commented
📝 Docs preview for commit eab785e079f727cc68de08c293185d31c60adf79 at: https://6485f6f18c6c522c16e5bb57--fastapi.netlify.app

2023-06-11 17:00 UTC, tiangolo commented
📝 Docs preview for commit 2578b7d87f55745b6dd47661264483b41e30aa36 at: https://6485fd9ead38cc31941d3e97--fastapi.netlify.app

2023-06-22 14:29 UTC, tiangolo commented
Thank you @ivan-abc! 🚀 

And thanks for the reviews @Xewus  and @Alexandrhub 🙇

2023-06-22 14:29 UTC, merged