Add Persian translation for docs/fa/docs/advanced/sub-applications.md
fastapi/fastapi pull request #9692
Opened 2023-06-17 12:35 UTC by mojtabapaso

I made a directory for the advanced section.
I translated and placed the sub-applications.md file inside it

2023-06-17 12:40 UTC, tiangolo commented
📝 Docs preview for commit 6226e5433e7a429d89c9e475d87bc17f1e96c6c4 at: https://648da98878649d03c1a5bd47--fastapi.netlify.app

2023-06-22 17:22 UTC, aminalaee reviewed
Looks really good, just some minor comments.

2023-06-22 17:22 UTC, aminalaee commented on docs/fa/docs/advanced/sub-applications.md
> +# برنامه فرعی - نصب
دلیل خاصی داره کلمه «برنامه اصلی» رو انتخاب کردی؟ کلمه «زیربرنامه» ترجمه دقیق تری نیست؟

2023-06-22 17:22 UTC, aminalaee commented on docs/fa/docs/advanced/sub-applications.md
> +حالا اجرا کنید `uvicorn` با نام فایل در این مثال `main.py` و نام برنامه و خواهد بود :
```suggestion
حالا ‘uvicorn’ را برای برنامه اصلی اجرا کنید، برای مثال اگر فایل شما`main.py` هست:
```

2023-06-22 17:40 UTC, tiangolo commented
📝 Docs preview for commit 14550db6a4e5ee1b1c072a05f04dbde17b6e66f6 at: https://64948757c0798e57b6bd8e37--fastapi.netlify.app

2023-06-22 17:55 UTC, mojtabapaso reviewed
A better translation for the word Sub Applications

2023-06-22 17:56 UTC, tiangolo commented
📝 Docs preview for commit ebd5eb5a1e62fad8ccecd1608e58521c05feed0d at: https://64948b3595eb4000865e04a4--fastapi.netlify.app

2023-06-22 17:59 UTC, mojtabapaso commented on docs/fa/docs/advanced/sub-applications.md
> +# برنامه فرعی - نصب
بله نظر شما درست تر است و آن را تغییر دادم.
ممنون از توجهات به این مطلب

2023-06-22 18:19 UTC, aminalaee approved these changes
LGTM 👍

2023-06-22 20:11 UTC, heysaeid reviewed
According to the comment I made, not all words should be translated in the technical content, because they reduce the meaning, readability and understanding, but it was good overall. Thankful

2023-06-22 20:11 UTC, heysaeid commented on docs/fa/docs/advanced/sub-applications.md
> +عملیات مسیر اعلام شده در آن زیر برنامه، رسیدگی می کند.
به نظرم تو ترجمه مطالب تکنیکال نباید تمام کلمات به فارسی ترجمه بشن چون معنی, خوانایی و درک جمله رو پایین میارن, برای مثال تو این قسمت استفاده از path operations به جای "عملیات مسیر" هم معنی بهتری داره و هم خواناتر هستش یا اینکه استفاده کلمه sub-application بهتر از کلمه "زیر برنامه" هستش, برای عنوان هم فکر میکنم اینجا کلمه اتصال بهتر از نصب باشه

2023-06-22 21:08 UTC, aminalaee commented on docs/fa/docs/advanced/sub-applications.md
> +عملیات مسیر اعلام شده در آن زیر برنامه، رسیدگی می کند.
I agree with the suggestion, but there’s a limit that you need to draw the line.
For example you are right that “path operations” should not be translated, but we can translate sub-application as we already have a good translation for application.

2023-06-23 06:35 UTC, tiangolo commented
📝 Docs preview for commit 402960b92f3857886c68a248aa580f2154dc7b33 at: https://64953d22f52eb444e494bdf9--fastapi.netlify.app

2023-06-23 08:13 UTC, heysaeid requested changes
Some suggestions to improve the translation, also the code blocks are not displayed
You can check in the following link:
https://64953d22f52eb444e494bdf9--fastapi.netlify.app/fa/advanced/sub-applications/

2023-06-23 08:13 UTC, heysaeid commented on docs/fa/docs/advanced/sub-applications.md
> +حالا ‘uvicorn’ را برای برنامه اصلی اجرا کنید، برای مثال اگر فایل شما`main.py` هست:
برنامه را با استفاده از uvicorn اجرا کنید، اگر فایل شما main.py نام دارد، دستور زیر را وارد کنید

همچنین تو ترجمه ای که انجام دادی یک space برای main.py جا افتاده 😃

2023-06-23 08:13 UTC, heysaeid commented on docs/fa/docs/advanced/sub-applications.md
> +آدرس <a href="http://127.0.0.1:8000/docs" class="external-link" target="_blank">http://127.0.0.1:8000/docs</a>
صفحه مستندات را در آدرس http://127.0.0.1:8000/docs باز کنید.

2023-06-23 08:13 UTC, heysaeid commented on docs/fa/docs/advanced/sub-applications.md
> +اسناد API خودکار برنامه اصلی را مشاهده خواهید کرد که فقط شامل عملیات مسیر خود می شود:
خب الان مشاهده میکنید که اسناد API خودکار برنامه اصلی فقط شامل path operations خود میباشد

این ترجمه و ترجمه بالا باید تو دو خط جدا باشند

2023-06-23 08:13 UTC, heysaeid commented on docs/fa/docs/advanced/sub-applications.md
> +هنگامی که یک زیر برنامه را همانطور که در بالا توضیح داده شد متصل می کنید,FastAPI با استفاده از مکانیزمی از مشخصات ASGI به نام `root_path` ارتباط مسیر mount را برای زیر برنامه انجام می دهد.
فاصله ها خوب رعایت نشدن

2023-06-23 08:54 UTC, tiangolo commented
📝 Docs preview for commit b7572cc1870e4450d33e3eb4c16c61e3822a1290 at: https://64955d89e032e50b82130ef4--fastapi.netlify.app

2023-06-23 09:47 UTC, heysaeid requested changes
The code blocks are not correct (I think because of space it is), that's why nothing is loaded, they should be corrected

You can see it in the following link:
https://64955d89e032e50b82130ef4--fastapi.netlify.app/fa/advanced/sub-applications/

2023-06-23 09:47 UTC, heysaeid commented on docs/fa/docs/advanced/sub-applications.md
> +{!../../../ docs_src / sub_applications / tutorial001.py!}
{!../../../docs_src/sub_applications/tutorial001.py!}
باید اصلاح بشه

2023-06-23 09:47 UTC, heysaeid commented on docs/fa/docs/advanced/sub-applications.md
> +```Python hl_lines="11  14-16"
{!../../../docs_src/sub_applications/tutorial001.py!}
باید اصلاح بشه

2023-06-23 09:47 UTC, heysaeid commented on docs/fa/docs/advanced/sub-applications.md
> +```Python hl_lines="11  19"
{!../../../docs_src/sub_applications/tutorial001.py!}
باید اصلاح بشه

2023-06-23 12:35 UTC, tiangolo commented
📝 Docs preview for commit 22bcb1432660f0ab35ba0f8eadc069fbd4196efe at: https://64959158be371e2b9e7b689e--fastapi.netlify.app

2023-06-23 12:49 UTC, heysaeid approved these changes
LGTM 😉

2023-06-27 00:47 UTC, tiangolo commented
📝 Docs preview for commit cad7ac6151c9ddf1402644cc597a09d3d0e88607 at: https://649a316c443f2f2085861512--fastapi.netlify.app

2023-06-27 01:01 UTC, tiangolo commented
Great, thank you @mojtabapaso! 🎉 

And thanks for the reviews @aminalaee and @heysaeid 🙇 ☕

2023-06-27 01:02 UTC, merged