Allow using dependables with functools.partial()
fastapi/fastapi pull request #9753
Opened 2023-06-27 07:05 UTC by lieryan

Discussion: https://github.com/tiangolo/fastapi/discussions/9744

Using `functools.partial()` with dependables feels like a very obvious idiom. `partial()` already works for dependables that are plain function, but it doesn't work consistently, partial of async and callable classes didn't work consistently.

This PR makes partial() work consistently in all combinations.

test_dependency_class.py have been renamed to test_dependency_types.py to reflect its bigger scope now.

There's quite a bit of repetition in the tests, part of me wants to just refactor those; but another part of me also wants to keep the tests simple.

2024-02-23 10:01 UTC, Lemminkyinen commented
This would be nice to have

2024-03-10 20:26 UTC, jtfidje commented
Yeah - I also just hit this! Please merge 😅

2024-07-23 07:34 UTC, jtfidje commented
@tiangolo Are we any closer to a merge on this? 🙂

2025-02-06 06:04 UTC, pachewise commented
@lieryan could you resolve conflicts for this to be ready to merge?

2025-06-25 06:52 UTC, YuriiMotov commented
@lieryan, thanks for contributing to FastAPI!

Are you still interested in getting this PR merged?
I think it would be better to move new tests to separate file (e.g. `test_dependencies_partial.py`) to make it easier to review.
Also, I would add second parameters to all initial functions, so that partial would reduce the number of parameters from 2 to 1.
Would you like to make these changes? Or, don't you mind if I make these changes?

2025-07-08 16:14 UTC, YuriiMotov commented on fastapi/dependencies/utils.py
> +        return is_coroutine_callable(call.func)
```suggestion
    if inspect.isclass(call):
        return False
    if isinstance(call, partial):
        return is_coroutine_callable(call.func)
```
Why do we need to remove this condition (`isclass`)?
I just tried running tests with these lines and it still works.
I think if it's not necessary for making partial work, we shouldn't remove this lines in this PR

2025-07-08 16:31 UTC, YuriiMotov requested changes
There is a problem when we use named parameters to `prtial`.

Currently it produces wrong schema:
```python
from functools import partial

from fastapi import Depends, FastAPI

app = FastAPI()

async def dep1(n: int):
    return n + 1

@app.get("/")
def main(d1=Depends(partial(dep1, n=10))):  # But `partial(dep1, 10)` works fine
    return d1
```

![image](https://github.com/user-attachments/assets/fddcd64e-0f49-4dde-9916-49158aa63e64)

`n` Query parameter still appears in schema and even works (you can pass value and it will be used as input parameter).
I expected it shouldn't appear in the schema and wouldn't be used as input

2025-07-10 15:30 UTC, YuriiMotov commented
@lieryan, thanks for your work on this!

Do you have any ideas how to fix the problem I mentioned above?

2025-07-24 23:27 UTC, ruitcatarino commented
> There is a problem when we use named parameters to `prtial`.
> 
> 
> 
> Currently it produces wrong schema:
> 
> ```python
> 
> from functools import partial
> 
> 
> 
> from fastapi import Depends, FastAPI
> 
> 
> 
> app = FastAPI()
> 
> 
> 
> async def dep1(n: int):
> 
>     return n + 1
> 
> 
> 
> @app.get("/")
> 
> def main(d1=Depends(partial(dep1, n=10))):  # But `partial(dep1, 10)` works fine
> 
>     return d1
> 
> ```
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/fddcd64e-0f49-4dde-9916-49158aa63e64)
> 
> 
> 
> `n` Query parameter still appears in schema and even works (you can pass value and it will be used as input parameter).
> 
> I expected it shouldn't appear in the schema and wouldn't be used as input


Hi, today I ran into the same issue that resulted in this pull request, not being able to use `functools.partial` as a dependency. I eventually found this pull request and this issue. I did a little digging and the conclusion that I reached is that this has to do with how `functools.partial` works and positional vs keyword arguments.

```python
import inspect

from functools import partial

def add_one(num: int) -> int:
    return num + 1

two = partial(add_one, 1)
two_kwarg = partial(add_one, num=1)


inspect.signature(add_one) # <Signature (num: int) -> int>
inspect.signature(add_one).parameters.values() # odict_values([<Parameter "num: int">])

inspect.signature(two) # <Signature () -> int>
inspect.signature(two).parameters.values() # odict_values([])

inspect.signature(two_kwarg) # <Signature (*, num: int = 1) -> int>
inspect.signature(two_kwarg).parameters.values() # odict_values([<Parameter "num: int = 1">])
```

For this reason when `get_typed_signature` (from fastapi code) is called we will get diferente results depending on how we used `functools.partial`.

> `n` Query parameter still appears in schema and even works (you can pass value and it will be used as input parameter).

As for this, this works when using keyword arguments with `functools.partial` because:

> Return a new partial object which when called will behave like func called with the positional arguments args and keyword arguments keywords. If more arguments are supplied to the call, they are appended to args. If additional keyword arguments are supplied, they extend and override keywords.

https://docs.python.org/3/library/functools.html#functools.partial

Thinking on the example above calling `two_kwarg(num=3)` would still return `4` since the keyword argument `num` would get overridden.

2025-07-25 07:01 UTC, YuriiMotov commented
> As for this, this works when using keyword arguments with `functools.partial` because:
> 
> > Return a new partial object which when called will behave like func called with the positional arguments args and keyword arguments keywords. If more arguments are supplied to the call, they are appended to args. If additional keyword arguments are supplied, they extend and override keywords.
> 
> https://docs.python.org/3/library/functools.html#functools.partial

@ruitcatarino, thanks for explaining this!

So, then we can (we should) just mention this pitfall somewhere in docs.
We can probably skip this for now and add a section in docs named "What you can use inside `Depends`" later on

2025-07-25 07:16 UTC, YuriiMotov approved these changes
LGTM in general

There are 2 things to think about:
* I don't understand why the `if inspect.isclass(call):` condition was removed [here](https://github.com/fastapi/fastapi/pull/9753/files#r2192922090). Although, tests pass regardless of this condition.
* There is an [issue](https://github.com/fastapi/fastapi/pull/9753#pullrequestreview-2998359406) when `partial` is used with named parameters, but this is just how `partial` works. I think we can later explain this in docs

@lieryan, @ruitcatarino, thanks a lot!

2025-07-25 08:04 UTC, ruitcatarino commented
You're welcome, glad it helped!

I would also suggest adding some tests using keyword arguments and partial since they have different behaviours.

Even maybe validate that if you're using partial and positional sending the query param won't affect the output but using keyword arguments and partial will.

2025-07-27 07:28 UTC, YuriiMotov commented
@ruitcatarino, I personally don't think we need more tests here.
Let's wait for Sebastian to review this and if this is accepted, we will add docs (probably as a separate PR).

2025-11-05 10:00 UTC, YuriiMotov commented on fastapi/dependencies/models.py
>              return False
In the initial version of this PR it was suggested to change these lines to something like:
```diff
-        if inspect.isroutine(use_call):
-            return inspect.iscoroutinefunction(use_call)
+        if inspect.iscoroutinefunction(use_call):
+            return True
-        if inspect.isclass(use_call):
-            return False
```

See original commit: https://github.com/fastapi/fastapi/pull/9753/commits/f16dd38b478c0a88ae4ae79fd73094fdb3ffa425

I updated it to be closer to current implementation (don't simplify first condition and don't remove `if inspect.isclass(use_call):`)

2025-12-02 20:57 UTC, tiangolo approved these changes
Thank you @lieryan! 🚀 

Sorry for the delay getting back to this.

Thanks all for the discussion, thanks @YuriiMotov for the help. ☕ 

This will be available in FastAPI 0.123.5, released in the next few hours. 🎉

2025-12-02 20:58 UTC, merged

2025-12-03 07:26 UTC, wu-clan commented
> > As for this, this works when using keyword arguments with `functools.partial` because:
> > > Return a new partial object which when called will behave like func called with the positional arguments args and keyword arguments keywords. If more arguments are supplied to the call, they are appended to args. If additional keyword arguments are supplied, they extend and override keywords.
> > 
> > 
> > https://docs.python.org/3/library/functools.html#functools.partial
> 
> @ruitcatarino, thanks for explaining this!
> 
> So, then we can (we should) just mention this pitfall somewhere in docs. We can probably skip this for now and add a section in docs named "What you can use inside `Depends`" later on

I used this feature in the new feature today and discovered this issue. Can we find a way to exclude it from the schema? I think it's a distraction for the schema because Swagger display them.