🌐 Add Russian translation for `docs/tutorial/request-forms.md`
fastapi/fastapi pull request #9841
Opened 2023-07-09 10:51 UTC by dedkot01

Здесь представлен перевод страницы [Form Data](https://fastapi.tiangolo.com/tutorial/request-forms/) на русский язык.

2023-07-09 10:55 UTC, tiangolo commented
📝 Docs preview for commit c0cf997e161b13bb4cb3efd5dd2a1d6745a1e475 at: https://64aa920c4dd25f16cfc77087--fastapi.netlify.app

2023-07-19 22:15 UTC, Tiazen commented on docs/ru/docs/tutorial/request-forms.md
Рекомендуется использовать версию с `Annotated` если возможно. Может лучше написать "Рекомендуется использовать 'Annotated' версию, если это возможно. или По возможности, используйте 'Annotated' версию

2023-07-23 05:05 UTC, Xewus requested changes

2023-07-23 05:05 UTC, Xewus commented on docs/ru/docs/tutorial/request-forms.md
> +!!! warning "Внимание"
```suggestion
!!! warning "Предупреждение"
```

2023-07-23 05:05 UTC, Xewus commented on docs/ru/docs/tutorial/request-forms.md
> +    Вы можете объявлять несколько параметров `Form` в *операции пути*, но вы не можете также объявлять поля `Body`, которые вы ожидаете получить в виде JSON, так как запрос будет иметь тело, закодиро
```suggestion
    Вы можете объявлять несколько параметров `Form` в *операции пути*, но вы не можете одновременно с этим объявлять поля `Body`, которые вы ожидаете получить в виде JSON, так как запрос будет иметь тело, закодированное с использованием `application/x-www-form-urlencoded`, а не `application/json`.
```

2023-07-23 12:33 UTC, dedkot01 commented on docs/ru/docs/tutorial/request-forms.md
Ориентировался на уже существующие версии перевода данного сообщения:
https://fastapi.tiangolo.com/ru/tutorial/query-params-str-validations/#_2
https://fastapi.tiangolo.com/ru/tutorial/path-params-numeric-validations/#__tabbed_1_4

Учитывая, что есть ещё и второй вариант:
https://fastapi.tiangolo.com/ru/tutorial/body-multiple-params/#__tabbed_1_4

Вариант "Рекомендуется использовать 'Annotated' версию, если это возможно" мне нравится больше.

2023-07-23 12:46 UTC, dedkot01 commented on docs/ru/docs/tutorial/request-forms.md
> +Например, в одном из способов использования спецификации OAuth2 (называемом "потоком пароля") требуется отправить `username` и `password` в виде полей формы.
Согласен, тоже не встречался с данным термином, и при поиске не нашёл достаточно информации по этому поводу на ру источниках. Но далее в документации этот термин ещё используется:
https://fastapi.tiangolo.com/tutorial/security/first-steps/#the-password-flow

Может как-то всё же указать этот термин? Может оставить не переведённым `password flow`?

Оригинал предложения:
For example, in one of the ways the OAuth2 specification can be used (called "password flow") it is required to send a username and password as form fields.

2023-07-23 12:49 UTC, dedkot01 commented on docs/ru/docs/tutorial/request-forms.md
> +Спецификация требует, чтобы поля назывались точно `username` и `password` и отправлялись в виде полей формы, а не JSON.
Тогда думаю стоит взять "не JSON" в скобки:

Данный способ требует отправку данных для авторизации посредством формы (а не JSON) и обязательного наличия в форме строго именованных полей  `username` и `password`.

2023-07-23 12:58 UTC, dedkot01 commented on docs/ru/docs/tutorial/request-forms.md
> +!!! warning "Внимание"
Уже используется данный перевод в следующих страницах:
https://fastapi.tiangolo.com/ru/tutorial/body-fields/
https://fastapi.tiangolo.com/ru/tutorial/path-operation-configuration/

Хотя нашёл и "предупреждение":
https://fastapi.tiangolo.com/ru/tutorial/extra-models/

Но всё же, "предупреждение" пожалуй более верный вариант.

2023-07-25 10:12 UTC, tiangolo commented
📝 Docs preview for commit 32546d52842567e983c584416a3c08150b5343a6 at: https://64bf9fd74157ce4df7fd5ca6--fastapi.netlify.app

2023-07-25 10:19 UTC, Xewus approved these changes

2023-07-25 10:24 UTC, Tiazen approved these changes

2023-07-27 18:47 UTC, tiangolo commented
Great, thanks @dedkot01! 🚀 

And thanks for the reviews @Tiazen and @Xewus! 🍰

2023-07-27 18:47 UTC, merged