feat: add contributing spanish section
fastapi/fastapi pull request #9879
Opened 2023-07-14 02:51 UTC by VicenteMerino

Translation of contributing section for spanish language

2023-07-14 02:55 UTC, tiangolo commented
📝 Docs preview for commit 639b3d9db4aa0f5a96992c662712e064e54b5edf at: https://64b0b913d03a707382b3daf6--fastapi.netlify.app

2023-07-19 08:35 UTC, jfunez approved these changes

2023-07-21 16:16 UTC, setejera requested changes
Pequeño error con un elemento a tag, linea 265

2023-07-21 16:16 UTC, setejera commented on docs/es/docs/contributing.md
> +* Revisa las < href="https://github.com/tiangolo/fastapi/discussions/categories/translations" class="external-link" target="_blank">GitHub Discussions</a> para coordinar las traducciones para tu idio
Hola! En el a tag falta la a en el de apertura

2024-01-15 16:11 UTC, tiangolo commented
As this PR had requested changes to be applied but has been inactive for a while, it's now going to be closed. But if there's anyone interested, feel free to create a new PR.

2024-01-15 16:11 UTC, closed without merging