🌐 Add Russian translation for 'docs/ru/docs/tutorial/security/index.md'
fastapi/fastapi pull request #9963
Opened 2023-07-28 17:03 UTC by eVery1337

2023-07-28 17:07 UTC, tiangolo commented
📝 Docs preview for commit ba4fd494c75e6deb1f9ea1e8da29b4fcf12daca9 at: https://64c3f5ae73d5542927455717--fastapi.netlify.app

2023-07-29 07:12 UTC, dedkot01 requested changes
Добавил пару технических исправлений, в остальном перевод хороший👍

2023-07-29 07:12 UTC, dedkot01 commented on docs/ru/docs/tutorial/security/index.md
> +!!! Подсказка
```suggestion
!!! tip "Подсказка"
```

2023-07-29 07:12 UTC, dedkot01 commented on docs/ru/docs/tutorial/security/index.md
> +Fast API предоставляет несколько инструментов для каждой из этих схем безопасности в модуле "fastapi.security", которые упрощают использование этих механизмов безопасности.
```suggestion
Fast API предоставляет несколько инструментов для каждой из этих схем безопасности в модуле `fastapi.security`, которые упрощают использование этих механизмов безопасности.
```

2023-07-29 08:09 UTC, tiangolo commented
📝 Docs preview for commit 6baf1a7c7ff2cf9b462ef8f47b08b6892bc244a8 at: https://64c4c917457ce74d1a868bf7--fastapi.netlify.app

2023-07-29 08:13 UTC, dedkot01 approved these changes

2023-07-30 17:04 UTC, FraneCaleta approved these changes

2023-07-31 06:07 UTC, Xewus requested changes
В целом хорошо и творчески, но всё же хотелось бы уточнения термина "Безопасность". Безопасно ли разворачивать приложение на 1 ядре 1 ГБ RAM? Безопасно ли размещать приложение в AWS или Яндекс.Облаке?
Эти вопросы содержат терми "безопасность", но на них нет ответов в этом разделе, потму что этот раздел про аутентификации.

2023-07-31 06:07 UTC, Xewus commented on docs/ru/docs/tutorial/security/index.md
> +Он просто расширяет OAuth2, указывая некоторые вещи, которые относительно неоднозначны в OAuth2, чтобы попытаться сделать его более совместимым.
```suggestion
Он просто расширяет OAuth2, уточняя некоторые вещи, не имеющие  однозначного определения в OAuth2, в  попытке сделать его более совместимым.
```

2023-07-31 06:07 UTC, Xewus commented on docs/ru/docs/tutorial/security/index.md
> +OpenAPI может использовать следующие схемы безопасности:
```suggestion
OpenAPI может использовать следующие схемы обеспечения доступа к приложению:
```

2023-07-31 06:07 UTC, Xewus commented on docs/ru/docs/tutorial/security/index.md
> +* `oauth2`: все способы обеспечения безопасности OAuth2 (называемые "flows").
Хотелось бы услышать комментарии сообщества по термину "flows", не вспоминается широкого использования сего в ру-сегменте...

2023-07-31 06:09 UTC, Xewus commented
И хорошо, что указали ссылку на оригинал! Как раньше не приходило такое в голову...

2023-07-31 07:08 UTC, eVery1337 commented
> В целом хорошо и творчески, но всё же хотелось бы уточнения термина "Безопасность". Безопасно ли разворачивать приложение на 1 ядре и 1 ГБ RAM? Безопасно ли размещать приложение в AWS или Яндекс.Облаке? Эти вопросы содержат термин "безопасность", но на них нет ответов в этом разделе, потому что этот раздел про аутентификации.

Согласен, что термин безопасность не в полной мере отражает содержание раздела. В таком случае предлагаю поменять его на "Настройка авторизации" или "Настройка аутентификации". Термин "авторизация" в ру сегменте ассоциируется больше с действиями залогиниться куда-либо. Например, при переводе на русский слова "Authorization" первым на ум идет англицизм. Да и глазами будет легче найти.

2023-07-31 10:22 UTC, Xewus commented
> > В целом хорошо и творчески, но всё же хотелось бы уточнения термина "Безопасность". Безопасно ли разворачивать приложение на 1 ядре и 1 ГБ RAM? Безопасно ли размещать приложение в AWS или Яндекс.Облаке? Эти вопросы содержат термин "безопасность", но на них нет ответов в этом разделе, потому что этот раздел про аутентификации.
> 
> Согласен, что термин безопасность не в полной мере отражает содержание раздела. В таком случае предлагаю поменять его на "Настройка авторизации" или "Настройка аутентификации". Термин "авторизация" в ру сегменте ассоциируется больше с действиями залогиниться куда-либо. Например, при переводе на русский слова "Authorization" первым на ум идет англицизм. Да и глазами будет легче найти.
> 
> Для термина "flow" также было найдено перевода, отражающего смысл понятия на русский, но в данном случае нет и англицизма, поэтому решено было оставить английское слово. Изучаю сейчас этот момент подробнее. Существуют ресурсы как без прямого перевода, так и с ним на слово "поток" и с последним все же источников больше. Предлагаю все переписать на потоки, но при первом упоминании оставить уточнение в скобках.

Смотрел замечательные лекции по ОС, там профессор тоже замечает, что тяжело с терминами. Особенно  с "потоком". В английском 3 разных слова для разных сущностей.

2023-07-31 11:40 UTC, tiangolo commented
📝 Docs preview for commit 3ec5c09eb5b417ca832d6fd2d8d502b502cd1269 at: https://64c79d6bf0a2c3083ea401bf--fastapi.netlify.app

2023-07-31 11:47 UTC, tiangolo commented
📝 Docs preview for commit 8d23b40d1cfaa210314eed424b25f2c019303f14 at: https://64c79f29fb63e108e288f7d8--fastapi.netlify.app

2023-07-31 11:50 UTC, Xewus approved these changes

2023-07-31 18:21 UTC, dudyaosuplayer approved these changes

2023-08-02 15:14 UTC, merged