🌐 Add Russian translation for docs/tutorial/global-dependencies.md
fastapi/fastapi pull request #9970
Opened 2023-07-30 18:21 UTC by dudyaosuplayer

Original(https://fastapi.tiangolo.com/ru/tutorial/dependencies/global-dependencies/)

2023-07-30 18:26 UTC, tiangolo commented
📝 Docs preview for commit e4c7c154ed82d52280f210b2dc92685e7ea611d3 at: https://64c6ab1123a9c32821205a9a--fastapi.netlify.app

2023-07-30 22:16 UTC, eVery1337 commented on docs/ru/docs/tutorial/dependencies/global-dependencies.md
> +Позднее, читая о том как структурировать большие приложения([Bigger Applications - Multiple Files](../../tutorial/bigger-applications.md){.internal-link target=_blank}), состоящие из большого количес
```suggestion
Позднее, читая о том как структурировать большие приложения([Масштабирование приложений - структура множества файлов](../../tutorial/bigger-applications.md){.internal-link target=_blank}), состоящие из большого количества файлов, вы узнаете как объявить один параметр `dependencies` для целой группы *путевых операций*.
```

2023-07-30 22:28 UTC, eVery1337 approved these changes
Перевод отличный!
Одно момент связанный с локализацией названия ссылки. На нее перевода на данный момент нет, но когда-то он появится. Название будет примерно такое.

2023-07-30 22:28 UTC, eVery1337 commented on docs/ru/docs/tutorial/dependencies/global-dependencies.md
> +Позднее, читая о том как структурировать большие приложения([Bigger Applications - Multiple Files](../../tutorial/bigger-applications.md){.internal-link target=_blank}), состоящие из большого количес
```suggestion
Позднее, читая о том как структурировать большие приложения([Масштабирование приложений - структура множества файлов](../../tutorial/bigger-applications.md){.internal-link target=_blank}), состоящие из большого количества файлов, вы узнаете как объявить один параметр `dependencies` для целой группы *путевых операций*.
```

2023-07-31 05:16 UTC, Xewus commented
В заголовке принято указывать полный путь к файлу - docs/tutorial/депендс/global-dependencies.md.

2023-07-31 09:12 UTC, dedkot01 approved these changes

2023-07-31 09:40 UTC, dudyaosuplayer commented on docs/ru/docs/tutorial/dependencies/global-dependencies.md
> +Позднее, читая о том как структурировать большие приложения([Bigger Applications - Multiple Files](../../tutorial/bigger-applications.md){.internal-link target=_blank}), состоящие из большого количес
Может тогда не "Масштабирование приложений - структура множества файлов", а "Масштабирование приложений - многофайловая структура"?

2023-07-31 09:48 UTC, eVery1337 commented on docs/ru/docs/tutorial/dependencies/global-dependencies.md
> +Позднее, читая о том как структурировать большие приложения([Bigger Applications - Multiple Files](../../tutorial/bigger-applications.md){.internal-link target=_blank}), состоящие из большого количес
Да, отлично.

2023-07-31 09:59 UTC, tiangolo commented
📝 Docs preview for commit a43c3eca731fdd06cf1c7b068122d108082f25c7 at: https://64c785e742477c0ebc6723b6--fastapi.netlify.app

2023-07-31 10:07 UTC, dedkot01 requested changes
Думаю, следует заменить термин "путевые операции" на "операции пути", так как ранее в переводе принималась такая формулировка:
https://fastapi.tiangolo.com/ru/tutorial/path-operation-configuration/#_1
https://fastapi.tiangolo.com/ru/tutorial/first-steps/#3-path-operation
https://fastapi.tiangolo.com/ru/tutorial/response-model/#-

2023-07-31 10:07 UTC, dedkot01 commented on docs/ru/docs/tutorial/dependencies/global-dependencies.md
> +Подобно тому, как вы можете [добавлять `dependencies` к *декораторам путевых операций*](dependencies-in-path-operation-decorators.md){.internal-link target=_blank}, вы можете добавить их через прилож
```suggestion
Подобно тому, как вы можете [добавлять `dependencies` к *декораторам операции пути*](dependencies-in-path-operation-decorators.md){.internal-link target=_blank}, вы можете добавлять их в `FastAPI` приложении.
```
Уже ранее встречался перевод данного термина как "операция пути", например здесь:
https://fastapi.tiangolo.com/ru/tutorial/path-operation-configuration/#_1

2023-07-31 10:07 UTC, dedkot01 commented on docs/ru/docs/tutorial/dependencies/global-dependencies.md
> +В этом случае они будут применяться ко всем *путевым операциям* в приложении:
```suggestion
В этом случае они будут применяться ко всем *операциям пути* в приложении:
```

2023-07-31 10:07 UTC, dedkot01 commented on docs/ru/docs/tutorial/dependencies/global-dependencies.md
> +Все способы [добавления `dependencies` к *декораторам путевых операций*](dependencies-in-path-operation-decorators.md){.internal-link target=_blank} по-прежнему применимы, но в данном случае зависимо
```suggestion
Все способы [добавления `dependencies` к *декораторам операции пути*](dependencies-in-path-operation-decorators.md){.internal-link target=_blank} по-прежнему применимы, но в данном случае зависимости применяются ко всем *операциям пути* приложения.
```

2023-07-31 10:07 UTC, dedkot01 commented on docs/ru/docs/tutorial/dependencies/global-dependencies.md
> +## Зависимости для групп *путевых операций*
```suggestion
## Зависимости для групп *операций пути*
```

2023-07-31 10:07 UTC, dedkot01 commented on docs/ru/docs/tutorial/dependencies/global-dependencies.md
> +Позднее, читая о том как структурировать большие приложения ([Масштабирование приложений - многофайловая структура](../../tutorial/bigger-applications.md){.internal-link target=_blank}), состоящие из
```suggestion
Позднее, читая о том как структурировать большие приложения ([Масштабирование приложений - многофайловая структура](../../tutorial/bigger-applications.md){.internal-link target=_blank}), состоящие из большого количества файлов, вы узнаете как объявить один параметр `dependencies` для целой группы *операций пути*.
```

2023-07-31 13:15 UTC, tiangolo commented
📝 Docs preview for commit 93de28090649c9ac7d469ff6fe1f9de127b841d2 at: https://64c7b3b1ba910415f9934ad9--fastapi.netlify.app

2023-07-31 17:55 UTC, dedkot01 approved these changes

2023-07-31 20:22 UTC, Xewus commented
Парни, блядь, прекращайте бездумно апрувить, прочтите сначала текст. Не нужно позорить русский язык.

2023-08-01 05:17 UTC, dedkot01 commented
> Парни, блядь, прекращайте бездумно апрувить, прочтите сначала текст. Не нужно позорить русский язык.

Позор русского языка вижу сейчас только в Вашем сообщении.

Вижу, что человек проработал все запрошенные у него изменения, где тут бездумно? Бездумно оставить комментарий "Всё плохо" не указав на то, что плохо (не говорю уже о том, чтобы предложить исправления).

Просто оставлю это здесь. @Xewus , советую прочитать 3 и 4 абзац на досуге:
https://fastapi.tiangolo.com/ru/help-fastapi/#github_1

2023-08-01 07:52 UTC, Xewus commented
> > Парни, блядь, прекращайте бездумно апрувить, прочтите сначала текст. Не нужно позорить русский язык.
> 
> Позор русского языка вижу сейчас только в Вашем сообщении.
> 
> Вижу, что человек проработал все запрошенные у него изменения, где тут бездумно? Бездумно оставить комментарий "Всё плохо" не указав на то, что плохо (не говорю уже о том, чтобы предложить исправления).
> 
> Просто оставлю это здесь. @Xewus , советую прочитать 3 и 4 абзац на досуге: https://fastapi.tiangolo.com/ru/help-fastapi/#github_1



> > Парни, блядь, прекращайте бездумно апрувить, прочтите сначала текст. Не нужно позорить русский язык.
> 
> Позор русского языка вижу сейчас только в Вашем сообщении.
> 
> Вижу, что человек проработал все запрошенные у него изменения, где тут бездумно? Бездумно оставить комментарий "Всё плохо" не указав на то, что плохо (не говорю уже о том, чтобы предложить исправления).
> 
> Просто оставлю это здесь. @Xewus , советую прочитать 3 и 4 абзац на досуге: https://fastapi.tiangolo.com/ru/help-fastapi/#github_1
---

> добавлять dependencies 

Было указано, что термин не переведён. И если с `flow`есть, что обсуждать, то термины "зависимости" и "внедрение зависимостей" существуют и широко известны.

>  можете добавлять их в FastAPI приложении.

А до этого их где добавляли? В Караганде? Указание на это тоже было.

> Масштабирование приложений - многофайловая структура

На это тоже было указание, причём с аргументом про содержание той страницы, раз уж сам переводчик не удосужился просмотреть её. Более того, когда второй раз было написано так же, был задан конкретный вопрос - "Как вы пришли к такому варианту".

Так что Ваши обвинения явно беспочвенны и лишь дополнительно подтверждают, что Вы не изволили ознакомиться с предметом дискуссии.

---

Страница, которую Вы прикрепили в конце, мне прекрасно известна и аргументы, которые Вы могли бы оттуда использовать, относятся, например, к заголовку, в котором второе слово с заглавной буквы или к пропущенным запятым (на них тоже было указано, хотя я и не знаток пунктуации), но никак не к искажению смысла.

---

Одно дело, если вы желаете условно "поделиться знаниями, нести свет" (я надеюсь, что большинство людей всё-таки придерживается этого), и другое дело набивать коммиты, засовывая страницу в гугло-переводчик и выкладывая итог сюда.

2023-08-01 08:10 UTC, dudyaosuplayer commented
> > > Парни, блядь, прекращайте бездумно апрувить, прочтите сначала текст. Не нужно позорить русский язык.
> > 
> > 
> > Позор русского языка вижу сейчас только в Вашем сообщении.
> > Вижу, что человек проработал все запрошенные у него изменения, где тут бездумно? Бездумно оставить комментарий "Всё плохо" не указав на то, что плохо (не говорю уже о том, чтобы предложить исправления).
> > Просто оставлю это здесь. @Xewus , советую прочитать 3 и 4 абзац на досуге: https://fastapi.tiangolo.com/ru/help-fastapi/#github_1
> 
> > > Парни, блядь, прекращайте бездумно апрувить, прочтите сначала текст. Не нужно позорить русский язык.
> > 
> > 
> > Позор русского языка вижу сейчас только в Вашем сообщении.
> > Вижу, что человек проработал все запрошенные у него изменения, где тут бездумно? Бездумно оставить комментарий "Всё плохо" не указав на то, что плохо (не говорю уже о том, чтобы предложить исправления).
> > Просто оставлю это здесь. @Xewus , советую прочитать 3 и 4 абзац на досуге: https://fastapi.tiangolo.com/ru/help-fastapi/#github_1
> 
> > добавлять dependencies
> 
> Было указано, что термин не переведён. И если с `flow`есть, что обсуждать, то термины "зависимости" и "внедрение зависимостей" существуют и широко известны.
> 
> > можете добавлять их в FastAPI приложении.
> 
> А до этого их где добавляли? В Караганде? Указание на это тоже было.
> 
> > Масштабирование приложений - многофайловая структура
> 
> На это тоже было указание, причём с аргументом про содержание той страницы, раз уж сам переводчик не удосужился просмотреть её. Более того, когда второй раз было написано так же, был задан конкретный вопрос - "Как вы пришли к такому варианту".
> 
> Так что Ваши обвинения явно беспочвенны и лишь дополнительно подтверждают, что Вы не изволили ознакомиться с предметом дискуссии.
> 
> Страница, которую Вы прикрепили в конце, мне прекрасно известна и аргументы, которые Вы могли бы оттуда использовать, относятся, например, к заголовку, в котором второе слово с заглавной буквы или к пропущенным запятым (на них тоже было указано, хотя я и не знаток пунктуации), но никак не к искажению смысла.
> 
> Одно дело, если вы желаете условно "поделиться знаниями, нести свет" (я надеюсь, что большинство людей всё-таки придерживается этого), и другое дело набивать коммиты, засовывая страницу в гугло-переводчик и выкладывая итог сюда.

Вы можете просто написать, что вам конкретно не нравится и предложить варианты исправления. 
Про dependencies: я подумал, что это слово в тексте указывает на название параметра.
Про "Масштабирование приложений". Из вашего сообщения непонятно, что конкретно нуждается в исправлении.

2023-08-01 08:46 UTC, eVery1337 commented
> > > Парни, блядь, прекращайте бездумно апрувить, прочтите сначала текст. Не нужно позорить русский язык.
> > 
> > 
> > Позор русского языка вижу сейчас только в Вашем сообщении.
> > Вижу, что человек проработал все запрошенные у него изменения, где тут бездумно? Бездумно оставить комментарий "Всё плохо" не указав на то, что плохо (не говорю уже о том, чтобы предложить исправления).
> > Просто оставлю это здесь. @Xewus , советую прочитать 3 и 4 абзац на досуге: https://fastapi.tiangolo.com/ru/help-fastapi/#github_1
> 
> > > Парни, блядь, прекращайте бездумно апрувить, прочтите сначала текст. Не нужно позорить русский язык.
> > 
> > 
> > Позор русского языка вижу сейчас только в Вашем сообщении.
> > Вижу, что человек проработал все запрошенные у него изменения, где тут бездумно? Бездумно оставить комментарий "Всё плохо" не указав на то, что плохо (не говорю уже о том, чтобы предложить исправления).
> > Просто оставлю это здесь. @Xewus , советую прочитать 3 и 4 абзац на досуге: https://fastapi.tiangolo.com/ru/help-fastapi/#github_1
> 
> > добавлять dependencies
> 
> Было указано, что термин не переведён. И если с `flow`есть, что обсуждать, то термины "зависимости" и "внедрение зависимостей" существуют и широко известны.
> 
> > можете добавлять их в FastAPI приложении.
> 
> А до этого их где добавляли? В Караганде? Указание на это тоже было.
> 
> > Масштабирование приложений - многофайловая структура
> 
> На это тоже было указание, причём с аргументом про содержание той страницы, раз уж сам переводчик не удосужился просмотреть её. Более того, когда второй раз было написано так же, был задан конкретный вопрос - "Как вы пришли к такому варианту".
> 
> Так что Ваши обвинения явно беспочвенны и лишь дополнительно подтверждают, что Вы не изволили ознакомиться с предметом дискуссии.
> 
> Страница, которую Вы прикрепили в конце, мне прекрасно известна и аргументы, которые Вы могли бы оттуда использовать, относятся, например, к заголовку, в котором второе слово с заглавной буквы или к пропущенным запятым (на них тоже было указано, хотя я и не знаток пунктуации), но никак не к искажению смысла.
> 
> Одно дело, если вы желаете условно "поделиться знаниями, нести свет" (я надеюсь, что большинство людей всё-таки придерживается этого), и другое дело набивать коммиты, засовывая страницу в гугло-переводчик и выкладывая итог сюда.

Я один не вижу ни одного указания о котором говорит @Xewus ?

2023-08-01 09:07 UTC, Xewus commented
> Я один не вижу ни одного указания о которых говорит @Xewus ?


![image](https://github.com/tiangolo/fastapi/assets/85196001/c2a56d98-463f-46a5-a52b-c5e18e33b88b)

2023-08-01 09:12 UTC, Xewus commented
И безотносительно спора о правильности терминов, в которых я вполне могу быть не прав, ну что это за строка?
`Позднее, читая о том как структурировать большие приложения Масштабирование приложений - многофайловая структура, состоящие из большого количества файлов`

2023-08-01 09:13 UTC, eVery1337 commented
> > Я один не вижу ни одного указания о которых говорит @Xewus ?
> 
> ![image](https://user-images.githubusercontent.com/85196001/257463745-c2a56d98-463f-46a5-a52b-c5e18e33b88b.png)

Ваши комментарии имеют статус pending и видны только вам!

2023-08-01 09:17 UTC, eVery1337 commented
> И безотносительно спора о правильности терминов, в которых я вполне могу быть не прав, ну что это за строка? `Позднее, читая о том как структурировать большие приложения Масштабирование приложений - многофайловая структура, состоящие из большого количества файлов`

Согласен, можно убрать название этой статьи из предложения вовсе и оставить в части 'читая о том как структурировать большие приложения' гиперлинк на нее

2023-08-01 09:19 UTC, Xewus commented
> Ваши комментарии имеют статус pending и видны только вам!

Ох! Точно. Прощу прощения, посыпаю голову пеплом и всё такое. Тем не менее, претензии к более внимательному ознакомлению перед апрувом не снимаю.

2023-08-01 09:26 UTC, eVery1337 commented
> > Ваши комментарии имеют статус pending и видны только вам!
> 
> Ох! Точно. Прощу прощения, посыпаю голову пеплом и всё такое. Тем не менее, претензии к более внимательному ознакомлению перед апрувом не снимаю.

У всех разное видение на правильность каких-то моментов. Перевод с моей точки зрения был вполне логичен и понятен. dependency и правда может и стоит перевести, но при прочтении этот термин не путал и трудностей не вызывал, в принципе как и flow, посему этот пр заслужил мой апрув. Однако на то мы здесь и собрались, дабы учесть мнение каждого и получить лучший результат.

2023-08-01 09:27 UTC, Xewus commented
Хм.. Нажал "прервать", а вывалило всё сюда. Ну, что ж, будем считать следствием моей криворукости.

2023-08-01 09:31 UTC, Xewus commented
> > > Ваши комментарии имеют статус pending и видны только вам!
> > 
> > 
> > Ох! Точно. Прощу прощения, посыпаю голову пеплом и всё такое. Тем не менее, претензии к более внимательному ознакомлению перед апрувом не снимаю.
> 
> У всех разное видение на правильность каких-то моментов. Перевод с моей точки зрения был вполне логичен и понятен. dependency и правда может и стоит перевести, но при прочтении этот термин не путал и трудностей не вызывал, в принципе как и flow, посему этот пр заслужил мой апрув. Однако на то мы здесь и собрались, дабы учесть мнение каждого и получить лучший результат.

Вполне возможно, что Вы встречались с этим паттерном ранее и он для Вас понятен и так, но (по моему мнению) данная документация прекрасно подходит для новичков, которые впервые это слышат и стоит позаботится о том, что им было более понятно. Как пример -  `Про dependencies: я подумал, что это слово в тексте указывает на название параметра`.

2023-08-01 09:31 UTC, dudyaosuplayer commented
> И безотносительно спора о правильности терминов, в которых я вполне могу быть не прав, ну что это за строка? `Позднее, читая о том как структурировать большие приложения Масштабирование приложений - многофайловая структура, состоящие из большого количества файлов`

Здесь ссылка на статью про большие приложения находится в скобках, так что можно и не удалять ее. Я предлагаю такой вариант: 
Позднее, читая о том как структурировать более крупные приложения (Большие приложения - многофайловая структура), вы узнаете как объявить один параметр `dependencies` для целой группы *операций пути*.

2023-08-01 09:35 UTC, dudyaosuplayer commented on docs/ru/docs/tutorial/dependencies/global-dependencies.md
> +Все способы [добавления `dependencies` к *декораторам путевых операций*](dependencies-in-path-operation-decorators.md){.internal-link target=_blank} по-прежнему применимы, но в данном случае зависимо
> ... `dependencies`... путевых операций ...

Я считаю, что `dependencies` не стоит переводить, т.к. в оригинале это преподноситься именно как название передаваемого параметра

2023-08-01 09:45 UTC, dudyaosuplayer commented
> > > > Ваши комментарии имеют статус pending и видны только вам!
> > > 
> > > 
> > > Ох! Точно. Прощу прощения, посыпаю голову пеплом и всё такое. Тем не менее, претензии к более внимательному ознакомлению перед апрувом не снимаю.
> > 
> > 
> > У всех разное видение на правильность каких-то моментов. Перевод с моей точки зрения был вполне логичен и понятен. dependency и правда может и стоит перевести, но при прочтении этот термин не путал и трудностей не вызывал, в принципе как и flow, посему этот пр заслужил мой апрув. Однако на то мы здесь и собрались, дабы учесть мнение каждого и получить лучший результат.
> 
> Вполне возможно, что Вы встречались с этим паттерном ранее и он для Вас понятен и так, но (по моему мнению) данная документация прекрасно подходит для новичков, которые впервые это слышат и стоит позаботится о том, что им было более понятно. Как пример - `Про dependencies: я подумал, что это слово в тексте указывает на название параметра`.

Можно явно указать, что тут подразумевается именно параметр:

2023-08-01 15:17 UTC, tiangolo commented
📝 Docs preview for commit b860b41c7390929388ac75b97ebf90b4518307ab at: https://71e0f650.fastapitiangolo.pages.dev

2023-08-01 15:23 UTC, tiangolo commented
📝 Docs preview for commit a37df174f312f543a4c169a4603dbd11476036b2 at: https://2af6db02.fastapitiangolo.pages.dev

2023-08-02 03:58 UTC, Xewus commented on docs/ru/docs/tutorial/dependencies/global-dependencies.md
> +# Глобальные Зависимости
```suggestion
# Глобальные зависимости
```

2023-08-02 03:58 UTC, Xewus commented on docs/ru/docs/tutorial/dependencies/global-dependencies.md
> +Для некоторых типов приложений может потребоваться добавить зависимости ко всему приложению.
```suggestion
Иногда Вам может понадобиться добавить одинаковые зависимости ко всему приложению.
```
Это так, на усмотрение автора.

2023-08-02 03:58 UTC, Xewus commented on docs/ru/docs/tutorial/dependencies/global-dependencies.md
> +Подобно тому, как вы можете [добавлять параметр зависимостей `dependencies` к *декораторам операций пути*](dependencies-in-path-operation-decorators.md){.internal-link target=_blank}, вы можете добав
```suggestion
Подобно тому, как вы можете [добавлять зависимости через параметр `dependencies` в *декораторах операций пути*](dependencies-in-path-operation-decorators.md){.internal-link target=_blank}, вы можете добавлять зависимости сразу ко всему `FastAPI` приложению.
```
Замечу, что строчкой выше написано `ко всему приложению`, а добавление в декораторах также входит в "добавить в приложении", потому что сами декораторы в приложении.

2023-08-02 03:58 UTC, Xewus commented on docs/ru/docs/tutorial/dependencies/global-dependencies.md
> +Все способы [добавления `dependencies` к *декораторам операции пути*](dependencies-in-path-operation-decorators.md){.internal-link target=_blank} по-прежнему применимы, но в данном случае зависимости
```suggestion
Все способы [добавления `зависимостей` в *декораторах операций пути*](dependencies-in-path-operation-decorators.md){.internal-link target=_blank} по-прежнему применимы, но в данном случае зависимости применяются ко всем *операциям пути* приложения.
```

2023-08-02 03:58 UTC, Xewus commented on docs/ru/docs/tutorial/dependencies/global-dependencies.md
> +Позднее, читая о том, как структурировать более крупные приложения ([Большие приложения - многофайловая структура](../../tutorial/bigger-applications.md){.internal-link target=_blank}), вы узнаете, к
```suggestion
Позднее, читая о том, как структурировать более крупные ([Приложения содержащие много файлов](https://64c7426e71ccc66c38699754--fastapi.netlify.app/ru/tutorial/bigger-applications/),](../../tutorial/bigger-applications.md){.internal-link target=_blank}), вы узнаете, как объявить один параметр dependencies для целой группы *операций пути*.
```

2023-08-02 04:01 UTC, Xewus commented
В итоге споров больше, чем размер страницы...

2023-08-02 11:17 UTC, dudyaosuplayer commented on docs/ru/docs/tutorial/dependencies/global-dependencies.md
> +# Глобальные Зависимости
В оригинале оба слова в заголовке начинаются с заглавной.

2023-08-02 11:24 UTC, tiangolo commented
📝 Docs preview for commit 6c0086220424dfe7db517910d2090b1bedc9f3b4 at: https://9cd7cfde.fastapitiangolo.pages.dev

2023-08-02 11:42 UTC, tiangolo commented
📝 Docs preview for commit 06c4cefaeb1f1f86f060248a284967c8761b2d41 at: https://20ecb78d.fastapitiangolo.pages.dev

2023-08-02 11:49 UTC, dudyaosuplayer commented on docs/ru/docs/tutorial/dependencies/global-dependencies.md
> +Позднее, читая о том, как структурировать более крупные приложения ([Большие приложения - многофайловая структура](../../tutorial/bigger-applications.md){.internal-link target=_blank}), вы узнаете, к
Я бы оставил без изменений

2023-08-02 12:11 UTC, tiangolo commented
📝 Docs preview for commit 511b436e7e3c0ae2edca5cc522396a0f1d49a131 at: https://a5e6b75d.fastapitiangolo.pages.dev

2023-08-02 13:29 UTC, Xewus commented on docs/ru/docs/tutorial/dependencies/global-dependencies.md
> +# Глобальные Зависимости
Оригинал на английском языке. В английском языке немного другие правила.
![Снимок экрана от 2023-08-02 16-28-38](https://github.com/tiangolo/fastapi/assets/85196001/8c977728-e20a-4467-b8f6-3bcf8fe13175)

2023-08-02 13:31 UTC, Xewus commented on docs/ru/docs/tutorial/dependencies/global-dependencies.md
> +Позднее, читая о том, как структурировать более крупные приложения ([Большие приложения - многофайловая структура](../../tutorial/bigger-applications.md){.internal-link target=_blank}), вы узнаете, к
При просмотре страницы, читатель не видит скобок, то есть выглядит так:

Позднее, читая о том, как структурировать более крупные Приложения содержащие много файлов, вы узнаете, как объявить один параметр dependencies для целой группы *операций пути*

2023-08-02 15:49 UTC, dudyaosuplayer commented on docs/ru/docs/tutorial/dependencies/global-dependencies.md
> +Позднее, читая о том, как структурировать более крупные приложения ([Большие приложения - многофайловая структура](../../tutorial/bigger-applications.md){.internal-link target=_blank}), вы узнаете, к
У меня видно 
![image](https://github.com/tiangolo/fastapi/assets/62661898/454f0c20-5eb6-4dcf-a9e2-5c85ea4f0469)

2023-08-02 15:55 UTC, tiangolo commented
📝 Docs preview for commit 785fe9dd9d727e266754f4d584d941b7d811edf2 at: https://db266388.fastapitiangolo.pages.dev

2023-08-02 16:32 UTC, dedkot01 commented on docs/ru/docs/tutorial/dependencies/global-dependencies.md
> +Позднее, читая о том, как структурировать более крупные приложения ([Большие приложения - многофайловая структура](../../tutorial/bigger-applications.md){.internal-link target=_blank}), вы узнаете, к
Скобка есть, разметка MD соблюдена верна. Разница в тексте невелика.
@Xewus зачем предлагаете вставить ссылку на временный деплой доки в оригинал?

2023-08-02 16:44 UTC, Xewus commented on docs/ru/docs/tutorial/dependencies/global-dependencies.md
> +Позднее, читая о том, как структурировать более крупные приложения ([Большие приложения - многофайловая структура](../../tutorial/bigger-applications.md){.internal-link target=_blank}), вы узнаете, к
я предлагаю читаемое построение, а не конкретную ссылку

2023-08-02 21:58 UTC, dedkot01 commented on docs/ru/docs/tutorial/dependencies/global-dependencies.md
> +Позднее, читая о том, как структурировать более крупные приложения ([Большие приложения - многофайловая структура](../../tutorial/bigger-applications.md){.internal-link target=_blank}), вы узнаете, к
Вот как в результате будет выглядеть предлагаемый Вами вариант:

### Позднее, читая о том, как структурировать более крупные ([Приложения содержащие много файлов](https://64c7426e71ccc66c38699754--fastapi.netlify.app/ru/tutorial/bigger-applications/),](../../tutorial/bigger-applications.md){.internal-link target=_blank}), вы узнаете, как объявить один параметр dependencies для целой группы *операций пути*.

Навсякий случай, скриншот с raw текстом из вашего предложения:
![image](https://github.com/tiangolo/fastapi/assets/26196675/66c756fa-de41-430e-bac2-09258823a6e7)

Уже здесь видно нарушение MD разметки в виде неверно расставленных скобок. В оригинале автора они расставлены верно, выше есть скриншот https://github.com/tiangolo/fastapi/pull/9970#discussion_r1282100391.

Дальше, уберу ссылки, чтобы не мешали представлению, исправлю оплошность со скобкой:

### Позднее, читая о том, как структурировать более крупные (Приложения содержащие много файлов), вы узнаете, как объявить один параметр dependencies для целой группы *операций пути*.

Скриншот с raw текстом:
![image](https://github.com/tiangolo/fastapi/assets/26196675/c74ea078-0d50-4075-a911-4d00e2fd92e0)

Как известно, если убрать слова в скобках из предложения, смысл предложения от этого не изменится. Уберём скобки из Вашего предложения:

### Позднее, читая о том, как структурировать более крупные, вы узнаете, как объявить один параметр dependencies для целой группы *операций пути*.

## ...как структурировать более крупные, вы узнаете, как объявить один параметр dependencies...

# ...более крупные, вы узнаете...

Более крупные... кого? Где в Вашем предложении 'читаемое построение'? Оно обрывается. Может когда Вы писали, то закладывали какое-то дельное предложение, но, в результате Вашей невнимательности, его не предоставили. Я против данного изменения, оно нарушает правило русского языка "Без существительного, нет прилагательного".

Во вторых, Ваше утверждение 'я предлагаю читаемое построение, а не конкретную ссылку' ложное. Здесь ярко зелёным выделено, что Вы предлагаете в качестве изменения:
![image](https://github.com/tiangolo/fastapi/assets/26196675/4a3f7523-af7e-4700-adbe-1246e6fc7339)

Повторяю свой вопрос - @Xewus зачем предлагаете вставить абсолютную ссылку на временный деплой доки в оригинал?

2023-08-03 07:40 UTC, Xewus commented on docs/ru/docs/tutorial/dependencies/global-dependencies.md
> +Позднее, читая о том, как структурировать более крупные приложения ([Большие приложения - многофайловая структура](../../tutorial/bigger-applications.md){.internal-link target=_blank}), вы узнаете, к
Вы сильно перевозбудились, то расставляете скобки, то удаляете, то снова их расставляете, а потом удаляете то, что внутри., заявляя, что Вам широко известна такая последовательность действий. Примените лучше свои писательские таланты к качественному переводу ещё одной страницы. Я привёл конкретную строку, как она должна выглядеть для читателя.

> Позднее, читая о том, как структурировать более крупные Приложения содержащие много файлов, вы узнаете, как объявить один параметр dependencies для целой группы операций пути

здесь нет скобок.

Если же Вы  изволите требовать, чтоб я переписывал предложенный перевод, то зачем тогда автор перевода? Задача ревью - указать недостатки и предложить направление изысканий, а не требовать "вставь мою строку". Если в Вашем окружении принято последнее , могу лишь посочувствовать, хотя долгодержащаяся повышенная температура табурета не даёт Вам рассуждать разумно.

2023-08-03 08:54 UTC, tiangolo commented
📝 Docs preview for commit d978308f961e6a7d7d3d0c5471090310edddc5b4 at: https://aa5f2ef8.fastapitiangolo.pages.dev

2023-08-03 09:51 UTC, Xewus approved these changes

2023-08-03 09:54 UTC, Xewus commented
@dudyaosuplayer, если что, не переживай, обычно тут намного спокойнее.
![фф](https://github.com/tiangolo/fastapi/assets/85196001/0d1d5103-8b29-4458-bdd3-2a0784763ec4)

2023-08-05 08:25 UTC, tiangolo commented
Thanks @dudyaosuplayer! 🚀 

And thanks for the reviews and discussion @dedkot01, @eVery1337, @Xewus, I don't speak Russian but I'm glad you were able to come to an agreement 😅 ☕

2023-08-05 08:26 UTC, merged